### PR TITLE
GH-39649: [Java][CI] Fix or suppress spurious errorprone warnings stage 2

### LINKED ISSUE #39649: [Java][CI] Fix or suppress spurious errorprone warnings stage 2
### Describe the enhancement requested

This is a continuation of https://github.com/apache/arrow/issues/39330

And this is to report the warnings in the following modules. 

1. adapter
2. c
3. dataset
4. format
5. gandiva
6. maven
7. memory
8. performance

### Component(s)

Java

### PR DESCRIPTION
**Pull request by vibhatha**
### Rationale for this change

This PR is a continuation of errorprone warning fixes. 

### What changes are included in this PR?

Fixing warnings suggested by the errorpone module. 

- [x] Adapter
- [x] C
- [x] Format
- [x] Maven
- [x] Memory
- [x] Performance 

### Are these changes tested?

The existing test cases will be covering them. 

### Are there any user-facing changes?

No
* Closes: #39649

### CODE REVIEW

**Comment by vibhatha** [comment]
@github-actions crossbow submit java

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by vibhatha** [comment]
@github-actions crossbow submit java

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by vibhatha** [comment]
converting back to draft as the crossbow failure seems to be consistent 🙁

**Comment by pitrou** [comment]
What is the status on this? Do you plan to push this PR to completion @vibhatha ?

Also cc @danepitkin

**Comment by danepitkin** [comment]
@github-actions crossbow submit -g java

**Comment by vibhatha** [comment]
@github-actions crossbow submit -g java

**Comment by vibhatha** [comment]
@pitrou sorry about the delay, got side tracked by other priorities at the time. I updated the PR, re-validated locally. 
Now checking the CIs.

**Comment by vibhatha** [comment]
cc @pitrou @lidavidm CIs are passing.

File: java/adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfigTest.java [hunk 1]
```diff
@@ -89,17 +90,17 @@ public void testConfig() {
     JdbcToArrowConfigBuilder builder = new JdbcToArrowConfigBuilder(allocator, calendar);
     JdbcToArrowConfig config = builder.build();
 
-    assertTrue(allocator == config.getAllocator());
-    assertTrue(calendar == config.getCalendar());
+    assertTrue(Objects.equals(allocator, config.getAllocator()));
```
Comment (lidavidm) [inline java/adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfigTest.java:93]: assertEquals

File: java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java
Comment (lidavidm) [inline java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java:1]: These should be excluded? They're generated code.

File: java/memory/memory-core/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 2]
```diff
@@ -1077,8 +1077,6 @@ public void testMemoryLeakWithReservation() throws Exception {
           "child2", 1024, MAX_ALLOCATION);
       rootAllocator.verify();
 
-      ArrowBuf buff = childAllocator2.buffer(256);
```
Comment (lidavidm) [inline java/memory/memory-core/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1080]: Er, these have side effects. Do not delete.

**Review by lidavidm — CHANGES_REQUESTED** [review]

File: java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java
Comment (vibhatha) [reply java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java:1]: Mmm... is it? https://github.com/apache/arrow/blob/main/java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java

Some changes have been made here as well: https://github.com/apache/arrow/pull/38991
Please correct me if I am wrong.

Comment (vibhatha) [reply java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java:1]: Oh, will clean up.

Comment (lidavidm) [reply java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java:1]: We should configure errorprone to not run on this module, probably

Comment (vibhatha) [reply java/format/src/main/java/org/apache/arrow/flatbuf/Binary.java:1]: Yeah, that would be the best. I will take a look.

File: java/format/pom.xml [hunk 3]
```diff
@@ -41,6 +41,14 @@
           <skip>true</skip>
         </configuration>
       </plugin>
+      <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
+        <artifactId>maven-compiler-plugin</artifactId>
+        <version>${maven-compiler-plugin.version}</version>
+        <configuration>
+          <useIncrementalCompilation>false</useIncrementalCompilation>
```
Comment (lidavidm) [inline java/format/pom.xml:49]: I'm not sure we want to do this? We should just document the right way to do a "true" clean build.

Comment (vibhatha) [reply java/format/pom.xml:49]: Ah yes, I am still addressing the reviews. I still didn't find a better way to test this out.

Comment (vibhatha) [reply java/format/pom.xml:49]: Finally! 
```bash
mvn clean install -Ddevelocity.cache.local.enabled=false -Ddevelocity.cache.remote.enabled=false
```

Comment (lidavidm) [reply java/format/pom.xml:49]: Can we add this to the dev docs?

Comment (vibhatha) [reply java/format/pom.xml:49]: Of course I will.

Comment (vibhatha) [reply java/format/pom.xml]: Documented here.

**Comment by vibhatha** [comment]
@github-actions crossbow submit -g java

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/ChildAllocator.java [hunk 4]
```diff
@@ -26,6 +26,7 @@
  * <p>Child allocators can only be created by the root, or other children, so
  * this class is package private.</p>
  */
+@SuppressWarnings("InvalidInlineTag")
```
Comment (lidavidm) [inline java/memory/memory-core/src/main/java/org/apache/arrow/memory/ChildAllocator.java:29]: I think this can be fixed by replacing `@see` with `@link` above.

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/rounding/DefaultRoundingPolicy.java [hunk 5]
```diff
@@ -44,20 +44,16 @@ public class DefaultRoundingPolicy implements RoundingPolicy {
...
-      pageSizeFallbackCause = t;
       defaultPageSize = 8192;
     }
 
     int defaultMaxOrder = Integer.getInteger("org.apache.memory.allocator.maxOrder", 11);
-    Throwable maxOrderFallbackCause = null;
     try {
       validateAndCalculateChunkSize(defaultPageSize, defaultMaxOrder);
     } catch (Throwable t) {
-      maxOrderFallbackCause = t;
```
Comment (lidavidm) [inline java/memory/memory-core/src/main/java/org/apache/arrow/memory/rounding/DefaultRoundingPolicy.java:60]: Possibly the intent was to log them below?

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/util/HistoricalLog.java [hunk 6]
```diff
@@ -80,14 +85,15 @@ public HistoricalLog(final int limit, final String idStringFormat, Object... arg
...
+  @FormatMethod
+  public synchronized void recordEvent(@FormatString final String noteFormat, Object... args) {
     final String note = String.format(noteFormat, args);
     final Event event = new Event(note);
     if (firstEvent == null) {
       firstEvent = event;
     }
     if (history.size() == limit) {
-      history.removeFirst();
+      history.remove(0);
```
Comment (lidavidm) [inline java/memory/memory-core/src/main/java/org/apache/arrow/memory/util/HistoricalLog.java:96]: Is this good with ArrayList? Deque is probably preferable

File: java/memory/memory-core/pom.xml
Comment (lidavidm) [inline java/memory/memory-core/pom.xml:1]: why do we have to duplicate this here? (if it's necessary I just want to document why)

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/rounding/DefaultRoundingPolicy.java (hunk 5 above)
Comment (vibhatha) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/rounding/DefaultRoundingPolicy.java:60]: I see, how should we log this, any preferred practice?

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/util/HistoricalLog.java (hunk 6 above)
Comment (vibhatha) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/util/HistoricalLog.java:96]: A naive 1-1 conversion without putting that much thought. I will check this.

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/rounding/DefaultRoundingPolicy.java (hunk 5 above)
Comment (lidavidm) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/rounding/DefaultRoundingPolicy.java:60]: Hmm, we can just leave it out. Clearly nobody complained before.

File: java/memory/memory-core/pom.xml
Comment (vibhatha) [reply java/memory/memory-core/pom.xml:1]: Ah good point. I am actually not sure what is the best way to add this dependency (`error_prone_annotations`)

Comment (vibhatha) [reply java/memory/memory-core/pom.xml:1]: First, I tried to add it to the `path` section in the root pom, but it didn't work. Do you have an idea how to do that?

Comment (lidavidm) [reply java/memory/memory-core/pom.xml:1]: It's not an annotation processor, just annotations. So perhaps it should be in a `dependency` section instead?

Comment (lidavidm) [reply java/memory/memory-core/pom.xml:1]: Is this only for `@FormatString`? Do we actually need that annotation?

Comment (lidavidm) [reply java/memory/memory-core/pom.xml:1]: Right, but does ErrorProne complain if we don't use these? I guess it does? Hmm.

It doesn't work when the dependency is placed in the right section? (I'm also concerned at having different dependency versions for different Java versions. I think I'd prefer to just suppress this check for now and leave a ticket to reenable it post Java upgrade.)

Comment (vibhatha) [reply java/memory/memory-core/pom.xml:1]: Sure let me do that.

Comment (vibhatha) [reply java/memory/memory-core/pom.xml:1]: Reported here: https://github.com/apache/arrow/issues/41951

I am going to suppress the warning but add this issue with a note to fix at each location.

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/util/HistoricalLog.java (hunk 6 above)
Comment (vibhatha) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/util/HistoricalLog.java:96]: Using `ArrayDeque`

File: docs/source/developers/java/development.rst [hunk 7]
```diff
@@ -137,3 +137,14 @@ This applies the style to all pom.xml files under the current directory or from
...
+
+Error Prone
+===========
+
+In relation to code formatting and standards, ``Error Prone`` compiler analysis may use cache to avoid
+showing the warnings if attempted re-run of ``mvn clean install``. To avoid the cache to include the
+warnings, use ``mvn clean install -Ddevelocity.cache.local.enabled=false -Ddevelocity.cache.remote.enabled=false``
+instead.
+
+Also note that Error Prone must be disabled for auto generated content.
```
Comment (lidavidm) [inline docs/source/developers/java/development.rst:150]:
```suggestion
Build Caching
=============

Build caching is done through Develocity (formerly Maven Enterprise).  To force
a build without the cache, run::

    mvn clean install -Ddevelocity.cache.local.enabled=false -Ddevelocity.cache.remote.enabled=false

This can be useful to make sure you see all warnings from ErrorProne, for example.

ErrorProne
==========

ErrorProne should be disabled for generated code.
```

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
@github-actions crossbow submit -g java
