### PR TITLE
GH-40773: [Java] add `DENSEUNION` case to StructWriters, resolves #40773

### LINKED ISSUE #40773: [Java] Cannot create StructVector with dense-union child
### Describe the bug, including details regarding any error messages, version, and platform.

I cannot create a StructVector with a dense-union child - it fails with the following stack trace:

```
java.lang.UnsupportedOperationException: Unknown type: DENSEUNION
	at org.apache.arrow.vector.complex.impl.NullableStructWriter.<init>(NullableStructWriter.java:258)
	at org.apache.arrow.vector.complex.StructVector.<init>(StructVector.java:69)
	at xtdb.vector.StructVectorWriterTest.struct with DUV child(StructVectorWriterTest.kt:101)
```

Test code is essentially:

```java
Field child = new Field("child", FieldType.notNullable(new ArrowType.Union(UnionMode.Dense, null)), emptyList());
Field struct = new Field("foo", FieldType.notNullable(ArrowType.Struct.INSTANCE), List.of(child));

try(RootAllocator allocator = new RootAllocator();
   StructVector structVec = new StructVector(struct, allocator, null)) {
            
   System.out.println("working!");
}
```

I suspect it's a case of adding `DENSEUNION` to the `switch` in the `NullableStructWriter` constructor, with a similar implementation to the sparse `UNION`?

Cheers,

James

### Component(s)

Java

### PR DESCRIPTION
**Pull request by jarohen**
### What changes are included in this PR?

Adding a `DENSEUNION` case to the `StructWriters` template so that one can create StructVectors with a DenseUnionVector child.

### Are these changes tested?

Yes

### Are there any user-facing changes?

No
* GitHub Issue: #40773

### CODE REVIEW

File: java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java [hunk 1]
```diff
@@ -17,6 +17,7 @@
 
 package org.apache.arrow.vector;
 
+import static java.util.Collections.emptyList;
```
Comment (vibhatha) [inline java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java:20]: nit: would it be better to use a non-static import and use `emptyList`?

**Review by vibhatha — APPROVED** [review]
LGTM! Though I am thinking can we add more tests to this? 
cc @danepitkin

File: java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java (hunk 1 above)
Comment (jarohen) [reply java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java:20]: happy to if that's the convention, yep :slightly_smiling_face:

Comment (danepitkin) [reply java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java:20]: +1 for non-static

**Review by danepitkin — APPROVED** [review]
LGTM! I think the testing is good enough to merge

File: java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java (hunk 1 above)
Comment (jarohen) [reply java/vector/src/test/java/org/apache/arrow/vector/TestValueVector.java]: updated :slightly_smiling_face:

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
Integration failure looks to be a flake.
