### PR TITLE
GH-39865: [C++] Strip extension metadata when importing a registered extension

### LINKED ISSUE #39865: [C++] Schema C Data Interface import keeps metadata for registered extension type
### Describe the bug, including details regarding any error messages, version, and platform.

Originally found out by [Arrow Rust](https://github.com/apache/arrow-rs/issues/5354): when importing a Schema with an extension type, the extension type will keep its serialized extension metadata even if there is a corresponding registered extension.

Instead, we should strip the corresponding metadata if the extension type is known.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

When importing an extension type from the C Data Interface and the extension type is registered, we would still leave the extension-related metadata on the storage type.

### What changes are included in this PR?

Strip extension-related metadata on the storage type if we succeed in recreating the extension type.
This matches the behavior of the IPC layer and allows for more exact roundtripping.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No, unless people mistakingly rely on the presence of said metadata.
* Closes: #39865

### CODE REVIEW

File: cpp/src/arrow/c/bridge_test.cc [hunk 1]
```diff
@@ -3693,13 +3693,23 @@ TEST_F(TestSchemaRoundtrip, Dictionary) {
...
 TEST_F(TestSchemaRoundtrip, UnregisteredExtension) {
   TestWithTypeFactory(uuid, []() { return fixed_size_binary(16); });
   TestWithTypeFactory(dict_extension_type, []() { return dictionary(int8(), utf8()); });
 
   // Inside nested type
-  TestWithTypeFactory([]() { return list(dict_extension_type()); },
-                      []() { return list(dictionary(int8(), utf8())); });
+  TestWithTypeFactory(
+      []() { return list(dict_extension_type()); },
+      []() { return list(GetStorageWithMetadata("item", dict_extension_type())); });
```
Comment (bkietz) [inline cpp/src/arrow/c/bridge_test.cc:3712]: Would you mind adding a comment explaining why the nested metadata is present ?

File: cpp/src/arrow/util/key_value_metadata.cc [hunk 2]
```diff
@@ -188,7 +186,7 @@ std::vector<std::pair<std::string, std::string>> KeyValueMetadata::sorted_pairs(
   return pairs;
 }
 
-int KeyValueMetadata::FindKey(const std::string& key) const {
+int KeyValueMetadata::FindKey(std::string_view key) const {
```
Comment (bkietz) [inline cpp/src/arrow/util/key_value_metadata.cc:189]: :+1:

**Review by bkietz — APPROVED** [review]
Mostly LGTM, just one nit

**Comment by pitrou** [comment]
CI failures are unrelated, will merge.
