### PR TITLE
GH-39444: [C++][Parquet] Fix crash in Modular Encryption

### LINKED ISSUE #39444: [C++][Parquet] Segmentation fault reading modular encrypted Parquet dataset over 2^15 rows
### Describe the bug, including details regarding any error messages, version, and platform.

Version: `pyarrow==14.0.2`
Platform: `Linux 5.15.x x86_64 GNU/Linux`

I have been trying out the new capability introduced in Arrow 14 which allows modular encryption of Parquet files to be used alongside the generic Dataset API, but began to experience segmentation faults in C++ Arrow code when working with real, partitioned datasets rather than toy examples.

The error is most often segmentation fault but I have seen all of these:
```
Segmentation fault
OSError: Failed decryption finalization
OSError: Couldn't set AAD
```

After some trial and error generating larger and larger toy examples until the error was reliably hit, I discovered that the threshold was when the data which is *initially written* to the dataset on disk with modular encryption was over `2^15`. In testing, `2^15` rows never faulted, but `2^15 + 1` often faults (occasionally it does not).

The backtrace when triggering the fault or error always ends in the same function:
```
#9  0x00007f9b726625f2 in parquet::encryption::AesDecryptor::AesDecryptorImpl::GcmDecrypt(unsigned char const*, int, unsigned char const*, int, unsigned char const*, int, unsigned char*) [clone .cold] () from venv/lib/python3.10/site-packages/pyarrow/libparquet.so.1400
#10 0x00007f9b7270923e in parquet::Decryptor::Decrypt(unsigned char const*, int, unsigned char*) () from venv/lib/python3.10/site-packages/pyarrow/libparquet.so.1400
#11 0x00007f9b726f569b in void parquet::ThriftDeserializer::DeserializeMessage<parquet::format::ColumnMetaData>(unsigned char const*, unsigned int*, parquet::format::ColumnMetaData*, parquet::Decryptor*) () from venv/lib/python3.10/site-packages/pyarrow/libparquet.so.1400
#12 0x00007f9b726f8f34 in parquet::ColumnChunkMetaData::ColumnChunkMetaDataImpl::ColumnChunkMetaDataImpl(parquet::format::ColumnChunk const*, parquet::ColumnDescriptor const*, short, short, parquet::ReaderProperties const&, parquet::ApplicationVersion const*, std::shared_ptr<parquet::InternalFileDecryptor>) () from venv/lib/python3.10/site-packages/pyarrow/libparquet.so.1400
```
Corresponding to this source: https://github.com/apache/arrow/blob/main/cpp/src/parquet/encryption/encryption_internal.cc#L453

I found this previous fix in this area, the issue for which details the exact same symptoms: https://github.com/apache/arrow/commit/88bccab18a4ab818355209e45862cc52f9cf4a0d
```
However, AesDecryptor::AesDecryptorImpl::GcmDecrypt() and AesDecryptor::AesDecryptorImpl::CtrDecrypt() use ctx_ member of type EVP_CIPHER_CTX from OpenSSL, which shouldn't be used from multiple threads concurrently.
```
So I was suspicious that it could be a multi-threading issue during read or write.

Whilst attempting to narrow down the cause (and whether the root cause occurs during writing or reading), I made the following observations:
- Writing `2^15 + 1` rows, deleting half the dataset and then reading in the full dataset still encounters the error
- Writing `2^15 + 1` rows, and filtering to half the partitions in the dataset when reading still encounters the error
- Writing `2^15 + 1` rows, and decrypting with modular encryption each individual parquet file in the dataset and concatenating them never failed, only doing so as a full dataset
- Writing or reading or both with `use_threads=False` still encounters the error

The fact that the issue still occurs when the dataset on disk is halved and then read again suggested corruption during write, but the fact that all individual Parquet files are still independently readable suggests an issue with modular decryption during Dataset operations. Issue still occurring with threading disabled was unexpected.

The error is reproducible using any random data, and using a KMS client which actually does no encryption at all (eliminating our custom KMS client as a probable cause), but simply passes the keys used around in (encoded) plaintext. It occurs whether the footer is plaintext or not, or whether envelope encryption is used or not.

Reproduction in Python here (no partitions needed at all, so it produces a single Parquet file, which can be read normally):
```python3
import base64
import numpy as np
import tempfile

import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds
import pyarrow.parquet.encryption as pqe

class NoOpKmsClient(pqe.KmsClient):
    def __init__(self):
        super().__init__()

    def wrap_key(self, key_bytes: bytes, _: str) -> bytes:
        b = base64.b64encode(key_bytes)
        return b

    def unwrap_key(self, wrapped_key: bytes, _: str) -> bytes:
        b = base64.b64decode(wrapped_key)
        return b

row_count = pow(2, 15) + 1
table = pa.Table.from_arrays([pa.array(np.random.rand(row_count), type=pa.float32())], names=["foo"])

kms_config = pqe.KmsConnectionConfig()
crypto_factory = pqe.CryptoFactory(lambda _: NoOpKmsClient())
encryption_config = pqe.EncryptionConfiguration(
    footer_key="UNIMPORTANT_KEY",
    column_keys={"UNIMPORTANT_KEY": ["foo"]},
    double_wrapping=True,
    plaintext_footer=False,
    data_key_length_bits=128,
)
pqe_config = ds.ParquetEncryptionConfig(crypto_factory, kms_config, encryption_config)
pqd_config = ds.ParquetDecryptionConfig(crypto_factory, kms_config, pqe.DecryptionConfiguration())
scan_options = ds.ParquetFragmentScanOptions(decryption_config=pqd_config)
file_format = ds.ParquetFileFormat(default_fragment_scan_options=scan_options)
write_options = file_format.make_write_options(encryption_config=pqe_config)
file_decryption_properties = crypto_factory.file_decryption_properties(kms_config)

with tempfile.TemporaryDirectory() as tempdir:
    path = tempdir + "/test-dataset"
    ds.write_dataset(table, path, format=file_format, file_options=write_options)

    file_path = path + "/part-0.parquet"
    new_table = pq.ParquetFile(file_path, decryption_properties=file_decryption_properties).read()
    assert table == new_table

    dataset = ds.dataset(path, format=file_format)
    new_table = dataset.to_table()
    assert table == new_table
```

Any help here would be much appreciated: being restricted to `2^15` rows is a roadblock for us for the use of this feature.

### Component(s)

Parquet, Python

### PR DESCRIPTION
**Pull request by tolleybot**
**Rationale for this change:**

This pull request addresses a critical issue (GH-39444) in the C++/Python components of Parquet, specifically a segmentation fault occurring when processing encrypted datasets over 2^15 rows. The fix involves modifications in `cpp/src/parquet/encryption/internal_file_decryptor.cc`, particularly in `InternalFileDecryptor::GetColumnDecryptor`. The caching of the `Decryptor` object was removed to resolve the multithreading issue causing the segmentation fault and encryption failures.

**What changes are included in this PR?**

- Removal of `Decryptor` object caching in `InternalFileDecryptor::GetColumnDecryptor`.
- Addition of two unit tests: `large_row_parquet_encrypt_test.cc` for C++ and an update to `test_dataset_encryption.py` with `test_large_row_encryption_decryption` for Python.

**Are these changes tested?**

Yes, the unit tests (`large_row_parquet_encrypt_test.cc` and `test_large_row_encryption_decryption` in `test_dataset_encryption.py`) have been added to ensure the reliability and effectiveness of these changes.

**Are there any user-facing changes?**

No significant user-facing changes, but the update significantly improves the backend stability and reliability of Parquet file handling.  Calling DecryptionKeyRetriever::GetKey could be an expensive operation potentially involving network calls to key management servers. 

* Closes: #39444
* GitHub Issue: #39444

### CODE REVIEW

File: cpp/src/parquet/encryption/internal_file_decryptor.cc [hunk 1]
```diff
@@ -61,6 +61,7 @@ InternalFileDecryptor::InternalFileDecryptor(FileDecryptionProperties* propertie
 }
 
 void InternalFileDecryptor::WipeOutDecryptionKeys() {
+  std::lock_guard<std::mutex> lock(mutex_);
```
Comment (wgtmac) [inline cpp/src/parquet/encryption/internal_file_decryptor.cc:64]: CMIW, this is only called once in `SerializedFile::Close()` so it does not require the lock here.

File: cpp/src/parquet/encryption/internal_file_decryptor.cc [hunk 2]
```diff
@@ -138,6 +139,9 @@ std::shared_ptr<Decryptor> InternalFileDecryptor::GetFooterDecryptor(
 
   // Create both data and metadata decryptors to avoid redundant retrieval of key
   // from the key_retriever.
+
+  std::lock_guard<std::mutex> lock(mutex_);  // Lock the critical section
```
Comment (wgtmac) [inline cpp/src/parquet/encryption/internal_file_decryptor.cc:143]: Should we add a block to limit the scope of the lock from line 146 to 149 only?

File: cpp/src/parquet/encryption/internal_file_decryptor.cc [hunk 3]
```diff
@@ -200,21 +190,13 @@ std::shared_ptr<Decryptor> InternalFileDecryptor::GetColumnDecryptor(
...
-      aes_metadata_decryptor, column_key, file_aad_, aad, pool_);
-  column_data_map_[column_path] =
-      std::make_shared<Decryptor>(aes_data_decryptor, column_key, file_aad_, aad, pool_);
+  std::lock_guard<std::mutex> lock(mutex_);
+  auto aes_decryptor =
+      encryption::AesDecryptor::Make(algorithm_, key_len, metadata, &all_decryptors_);
 
-  if (metadata) return column_metadata_map_[column_path];
-  return column_data_map_[column_path];
+  return std::make_shared<Decryptor>(aes_decryptor, column_key, file_aad_, aad, pool_);
```
Comment (wgtmac) [inline cpp/src/parquet/encryption/internal_file_decryptor.cc:199]:
```suggestion
  return std::make_shared<Decryptor>(std::move(aes_decryptor), column_key, file_aad_, aad, pool_);
```

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc [hunk 4]
```diff
@@ -0,0 +1,201 @@
...
+#include <parquet/encryption/test_in_memory_kms.h>
+#include <cmath>
+#include <memory>
+#include <string_view>
+#include "gtest/gtest.h"
+
+#include <arrow/util/base64.h>
+#include <filesystem>
+
+#define ROW_COUNT 32769;
```
Comment (wgtmac) [inline cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc:44]: Please use `constexpr int kRowCount`

File: cpp/src/parquet/encryption/internal_file_decryptor.cc [hunk 5]
```diff
@@ -168,21 +172,7 @@ std::shared_ptr<Decryptor> InternalFileDecryptor::GetColumnDataDecryptor(
 std::shared_ptr<Decryptor> InternalFileDecryptor::GetColumnDecryptor(
     const std::string& column_path, const std::string& column_key_metadata,
     const std::string& aad, bool metadata) {
-  std::string column_key;
```
Comment (wgtmac) [inline cpp/src/parquet/encryption/internal_file_decryptor.cc:171]: This may introduce performance regression. But that's not my concern here due to keeping the cache in single-threaded mode may require more complicated logic.

**Review by wgtmac — CHANGES_REQUESTED** [review]
Thanks for the thorough investigation and quick fix!

cc @emkornfield @pitrou

File: python/pyarrow/tests/test_dataset_encryption.py [hunk 6]
```diff
@@ -151,3 +155,61 @@ def test_write_dataset_parquet_without_encryption():
 
     with pytest.raises(NotImplementedError):
         _ = pformat.make_write_options(encryption_config="some value")
+
+
+@pytest.mark.skipif(
+    not encryption_unavailable, reason="Parquet Encryption is currently enabled"
```
Comment (adamreeve) [inline python/pyarrow/tests/test_dataset_encryption.py:161]: Shouldn't this be skipped if encryption is unavailable rather than the other way around?
```suggestion
    encryption_unavailable, reason="Parquet Encryption is not currently enabled"
```

File: python/pyarrow/tests/test_dataset_encryption.py [hunk 7]
```diff
@@ -151,3 +155,61 @@ def test_write_dataset_parquet_without_encryption():
...
+)
+def test_large_row_encryption_decryption():
+    """Test encryption and decryption of a large row."""
```
Comment (adamreeve) [inline python/pyarrow/tests/test_dataset_encryption.py:164]:
```suggestion
    """Test encryption and decryption of a large number of rows."""
```

File: cpp/src/parquet/encryption/internal_file_decryptor.cc (hunk 5 above)
Comment (adamreeve) [reply cpp/src/parquet/encryption/internal_file_decryptor.cc:171]: Would it make sense to at least cache `column_key` though? As mentioned in the PR description, `key_retriever()->GetKey` might call out to the user's key management service and could be fairly expensive.

Comment (adamreeve) [reply cpp/src/parquet/encryption/internal_file_decryptor.cc:171]: Although if double wrapping is used, it looks like keys will be cached with `kek_per_kek_id_` in `FileKeyUnwrapper` so maybe the performance impact won't be too bad.

File: cpp/src/parquet/encryption/internal_file_decryptor.h [hunk 8]
```diff
@@ -88,11 +89,10 @@ class InternalFileDecryptor {
       const std::string& aad = "");
 
  private:
+  std::mutex mutex_;
```
[the remark this answers is not in the document]
Comment (mapleFU) [reply cpp/src/parquet/encryption/internal_file_decryptor.h:92]: I think the `mutex_` would better be `mutable`. and variable using it would better adding a `GUARDED_BY` comment

File: cpp/src/parquet/encryption/internal_file_decryptor.cc (hunk 2 above)
Comment (tolleybot) [reply cpp/src/parquet/encryption/internal_file_decryptor.cc:143]: Ok

Comment (tolleybot) [reply cpp/src/parquet/encryption/internal_file_decryptor.cc]: Done

File: cpp/src/parquet/encryption/encryption_internal.cc [hunk 9]
```diff
@@ -24,6 +24,7 @@
 #include <algorithm>
 #include <iostream>
 #include <memory>
+#include <mutex>
```
[the remark this answers is not in the document]
Comment (tolleybot) [reply cpp/src/parquet/encryption/encryption_internal.cc]: I removed it

File: cpp/src/parquet/encryption/internal_file_decryptor.cc (hunk 2 above)
Comment (tolleybot) [reply cpp/src/parquet/encryption/internal_file_decryptor.cc]: I limited the scope as suggested

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc (hunk 4 above)
Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: Done

File: cpp/src/parquet/encryption/internal_file_decryptor.cc (hunk 1 above)
Comment (tolleybot) [reply cpp/src/parquet/encryption/internal_file_decryptor.cc]: Ok, I removed it

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc [hunk 10]
```diff
@@ -0,0 +1,201 @@
...
+  NoOpKmsClientFactory() {}
+
+  std::shared_ptr<parquet::encryption::KmsClient> CreateKmsClient(
+      const parquet::encryption::KmsConnectionConfig& config) override {
+    // Return a new instance of NoOpKmsClient
+    return std::make_shared<NoOpKmsClient>();
+  }
+};
+
+class LargeRowEncryptionTest : public ::testing::Test {
```
Comment (wgtmac) [inline cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc:83]: IMO, this test can be simplified and changed to align with the coding style. Do you authorize me to refactor it a little bit?

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc [hunk 11]
```diff
@@ -0,0 +1,201 @@
...
+    EXPECT_OK_AND_ASSIGN(file_system_, fs::internal::MockFileSystem::Make(
+                                           std::chrono::system_clock::now(), {}));
+    ASSERT_OK(file_system_->CreateDir(std::string(kBaseDir)));
+
+    // Prepare table data with CreateRandomTable.
+    CreateRandomTable();
+
+    crypto_factory_ = std::make_shared<parquet::encryption::CryptoFactory>();
+
+    std::shared_ptr<parquet::encryption::KmsClientFactory> kms_client_factory =
```
Comment (wgtmac) [inline cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc:99]: Is this required, or [TestOnlyInMemoryKmsClientFactory](https://github.com/apache/arrow/blob/21ffd82c05c93b873ae3c27128eb8604ed0c735f/cpp/src/parquet/encryption/test_in_memory_kms.h#L74) is enough?

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc (hunk 10 above)
Comment (wgtmac) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc:83]: I have tried to refactor it locally with this commit: https://github.com/wgtmac/arrow/commit/93bca5b134ca664bf98853a3d420c39bb6d11005. I can verify that I get following errors occasionally:
```
/Users/gangwu/Projects/arrow/cpp/build_upstream/debug/arrow-dataset-file-parquet-encryption-test --gtest_filter=DatasetEncryptionTest.WriteReadDatasetWithEncryption:DatasetEncryptionTest/*.WriteReadDatasetWithEncryption:DatasetEncryptionTest.WriteReadDatasetWithEncryption/*:*/DatasetEncryptionTest.WriteReadDatasetWithEncryption/*:*/DatasetEncryptionTest/*.WriteReadDatasetWithEncryption:DatasetEncryptionTest.ReadSingleFile:DatasetEncryptionTest/*.ReadSingleFile:DatasetEncryptionTest.ReadSingleFile/*:*/DatasetEncryptionTest.ReadSingleFile/*:*/DatasetEncryptionTest/*.ReadSingleFile:LargeRowEncryptionTest.ReadEncryptLargeRows:LargeRowEncryptionTest/*.ReadEncryptLargeRows:LargeRowEncryptionTest.ReadEncryptLargeRows/*:*/LargeRowEncryptionTest.ReadEncryptLargeRows/*:*/LargeRowEncryptionTest/*.ReadEncryptLargeRows --gtest_color=no
Testing started at 21:32 ...
Running main() from /Users/gangwu/Projects/arrow/cpp/build_upstream/_deps/googletest-src/googletest/src/gtest_main.cc
/Users/gangwu/Projects/arrow/cpp/src/arrow/dataset/file_parquet_encryption_test.cc:154: Failure
Failed
'_error_or_value27.status()' failed with IOError: Failed decryption finalization
/Users/gangwu/Projects/arrow/cpp/src/arrow/dataset/file_parquet_encryption_test.cc:255: Failure
Expected: TestScanDataset() doesn't generate new fatal failures in the current thread.
  Actual: it does.
```

As this test case has many duplication with file_parquet_encryption_test.cc, I simply modified it to incorporate your change. The entire file can be viewed for your convenience: https://[raw.githubusercontent.com/wgtmac/arrow/93bca5b134ca664bf98853a3d420c39bb6d11005/cpp/src/arrow/dataset/file_parquet_encryption_test.cc](https://raw.githubusercontent.com/wgtmac/arrow/93bca5b134ca664bf98853a3d420c39bb6d11005/cpp/src/arrow/dataset/file_parquet_encryption_test.cc)

File: cpp/src/arrow/dataset/CMakeLists.txt [hunk 12]
```diff
@@ -180,6 +180,11 @@ if(ARROW_PARQUET)
                            file_parquet_encryption_test.cc
                            ${PROJECT_SOURCE_DIR}/src/parquet/encryption/test_in_memory_kms.cc
     )
+    add_arrow_dataset_test(large_row_parquet_encrypt_test
+                           SOURCES
+                           large_row_parquet_encrypt_test.cc
```
Comment (wgtmac) [inline cpp/src/arrow/dataset/CMakeLists.txt:185]: See my other comment, this does not have to be a separate test.

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc (hunk 10 above)
Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc:83]: Feel free to modify as you see fit.  Ill try and replicate your findings.

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc (hunk 11 above)
Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc:99]: I imagine TestOnlyMemoryKmsClientFactory is fine.

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc (hunk 10 above)
Comment (wgtmac) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: Thanks! I've pushed my local changes of test refactoring to your branch.

**Comment by wgtmac** [comment]
The C++ side looks good to me. I have also refactored the C++ tests.

Could you take a look as well? @jorisvandenbossche @westonpace @pitrou

File: cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc (hunk 10 above)
Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: I'm having issues getting the test to fail, is there anything specific you do besides just building and running it?  I tested debug and release.

Comment (wgtmac) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: `cmake .. -G "Unix Makefiles" -DARROW_PARQUET=ON -DARROW_BUILD_TESTS=ON -DARROW_WITH_ZSTD=OFF -DARROW_WITH_ZLIB=OFF -DARROW_WITH_SNAPPY=OFF -DPARQUET_REQUIRE_ENCRYPTION=ON -DARROW_BUILD_BENCHMARKS=OFF -DARROW_DATASET=ON`

That's my cmake command. No special step.

Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: Yes, I still have an issue with getting it to fail

Comment (wgtmac) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: Could you try this patch (i.e. without your fix): https://github.com/wgtmac/arrow/commit/93bca5b134ca664bf98853a3d420c39bb6d11005 ?

Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: Will do

Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: sorry for delay.  I pulled the patch and these tests passed:
```
[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from DatasetEncryptionTest
[ RUN      ] DatasetEncryptionTest.WriteReadDatasetWithEncryption
[       OK ] DatasetEncryptionTest.WriteReadDatasetWithEncryption (77 ms)
[ RUN      ] DatasetEncryptionTest.ReadSingleFile
[       OK ] DatasetEncryptionTest.ReadSingleFile (12 ms)
[----------] 2 tests from DatasetEncryptionTest (90 ms total)

[----------] 1 test from LargeRowEncryptionTest
[ RUN      ] LargeRowEncryptionTest.ReadEncryptLargeRows
[       OK ] LargeRowEncryptionTest.ReadEncryptLargeRows (40 ms)
[----------] 1 test from LargeRowEncryptionTest (40 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test suites ran. (131 ms total)
[  PASSED  ] 3 tests.
```

Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: I am running on Ubuntu Linux

Comment (wgtmac) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: I opened https://github.com/apache/arrow/pull/40256 which is able to reproduce the failure: 

https://github.com/apache/arrow/actions/runs/8058179725/job/22010555480?pr=40256
```
      Start 67: arrow-dataset-file-parquet-encryption-test
    Test #67: arrow-dataset-file-parquet-encryption-test ...***Failed    0.04 sec
Running main() from D:/a/arrow/arrow/build/cpp/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from DatasetEncryptionTest
[ RUN      ] DatasetEncryptionTest.WriteReadDatasetWithEncryption
[       OK ] DatasetEncryptionTest.WriteReadDatasetWithEncryption (8 ms)
[ RUN      ] DatasetEncryptionTest.ReadSingleFile
[       OK ] DatasetEncryptionTest.ReadSingleFile (1 ms)
[----------] 2 tests from DatasetEncryptionTest (10 ms total)

[----------] 1 test from LargeRowEncryptionTest
[ RUN      ] LargeRowEncryptionTest.ReadEncryptLargeRows
D:/a/arrow/arrow/cpp/src/arrow/dataset/file_parquet_encryption_test.cc:154: Failure
Failed
'_error_or_value27.status()' failed with IOError: Failed decryption finalization
D:/a/arrow/arrow/cpp/src/arrow/dataset/file_parquet_encryption_test.cc:255: Failure
Expected: TestScanDataset() doesn't generate new fatal failures in the current thread.
  Actual: it does.
[  FAILED  ] LargeRowEncryptionTest.ReadEncryptLargeRows (3 ms)
[----------] 1 test from LargeRowEncryptionTest (3 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test suites ran. (13 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LargeRowEncryptionTest.ReadEncryptLargeRows

 1 FAILED TEST
```

Comment (wgtmac) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: The test failure is due to race condition so it may not happen at each run.

Comment (tolleybot) [reply cpp/src/arrow/dataset/large_row_parquet_encrypt_test.cc]: Understood I'll keep working on it until it fails

File: cpp/src/parquet/encryption/internal_file_decryptor.cc [hunk 13]
```diff
@@ -139,10 +139,16 @@ std::shared_ptr<Decryptor> InternalFileDecryptor::GetFooterDecryptor(
...
   int key_len = static_cast<int>(footer_key.size());
-  auto aes_metadata_decryptor = encryption::AesDecryptor::Make(
-      algorithm_, key_len, /*metadata=*/true, &all_decryptors_);
-  auto aes_data_decryptor = encryption::AesDecryptor::Make(
-      algorithm_, key_len, /*metadata=*/false, &all_decryptors_);
+  std::shared_ptr<encryption::AesDecryptor> aes_metadata_decryptor;
+  std::shared_ptr<encryption::AesDecryptor> aes_data_decryptor;
+
+  {
+    std::lock_guard<std::mutex> lock(mutex_);
```
Comment (westonpace) [inline cpp/src/parquet/encryption/internal_file_decryptor.cc:146]: Should we also be locking on `mutex_` in `WipeOutDecryptionKeys`?

Comment (tolleybot) [reply cpp/src/parquet/encryption/internal_file_decryptor.cc:146]: Ill look into that. Thanks

**Comment by wgtmac** [comment]
@adamreeve @westonpace Do you want to take another pass?

**Review by westonpace — APPROVED** [review]
@wgtmac no additional concerns on my end

**Review by wgtmac — APPROVED** [review]
+1

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g cpp

File: python/pyarrow/tests/test_dataset_encryption.py [hunk 14]
```diff
@@ -15,10 +15,14 @@
 # specific language governing permissions and limitations
 # under the License.
 
+import base64
 from datetime import timedelta
+import numpy as np
 import pyarrow.fs as fs
 import pyarrow as pa
+import pyarrow.parquet as pq
```
Comment (pitrou) [inline python/pyarrow/tests/test_dataset_encryption.py:23]: I'm not sure this will work on builds where Parquet is disabled. Let's watch for CI.

File: python/pyarrow/tests/test_dataset_encryption.py [hunk 15]
```diff
@@ -151,3 +155,61 @@ def test_write_dataset_parquet_without_encryption():
...
+
+        def wrap_key(self, key_bytes: bytes, _: str) -> bytes:
+            b = base64.b64encode(key_bytes)
+            return b
+
+        def unwrap_key(self, wrapped_key: bytes, _: str) -> bytes:
+            b = base64.b64decode(wrapped_key)
+            return b
+
+    row_count = pow(2, 15) + 1
```
Comment (pitrou) [inline python/pyarrow/tests/test_dataset_encryption.py:178]: Nit: more idiomatic spelling
```suggestion
    row_count = 2**15 + 1
```

File: python/pyarrow/tests/test_dataset_encryption.py [hunk 16]
```diff
@@ -151,3 +155,61 @@ def test_write_dataset_parquet_without_encryption():
...
+
+@pytest.mark.skipif(
+    encryption_unavailable, reason="Parquet Encryption is not currently enabled"
+)
+def test_large_row_encryption_decryption():
+    """Test encryption and decryption of a large number of rows."""
+
+    class NoOpKmsClient(pe.KmsClient):
+        def __init__(self):
+            super().__init__()
```
Comment (pitrou) [inline python/pyarrow/tests/test_dataset_encryption.py:168]: This shouldn't be necessary.

File: python/pyarrow/tests/test_dataset_encryption.py [hunk 17]
```diff
@@ -151,3 +155,61 @@ def test_write_dataset_parquet_without_encryption():
...
+    )
+    pqd_config = ds.ParquetDecryptionConfig(
+        crypto_factory, kms_config, pe.DecryptionConfiguration()
+    )
+    scan_options = ds.ParquetFragmentScanOptions(decryption_config=pqd_config)
+    file_format = ds.ParquetFileFormat(default_fragment_scan_options=scan_options)
+    write_options = file_format.make_write_options(encryption_config=pqe_config)
+    file_decryption_properties = crypto_factory.file_decryption_properties(kms_config)
+
+    with tempfile.TemporaryDirectory() as tempdir:
```
Comment (pitrou) [inline python/pyarrow/tests/test_dataset_encryption.py:203]: No problem a priori with this, but within tests we tend to use the `tmpdir` fixture provided by pytest:
https://docs.pytest.org/en/6.2.x/tmpdir.html#the-tmpdir-fixture

**Comment by pitrou** [comment]
Question: the caching was probably there for a reason, is it ok to remove it? Would it be beneficial to reimplement it in a thread-safe way? (the PR description mentions network requests)

**Comment by pitrou** [comment]
Hmm, I was assuming the Cython compatibility issues were fixed? @raulcd

**Comment by raulcd** [comment]
> Hmm, I was assuming the Cython compatibility issues were fixed? @raulcd

That was my understanding, isn't this the fix? https://github.com/apache/arrow/issues/40386
I've added the above to 15.0.2.

**Comment by pitrou** [comment]
Ah, that's because this PR needs rebasing.

File: python/pyarrow/tests/test_dataset_encryption.py (hunk 14 above)
Comment (tolleybot) [reply python/pyarrow/tests/test_dataset_encryption.py:23]: Ok sounds good

File: python/pyarrow/tests/test_dataset_encryption.py (hunk 16 above)
Comment (tolleybot) [reply python/pyarrow/tests/test_dataset_encryption.py:168]: Ok Ill take it out

File: python/pyarrow/tests/test_dataset_encryption.py (hunk 17 above)
Comment (tolleybot) [reply python/pyarrow/tests/test_dataset_encryption.py:203]: Ok noted.  Thanks

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g cpp

**Review by pitrou — APPROVED** [review]
Thanks a lot @tolleybot . I'm going to merge after the latest update.

**Comment by pitrou** [comment]
@raulcd Not a blocker, but if you ever need to do a RC3, this would be a good candidate for inclusion :-)

File: python/pyarrow/tests/test_dataset_encryption.py (hunk 14 above)
Comment (jorisvandenbossche) [reply python/pyarrow/tests/test_dataset_encryption.py:23]: We might not have an actual test build without parquet .. (but indeed in general we always import pyarrow.parquet within a try/except to let this run on versions without parquet support as well)

Comment (pitrou) [reply python/pyarrow/tests/test_dataset_encryption.py:23]: Ah, I thought we did...

Comment (jorisvandenbossche) [reply python/pyarrow/tests/test_dataset_encryption.py:23]: I was just deducting that from the fact we got no failures in the builds you triggered. 
But looking at our tasks.yml, it seems the python minimal builds are not included in the "python" group ...

Comment (pitrou) [reply python/pyarrow/tests/test_dataset_encryption.py:23]: That would be why :-(

Comment (jorisvandenbossche) [reply python/pyarrow/tests/test_dataset_encryption.py:23]: Testing and potentially fixing in https://github.com/apache/arrow/pull/40505 (and at once adding the minimal tests to the python group)
