### PR TITLE
GH-34472: [Go][FlightRPC] Drain result of DoAction in Flight SQL client

### LINKED ISSUE #34472: [Go][FlightRPC] Flight SQL client does not drain DoAction streams
### Describe the bug, including details regarding any error messages, version, and platform.

This is similar to a bug that was in the C++ Flight SQL client. This means that certain operations won't actually complete when the function returns, causing nondeterministic behavior in callers.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by lidavidm**
### Rationale for this change

Unless we drain the result of DoAction, we can't be sure that the RPC actually completed.

### What changes are included in this PR?

Always drain the result of DoAction.

### Are these changes tested?

A new test was added and existing tests were modified.

### Are there any user-facing changes?

This fixes potential nondeterministic behavior that users may have previously observed.
* Closes: #34472

### CODE REVIEW

File: go/arrow/flight/flightsql/client.go [hunk 1]
```diff
@@ -396,6 +408,11 @@ func (c *Client) Prepare(ctx context.Context, query string, opts ...grpc.CallOpt
 		return
 	}
 	defer stream.CloseSend()
+	defer func() {
+		// XXX: assuming server will not return a result and then an error
+		// (or else we need to also try to clean up stmt)
+		err = readUntilEOF(stream)
+	}()
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/client.go:415]: would it make more sense to put this into `parsePreparedStatementResponse` and get it for free in all the spots that just delegate to it?

File: go/arrow/flight/flightsql/client.go [hunk 2]
```diff
@@ -500,6 +522,11 @@ func (c *Client) CancelQuery(ctx context.Context, info *flight.FlightInfo, opts
...
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/client.go:529]: rather than defer this, why not just do it manually after the next if statement?

File: go/arrow/flight/flightsql/client.go [hunk 3]
```diff
@@ -775,9 +816,7 @@ func (tx *Txn) Commit(ctx context.Context, opts ...grpc.CallOption) error {
 	}
 
 	tx.txn = nil
-	if _, err = stream.Recv(); err == io.EOF {
-		err = nil
-	}
+	err = readUntilEOF(stream)
 	return err
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/client.go:820]: `return readUntilEOF(stream)` ?

File: go/arrow/flight/flightsql/client.go [hunk 4]
```diff
@@ -806,10 +845,7 @@ func (tx *Txn) Rollback(ctx context.Context, opts ...grpc.CallOption) error {
 	}
 
 	tx.txn = nil
-	if _, err = stream.Recv(); err == io.EOF {
-		err = nil
-	}
-
+	err = readUntilEOF(stream)
 	return err
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/client.go:849]: same as above

**Review by zeroshade — COMMENTED** [review]
Looks good, just a few nitpicks

**Comment by lidavidm** [comment]
Cleaned things up:
- CloseSend() needs to be called before Recv() always
- Mocks were made more reliable via Once()
- Addressed comments

**Review by zeroshade — APPROVED** [review]
LGTM though i think you missed a spot which could just `return readUntilEOF`

**Comment by lidavidm** [comment]
Whoops, thanks.

**Comment by lidavidm** [comment]
I'll merge this now, CI failures are from #34488
