### PR TITLE
GH-39191: [R] throw error when `string_replace` is passed vector of values in `pattern`

### LINKED ISSUE #39191: [R] arrow R package: support for stringr::str_replace_all() incomplete
### Describe the bug, including details regarding any error messages, version, and platform.

The [arrow R package claims to support the `stringr::str_replace_all()` function](https://arrow.apache.org/docs/dev/r/reference/acero.html#stringr), however, it does not support using a vector of pattern/replacements as [the function says it should.](https://stringr.tidyverse.org/reference/str_replace.html)
```r
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(stringr)
dat<-data.frame(common_name=c("Cobalt-rumped Parrotlet", 
                              "Striped Woodcreeper", 
                              "Allard's Ground Cricket",
                              "Southern Double-collared Sunbird"))
dat_arrow<-arrow_table(dat)

# if working with a normal data.frame the following code works
dat_df<-dat %>% 
    mutate(common_name_clean = str_replace_all(common_name, c(" |-"="_", "'" = "")))

dat_df
#>                        common_name                common_name_clean
#> 1          Cobalt-rumped Parrotlet          Cobalt_rumped_Parrotlet
#> 2              Striped Woodcreeper              Striped_Woodcreeper
#> 3          Allard's Ground Cricket           Allards_Ground_Cricket
#> 4 Southern Double-collared Sunbird Southern_Double_collared_Sunbird

#but if working with an arrow data.frame it says I have to collect first
dat_arrow<-dat_arrow%>% 
    mutate(common_name_clean = str_replace_all(common_name, c(" |-"="_", "'" = "")))
#> Warning: Expression str_replace_all(common_name, c(` |-` = "_", `'` = "")) not
#> supported in Arrow; pulling data into R
Created on 2023-12-11 with reprex v2.0.2
```

### Component(s)

R

### PR DESCRIPTION
**Pull request by abfleishman**
### Rationale for this change
See #39191 This PR will hopefully throw an informative error message to let the user know that while the stringr::str_replace_all function can handle a named vector of values as the pattern argument, the arrow R package implementation cannot.  

### What changes are included in this PR?
- [ ] add tests for passing vector to the pattern argument
- [ ] add check for length > 1 to the string replace bindings

### Are these changes tested?
yes (though I need help!)

### Are there any user-facing changes?
 yes. Hopefully the user will be alerted by an informative error message that they cannot pass a vector to the pattern argument. No breaking changes are expected.

* Closes: #39191

### CODE REVIEW

**Comment by abfleishman** [comment]
@thisisnic I have started this PR with my failed attempt to add the check  and tests I thought might be useful. I could not figure it all out and my tests fail.

**Comment by abfleishman** [comment]
> A question for you also, to fix the reported bug, do we need to check the input length for both pattern and replacement, or just one?
[Looks like](https://stringr.tidyverse.org/reference/str_replace.html) if `pattern` is length 1, then `replacement` has to be length 1.  If `pattern` is length >1 then `replacement` can be length 1 or the same as pattern.  So I think checking for `length(pattern)==1`  should be enough.

@thisisnic can you explain what the `call_binding` is doing?  

also, I think this is ready?  LMK if there is more I should do?

**Comment by thisisnic** [comment]
> @thisisnic can you explain what the `call_binding` is doing?

Sure.  Here's the code for `call_binding()`:

https://github.com/apache/arrow/blob/75c6b642b5ff1ed171bc1d1a758a70098539c48e/r/R/dplyr-funcs.R#L136-L138

In the arrow R package, we create "bindings" which create a link between the call to the R code and an expression which can be understood and ran by Arrow - in your case in this PR, the binding to `stringr::string_replace()`.  We keep a list of bindings in a registry - which is that the `nse_funcs` which is being accessed in that function is.  When we call `call_binding()`, it finds the relevant function in the registry and runs it, to create the correct Arrow Expression based on the R call.

Here's an example of using `call_binding()`.  It needs to know the column we want to run it on (in this case we'll call it `x`) and any parameter to pass in (in this case, the pattern and replacement).  You can see below that it maps the `stringr` function `str_replace` to the Arrow function `replace_substring_regex`.

```
> x <- Expression$field_ref("x")
> call_binding("str_replace", x, "a", "A")
Expression
replace_substring_regex(x, {pattern="a", replacement="A", max_replacements=1})
```

On its own `call_binding()` isn't much use in day-to-day arrow usage - it's used internally in more complex functions. But when we are running tests and want to isolate that the error messages we have designed appear correctly, then we can use it and so not have to worry about the other components of the functions which use `call_binding()` (for example when they ignore error messages to just run the code in R if it's possible, like you found earlier).

**Comment by thisisnic** [comment]
> also, I think this is ready? LMK if there is more I should do?

My apologies, I had a brain fart moment when I asked if we need to test them both, and was getting the input data column mixed up with `replacement`.  I think we do need to test both `pattern` and `replacement`.

This PR is looking excellent, and is most of the way there; just needs the extra check (for `replacement` added in, a test for it), and then, if you run `styler::style_file()` on each of the changed files, it'll fix the linting issues which are causing one of the CI jobs to fail at the moment.

File: r/tests/testthat/test-dplyr-funcs-string.R [hunk 1]
```diff
@@ -433,7 +433,24 @@ test_that("str_replace and str_replace_all", {
...
+      transmute(x = call_binding("str_replace_all", x, c("F", "b"), c("_", ""))) %>%
+      collect(),
+    regexp = "`pattern` must be a length 1 character vector",
+  )
+  expect_error(
+    arrow_table(df) %>%
+      transmute(x = call_binding("str_replace_all", x, c("F"), c("_", ""))) %>%
+      collect(),
+    regexp = "`replacement` must be a length 1 character vector",
+  )
```
Comment (thisisnic) [inline r/tests/testthat/test-dplyr-funcs-string.R:453]: One tiny last change to suggest, and then this will be ready to merge!  You don't need the `arrow_table()` etc stuff here as `call_binding()` can be called on its own.  What is needed instead is to create a field reference so `call_binding()` has something to refer to in the expression it creates, and then `expect_error()` can just wrap `call_binding()`.

For example, in that final test, you'll need something a bit shorter, like this:

```
  x <- Expression$field_ref("x")
  expect_error(
    call_binding("str_replace_all", x, c("F"), c("_", ""))),
    regexp = "`replacement` must be a length 1 character vector"
  )
```

Comment (abfleishman) [reply r/tests/testthat/test-dplyr-funcs-string.R]: Cool.  I'll be honest.  I really am lost in this whole `call_bindings`/`Expression$field_ref("x")` stuff.  I guess thats what I get for being a field biologist dabbling in computer science.  Thanks for walking me through this stuff!

Comment (thisisnic) [reply r/tests/testthat/test-dplyr-funcs-string.R]: You've dived into a really tricky bit of the codebase, but you've done a great job!  A lot of my own early PRs to arrow involved drawing analogies between different bits of the codebase, but not understanding exactly what was going on (and this is still the case for any of my PRs which involve any C++).

Congratulations on your first PR to Arrow! Once the CI passes I'll merge it.  Welcome to the project :)

**Review by thisisnic — APPROVED** [review]
Wonderful, thank you for making this PR!

**Comment by abfleishman** [comment]
Nice!  Thanks @thisisnic!  Slightly confusing but great (small) issue to tackle as a first issue!  Thanks for walking me through making the edits.  I imagine you spent more time responding to me than it would have taken you to make the changes yourself, but I guess that is part of the open-source philosophy!

**Comment by thisisnic** [comment]
> Nice! Thanks @thisisnic! Slightly confusing but great (small) issue to tackle as a first issue! Thanks for walking me through making the edits. I imagine you spent more time responding to me than it would have taken you to make the changes yourself, but I guess that is part of the open-source philosophy!

Happy to do it again any time :)

**Comment by baarthur** [comment]
hey guys!

i'd like to suggest including a caveat [on this page](https://arrow.apache.org/docs/r/reference/acero.html#stringr) to highlight that pattern/replacement vectors are not supported. 

also, user feedback: i think the error message could be a little more informative, by explicitly saying that arrow cannot support multiple pattern/replacement vectors, it would be clearer to me since i thought it was a message from R and not from arrow

**Comment by thisisnic** [comment]
Hi @baarthur - as this PR has now been marged, I don't suppose you'd mind opening a new issue with this? It'd be great to include your suggestion for the updated error message.  If you were interested, we'd be happy to accept a PR for those changes too :)

**Comment by baarthur** [comment]
sure thing! opening a new issue right away
