### PR TITLE
GH-15176: Fix various issues introduced in the asof-join benchmark by ARROW-17980 and ARROW-15732

### LINKED ISSUE #15176: [C++][Benchmarking] AsOfJoinOverhead benchmarks started failing after https://github.com/apache/arrow/commit/498b645e1d09306bf5399a9a019a5caa99513815 was merged
### Describe the bug, including details regarding any error messages, version, and platform.

C++ benchmarks started failing on all machines (test-mac-arm, ec2s, ursa-thinkcentre-m75q) when https://github.com/apache/arrow/commit/498b645e1d09306bf5399a9a019a5caa99513815 was merged 4 days ago:

Here is a build with failed C++ benchmarks: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/2107

Steps to reproduce:
```
cd ~
rm -rf arrow
git clone https://github.com/apache/arrow.git
cd arrow
conda create -y -n arrow-commit -c conda-forge \
  --file ci/conda_env_unix.txt \
  --file ci/conda_env_cpp.txt \
  --file ci/conda_env_python.txt \
  compilers \
  python=3.8 \
  pandas

conda activate arrow-commit

pip install -r python/requirements-build.txt -r python/requirements-test.txt

source dev/conbench_envs/hooks.sh set_arrow_build_and_run_env_vars

export RANLIB=`which $RANLIB`
export AR=`which $AR`
export ARROW_JEMALLOC=OFF

pip install -e dev/archery
archery benchmark run --suite-filter=arrow-compute-asof-join-benchmark

```

Note the errors:
```
...
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: mismatching number of input schema and keys
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
/Users/voltrondata/arrow/cpp/src/arrow/compute/exec/asof_join_benchmark.cc:88: Failure
Failed
'DeclarationToStatus(std::move(join_node))' failed with Invalid: inconsistent size of by-key across inputs
Traceback (most recent call last):
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/bin/archery", line 33, in <module>
    sys.exit(load_entry_point('archery', 'console_scripts', 'archery')())
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/voltrondata/arrow/dev/archery/archery/cli.py", line 513, in benchmark_run
    json_out = json.dumps(runner_base, cls=JsonEncoder)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/voltrondata/arrow/dev/archery/archery/benchmark/codec.py", line 35, in default
    return BenchmarkRunnerCodec.encode(o)
  File "/Users/voltrondata/arrow/dev/archery/archery/benchmark/codec.py", line 79, in encode
    return {"suites": [BenchmarkSuiteCodec.encode(s) for s in br.suites]}
  File "/Users/voltrondata/arrow/dev/archery/archery/benchmark/codec.py", line 79, in <listcomp>
    return {"suites": [BenchmarkSuiteCodec.encode(s) for s in br.suites]}
  File "/Users/voltrondata/arrow/dev/archery/archery/benchmark/runner.py", line 176, in suites
    suite = self.suite(suite_name, suite_bin)
  File "/Users/voltrondata/arrow/dev/archery/archery/benchmark/runner.py", line 152, in suite
    results = suite_cmd.results(repetitions=self.repetitions)
  File "/Users/voltrondata/arrow/dev/archery/archery/benchmark/google.py", line 63, in results
    self.run(*argv, check=True)
  File "/Users/voltrondata/arrow/dev/archery/archery/utils/command.py", line 78, in run
    return subprocess.run(invocation, **kwargs)
  File "/Users/voltrondata/miniconda3/envs/arrow-commit-2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/var/folders/d9/n0lbzbf16nvgt7b83xhcssm80000gn/T/arrow-archery-_er3jw0l/WORKSPACE/build/release/arrow-compute-asof-join-benchmark', '--benchmark_repetitions=1', '--benchmark_out=/var/folders/d9/n0lbzbf16nvgt7b83xhcssm80000gn/T/tmpa0lpbr61', '--benchmark_out_format=json']' died with <Signals.SIGSEGV: 11>.
```

### Component(s)

Benchmarking, C++

### PR DESCRIPTION
**Pull request by westonpace**
* Closes: #15176

### CODE REVIEW

File: cpp/src/arrow/compute/exec/asof_join_benchmark.cc [hunk 1]
```diff
@@ -112,8 +115,8 @@ AsofJoinNodeOptions GetRepeatedOptions(size_t repeat, FieldRef on_key,
 
 static void AsOfJoinOverhead(benchmark::State& state) {
   int64_t tolerance = 0;
-  AsofJoinNodeOptions options =
-      GetRepeatedOptions(int(state.range(4)), kTimeCol, {kKeyCol}, tolerance);
+  auto options = std::make_shared<AsofJoinNodeOptions>(
+      GetRepeatedOptions(int(state.range(4) + 1), kTimeCol, {kKeyCol}, tolerance));
```
Comment (westonpace) [inline cpp/src/arrow/compute/exec/asof_join_benchmark.cc:119]: @rtpsw can you verify this change?  `state.range(4)` is the # of right tables but it seems we need a `Keys` element for each of the right tables as well as 1 for the left table.

**Comment by westonpace** [comment]
@ursabot please benchmark lang=C++

**Comment by westonpace** [comment]
Odd...ursabot scheduled the runs but gave me links to old buildkite builds.  Here are the correct links:

test-mac-arm: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/2134
ursa-thinkcentre-m75q: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-thinkcentre-m75q/builds/2126

@ElenaHenderson is this a known issue?

**Comment by westonpace** [comment]
Both benchmark builds passed so I think this addresses the issue.

**Comment by westonpace** [comment]
Ah, that makes sense.  Just a matter of reading more closely.  I'm going to go ahead and merge this so CI can be unblocked.  @rtpsw , if you have any concerns let's address in a follow-up.

File: cpp/src/arrow/compute/exec/asof_join_benchmark.cc (hunk 1 above)
Comment (rtpsw) [reply cpp/src/arrow/compute/exec/asof_join_benchmark.cc:119]: Sorry, I somehow missed this. The fix seems right to me.
