### PR TITLE
GH-38794: [C++][S3] Handle conventional content-type for directories

### LINKED ISSUE #38794: [Python] [AWS] Fail to open partitioned parquet with s3fs + pyarrow due to s3 prefix
### Describe the bug, including details regarding any error messages, version, and platform.
pyarrow == 14.0.1

## How the parquet is created:
``` python
import polars as pl
import pyarrow.dataset as ds
import s3fs

s3fs = s3fs.S3FileSystem()
df = pl.DataFrame()
ds.write_dataset(
    df.to_arrow(),
    "s3://bucket/parquet_root",
    format='parquet', 
    filesystem=s3fs,
    partitioning=ds.partitioning(pa.schema([("set", pa.string()), ("subset", pa.string())])),
    existing_data_behavior='delete_matching'
)
```

After the action, in the bucket, path `parquet_root/abc/def/part-0.parquet` exists.

## Try to access the parquet
**NOTE: same API call endures a behavior change after I call `s3fs.isdir` in between, that is also weird**
``` python
import polars as pl
import pyarrow as pa
import pyarrow.dataset as ds
import pyarrow.parquet as pq
import s3fs

s3fs = s3fs.S3FileSystem()
pq.read_table('bucket/parquet_root/abc/def/part-0.parquet',filesystem=s3fs) # ok
pq.read_table('s3://bucket/parquet_root/abc/def/part-0.parquet',filesystem=s3fs) # ok

pq.ParquetDataset('s3://bucket/parquet_root/', filesystem=s3fs, 
  partitioning=ds.DirectoryPartitioning(pa.schema([("set", pa.string()), ("subset", pa.string())])))
# pyarrow.lib.ArrowInvalid: Could not open Parquet input source 's3://bucket/parquet_root/': Parquet file size is 0 bytes

# after I manually call s3fs.isdir, things changes, I suspect this is another bug
s3fs.isdir('s3://bucket/parquet_root/') # True

# repeat the call
pq.ParquetDataset('s3://bucket/parquet_root/', filesystem=s3fs, 
  partitioning=ds.DirectoryPartitioning(pa.schema([("set", pa.string()), ("subset", pa.string())])))
# pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'bucket/parquet_root/abc/def/part-0.parquet', which is outside base dir 's3://bucket/parquet_root/'

# another try, the same error
dataset = ds.dataset(
  's3://bucket/parquet_root/',
  format='parquet', 
  filesystem=s3fs, 
  partitioning=ds.DirectoryPartitioning(pa.schema([("set", pa.string()), ("subset", pa.string())]))
)
# pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'bucket/parquet_root/abc/def/part-0.parquet', which is outside base dir 's3://bucket/parquet_root/'
```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

Some AWS-related tools write and expect the content-type "application/x-directory" for directory-like entries.

This PR does two things:
1) set the object's content-type to "application/x-directory" when the user explicitly creates a directory
2) when a 0-sized object with content-type starting with "application/x-directory" is encountered, consider it a directory

### Are these changes tested?

Unfortunately, this cannot be tested with MinIO, as it seems to ignore the content-type set on directories (as opposed to regular files).

### Are there any user-facing changes?

Hopefully better compatibility with existing S3 filesystem hierarchies.

* Closes: #38794
* GitHub Issue: #38794

### CODE REVIEW

**Comment by pitrou** [comment]
@yf-yang This might solve your issue, though obviously I'm not able to test.

**Comment by pitrou** [comment]
Actually, probably not, since the FileInfo result in https://github.com/apache/arrow/issues/38794#issuecomment-1908322370 will not be changed.

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 1]
```diff
@@ -1214,6 +1215,24 @@ Status SetObjectMetadata(const std::shared_ptr<const KeyValueMetadata>& metadata
   return Status::OK();
 }
 
+bool IsDirectory(std::string_view key, const S3Model::HeadObjectResult& result) {
+  // If it has a non-zero length, it's a regular file
+  if (result.GetContentLength() > 0) {
+    return false;
+  }
+  // Otherwise, if it has a trailing slash, it's a directory
+  if (key[key.size() - 1] == kSep) {
```
Comment (kou) [inline cpp/src/arrow/filesystem/s3fs.cc:1224]:
```suggestion
  if (internal::HasTrailingSlash(key)) {
```

**Review by kou — APPROVED** [review]
+1 if it works.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel

**Comment by pitrou** [comment]
@yf-yang Once they are marked "passing", the Crossbow badges above will give you access to binary wheels of PyArrow with this PR's changes (for example : https://github.com/ursacomputing/crossbow/actions/runs/7971839531). Can you try installing the corresponding wheel for your configuration and check if it fixes the issue for you?

**Comment by pitrou** [comment]
Ping @yf-yang

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 2]
```diff
@@ -1214,6 +1215,24 @@ Status SetObjectMetadata(const std::shared_ptr<const KeyValueMetadata>& metadata
   return Status::OK();
 }
 
+bool IsDirectory(std::string_view key, const S3Model::HeadObjectResult& result) {
+  // If it has a non-zero length, it's a regular file
+  if (result.GetContentLength() > 0) {
+    return false;
+  }
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/s3fs.cc:1222]: I don't think it's even possible for all `arrow::FileSystem` functions to deal with `/`-ending paths that are sometimes considered to be a "file". It's better to simply say "we do not support reading files that end in a `/` in `arrow::FileSystem` implementations".

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 3]
```diff
@@ -1214,6 +1215,24 @@ Status SetObjectMetadata(const std::shared_ptr<const KeyValueMetadata>& metadata
...
+  // Otherwise, if it has a trailing slash, it's a directory
+  if (internal::HasTrailingSlash(key)) {
+    return true;
+  }
+  // Otherwise, if its content type starts with "application/x-directory",
+  // it's a directory
+  if (::arrow::internal::StartsWith(result.GetContentType(), kAwsDirectoryContentType)) {
+    return true;
+  }
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/s3fs.cc:1231]: This we can support: directories that don't end in a `/`.

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 4]
```diff
@@ -2145,7 +2166,10 @@ class S3FileSystem::Impl : public std::enable_shared_from_this<S3FileSystem::Imp
           child_path_ss << bucket << kSep << child_key;
           child_key = child_path_ss.str();
           if (obj.GetSize() > 0 || !had_trailing_slash) {
-            // We found a real file
+            // We found a real file.
+            // XXX Ideally, for 0-sized files we would also check the Content-Type
+            // against kAwsDirectoryContentType, but ListObjectsV2 does not give
+            // that information.
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/s3fs.cc:2172]: As I said above, trying to support this gets ugly very quickly. The explosion of conditions to check when validating operations and extra requests everywhere.

Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: I checked the issue and I think supporting directories with trailing-slash-less keys + requiring that files never have a trailing-slash is enough to solve the issue. And won't create more issues.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 2 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:1222]: This is the information that comes back from S3, not what we present to the user.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 4 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: I agree it's not very pretty, but if it solves a real issue for users, then we should probably do it IMHO.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 2 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:1222]: Ah, sorry, I misread your comment. Well, we were originally cautious on this. It's also not obvious to me that AWS or other S3 implementations would always return an ending slash for pseudo-"directories". It seems to depend on _how_ the directory was created.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 4 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: By ugly I mean it creates bugs: actions on the filesystem become undefined or with very complicated semantics.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 2 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:1222]: I know, but we can limit the Arrow implementation in saying that it's unable to reason about files ending with a `/`. Directories without a `/` should be OK. It won't read and won't create files at keys ending with a `/`. Without this, it's really hard to offer filesystem operations that behave as expected.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 4 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: For example:

s3fs doesn't support `Move` yet I think, but if it were to support, the semantics of the path validations take the trailing `/` in `dest` to mean `src` should also be a directory. It's OK to pass `/`-less to `Move` that refer to directories, but it's not OK to pass paths with trailing slashes that refer to files.

This prevents accidental overrides of files by `Move(src, dest)` because directories can only be overriden if they are empty.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 2 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:1222]: To be clear, this PR shouldn't change anything in that regard. It just adds the Content-Type heuristic, which seems desirable since it's shared with other tools.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 4 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: `GetFileInfo` has the following post-condition:

If path has trailing slash, then result is either `FileType::kDirectory` or `FileType::kNotFound` [1]. You would break that by returning `kFile` for paths containing trailing slashes.

> I don't think we plan to support Move because, last I looked, S3 didn't support a native move operation.

Technically, it doesn't support any directory operation, but the file system implementation is supposed to be a layer that implements filesytem semantics on top of it. Even a filesystem `stat` can't be mapped directly to S3 operations.

[1] https://github.com/apache/arrow/blob/main/cpp/src/arrow/filesystem/localfs.cc#L169

Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: > I agree it's not very pretty, but if it solves a real issue for users, then we should probably do it IMHO.

The restriction I'm asking for doesn't prevent the issue to be fixed. We can support directories on paths not ending with a `/`. I'm asking to not expand the scope of the fix to also allow files on paths with trailing `/`.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 2 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:1222]: I'm closing this thread as the discussion is the same as in the other thread.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 4 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: But again, the PR doesn't change anything about this. We could make our heuristics stricter but that would be beside the scope of this PR.

Comment (felipecrv) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: You're right. All the calls to `IsDirectory` were accepting paths that end with `/` as files. 🤔 

Can you at least add a comment on the file size check in `IsDirectory`?

Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:2172]: I'll add a comment, yes.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel -g python
