### PR TITLE
GH-40037: [C++][FS][Azure] Make attempted reads and writes against directories fail fast

### LINKED ISSUE #40037: [C++][FS][Azure] Prevent reading or writing directory marker blobs
### Describe the enhancement requested

Child of https://github.com/apache/arrow/issues/18014

Blob storage doesn't really have directories. Instead we use directory marker blobs to implement directories. Even hierarchical namespace storage accounts, that do have built in directories, implement it using directory markers. 

Its possible that a user of the `AzureFileSystem` might accidentally try to read or write a directory marker which could cause confusion. This scenario should return a clear error message. 

Hierarchical namespace storage accounts will add `hdi_isFolder=true` https://github.com/Azure/azure-sdk-for-cpp/blob/12407e8bfcb9bc1aa43b253c1d0ec93bf795ae3b/sdk/storage/azure-storage-files-datalake/src/datalake_utilities.cpp#L86-L90 and on flat namespace accounts the the `AzureFileSystem` sets `is_directory=true`. This would make a cheap check so that we can fail fast.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by Tom-Newton**
### Rationale for this change
Prevent confusion if a user attempts to read or write a directory. 

### What changes are included in this PR?
- Make `ObjectAppendStream::Flush` a noop if `ObjectAppendStream::Init` has not run successfully. This avoids an unhandled error when the destructor calls flush. 
- Check blob properties for directory marker metadata when initialising `ObjectInputFile` or `ObjectAppendStream`. 
- When initialising `ObjectAppendStream` call `GetFileInfo` if it is a flat namespace account.

### Are these changes tested?
Add new tests `DisallowReadingOrWritingDirectoryMarkers` and `DisallowCreatingFileAndDirectoryWithTheSameName` to cover the new fail fast behaviour. 
Also updated `WriteMetadata` to ensure that my changes to Flush didn't break setting metadata without calling `Write` on the stream. 

### Are there any user-facing changes?
Yes. Invalid read and write operations will now fail fast and gracefully. Previously could get into a confusing state where there were files and directories at the same path and there were some un-graceful failures. 

* Closes: #40037

### CODE REVIEW

**Comment by Tom-Newton** [comment]
@felipecrv I expect you will be interested in reviewing this.

**Review by felipecrv — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 1]
```diff
@@ -698,11 +721,15 @@ class ObjectAppendStream final : public io::OutputStream {
   ObjectAppendStream(std::shared_ptr<Blobs::BlockBlobClient> block_blob_client,
                      const io::IOContext& io_context, const AzureLocation& location,
                      const std::shared_ptr<const KeyValueMetadata>& metadata,
-                     const AzureOptions& options, int64_t size = kNoSize)
+                     const AzureOptions& options, const bool truncate,
+                     std::function<Status()> ensure_not_flat_namespace_directory,
```
[the remark this answers is not in the document]
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs.cc:725]: I'm happy to implement it as you described but if the function is only used in `Init()` then, am I right in thinking we will never actually hit this problem?

[the remark this answers is not in the document]
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:725]: I thought you had to retain the funtions as a member of the file handle. If you only need it on `Init` you can pass `*this` as an `Init` function parameter avoiding unnecessary copying and bloating the destructor of every file handle unnecessarily. You will still need to be-`friend` the classes.

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 2]
```diff
@@ -716,17 +738,31 @@ class ObjectAppendStream final : public io::OutputStream {
     io::internal::CloseFromDestructor(this);
   }
 
-  Status Init() {
-    if (content_length_ != kNoSize) {
-      DCHECK_GE(content_length_, 0);
-      pos_ = content_length_;
+  Status Init(const bool truncate,
+              std::function<Status()> ensure_not_flat_namespace_directory) {
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/azurefs.cc:742]: You can inject `AzureFileSystem *azure_file_system` here and not have to allocate a closure for this. You would call  `AzureFileSystem::Impl::EnsureNotFlatNamespaceDirectory(location)` via `azure_file_system->impl_` (accessible because the handles produced by the azure file system can be friends with the filesystem class).

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 3]
```diff
@@ -1662,20 +1705,28 @@ class AzureFileSystem::Impl {
...
     auto block_blob_client = std::make_shared<Blobs::BlockBlobClient>(
-        blob_service_client_->GetBlobContainerClient(location.container)
-            .GetBlockBlobClient(location.path));
+        blob_container_client.GetBlockBlobClient(location.path));
+
+    auto ensure_not_flat_namespace_directory = [this, location,
+                                                blob_container_client]() -> Status {
+      bool hierarchical_namespace_enabled =
+          HierarchicalNamespaceSupport(GetFileSystemClient(location.container)) ==
+          HNSSupport::kEnabled;
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/azurefs.cc:1716]: It could be `HNSSupport::kContainerNotFound`.

You can be explicit

```cpp
    ARROW_ASSIGN_OR_RAISE(auto hns_support, HierarchicalNamespaceSupport(adlfs_client));
    if (hns_support == HNSSupport::kContainerNotFound) {
      return Status::OK();
    }
    if (hns_support == HNSSupport::kDisabled) {
      // handle HNS disabled case
    }
    return Status::OK();
```

or compare with `HNSSupport::kDisabled` (`!(hns_suppport == kEnabled)` is not equivalent to `hns_support == kDisabled`).

```cpp
    ARROW_ASSIGN_OR_RAISE(auto hns_support, HierarchicalNamespaceSupport(adlfs_client));
    if (hns_support == HNSSupport::kDisabled) {
       // check
    }
    return Status::OK();
```

**Review by felipecrv — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 2 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:742]: The trick is to forward-declare the class as well.

```cpp
diff --git a/cpp/src/arrow/filesystem/azurefs.h b/cpp/src/arrow/filesystem/azurefs.h
index 2a131e40c..d48ef9dd7 100644
--- a/cpp/src/arrow/filesystem/azurefs.h
+++ b/cpp/src/arrow/filesystem/azurefs.h
@@ -44,6 +44,7 @@ class DataLakeServiceClient;

 namespace arrow::fs {

+class ObjectAppendStream;
 class TestAzureFileSystem;

 /// Options for the AzureFileSystem implementation.
@@ -180,6 +181,7 @@ class ARROW_EXPORT AzureFileSystem : public FileSystem {

   explicit AzureFileSystem(std::unique_ptr<Impl>&& impl);

+  friend class ObjectAppendStream;
   friend class TestAzureFileSystem;
   void ForceCachedHierarchicalNamespaceSupport(int hns_support);
```

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 3 above)
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs.cc]: :+1:  we can save ourselves an extra API call if its `HNSSupport::kContainerNotFound`

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 2 above)
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs.cc:743]: I think my main problem was that `ObjectAppendStream` is defined inside an anonymous namespace. 

Are you suggesting to use `AzureFileSystem *azure_file_system` or `AzureFileSystem:Impl *azure_file_system` as the argument to `ObjectAppendStream::Impl`. I don't know how I can get a `AzureFileSystem` pointer from inside `AzureFileSystem::Impl` and using `AzureFileSystem::Impl` as the argument leads to `incomplete type` errors which I don't think I can avoid. 

Also if you wouldn't mind I would be interested to know what the disadvantage of a lambda function is compared to what you proposed. 

Sorry about my lacking C++ knowledge here.

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs.cc]: I marked as resolved since remaining changes are tracked by https://github.com/apache/arrow/pull/40119#discussion_r1495973990

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 2 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:743]: > Also if you wouldn't mind I would be interested to know what the disadvantage of a lambda function is compared to what you proposed.

To create the `std::function`, you heap allocate an object with copies of the values in the capture list and generate a lot more extra code in the binary:

```
class function {
  T valuesfromthecpapturelist;
  
  RetType operator()(ArgsType ...) {...};
}
```

When you think about an `std::function` this way (a pair of context data and a function), you realize the class you already serves that purpose.

But hey, this is becoming challenging, so I won't hold the PR anymore because of this. Moving to `Init()` was a big step in the right direction.

**Review by felipecrv — APPROVED** [review]

File: cpp/src/arrow/filesystem/azurefs_test.cc [hunk 4]
```diff
@@ -1599,6 +1603,11 @@ TYPED_TEST(TestAzureFileSystemOnAllScenarios,
   this->TestDisallowCreatingFileAndDirectoryWithTheSameName();
 }
 
+TYPED_TEST(TestAzureFileSystemOnAllScenarios,
+           OpenOutputStreamWithMissingContainer) {
```
[the remark this answers is not in the document]
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs_test.cc]: Fixed

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 2 above)
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs.cc:742]: Thanks for explaining

**Review by felipecrv — APPROVED** [review]

**Comment by austin3dickey** [comment]
That should be the last one. Sorry again about the noise!

**Comment by felipecrv** [comment]
@austin3dickey no worries :)
