### PR TITLE
GH-38676: [Python] Fix potential deadlock when CSV reading errors out

### LINKED ISSUE #38676: [C++] Reading empty CSV file in parallel hangs
### Describe the bug, including details regarding any error messages, version, and platform.

With the following script:

```
from pyarrow import csv
from io import BytesIO
from concurrent.futures import ThreadPoolExecutor

data = "x,y,z"

def read_csv_pyarrow(i):
    try:
        csv.read_csv(BytesIO(data.encode()))
    except:
        pass
    print(i)
    return i

with ThreadPoolExecutor(4) as e:
    list(e.map(read_csv_pyarrow, range(20)))
```

this occasionally hangs.

Reading the file itself gives the "ArrowInvalid: CSV parse error: Empty CSV file or block: cannot infer number of columns" error:

https://github.com/apache/arrow/blob/db19a358cdf2b550b741fc7574dea38a6e32261b/cpp/src/arrow/csv/parser.cc#L545

We discovered this in the pandas test suite (https://github.com/pandas-dev/pandas/pull/55687)

### Component(s)

C++

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

A deadlock can happen in a C++ destructor in the following case:
* the C++ destructor is called from Python, holding the GIL
* the C++ destructor waits for a threaded task to finish
* the threaded task has invoked some Python code which is waiting to acquire the GIL

### What changes are included in this PR?

To reliably present such a deadlock, introduce `std::shared_ptr` and `std::unique_ptr` wrappers that release the GIL when deallocating the embedded pointer.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #38676

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel

File: python/pyarrow/src/arrow/python/common.h [hunk 1]
```diff
@@ -235,6 +238,48 @@ class ARROW_PYTHON_EXPORT OwnedRefNoGIL : public OwnedRef {
...
+    if (this->get() != nullptr && Py_IsInitialized() && PyGILState_Check()) {
+      return PyReleaseGIL();
+    }
+    return {};
+  }
+};
+
+/// \brief A std::shared_ptr<T, ...> subclass that releases the GIL when destroying T
+template <typename... Ts>
+using SharedPtrNoGIL = SmartPtrNoGIL<std::shared_ptr, Ts...>;
```
Comment (bkietz) [inline python/pyarrow/src/arrow/python/common.h:277]: What if the no GIL smart pointer wraps an object which must call into python as part of its destruction? (For example a dataset which wraps a python file system.) I *think* that this will be fine since such a call would acquire the GIL at the call site

**Review by bkietz — APPROVED** [review]
LGTM, modulo one concern where I'm not totally confident of GIL dynamics

File: python/pyarrow/src/arrow/python/common.h (hunk 1 above)
Comment (pitrou) [reply python/pyarrow/src/arrow/python/common.h:277]: > I _think_ that this will be fine since such a call would acquire the GIL at the call site

Yes, it would.
