### PR TITLE
GH-39870: [Go] Include buffered pages in TotalBytesWritten

### LINKED ISSUE #39870: [Go][Parquet] Inaccurate RowGroupTotalCompressedBytes/RowGroupTotalBytesWritten with go parquet file writer
### Describe the bug, including details regarding any error messages, version, and platform.

There does not appear to be an accurate way to identify or estimate the size of the current row group with `pqarrow.FileWriter`. 

`RowGroupTotalCompressedBytes()`provides the total bytes from [created data pages](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L334) but, when the [dictionary page size limit is reached ](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer_types.gen.go.tmpl#L240-L242) the buffered data pages are flushed and the [total size is reset to "0"](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L400). This means the RowGroupTotalCompressedBytes will only provide the size of pages created after the dictionary page size was reached. Ideally the size the TotalCompressedBytes size should include all created data pages. 

`RowGroupTotalBytesWritten()` will provide the total bytes of DataPages when [they are written](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L461) but, not if the the page is buffered due to the [dictionary page still being created](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L330). This causes the `RowGroupTotalBytesWritten` to inaccurately provide a "0" bytes estimate until the dictionary page size limit is reached.

Perhaps related to: https://github.com/apache/arrow/issues/39789. 

### Component(s)

Go

### PR DESCRIPTION
**Pull request by matthewmcnew**
### Rationale for this change

Currently, buffered data pages are not included in TotalBytesWritten this means that their is not an accurate estimate of the size of the current size. 

### Are there any user-facing changes?
`RowGroupTotalBytesWritten` will include the TotalBytes in buffered DataPages minus the buffered data pages headers. 

* Closes: #39870

### CODE REVIEW

File: go/parquet/file/column_writer_test.go [hunk 1]
```diff
@@ -430,7 +430,12 @@ func (p *PrimitiveWriterTestSuite) testDictionaryFallbackEncoding(version parque
 }
 
 func (p *PrimitiveWriterTestSuite) testDictionaryFallbackAndCompressedSize(version parquet.Version) {
-	p.GenerateData(SmallSize)
+	// skip boolean as dictionary encoding is not used
+	if p.Typ.Kind() == reflect.Bool {
+		return
+	}
+
+	p.GenerateData(LargeSize)
```
Comment (zeroshade) [inline go/parquet/file/column_writer_test.go:438]: why the change from SmallSize to LargeSize?

File: go/parquet/file/column_writer_test.go [hunk 2]
```diff
@@ -440,13 +445,14 @@ func (p *PrimitiveWriterTestSuite) testDictionaryFallbackAndCompressedSize(versi
 		props.Encoding = parquet.Encodings.RLEDict
 	}
 
-	writer := p.buildWriter(SmallSize, props, parquet.WithVersion(version))
+	writer := p.buildWriter(SmallSize, props, parquet.WithVersion(version), parquet.WithDataPageSize(LargeSize-1))
 	p.WriteBatchValues(writer, nil, nil)
+	p.NotEqual(int64(0), writer.TotalBytesWritten())
```
Comment (zeroshade) [inline go/parquet/file/column_writer_test.go:450]: I believe there's a `NotZero` you can use which would be more explicit

File: go/parquet/file/column_writer_test.go (hunk 1 above)
Comment (matthewmcnew) [reply go/parquet/file/column_writer_test.go]: Originally, I thought it was needed to ensure that a data page was written but, the smallsize works. Updated.

**Review by zeroshade — APPROVED** [review]
LGTM
