### PR TITLE
GH-35789: [C++] Remove check_overflow from CumulativeSumOptions

### LINKED ISSUE #35789: [C++] cumulative_sum ignores CumulativeSumOptions::check_overflow
### Describe the bug, including details regarding any error messages, version, and platform.

There are two variants of cumsum, `cumulative_sum` always wraps around on overflow and `cumulative_sum` always return `Status::Invalid` on overflow, regardless of the `check_overflow` parameter in CumulativeSumOptions.
For example:
```cpp
CumulativeSumOptions options(/*start=*/0, /*skip_nulls=*/true, /*check_overflow=*/true);
auto res = CallFunction("cumulative_sum", {ArrayFromJSON(int8(), "[127, 1]")}, &options);
std::cout << res->make_array()->ToString() << std::endl;
// prints [127, -128], but user might expect an error returned.
```

The document of `cumulative_sum` also doesn't memtion `check_overflow` at all, and `check_overflow` is not exposed to  pyarrow. So I believe the best approach to avoid confusion is to remove `check_overflow` from CumulativeSumOptions.

The only place where `check_overflow` is used is in the convenience function `CumulativeSum` defined in api_vector.h, which calls `cumulative_sum_checked` or `cumulative_sum` depending on the parameter. It can be replaced by a bool parameter in the convenience function.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by js8544**
### Rationale for this change

There are two variants of cumsum, `cumulative_sum` always wraps around on overflow and `cumulative_sum_checked` always return `Status::Invalid` on overflow, regardless of the `check_overflow` parameter in CumulativeSumOptions.
For example:
```cpp
CumulativeSumOptions options(/*start=*/0, /*skip_nulls=*/true, /*check_overflow=*/true);
auto res = CallFunction("cumulative_sum", {ArrayFromJSON(int8(), "[127, 1]")}, &options);
std::cout << res->make_array()->ToString() << std::endl;
// prints [127, -128], but user might expect an error returned.
```

I believe it's more of a ambiguity rather than a bug. The document of `cumulative_sum` also doesn't mention `check_overflow` at all, and `check_overflow` is not exposed to pyarrow. So IMO the best approach to avoid confusion is to remove `check_overflow` from CumulativeSumOptions.

The only place where `check_overflow` is used is in the C++ convenience function `CumulativeSum` defined in api_vector.h, which calls `cumulative_sum_checked` or `cumulative_sum` depending on the parameter. It can be replaced by a bool parameter in the C++ convenience function.

### What changes are included in this PR?

1. `check_overflow` is removed from CumulativeSumOptions.
2. Add a bool check_overflow parameter to the C++ convenience function CumulativeSum.

### Are these changes tested?

It doesn't affect the current tests.

### Are there any user-facing changes?

Yes, but only the C++ convenience function because check_overflow is not used in the kernel implementation and not exposed to pyarrow anyways.

* Closes: #35789

### CODE REVIEW

**Comment by pitrou** [comment]
> There are two variants of cumsum, `cumulative_sum` always wraps around on overflow and `cumulative_sum` always return `Status::Invalid` on overflow,

This does not seem to make sense to me, is there a typo?

**Comment by pitrou** [comment]
Regardless, the unused option is misleading, so I agree with removing it.

**Comment by js8544** [comment]
> > There are two variants of cumsum, `cumulative_sum` always wraps around on overflow and `cumulative_sum` always return `Status::Invalid` on overflow,
> 
> This does not seem to make sense to me, is there a typo?

Sorry! It's a typo indeed. I meant `cumulative_sum_checked`.

File: cpp/src/arrow/compute/api_vector.h [hunk 1]
```diff
@@ -601,7 +596,7 @@ ARROW_EXPORT
 Result<Datum> CumulativeSum(
     const Datum& values,
     const CumulativeSumOptions& options = CumulativeSumOptions::Defaults(),
-    ExecContext* ctx = NULLPTR);
+    bool check_overflow = false, ExecContext* ctx = NULLPTR);
```
Comment (pitrou) [inline cpp/src/arrow/compute/api_vector.h:599]: Can you document the  additional param in the docstring above?
Also, can you add a small test that the param is taken into account?

**Review by pitrou — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/compute/api_vector.h (hunk 1 above)
Comment (js8544) [reply cpp/src/arrow/compute/api_vector.h:606]: There were no doc for CumulativeSum above... But I added one anyways.
Also added a small test.

**Review by pitrou — APPROVED** [review]
Thanks for this @js8544 . Let's just wait for CI now.

**Comment by js8544** [comment]
The CI failure looks weird. I pushed an empty commit to trigger a rerun.

**Comment by pitrou** [comment]
The CI failure was probably unrelated, but let's wait for it.
