### PR TITLE
GH-49003: [C++] Don't consider `out_of_range` an error in float parsing

### LINKED ISSUE #49003: [Python] CSV reader returns different values in 23.0.0
### Describe the bug, including details regarding any error messages, version, and platform.

This is currently causing failures on the pandas CI.

```python
import pyarrow.csv

table = pyarrow.csv.read_csv(io.BytesIO(f"data\n10E-617".encode()))
print(table)
# pyarrow.Table  <-- pyarrow 22.0.0
# data: double
# ----
# data: [[0]]

# pyarrow.Table  <-- pyarrow 23.0.0
# data: string
# ----
# data: [["10E-617"]]
```

It's not clear to me if this was an intentional change. The only thing that looked possibly related from the release notes was

https://github.com/apache/arrow/pull/47925

but I haven't bisected to find if this was the cause.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by Alvaro-Kothe**
### Rationale for this change
This PR restores the behavior previous to version 23 for floating-point parsing on overflow and subnormal.

`fast_float` didn't assign an error code on overflow in version `3.10.1` and assigned `±Inf` on overflow and `0.0` on subnormal. With the update to version `8.1`, it started to assign `std::errc::result_out_of_range` in such cases. 

### What changes are included in this PR?
Ignores `std::errc::result_out_of_range` and produce `±Inf` / `0.0` as appropriate instead of failing the conversion.

### Are these changes tested?
Yes. Created tests for overflow with positive and negative signed mantissa, and also created tests for subnormal, all of them for binary{16,32,64}.

### Are there any user-facing changes?
It's a user facing change. The CSV reader on version `libarrow==23` was assigning them as strings, while before it was parsing it as `0` or `+- inf`.

With this patch, the CSV reader in PyArrow outputs:

```python
>>> import pyarrow
>>> import pyarrow.csv
>>> import io
>>> table = pyarrow.csv.read_csv(io.BytesIO(f"data\n10E-617\n10E617\n-10E617".encode()))
>>> print(table)
pyarrow.Table
data: double
----
data: [[0,inf,-inf]]
```

Closes #49003 

* GitHub Issue: #49003

### CODE REVIEW

File: cpp/src/arrow/util/value_parsing.cc [hunk 1]
```diff
@@ -35,15 +35,17 @@ bool StringToFloat(const char* s, size_t length, char decimal_point, float* out)
       ::arrow_vendored::fast_float::chars_format::general, decimal_point};
   const auto res =
       ::arrow_vendored::fast_float::from_chars_advanced(s, s + length, *out, options);
-  return res.ec == std::errc() && res.ptr == s + length;
+  return (res.ec == std::errc() || res.ec == std::errc::result_out_of_range) &&
```
Comment (WillAyd) [inline cpp/src/arrow/util/value_parsing.cc]: Nit on readability - I think it would help to break up this line. Something like:

```cpp
const auto is_allowed_ec = res.ec == std::errc() || res.ec == std::errc::result_out_of_range;
return is_allowed_ec && res.ptr = s + length;
```

**Review by WillAyd — COMMENTED** [review]
lgtm @pitrou

File: cpp/src/arrow/util/value_parsing.cc (hunk 1 above)
Comment (Alvaro-Kothe) [reply cpp/src/arrow/util/value_parsing.cc]: Definitely it's better. I also took the liberty to store the pointer comparison in an auxiliary variable in favor of readability.

**Review by WillAyd — APPROVED** [review]

File: cpp/src/arrow/util/value_parsing_test.cc [hunk 2]
```diff
@@ -141,6 +141,9 @@ TEST(StringConversion, ToFloat) {
   AssertConversion<FloatType>("0", 0.0f);
   AssertConversion<FloatType>("-0.0", -0.0f);
   AssertConversion<FloatType>("-1e20", -1e20f);
+  AssertConversion<FloatType>("4e38", std::numeric_limits<float>::infinity());
+  AssertConversion<FloatType>("-4e38", -std::numeric_limits<float>::infinity());
+  AssertConversion<FloatType>("1e-46", 0.0f);
```
Comment (pitrou) [inline cpp/src/arrow/util/value_parsing_test.cc:146]: Can you also test negative zeros?

**Review by pitrou — CHANGES_REQUESTED** [review]
Thanks a lot for this @Alvaro-Kothe . I agree this looks good on the principle, just one comment.

File: cpp/src/arrow/util/value_parsing_test.cc (hunk 2 above)
Comment (Alvaro-Kothe) [reply cpp/src/arrow/util/value_parsing_test.cc:146]: Done

**Review by pitrou — APPROVED** [review]
Thanks a lot for fixing this @Alvaro-Kothe !

**Comment by pitrou** [comment]
CI failure is unrelated, I'll merge. @raulcd

**Comment by raulcd** [comment]
> CI failure is unrelated, I'll merge. @raulcd

Thanks! I've cherry-picked it into the 23.0.1 maintenance branch.
