### PR TITLE
GH-36708: [C++] Fully calculate null-counts so the REE allocations make sense

### LINKED ISSUE #36708: [C++] `run_end_encode` segfaults on arrays with an all-set validity buffer
### Describe the bug, including details regarding any error messages, version, and platform.

```python
import pyarrow as pa, pyarrow.compute as pc, pyarrow.dataset as ds

ds.write_dataset(pa.table({'': pa.repeat(1, 10)}), 'temp', format='parquet')
(column,) = ds.dataset('temp').to_table()

assert pc.run_end_encode(column.combine_chunks())
pc.run_end_encode(column)  # <- segfaults
```
Seems to only reproduce when the array is read. Tested on the latest nightly build: 13.0.0.dev516.

### Component(s)

C++, Python

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

When `has_validity_buffer` is true, we expect validity buffers to be allocated, but if null_count is calculated and ends up being 0, `ArrayData::Make()` will sneakily remove the validity buffer from the physical array for us and the assumption that it exists stops holding and causes a crash.

Forcing `null_count` calculation with `input.GetNullCount()` ensures `has_validity_buffer` won't be `true` if the `null_count` on the input ends up being 0.

### What changes are included in this PR?

The fix and tests to reproduce it.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #36708

### CODE REVIEW

**Comment by felipecrv** [comment]
@kou

**Comment by mapleFU** [comment]
So this is because that REE ( https://arrow.apache.org/docs/format/Columnar.html#run-end-encoded-layout ) handling null with `values` validity, and when doesn't has null, it expect `values` to has a `validity` bitmap?

File: cpp/src/arrow/compute/kernels/ree_util_internal.cc [hunk 1]
```diff
@@ -60,6 +60,7 @@ Result<std::shared_ptr<ArrayData>> PreallocateRunEndsArray(
 Result<std::shared_ptr<ArrayData>> PreallocateValuesArray(
     const std::shared_ptr<DataType>& value_type, bool has_validity_buffer, int64_t length,
     int64_t null_count, MemoryPool* pool, int64_t data_buffer_size) {
+  DCHECK(!has_validity_buffer || null_count != 0);
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/ree_util_internal.cc:63]: It's difficult to understand for me... How about this style?

```suggestion
  DCHECK(!(has_validity_buffer && null_count == 0));
```

And how about adding the pre-condition in the doc as a comment here too?

File: cpp/src/arrow/compute/kernels/ree_util_internal.cc [hunk 2]
```diff
@@ -79,7 +80,10 @@ Result<std::shared_ptr<ArrayData>> PreallocateValuesArray(
   } else {
     values_data_buffers = {std::move(validity_buffer), std::move(values_buffer)};
   }
-  return ArrayData::Make(value_type, length, std::move(values_data_buffers), null_count);
+  auto data =
+      ArrayData::Make(value_type, length, std::move(values_data_buffers), null_count);
+  DCHECK(!has_validity_buffer || data->buffers[0] != NULLPTR);
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/ree_util_internal.cc:85]: We don't need to use `NULLPTR` in `.cc`.

And how about using this style?

```suggestion
  DCHECK(!(has_validity_buffer && data->buffers[0]));
```

(Post-condition as a comment will help use here too.)

**Review by kou — APPROVED** [review]
+1

File: cpp/src/arrow/compute/kernels/ree_util_internal.cc [hunk 3]
```diff
@@ -79,7 +80,10 @@ Result<std::shared_ptr<ArrayData>> PreallocateValuesArray(
...
+  return {std::move(data)};
```
[the remark this answers is not in the document]
Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/ree_util_internal.cc:86]: I don't really know for sure. `{std::move(data)}` is to make sure I'm constructing `Result` with an r-value. But I guess it's unnecessary because `data` is part of a `return` expression.

File: cpp/src/arrow/compute/kernels/ree_util_internal.cc (hunk 1 above)
Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/ree_util_internal.cc:63]: `!condition || consequence` is the more direct equivalent of `condition implies consequence`.

I'm going to add a comment saying `has_validity_buffer implies null_count != 0`.

https://en.wikipedia.org/wiki/Logical_equivalence#Logical_equivalences_involving_conditional_statements

Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/ree_util_internal.cc:63]: The more I think of it, I realize I can remove the `has_validity_buffer` parameter and infer it completely from the `null_count`.

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc [hunk 4]
```diff
@@ -254,7 +254,7 @@ struct RunEndEncodeExec {
       return RunEndEncodeNullArray(TypeTraits<RunEndType>::type_singleton(), ctx,
                                    input_array, result);
     } else {
-      const bool has_validity_buffer = input_array.MayHaveNulls();
+      const bool has_validity_buffer = input_array.GetNullCount() > 0;
```
Comment (felipecrv) [inline cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:257]: @mapleFU this is the fix to the issue. `MayHaveNulls` was returning `true` here because the validity bitmap exists, but down the road, when the REE is allocated, validity buffer was assumed to also exist in the allocated output. When, in fact, it didn't actually exist because `null_count == 0` gets that buffer cleared.

File: cpp/src/arrow/compute/kernels/ree_util_internal.cc (hunk 1 above)
Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/ree_util_internal.cc:63]: I'm removing `null_count` instead and having the callers change the `null_count`s from `kUnknownNullCount` to the correct value when they see fit. Seems like a more robust way to guarantee correctness.

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc [hunk 5]
```diff
@@ -196,17 +198,26 @@ class RunEndEncodeImpl {
...
     // Initialize the output pointers
     auto* output_run_ends =
         output_array_data->child_data[0]->template GetMutableValues<RunEndCType>(1, 0);
     auto* output_values_array_data = output_array_data->child_data[1].get();
+    // Set the null_count on the physical array
+    DCHECK(!has_validity_buffer || output_values_array_data->buffers[0])
+        << "has_validity_buffer implies a validity buffer is allocated";
+    DCHECK(output_values_array_data->null_count == kUnknownNullCount ||
+           physical_null_count == 0);
+    output_values_array_data->null_count = physical_null_count;
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:220]: How about adding "caller must set values' null_count explicitly" or something to `PreallocateREEArray()` document?

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc [hunk 6]
```diff
@@ -196,17 +198,26 @@ class RunEndEncodeImpl {
...
+            std::move(ree_type), has_validity_buffer, /*logical_length=*/input_length,
+            /*physical_length=*/num_output_runs, ctx_->memory_pool(), data_buffer_size));
 
     // Initialize the output pointers
     auto* output_run_ends =
         output_array_data->child_data[0]->template GetMutableValues<RunEndCType>(1, 0);
     auto* output_values_array_data = output_array_data->child_data[1].get();
+    // Set the null_count on the physical array
+    DCHECK(!has_validity_buffer || output_values_array_data->buffers[0])
+        << "has_validity_buffer implies a validity buffer is allocated";
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:217]: Why do we do this in caller not in `PreallocateREEValues()`?
It seems that `PreallocateREEValues()` is responsible for this.

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc [hunk 7]
```diff
@@ -196,17 +198,26 @@ class RunEndEncodeImpl {
...
+    DCHECK(output_values_array_data->null_count == kUnknownNullCount ||
+           physical_null_count == 0);
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:219]: Is this useful?
It seems that `output_values_array_data->null_count == kUnknownNullCount` is always true because `PreallocateREEValues()` uses `kUnknownNullCount` unconditionally.

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc [hunk 8]
```diff
@@ -398,17 +409,19 @@ class RunEndDecodeImpl {
...
+                                         length, ctx_->memory_pool(), data_buffer_size));
 
     int64_t output_null_count = 0;
     if (length > 0) {
       RunEndDecodingLoop<RunEndType, ValueType, has_validity_buffer> loop(
           input_array_, output_array_data.get());
       output_null_count = length - loop.ExpandAllRuns();
     }
+    DCHECK(output_array_data->null_count == kUnknownNullCount ||
+           output_array_data->null_count == 0);
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:424]: Is this useful?
It seems that this just checks a return value of `PreallocateValuesArray()`. If this is a post-condition of `PreallocateValuesArray()`, how about doing this in `PreallocateValuesArray()` not in callers?

**Comment by mapleFU** [comment]
Personally I think `has_validity_buffer` would better changed to `has_null`, the name would be better here.

**Comment by felipecrv** [comment]
> Personally I think `has_validity_buffer` would better changed to `has_null`, the name would be better here.

The general theme for the `has_validity_buffer` across the kernel and utilities is about presence of the buffer that will be written to. We can actually avoid computing the null count if we are OK with sometimes producing `11111...` bitmaps which might be an efficiency gain in the future.

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc [hunk 9]
```diff
@@ -196,17 +198,26 @@ class RunEndEncodeImpl {
         /*output_run_ends=*/NULLPTR);
     std::tie(num_valid_runs, num_output_runs, data_buffer_size) =
         counting_loop.CountNumberOfRuns();
+    const int64_t physical_null_count = num_output_runs - num_valid_runs;
```
[the remark this answers is not in the document]
Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:201]: Done manually now.

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc (hunk 5 above)
Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:220]: The caller doesn't necessarily have to set it, leaving it as `kUnknownNullCount` is fine, but I will document this.

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc (hunk 8 above)
Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:424]: Same as above. I'm removing the DCHECK to reduce the noise here.

**Review by kou — APPROVED** [review]
+1

I think that we can merge this after @mapleFU also approves these changes.

**Review by mapleFU — APPROVED** [review]
So this will first create a `ArrayData` with `kUnkownNullCount`, and explicit set using `physical_null_count`?

**Comment by felipecrv** [comment]
> So this will first create a `ArrayData` with `kUnkownNullCount`, and explicit set using `physical_null_count`?

Yes. The REE pre-allocation doesn't have to be concerned about setting the null_count. It's only concerned about allocating the memory.

**Comment by felipecrv** [comment]
CI failures are unrelated (linter errors in R code).

@pitrou can you merge this PR?

**Comment by mapleFU** [comment]
By the way, should this patch be a blocker in 13.0?

**Comment by felipecrv** [comment]
> By the way, should this patch be a blocker in 13.0?

I don't think so. REEs are not used that much and this is a bit of a corner case.

**Comment by felipecrv** [comment]
I will do a rebase and force push to see if these CI failures go away.

**Review by kou — APPROVED** [review]
+1

I'll merge this because nobody objects it.
