### PR TITLE
GH-39933: [R] Fix pointer conversion to Python for latest reticulate

### LINKED ISSUE #39933: [CI][R][Python] R and Python integration's tests failed
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/7760862085/job/21168058007#step:6:32228

<details>

```text
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-python-flight.R:32:5'): flight_put ─────────────────────────────
<python.builtin.ValueError/python.builtin.Exception/python.builtin.BaseException/python.builtin.object/error/condition>
Error in `py_call_impl(callable, call_args$unnamed, call_args$named)`: ValueError: PyCapsule_GetPointer called with incorrect name
Run `reticulate::py_last_error()` for details.
Backtrace:
    ▆
 1. └─arrow::flight_put(client, example_data, path = flight_obj) at test-python-flight.R:32:5
 2.   ├─reticulate::r_to_py(data)
 3.   └─arrow:::r_to_py.Table(data)
 4.     ├─reticulate::r_to_py(as_record_batch_reader(x), convert = FALSE)
 5.     └─arrow:::r_to_py.RecordBatchReader(...)
 6.       └─pa$lib$RecordBatchReader$`_import_from_c`(pyarrow_compatible_pointer(stream_ptr))
 7.         └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
── Error ('test-python-flight.R:42:5'): flight_put with max_chunksize ──────────
<python.builtin.ValueError/python.builtin.Exception/python.builtin.BaseException/python.builtin.object/error/condition>
Error in `py_call_impl(callable, call_args$unnamed, call_args$named)`: ValueError: PyCapsule_GetPointer called with incorrect name
Run `reticulate::py_last_error()` for details.
Backtrace:
    ▆
 1. └─arrow::flight_put(client, example_data, path = flight_obj, max_chunksize = 1) at test-python-flight.R:42:5
 2.   ├─reticulate::r_to_py(data)
 3.   └─arrow:::r_to_py.Table(data)
 3.   └─pa$Field$`_import_from_c`(pyarrow_compatible_pointer(schema_ptr))
 4.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
── Error ('test-python.R:157:3'): RecordBatchReader to python ──────────────────
<python.builtin.ValueError/python.builtin.Exception/python.builtin.BaseException/python.builtin.object/error/condition>
Error in `py_call_impl(callable, call_args$unnamed, call_args$named)`: ValueError: PyCapsule_GetPointer called with incorrect name
Run `reticulate::py_last_error()` for details.
Backtrace:
    ▆
 1. ├─reticulate::r_to_py(reader) at test-python.R:157:3
 2. └─arrow:::r_to_py.RecordBatchReader(reader)
 3.   └─pa$lib$RecordBatchReader$`_import_from_c`(pyarrow_compatible_pointer(stream_ptr))
 4.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
── Error ('test-python.R:177:3'): RecordBatchReader from python ────────────────
<python.builtin.ValueError/python.builtin.Exception/python.builtin.BaseException/python.builtin.object/error/condition>
Error in `py_call_impl(callable, call_args$unnamed, call_args$named)`: ValueError: PyCapsule_GetPointer called with incorrect name
Run `reticulate::py_last_error()` for details.
Backtrace:
    ▆
 1. ├─reticulate::r_to_py(reader) at test-python.R:177:3
 2. └─arrow:::r_to_py.RecordBatchReader(reader)
 3.   └─pa$lib$RecordBatchReader$`_import_from_c`(pyarrow_compatible_pointer(stream_ptr))
 4.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
```

</details>

The last success commit: https://github.com/apache/arrow/commit/2721134715b7dedfa2715bcf47548728ff702d5a
The first failed commit: https://github.com/apache/arrow/commit/b684028dfbeeed85d132a1249449a85877d796b1

Commits between them:
* https://github.com/apache/arrow/commit/44d5597a0e8a4d635f1aec82ba885f61b5c17829
* https://github.com/apache/arrow/commit/3d45ac96534fc76b820b488aa02182e6b93a388f
* https://github.com/apache/arrow/commit/a1c1773b724e4d78faf9a097247c7e976cd2cbfa
* https://github.com/apache/arrow/commit/4ceb66101382d74c6ef73ff546fad10183ab58d8

@jorisvandenbossche Could you take a look at this PyCapsule related error messages?

### Component(s)

Continuous Integration, Python, R

### PR DESCRIPTION
**Pull request by paleolimbot**
### Rationale for this change

The integration tests and documentation build is failing

### What changes are included in this PR?

Instead of relying on how reticulate converts an R external pointer, use a Python integer instead. We can't use an R integer (because they're only 32 bits); we can't use an R double (because the static cast to/from uintptr_t is a bit iffy); however, we can use Python to convert a string to Python integer. This is probably how I should have written it the first time but it didn't occur to me at the time.

### Are these changes tested?

Yes, covered by existing tests.

### Are there any user-facing changes?

No
* Closes: #39933

### CODE REVIEW

File: r/R/python.R [hunk 1]
```diff
@@ -339,15 +339,9 @@ install_pyarrow <- function(envname = NULL, nightly = FALSE, ...) {
...
-  # remove trailing .devXXX because it won't work with package_version()
-  pyarrow_version <- package_version(gsub("\\.dev.*?$", "", version_string))
-
-  # pyarrow pointers changed in version 7.0.0
-  if (pyarrow_version >= "7.0.0") {
-    return(ptr)
-  } else {
-    return(external_pointer_addr_double(ptr))
-  }
+  # Workaround because there is no built-in way to send a 64-bit integer
```
Comment (pitrou) [inline r/R/python.R:342]: Can you add a reference to the GH issue?

**Review by pitrou — APPROVED** [review]
LGTM
