### PR TITLE
GH-35270: [C++] Use Buffer instead of raw buffer in hash join internals

### LINKED ISSUE #35270: Memory leak in SwissTable::grow_double()
### Describe the bug, including details regarding any error messages, version, and platform.

There are two allocation in grow_double. If the first suceeded but the second failed, the function will return without Free the first buffer 
```
RETURN_NOT_OK(pool_->Allocate(block_size_total_after, &blocks_new));
RETURN_NOT_OK(pool_->Allocate(hashes_size_total_after, &hashes_new_8B));
```

https://github.com/apache/arrow/blob/main/cpp/src/arrow/compute/key_map.cc#L670

### Component(s)

C++

### PR DESCRIPTION
**Pull request by westonpace**
### Rationale for this change

The current code has two storage buffers in the key map which are allocated with MemoryPool::Allocate which does not use smart pointers.  This could have led to a potential memory leak in an OOM scenario where the first allocate fails and it also led to some convoluted code keeping track of the previously allocated size in order to properly call Free.

Furthermore, it seems that this key map could have been getting potentially copied in the swiss join code.  While that was probably not happening (since the copy happened before the key map was initialized) it is still an easy recipe for an accidental double-free later on as we maintain the class.

### What changes are included in this PR?

Those raw buffers are changed to std::shared_ptr<Buffer> to avoid these issues.

### Are these changes tested?

Somewhat, the existing unit tests should ensure we didn't cause a regression.  I didn't introduce a regression test to introduce this potential bug because it would be very difficult to do so.

### Are there any user-facing changes?

No

* Closes: #35270

### CODE REVIEW

File: cpp/src/arrow/compute/key_map.h [hunk 1]
```diff
@@ -226,12 +228,12 @@ class ARROW_EXPORT SwissTable {
   // ---------------------------------------------------
   // * Empty bucket has value 0x80. Non-empty bucket has highest bit set to 0.
   //
-  uint8_t* blocks_;
+  std::shared_ptr<Buffer> blocks_;
 
   // Array of hashes of values inserted into slots.
   // Undefined if the corresponding slot is empty.
   // There is 64B padding at the end.
```
Comment (mapleFU) [inline cpp/src/arrow/compute/key_map.h:235]: Should here still mention padding here? Since Buffer already ensure padding?

**Review by mapleFU — APPROVED** [review]

File: cpp/src/arrow/compute/key_map.h (hunk 1 above)
Comment (westonpace) [reply cpp/src/arrow/compute/key_map.h:235]: Buffer ensures that allocations are aligned (and I think, at least 64 bytes) but I don't know if it actually guarantees padding.  I think this buffer needs to go 64 bytes past the end regardless of the size which is a slightly different requirement.

Comment (mapleFU) [reply cpp/src/arrow/compute/key_map.h:235]: Got it, padding and aligned are different, I missed it previously. the patch LGTM

**Review by pitrou — APPROVED** [review]
+1, nice robustness improvement
