### PR TITLE
GH-39672: [Go] Time to Date32/Date64 conversion issues for non-UTC timezones

### LINKED ISSUE #39672: [Go] Time to Date32 / Date64 conversion incorrect for non-UTC timezone
### Describe the bug, including details regarding any error messages, version, and platform.

During release verification, a unit test was failing with:

```
ok      [github.com/apache/arrow/go/v15/arrow/flight/flightsql](http://github.com/apache/arrow/go/v15/arrow/flight/flightsql)   4.990s
1970-01-01 12:00:00 +0000 UTC
--- FAIL: Test_fromArrowType (0.00s)
    --- FAIL: Test_fromArrowType/fromArrowType_date64_f16-d64 (0.00s)
        utils_test.go:104: test failed, wanted time.Time 2024-01-17
00:00:00 +0000 UTC got time.Time 2024-01-18 00:00:00 +0000 UTC
FAIL
FAIL    [github.com/apache/arrow/go/v15/arrow/flight/flightsql/driver](http://github.com/apache/arrow/go/v15/arrow/flight/flightsql/driver)
 5.821s
```

### Component(s)

Go

### PR DESCRIPTION
**Pull request by zeroshade**
A failing unit test in release verification led to discovering an issue with timestamp to date conversions for non-utc timezones. 

Upon some investigation I was able to determine that it was the conflation of casting conversion behavior (normalize to cast a Timestamp to a Date) vs flat conversion. I've fixed this conflation of concerns and the version of the methods which are exported properly converts non-UTC timezones to dates without affecting Casting behavior.

### Are these changes tested?
yes

### Are there any user-facing changes?
The methods `Date32FromTime` and `Date64FromTime` will properly handle timezones now.

* Closes: #39672

### CODE REVIEW

**Comment by zeroshade** [comment]
@raulcd this should get cherry-picked into a new RC to fix the failing test

**Review by raulcd — APPROVED** [review]
Test looks good to me. I am not an expert on go so I am not entirely sure why the changes on `datatype_fixedwidth.go` are required but as per the test I am ok with the change :)

File: go/arrow/datatype_fixedwidth.go [hunk 1]
```diff
@@ -88,11 +84,7 @@ func (d Date32) FormattedString() string {
 
 // Date64FromTime returns a Date64 value from a time object
 func Date64FromTime(t time.Time) Date64 {
-	if _, offset := t.Zone(); offset != 0 {
-		// properly account for timezone adjustments before we calculate
-		// the actual value by adjusting the time and converting to UTC
-		t = t.Add(time.Duration(offset) * time.Second).UTC()
-	}
+	t = t.In(time.UTC)
```
Comment (lidavidm) [inline go/arrow/datatype_fixedwidth.go:87]: Time.Unix() claims it is independent of the location, is this strictly needed?

Comment (lidavidm) [reply go/arrow/datatype_fixedwidth.go:87]: Since in theory if this change were needed, the adjustment above and the adjustment here would be the same?

File: go/arrow/compute/internal/kernels/cast_temporal.go [hunk 2]
```diff
@@ -125,6 +129,10 @@ func TimestampToDate64(ctx *exec.KernelCtx, batch *exec.ExecSpan, out *exec.Exec
 
 	return ScalarUnaryNotNull(func(_ *exec.KernelCtx, arg0 arrow.Timestamp, _ *error) arrow.Date64 {
 		tm := fnToTime(arg0)
+		if _, offset := tm.Zone(); offset != 0 {
+			// normalize the tm
+			tm = tm.Add(time.Duration(offset) * time.Second).UTC()
+		}
```
Comment (lidavidm) [inline go/arrow/compute/internal/kernels/cast_temporal.go:135]: ~this is effectively taking a timestamp with timezone and turning it into a naive timestamp showing the date in the former timezone (but marked as UTC)?

**Review by lidavidm — APPROVED** [review]

File: go/arrow/compute/internal/kernels/cast_temporal.go (hunk 2 above)
Comment (zeroshade) [reply go/arrow/compute/internal/kernels/cast_temporal.go:135]: Yes. Because as you pointed out above, when we call `.Unix()` it returns the result *not according to the location* but we want it to represent the date in the timezone's location, without having a timezone mark associated. This matches the C++ implementation of the casting in acero  (which is where I got the idea)

Comment (lidavidm) [reply go/arrow/compute/internal/kernels/cast_temporal.go:135]: Ok, cool. This just confuses me since I'm used to Java etc. where these are separate types ^_^

File: go/arrow/datatype_fixedwidth.go (hunk 1 above)
Comment (zeroshade) [reply go/arrow/datatype_fixedwidth.go:87]: Good point,  you're absolutely right. I'll update and remove those lines

**Review by lidavidm — APPROVED** [review]
