### PR TITLE
GH-31735: [Docs][Release] Move release verification guide to developers documentation

### LINKED ISSUE #31735: [Wiki] Release verification howto is obsolete
https://cwiki.apache.org/confluence/display/ARROW/How+to+Verify+Release+Candidates#HowtoVerifyReleaseCandidates-LinuxandmacOS

The example commands are wrong.
E.g., 
```bash
TEST_DEFAULT=0 TEST_SOURCE=1 TEST_CPP=1 verify-release-candidate.sh source $VERSION $RC_NUM
```

should be changed to
```bash
TEST_DEFAULT=0 TEST_CPP=1 verify-release-candidate.sh $VERSION $RC_NUM
```

**Reporter**: [Yibo Cai](https://issues.apache.org/jira/browse/ARROW-16353) / @cyb70289

<sub>**Note**: *This issue was originally created as [ARROW-16353](https://issues.apache.org/jira/browse/ARROW-16353). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

The current verification guide is obsolete and should not be on the wiki.

### What changes are included in this PR?

Adding a new page with the release verification information.

### Are these changes tested?

The documentation will be generated and will use the preview-docs job.

### Are there any user-facing changes?

Yes but not relevant in terms of code changes.
* Closes: #31735

### CODE REVIEW

File: dev/release/02-source.sh [hunk 1]
```diff
@@ -202,7 +202,7 @@ The vote will be open for at least 72 hours.
 [10]: https://apache.jfrog.io/artifactory/arrow/python-rc/${version}-rc${rc}
 [11]: https://apache.jfrog.io/artifactory/arrow/ubuntu-rc/
 [12]: https://github.com/apache/arrow/blob/${release_hash}/CHANGELOG.md
-[13]: https://cwiki.apache.org/confluence/display/ARROW/How+to+Verify+Release+Candidates
+[13]: https://arrow.apache.org/docs/developers/release_verification.html
```
Comment (raulcd) [inline dev/release/02-source.sh:205]: We probably can change that. I will try to remember to update the vote thread email before sending it to point to the `dev` documentation for the 16.0.0 release.

File: docs/source/developers/release_verification.rst [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+      clang \
+      cmake \
+      libsqlite3-dev \
+      libssh-dev \
+      libyaml-dev \
+      llvm-dev \
+      python3-dev \
+      python3.10-venv
+
+   # Install ruby
```
Comment (raulcd) [inline docs/source/developers/release_verification.rst:105]: @kou I am trying to run a source verification from scratch on a new Ubuntu to take the notes on what is needed, these are the things that I have installed but I am currently having an issue on the `C GLib` source verification, any idea?
```
ubuntu@ip:~/arrow/dev/release$ tail -100f /tmp/arrow-15.0.0.XCn9G/c-glib-build/meson-logs/meson-log.txt
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=/tmp/arrow-15.0.0.XCn9G/c-glib-build/meson-private/cmake_gobject-introspection-1.0/CMakeMesonToolchainFile.cmake"
  - "."
  - "-DCMAKE_PREFIX_PATH=/tmp/arrow-15.0.0.XCn9G/install"
  -- Module search paths:    ['/', '/opt', '/tmp/arrow-15.0.0.XCn9G/install', '/usr', '/usr/local']
  -- CMake root:             /usr/share/cmake-3.22
  -- CMake architectures:    ['x86_64-linux-gnu']
  -- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share', '', 'lib/x86_64-linux-gnu']
Preliminary CMake check failed. Aborting.
Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)
Dependency lookup for arrow with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.
CMake binary for host machine is cached.

Determining dependency 'arrow' with CMake executable '/usr/bin/cmake'
CMake Toolchain: Calling CMake once to generate the compiler state
Calling CMake (['/usr/bin/cmake']) in /tmp/arrow-15.0.0.XCn9G/c-glib-build/meson-private/__CMake_compiler_info__ with:
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-G"
  - "Ninja"
  - "-DCMAKE_TOOLCHAIN_FILE=/tmp/arrow-15.0.0.XCn9G/c-glib-build/meson-private/__CMake_compiler_info__/CMakeMesonTempToolchainFile.cmake"
  - "."
  - "-DCMAKE_PREFIX_PATH=/tmp/arrow-15.0.0.XCn9G/install"
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Try CMake generator: auto
Calling CMake (['/usr/bin/cmake']) in /tmp/arrow-15.0.0.XCn9G/c-glib-build/meson-private/cmake_arrow with:
  - "-DNAME=arrow"
  - "-DARCHS=x86_64-linux-gnu"
  - "-DVERSION="
  - "-DCOMPS="
  - "-DSTATIC=False"
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=/tmp/arrow-15.0.0.XCn9G/c-glib-build/meson-private/cmake_arrow/CMakeMesonToolchainFile.cmake"
  - "."
  - "-DCMAKE_PREFIX_PATH=/tmp/arrow-15.0.0.XCn9G/install"
WARNING: Could not find and exact match for the CMake dependency arrow.

However, Meson found the following partial matches:

    ['Arrow::arrow_shared', 'Arrow::arrow_static', 'Arrow::arrow_bundled_dependencies']

Using imported is recommended, since this approach is less error prone
and better supported by Meson. Consider explicitly specifying one of
these in the dependency call with:

    dependency('arrow', modules: ['arrow::<name>', ...])

Meson will now continue to use the old-style arrow_LIBRARIES CMake
variables to extract the dependency information since no explicit
target is currently specified.


More info for the partial match targets:
CMake TARGET:
  -- name:      Arrow::arrow_shared
  -- type:      SHARED
  -- imported:  True
  -- properties: {
      'INTERFACE_COMPILE_FEATURES': ['cxx_std_17']
      'INTERFACE_INCLUDE_DIRECTORIES': ['/tmp/arrow-15.0.0.XCn9G/install/include']
      'IMPORTED_CONFIGURATIONS': ['RELEASE']
      'IMPORTED_LOCATION_RELEASE': ['/tmp/arrow-15.0.0.XCn9G/install/lib/libarrow.so.1500.0.0']
      'IMPORTED_SONAME_RELEASE': ['libarrow.so.1500']
     }
  -- tline: CMake TRACE: /tmp/arrow-15.0.0.XCn9G/install/lib/cmake/Arrow/ArrowTargets.cmake:54 add_library(['Arrow::arrow_shared', 'SHARED', 'IMPORTED'])
CMake TARGET:
  -- name:      Arrow::arrow_static
  -- type:      STATIC
  -- imported:  True
  -- properties: {
      'INTERFACE_COMPILE_FEATURES': ['cxx_std_17']
      'INTERFACE_INCLUDE_DIRECTORIES': ['/tmp/arrow-15.0.0.XCn9G/install/include']
      'INTERFACE_LINK_LIBRARIES': ['Arrow::arrow_bundled_dependencies', 'OpenSSL::Crypto', 'OpenSSL::SSL', 'ZLIB::ZLIB', 'dl', 'Threads::Threads', 'rt']
      'IMPORTED_CONFIGURATIONS': ['RELEASE']
      'IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE': ['C', 'CXX']
      'IMPORTED_LOCATION_RELEASE': ['/tmp/arrow-15.0.0.XCn9G/install/lib/libarrow.a']
     }
  -- tline: CMake TRACE: /tmp/arrow-15.0.0.XCn9G/install/lib/cmake/Arrow/ArrowTargets.cmake:62 add_library(['Arrow::arrow_static', 'STATIC', 'IMPORTED'])
CMake TARGET:
  -- name:      Arrow::arrow_bundled_dependencies
  -- type:      STATIC
  -- imported:  True
  -- properties: {
      'IMPORTED_CONFIGURATIONS': ['RELEASE']
      'IMPORTED_LOCATION_RELEASE': ['/tmp/arrow-15.0.0.XCn9G/install/lib/libarrow_bundled_dependencies.a']
     }
  -- tline: CMake TRACE: /tmp/arrow-15.0.0.XCn9G/install/lib/cmake/Arrow/ArrowConfig.cmake:128 add_library(['Arrow::arrow_bundled_dependencies', 'STATIC', 'IMPORTED'])
Dependency lookup for arrow with method 'cmake' failed: Dependency arrow not found: CMake: failed to guess a CMake target for arrow.
Try to explicitly specify one or more targets with the "modules" property.
Valid targets are:
['Threads::Threads', 'OpenSSL::Crypto', 'OpenSSL::SSL', 'ZLIB::ZLIB', 'Arrow::arrow_shared', 'Arrow::arrow_static', 'Arrow::arrow_bundled_dependencies', 'arrow_shared', 'arrow_static']
Run-time dependency arrow found: NO 

meson.build:80:10: ERROR: Dependency lookup for arrow with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.
```

Comment (assignUser) [reply docs/source/developers/release_verification.rst:105]: I think you need to install: https://packages.ubuntu.com/search?keywords=gobject-introspection

File: docs/source/developers/release.rst [hunk 3]
```diff
@@ -200,6 +200,8 @@ Verify the Release
     # on dev@arrow.apache.org. To regenerate the email template use
     SOURCE_DEFAULT=0 SOURCE_VOTE=1 dev/release/02-source.sh <version> <rc-number>
 
+See more about the verification process on :ref:`Release verification <release_verification>`
```
Comment (kou) [inline docs/source/developers/release.rst:203]: How about simplifying this?

```suggestion
See :ref:`release_verification` for details.
```

File: docs/source/developers/release_verification.rst (hunk 2 above)
Comment (kou) [reply docs/source/developers/release_verification.rst:105]: Yes. gobject-introspection is missing. We can install it by `libgirepository1.0-dev`.

FYI: We can use https://github.com/apache/arrow/blob/main/dev/release/setup-ubuntu.sh for this section.

Comment (raulcd) [reply docs/source/developers/release_verification.rst:109]: > FYI: We can use https://github.com/apache/arrow/blob/main/dev/release/setup-ubuntu.sh for this section.

You mean telling people to use `setup-ubuntu.sh` or as a base for this? Currently with the last commit I had a source verification successful and I plan to modify the documentation later a little to document only source verification to try and make the process simpler.

Comment (kou) [reply docs/source/developers/release_verification.rst:109]: The former: telling people to use `setup-ubuntu.sh`

If we use `setup-ubuntu.sh` in documentation too, we don't need to update both of `setup-ubuntu.sh` and documentation.

**Comment by raulcd** [comment]
@github-actions crossbow submit preview-docs

**Comment by raulcd** [comment]
@kou @assignUser should we add Windows instructions? I've tested source verification from scratch on Linux and macOS and added the required configuration.
Maybe we can merge and add Windows on a different ticket as it will take me some time to be able to do. I also want to re-review our verification process on another ticket as per the feedback received on this ML thread: https://lists.apache.org/thread/ogp9dthp124oq0fmvlyzvjorjsyom03v

**Comment by raulcd** [comment]
@github-actions crossbow submit preview-docs

**Comment by kou** [comment]
http://crossbow.voltrondata.com/pr_docs/39960/developers/release_verification.html

File: docs/source/developers/release_verification.rst [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+utility script can be used to set your Ubuntu system. This wil install
+the required packages to perform a source verification on a clean
+Ubuntu:
+
+.. code-block::
+
+   # From the arrow clone
+   popd dev/release
+   sudo ./setup-ubuntu.sh
+   pushd
```
Comment (kou) [inline docs/source/developers/release_verification.rst:95]:
```suggestion
   pushed dev/release
   sudo ./setup-ubuntu.sh
   popd
```

Comment (kou) [reply docs/source/developers/release_verification.rst:95]: Or:

```suggestion
   sudo dev/release/setup-ubuntu.sh
```

File: docs/source/developers/release_verification.rst [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+   brew bundle --file=c_glib/Brewfile
+   brew uninstall node
+   # You might need to add node, ruby java and maven to the PATH, follow
+   # instructions from brew after installing.
+   brew install node@20
+   brew install ruby
+   brew install openjdk
+   brew install maven
+   # libffi required for gobject-introspection gem
+   brew install libffi
```
Comment (kou) [inline docs/source/developers/release_verification.rst:114]: I think that this is needless because Homebrew's GObject Introspection uses system libffi: https://github.com/Homebrew/homebrew-core/blob/c8900f1b3f0483b602e948d2c5400e8ac870e690/Formula/g/gobject-introspection.rb#L33

```suggestion
```

**Review by kou — APPROVED** [review]
+1

We can defer the Windows part as a separated task.

File: docs/source/developers/release_verification.rst (hunk 5 above)
Comment (raulcd) [reply docs/source/developers/release_verification.rst:114]: without this my build was failing on a brand new M2. I can share the logs tomorrow if you want.

Comment (kou) [reply docs/source/developers/release_verification.rst:112]: Wow! Yes, please share the logs!

Comment (raulcd) [reply docs/source/developers/release_verification.rst:112]: After `brew uninstall libffi` this is the error I get:
```
Resolving dependencies...
Fetching power_assert 2.0.3
Fetching native-package-installer 1.1.9
Fetching pkg-config 1.5.6
Installing power_assert 2.0.3
Installing native-package-installer 1.1.9
Installing pkg-config 1.5.6
Fetching test-unit 3.6.2
Fetching glib2 4.2.0
Installing test-unit 3.6.2
Installing glib2 4.2.0 with native extensions
Fetching gobject-introspection 4.2.0
Installing gobject-introspection 4.2.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/private/var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O/apache-arrow-15.0.0/c_glib/vendor/bundle/ruby/3.3.0/gems/gobject-introspection-4.2.0/ext/gobject-introspection
/opt/homebrew/opt/ruby/bin/ruby extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... yes
checking for gobject-introspection-1.0... yes (1.78.1)
creating rbgiversion.h
creating gobject-introspection-enum-types.c
creating gobject-introspection-enum-types.h
creating ruby-gobject-introspection.pc
creating Makefile

current directory:
/private/var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O/apache-arrow-15.0.0/c_glib/vendor/bundle/ruby/3.3.0/gems/gobject-introspection-4.2.0/ext/gobject-introspection
make DESTDIR\= sitearchdir\=./.gem.20240216-45788-684atu sitelibdir\=./.gem.20240216-45788-684atu clean

current directory:
/private/var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O/apache-arrow-15.0.0/c_glib/vendor/bundle/ruby/3.3.0/gems/gobject-introspection-4.2.0/ext/gobject-introspection
make DESTDIR\= sitearchdir\=./.gem.20240216-45788-684atu sitelibdir\=./.gem.20240216-45788-684atu
compiling gobject-introspection-enum-types.c
compiling rb-gi-arg-info.c
In file included from rb-gi-arg-info.c:21:
In file included from ./rb-gi-private.h:24:
In file included from
/private/var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O/apache-arrow-15.0.0/c_glib/vendor/bundle/ruby/3.3.0/gems/glib2-4.2.0/ext/glib2/../../lib/rbgobject.h:27:
In file included from
/private/var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O/apache-arrow-15.0.0/c_glib/vendor/bundle/ruby/3.3.0/gems/glib2-4.2.0/ext/glib2/../../lib/rbgutil.h:26:
In file included from /opt/homebrew/Cellar/ruby/3.3.0/include/ruby-3.3.0/ruby/encoding.h:22:
/opt/homebrew/Cellar/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/encoding/ctype.h:82:46: warning: unused parameter 'enc' [-Wunused-parameter]
rb_enc_isascii(OnigCodePoint c, rb_encoding *enc)
                                             ^
In file included from rb-gi-arg-info.c:21:
In file included from ./rb-gi-private.h:28:
/opt/homebrew/Cellar/gobject-introspection/1.78.1/include/gobject-introspection-1.0/girffi.h:25:10: fatal error: 'ffi.h' file not found
#include <ffi.h>
         ^~~~~~~
1 warning and 1 error generated.
make: *** [rb-gi-arg-info.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/private/var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O/apache-arrow-15.0.0/c_glib/vendor/bundle/ruby/3.3.0/gems/gobject-introspection-4.2.0 for inspection.
Results logged to
/private/var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O/apache-arrow-15.0.0/c_glib/vendor/bundle/ruby/3.3.0/extensions/arm64-darwin-23/3.3.0/gobject-introspection-4.2.0/gem_make.out

  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/source/rubygems.rb:205:in `install'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:54:in `install'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:132:in `do_install'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:62:in `apply_func'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:54:in `process_queue'
  /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing gobject-introspection (4.2.0), and Bundler cannot continue.

In Gemfile:
  gobject-introspection
Failed to verify release candidate. See /var/folders/rr/t_15q7dx4_lf1nv0btypffcw0000gn/T/arrow-15.0.0.XXXXX.li0gqOMB3O for details.
```

Comment (kou) [reply docs/source/developers/release_verification.rst:112]: Thanks!

Could you show the output of `pkg-config --cflags gobject-introspection-1.0` on the environment?

Comment (raulcd) [reply docs/source/developers/release_verification.rst:112]: sure:
```
% pkg-config --cflags gobject-introspection-1.0
-I/opt/homebrew/Cellar/gobject-introspection/1.78.1/include/gobject-introspection-1.0 -I/opt/homebrew/Cellar/glib/2.78.4/include -I/opt/homebrew/Cellar/glib/2.78.4/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.78.4/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.42/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi
```

Comment (kou) [reply docs/source/developers/release_verification.rst:112]: Thanks!

It includes `-I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi`. It seems that the environment doesn't have `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/`.

Could you show the output of `ls -l /Library/Developer/CommandLineTools/SDKs/`?

But it's a bit strange. I think that a brand new M2 uses more recent version than 12... Could you also show the output of `sw_vers -productVersion`? Homebrew uses it to detect the version.

Comment (kou) [reply docs/source/developers/release_verification.rst:112]: Thanks. `MacOSX12.sdk -> MacOSX12.3.sdk` symbolic link doesn't exist. I think that it's a problem.

Comment (kou) [reply docs/source/developers/release_verification.rst:112]: On my Mac mini environment:

```console
$ ls -l /Library/Developer/CommandLineTools/SDKs
total 0
lrwxr-xr-x  1 root  wheel   14 12  2 05:05 MacOSX.sdk -> MacOSX14.0.sdk
drwxr-xr-x  7 root  wheel  224  8 21  2023 MacOSX12.3.sdk
lrwxr-xr-x  1 root  wheel   14  8 21  2023 MacOSX12.sdk -> MacOSX12.3.sdk
drwxr-xr-x  7 root  wheel  224 12  2 05:05 MacOSX13.3.sdk
lrwxr-xr-x  1 root  wheel   14 12  2 05:04 MacOSX13.sdk -> MacOSX13.3.sdk
drwxr-xr-x  7 root  wheel  224  9  1 04:12 MacOSX14.0.sdk
lrwxr-xr-x  1 root  wheel   14 12  2 05:04 MacOSX14.sdk -> MacOSX14.0.sdk
```

Could you try again after `sudo ln -s MacOSX12.3.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk`?

Comment (kou) [reply docs/source/developers/release_verification.rst:112]: (I'm not sure who created the `MacOSX${MAJOR_VERSION}.sdk` symbolic links. But I haven't done it manually.)

Comment (raulcd) [reply docs/source/developers/release_verification.rst:112]: @kou as per the PR, if you want I can remove the `brew install libffi` and we can keep investigating further the issue on a different GH issue so we can merge this initial documentation, are you ok with that?

Comment (kou) [reply docs/source/developers/release_verification.rst:112]: Yes. Let's do it! (We remove `brew install libffi` in this PR, merge this PR and open a new issue for this.)

Comment (raulcd) [reply docs/source/developers/release_verification.rst]: Done and created issue to follow up:
* https://github.com/apache/arrow/issues/40195

Comment (kou) [reply docs/source/developers/release_verification.rst]: Thanks!
