### PR TITLE
GH-37164: [Python] Attach Python stacktrace to errors in `ConvertPyError`

### LINKED ISSUE #37164: [Python] Attach Python stacktrace to errors in `ConvertPyError`
### Describe the bug, including details regarding any error messages, version, and platform.

We have an internal application that is using the `arrow::RecordBatchReader` with a Python generator (but in C++). Right now, when the Python generator raises an error, the stack trace disappears (e.g. in our code base we just see:

```
Python exception: AssertionError
```

without the stack trace.

I am not super familiar with C++ or the code, but I *think* the problem can be traced to this function:

https://github.com/apache/arrow/blob/750670e8c7c8b7985323f7866e4aa09be4232169/python/pyarrow/src/arrow/python/common.cc#L144-L153

which calls into

https://github.com/apache/arrow/blob/750670e8c7c8b7985323f7866e4aa09be4232169/python/pyarrow/src/arrow/python/common.cc#L91-L96

where we *only* attach the exception type name and no other information. My C++ is not very good, but how hard would it be to actually attach the full Python stacktrace inside the message whenever we hit a Python exception?

### Component(s)

Python

### PR DESCRIPTION
**Pull request by wjones127**
### Rationale for this change

Users might define Python generators that are used in RecordBatchReaders and then exported through the C Data Interface. However, if an error occurs in their generator, the stacktrace and message are currently swallowed in the current `ConvertPyError` implementation, which only provides the type of error. This makes debugging code that passed RBRs difficult.

### What changes are included in this PR?

Changes `ConvertPyError` to provide the fully formatted traceback in the error message.

### Are these changes tested?

Yes, added one test to validate the errors messages are propagated.

### Are there any user-facing changes?

This is a minor change in the error reporting behavior, which will provide more information.
* Closes: #37164

### CODE REVIEW

File: python/pyarrow/src/arrow/python/common.cc [hunk 1]
```diff
@@ -131,6 +138,34 @@ class PythonErrorDetail : public StatusDetail {
   }
 
  protected:
+  Result<std::string> FormatImpl() const {
+    PyAcquireGIL lock;
+
+    // Use traceback.format_exception()
+    OwnedRef traceback_module;
+    RETURN_NOT_OK(internal::ImportModule("traceback", &traceback_module));
```
Comment (AlenkaF) [inline python/pyarrow/src/arrow/python/common.cc:146]: It seems we are already retrieving the error indicator and saving the traceback in `PythonErrorDetail` class, but can be reading the code wrong.
Would it be possible to use `exc_traceback_.obj()` similar to `exc_type_.obj()` so there would be no need to use the traceback module?

Comment (wjones127) [reply python/pyarrow/src/arrow/python/common.cc:146]: > It seems we are already retrieving the error indicator and saving the traceback in PythonErrorDetail class, but can be reading the code wrong.

Yes, the `traceback` module isn't being used to retrieve any errors. They are definitely already retrieved.

I am using `traceback.format_exception()` so that our error format is consistent with what Python prints normally, which should be easiest for users to understand. I could instead manually try to reproduce this format, but there's a lot of special logic in https://github.com/python/cpython/blob/3.12/Lib/traceback.py

File: python/pyarrow/src/arrow/python/common.cc [hunk 2]
```diff
@@ -131,6 +138,34 @@ class PythonErrorDetail : public StatusDetail {
...
+                                             &fmt_exception));
+
+    OwnedRef formatted;
+    formatted.reset(PyObject_CallFunctionObjArgs(fmt_exception.obj(), exc_type_.obj(),
+                                                 exc_value_.obj(), exc_traceback_.obj(),
+                                                 NULL));
+
+    std::stringstream ss;
+    ss << "Python exception: ";
+    Py_ssize_t num_lines = PyList_GET_SIZE(formatted.obj());
```
Comment (pitrou) [inline python/pyarrow/src/arrow/python/common.cc:159]: You should probably check that we do have a list here. Or you can simply use `PySequence_Length` and `PySequence_GetItem` (this code is not performance-critical).

File: python/pyarrow/src/arrow/python/common.cc [hunk 3]
```diff
@@ -131,6 +138,34 @@ class PythonErrorDetail : public StatusDetail {
...
+    for (Py_ssize_t i = 0; i < num_lines; ++i) {
+      Py_ssize_t line_size;
+      const char* data =
+          PyUnicode_AsUTF8AndSize(PyList_GET_ITEM(formatted.obj(), i), &line_size);
```
Comment (pitrou) [inline python/pyarrow/src/arrow/python/common.cc:163]: Again, should either type-check and check for errors, or call the more generic `PyObject_StdStringStr`.

File: python/pyarrow/tests/test_cffi.py [hunk 4]
```diff
@@ -414,6 +414,37 @@ def test_export_import_batch_reader(reader_factory):
...
+    original = pa.RecordBatchReader.from_batches(make_schema(), gen())
+    original._export_to_c(ptr_stream)
+
+    reader = pa.RecordBatchReader._import_from_c(ptr_stream)
+    with pytest.raises(OSError) as exc_info:
+        reader.read_next_batch()
+
+    # inner *and* outer exception should be present
+    assert 'ValueError: foo' in str(exc_info.value)
+    assert 'NotImplementedError: bar' in str(exc_info.value)
```
Comment (pitrou) [inline python/pyarrow/tests/test_cffi.py:443]: Can you also test that the traceback is present? For example:
```suggestion
    assert "raise ValueError('foo')" in str(exc_info.value)
```

File: python/pyarrow/tests/test_cffi.py [hunk 5]
```diff
@@ -414,6 +414,37 @@ def test_export_import_batch_reader(reader_factory):
         pa.RecordBatchReader._import_from_c(ptr_stream)
 
 
+@needs_cffi
+def test_export_import_exception_reader():
+    c_stream = ffi.new("struct ArrowArrayStream*")
```
Comment (pitrou) [inline python/pyarrow/tests/test_cffi.py:419]: Can you add a reference to the GH issue?

**Review by pitrou — CHANGES_REQUESTED** [review]

File: python/pyarrow/src/arrow/python/common.cc (hunk 1 above)
Comment (AlenkaF) [reply python/pyarrow/src/arrow/python/common.cc:146]: Ah, I see. Thank you for explaining!

File: python/pyarrow/src/arrow/python/common.cc [hunk 6]
```diff
@@ -131,6 +138,34 @@ class PythonErrorDetail : public StatusDetail {
...
+    // Use traceback.format_exception()
+    OwnedRef traceback_module;
+    RETURN_NOT_OK(internal::ImportModule("traceback", &traceback_module));
+
+    OwnedRef fmt_exception;
+    RETURN_NOT_OK(internal::ImportFromModule(traceback_module.obj(), "format_exception",
+                                             &fmt_exception));
+
+    OwnedRef formatted;
+    formatted.reset(PyObject_CallFunctionObjArgs(fmt_exception.obj(), exc_type_.obj(),
```
[the remark this answers is not in the document]
Comment (wjones127) [reply python/pyarrow/src/arrow/python/common.cc:153]: Thanks. I've added error checks to each of the calls into the Python API.

File: python/pyarrow/src/arrow/python/common.cc (hunk 2 above)
Comment (wjones127) [reply python/pyarrow/src/arrow/python/common.cc]: The [API docs](https://docs.python.org/3/library/traceback.html#traceback.format_exception) claim this should return a list, but it's perhaps possible that they might change to some other sequence. I changed to be generic sequences.

I assume the function calls will do the type checking internally, correct?

File: python/pyarrow/tests/test_cffi.py (hunk 5 above)
Comment (wjones127) [reply python/pyarrow/tests/test_cffi.py:420]: Done.

File: python/pyarrow/tests/test_cffi.py (hunk 4 above)
Comment (wjones127) [reply python/pyarrow/tests/test_cffi.py:444]: Thanks, that is a good idea.

File: python/pyarrow/src/arrow/python/common.cc (hunk 2 above)
Comment (pitrou) [reply python/pyarrow/src/arrow/python/common.cc]: > I assume the function calls will do the type checking internally, correct?

If you're the concrete `PyList` APIs, they will generally assume that it is a list object. Also, fast access macros such as `PyList_GET_ITEM` don't do any error checking.

File: python/pyarrow/src/arrow/python/common.cc [hunk 7]
```diff
@@ -131,6 +138,40 @@ class PythonErrorDetail : public StatusDetail {
...
+                                                 exc_value_.obj(), exc_traceback_.obj(),
+                                                 NULL));
+    RETURN_IF_PYERROR();
+
+    std::stringstream ss;
+    ss << "Python exception: ";
+    Py_ssize_t num_lines = PySequence_Length(formatted.obj());
```
[the remark this answers is not in the document]
Comment (wjones127) [reply python/pyarrow/src/arrow/python/common.cc:160]: Thanks, I should have seen that 🤦

File: python/pyarrow/src/arrow/python/common.cc (hunk 2 above)
Comment (wjones127) [reply python/pyarrow/src/arrow/python/common.cc]: Ah right. I see the distinction now between the error checking and non-error-checking variants. 👍

**Review by pitrou — APPROVED** [review]
