### PR TITLE
GH-47279: [C++] Implement GetByteRangesArray for view types

### LINKED ISSUE #47279: [Python] Unable to calculate pyarrow.Table.nbytes if column type is string_view
### Describe the bug, including details regarding any error messages, version, and platform.

Hi,

I am receiving the following error when trying the method` pyarrow.Table.nbytes` on a table that has a column with _string_view_ type

`ArrowTypeError: Extracting byte ranges not supported for type string_view
`

## MRE 

``` py 
import pyarrow as pa

schema = pa.schema([pa.field("a", pa.string_view())])
table = pa.Table.from_pylist([{"a": "1"}], schema=schema)
table.nbytes

### Component(s)

Python

### PR DESCRIPTION
**Pull request by robert3005**
### Rationale for this change

- Fix https://github.com/apache/arrow/issues/47279

### What changes are included in this PR?

Add missing visit methods to GetByteRangesArray. The returned results are over
estimates since there's no cheap way to estimate offsets of the child
arrays/buffers. We can compute exact value if we are willing to check every
offset/view

### Are these changes tested?

Added tests

### Are there any user-facing changes?

No

* GitHub Issue: #47279

### CODE REVIEW

**Comment by robert3005** [comment]
@alamb do you know who can help me review this?

**Comment by alamb** [comment]
By my reading of the [blame](https://github.com/apache/arrow/blame/main/cpp/src/arrow/util/byte_size.cc), it looks like @westonpace and @lidavidm were involved in the initial development as part of

https://github.com/apache/arrow/commit/16af17c3327cfe624038913a7a808656082f69e0

Perhaps they can help review this PR or know someone more appropriate

**Review by lidavidm — APPROVED** [review]
It seems reasonable to me, but I haven't been in the C++ codebase for a while. Any objections @rok?

**Comment by jonasdedden** [comment]
@rok coming here from another issue (https://github.com/apache/arrow/issues/47279) blocking Ray Data usage with `string_view()`, could this get some more attention again? :pleading_face:

**Comment by rok** [comment]
Let me try taking a look tomorrow

File: cpp/src/arrow/util/byte_size.cc [hunk 1]
```diff
@@ -192,6 +192,29 @@ struct GetByteRangesArray {
...
+  template <typename BaseViewType>
+  Status VisitBaseViewType(const BaseViewType& type) const {
+    using c_type = typename BaseViewType::c_type;
+    RETURN_NOT_OK(VisitBitmap(input.buffers[0]));
+    const Buffer& views = *input.buffers[1];
+    RETURN_NOT_OK(range_starts->Append(reinterpret_cast<uint64_t>(views.data())));
+    RETURN_NOT_OK(range_offsets->Append(sizeof(c_type) * offset));
+    RETURN_NOT_OK(range_lengths->Append(sizeof(c_type) * length));
+
+    for (std::size_t i = 2; i < input.buffers.size(); i++) {
```
Comment (rok) [inline cpp/src/arrow/util/byte_size.cc]: Perhaps add a comment here about impercission because we don't scan every view?

File: cpp/src/arrow/util/byte_size.cc [hunk 2]
```diff
@@ -215,6 +238,36 @@ struct GetByteRangesArray {
...
+    RETURN_NOT_OK(range_offsets->Append(sizeof(offset_type) * offset));
+    RETURN_NOT_OK(range_lengths->Append(sizeof(offset_type) * length));
+
+    const Buffer& lengths_buffer = *input.buffers[2];
+    RETURN_NOT_OK(
+        range_starts->Append(reinterpret_cast<uint64_t>(lengths_buffer.data())));
+    RETURN_NOT_OK(range_offsets->Append(sizeof(offset_type) * offset));
+    RETURN_NOT_OK(range_lengths->Append(sizeof(offset_type) * length));
+
+    GetByteRangesArray child{*input.child_data[0],
```
Comment (rok) [inline cpp/src/arrow/util/byte_size.cc]: Similar comment about imprecision as above.

**Review by rok — CHANGES_REQUESTED** [review]
This looks pretty good! Sorry for taking a while. Two requests:
* Could you please add comments inline about the scanning trade-off?
* Add tests on slices (see sketch below)

```diff
diff --git i/cpp/src/arrow/util/byte_size_test.cc w/cpp/src/arrow/util/byte_size_test.cc
index d5c6c37a75..8b7d01fad0 100644
--- i/cpp/src/arrow/util/byte_size_test.cc
+++ w/cpp/src/arrow/util/byte_size_test.cc
@@ -326,6 +326,10 @@ TEST(ByteRanges, StringViewType) {
   std::shared_ptr<Array> str_view_with_nulls = ArrayFromJSON(
       utf8_view(), R"(["short", null, "another long string that requires a buffer"])");
   CheckBufferRanges(str_view_with_nulls, {{0, 0, 1}, {1, 0, 48}, {2, 0, 42}});
+
+  CheckBufferRanges(str_view_arr->Slice(1, 1), {{0, 16, 16}, {1, 0, 38}});
+  CheckBufferRanges(str_view_arr->Slice(0, 1), {{0, 0, 16}, {1, 0, 38}});
+  CheckBufferRanges(str_view_with_nulls->Slice(2, 1), {{0, 0, 1}, {1, 32, 16}, {2, 0, 42}});
 }

 TEST(ByteRanges, BinaryViewType) {
@@ -337,6 +341,9 @@ TEST(ByteRanges, BinaryViewType) {
   std::shared_ptr<Array> bin_view_with_nulls =
       ArrayFromJSON(binary_view(), R"(["AB", null, "CDEFGHIJKLMNOPQRSTUVWXYZ"])");
   CheckBufferRanges(bin_view_with_nulls, {{0, 0, 1}, {1, 0, 48}, {2, 0, 24}});
+
+  CheckBufferRanges(bin_view_arr->Slice(1, 1), {{0, 16, 16}, {1, 0, 22}});
+  CheckBufferRanges(bin_view_with_nulls->Slice(2, 1), {{0, 0, 1}, {1, 32, 16}, {2, 0, 24}});
 }

 using ListViewArrowTypes = ::testing::Types<ListViewType, LargeListViewType>;
@@ -359,6 +366,17 @@ TYPED_TEST(ByteRangesListView, Basic) {
                                            {1, 0, 3 * sizeof(offset_type)},
                                            {2, 0, 3 * sizeof(offset_type)},
                                            {3, 0, 20}});
+
+  CheckBufferRanges(
+      list_view_arr->Slice(2, 1),
+      {{0, 2 * sizeof(offset_type), sizeof(offset_type)},
+       {1, 2 * sizeof(offset_type), sizeof(offset_type)},
+       {2, 0, 16}});
+  CheckBufferRanges(list_view_with_nulls->Slice(2, 1),
+                    {{0, 0, 1},
+                     {1, 2 * sizeof(offset_type), sizeof(offset_type)},
+                     {2, 2 * sizeof(offset_type), sizeof(offset_type)},
+                     {3, 0, 20}});
 }

 TYPED_TEST(ByteRangesListView, NestedListView) {
```

File: cpp/src/arrow/util/byte_size.cc (hunk 1 above)
Comment (rok) [reply cpp/src/arrow/util/byte_size.cc]: Also perhaps:

```suggestion
    for (int i = 2; i < input.buffers.size(); i++) {
```

**Comment by robert3005** [comment]
thanks for the review @rok. I have added comments and incorporated your test suggestions

File: cpp/src/arrow/util/byte_size.cc [hunk 3]
```diff
@@ -215,6 +244,42 @@ struct GetByteRangesArray {
...
+
+    // The following calculation is an over/under estimate of the byte size since views
+    // buffer might
+    // 1. Not reference all the values in data buffers (the array was filtered without gc)
+    // 2. Reference a value multiple times without repeating it in the data buffer
+    //
+    // Producing exact byte size would require linear scan of all values in view buffer
+    GetByteRangesArray child{*input.child_data[0],
+                             0,
+                             (*input.child_data[0]).length,
```
Comment (rok) [inline cpp/src/arrow/util/byte_size.cc]:
```suggestion
                             input.child_data[0]->length,
```

File: cpp/src/arrow/util/byte_size.cc [hunk 4]
```diff
@@ -215,6 +244,42 @@ struct GetByteRangesArray {
...
+    RETURN_NOT_OK(range_offsets->Append(sizeof(offset_type) * offset));
+    RETURN_NOT_OK(range_lengths->Append(sizeof(offset_type) * length));
+
+    const Buffer& lengths_buffer = *input.buffers[2];
+    RETURN_NOT_OK(
+        range_starts->Append(reinterpret_cast<uint64_t>(lengths_buffer.data())));
+    RETURN_NOT_OK(range_offsets->Append(sizeof(offset_type) * offset));
+    RETURN_NOT_OK(range_lengths->Append(sizeof(offset_type) * length));
+
+    // The following calculation is an over/under estimate of the byte size since views
```
Comment (rok) [inline cpp/src/arrow/util/byte_size.cc]:
```suggestion
    // The following calculation is an over estimate of the byte size since views
```

File: cpp/src/arrow/util/byte_size.cc [hunk 5]
```diff
@@ -192,6 +192,35 @@ struct GetByteRangesArray {
...
+  template <typename BaseViewType>
+  Status VisitBaseViewType(const BaseViewType& type) const {
+    using c_type = typename BaseViewType::c_type;
+    RETURN_NOT_OK(VisitBitmap(input.buffers[0]));
+    const Buffer& views = *input.buffers[1];
+    RETURN_NOT_OK(range_starts->Append(reinterpret_cast<uint64_t>(views.data())));
+    RETURN_NOT_OK(range_offsets->Append(sizeof(c_type) * offset));
+    RETURN_NOT_OK(range_lengths->Append(sizeof(c_type) * length));
+
+    // The following calculation is an over/under estimate of the size since views buffer
```
Comment (rok) [inline cpp/src/arrow/util/byte_size.cc]: Can this actually underestimate?
```suggestion
    // The following calculation is an over estimate of the size since views buffer
```

**Review by rok — APPROVED** [review]
Three minor nits, looks good otherwise!

**Comment by robert3005** [comment]
Whether this function under estimates depends on the contract of the api. Essentially the logical value can only ever exist in the view buffer since you can repeat the offset. However, it is still the number of bytes used in memory but it might not be the number of bytes required to store the logical values. Happy to adjust

**Comment by robert3005** [comment]
The api that uses this logic says it's just the referenced ranges so you're correct that it will not underestimate

**Review by rok — APPROVED** [review]
Looks good, will merge when CI passes.

**Comment by rok** [comment]
cc @pitrou

**Comment by rok** [comment]
@robert3005 could you rebase please? The current CI failures are not related, and were fixed on master already.

**Comment by robert3005** [comment]
Latest run is rebased on https://github.com/apache/arrow/commit/cfbbf708082c84f3a7cb1246d83ef134c2ac27c4 which is as new as it gets at the moment of the run

**Comment by rok** [comment]
The failures are parquet fuzz https://github.com/apache/arrow/pull/49374#issuecomment-3992734739, grpc https://github.com/apache/arrow/issues/49435 and aws-sdk-cpp https://github.com/apache/arrow/issues/49347. So PR appears to not introduce new regressions :).

**Comment by rok** [comment]
Merged. Thanks for contributing and the persistence @robert3005 !
