### PR TITLE
GH-36502: [C++] Add run-end encoded array support to ReferencedByteRanges

### LINKED ISSUE #36502: GetByteRangesArray doesn't support run-end encoded arrays
### Describe the bug, including details regarding any error messages, version, and platform.

Environment:

OS: Ubuntu 20.04
Python: 3.10
Arrow: 12.0.0

Reproducer:

```python
import numpy as np
import pyarrow as pa
import pyarrow.compute as pac

if __name__ == "__main__":
   pa.Table.from_pydict({"A": pac.run_end_encode(np.zeros(1000))}).nbytes
```

Example error message:

```python
In [10]: pa.Table.from_pydict({"A": pac.run_end_encode(np.zeros(1000))}).nbytes
---------------------------------------------------------------------------
ArrowTypeError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 pa.Table.from_pydict({"A": pac.run_end_encode(np.zeros(1000))}).nbytes

File ~/venv/venv3.10/lib/python3.10/site-packages/pyarrow/table.pxi:4474, in pyarrow.lib.Table.nbytes.__get__()

File ~/venv/venv3.10/lib/python3.10/site-packages/pyarrow/error.pxi:144, in pyarrow.lib.pyarrow_internal_check_status()

File ~/venv/venv3.10/lib/python3.10/site-packages/pyarrow/error.pxi:123, in pyarrow.lib.check_status()

ArrowTypeError: Extracting byte ranges not supported for type run_end_encoded<run_ends: int32, values: double>
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

Fix for #36502.

### What changes are included in this PR?

Fix and C++ tests.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Addition of a new function to the `ree_util` namespace.
* Closes: #36502

### CODE REVIEW

**Comment by felipecrv** [comment]
@mapleFU @sjperkins  @pitrou

File: cpp/src/arrow/util/ree_util.cc [hunk 1]
```diff
@@ -85,6 +85,26 @@ int64_t FindPhysicalLength(const ArraySpan& span) {
   return internal::FindPhysicalLength<int64_t>(span);
 }
 
+std::pair<int64_t, int64_t> FindPhysicalRange(const ArraySpan& span, int64_t offset,
+                                              int64_t length) {
+  auto& run_ends_span = RunEndsArray(span);
```
Comment (bkietz) [inline cpp/src/arrow/util/ree_util.cc:90]: Nit
```suggestion
  const auto& run_ends_span = RunEndsArray(span);
```

File: cpp/src/arrow/util/ree_util.h [hunk 2]
```diff
@@ -73,24 +73,39 @@ int64_t FindPhysicalIndex(const RunEndCType* run_ends, int64_t run_ends_size, in
...
+/// \brief Uses binary-search to calculate the number of physical values (and
+/// run-ends) necessary to represent the logical range of values from
+/// offset to length
+template <typename RunEndCType>
+int64_t FindPhysicalLength(const RunEndCType* run_ends, int64_t run_ends_size,
+                           int64_t length, int64_t offset) {
+  int64_t physical_length;
+  std::tie(std::ignore, physical_length) =
+      FindPhysicalRange<RunEndCType>(run_ends, run_ends_size, length, offset);
+  return physical_length;
```
Comment (bkietz) [inline cpp/src/arrow/util/ree_util.h:108]: Nit:
```suggestion
  auto [_, physical_length] =
      FindPhysicalRange<RunEndCType>(run_ends, run_ends_size, length, offset);
  return physical_length;
```

File: cpp/src/arrow/util/byte_size.cc [hunk 3]
```diff
@@ -294,6 +295,21 @@ struct GetByteRangesArray {
...
+  Status Visit(const RunEndEncodedType& type) const {
+    auto physical_range = ree_util::FindPhysicalRange(input, offset, length);
+    for (int i = 0; i < type.num_fields(); i++) {
+      GetByteRangesArray child{
+          *input.child_data[i],
+          /*offset=*/input.child_data[i]->offset + physical_range.first,
+          /*length=*/physical_range.second,
+          range_starts,
+          range_offsets,
+          range_lengths};
```
Comment (bkietz) [inline cpp/src/arrow/util/byte_size.cc:307]:
```suggestion
    auto [phys_offset, phys_length] = ree_util::FindPhysicalRange(input, offset, length);
    for (int i = 0; i < type.num_fields(); i++) {
      GetByteRangesArray child{
          *input.child_data[i],
          /*offset=*/input.child_data[i]->offset + phys_offset,
          /*length=*/phys_length,
          range_starts,
          range_offsets,
          range_lengths};
```

**Review by bkietz — CHANGES_REQUESTED** [review]
LGTM, just a few nits

File: cpp/src/arrow/util/byte_size.cc [hunk 4]
```diff
@@ -294,6 +295,21 @@ struct GetByteRangesArray {
...
+  Status Visit(const RunEndEncodedType& type) const {
+    auto [phys_offset, phys_length] = ree_util::FindPhysicalRange(input, offset, length);
+    for (int i = 0; i < type.num_fields(); i++) {
+      GetByteRangesArray child{
+          *input.child_data[i],
+          /*offset=*/input.child_data[i]->offset + phys_offset,
+          /*length=*/phys_length,
+          range_starts,
+          range_offsets,
+          range_lengths};
```
Comment (felipecrv) [inline cpp/src/arrow/util/byte_size.cc:307]:
```suggestion
      GetByteRangesArray child{
          *input.child_data[i],
          /*offset=*/input.child_data[i]->offset + phys_offset,
          /*length=*/phys_length,
          range_starts,
          range_offsets,
          range_lengths};
```
```suggestion
      GetByteRangesArray child{*input.child_data[i],
                               /*offset=*/input.child_data[i]->offset + phys_offset,
                               /*length=*/phys_length,
                               range_starts,
                               range_offsets,
                               range_lengths};
```

**Review by bkietz — APPROVED** [review]

File: cpp/src/arrow/util/ree_util.h [hunk 5]
```diff
@@ -138,6 +152,13 @@ int64_t FindPhysicalIndex(const ArraySpan& span, int64_t i, int64_t absolute_off
 /// end). This function uses binary-search, so it has a O(log N) cost.
 int64_t FindPhysicalLength(const ArraySpan& span);
 
+/// \brief Find the physical range of physical values referenced by the REE in
+/// the logical range from offset to offset + length
+///
+/// \return a pair of physical offset and physical length
+std::pair<int64_t, int64_t> FindPhysicalRange(const ArraySpan& span, int64_t offset,
```
Comment (pitrou) [inline cpp/src/arrow/util/ree_util.h:159]: Can you add unit tests for this new function?

**Review by pitrou — CHANGES_REQUESTED** [review]
Thanks @felipecrv ! Just one comment but otherwise LGTM.

File: cpp/src/arrow/util/ree_util.h (hunk 5 above)
Comment (felipecrv) [reply cpp/src/arrow/util/ree_util.h:159]: As length calculation is defined in terms of it, I thought tests would be redundant. But I will add them now close to the length tests.

Comment (pitrou) [inline cpp/src/arrow/util/ree_util.h:159]: You need to ARROW_EXPORT this as well as the non-template `FindPhysicalIndex` and `FindPhysicalLength`, for Windows.

**Review by pitrou — CHANGES_REQUESTED** [review]
LGTM but one thing to fix.

File: cpp/src/arrow/util/ree_util.h (hunk 5 above)
Comment (felipecrv) [reply cpp/src/arrow/util/ree_util.h:159]: Pushing a commit now.

**Review by pitrou — APPROVED** [review]

**Comment by felipecrv** [comment]
I'm going to rebase and force-push to see if these protobuf issues go away.

**Comment by pitrou** [comment]
The protobuf issues are https://github.com/apache/arrow/pull/36606
