### PR TITLE
GH-33904: [R] improve behavior of s3_bucket - work-around

### LINKED ISSUE #33904: [R] Using s3_bucket with non-AWS S3-compatible storage is confusing
### Describe the bug, including details regarding any error messages, version, and platform.

If I want to use arrow with non-AWS, S3-compatible storage, I might find the `s3_bucket` convenience function from our documentation [[1](https://arrow.apache.org/docs/dev/r/articles/arrow.html#connecting-to-cloud-storage), [2](https://arrow.apache.org/docs/dev/r/articles/fs.html)].  The documentation doesn't always mention non-AWS storage but I might see in the help page for `s3_bucket` that I can pass options to `S3FileSystem$Create` using dots and those options include `endpoint_override`. I might then try the following:

```r
s3_bucket(
    "my-bucket",
    endpoint_override = "example.org", 
    anonymous = TRUE
)
```

However, this results in the following error:

```
# Error: IOError: Bucket 'my-bucket' not found
# /Users/bryce/src/apache/arrow/cpp/src/arrow/filesystem/s3fs.cc:829  ResolveRegionUncached(bucket)
# /Users/bryce/src/apache/arrow/cpp/src/arrow/filesystem/s3fs.cc:357  ResolveS3BucketRegion(bucket)
# /Users/bryce/src/apache/arrow/cpp/src/arrow/filesystem/filesystem.cc:719  S3Options::FromUri(uri, out_path)
```

You can see that we're trying to resolve the bucket's AWS region which fails as expected. Interestingly, the user that reported this issue to me found they could prevent this error by creating a bucket on AWS with the same name at which point the region resolution would succeed (pointlessly), the `S3FileSystem` createsd would respect their `endpoint_override`, and future calls like $ls() would target the correct endpoint. This could actually cause some significant frustration for non-AWS users.

If I go back to the docs and read further down on https://arrow.apache.org/docs/dev/r/articles/fs.html#file-systems-that-emulate-s3, I find that the recommended way to do what I want is directly through `S3FileSystem$create`:

```r
S3FileSystem$create(
    endpoint_override = "example.org",
    anonymous = TRUE
)
```

I was made aware through other channels while researching this issue that this syntax would also have worked (though it's not documented sufficiently):

```r
s3_bucket("s3://anonymous@my-bucket?endpoint_override=example.org")
```

With the increasing number of non-AWS providers of S3-compatible storage (e.g., [Ceph](https://docs.ceph.com/en/latest/radosgw/s3/), [DigitalOcean](https://www.digitalocean.com/products/spaces)], I only think we'll have more users of non-AWS, S3-compatible storage and those users will run into confusion over (1) how things work and (2) how things are documented.

I'd like to:

1. Do a pass over the documentation (online, and R help pages)
  a.  To make the messaging clear that we support AWS, GCS, and S3-compatible storage providers
  b. Add more examples to `s3_bucket` to make it clearer how a user can go about doing that
3. Change the behavior of `s3_bucket` to special-case passing `endpoint_override` to skip region resolution and just jump directly to creating an `S3FileSystem`.

### Component(s)

R

### PR DESCRIPTION
**Pull request by cboettig**
I think this is another option to address #33918.

This retains the existing behavior when no additional arguments (region, endpoint, etc) are supplied.  

If any optional arguments are supplied, this approach will by-pass the `$from_uri` call.  I think this is reasonable, given that the `from_uri()` call is implicitly ignoring optional arguments already, which is giving rise to the current bugs.  

* Closes: #33904

### CODE REVIEW

**Comment by cboettig** [comment]
I think this work-around is much preferable to a warning for now.  If you introduce a warning that says `endpoint_override` is not supported by s3_bucket, I have a good number of users across a few different packages who will be confused by the warning, because it works just fine as long as the bucket name is not unique.  (and yes, users on custom endpoints will often pick common bucket names already in use somewhere on AWS, since they have no reason to need unique names).

**Review by paleolimbot — COMMENTED** [review]
This change looks reasonable...thank you for making the change!

Could you add a test that makes sure that at least one parameter is not ignored? I'm not sure what the best call to `s3_bucket()` is that will both succeed and not ignore a parameter...perhaps that's best done on the `test-minio.R` (make sure we can connect to the minio server using `s3_bucket(..., endpoint_override = "xxx")`?

File: r/R/filesystem.R [hunk 1]
```diff
@@ -462,12 +462,13 @@ s3_bucket <- function(bucket, ...) {
...
+  if (!length(args)) {
+    fs_and_path <- FileSystem$from_uri(bucket)
+    fs <- fs_and_path$fs
+  } else {
   # If there are no additional S3Options, we can use that filesystem
-  # Otherwise, take the region that was detected and make a new fs with the args
-  if (length(args)) {
-    args$region <- fs$region
+  # If user specifies args, they must specify region as arg, env var, or config
     fs <- exec(S3FileSystem$create, !!!args)
```
Comment (paleolimbot) [inline r/R/filesystem.R:472]: Looks like you need to define `fs_and_path` here somehow?

**Comment by cboettig** [comment]
@paleolimbot ah simple, `fs_and_path$path` is just the `bucket`, should be fixed now.  

Also checked locally this time (apologies for not doing so before, had to fiddle a bit to get `devtools::load_all()` to compile with S3 support).  Seems to be working on my end.

One of the CI tasks seems to have timed out, not sure precisely but doesn't look like a related issue?

**Comment by thisisnic** [comment]
CI timeout will be unrelated to this PR as we've seen it do that on another one; have manually re-triggered it for you.

File: r/tests/testthat/test-s3-minio.R [hunk 2]
```diff
@@ -61,6 +61,13 @@ fs$CreateDir(now)
 # Clean up when we're all done
 withr::defer(fs$DeleteDir(now))
 
+test_that("Confirm s3_bucket works with endpoint_override", {
+  
+  
+  bucket <- s3_bucket("test", endpoint_override = "https://play.min.io")
```
Comment (paleolimbot) [inline r/tests/testthat/test-s3-minio.R:67]: Was something wrong with the localhost version?

Comment (cboettig) [reply r/tests/testthat/test-s3-minio.R:67]: @paleolimbot good question, that's something I'm trying to figure out too.  It failed to find the bucket in the previous test, https://github.com/apache/arrow/actions/runs/4093029707/jobs/7073398005, but I don't think that's because of any change I made -- in my own local testing I could never reproduce that error.  I see the desire to use localhost, but it's not quite clear how to ensure the localhost deploy works before running the test.

It's not so clear to me that any of the other tests rely on the localhost bucket existing?  

https://play.min.io is the official test service for the MINIO platform, not sure if that's ideal choice here for the tests, but then the test suite here isn't really built out and my objective is just submit a patch for this confirmed bug in the codebase.

**Comment by cboettig** [comment]
It looks like things are passing now, except for again a stalled checks that don't seem related to the pull request(?)

File: r/tests/testthat/test-s3-minio.R (hunk 2 above)
Comment (paleolimbot) [reply r/tests/testthat/test-s3-minio.R:67]: Hmm...the localhost version should definitely work. I will do a local pull tomorrow morning and see what I can come up with 🙂

**Comment by cboettig** [comment]
ah, good catch!  

Good to know that the URI format requires all optional arguments to be included in the URI and aren't read from config or manual options even when using `$create()`, that's a bit surprising to me but guess it makes sense.  (My play.minio example must have passed because again it used a bucket name available on both AWS and play.minio endpoints! whoops!)

Yup, all looks good now to me as well and works as expected.  Thanks much!

**Comment by cboettig** [comment]
:tada:
