### PR TITLE
GH-39803: [C++][Acero] Fix AsOfJoin with differently ordered schemas than the output

### LINKED ISSUE #39803: [Acero] As of join breaks depending on the key order
### Describe the bug, including details regarding any error messages, version, and platform.

I discovered a bug on the asofjoin, wherein if you change the order of the columns and make types different, it breaks.

Suppose the left table has:

```
ts,key_str_type,l_val
...data here
```

And the right table has:

```
key_str,ts,r_val
...data here
```

This ends up breaking, since the key hasher metadata is based on the output schema, which looks like:

```
ts,key_str,l_val,r_val
```

...And since the right table's 0th column is a string type, the hashes end up being all over the place.

I have a repro, test, and fix that I will attach to this. But you can see the test outputs here for the before and after fix: https://gist.github.com/JerAguilon/953d82ed288d58f9ce24d1a925def2cc

### Component(s)

C++

### PR DESCRIPTION
**Pull request by JerAguilon**
### Rationale for this change

Issue is described visually in https://github.com/apache/arrow/issues/39803.

The key hasher works by hashing every row of the input tables' key columns. An important step is inspecting the [column metadata](https://github.com/apache/arrow/blob/main/cpp/src/arrow/acero/asof_join_node.cc#L412) for the asof-join key fields. This returns whether columns are fixed width, among other things.

The issue is we are passing the `output_schema`, rather than the input's schema.

If an input looks like 

```
key_string_type,ts_int32_type,val
```

But our expected output schema looks like:

```
ts_int32,key_string_type,...
```
Then the hasher will think that the `key_string_type`'s type is an int32. This completely throws off hashes. Tests currently get away with it since we just use ints across the board.

### What changes are included in this PR?

One line fix and test with string types.

### Are these changes tested?

Yes. Can see the test run before and after changes here: https://gist.github.com/JerAguilon/953d82ed288d58f9ce24d1a925def2cc

Before the change, notice that inputs 0 and 1 have mismatched hashes:

```
AsofjoinNode(0x16cf9e2d8): key hasher 1 got hashes [0, 9784892099856512926, 1050982531982388796, 10763536662319179482, 2029627098739957112, 11814237723602982167, 3080328155728858293, 12792882290360550483, 4058972722486426609, 13771526852823217039]
...
AsofjoinNode(0x16cf9dd18): key hasher 0 got hashes [17528465654998409509, 12047706865972860560, 18017664240540048750, 12358837084497432044, 8151160321586084686, 8691136767698756332, 15973065724125580046, 9654919479117127288, 618127929167745505, 3403805303373270709]

```

And after, they do match:

```
AsofjoinNode(0x16f2ea2d8): key hasher 1 got hashes [17528465654998409509, 12047706865972860560, 18017664240540048750, 12358837084497432044, 8151160321586084686, 8691136767698756332, 15973065724125580046, 9654919479117127288, 618127929167745505, 3403805303373270709]
...
AsofjoinNode(0x16f2e9d18): key hasher 0 got hashes [17528465654998409509, 12047706865972860560, 18017664240540048750, 12358837084497432044, 8151160321586084686, 8691136767698756332, 15973065724125580046, 9654919479117127288, 618127929167745505, 3403805303373270709]
```

...which is exactly what you want, since the `key` column for both tables looks like `["0", "1", ..."9"]`

### Are there any user-facing changes?

* Closes: #39803

### CODE REVIEW

File: cpp/src/arrow/acero/asof_join_node_test.cc [hunk 1]
```diff
@@ -16,6 +16,7 @@
 // under the License.
 
 #include <gmock/gmock-matchers.h>
+#include <iostream>  // nocommit
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node_test.cc:19]: Is this required? Also, what is "nocommit" for?

File: cpp/src/arrow/acero/asof_join_node_test.cc [hunk 2]
```diff
@@ -1582,6 +1583,66 @@ TEST(AsofJoinTest, BatchSequencing) {
   return TestSequencing(MakeIntegerBatches, /*num_batches=*/32, /*batch_size=*/1);
 }
 
+template <typename BatchesMaker>
+void TestSchemaResolution(BatchesMaker maker, int num_batches, int batch_size) {
+  auto l_schema =
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node_test.cc:1588]: Can you add a comment explaining this test, together with a reference to the GH issue?

**Comment by pitrou** [comment]
Also, can you please rebase from git main?

File: cpp/src/arrow/acero/asof_join_node_test.cc (hunk 1 above)
Comment (JerAguilon) [reply cpp/src/arrow/acero/asof_join_node_test.cc:19]: whoops - this was for some cout debugging, will remove

**Comment by JerAguilon** [comment]
> Also, can you please rebase from git main?

Done and addressed comments. Thanks for the review

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
Thanks a lot for this @JerAguilon !
