### PR TITLE
GH-39598: [C#] Fix verification script

### LINKED ISSUE #39598: [Release][C#] Source verification for C# on 15.0.0 Release Candidate fails with `file does not exist: artifacts/Apache.Arrow/Release/netstandard1.3/Apache.Arrow.pdb`
### Describe the bug, including details regarding any error messages, version, and platform.

I have been executing the source verification jobs both on the nightly jobs and the maintenance branch and I haven't found any prior issues but as soon as I've created the Release Candidate 0 for 15.0.0 all the C# verification jobs for the sources fail with the following error:
```
  Successfully created package '/tmp/arrow-15.0.0.NZGxf/apache-arrow-15.0.0/csharp//artifacts/Apache.Arrow.Flight.Sql/Release/Apache.Arrow.Flight.Sql.15.0.0.snupkg'.
file does not exist: artifacts/Apache.Arrow/Release/netstandard1.3/Apache.Arrow.pdb
Failed to verify release candidate. See /tmp/arrow-15.0.0.NZGxf for details.
```
The Release Candidate 0 jobs that are failing can be seen here:
https://github.com/apache/arrow/pull/39597#issuecomment-1890973621
and one example of failed job here: https://github.com/ursacomputing/crossbow/actions/runs/7519893060/job/20468954451

The maintenance branch successful jobs can be seen here:
https://github.com/apache/arrow/pull/39545#issuecomment-1889979579

### Component(s)

C#, Release

### PR DESCRIPTION
**Pull request by CurtHagenlocher**
### What changes are included in this PR?

The verification script is modified to look for the versions of .NET now supported by the package.

### Are these changes tested?

Manually tested the verification command.

* Closes: #39598

### CODE REVIEW

File: dev/release/verify-release-candidate.sh [hunk 1]
```diff
@@ -880,8 +880,8 @@ test_csharp() {
   if [ "${SOURCE_KIND}" = "local" ]; then
     echo "Skipping sourelink verification on local build"
   else
-    dotnet tool run sourcelink test artifacts/Apache.Arrow/Release/netstandard1.3/Apache.Arrow.pdb
-    dotnet tool run sourcelink test artifacts/Apache.Arrow/Release/netcoreapp3.1/Apache.Arrow.pdb
+    dotnet tool run sourcelink test artifacts/Apache.Arrow/Release/netstandard2.0/Apache.Arrow.pdb
```
Comment (raulcd) [inline dev/release/verify-release-candidate.sh:883]: I have no experience with C# and I might be saying something that doesn't make sense but is there a reason why we don't test this when `SOURCE_KIND` is `local`?
We probably could find the issue on nightlies / maintenance branch if we also tested there instead of only when we have generated a Release candidate.

**Review by raulcd — COMMENTED** [review]
The change looks good to me, only a minor comment to see if we could find the error earlier instead of when the RC is generated.

File: dev/release/verify-release-candidate.sh [hunk 2]
```diff
@@ -880,8 +880,8 @@ test_csharp() {
   if [ "${SOURCE_KIND}" = "local" ]; then
     echo "Skipping sourelink verification on local build"
```
Comment (raulcd) [inline dev/release/verify-release-candidate.sh:881]: Found a minor typo:
```suggestion
    echo "Skipping sourcelink verification on local build"
```

**Comment by raulcd** [comment]
@kou I plan to merge this. I have created https://github.com/apache/arrow/issues/39631 to follow up the local build issue. Let me know if you are ok with merging it as is to add to RC1

**Review by raulcd — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1
