### PR TITLE
GH-36069: [Java] Ensure S3 is finalized on shutdown

### LINKED ISSUE #36069: [Java] while using s3 FileSystemDatasetFactory getting this exception
### Describe the bug, including details regarding any error messages, version, and platform.

/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/arrow/cpp/src/arrow/filesystem/s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit

i think the java client is not closing the s3 client gracefully because of that memory leak happening

### Component(s)

Java

### PR DESCRIPTION
**Pull request by danepitkin**
### Rationale for this change

Java datasets can implicitly create an S3 filesystem, which will initialize S3 APIs. There is currently no explicit call to shutdown S3 APIs in Java, which results in a warning message being printed at runtime:

`arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit`

### What changes are included in this PR?

* Add a Java runtime shutdown hook that calls `EnsureS3Finalized()` via JNI. This is a noop if S3 is uninitialized or already finalized.

### Are these changes tested?

Yes, reproduced with:

```
import org.apache.arrow.dataset.file.FileFormat;
import org.apache.arrow.dataset.file.FileSystemDatasetFactory;
import org.apache.arrow.dataset.jni.NativeMemoryPool;
import org.apache.arrow.dataset.source.DatasetFactory;
import org.apache.arrow.memory.BufferAllocator;
import org.apache.arrow.memory.RootAllocator;

public class DatasetModule {
    public static void main(String[] args) {
        String uri = "s3://voltrondata-labs-datasets/nyc-taxi-tiny/year=2022/month=2/part-0.parquet";
        try (
            BufferAllocator allocator = new RootAllocator();
            DatasetFactory datasetFactory = new FileSystemDatasetFactory(allocator, NativeMemoryPool.getDefault(), FileFormat.PARQUET, uri);
        ) {
            // S3 is initialized
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

I didn't think a unit test was worth adding. Let me know if you think otherwise. Reasoning:
* We can't test the actual shutdown since thats a JVM thing.
* We could test to see if the hook is registered, but that involves exposing the API and having access to the thread object registered with the hook. Or using reflection to obtain it. Not worth it IMO.
* No need to test the functionality inside the hook, its just a wrapper around a single C++ API with no params/retval.

### Are there any user-facing changes?

No
* Closes: #36069

### CODE REVIEW

File: java/dataset/src/main/java/org/apache/arrow/dataset/file/FileSystemDatasetFactory.java [hunk 1]
```diff
@@ -26,14 +28,18 @@
  */
 public class FileSystemDatasetFactory extends NativeDatasetFactory {
 
+  private static final AtomicBoolean addedS3ShutdownHook = new AtomicBoolean(false);
```
Comment (danepitkin) [inline java/dataset/src/main/java/org/apache/arrow/dataset/file/FileSystemDatasetFactory.java:31]: I added an atomic check to ensure we only register a single hook. Without it, we could register multiple hooks to call `EnsureS3Finalized`.

**Comment by danepitkin** [comment]
@github-actions crossbow submit *java*

File: java/dataset/src/main/java/org/apache/arrow/dataset/file/FileSystemDatasetFactory.java (hunk 1 above)
Comment (lidavidm) [reply java/dataset/src/main/java/org/apache/arrow/dataset/file/FileSystemDatasetFactory.java:31]: Can we just stick it in JniLoader? https://github.com/apache/arrow/blob/main/java/dataset/src/main/java/org/apache/arrow/dataset/jni/JniLoader.java

Comment (danepitkin) [reply java/dataset/src/main/java/org/apache/arrow/dataset/file/FileSystemDatasetFactory.java:31]: Ah yes, this is a much better spot for this. Will update. The atomic bool did feel like overkill

**Comment by danepitkin** [comment]
@github-actions crossbow submit *java*

**Review by lidavidm — APPROVED** [review]
