### PR TITLE
GH-35960: [Java] Detect overflow in allocation

### LINKED ISSUE #35960: [Java] Accounted size went negative when locallyHeldMemory overflow
### Bug description:
The following code will throw `Accounted size went negative` exception.
The buffer allocator `a` will ask its parent allocator to do allocation, however the `locallyHeldMemory` of parent allocator already reaches `Long.MAX_VALUE` when creating child actor `ChildB`

```
        RootAllocator parentAllocator  = new RootAllocator();
        BufferAllocator a = parentAllocator.newChildAllocator("ChildA", 0, Long.MAX_VALUE);
        BufferAllocator b = parentAllocator.newChildAllocator("ChildB", Long.MAX_VALUE, Long.MAX_VALUE);
        IntVector intVector = new IntVector("intVector", a);
        intVector.allocateNew(1);
        intVector.set(0, 2);
        intVector.setValueCount(1);

        IntVector intVector2 = new IntVector("intVector2", a);
        intVector2.allocateNew(1);
        intVector2.set(0, 2);
        intVector2.setValueCount(1);

        intVector.close();
        intVector2.close();
        a.close();
        b.close();
```

### error message:
```
Exception in thread "main" java.lang.IllegalArgumentException: Accounted size went negative.
	at org.apache.arrow.util.Preconditions.checkArgument(Preconditions.java:136)
	at org.apache.arrow.memory.Accountant.releaseBytes(Accountant.java:214)
	at org.apache.arrow.memory.RootAllocator.releaseBytes(RootAllocator.java:29)
	at org.apache.arrow.memory.Accountant.releaseBytes(Accountant.java:221)
	at org.apache.arrow.memory.AllocationManager.release(AllocationManager.java:152)
	at org.apache.arrow.memory.BufferLedger.decrement(BufferLedger.java:157)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:124)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
	at org.apache.arrow.vector.BaseValueVector.releaseBuffer(BaseValueVector.java:114)
	at org.apache.arrow.vector.BaseFixedWidthVector.clear(BaseFixedWidthVector.java:248)
	at org.apache.arrow.vector.BaseFixedWidthVector.close(BaseFixedWidthVector.java:238)
	at Test.main(Test.java:46)
```

### version:
12.0.0

### Component(s)

Java

### PR DESCRIPTION
**Pull request by lidavidm**
### Rationale for this change

The Java allocator wasn't detecting overflow (which is admittedly a corner case since you can't actually allocate that many bytes), causing an unexpected exception.

### What changes are included in this PR?

Detect overflow and provide the right exception.

### Are these changes tested?

Yes

### Are there any user-facing changes?

No
* Closes: #35960

### CODE REVIEW

**Comment by lidavidm** [comment]
CC @davisusanibar

**Comment by danepitkin** [comment]
LGTM!

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/Accountant.java [hunk 1]
```diff
@@ -169,9 +169,14 @@ public boolean forceAllocate(long size) {
    */
   private AllocationOutcome.Status allocate(final long size, final boolean incomingUpdatePeak,
       final boolean forceAllocation, AllocationOutcomeDetails details) {
-    final long newLocal = locallyHeldMemory.addAndGet(size);
+    final long oldLocal = locallyHeldMemory.getAndAdd(size);
+    final long newLocal = oldLocal + size;
+    // Borrowed from Math.addExact (but avoid exception here)
```
Comment (davisusanibar) [inline java/memory/memory-core/src/main/java/org/apache/arrow/memory/Accountant.java:174]: Is it necessary to postpone exception throws?

Comment (lidavidm) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/Accountant.java:174]: Exception handlers may have a performance penalty (even if not invoked), and this code is meant to be fast.
