### PR TITLE
GH-37750: [R][C++] Add compatability with IntelLLVM

### LINKED ISSUE #37750: [R][C++] Cmake error `Unknown compiler: IntelLLVM 2023.2.0`
### Describe the bug, including details regarding any error messages, version, and platform.

When trying to build the C++ library from source on one of the CRAN machines, we get the following error:

```
-- Building using CMake version: 3.26.3
-- The C compiler identification is IntelLLVM 2023.2.0
-- The CXX compiler identification is IntelLLVM 2023.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler:
/data/gannet/ripley/intel/oneapi/compiler/2023.2.1/linux/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler:
/data/gannet/ripley/intel/oneapi/compiler/2023.2.1/linux/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Arrow version: 13.0.0 (full: '13.0.0')
-- Arrow SO version: 1300 (full: 1300.0.0)
-- clang-tidy found at /usr/bin/clang-tidy
-- clang-format found at /usr/bin/clang-format
-- Found ClangTools: /usr/bin/clang-format
-- infer not found
-- Found Python3: /usr/bin/python3.10 (found version "3.10.11") found
components: Interpreter
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Found cpplint executable at
/tmp/RtmpAEH6nP/R.INSTALL27b65d4fc79fd5/arrow/tools/cpp/build-support/cpplint.py
-- System processor: x86_64
-- Performing Test CXX_SUPPORTS_SSE4_2
-- Performing Test CXX_SUPPORTS_SSE4_2 - Success
-- Performing Test CXX_SUPPORTS_AVX2
-- Performing Test CXX_SUPPORTS_AVX2 - Success
-- Performing Test CXX_SUPPORTS_AVX512
-- Performing Test CXX_SUPPORTS_AVX512 - Success
-- Arrow build warning level: PRODUCTION
CMake Error at cmake_modules/SetupCxxFlags.cmake:384 (message):
   Unknown compiler: IntelLLVM 2023.2.0
Call Stack (most recent call first):
   CMakeLists.txt:419 (include)
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by assignUser**
### Rationale for this change

The IntelLLVM compiler has a different compiler ID that we currently can't handle and causes the build to fail. 

### What changes are included in this PR?

This adds the missing flags/IDs. Mimalloc in the current bundled version is not compatible with IntelLLVM this can be worked around by using a system version, a simple version bump is not sufficient and I don't think it's worth the effort to fix it properly for now.

For the R package build I have disabled mimalloc with IntelLLVM to avoid issues on CRAN.

* Closes: #37750

### CODE REVIEW

File: r/inst/build_arrow_static.sh [hunk 1]
```diff
@@ -55,6 +55,13 @@ else
   ARROW_DEFAULT_PARAM="OFF"
 fi
 
+# Disable mimalloc on IntelLLVM
```
Comment (kou) [inline r/inst/build_arrow_static.sh:58]: Could you add a comment why we need to disable mimalloc? (Or could you open a new issue for it and refer it in this comment?)

**Review by kou — APPROVED** [review]
+1

Can we add a nightly CI job for IntelLLVM?

**Comment by assignUser** [comment]
> Can we add a nightly CI job for IntelLLVM?

If there was any user request/bug reports for it but we only found this due to a synthetic test on CRAN so I don't really think that is worth the effort and cost(in ci time) at the moment. AFAIK we don't even have a job for classic Intel compiler...

File: r/inst/build_arrow_static.sh (hunk 1 above)
Comment (assignUser) [reply r/inst/build_arrow_static.sh]: done

File: cpp/cmake_modules/SetupCxxFlags.cmake [hunk 2]
```diff
@@ -329,7 +329,8 @@ if("${BUILD_WARNING_LEVEL}" STREQUAL "CHECKIN")
     set(CXX_COMMON_FLAGS "${CXX_COMMON_FLAGS} -Wno-sign-conversion")
     set(CXX_COMMON_FLAGS "${CXX_COMMON_FLAGS} -Wunused-result")
     set(CXX_COMMON_FLAGS "${CXX_COMMON_FLAGS} -Wdate-time")
-  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
+  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel" OR CMAKE_CXX_COMPILER_ID STREQUAL
+                                                   "IntelLLVM")
```
Comment (h-vetinari) [inline cpp/cmake_modules/SetupCxxFlags.cmake:333]: The code further up in the diff is using a regex-match already; would make this a bit easier I guess...
```suggestion
  elseif(CMAKE_CXX_COMPILER_ID Matches "^Intel(LLVM)?$")
```

Comment (thisisnic) [reply cpp/cmake_modules/SetupCxxFlags.cmake:333]: I hope you don't mind, but I'm going to merge the PR as I need it to cherry-pick into an R package release I'm doing today, but we could make this change in a follow-up PR.
