### PR TITLE
GH-40252: [C++] Make span SFINAE standards-conforming to enable compilation with nvcc

### LINKED ISSUE #40252: [C++] Span implementation includes non-conformant SFINAE
### Describe the bug, including details regarding any error messages, version, and platform.

The span polyfill includes a SFINAE overload for selecting [which types a span should be constructible from](https://github.com/apache/arrow/blob/apache-arrow-15.0.0/cpp/src/arrow/util/span.h#L61). Currently this implementation includes code that is technically in violation of the standard because it requires querying another constructor of `span<T>` at a point when the type is still incomplete. Other span implementations avoid this kind of templating: here are 1) [Microsoft's GSL implementation](https://github.com/microsoft/GSL/blob/caae4dd0f8343efb879369dcd08a2b18aae59f3b/include/gsl/span#L500-L512) and 2) [cudf's implementation in RAPIDS](https://github.com/rapidsai/cudf/blob/branch-24.04/cpp/include/cudf/utilities/span.hpp#L235). 

It seems like both clang and gcc allow this particular code to compile from my experiments, but nvcc does not. [Here is an example with the compiler explorer demonstrating the expected failure mode with an even simpler construct](https://godbolt.org/z/9MTjq7b3h) (also showing that the current code compiles, albeit unexpectedly). Prior to Arrow 15 this was not a major issue unless external code tried to use Arrow's span directly. However, after the merge of #38027 span.h is transitively included by `arrow/api.h`, which means that essentially any code including Arrow headers will no longer compile on device. Here's a minimal example:

```
#include <arrow/api.h>
int main() { return 0; }
```

And attempting to compile it:
```
(rapids) coder _ ~/local/arrow/span_test $ nvcc test.cu  -I ../cpp/install/include/
../cpp/install/include/arrow/result.h(263): warning #2810-D: ignoring return value type with "nodiscard" attribute

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

../cpp/install/include/arrow/util/span.h(62): error: incomplete type is not allowed

../cpp/install/include/arrow/record_batch.h(335): warning #2810-D: ignoring return value type with "nodiscard" attribute

../cpp/install/include/arrow/record_batch.h(338): warning #2810-D: ignoring return value type with "nodiscard" attribute

../cpp/install/include/arrow/table.h(244): warning #611-D: overloaded virtual function "arrow::RecordBatchReader::ReadNext" is only partially overridden in class "arrow::TableBatchReader"

1 error detected in the compilation of "test.cu".
```
This issue may be fixed using a different expression analogous to those shown in the other span implementations linked above.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by vyasr**
### Rationale for this change

The current code uses an incomplete type in a SFINAE construct.

Closes #40252 

### What changes are included in this PR?

This PR changes the way that the type is specified to avoid any UB.

### Are these changes tested?

I tested locally that code that originally failed to compile with nvcc now compiles successfully. The same code also compiles under clang and gcc. This is a minimal reproducer:
```
#include <arrow/api.h>
#include <vector>

int main() {
  arrow::util::span<int> x{std::vector<int>{1, 2, 3}};
}
```

I did not include it here because it is a compile-time rather than runtime issue, and because at present it only manifests on nvcc.

### Are there any user-facing changes?

No.

* GitHub Issue: #40252

### CODE REVIEW

**Comment by vyasr** [comment]
I should say that I've tested this with both CUDA 11.8 and CUDA 12.0.

File: cpp/src/arrow/util/span.h [hunk 1]
```diff
@@ -59,12 +59,13 @@ writing code which would break when it is replaced by std::span.)");
...
       typename DisableUnlessConstructibleFromDataAndSize =
-          decltype(span<T>(std::data(std::declval<R>()), std::size(std::declval<R>()))),
+          std::enable_if_t<std::is_convertible_v< std::remove_pointer_t<decltype(std::data(std::declval<R&>()))> (*)[],
+                                              T(*)[]>>,
       typename DisableUnlessSimilarTypes = std::enable_if_t<std::is_same_v<
           std::decay_t<std::remove_pointer_t<decltype(std::data(std::declval<R>()))>>,
           std::decay_t<T>>>>
   // NOLINTNEXTLINE runtime/explicit, non-const reference
-  constexpr span(R&& range) : span{std::data(range), std::size(range)} {}
+  constexpr span(R& range) : span{std::data(range), std::size(range)} {}
```
Comment (pitrou) [inline cpp/src/arrow/util/span.h:68]: Why not keep the universal reference `R&&`?

Comment (vyasr) [reply cpp/src/arrow/util/span.h]: I ran into a different issue with the universal ref where the template also matched an rvalue input, which is forbidden by one of the tests. I just reverted that change so that you can see it. I believe that the test is correct since you wouldn't want to create a span pointing to a temporary that is immediately discarded. While rvalues can extend the lifetime of objects (see the "rvalue references" section of https://en.cppreference.com/w/cpp/language/reference) that wouldn't make this kind of usage safe since the span would persist after that expression.

Comment (pitrou) [reply cpp/src/arrow/util/span.h]: Ah, fair enough.

**Comment by felipecrv** [comment]
CI builds are complaining.

File: cpp/src/arrow/util/span.h (hunk 1 above)
Comment (vyasr) [reply cpp/src/arrow/util/span.h]: OK I think I've got a working version of this now. No need to change the reference parameter.

**Comment by vyasr** [comment]
@felipecrv @pitrou thanks for your patience. I have something that is working now (still waiting to see if it has any issues on the Windows builds in CI, but I've tested various compilers on Linux and they're happy so I'm hopeful). It's a bit more verbose than the old solution, but equally readable.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

File: cpp/src/arrow/util/span_test.cc [hunk 2]
```diff
@@ -51,7 +51,6 @@ TEST(Span, Construction) {
 
   static_assert(std::is_constructible_v<span<const int>, decltype(arr)&>);
   static_assert(std::is_constructible_v<span<const int>, decltype(const_arr)&>);
-  static_assert(std::is_constructible_v<span<const int>, span<int>>);
```
Comment (pitrou) [inline cpp/src/arrow/util/span_test.cc:54]: Hmm... does this mean conversion from `span<T>` to `span<const T>` doesn't work anymore?

File: cpp/src/arrow/util/span.h [hunk 3]
```diff
@@ -25,6 +25,18 @@
 
 namespace arrow::util {
 
+template <class T>
+class span;
+
+template <class T, class R, class Enable = void>
+struct ConstructibleFromDataAndSize : std::false_type {};
+
+template <class T, class R>
```
Comment (pitrou) [inline cpp/src/arrow/util/span.h:34]: Can you add a comment explaining why this construct is needed, and pointing to the GH issue?

File: cpp/src/arrow/util/span_test.cc (hunk 2 above)
Comment (vyasr) [reply cpp/src/arrow/util/span_test.cc:54]: Nope. Sorry I meant to leave this comment on this PR but forgot, but the reason I removed this line is because it's redundant. The same check already exists on line 42. I noticed it while experimenting.

File: cpp/src/arrow/util/span.h (hunk 3 above)
Comment (vyasr) [reply cpp/src/arrow/util/span.h:34]: Yup sure.

Comment (vyasr) [reply cpp/src/arrow/util/span.h:47]: Done.

File: cpp/src/arrow/util/span_test.cc (hunk 2 above)
Comment (pitrou) [reply cpp/src/arrow/util/span_test.cc:54]: Ok, thanks!

**Comment by pitrou** [comment]
@raulcd This is a possible candidate for 15.0.2, but not critical.

**Comment by bdice** [comment]
This would be nice to get in 15.0.2 if possible. It blocks RAPIDS updating Arrow from 14 to 15. Not super high priority - so it's fine if it slips to a later patch release or a near-term major release - but it would be nice to keep up with the latest Arrow major version.

**Comment by vyasr** [comment]
Thank you for pushing on the patch release!
