### PR TITLE
GH-40052: [C++][FS][Azure] Fix CreateDir and DeleteDir trailing slash issues on hierarchical namespace accounts

### LINKED ISSUE #40052: [C++][FS][Azure] Fix CreateDir and DeleteDir on hierarchical namespace accounts where the directory has a trailing `/`
### Describe the bug, including details regarding any error messages, version, and platform.

Manually modifying https://github.com/apache/arrow/pull/40021 to run the Python tests from against a hierarchical namespace account has highlighted some missing test coverage in the existing C++ tests and some cases that we need to fix. 

Currently the following fail on hierarchical namespace storage accounts.
```
fs->CreateDir("directory/")
``` 
```
fs->DeleteDir("directory/")
``` 
They fail with 
```
Failed to delete a directory: directory/: https://tomtesthns.blob.core.windows.net/ea119933-c9d3-11ee-989a-71cec6336ac8/directory/ Azure Error: [InvalidUri] 400 The request URI is invalid.
The request URI is invalid.
RequestId:c9ad826a-101f-0005-5be0-5d0db4000000
Time:2024-02-12T18:24:12.9974541Z
Request ID: c9ad826a-101f-0005-5be0-5d0db4000000
```
Removing the trailing slash solves the problem. 

I haven't tested but I expect `DeleteDirContents` probably has the same issue. 

### Component(s)

C++

### PR DESCRIPTION
**Pull request by Tom-Newton**
### Rationale for this change
There were the following failure cases
```
fs->CreateDir("directory/")
``` 
```
fs->DeleteDir("directory/")
``` 
They fail with 
```
Failed to delete a directory: directory/: https://tomtesthns.blob.core.windows.net/ea119933-c9d3-11ee-989a-71cec6336ac8/directory/ Azure Error: [InvalidUri] 400 The request URI is invalid.
The request URI is invalid.
RequestId:c9ad826a-101f-0005-5be0-5d0db4000000
Time:2024-02-12T18:24:12.9974541Z
Request ID: c9ad826a-101f-0005-5be0-5d0db4000000
```

### What changes are included in this PR?
Add tests to cover these cases. 
Remove trailing slashes to avoid these issues. 

### Are these changes tested?
Yes. I added new test cases to cover these cases. I was rather torn about whether to add precise tests like I've done or to duplicate every test case we had and run it a second time with trailing slashes.

### Are there any user-facing changes?
Fixed bug on `CreateDir` and `DeleteDir`.

* Closes: #40052

### CODE REVIEW

File: cpp/src/arrow/filesystem/azurefs_test.cc [hunk 1]
```diff
@@ -844,6 +861,21 @@ class TestAzureFileSystem : public ::testing::Test {
     AssertFileInfo(fs(), blob_path, FileType::NotFound);
   }
 
+  void TestDeleteDirSuccessHaveBlobWithTrailingSlash() {
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/azurefs_test.cc:864]: I would rename this to `TestNonEmptyDirWithTrailingSlash`. "have blob with trailing slash" can be misinterpreted as the blob path itself having a trailing slash.

**Review by felipecrv — APPROVED** [review]
Thank you for catching and fixing this. I was careful with trailing slashes in the `Move()` implementation and tests, but missed this one in `CreateDir`.

File: cpp/src/arrow/filesystem/azurefs_test.cc (hunk 1 above)
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs_test.cc]: Done

**Review by felipecrv — APPROVED** [review]
