### PR TITLE
GH-36674: [C++] Use anonymous namespace in arrow/ipc/reader.cc

### LINKED ISSUE #36674: [C++] Use anonymous namespace in arrow/IPC/reader.cc
### Describe the bug, including details regarding any error messages, version, and platform.

It is technically not a bug, but the following types and functions should be in in file scope:

IpcReadConext, BatchDataReadRequest, ArrayLoader,
DecompressBuffer(s), LoadRecordBatch*, GetCompression*,
ReadRecordBatchInternal,
GetInclusionMaskAndOutSchmea, UnpackSchemaMessage,
ReadDictionary, AsyncRecordBatchStreamReaderImpl,

### Component(s)

C++

### PR DESCRIPTION
**Pull request by pegasas**
### Rationale for this change

The following types and functions should be in file scope:

IpcReadConext, BatchDataReadRequest, ArrayLoader,
DecompressBuffer(s), LoadRecordBatch*, GetCompression*,
ReadRecordBatchInternal,
GetInclusionMaskAndOutSchmea, UnpackSchemaMessage,
ReadDictionary, AsyncRecordBatchStreamReaderImpl.

### What changes are included in this PR?

Use anonymous namespace around the aforementioned definitions.

### Are these changes tested?

No

### Are there any user-facing changes?

No

* Closes: #36674

### CODE REVIEW

**Comment by pegasas** [comment]
trying to fix https://github.com/apache/arrow/issues/36674

**Comment by pegasas** [comment]
trying to fix https://github.com/apache/arrow/issues/36674

**Comment by pegasas** [comment]
hi, @westonpace ,

Would you like to review this PR when anytime you are available?

Regards,
Junyao

File: cpp/src/arrow/ipc/reader.cc [hunk 1]
```diff
@@ -643,27 +641,6 @@ static Status ReadContiguousPayload(io::InputStream* file,
   return Status::OK();
 }
```
Comment (pitrou) [inline cpp/src/arrow/ipc/reader.cc:642]: Can you remove the `static` qualifier above, since it has become redundant?

**Review by pitrou — CHANGES_REQUESTED** [review]

**Comment by pitrou** [comment]
@pegasas Can you make the PR description a bit more explicit?

File: cpp/src/arrow/ipc/reader.cc (hunk 1 above)
Comment (pegasas) [reply cpp/src/arrow/ipc/reader.cc:642]: Thanks @pitrou  for review! removed.

**Comment by pegasas** [comment]
> @pegasas Can you make the PR description a bit more explicit?

Sure.

I added more description into that.

**Review by pitrou — APPROVED** [review]
