### PR TITLE
GH-15054: [C++] Change s3 finalization to happen after arrow threads finished, add pyarrow exit hook

### LINKED ISSUE #15054: [CI][Python] wheel-manylinux2014-* sometimes crashed on pytest exit
### Describe the bug, including details regarding any error messages, version, and platform.

wheel-manylinux2014-cp38-amd64 2022-12-20 nighty:

https://github.com/ursacomputing/crossbow/actions/runs/3738813751/jobs/6345300403#step:9:775

```text
= 4294 passed, 382 skipped, 18 xfailed, 2 xpassed, 4 warnings in 522.05s (0:08:42) =
/arrow/ci/scripts/python_wheel_unix_test.sh: line 95:    79 Segmentation fault      (core dumped) python -m pytest -r s --pyargs pyarrow
```

wheel-manylinux2014-cp39-arm64 2022-12-20 nighty:

https://app.travis-ci.com/github/ursacomputing/crossbow/builds/259026563#L5708

```text
= 4324 passed, 352 skipped, 18 xfailed, 2 xpassed, 1 warning in 141.20s (0:02:21) =
/arrow/ci/scripts/python_wheel_unix_test.sh: line 95:    15 Segmentation fault      (core dumped) python -m pytest -r s --pyargs pyarrow
```

### Component(s)

Continuous Integration, Packaging, Python

### PR DESCRIPTION
**Pull request by westonpace**
CRITICAL FIX: When statically linking error with AWS it was possible to have a crash on shutdown/exit.  Now that should no longer be possible.

BREAKING CHANGE: S3 can only be initialized and finalized once.

BREAKING CHANGE: S3 (the AWS SDK) will not be finalized until after all CPU & I/O threads are finished.
* Closes: #15054

### CODE REVIEW

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 1]
```diff
@@ -2568,84 +2568,92 @@ namespace {
...
+    switch (options.log_level) {
+      LOG_LEVEL_CASE(Fatal)
+      LOG_LEVEL_CASE(Error)
+      LOG_LEVEL_CASE(Warn)
+      LOG_LEVEL_CASE(Info)
+      LOG_LEVEL_CASE(Debug)
+      LOG_LEVEL_CASE(Trace)
+      default:
+        aws_log_level = Aws::Utils::Logging::LogLevel::Off;
+    }
```
Comment (vibhatha) [inline cpp/src/arrow/filesystem/s3fs.cc:2591]: is the new tab an expected change?

Comment (westonpace) [reply cpp/src/arrow/filesystem/s3fs.cc:2591]: Yes.  The initialize and finalize methods were file-scoped methods previously.  Now they have become the constructor/destructor of the `AwsInstance` class.  Since they are in a class they get some indentation.

**Review by zeroshade — APPROVED** [review]
I don't know if I'm the best to review here, but at least at the moment I don't see anything glaringly problematic with this and it seems like a good idea in general. 

It feels like it should be better tested, but I'm not particularly sure how would be a good way to do so. But that might just be because it's the end of the day lol.

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 2]
```diff
@@ -2573,98 +2573,105 @@ namespace {
...
-  RegionResolver::ResetDefaultInstance();
-  Aws::ShutdownAPI(aws_options);
-  aws_initialized.store(false);
-  return Status::OK();
+std::shared_ptr<AwsInstance>* GetAwsInstance(const S3GlobalOptions& options) {
+  static auto instance = CreateAwsInstance(options);
+  return &instance;
 }
 
+bool IsAwsInitialized() { return !!GetAwsInstance({}); }
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/s3fs.cc:2647]: If this gets called before `InitializeS3`, the `options` passed there will be ignored and an instance based on `{}` options will stick around. I think bringing back the `bool` flag can avoid these risks.

**Comment by westonpace** [comment]
Thanks @felipecrv , that is a good point regarding IsInitialized.  I added the flag back but put it inside the instance object.  I put everything inside the instance object and I think the code is simpler now.  What do you think of this version?

**Review by felipecrv — APPROVED** [review]
This LGTM. Thank you!

**Comment by westonpace** [comment]
These R crashes are a little concerning since they seem to be crashes at shutdown.  Maybe it is related.

**Comment by westonpace** [comment]
Yes, the R crashes are relevant.  With this fix we ensure that `AWS::ShutdownAPI` is the last call we make to AWS.  However, AWS has static global objects of its own.  So it is entirely possible that these have been destroyed by the time `AWS::ShutdownAPI` is called.  In fact, by prolonging the call to `ShutdownAPI` here it seems we are making the R situation worse because it is more likely these other static globals have been destroyed.  There is an open AWS issue for this at https://github.com/aws/aws-sdk-cpp/issues/1550  .  However, it does not sound like it will be resolved quickly.  In the meantime an R atexit hook of some kind will be required (technically it has always been required but we've gotten lucky).

File: r/R/arrow-package.R [hunk 3]
```diff
@@ -147,6 +153,12 @@ supported_dplyr_methods <- list(
   # Register extension types that we use internally
   reregister_extension_type(vctrs_extension_type(vctrs::unspecified()))
 
+  # Registers a callback to run at session exit
+  .onLoad <- function(libname, pkgname) {
+    print(parent.env(environment()))
+    reg.finalizer(parent.env(environment()), finalize_s3, onexit=TRUE)
+  }
+
```
Comment (paleolimbot) [inline r/R/arrow-package.R:161]: I know you asked about this earlier and found `.onUnload()`...just putting a note here in case this gets forgotten about.

If `.onUnload()` isn't working you can create your own environment an register a finalizer on that:

```r
s3_finalizer <- new.env(parent = emptyenv())

.onLoad <- function(...) {
  # ...
  reg.finalizer(s3_finalizer, finalize_s3, onexit=TRUE)
}
```

You probably shouldn't register a finalizer on the package namespace because somebody else might have done that (maybe even R).

**Comment by westonpace** [comment]
The broken C++ tests are unrelated (will be fixed by #35145).  It seems the R tests are passing now.  Would appreciate a review from @paleolimbot or @thisisnic on the R changes.

@kou do you know if cglib / ruby is using S3?  If so, is it calling `FinalizeS3` in some kind of shutdown hook?  Or do we need a change there too.

File: r/R/arrow-package.R (hunk 3 above)
Comment (paleolimbot) [reply r/R/arrow-package.R:161]: There is also `.onLoad()` defined twice here as written (you should be able to use the existing `.onLoad()` to register this hook if you can't in fact use `.onUnload()`.

Comment (westonpace) [reply r/R/arrow-package.R:161]: Ah, ok.  I will change to this pattern instead of `parent.env(environment())`

Comment (westonpace) [reply r/R/arrow-package.R:161]: Also, I just realized I left the print in >_<

Comment (paleolimbot) [reply r/R/arrow-package.R:161]: And if `.onUnload()` really isn't working make sure to put a comment in explaining that (so I don't forget about this and try to consolidate our namespace unload incorrectly)

Comment (westonpace) [reply r/R/arrow-package.R]: Ok, I think I've resolved all your concerns now.  Thanks for looking at this.

Comment (westonpace) [reply r/R/arrow-package.R]: > And if .onUnload() really isn't working make sure to put a comment in explaining that (so I don't forget about this and try to consolidate our namespace unload incorrectly)

Added a comment

**Comment by kou** [comment]
> do you know if cglib / ruby is using S3? If so, is it calling `FinalizeS3` in some kind of shutdown hook? Or do we need a change there too.

Yes, I know. GLib/Ruby is using S3.
It doesn't call `FinalizeS3()` automatically but it provides APIs that can call `InitializeS3()` and `FinalizeS3()` explicitly. So we don't need changes for GLib/Ruby here for now.
If a report from community is raised, we can consider this.

**Comment by westonpace** [comment]
Thanks, that sounds reasonable.  I'll merge when CI passes then.

**Comment by assignUser** [comment]
I have added the appropriate labels for visibility
