### PR TITLE
GH-41246: [C++][Python] Simplify nested field encryption configuration

### LINKED ISSUE #41246: [Python] Attempt to encrypt column of type 'list' produces OSError
### Describe the bug, including details regarding any error messages, version, and platform.

pyarrow 15.0.2

Changing the table definition for example at python/examples/parquet_encryption/sample_vault_kms_client.py to this:

```
    table = pa.Table.from_pydict({
        'a': pa.array([1, 2, 3]),
        'b': pa.array([['a', 'b', 'c'], ['a', 'b', 'c'], ['a', 'b', 'c']]),
        'c': pa.array(['x', 'y', 'z'])
    })
```

produces an exception:
`OSError: Encrypted column b not in file schema`

I expected the encryption to work on a list type. I didn't test other non-fundamental types (like structs) or nested types. I did look for clarification on the capability in Parquet and Arrow, without much luck. Apologies if I missed something.

Thanks for Arrow, it's quite nice!

### Component(s)

Python

### PR DESCRIPTION
**Pull request by EnricoMi**
### Rationale for this change

Columns can b encrypted with individual keys. For this, the column name have to be set in `EncryptionConfiguration::column_keys`. This poses the following challenges for columns with nested fields like `MapType`, `ListType`, and `StructType`. Encrypting a column of such type requires providing an encryption key for all nested (leaf) fields. Ideally, the column name should be sufficient (as it is for any other data type) to encrypt all nested fields.

### What changes are included in this PR?

The column name can be used to encrypt all nested fields of `StrutType`, `MapType`, and `ListType` columns with the same encryption key. The current column naming scheme can still be used for backward compatibility.

### Are these changes tested?
Tested in C++ and Python.

### Are there any user-facing changes?
Column encryption can be configured with less code and more intuitive naming.

Documentation and examples updated.

Fixes #41246.
* GitHub Issue: #41246

### CODE REVIEW

**Review by AlenkaF — COMMENTED** [review]
The Python tests LGTM - they are vey concise and reflect the C++ tests.

The C++ addition of `FileEncryptionProperties::encrypt_schema` looks good to me also but will need a check from a C++ developer. @wgtmac mind having a look?

**Comment by AlenkaF** [comment]
Note, CI Win failures do not look related but there is a linter fix needed:

```
@@ -257,11 +257,12 @@ void FileEncryptionProperties::encrypt_schema(const SchemaDescriptor& schema) {
       // encrypted_column encrypts column 'it' when 'it' is either equal to
       // encrypted_column, or 'it' starts with encrypted_column_prefix,
       // i.e. encrypted_column followed by a '.'
-      while (it != column_path_vec.end() &&
-             (it->first == encrypted_column ||
-               // C++20: can be replaced with it->first.starts_with(encrypted_column_prefix)
-              it->first.compare(0, encrypted_column_prefix_len,
-                                encrypted_column_prefix) == 0)) {
+      while (
+          it != column_path_vec.end() &&
+          (it->first == encrypted_column ||
+           // C++20: can be replaced with it->first.starts_with(encrypted_column_prefix)
+           it->first.compare(0, encrypted_column_prefix_len, encrypted_column_prefix) ==
+               0)) {
```

**Comment by AlenkaF** [comment]
The C++ failure looks related.

**Comment by AlenkaF** [comment]
cc @pitrou, this is connected to https://github.com/apache/arrow/pull/45411.

**Comment by pitrou** [comment]
> This adds a user-friendly notation for nested fields:
> * Columns `col.key` and `col.value` can be used to reference they key and value nested field of a `MapType` column. Currently, `col.key_value.key` and `col.key_value.value` are required, respectively.

Is this useful? Is there a reasonable use case for using different encryption settings for the map key and value columns, respectively? Otherwise I think we can only keep the following items, which will also simplify the semantics and the implementation:

> * Columns `col.element` can be used to reference they individual list elements of a `ListType` column. Currently, `col.list.element` is required.
> * The actual column name can be used to encrypt all nested fields with the same encryption key.
> * The current column naming scheme can still be used for backward compatibility.

**Comment by EnricoMi** [comment]
> Is this useful? Is there a reasonable use case for using different encryption settings for the map key and value columns, respectively?

Irrespective of it being useful, it is currently possible to do via `col.key_value.key` and `col.key_value.value`. This pull request simplifies that notation consistently with lists and structs.

**Comment by EnricoMi** [comment]
Note that I have removed encrypting the individual list elements via `col.element` as I cannot see a difference in semantics and encryption output between `col.element` and `col`. Both notations are equivalent.

Encrypting a single field of a list of structs column can be denoted as `col.f1` rather than `col.element.f1`.

What do you think?

**Comment by pitrou** [comment]
> Note that I have removed encrypting the individual list elements via `col.element` as I cannot see a difference in semantics and encryption output between `col.element` and `col`. Both notations are equivalent.
> 
> Encrypting a single field of a list of structs column can be denoted as `col.f1` rather than `col.element.f1`.

Sorry for the delay. That seems fine to me, and the documentation will be easier to read like that.

**Review by pitrou — COMMENTED** [review]
An incomplete review, as I have not gone over all the changes yet.

File: cpp/src/parquet/encryption/encryption.cc [hunk 1]
```diff
@@ -163,6 +163,76 @@ FileEncryptionProperties::Builder* FileEncryptionProperties::Builder::encrypted_
...
+          });
+      bool matches = false;
+
+      // encrypted_column encrypts column 'it' when 'it' is either equal to
+      // encrypted_column, or 'it' starts with encrypted_column_prefix,
+      // i.e. encrypted_column followed by a '.'
+      while (
+          it != column_path_vec.end() &&
+          (it->first == encrypted_column ||
+           // C++20: can be replaced with it->first.starts_with(encrypted_column_prefix)
```
[the remark this answers is not in the document]
Comment (EnricoMi) [reply cpp/src/parquet/encryption/encryption.cc]: thanks for the pointer, applied

File: cpp/src/parquet/encryption/encryption.h [hunk 2]
```diff
@@ -429,6 +429,16 @@ class PARQUET_EXPORT FileEncryptionProperties {
     return encrypted_columns_;
   }
 
+  /// All columns in encrypted_columns must refer to columns in the given schema.
```
[the remark this answers is not in the document]
Comment (EnricoMi) [reply cpp/src/parquet/encryption/encryption.h]: Rephrased entirely

```
  /// \brief Check and replace encrypted columns according to schema
  ///
  /// Checks all columns in encrypted_columns reference columns in the given schema.
  /// Replaces parent fields in encrypted_columns with all their nested fields,
  /// all using the same encrypion key.
  /// Fields referenced by schema paths are replaced with the respective parquet paths.
  /// These are usually identical, except for nested fields of lists and maps.
```

File: cpp/src/parquet/encryption/encryption.h [hunk 3]
```diff
@@ -429,6 +429,16 @@ class PARQUET_EXPORT FileEncryptionProperties {
...
+  /// They can also refer to parent fields if schema contains nested fields. Then
+  /// all those nested fields of a matching parent field are encrypted by the same key.
+  /// This method modifies encrypted_columns to reflect this.
+  ///
+  /// Columns in encrypted_columns can refer to the parquet column paths as well as the
+  /// schema paths of columns. Those are usually identical, except for nested fields of
+  /// lists and maps.
+  void encrypt_schema(const SchemaDescriptor& schema);
```
[the remark this answers is not in the document]
Comment (EnricoMi) [reply cpp/src/parquet/encryption/encryption.h]: done

File: cpp/src/parquet/schema.h [hunk 4]
```diff
@@ -132,6 +134,8 @@ class PARQUET_EXPORT Node {
 
   const std::shared_ptr<ColumnPath> path() const;
 
+  const std::shared_ptr<ColumnPath> schema_path() const;
```
[the remark this answers is not in the document]
Comment (EnricoMi) [reply cpp/src/parquet/schema.h]: added for now

File: cpp/src/parquet/schema.h [hunk 5]
```diff
@@ -386,6 +390,8 @@ class PARQUET_EXPORT ColumnDescriptor {
 
   const std::shared_ptr<schema::ColumnPath> path() const;
 
+  const std::shared_ptr<schema::ColumnPath> schema_path() const;
```
[the remark this answers is not in the document]
Comment (EnricoMi) [reply cpp/src/parquet/schema.h]: same here

**Comment by EnricoMi** [comment]
I have reworked the logic. It does not support the simplified column paths like `map.key`. Users that want to use different encryption keys for different nested fields (which is still supported) have to use the non-intuitive column paths like `map.key_value.key`.

**Comment by EnricoMi** [comment]
TODO:
- update PR description
- update docs

**Comment by EnricoMi** [comment]
I have further reduced the logic. You can either configure an encryption key for a full column path match, or a root field name match. This simplifies match logic and computational effort when looking up encryption properties for column paths.

**Comment by EnricoMi** [comment]
@pitrou what are your thoughts on the latest logic / semantics?

File: cpp/src/parquet/schema.cc [hunk 6]
```diff
@@ -68,11 +68,25 @@ std::shared_ptr<ColumnPath> ColumnPath::FromDotString(const std::string& dotstri
...
+    if (schema_path &&
+        (
+            // nested fields in arrow schema do not know these intermediate nodes
+            cursor->parent()->converted_type() == ConvertedType::MAP ||
+            cursor->parent()->converted_type() == ConvertedType::LIST ||
+            (cursor->parent()->parent() &&
+             cursor->parent()->parent()->converted_type() == ConvertedType::LIST))) {
+      cursor = cursor->parent();
+      continue;
+    }
```
[the remark this answers is not in the document]
Comment (EnricoMi) [reply cpp/src/parquet/schema.cc]: This specific logic has been removed. Lookup logic has been simplified to looking up column path or root column among the keys. No type-specific logic left.

**Comment by EnricoMi** [comment]
@pitrou hope you have a moment for this

**Comment by pitrou** [comment]
I'll be out on vacation, so not before ~10 days I think.

**Comment by EnricoMi** [comment]
No worries, enjoy!

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc [hunk 7]
```diff
@@ -79,14 +83,20 @@ const auto kAllParamValues = ::testing::Values(
     EncryptionTestParam{false, true, true}, EncryptionTestParam{true, true, true});
 
 // Base class to test writing and reading encrypted dataset.
-class DatasetEncryptionTestBase : public testing::TestWithParam<EncryptionTestParam> {
+template <typename T, typename = typename std::enable_if<
+                          std::is_base_of<EncryptionTestParam, T>::value>::type>
```
Comment (pitrou) [inline cpp/src/arrow/dataset/file_parquet_encryption_test.cc]: No need to change this, but as a nit it can probably be simplified to
```suggestion
template <typename T, typename = typename std::enable_if_t<
                          std::is_base_of_v<EncryptionTestParam, T>>
```

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc [hunk 8]
```diff
@@ -398,9 +411,191 @@ TEST_P(DatasetEncryptionTest, ReadSingleFile) {
 
 INSTANTIATE_TEST_SUITE_P(DatasetEncryptionTest, DatasetEncryptionTest, kAllParamValues);
 
+struct NestedFieldsEncryptionTestParam : EncryptionTestParam {
```
Comment (pitrou) [inline cpp/src/arrow/dataset/file_parquet_encryption_test.cc:412]: Should this use `public` inheritance?

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc [hunk 9]
```diff
@@ -79,14 +83,20 @@ const auto kAllParamValues = ::testing::Values(
...
+                          std::is_base_of<EncryptionTestParam, T>::value>::type>
+class DatasetEncryptionTestBase : public testing::TestWithParam<T> {
  public:
 #ifdef ARROW_VALGRIND
   static constexpr int kConcurrentIterations = 4;
 #else
   static constexpr int kConcurrentIterations = 20;
 #endif
 
+  static const EncryptionTestParam& GetParam() {
```
Comment (pitrou) [inline cpp/src/arrow/dataset/file_parquet_encryption_test.cc]: I'm honestly curious why this is required.

File: python/pyarrow/tests/parquet/encryption.py [hunk 10]
```diff
@@ -41,6 +41,8 @@ def wrap_key(self, key_bytes, master_key_identifier):
     def unwrap_key(self, wrapped_key, master_key_identifier):
         """Not a secure cipher - just extract the key from
         the wrapped key"""
+        if master_key_identifier not in self.master_keys_map:
+            raise ValueError("Unknown master key", master_key_identifier)
```
Comment (pitrou) [inline python/pyarrow/tests/parquet/encryption.py:46]: Why not keep the `KeyError` that the line below would raise?

File: python/pyarrow/tests/test_dataset_encryption.py [hunk 11]
```diff
@@ -82,11 +88,11 @@ def create_decryption_config():
     return pe.DecryptionConfiguration(cache_lifetime=300)
 
 
-def create_kms_connection_config():
+def create_kms_connection_config(keys):
     return pe.KmsConnectionConfig(
         custom_kms_conf={
-            FOOTER_KEY_NAME: FOOTER_KEY.decode("UTF-8"),
-            COL_KEY_NAME: COL_KEY.decode("UTF-8"),
+            key_name: key.decode("UTF-8") if isinstance(key, bytes) else key
```
Comment (pitrou) [inline python/pyarrow/tests/test_dataset_encryption.py]: I'm not sure we want to allow both `bytes` and `str` key names here?

**Comment by pitrou** [comment]
@github-actions crossbow submit preview-docs

**Review by pitrou — COMMENTED** [review]
Sorry for the delay. This looks in general, a bunch of minor comments and suggestions below.

File: python/pyarrow/tests/test_dataset_encryption.py (hunk 11 above)
Comment (EnricoMi) [reply python/pyarrow/tests/test_dataset_encryption.py]: right

File: python/pyarrow/tests/parquet/encryption.py (hunk 10 above)
Comment (EnricoMi) [reply python/pyarrow/tests/parquet/encryption.py:46]: I found

    ValueError: ('Unknown master key', 'XYZ')

more expressive than

    KeyError: 'XYZ'

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc (hunk 9 above)
Comment (EnricoMi) [reply cpp/src/arrow/dataset/file_parquet_encryption_test.cc]: Accessing `GetParam` could not derive return type of `testing::WithParamInterface<T>::GetParam`:

    there are no arguments to ‘GetParam’ that depend on a template parameter, so a declaration of ‘GetParam’ must be available

Fixed accessing `GetParam` in 473839e597.

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc (hunk 8 above)
Comment (EnricoMi) [reply cpp/src/arrow/dataset/file_parquet_encryption_test.cc:412]: As in

    struct NestedFieldsEncryptionTestParam : public EncryptionTestParam {

IDE says `public` is redundant here.

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc (hunk 7 above)
Comment (EnricoMi) [reply cpp/src/arrow/dataset/file_parquet_encryption_test.cc]: applied

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc (hunk 8 above)
Comment (pitrou) [reply cpp/src/arrow/dataset/file_parquet_encryption_test.cc:412]: Ha, another C++ subtletly that I ignored/forgot :-)

File: python/pyarrow/tests/parquet/encryption.py (hunk 10 above)
Comment (pitrou) [reply python/pyarrow/tests/parquet/encryption.py:46]: Ok, thanks.

**Comment by pitrou** [comment]
Ha, sorry, CI fails now that https://github.com/apache/arrow/pull/48338 was merged, you need to stop passing the column path to `ColumnEncryptionProperties::Builder`.

**Review by pitrou — APPROVED** [review]
Thanks for the update @EnricoMi !

**Comment by pitrou** [comment]
I'm sorry that it took so long @EnricoMi . Looking forward to more contributions from you!
