### PR TITLE
GH-34391: [C++] Future as-of-join-node hangs on distant times

### LINKED ISSUE #34391: [C++] Future as-of-join-node hangs on distant times
### Describe the bug, including details regarding any error messages, version, and platform.

Future as-of-join-node goes into an infinite loop when right-table times are distant. A specific test case reproducing this is:
```
/*l*/ {R"([[0, 1, 1]])", R"([[1000, 2, 2]])", R"([[2000, 1, 3]])"},
/*r0*/ {R"([[0, 1, 10], [1500, 1, 11], [2500, 1, 12]])"},
/*r1*/ {R"([[0, 1, 100], [1500, 1, 101], [2500, 1, 102]])"},
/*exp_nokey*/ {R"([[0, 0, 1, 10, 100], [1000, 0, 2, 11, 101], [2000, 0, 3, 12, 102]])"},
/*exp_emptykey*/ {R"([[0, 1, 1, 10, 100], [1000, 2, 2, 11, 101], [2000, 1, 3, 12, 102]])"},
/*exp*/ {R"([[0, 1, 1, 10, 100], [1000, 2, 2, null, null], [2000, 1, 3, 12, 102]])"}, 1000);
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by rtpsw**
See #34391
* Closes: #34391

Note that the `TestBasic7Forward` test-case included in the PR reproduces the hang in the pre-PR code.

### CODE REVIEW

**Comment by rtpsw** [comment]
Marked as a draft because the current version appears to infrequently hit a race condition. For example:
```
Unequal at absolute position 2

@@ -0, +0 @@
-null
@@ -2, +1 @@
+13
Expected:
  [
    13,
    13
  ]
Actual:
  [
    null,
    13
  ]
Google Test trace:
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:587: Right-1 type: double
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:585: Right-0 type: uint64
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:583: Left type: time64[us]
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:581: Key type: int32
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:579: Time type: timestamp[us, tz=UTC]
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:577: Iteration: 63
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:567: Types seed: 1677489070467191057
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:968: AsofJoinBasicTest_TestEmpty1Forward_MutateNullKey
/mnt/user1/tscontract/github/rtpsw/arrow2/cpp/src/arrow/compute/exec/asof_join_node_test.cc:967: AsofJoinBasicTest_TestEmpty1Forward_MutateNullKey
```
occurred at iteration 63 (which can change, even when the seed is fixed) only of the above test-case, after several runs of the tester have passed.

**Comment by rtpsw** [comment]
cc @westonpace @icexelloss, in case you have an idea about the apparent race condition.

**Comment by rtpsw** [comment]
Coming back to this, I see [the same race condition](https://github.com/apache/arrow/pull/34392#issuecomment-1449560506) after merging main.

One experiment I made is related to [this comment](https://github.com/apache/arrow/blob/311cc52d208034214c325983f416f2f847a2a015/cpp/src/arrow/acero/asof_join_node.cc#L186-L189):
- When I add a lock over `mutex_` to `UnsyncFront`, I get the same results, including the race condition. This means that `UnsyncFront` is called safely per the comment, i.e., not called concurrently with `pop` or `try_pop`.
- When  I add a lock over `mutex_` to `UnsyncSize`, I see a deadlock between one thread calling `AsofJoinNode::ProcessThread` -> `ConcurrentQueue::Pop and another calling `InputState::Push` -> `BackpressureConcurrentQueue::Push` -> `BackpressureConcurrentQueue::DoHandle` -> `ConcurrentQueue::UnsyncSize`. This isn't surprising, just shows that the comment does not apply to `UnsyncSize`.

**Comment by rtpsw** [comment]
I fixed the race condition, at least locally, as I now see [this macOS CI failure](https://github.com/apache/arrow/actions/runs/4656962922/jobs/8241089942?pr=34392).

In a debug session, I observed [that `GetCurrentTime()`](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L571) for one of the RHS tables was returning 0 when it was expected to be ahead, leading to [the tolerance not accepting](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L865) this 0 time [in `CompositeReferenceTable::Emplace`](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L834) and to [keeping a null batch](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L874), which [checked up](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L1019) as [a null value](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L1024) in the [materialized column](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L1011) and ended up in the output. This scenario occurred only in a future-as-of-join, where `GetCurrentTime()` [returns `memo_.current_time_`](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L572). Following up on this, I noticed that `MemoStore` was [updating `current_time_`](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L308-L324) only upon [entry-removal](https://github.com/apache/arrow/blob/e3dd1cc7f918d3b4709ce712e7d08efafd8c9601/cpp/src/arrow/acero/asof_join_node.cc#L283). Apparently, the (not-so-controlled) timing of this entry-removal can cause the race condition. I fixed `MemoStore` to update the current time upon entry-store, and simplified its updating upon entry-removal.

Following this fix, I did not locally observe the race condition in several runs of the tester, whereas before I observed it after one or two runs. There is still the macOS failure, however, I don't have access to a macOS to locally test on it.

**Comment by rtpsw** [comment]
For reference, here are the relevant log lines from the [macOS CI job failure](https://github.com/apache/arrow/actions/runs/4656962922/jobs/8241089942?pr=34392):
```
[ RUN      ] AsofJoinNodeTest/AsofJoinBasicTest.TestBasic7Forward/1
/Users/runner/work/arrow/arrow/cpp/src/arrow/testing/gtest_util.cc:486: Failure
Failed
Unequal at absolute position 3

@@ -2, +2 @@
-null
+00:00:00.000012
Expected:
  [
    00:00:00.000010,
    null,
    00:00:00.000012
  ]
Actual:
  [
    00:00:00.000010,
    null,
    null
  ]
Google Test trace:
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:591: Right-1 type: timestamp[s, tz=UTC]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:589: Right-0 type: time64[us]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:587: Left type: int8
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:585: Key type: time64[ns]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:583: Time type: time32[ms]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:581: Iteration: 1
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:572: Types seed: 1681127979841385
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:922: AsofJoinBasicTest_TestBasic7_DoubleByKey
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:926: AsofJoinBasicTest_TestBasic7Forward_DoubleByKey
/Users/runner/work/arrow/arrow/cpp/src/arrow/testing/gtest_util.cc:486: Failure
Failed
Unequal at absolute position 3

@@ -1, +1 @@
-1970-01-01 00:00:00.000011
+null
Expected:
  [
    1970-01-01 00:00:00.000010,
    null,
    1970-01-01 00:00:00.000012
  ]
Actual:
  [
    1970-01-01 00:00:00.000010,
    1970-01-01 00:00:00.000011,
    1970-01-01 00:00:00.000012
  ]
Google Test trace:
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:591: Right-1 type: time64[us]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:589: Right-0 type: timestamp[us, tz=UTC]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:587: Left type: time64[us]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:585: Key type: int32
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:583: Time type: timestamp[ms, tz=UTC]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:581: Iteration: 9
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:572: Types seed: 1681127979841385
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:922: AsofJoinBasicTest_TestBasic7_DoubleByKey
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:926: AsofJoinBasicTest_TestBasic7Forward_DoubleByKey
[  FAILED  ] AsofJoinNodeTest/AsofJoinBasicTest.TestBasic7Forward/1, where GetParam() = AsofJoinBasicParams: DoubleByKey (202 ms)
```

**Comment by rtpsw** [comment]
The [recent commit](https://github.com/apache/arrow/pull/34392/commits/c2e9dbc39ecf31ffad284c0242109198fe2635e7) allowed the macOS CI job that previously failed to succeed this time (the [single-job failure](https://github.com/apache/arrow/actions/runs/4707863345/jobs/8349979477?pr=34392) this time is irrelevant). Of course, this does not prove the as-of-join code is now free of race conditions, yet the explanation below may help in reasoning about what's going on.

The main idea in this recent fix is to ensure `MemoStore` has a valid current time when `GetCurrentTime()` is called, since in a future-as-of-join `GetCurrentTime()` returns `memo_.current_time_`. The initial current time of 0, which is set by the `MemoStore` constructor, is invalid; it was observed in the [debug session described above](https://github.com/apache/arrow/pull/34392#issuecomment-1501767228) and led to a null-value in the output. The fix includes the following:
1. Changing `MemoStore::current_time_` to be an atomic number.
2.  Adding `MemoStore::UpdateTime`, which updates `MemoStore::current_time_` in a multi-threaded-safe way to the given time if the latter is greater.
3. Invoking `MemoStore::UpdateTime` with the time of the first row of a received batch. This happens-before (in the multi-threading sense of the term) the batch is pushed to the queue, and therefore ensures that `MemoStore::current_time_` is valid by the time `GetLatestTime()` is called when the batch is processed out of the queue.

Note that I believe the as-of-join node's process-thread is not responsible for the race condition. It just processes in the same order of batches received, regardless of this being done in a separate thread. I believe the race condition is due to the non-deterministic order of arrival of batches to the as-of-join node, and that there's an order of arrival that drives the code (before the recent fix) to access an invalid `MemoStore::current_time_`. If so, this order could be found and then simulated in a test-case, though I think this task can be left to later.

**Comment by rtpsw** [comment]
cc @westonpace, @icexelloss

**Comment by icexelloss** [comment]
Thanks @rtpsw I don't have to look this closely Today but I will try to take a look soon

**Comment by icexelloss** [comment]
A quick look and a couple of questions:
> The initial current time of 0, which is set by the MemoStore constructor, is invalid;
Why would the code later unable to detect that the current time is invalid? (I assume this is invalid because it hasn't got any input?)

> I believe the race condition is due to the non-deterministic order of arrival of batches to the as-of-join node,
This is surprising - why would this happen in serial execution? And what evidence makes you believe this is happening?

**Comment by rtpsw** [comment]
> Why would the code later unable to detect that the current time is invalid? (I assume this is invalid because it hasn't got any input?)

Detecting is not good enough. `GetCurrentTime()` needs a valid time when called, so there needs to be code that ensures this. The `MemoStore` constructor can't do this because at that time there is no input yet.

> This is surprising - why would this happen in serial execution? And what evidence makes you believe this is happening?

I don't (yet?) have evidence to directly support this. What I noted is evidence against the race condition being due to the process thread, and so I suspect the order of input batches. I suspect that when a node has at least two inputs, the order of batches to that node (i.e., across its inputs) may still be non-deterministic even with serial execution. Perhaps @westonpace can shed some light here, or we could investigate.

**Comment by icexelloss** [comment]
> Detecting is not good enough. GetCurrentTime() needs a valid time when called, so there needs to be code that ensures this. The MemoStore constructor can't do this because at that time there is no input yet.

If the `GetCurrenTime() returns something that the caller can detect as invalid (e.g., negative value), then the caller can treat it as if there is no data and skip the current processing?

**Comment by rtpsw** [comment]
> If the `GetCurrentTime()` returns something that the caller can detect as invalid (e.g., negative value), then the caller can treat it as if there is no data and skip the current processing?

That might be doable, but I doubt it would be simple. The calls to `GetCurrentTime` are in a deep enough stack that would be annoying to unwind while carrying some status indicating the invalid time condition.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 1]
```diff
@@ -707,15 +704,16 @@ class InputState {
...
+      // "updated" was not modified in the loop; set it here
       updated = memo_.RemoveEntriesWithLesserTime(ts);
     }
     return updated;
   }
 
   void Rehash() {
     MemoStore new_memo(memo_.no_future_);
-    new_memo.current_time_ = memo_.current_time_;
+    new_memo.current_time_ = (OnType)memo_.current_time_;
```
Comment (westonpace) [inline cpp/src/arrow/acero/asof_join_node.cc:716]: Minor nit: Prefer `static_cast`.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 2]
```diff
@@ -249,12 +250,18 @@ struct MemoStore {
...
-    std::swap(current_time_, memo.current_time_);
+    current_time_ = memo.current_time_.exchange((OnType)current_time_);
     entries_.swap(memo.entries_);
     future_entries_.swap(memo.future_entries_);
     times_.swap(memo.times_);
   }
 
+  void UpdateTime(OnType ts) {
+    OnType prev_time = current_time_;
+    while (prev_time < ts && current_time_.compare_exchange_weak(prev_time, ts)) {
```
Comment (westonpace) [inline cpp/src/arrow/acero/asof_join_node.cc:261]: Why use a `while` loop here instead of a single call to `compare_exchange_strong`?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 3]
```diff
@@ -569,7 +565,7 @@ class InputState {
   // returns the latest time (which is current); otherwise, returns the current time.
   // used when checking whether RHS is up to date with LHS.
   OnType GetCurrentTime() const {
-    return memo_.no_future_ ? GetLatestTime() : memo_.current_time_;
+    return memo_.no_future_ ? GetLatestTime() : (OnType)memo_.current_time_;
```
Comment (westonpace) [inline cpp/src/arrow/acero/asof_join_node.cc:568]: Prefer `static_cast`.

**Review by westonpace — COMMENTED** [review]
A few minor suggestions.

**Comment by westonpace** [comment]
I agree that order between sources is not guaranteed.  In other words, the first batch might be `Source1Batch1` or it might be `Source2Batch1` but it will not be `Source1Batch2`.

Another potential source of contention / race conditions is the interplay between `InputReceived` and the process thread.  Normally `InputReceived` runs first and then the process thread runs afterwards.  However, if the process thread is currently processing, it might run at the same time as `InputReceived` and there could be potential race conditions on the state.  Though I'm pretty sure you're aware of this already :)

**Comment by rtpsw** [comment]
> Another potential source of contention / race conditions is the interplay between `InputReceived` and the process thread. Normally `InputReceived` runs first and then the process thread runs afterwards. However, if the process thread is currently processing, it might run at the same time as `InputReceived` and there could be potential race conditions on the state. Though I'm pretty sure you're aware of this already :)

Indeed I'm aware. This scenario doesn't cause trouble because [the `InputReceived` method](https://github.com/apache/arrow/blob/a2548a79a191c280966d869c7778643fd64fdcd6/cpp/src/arrow/acero/asof_join_node.cc#L1503-L1513) basically just pushes a batch to the queue.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 2 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:261]: This is because `compare_and_exchange_weak` (see [doc](https://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange)) may not find the expected value of `prev_time` from line 260 by the time the loop is executed due to a race condition (expected to be rare). In this case `false` is returned and `prev_time` is updated to the value of `current_time_`. Then, another iteration is tried. This is normal CAS-loop logic.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 1 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:714]: Done.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 3 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc]: Done.

**Comment by rtpsw** [comment]
I see a failure on macOS and Windows with the same symptom as seen before for the race condition. Need to debug on at least one of these platforms.

**Comment by wjones127** [comment]
This is odd. I have attempted to reproduce the failing test on both x86_64 and arm64 MacOS but couldn't. The full test suite passes on both.

**Comment by wjones127** [comment]
It seems like the failure is inconsistent, which suggests it might have to do with timing more than the platform.

**Comment by rtpsw** [comment]
> This is odd. I have attempted to reproduce the failing test on both x86_64 and arm64 MacOS but couldn't. The full test suite passes on both.

Perhaps the CI job's configuration, such as build flags, is different than what you tried?

> It seems like the failure is inconsistent, which suggests it might have to do with timing more than the platform.

It is indeed inconsistent, but it occured way more frequently in the macOS CI job than elsewhere (e.g., it doesn't seem to occur at all on my local platform). So, I suspect the platform/configuration of this job has something to do with it.

**Comment by rtpsw** [comment]
For reference, here's the [macOS CI job](https://github.com/apache/arrow/actions/runs/4731098434/jobs/8395636846?pr=34392)'s diff:
```
[ RUN      ] AsofJoinNodeTest/AsofJoinBasicTest.TestBasic7Forward/2
/Users/runner/work/arrow/arrow/cpp/src/arrow/testing/gtest_util.cc:486: Failure
Failed
Unequal at absolute position 3

@@ -1, +1 @@
-1970-01-12
+null
Expected:
  [
    1970-01-11,
    null,
    1970-01-13
  ]
Actual:
  [
    1970-01-11,
    1970-01-12,
    1970-01-13
  ]
Google Test trace:
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:591: Right-1 type: timestamp[s, tz=UTC]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:589: Right-0 type: date32[day]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:587: Left type: bool
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:585: Key type: time64[ns]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:583: Time type: timestamp[s, tz=UTC]
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:581: Iteration: 5
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:572: Types seed: 1681813755919658
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:922: AsofJoinBasicTest_TestBasic7_MutateByKey
/Users/runner/work/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:926: AsofJoinBasicTest_TestBasic7Forward_MutateByKey
[  FAILED  ] AsofJoinNodeTest/AsofJoinBasicTest.TestBasic7Forward/2, where GetParam() = AsofJoinBasicParams: MutateByKey (257 ms)
```
and the [WIndows MinGW32 CI job](https://github.com/apache/arrow/actions/runs/4731098434/jobs/8395637803?pr=34392)'s diff:
```
[ RUN      ] AsofJoinNodeTest/AsofJoinBasicTest.TestBasic7Forward/1
D:/a/arrow/arrow/cpp/src/arrow/testing/gtest_util.cc:486: Failure
Failed
Unequal at absolute position 3

@@ -1, +1 @@
-11
+null
Expected:
  [
    10,
    null,
    12
  ]
Actual:
  [
    10,
    11,
    12
  ]
Google Test trace:
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:591: Right-1 type: time64[us]
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:589: Right-0 type: uint64
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:587: Left type: large_binary
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:585: Key type: int8
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:583: Time type: time64[us]
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:581: Iteration: 54
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:572: Types seed: 1681813189536914100
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:922: AsofJoinBasicTest_TestBasic7_DoubleByKey
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:921: AsofJoinBasicTest_TestBasic7Forward_DoubleByKey
[  FAILED  ] AsofJoinNodeTest/AsofJoinBasicTest.TestBasic7Forward/1, where GetParam() = AsofJoinBasicParams: DoubleByKey (108 ms)
[ RUN      ] AsofJoinNodeTest/AsofJoinBasicTest.TestBasic7Forward/2
```

**Comment by wjones127** [comment]
SSH'd into the runner, and it seems to only fail if other acero test are run concurrently.

```
# Fails:
ctest --parallel 3 -R arrow-acero

# Passes:
ctest -R arrow-acero
build/cpp/debug/arrow-acero-asof-join-node-test
```

I haven't reproduced this locally yet though. Hopefully this gives some clue to what it might be.

**Comment by rtpsw** [comment]
> @wjones127, I'll later make an attempt to gather technical information on a failure occurring in a CI job.

The recent commit includes a mechanism for collecting debug messages, which are shown on failure, that is active in a debug-build for certain test-cases. Hopefully, assuming the same CI job failures occur, this should give us some information to work with.

**Comment by rtpsw** [comment]
There are two failed C++ CI jobs, and in both the actual output (which is different than the expected one) is not in agreement with the produced batches appearing in the debug messages - see details below.

Diff for [`ARM Ubuntu 20.04 C++` CI job](https://github.com/apache/arrow/actions/runs/4776544464/jobs/8491645558?pr=34392):
```
Unequal at absolute position 3

@@ -2, +2 @@
-null
+1970-01-01 00:00:00.000012
Expected:
  [
    1970-01-01 00:00:00.000010,
    null,
    1970-01-01 00:00:00.000012
  ]
Actual:
  [
    1970-01-01 00:00:00.000010,
    null,
    null
  ]
```
whereas the batches produced are:
```
AsofjoinNode(0xaaaaddd73bd0): produce batch 0:
time:   [
    00:00:00.000
  ]
key2:   [
    "0"
  ]
key:   [
    "1"
  ]
l_v0:   [
    00:00:00.000001
  ]
r0_v0:   [
    1970-01-01 00:00:00.000000010
  ]
r1_v0:   [
    100
  ]
...
AsofjoinNode(0xaaaaddd73bd0): produce batch 1:
time:   [
    00:00:01.000
  ]
key2:   [
    "0"
  ]
key:   [
    "2"
  ]
l_v0:   [
    00:00:00.000002
  ]
r0_v0:   [
    null
  ]
r1_v0:   [
    null
  ]
...
AsofjoinNode(0xaaaaddd73bd0): produce batch 2:
time:   [
    00:00:02.000
  ]
key2:   [
    "0"
  ]
key:   [
    "1"
  ]
l_v0:   [
    00:00:00.000003
  ]
r0_v0:   [
    1970-01-01 00:00:00.000000012
  ]
r1_v0:   [
    102
  ]
```

Diff for [`AMD64 macOS 12 C++` CI job](https://github.com/apache/arrow/actions/runs/4776544464/jobs/8491645668?pr=34392):
```
Unequal at absolute position 3

@@ -1, +1 @@
-11
+null
Expected:
  [
    10,
    null,
    12
  ]
Actual:
  [
    10,
    11,
    12
  ]
```
whereas the batches produced are:
```
AsofjoinNode(0x7f7b12021350): produce batch 0:
time:   [
    0
  ]
key2:   [
    0
  ]
key:   [
    1
  ]
l_v0:   [
    31
  ]
r0_v0:   [
    10
  ]
r1_v0:   [
    1970-01-01 00:01:40
  ]
...
AsofjoinNode(0x7f7b12021350): produce batch 1:
time:   [
    1000
  ]
key2:   [
    0
  ]
key:   [
    2
  ]
l_v0:   [
    32
  ]
r0_v0:   [
    null
  ]
r1_v0:   [
    null
  ]
...
AsofjoinNode(0x7f7b12021350): produce batch 2:
time:   [
    2000
  ]
key2:   [
    0
  ]
key:   [
    1
  ]
l_v0:   [
    33
  ]
r0_v0:   [
    12
  ]
r1_v0:   [
    1970-01-01 00:01:42
  ]
```

**Comment by rtpsw** [comment]
The [`AMD64 Conda C++` CI job](https://github.com/apache/arrow/actions/runs/4778086054/jobs/8494259405?pr=34392) shows that a similar failure with improved debug messages. The interesting observation from the pasted output below is for the comparison seen at the bottom: while the actual table is logically equal (up to flattening) to the expected table, the `AssertTablesEqual` comparison fails, as if the actual table had different data. Specifically, it "thinks" the actual data for column 4 (after flattening) is `[10, 11, 12]` whereas in fact it is `[10, null, 12]`. It looks like whatever race condition or root cause here actually affects this comparison logic and not `AsofJoinNode`.

@westonpace, @icexelloss, @wjones127 - what are your thoughts about this?

Pasted output:
```
/arrow/cpp/src/arrow/testing/gtest_util.cc:486: Failure
Failed
Column 4 is different: Unequal at absolute position 0

@@ -1, +1 @@
-11
+null
Expected:
  [
    10,
    null,
    12
  ]
Actual:
  [
    10,
    11,
    12
  ]
Google Test trace:
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:625: Right-1 type: int16
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:623: Right-0 type: int32
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:621: Left type: int16
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:619: Key type: binary
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:617: Time type: int16
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:615: Iteration: 28
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:606: Types seed: 1682252434581436418
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:992: AsofJoinBasicTest_TestBasic7_MutateByKey
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:991: AsofJoinBasicTest_TestBasic7Forward_MutateByKey
AsofJoinTest debug:
AsofjoinNode(0x55b12a56d600): received batch from input 2:
time:   [
    00:00:00.000000,
    00:00:00.001500,
    00:00:00.002500
  ]
key2:   [
    1970-01-01 00:00:00.000000,
    1970-01-01 00:00:00.000000,
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000001,
    1970-01-01 00:00:00.000001,
    1970-01-01 00:00:00.000001
  ]
r1_v0:   [
    1970-01-01 00:00:00.000000100,
    1970-01-01 00:00:00.000000101,
    1970-01-01 00:00:00.000000102
  ]

AsofjoinNode(0x55b12a56d600): received batch from input 1:
time:   [
    00:00:00.000000,
    00:00:00.001500,
    00:00:00.002500
  ]
key2:   [
    1970-01-01 00:00:00.000000,
    1970-01-01 00:00:00.000000,
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000001,
    1970-01-01 00:00:00.000001,
    1970-01-01 00:00:00.000001
  ]
r0_v0:   [
    10,
    11,
    12
  ]

AsofjoinNode(0x55b12a56d600): received batch from input 0:
time:   [
    00:00:00.000000
  ]
key2:   [
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000001
  ]
l_v0:   [
    00:00:00.000001
  ]

AsofjoinNode(0x55b12a56d600): received batch from input 0:
time:   [
    00:00:00.001000
  ]
key2:   [
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000002
  ]
l_v0:   [
    00:00:00.000002
  ]

AsofjoinNode(0x55b12a56d600): received batch from input 0:
time:   [
    00:00:00.002000
  ]
key2:   [
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000001
  ]
l_v0:   [
    00:00:00.000003
  ]

AsofjoinNode(0x55b12a56d600): Advancing input 1
AsofjoinNode(0x55b12a56d600): key hasher 1 got hashes [10621589963589458110, 10621589963589458110, 10621589963589458110]
AsofjoinNode(0x55b12a56d600): memo 1 store: for_time=0 row=0 time=0 key=10621589963589458110
AsofjoinNode(0x55b12a56d600): Advancing input 1 hit distant time=1500 at=0
AsofjoinNode(0x55b12a56d600): memo 1 remove: ts=0
AsofjoinNode(0x55b12a56d600): Advancing input 1 updated=0
AsofjoinNode(0x55b12a56d600): Advancing input 2
AsofjoinNode(0x55b12a56d600): key hasher 2 got hashes [10621589963589458110, 10621589963589458110, 10621589963589458110]
AsofjoinNode(0x55b12a56d600): memo 2 store: for_time=0 row=0 time=0 key=10621589963589458110
AsofjoinNode(0x55b12a56d600): Advancing input 2 hit distant time=1500 at=0
AsofjoinNode(0x55b12a56d600): memo 2 remove: ts=0
AsofjoinNode(0x55b12a56d600): Advancing input 2 updated=0
AsofjoinNode(0x55b12a56d600): key hasher 0 got hashes [10621589963589458110]
AsofjoinNode(0x55b12a56d600): Emplace: key=10621589963589458110 lhs_latest_row=0 lhs_latest_time=0
AsofjoinNode(0x55b12a56d600):   i=1 has_entry=1 time=0 row=0 accepted=1
AsofjoinNode(0x55b12a56d600):   i=2 has_entry=1 time=0 row=0 accepted=1
AsofjoinNode(0x55b12a56d600): memo 1 remove: ts=1000
AsofjoinNode(0x55b12a56d600): memo 2 remove: ts=1000
AsofjoinNode(0x55b12a56d600): produce batch 0:
time:   [
    00:00:00.000000
  ]
key2:   [
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000001
  ]
l_v0:   [
    00:00:00.000001
  ]
r0_v0:   [
    10
  ]
r1_v0:   [
    1970-01-01 00:00:00.000000100
  ]

AsofjoinNode(0x55b12a56d600): Advancing input 1
AsofjoinNode(0x55b12a56d600): memo 1 store: for_time=1000 row=1 time=1500 key=10621589963589458110
AsofjoinNode(0x55b12a56d600): Advancing input 1 hit distant time=2500 at=1000
AsofjoinNode(0x55b12a56d600): memo 1 remove: ts=1000
AsofjoinNode(0x55b12a56d600): Advancing input 1 updated=0
AsofjoinNode(0x55b12a56d600): Advancing input 2
AsofjoinNode(0x55b12a56d600): memo 2 store: for_time=1000 row=1 time=1500 key=10621589963589458110
AsofjoinNode(0x55b12a56d600): Advancing input 2 hit distant time=2500 at=1000
AsofjoinNode(0x55b12a56d600): memo 2 remove: ts=1000
AsofjoinNode(0x55b12a56d600): Advancing input 2 updated=0
AsofjoinNode(0x55b12a56d600): key hasher 0 got hashes [12073851083248405108]
AsofjoinNode(0x55b12a56d600): Emplace: key=12073851083248405108 lhs_latest_row=0 lhs_latest_time=1000
AsofjoinNode(0x55b12a56d600):   i=1 has_entry=0 time=0 row=0 accepted=0
AsofjoinNode(0x55b12a56d600):   i=2 has_entry=0 time=0 row=0 accepted=0
AsofjoinNode(0x55b12a56d600): memo 1 remove: ts=2000
AsofjoinNode(0x55b12a56d600): memo 2 remove: ts=2000
AsofjoinNode(0x55b12a56d600): produce batch 1:
time:   [
    00:00:00.001000
  ]
key2:   [
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000002
  ]
l_v0:   [
    00:00:00.000002
  ]
r0_v0:   [
    null
  ]
r1_v0:   [
    null
  ]

AsofjoinNode(0x55b12a56d600): Advancing input 1
AsofjoinNode(0x55b12a56d600): memo 1 store: for_time=2000 row=2 time=2500 key=10621589963589458110
AsofjoinNode(0x55b12a56d600): memo 1 remove: ts=2000
AsofjoinNode(0x55b12a56d600): Advancing input 1 updated=0
AsofjoinNode(0x55b12a56d600): Advancing input 2
AsofjoinNode(0x55b12a56d600): memo 2 store: for_time=2000 row=2 time=2500 key=10621589963589458110
AsofjoinNode(0x55b12a56d600): memo 2 remove: ts=2000
AsofjoinNode(0x55b12a56d600): Advancing input 2 updated=0
AsofjoinNode(0x55b12a56d600): key hasher 0 got hashes [10621589963589458110]
AsofjoinNode(0x55b12a56d600): Emplace: key=10621589963589458110 lhs_latest_row=0 lhs_latest_time=2000
AsofjoinNode(0x55b12a56d600):   i=1 has_entry=1 time=2500 row=2 accepted=1
AsofjoinNode(0x55b12a56d600):   i=2 has_entry=1 time=2500 row=2 accepted=1
AsofjoinNode(0x55b12a56d600): produce batch 2:
time:   [
    00:00:00.002000
  ]
key2:   [
    1970-01-01 00:00:00.000000
  ]
key:   [
    1970-01-01 00:00:00.000001
  ]
l_v0:   [
    00:00:00.000003
  ]
r0_v0:   [
    12
  ]
r1_v0:   [
    1970-01-01 00:00:00.000000102
  ]

Comparing flattened expected table:
time: time64[us]
key2: timestamp[us, tz=UTC]
key: timestamp[us, tz=UTC]
l_v0: time64[us]
r0_v0: uint16
r1_v0: timestamp[ns, tz=UTC]
----
time:
  [
    [
      00:00:00.000000,
      00:00:00.001000,
      00:00:00.002000
    ]
  ]
key2:
  [
    [
      1970-01-01 00:00:00.000000,
      1970-01-01 00:00:00.000000,
      1970-01-01 00:00:00.000000
    ]
  ]
key:
  [
    [
      1970-01-01 00:00:00.000001,
      1970-01-01 00:00:00.000002,
      1970-01-01 00:00:00.000001
    ]
  ]
l_v0:
  [
    [
      00:00:00.000001,
      00:00:00.000002,
      00:00:00.000003
    ]
  ]
r0_v0:
  [
    [
      10,
      null,
      12
    ]
  ]
r1_v0:
  [
    [
      1970-01-01 00:00:00.000000100,
      null,
      1970-01-01 00:00:00.000000102
    ]
  ]

with flattened result table:
time: time64[us]
key2: timestamp[us, tz=UTC]
key: timestamp[us, tz=UTC]
l_v0: time64[us]
r0_v0: uint16
r1_v0: timestamp[ns, tz=UTC]
----
time:
  [
    [
      00:00:00.000000
    ],
    [
      00:00:00.001000
    ],
    [
      00:00:00.002000
    ]
  ]
key2:
  [
    [
      1970-01-01 00:00:00.000000
    ],
    [
      1970-01-01 00:00:00.000000
    ],
    [
      1970-01-01 00:00:00.000000
    ]
  ]
key:
  [
    [
      1970-01-01 00:00:00.000001
    ],
    [
      1970-01-01 00:00:00.000002
    ],
    [
      1970-01-01 00:00:00.000001
    ]
  ]
l_v0:
  [
    [
      00:00:00.000001
    ],
    [
      00:00:00.000002
    ],
    [
      00:00:00.000003
    ]
  ]
r0_v0:
  [
    [
      10
    ],
    [
      null
    ],
    [
      12
    ]
  ]
r1_v0:
  [
    [
      1970-01-01 00:00:00.000000100
    ],
    [
      null
    ],
    [
      1970-01-01 00:00:00.000000102
    ]
  ]
```

**Comment by icexelloss** [comment]
@rtpsw I don't have a good idea where the problem might be. But if AsofJoin is producing the right batches then I think we can add debug information in the downstream node of AsofJoin (I think it's a sink node) and trace where did the output batch value change.

Also, in the failed case, is all the column in the second row/batch wrong or just a single column is wrong?

**Comment by rtpsw** [comment]
> @rtpsw I don't have a good idea where the problem might be. But if AsofJoin is producing the right batches then I think we can add debug information in the downstream node of AsofJoin (I think it's a sink node) and trace where did the output batch value change.

Right. I designed the code here to support adding on-failure-only debug messages to other nodes., so what you're describing is convenient to do. 

> Also, in the failed case, is all the column in the second row/batch wrong or just a single column is wrong?

The debug messages do not have this information, because only info about the failed column is printed. However, given these messages and that the columns are checked in order, we know that (1) the failed column has index 4, (2) all columns with lower indices were checked and passed, and (3) there is only one more column with index 5 which wasn't checked.

I can add debug messages to show the check result for each column.

**Comment by wjones127** [comment]
> what are your thoughts about this?

It sounds like there may be some subtle bug with the null buffers in `Concatenate` function. The other failure indicates it's not that it ignores it, since there is a new null instead of a missing one.

It sounds almost like buffer overflow similar to what I debugged here https://github.com/apache/arrow/pull/12216 but I tried the ARROW_DEBUG_MEMORY_POOL check on the failing CI job and it didn't detect anything. Although these are null buffers for one value each that are being concatenated, so buffer overflow isn't quite right either.

**Comment by rtpsw** [comment]
I used a macOS host, courtesy of @westonpace, to fairly reliably get a failure when under `stress -c`. After debugging and with a few added debug-messages, I think I finally figured out the as-of-join issue here.

The pasted output below, taken from a failure repro, shows the following. `input 0`, which is the left table of the as-of-join, received 3 batches with different content, as expected. However, all these batches have the same pointer-address (as seen in `input 0 push` messages), suggesting the next batch is allocated at the same address of the previous one that got freed; this is an unusual condition, which appears to occur only when certain runtime resources are restricted (such as when under stress and in certain CI jobs). The `key hasher 0` message shows that the left table's key hasher only hashes once, which indicates it is seeing a single batch instead of 3. This is because it [invalidates its cached hashes only when the batch address changes](https://github.com/apache/arrow/blob/0ea1a103dfc2fc4ab5a5d839369a805e2ae657a2/cpp/src/arrow/acero/asof_join_node.cc#L359-L362), which isn't the case here. Consequently, the same key hashes (here, one hash for a single-row batch) are computed for the second batch of `input 0` as for its first and third batches; this is incorrect given [the left table's batches](https://github.com/apache/arrow/pull/34392/files#diff-dd19a151cdbe71c43bad130c0dc2d6d00db89e57b6588d1597ee0011608e3299R980), since the second batch has 2 in the `key` column whereas the first and third batches have 1 there. This leads to an incorrect output table, which would have been correct for a same-key-test-case.

The [recent commit](https://github.com/apache/arrow/pull/34392/commits/34134f0b40ea241fa3c686df06c487d0539b9c99) fixes the key-hasher to invalidate when a new batch is received on the input it is associated with. With this fix, I was able to run 100 repetitions on the macOS host under stress without observing any failure. The CI job failures for this commit seem to be unrelated.

Note that I still do not have an explanation for (and wasn't able to reproduce) [the AMD64 Conda job's behavior](https://github.com/apache/arrow/pull/34392#issuecomment-1519077885). In particular, the key hasher invalidation issue does not occur there, since `key hasher 0` messages show hashes are computed for each batch of the left table. However, the above may be satisfying enough to accept this PR.

<details>

<summary>Pasted output:</summary>

AsofjoinNode(0x103e04eb0): received batch from input 2:
time:   [
    1970-01-01 00:00:00.000000,
    1970-01-01 00:00:00.001500,
    1970-01-01 00:00:00.002500
  ]
key2:   [
    0,
    0,
    0
  ]
key:   [
    1,
    1,
    1
  ]
r1_v0:   [
    100,
    101,
    102
  ]

AsofjoinNode(0x103e04eb0): input 2 push batch=0x60000291ca98
AsofjoinNode(0x103e04eb0): received batch from input 1:
time:   [
    1970-01-01 00:00:00.000000,
    1970-01-01 00:00:00.001500,
    1970-01-01 00:00:00.002500
  ]
key2:   [
    0,
    0,
    0
  ]
key:   [
    1,
    1,
    1
  ]
r0_v0:   [
    10,
    11,
    12
  ]

AsofjoinNode(0x103e04eb0): input 1 push batch=0x60000291c7f8
AsofjoinNode(0x103e04eb0): received batch from input 0:
time:   [
    1970-01-01 00:00:00.000000
  ]
key2:   [
    0
  ]
key:   [
    1
  ]
l_v0:   [
    1
  ]

AsofjoinNode(0x103e04eb0): input 0 push batch=0x60000290c2b8
AsofjoinNode(0x103e04eb0): Advancing input 1
AsofjoinNode(0x103e04eb0): key hasher 1 got hashes [10621589963589458110, 10621589963589458110, 10621589963589458110]
AsofjoinNode(0x103e04eb0): memo 1 store: for_time=0 row=0 time=0 key=10621589963589458110
AsofjoinNode(0x103e04eb0): Advancing input 1 hit distant time=1500 at=0
AsofjoinNode(0x103e04eb0): memo 1 remove: ts=0
AsofjoinNode(0x103e04eb0): Advancing input 1 updated=0
AsofjoinNode(0x103e04eb0): Advancing input 2
AsofjoinNode(0x103e04eb0): key hasher 2 got hashes [10621589963589458110, 10621589963589458110, 10621589963589458110]
AsofjoinNode(0x103e04eb0): memo 2 store: for_time=0 row=0 time=0 key=10621589963589458110
AsofjoinNode(0x103e04eb0): Advancing input 2 hit distant time=1500 at=0
AsofjoinNode(0x103e04eb0): memo 2 remove: ts=0
AsofjoinNode(0x103e04eb0): Advancing input 2 updated=0
AsofjoinNode(0x103e04eb0): key hasher 0 got hashes [10621589963589458110]
AsofjoinNode(0x103e04eb0): Emplace: key=10621589963589458110 lhs_latest_row=0 lhs_latest_time=0
AsofjoinNode(0x103e04eb0):   i=1 has_entry=1 time=0 row=0 accepted=1
AsofjoinNode(0x103e04eb0):   i=2 has_entry=1 time=0 row=0 accepted=1
AsofjoinNode(0x103e04eb0): input 0 try-pop batch=0x0
AsofjoinNode(0x103e04eb0): produce batch 0:
time:   [
    1970-01-01 00:00:00.000000
  ]
key2:   [
    0
  ]
key:   [
    1
  ]
l_v0:   [
    1
  ]
r0_v0:   [
    10
  ]
r1_v0:   [
    100
  ]

AsofjoinNode(0x103e04eb0): received batch from input 0:
time:   [
    1970-01-01 00:00:00.001000
  ]
key2:   [
    0
  ]
key:   [
    2
  ]
l_v0:   [
    2
  ]

AsofjoinNode(0x103e04eb0): input 0 push batch=0x60000290c2b8
AsofjoinNode(0x103e04eb0): Advancing input 1
AsofjoinNode(0x103e04eb0): memo 1 store: for_time=1000 row=1 time=1500 key=10621589963589458110
AsofjoinNode(0x103e04eb0): Advancing input 1 hit distant time=2500 at=1000
AsofjoinNode(0x103e04eb0): memo 1 store: for_time=1000 row=2 time=2500 key=10621589963589458110
AsofjoinNode(0x103e04eb0): input 1 try-pop batch=0x0
AsofjoinNode(0x103e04eb0): memo 1 remove: ts=1000
AsofjoinNode(0x103e04eb0): Advancing input 1 updated=1
AsofjoinNode(0x103e04eb0): Advancing input 2
AsofjoinNode(0x103e04eb0): memo 2 store: for_time=1000 row=1 time=1500 key=10621589963589458110
AsofjoinNode(0x103e04eb0): Advancing input 2 hit distant time=2500 at=1000
AsofjoinNode(0x103e04eb0): memo 2 store: for_time=1000 row=2 time=2500 key=10621589963589458110
AsofjoinNode(0x103e04eb0): input 2 try-pop batch=0x0
AsofjoinNode(0x103e04eb0): memo 2 remove: ts=1000
AsofjoinNode(0x103e04eb0): Advancing input 2 updated=1
AsofjoinNode(0x103e04eb0): Emplace: key=10621589963589458110 lhs_latest_row=0 lhs_latest_time=1000
AsofjoinNode(0x103e04eb0):   i=1 has_entry=1 time=1500 row=1 accepted=1
AsofjoinNode(0x103e04eb0):   i=2 has_entry=1 time=1500 row=1 accepted=1
AsofjoinNode(0x103e04eb0): input 0 try-pop batch=0x0
AsofjoinNode(0x103e04eb0): produce batch 1:
time:   [
    1970-01-01 00:00:00.001000
  ]
key2:   [
    0
  ]
key:   [
    2
  ]
l_v0:   [
    2
  ]
r0_v0:   [
    11
  ]
r1_v0:   [
    101
  ]

AsofjoinNode(0x103e04eb0): received batch from input 0:
time:   [
    1970-01-01 00:00:00.002000
  ]
key2:   [
    0
  ]
key:   [
    1
  ]
l_v0:   [
    3
  ]

AsofjoinNode(0x103e04eb0): input 0 push batch=0x60000290c2b8
AsofjoinNode(0x103e04eb0): Advancing input 1
AsofjoinNode(0x103e04eb0): memo 1 remove: ts=2000
AsofjoinNode(0x103e04eb0): Advancing input 2
AsofjoinNode(0x103e04eb0): memo 2 remove: ts=2000
AsofjoinNode(0x103e04eb0): Emplace: key=10621589963589458110 lhs_latest_row=0 lhs_latest_time=2000
AsofjoinNode(0x103e04eb0):   i=1 has_entry=1 time=2500 row=2 accepted=1
AsofjoinNode(0x103e04eb0):   i=2 has_entry=1 time=2500 row=2 accepted=1
AsofjoinNode(0x103e04eb0): input 0 try-pop batch=0x0
AsofjoinNode(0x103e04eb0): produce batch 2:
time:   [
    1970-01-01 00:00:00.002000
  ]
key2:   [
    0
  ]
key:   [
    1
  ]
l_v0:   [
    3
  ]
r0_v0:   [
    12
  ]
r1_v0:   [
    102
  ]

Comparing flattened expected table:
time: timestamp[us, tz=UTC]
key2: int32
key: int32
l_v0: int32
r0_v0: uint64
r1_v0: int32
----
time:
  [
    [
      1970-01-01 00:00:00.000000,
      1970-01-01 00:00:00.001000,
      1970-01-01 00:00:00.002000
    ]
  ]
key2:
  [
    [
      0,
      0,
      0
    ]
  ]
key:
  [
    [
      1,
      2,
      1
    ]
  ]
l_v0:
  [
    [
      1,
      2,
      3
    ]
  ]
r0_v0:
  [
    [
      10,
      null,
      12
    ]
  ]
r1_v0:
  [
    [
      100,
      null,
      102
    ]
  ]

with flattened result table:
time: timestamp[us, tz=UTC]
key2: int32
key: int32
l_v0: int32
r0_v0: uint64
r1_v0: int32
----
time:
  [
    [
      1970-01-01 00:00:00.000000
    ],
    [
      1970-01-01 00:00:00.001000
    ],
    [
      1970-01-01 00:00:00.002000
    ]
  ]
key2:
  [
    [
      0
    ],
    [
      0
    ],
    [
      0
    ]
  ]
key:
  [
    [
      1
    ],
    [
      2
    ],
    [
      1
    ]
  ]
l_v0:
  [
    [
      1
    ],
    [
      2
    ],
    [
      3
    ]
  ]
r0_v0:
  [
    [
      10
    ],
    [
      11
    ],
    [
      12
    ]
  ]
r1_v0:
  [
    [
      100
    ],
    [
      101
    ],
    [
      102
    ]
  ]
```

</details>

**Comment by rtpsw** [comment]
I investigated [the AMD Conda job's behavior](https://github.com/apache/arrow/pull/34392#issuecomment-1519077885) and I have a plausible explanation. The debug-messages were collected afresh for each test iteration, so the debug-messages shown were those for the most recent iteration. However, the `AssertTablesEqual` failure messages was collected for an earlier iteration, because it was collected using `FAIL()`, which (because, e.g., no exception was generated) the as-of-join-test callers up the stack ignored and just continued running until gtest captured the failure. Given this, the debug-messages and the failure message were unrelated, so there is nothing for us to worry about here.

To avoid this confusion in the future, I fixed the test-iteration code to break on failure.

**Comment by icexelloss** [comment]
@rtpsw I will try to take look later. Can you please summarize a description for PR? i.e., what is the issue and what is the fix? Which changes to intended to keep? (since there are lots of debug statement)

**Comment by rtpsw** [comment]
> Can you please summarize a description for PR? i.e., what is the issue and what is the fix?

We started with the goal of enabling future as-of-join and the first problem was the hang that started this issue. As the issue progressed with proposed fixes, we were dealing with a follow-up problem - what we called race condition. Perhaps a good title for this issue is something like "Fix future as-of-join-node hang and race condition". The resolution was [fixing handling](https://github.com/apache/arrow/pull/34392/commits/000219736c0abb2e0c9525963f083c0ab04d16cc) of [time](https://github.com/apache/arrow/pull/34392/commits/0dc7fa2339ddfa73be30f4780a35f3ca057f8957) and [key hasher invalidation](https://github.com/apache/arrow/pull/34392/commits/34134f0b40ea241fa3c686df06c487d0539b9c99).

> Which changes to intended to keep? (since there are lots of debug statement)

All the code related to debug-messages here is enabled only in debug mode (via `#ifndef NDEBUG`), so it doesn't hurt production runs. In addition, the code only collects debug-messages inside testers where `PrepareTest` is used, so its full effect is limited to these cases. OTOH, even in other testers, it always computes debug-messages (in debug mode), so I could fix the code to avoid this (using if-statements). Also, if a non-deterministic as-of-join problem pops up in the future in a CI job, which runs in debug mode, the debug messages collected for it should be helpful. Finally, the mechanism for collecting detailed debug messages only for a failed iteration implemented here is reusable in future Arrow non-deterministic failure investigations. My vote is to keep this code, though I wouldn't insist if anyone feels strongly against that.

**Comment by icexelloss** [comment]
Thanks @rtpsw.

> "Fix future as-of-join-node hang and race condition". The resolution was [fixing handling](https://github.com/apache/arrow/pull/34392/commits/000219736c0abb2e0c9525963f083c0ab04d16cc) of [time](https://github.com/apache/arrow/pull/34392/commits/0dc7fa2339ddfa73be30f4780a35f3ca057f8957) and [key hasher invalidation](https://github.com/apache/arrow/pull/34392/commits/34134f0b40ea241fa3c686df06c487d0539b9c99).

Thanks for the link for the resolution Can you summarize  what is the reason that causes the the hanging and the race condition here.

**Comment by rtpsw** [comment]
**First problem: hang on distant times**

What was the problem? In a future as-of-join, when the right table's next timestamp was distant (i.e., beyond the future tolerance) compared to the left table's, the join hanged.
 
What was the cause of the problem? The as-of-join node mishandled the `MemoStore` maintenance, failed to advance any of the tables and went into an infinite loop. The as-of-join node wasn't tested before with distant times.

What was the fix and how? [This](https://github.com/apache/arrow/pull/34392/commits/000219736c0abb2e0c9525963f083c0ab04d16cc) and [this commit](https://github.com/apache/arrow/pull/34392/commits/0dc7fa2339ddfa73be30f4780a35f3ca057f8957) fixed the `MemoStore` maintenance and the condition for advancing, and added a test-case with distant times.

**Second problem: non-deterministic output**

What was the problem? The newly added test-case produced a different output rarely and only on specific platforms/CI-jobs.

What was the cause of the problem? The as-of-join node used cached hashes, instead of computing new ones, for the key columns of a new batch. This happened because the new batch had the same pointer-address as the previous one, and the cache-invalidation condition relied on the pointer-address changing for a new batch. This rare same-pointer-address condition, which triggered the bug, occurred only on specific platforms/CI-jobs, likely under restricted memory resources.

What was the fix and how? The [fix](https://github.com/apache/arrow/pull/34392/commits/34134f0b40ea241fa3c686df06c487d0539b9c99) added cache invalidation upon receiving a new batch, allowing the hashes to be recomputed.

**Comment by icexelloss** [comment]
Thanks @rtpsw , some follow up questions:

> The as-of-join node mishandled the MemoStore maintenance,

Can you give a bit more details on what about MemoStore maintenance is not handles correctly? You can put code in the PR too if that is easier to align with the code. It's has been a while since I looked at future asof code so a refresher is appreciated.

> The as-of-join node used cached hashes, instead of computing new ones, for the key columns of a new batch.

Can you remind me why do we cache the hash in the first place. What is the case that we want to hash the same batch more than once?

**Comment by rtpsw** [comment]
> Can you give a bit more details on what about MemoStore maintenance is not handles correctly? You can put code in the PR too if that is easier to align with the code. It's has been a while since I looked at future asof code so a refresher is appreciated.

It would take a good amount of detail to explain the interaction between the various moving parts of the code. I'd prefer to add comments to the code to explain. Would that work?

> Can you remind me why do we cache the hash in the first place. What is the case that we want to hash the same batch more than once?

Hashes are used when the key is not fixed-width (and fits within 64-bits), e.g., when there are multiple key columns, and the hash for each row of the key columns is used as the value for grouping. For performance, the code computes hashes for all rows of the key columns of a given input batch once and caches the result. Later, whenever `GetKey` is invoked, which happens frequently, the key hash is quickly found in the cache.

**Comment by icexelloss** [comment]
> It would take a good amount of detail to explain the interaction between the various moving parts of the code. I'd prefer to add comments to the code to explain. Would that work?

Yes that would work

File: cpp/src/arrow/chunked_array.h [hunk 4]
```diff
@@ -263,8 +263,10 @@ Status ApplyBinaryChunked(const ChunkedArray& left, const ChunkedArray& right,
                           Action&& action) {
   MultipleChunkIterator iterator(left, right);
   std::shared_ptr<Array> left_piece, right_piece;
+  int64_t pos = iterator.position();
   while (iterator.Next(&left_piece, &right_piece)) {
-    ARROW_RETURN_NOT_OK(action(*left_piece, *right_piece, iterator.position()));
+    ARROW_RETURN_NOT_OK(action(*left_piece, *right_piece, pos));
+    pos = iterator.position();
```
Comment (westonpace) [inline cpp/src/arrow/chunked_array.h:269]: Why do we need this change?

File: cpp/src/arrow/acero/asof_join_node_test.cc [hunk 5]
```diff
@@ -451,6 +438,53 @@ struct BasicTest {
...
+
+#undef CHECK_RUN_OUTPUT
+#undef EXPAND_BY_KEY_TYPE
+
+  void CheckRunOutput(const BatchesWithSchema& l_batches,
+                      const BatchesWithSchema& r0_batches,
+                      const BatchesWithSchema& r1_batches,
+                      const BatchesWithSchema& exp_batches,
+                      const AsofJoinNodeOptions join_options) {
+#ifndef NDEBUG
```
Comment (westonpace) [inline cpp/src/arrow/acero/asof_join_node_test.cc:468]: Do we need `NDEBUG` checks in tests?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 6]
```diff
@@ -370,13 +475,20 @@ class KeyHasher {
...
             ColumnArrayFromArrayDataAndMetadata(array_data, metadata_[k], i, length);
       }
+      // write directly to the cache
       Hashing64::HashMultiColumn(column_arrays_, &ctx_, hashes_.data() + i);
     }
-    batch_ = batch;
+#ifndef NDEBUG
+    DebugSync(*node_) << "key hasher " << index_ << " got hashes "
+                      << compute::internal::GenericToString(hashes_) << std::endl;
+#endif
```
Comment (westonpace) [inline cpp/src/arrow/acero/asof_join_node.cc:484]: I wonder if it would be possible to do something like...

```
DEBUG_SYNC(*node_, "key hasher", index_, "got hashes ", compute::internal::GenericToString(hashes_), std::endl);
```

The macro could compile to nothing in release mode and then we can get rid of the `#ifndef`

File: cpp/src/arrow/acero/options_internal.h [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+
+namespace arrow {
+namespace acero {
+
+struct DebugOptions {
+  DebugOptions(std::ostream* os, std::mutex* mutex) : os(os), mutex(mutex) {}
+
+  std::ostream* os;
+  std::mutex* mutex;
+};
```
Comment (westonpace) [inline cpp/src/arrow/acero/options_internal.h:33]: Instead of passing these all around in options can we just make it part of the query context & query options?

**Review by westonpace — COMMENTED** [review]
Good catch on the cause.  Mac uses a very different allocator (e.g. it also tends to be less generous with its alignment) so it wouldn't surprise me that mac's allocator is more likely to reuse pointers.

As for the debugging stuff, I've encountered the same problem myself.  I put in a lot of debugging code and them I'm reluctant to pull it all out because I know how useful it would be for debugging future problems.  Perhaps we can find an approach that is more general and less specific to the asof join node?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 8]
```diff
@@ -200,8 +207,74 @@ class ConcurrentQueue {
...
+// Get the debug-mutex associated with the as-of-join node
+std::mutex* GetDebugMutex(AsofJoinNode& node);
+
+// A debug-facility that wraps output-stream insertions with synchronization. Code like
+//
+//   DebugSync(as_of_join_node) << ... << ... << ... ;
+//
+// will insert to the node's debug-stream and guard all insertions as one operation using
+// the node's debug-mutex.
+class DebugSync {
```
[the remark this answers is not in the document]
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:225]: To be sure, you mean that the code here is generally good for pushing and you'd like it refactored soon after?

File: cpp/src/arrow/chunked_array.h (hunk 4 above)
Comment (rtpsw) [reply cpp/src/arrow/chunked_array.h:269]: The pre-PR code reads `iterator.position()` after it is advanced, so the action gets a 1-based column index, which is incorrect per [the documentation comments](https://github.com/apache/arrow/blob/febd0ff144cfb8b2baffb1cb0be57ca40dc7cc77/cpp/src/arrow/chunked_array.h#L239-L260). In the investigation here, this index ended up in the messages and got me confused until I discovered this.

File: cpp/src/arrow/acero/asof_join_node_test.cc (hunk 5 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node_test.cc:468]: I think so, at least for `asof_join_node_test.cc` because, due to a time limit, the number of basic-test iteration it runs is affected by the speed of execution, so the Release and Debug builds behave a bit differently.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 6 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:484]: Yeah, that should work for removing those `#ifndef` used for `DebugSync`. I'll look into this.

File: cpp/src/arrow/acero/options_internal.h (hunk 7 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/options_internal.h:33]: I chose this design to allow the caller to limit the debug-mode to a specific execution node. In a future PR, we could add such arguments in the query context/options as a default for all nodes. Let me know what you prefer.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 6 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc]: This is done in the [recent commit](https://github.com/apache/arrow/pull/34392/commits/85328512f4899ca92ce5404f442036f54d6ab3ee). I tried a number of other approaches that I couldn't get compile with I/O manipulator (like `std::endl`) before settling on this one.

File: cpp/src/arrow/acero/asof_join_node_test.cc (hunk 5 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node_test.cc:468]: Also, there are `#ifndef NDEBUG` sections in the tester code that require similarly-conditionally-compiled elements, like `DebugOptions`, from the main code.

**Comment by rtpsw** [comment]
> Perhaps we can find an approach that is more general and less specific to the asof join node?

The design of `DebugSync` should be reusable in other nodes with simple modifications, which are basically:
- Move the `GetDebugStream` and `GetDebugMutex` methods to `ExecNode`.
- Take an `ExecNode` instead of an `AsofJoinNode` in the constructor of `DebugSync` and in the `GetDebugStream` and `GetDebugMutex` global functions.

We could do that as part of a follow-up PR.

**Comment by rtpsw** [comment]
The recent fix is an attempt to fix to the ["AMD64 Windows 2019 C++ 17" CI job](https://github.com/apache/arrow/actions/runs/4890588626/jobs/8730173377?pr=34392) error:
```
D:/a/arrow/arrow/cpp/src/arrow/acero/asof_join_node.cc(267): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'arrow::acero::MemoStore::Store::<lambda_b10c418846c3718f8df41dfad4d64c46>' (or there is no acceptable conversion)
```

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (westonpace) [reply cpp/src/arrow/acero/asof_join_node.cc:234]: Yes.  I would be ok with that.  As long as an issue is created first and there is a plan to get to it.

File: cpp/src/arrow/chunked_array.h (hunk 4 above)
Comment (westonpace) [reply cpp/src/arrow/chunked_array.h:269]: Ah, I see.  This does appear to be more or less unused outside of test reporting so perhaps it just wasn't noticed.  `MultiChunkIterator::position` is very unintuitive.  However, given its been around a few years, we should probably leave it alone.  Thanks for this fix.

File: cpp/src/arrow/acero/options_internal.h (hunk 7 above)
Comment (westonpace) [reply cpp/src/arrow/acero/options_internal.h:33]: If a user needs the ability to toggle debug logging on a per-node basis then I think that would be better done by passing a list of "enabled node ids" to query context / query options.  For example, in most logging frameworks, I can pass in severity level per-category.  So I can, for example, disable Foo logging in some application, but I do that when I'm configuring logging and not when I'm configuring the Foo feature.  Future PR is ok.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 9]
```diff
@@ -680,6 +816,7 @@ class InputState {
   Result<bool> AdvanceAndMemoize(OnType ts) {
     // Advance the right side row index until we reach the latest right row (for each key)
     // for the given left timestamp.
+    DEBUG_SYNC(node_, "Advancing input ", index_, DEBUG_MANIP(std::endl));
```
Comment (westonpace) [inline cpp/src/arrow/acero/asof_join_node.cc:819]: `DEBUG_MANIP` is ok.  However, I think ending a debug statement with an endline is going to be more common than not ending with an endline (in fact, if we don't end with an endline, I don't think we guarantee things are flushed, and it would still be possible to get interleaved / out of order output).  It would be nice though if there was a `DEBUG_LINE` or `DEBUG_SYNC_LINE` or something that acted exactly like `DEBUG_SYNC` except it included the endline for us.

**Review by westonpace — APPROVED** [review]
To avoid bike shedding I'm going to go ahead and approve the fix.  I think the bug fix you have here is good, but the logging could still use work but can be tackled in follow-up.

In addition to the inline comment I've made I think we should investigate GLOG and see if it has the ability to provide some of this for us.  We've already done the work to add glog to cmake, etc. and so it should be fairly easy to enable it when debugging.  Perhaps we could have it always turned on in tests.

Basically, I'd rather lean on a fully featured logging library than slowly grow into creating one ourselves (e.g. with things like category-specific logging levels).

**Comment by westonpace** [comment]
@icexelloss feel free to merge once the tests are passing and you are happy with this.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 9 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:819]: I agree.

**Comment by rtpsw** [comment]
>  I think we should investigate GLOG

Does GLOG allow collecting log messages in a buffer, so that the program could decide either to reset the buffer or flush it to the output stream? This is the main feature I needed here to avoid getting an enormous amount of debug-log messages due to the many successful test iterations that aren't relevant to the repro.

**Comment by rtpsw** [comment]
@wjones127, looks like your approval is needed too.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 9 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:819]: Note that there are a [couple](https://github.com/apache/arrow/pull/34392/commits/85328512f4899ca92ce5404f442036f54d6ab3ee#diff-5493b6ae7ea2a4d5cfb581034c076e9c4be7608382168de6d1301ef67b6c01eeR1331) of [examples](https://github.com/apache/arrow/pull/34392/commits/85328512f4899ca92ce5404f442036f54d6ab3ee#diff-5493b6ae7ea2a4d5cfb581034c076e9c4be7608382168de6d1301ef67b6c01eeR1681) where `std::endl` is used in the middle of a message, so `DEBUG_MANIP` would be useful even if we had `DEBUG_SYNC_LINE`.

**Comment by icexelloss** [comment]
@rtpsw Sorry I didn't get a chance to look yet. I will do a review before merging this.

**Comment by pitrou** [comment]
@rtpsw Can you rebase from git main?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 10]
```diff
@@ -370,13 +496,18 @@ class KeyHasher {
...
     }
-    batch_ = batch;
+    DEBUG_SYNC(*node_, "key hasher ", index_, " got hashes ",
+               compute::internal::GenericToString(hashes_), DEBUG_MANIP(std::endl));
+    batch_ = batch;  // associate cache with current batch
     return hashes_;
   }
 
  private:
+  AsofJoinNode* node_ = nullptr;  // avoids circular dependency during initialization
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:509]: Are `node_` and `index_` for debug purpose only?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 11]
```diff
@@ -505,29 +636,31 @@ class InputState {
...
       size_t index, TolType tolerance, bool must_hash, bool may_rehash,
-      KeyHasher* key_hasher, ExecNode* node, ExecNode* output,
+      KeyHasher* key_hasher, AsofJoinNode& node, ExecNode* output,
       std::atomic<int32_t>& backpressure_counter,
       const std::shared_ptr<arrow::Schema>& schema, const col_index_t time_col_index,
       const std::vector<col_index_t>& key_col_index) {
     constexpr size_t low_threshold = 4, high_threshold = 8;
     std::unique_ptr<BackpressureControl> backpressure_control =
-        std::make_unique<BackpressureController>(node, output, backpressure_counter);
+        std::make_unique<BackpressureController>(&node, output, backpressure_counter);
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:658]: Why change from pointer to reference?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 12]
```diff
@@ -569,7 +702,7 @@ class InputState {
   // returns the latest time (which is current); otherwise, returns the current time.
   // used when checking whether RHS is up to date with LHS.
   OnType GetCurrentTime() const {
-    return memo_.no_future_ ? GetLatestTime() : memo_.current_time_;
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:572]: Why this change?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 13]
```diff
@@ -688,14 +825,19 @@ class InputState {
 
     // Not updated.  Try to update and possibly advance.
     bool advanced, updated = false;
+    OnType latest_time;
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:828]: Why this change?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 14]
```diff
@@ -704,21 +846,27 @@ class InputState {
         Rehash();
       }
       memo_.Store(ts, rb, latest_ref_row_, latest_time, GetLatestKey());
+      // negative tolerance means a last-known entry was stored - set `updated` to `true`
       updated = memo_.no_future_;
       ARROW_ASSIGN_OR_RAISE(advanced, Advance());
     } while (advanced);
-    if (!memo_.no_future_) {  // "updated" was not modified in the loop; set it here
+    if (!memo_.no_future_ && latest_time >= ts) {
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:853]: Why this change?

**Comment by rtpsw** [comment]
Looks like, somehow, a clean local rebase is no guarantee for a clean rebase after pushing. I'll try to get this in order.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 11 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:660]: IIRC, this just signals `node` can be modified.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 12 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:572]: Because `memo_current_time_` has changed to an `std::atomic`, for which the cast extracts its value.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 13 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:830]: This just exposes `latest_time` outside the loop, for code just after it. Its type is unchanged.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 14 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:855]: This is where the exposed `latest_time` is used. If `latest_time` is less than `ts` then we know upfront that `updated = memo_.RemoveEntriesWithLesserTime(ts);` would have no effect, since all entries would have time no greater than `latest_time` and hence less than `ts`.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 11 above)
Comment (icexelloss) [reply cpp/src/arrow/acero/asof_join_node.cc:660]: Seem - I don't see other places that using a reference to indicate that a object can be modified. Is this done in other places?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 15]
```diff
@@ -1059,7 +1232,7 @@ class AsofJoinNode : public ExecNode {
         // If RHS is finished, then we know it's up to date
         if (rhs.CurrentEmpty())
           return false;  // RHS isn't finished, but is empty --> not up to date
-        if (lhs_ts >= rhs.GetCurrentTime())
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:1062]: Why this change?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 16]
```diff
@@ -821,7 +977,8 @@ struct CompositeReferenceRow {
 template <size_t MAX_TABLES>
 class CompositeReferenceTable {
  public:
-  explicit CompositeReferenceTable(size_t n_tables) : n_tables_(n_tables) {
+  CompositeReferenceTable(AsofJoinNode& node, size_t n_tables)
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:980]: Is the node used just for debugging here?

**Comment by rtpsw** [comment]
The [CI job failure](https://github.com/apache/arrow/actions/runs/4995144796/jobs/8946652030?pr=34392) is due to not finding `options_internal.h` in a debug-build (since this header is not used in a release-build). Why is this so? Is it because it only has access to public headers? and is this expected? If so, I guess I'll need to move the code in `options_internal.h` into `options.h`.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 15 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:1062]: IIRC, this fix was needed after the `MemoStore` changes for a future as-of-join. A more detailed answer would take some investigation.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 16 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:980]: Yes, debugging requires the context of a node, to which the debug-opts are associated.

Comment (icexelloss) [reply cpp/src/arrow/acero/asof_join_node.cc:977]: Can we wrap the node (and other debug variable used for debugging) in a DebugContext object so that it is clear what are these used for here?

Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:977]: I don't think a `DebugContext` is needed here. Only the node is needed because its debug-options provide the debug-variables (stream and mutex) and its address is included in the debug-message. I could add some inline comments, if that would help.

Comment (icexelloss) [reply cpp/src/arrow/acero/asof_join_node.cc:980]: I do think a `DebugContext` (or maybe some other name) that contains the needed variable here (the pointer to the AsofJoinNode or other information) make the code more clear and readable. Otherwise, for every class function that takes a AsofJoinNode, the reader needs to think about "Is the node needed here just for debug or for something else".

If there is already other debug related stuff such as stream and mutex, can we create one class to contain all debug related stuff?

Comment (icexelloss) [reply cpp/src/arrow/acero/asof_join_node.cc:980]: Actually DebugOptions looks like it needs to be passed from the caller. We can do sth like
```
struct DebugContext {
    // Need information from the node class for debugging message
    AsofJoinNode* node;
}
```

And pass that object

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 17]
```diff
@@ -248,15 +354,28 @@ struct MemoStore {
   std::deque<OnType> times_;
 
   void swap(MemoStore& memo) {
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:356]: What does this method do?

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 16 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:980]: Would it serve the purpose to add a `typedef AsofJoinNode DebugNode` and use `DebugNode` where needed?

Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc]: The [recent commit](https://github.com/apache/arrow/pull/34392/commits/e418422b6d025c1093bf49510f42c3a568dab78b) makes debug-arguments clear not only at declarations but also at call-sites.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 18]
```diff
@@ -782,6 +941,10 @@ class InputState {
   std::vector<Type::type> key_type_id_;
   // Hasher for key elements
   mutable KeyHasher* key_hasher_;
+  // Owning node
+  AsofJoinNode& node_;
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node.cc:945]: We want to avoid mutable references, as per the C++ style guide. References should be const, otherwise use a pointer to make it clear at the call site that the argument may be mutated.
```suggestion
  AsofJoinNode* node_;
```

**Comment by rtpsw** [comment]
> There's `arrow/util/mutex.h` specifically for this. However, we should generally strive to keep the amount of implementation code in public headers under control. The heavier public headers are, the longer the compile times.

Thanks, this is useful to know. I already avoided this include, so we're good here.

**Comment by rtpsw** [comment]
The current CI job failures don't appear to be related.

File: cpp/src/arrow/acero/options.h [hunk 19]
```diff
@@ -52,13 +52,21 @@ class Executor;
...
 
 /// \addtogroup execnode-options
 /// @{
 class ARROW_ACERO_EXPORT ExecNodeOptions {
  public:
   virtual ~ExecNodeOptions() = default;
+
+#ifndef NDEBUG
+  std::shared_ptr<DebugOptions> debug_opts;
+#endif
```
Comment (pitrou) [inline cpp/src/arrow/acero/options.h:69]: This makes the ABI depend on `NDEBUG`, which should really be avoided. Some people do use non-debug versions of Arrow in debug builds of their code (and potentially vice-versa, though of course much less common).

File: cpp/src/arrow/acero/asof_join_node_test.cc (hunk 5 above)
Comment (pitrou) [reply cpp/src/arrow/acero/asof_join_node_test.cc:468]: This discussion can (should?) be revisited once the `NDEBUG` API dependency is fixed.

File: cpp/src/arrow/acero/options.h (hunk 19 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/options.h:69]: I'm not sure how to solve this nicely. Could you make a suggestion? Not-so-nice solutions I see are:
1. Change to a `std::shared_ptr<void*>`.
2. Expose `DebugOptions` in release-mode too (but not use it).

Comment (pitrou) [reply cpp/src/arrow/acero/options.h:69]: Given I don't understand what `DebugOptions`, it's hard to answer. But I would question why `DebugOptions` would not be used in release mode. What is the use case?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 20]
```diff
@@ -821,7 +984,8 @@ struct CompositeReferenceRow {
 template <size_t MAX_TABLES>
 class CompositeReferenceTable {
  public:
-  explicit CompositeReferenceTable(size_t n_tables) : n_tables_(n_tables) {
+  NDEBUG_EXPLICIT CompositeReferenceTable(DEBUG_ADD(size_t n_tables, AsofJoinNode& node))
```
[the remark this answers is not in the document]
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc]: Done.

File: cpp/src/arrow/acero/options.h (hunk 19 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/options.h]: `DebugOptions` holds a debug-stream and a debug-mutex for it that are only used in debug-mode for collecting debug-messages specific to a node. With the [recent commit](https://github.com/apache/arrow/pull/34392/commits/275092cce3420fca67cbd9f58c3c7b5a9c9758e8), `DebugOptions` is an empty struct in release-mode, and the ABI is consistent in both modes because `DebugOptions` is only exposed by pointer/reference.

Comment (rtpsw) [reply cpp/src/arrow/acero/options.h]: > But I wonder why debug options would be ignored in release mode.

This can be discussed as part of the follow-up issue #35507

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 21]
```diff
@@ -239,24 +344,45 @@ struct MemoStore {
...
+#endif
     std::swap(no_future_, memo.no_future_);
-    std::swap(current_time_, memo.current_time_);
+    current_time_ = memo.current_time_.exchange(static_cast<OnType>(current_time_));
     entries_.swap(memo.entries_);
     future_entries_.swap(memo.future_entries_);
     times_.swap(memo.times_);
   }
 
+  bool UpdateTime(OnType ts) {
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node.cc:373]: What does it return? Should add a comment explaning this API.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 22]
```diff
@@ -239,24 +344,45 @@ struct MemoStore {
...
+    OnType prev_time = current_time_;
+    bool update = prev_time < ts;
+    while (prev_time < ts && current_time_.compare_exchange_weak(prev_time, ts)) {
+      // intentionally empty - standard CAS loop
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node.cc:377]: I'm not sure I understand. A standard CAS loop would retry when the CAS operation fails, right? Here, it retries when the CAS succeeds...

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 23]
```diff
@@ -268,11 +397,18 @@ struct MemoStore {
...
+    // future times are maintained, then only one time is maintained, and hence it is
+    // overwritten with the given time. Otherwise, the given time must be no less than the
+    // latest time, due to time ordering, so it is pushed back only if it is distinct.
+    if (times_.empty() || (!no_future_ && times_.back() != time)) {
       times_.push_back(time);
     } else {
-      times_.front() = time;
+      times_.back() = time;
     }
+    current_time_ = time;
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node.cc:411]: I'm curious, why don't we use `UpdateTime` here? Also, it looks like the `for_time` argument is unused?

Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:412]: > I'm curious, why don't we use `UpdateTime` here?

This is because the `time` argument to `MemoStore::Store` here is always the most advanced seen by the `MemoStore` instance - I'll add a doc of this. Using `UpdateTime(time)` won't harm but could lead one to think that it might fail to update, which isn't the case.

> Also, it looks like the for_time argument is unused?

It's used just in the debug-message. I'll make this explicit using `DEBUG_ADD`.

**Review by pitrou — APPROVED** [review]
Thanks for the update @rtpsw ! I can't vouch for the correctness but this PR looks formally fine to me.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 15 above)
Comment (icexelloss) [reply cpp/src/arrow/acero/asof_join_node.cc:1062]: Yes I think we should understand why this change is needed. This looks like something subtle and can introduce tricky bugs.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 14 above)
Comment (icexelloss) [reply cpp/src/arrow/acero/asof_join_node.cc:872]: Can you please add comments in the code to explain this. Looks like something could tricky to understand just from the code.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 24]
```diff
@@ -239,24 +344,48 @@ struct MemoStore {
   // the time of the current entry, defaulting to 0.
   // when entries with a time less than T are removed, the current time is updated to the
   // time of the next (by-time) and now-current entry or to T if no such entry exists.
-  OnType current_time_;
+  std::atomic<OnType> current_time_;
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:347]: Can you explain why do we change this to atomic.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 25]
```diff
@@ -731,7 +898,9 @@ class InputState {
 
   Status Push(const std::shared_ptr<arrow::RecordBatch>& rb) {
     if (rb->num_rows() > 0) {
-      queue_.Push(rb);
+      key_hasher_->Invalidate();  // batch changed - invalidate key hasher's cache
+      memo_.UpdateTime(GetTime(rb.get(), 0));  // time changed - update in MemoStore
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:902]: Can you explain why do we add the UpdateTime here. How was memostore time updated before?

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 26]
```diff
@@ -856,10 +1030,23 @@ class CompositeReferenceTable {
...
     // Get the state for that key from all on the RHS -- assumes it's up to date
     // (the RHS state comes from the memoized row references)
     for (size_t i = 1; i < in.size(); ++i) {
       std::optional<const MemoStore::Entry*> opt_entry = in[i]->GetMemoEntryForKey(key);
+#ifndef NDEBUG
+      {
+        bool has_entry = opt_entry.has_value();
+        OnType entry_time = has_entry ? (*opt_entry)->time : TolType::kMinValue;
+        row_index_t entry_row = has_entry ? (*opt_entry)->row : 0;
+        bool accepted = has_entry && tolerance.Accepts(lhs_latest_time, entry_time);
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:1045]: What does "accepted" mean here

**Review by icexelloss — COMMENTED** [review]
@rtpsw Unfortunately this is merged before I had the chance to properly review this. Can you take a look at the comments and create a follow up PR if needed,

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 15 above)
Comment (pitrou) [reply cpp/src/arrow/acero/asof_join_node.cc:1062]: Docstring says "Returns false if RHS not up to date for LHS". This implies that only strict inequality should return false, no?

**Comment by rtpsw** [comment]
> @rtpsw Unfortunately this is merged before I had the chance to properly review this. Can you take a look at the comments and create a follow up PR if needed,

Sorry about that. Would adding comments as part of #35838 work? I intend to handle this issue soon.

**Comment by pitrou** [comment]
Sorry for merging early. If @icexelloss 's comments can be addressed as part of a standalone PR, to ease reviewing, it would be nice.

**Comment by rtpsw** [comment]
> Can you please add comments in the code to explain this. Looks like something could tricky to understand just from the code.

Will do. In the meantime, I'll note that we do not remove entries earlier than a time `ts` when it is not in the past of `latest_time`, which is the case when `latest_time >= ts` is false; otherwise, we would be removing entries before processing them.

**Comment by icexelloss** [comment]
No worries! Can open a follow up PR to address the remaining issues.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 24 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:347]: This is related to your [other question here](https://github.com/apache/arrow/pull/34392#discussion_r1211622318). There, we need to set the current time on the `MemoStore` instance given a new batch, and this is done from a different thread (the one handling an incoming input batch) than the one processing the batch (the one running `ProcessThread`) using the same `MemoStore` instance. This means we need to synchronize `MemoStore.current_time_` between these threads, and so it is made atomic here.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 25 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:902]: See [this post](https://github.com/apache/arrow/pull/34392#discussion_r1211671161). `UpdateTime` is synchronized, and before we didn't need this synchronization.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 26 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:1045]: Here, `accepted` is in the same sense of `tolerance.Accepts`, meaning that the entry's time must (exist and) be within the [time interval defined by the tolerance](https://github.com/apache/arrow/blob/dcdeab76b4ba4bac0b4115925c820961ef70ae0d/cpp/src/arrow/acero/asof_join_node.cc#L111) for `lhs_latest_time`.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 15 above)
Comment (icexelloss) [reply cpp/src/arrow/acero/asof_join_node.cc:1062]: > Docstring says "Returns false if RHS not up to date for LHS". This implies that only strict inequality should return false, no?

I am not sure if that is correct and am hoping for more detailed reason than "IIRC, this fix was needed after the MemoStore changes for a future as-of-join."

Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:1062]: I looked into this to some degree. When '>=' is used instead, as-of-join hangs for the `Basic7Forward` test-case, because both right tables have distant times (right at the beginning) and none of them advances.

I tend to think that '>=' here won't work in general. Consider the case where the left table is at time `t` and a given right table has multiple rows with time `t`. In a past-join, we'd want to advance the right table past `t` and overwrite the stored entry up to the last row with time `t`, which would be ready for joining. In a future-join, we'd want to advance the same way but to store all rows except the first as future entries. Now, consider the case where the given right table has a row with a distant time `t+tolerance+1`. In a future-join, we'd want to advance the right table to this row and store it but only make it current when it is no longer distant. So, in a clearer (if not fixing) solution, I suspect the tolerance horizon needs to be accounted for in the condition here as well as in the storing/joining.

This needs further looking into in a separate issue.

**Review by westonpace — COMMENTED** [review]
This works but I find it a little confusing.  It seems strange to me that the delaying node would be placed after the asof join node.  I was thinking it would be placed on the slow input to ensure that it did not deliver any batches.

However, if you were to do that, the entire plan would hang.  This is because the delaying node synchronously blocks.  This means the CPU thread is taken out of use.  When `use_threads=false` (as it is when we use the asof join node) then that means the only working thread is blocked.

The reason it works today is because the delay happens after the asof join node and so it is actually blocking the processing thread and not a CPU thread.  It was surprising to me that the processing thread was the thread that called InputReceived.  This means, if you have something like...

Source -> AsofJoinNode -> Project -> Aggregation

Then the processing thread will be the one calling `Project` and `Aggregation` which is odd.  However, this issue isn't very relevant to the backpressure problem at hand.

So it seems this works because there is enough data initially delivered to release at least one batch.  This batch gets caught in the delayed node which hangs the processing thread.  Since the processing thread is hung then enough data accumulates in the inputs that it will eventually pause the inputs.

If we want to proceed with this design then I think that is ok.  For the sake of completeness I am including an example of what I had in my mind.  A "GatedNode" would not block but it would not emit any batches (they would just queue up in the scheduler) until the gate is unlocked.

So, with this idea, the gated node would be placed over the slow source.  You could get rid of the entire idea of "delayed" sources (and all the accompanying sleeps).  The plan would be started and we wait to ensure backpressure is hit.  Once backpressure is hit we release the gate and then confirm that the plan resumes and finishes.

Feel free to take my idea or continue with this one.

**Comment by westonpace** [comment]
Ignore that, put this review on the wrong PR.
