### PR TITLE
GH-36771: [R] stringr helper functions drop calling environment when evaluating

### LINKED ISSUE #36771: [R] stringr helper functions drop calling environment when evaluating
### Describe the bug, including details regarding any error messages, version, and platform.

I noticed when reviewing #36720 that we drop the calling environment when evaluating stringr modifier functions. This means potentially unexpected behaviour if one of the arguments is a symbol or function call.

https://github.com/apache/arrow/blob/be2014a9ebfb9570b016a5f0beda11022ace45d1/r/R/dplyr-funcs-string.R#L65

In practice it probably hasn't come up because (1) these arguments are usually literals and not defined by a variable and (2) if they are defined by a variable, that variable is probably in the global environment. The example below fails because `int32` is a name in the arrow package namespace.

``` r
library(arrow, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(stringr)

int32 <- "123"

tibble(x = "abc123") |> 
  filter(str_detect(x, regex(int32)))
#> # A tibble: 1 × 1
#>   x     
#>   <chr> 
#> 1 abc123

arrow_table(x = "abc123") |> 
  filter(str_detect(x, regex(int32)))
#> Warning: Expression str_detect(x, regex(int32)) not supported in Arrow; pulling
#> data into R
#> # A tibble: 1 × 1
#>   x     
#>   <chr> 
#> 1 abc123

arrow_table(x = "abc123") |> 
  filter(str_detect(x, regex("123")))
#> Table (query)
#> x: string
#> 
#> * Filter: match_substring_regex(x, {pattern="123", ignore_case=false})
#> See $.data for the source Arrow object
```

<sup>Created on 2023-07-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The solution is to use `eval_tidy()` with a data mask instead of `eval()`.

### Component(s)

R

### PR DESCRIPTION
**Pull request by thisisnic**
### What changes are included in this PR?

Update internals of `get_stringr_pattern_options()` to use `eval_tidy()` instead of `eval()` to ensure we're evaluating things in the right environment.

### Are these changes tested?

Yes

### Are there any user-facing changes?

Yes
* Closes: #36771

### CODE REVIEW

File: r/R/dplyr-funcs-string.R [hunk 1]
```diff
@@ -57,12 +57,14 @@ get_stringr_pattern_options <- function(pattern) {
...
   ensure_opts <- function(opts) {
+
     if (is.character(opts)) {
       opts <- list(pattern = opts, fixed = FALSE, ignore_case = FALSE)
     }
     opts
   }
-  ensure_opts(eval(pattern))
+
+    ensure_opts(eval_tidy(pattern, env = new_environment(as.list(rlang::current_env()), parent = caller_env())))
```
Comment (paleolimbot) [inline r/R/dplyr-funcs-string.R:67]: Here, I believe `pattern` is `quote()`d expression (created using `enexpr()` in one or more functions that call this one). The environment that is required is the calling environment of `str_xxxx()` (i.e., what `rlang::caller_env()` would return if it was called directly from `str_xxxx()`). Rather than keep track of that environment ourselves, I *think* we can use rlang's "quosure" (which is an expression AND and environment) by:

- Instead of `enexpr()` use `enquo()`
- Instead of `eval()` use `eval_tidy(pattern, mask = list(regex = regex, coll = coll, boundary = boundary))`

The alternative would be to add an `envir` argument to `get_stringr_pattern_options()` and any function that calls it. Given that the documentation for `enexpr()` warns not to use it for this exact reason, I think the `enquo()`/`eval_tidy()` solution is probably best.

Comment (thisisnic) [reply r/R/dplyr-funcs-string.R]: Thanks!

**Comment by thisisnic** [comment]
@paleolimbot Reckon this is ready to merge now?

**Review by paleolimbot — APPROVED** [review]
Very clean! Thank you!
