### PR TITLE
GH-36889: [C++][Python] Fix duplicate CSV header when first batch is empty

### LINKED ISSUE #36889: Duplicate csv header when table batches start with empty
### Describe the bug, including details regarding any error messages, version, and platform.

`pyarrow.csv.write_csv` works as expected, but when the first record batch in a table is empty, it writes two headers (on 2 different lines) instead of one:

```python
import pyarrow.csv
import pyarrow as pa
import io

table = pa.table({"col1": ["a", "b", "c"]})

with io.BytesIO() as fp:
    pyarrow.csv.write_csv(table, fp)
    fp.seek(0)
    assert fp.read() == b'"col1"\n"a"\n"b"\n"c"\n'

with io.BytesIO() as fp:
    pyarrow.csv.write_csv(pa.concat_tables([table.schema.empty_table(), table]), fp)
    fp.seek(0)
    # THIS IS WRONG:
    assert fp.read() == b'"col1"\n"col1"\n"a"\n"b"\n"c"\n'

```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by rynewang**
### Rationale for this change

Fixes https://github.com/apache/arrow/issues/36889

When writing CSV from a table where the first batch is empty, the header gets written twice:

```python
table = pa.table({"col1": ["a", "b", "c"]})
combined = pa.concat_tables([table.schema.empty_table(), table])
write_csv(combined, buf)
# Result: "col1"\n"col1"\n"a"\n"b"\n"c"\n  <-- header appears twice
```

### What changes are included in this PR?

The bug happens because:
1. Header is written to `data_buffer_` and flushed during `CSVWriterImpl` initialization
2. The buffer is not cleared after flush
3. When the next batch is empty, `TranslateMinimalBatch` returns early without modifying `data_buffer_`
4. The write loop then writes `data_buffer_` which still contains stale content

The fix introduces a `WriteAndClearBuffer()` helper that writes the buffer to sink and clears it. This helper is used in all write paths:
- `WriteHeader()`
- `WriteRecordBatch()`
- `WriteTable()`

This ensures the buffer is always clean after any flush, making it impossible for stale content to be written again.

### Are these changes tested?

Yes. Added C++ tests in `writer_test.cc` and Python tests in `test_csv.py`:
- Empty batch at start of table
- Empty batch in middle of table

### Are there any user-facing changes?

No API changes. This is a bug fix that prevents duplicate headers when writing CSV from tables with empty batches.

* GitHub Issue: #36889

### CODE REVIEW

**Comment by rynewang** [comment]
@wgtmac Hi would you mind to also review this? Thanks!

**Review by HuaHuaY — APPROVED** [review]

**Comment by HuaHuaY** [comment]
I think we can clear `data_buffer_` at last line of `writeHeader`. Relying on the `Resize` operation in `TranslateMinimalBatch` to perform implicit clear operation is not very readable.

**Comment by rynewang** [comment]
Clearing after `writeHeader` is a great idea! However it's not complete and failed my unit tests because there are other Write* methods. Now, I made a helper function and let all Write* to do "write to sink and clear buffer". @HuaHuaY can you help pointing this to a maintainer for approval? Thanks!

**Comment by HuaHuaY** [comment]
cc @pitrou @wgtmac . Please take a look.

File: cpp/src/arrow/csv/writer_test.cc [hunk 1]
```diff
@@ -405,5 +406,46 @@ INSTANTIATE_TEST_SUITE_P(
...
+  ASSERT_OK_AND_ASSIGN(auto combined_table,
+                       ConcatenateTables({table1, empty_table, table2}));
+
+  ASSERT_OK_AND_ASSIGN(auto out, io::BufferOutputStream::Create());
+  ASSERT_OK(WriteCSV(*combined_table, WriteOptions::Defaults(), out.get()));
+  ASSERT_OK_AND_ASSIGN(auto buffer, out->Finish());
+
+  std::string result(reinterpret_cast<const char*>(buffer->data()), buffer->size());
+  EXPECT_EQ(result, "\"col1\"\n\"a\"\n\"b\"\n");
+}
```
Comment (wgtmac) [inline cpp/src/arrow/csv/writer_test.cc]:
```suggestion
TEST(TestWriteCSV, EmptyBatchShouldNotPolluteOutput) {
  auto schema = arrow::schema({field("col1", utf8())});
  auto empty_batch = RecordBatchFromJSON(schema, "[]");
  auto batch_a = RecordBatchFromJSON(schema, R"([{"col1": "a"}])");
  auto batch_b = RecordBatchFromJSON(schema, R"([{"col1": "b"}])");

  struct TestParam {
    std::shared_ptr<Table> table;
    std::string expected_output;
  };

  std::vector<TestParam> test_params = {
      // Empty batch in the beginning
      {Table::FromRecordBatches(schema, {empty_batch, batch_a, batch_b}).ValueOrDie(),
       "\"col1\"\n\"a\"\n\"b\"\n"},
      // Empty batch in the middle
      {Table::FromRecordBatches(schema, {batch_a, empty_batch, batch_b}).ValueOrDie(),
       "\"col1\"\n\"a\"\n\"b\"\n"},
      // Empty batch in the end
      {Table::FromRecordBatches(schema, {batch_a, batch_b, empty_batch}).ValueOrDie(),
       "\"col1\"\n\"a\"\n\"b\"\n"},
  };

  for (const auto& param : test_params) {
    ASSERT_OK_AND_ASSIGN(auto out, io::BufferOutputStream::Create());
    ASSERT_OK(WriteCSV(*param.table, WriteOptions::Defaults(), out.get()));
    ASSERT_OK_AND_ASSIGN(auto buffer, out->Finish());
    EXPECT_EQ(buffer->ToString(), param.expected_output);
  }
}
```

These two cases are so similar so I'd recommend to combine them with different params like the above.

File: python/pyarrow/tests/test_csv.py [hunk 2]
```diff
@@ -2065,3 +2065,36 @@ def readinto(self, *args):
     for i in range(20):
         with pytest.raises(pa.ArrowInvalid):
             read_csv(MyBytesIO(data))
+
+
+def test_write_csv_empty_batch_no_duplicate_header():
```
Comment (wgtmac) [inline python/pyarrow/tests/test_csv.py]: Not an expert in pyarrow but I'd recommend to consolidate similar cases.

File: cpp/src/arrow/csv/writer.cc [hunk 3]
```diff
@@ -590,6 +590,13 @@ class CSVWriterImpl : public ipc::RecordBatchWriter {
     return Status::OK();
   }
 
+  // GH-36889: Write buffer to sink and clear it to avoid stale content
+  // being written again if the next batch is empty.
+  Status WriteAndClearBuffer() {
```
Comment (wgtmac) [inline cpp/src/arrow/csv/writer.cc]: nit: perhaps renaming to `FlushToSink` which is shorter and has the implication that the internal buffer is flushed and cleared.

Comment (rynewang) [reply cpp/src/arrow/csv/writer.cc]: done

File: python/pyarrow/tests/test_csv.py (hunk 2 above)
Comment (rynewang) [reply python/pyarrow/tests/test_csv.py]: done

**Review by wgtmac — APPROVED** [review]
Thanks for the update! This looks good to me now.

@pitrou Do you want to take a look at it?

**Comment by wgtmac** [comment]
Thanks @rynewang for fixing this and @HuaHuaY for the review!
