### PR TITLE
GH-38624: [C++] Fix: add TestingEqualOptions for gtest functions.

### LINKED ISSUE #38624: [C++] During unit testing, the float array contains nan equality judgment
### Describe the bug, including details regarding any error messages, version, and platform.

The default array options now have a nan comparison of false, but in a unit test situation we might expect nan=true.
for example:

```
  auto schema = ::arrow::schema({
      {field("a", float32())},
      {field("b", float64())},
  });

  std::vector<std::string> expected = {R"([{"a": 1,    "b": 5},
                                           {"a": 1,    "b": 3},
                                           {"a": 3,    "b": null},
                                           {"a": NaN,  "b": 5},
                                           {"a": NaN,  "b": NaN},
                                           {"a": NaN,   "b": null},
                                           {"a": null, "b": 5},
                                           {"a": null, "b": null}
                                          ])"};
  std::vector<std::string> actual = {R"([{"a": 1,    "b": 5},
                                         {"a": 1,    "b": 3},
                                         {"a": 3,    "b": null},
                                         {"a": NaN,  "b": 5},
                                         {"a": NaN,  "b": NaN},
                                         {"a": NaN,   "b": null},
                                         {"a": null, "b": 5},
                                         {"a": null, "b": null}
                                        ])"};
  ASSERT_TABLES_EQUAL(*TableFromJSON(schema, expected), *TableFromJSON(schema, actual));
```

Now the test will fail.

The reasons were found to be as follows:

```
  bool Equals(const Array& arr, const EqualOptions& = EqualOptions::Defaults()) const;
  bool Equals(const std::shared_ptr<Array>& arr,
              const EqualOptions& = EqualOptions::Defaults()) const;
```

So how can I modify the interface to support this function?

since ASSERT_TABLES_EQUAL will invoke ChunkedArray::ApproxEquals funciton.There is no way to pass options here

```
  return internal::ApplyBinaryChunked(
             *this, other,
             [&](const Array& left_piece, const Array& right_piece,
                 int64_t ARROW_ARG_UNUSED(position)) {
               if (!left_piece.ApproxEquals(right_piece, equal_options)) {
                 return Status::Invalid("Unequal piece");
               }
               return Status::OK();
             })
      .ok();
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by Light-City**
### Rationale for this change

some other interfaces lack equal options, suck as nan equal, so we add TestingEqualOptions for each function and add some testing.

### What changes are included in this PR?

gtest_util related.

### Are these changes tested?

gtest_util.cc

### Are there any user-facing changes?
yes.
* Closes: #38624

### CODE REVIEW

**Comment by Light-City** [comment]
@mapleFU @js8544 here, add TestingEqualOptions to fix previous issue

File: cpp/src/arrow/testing/gtest_util.h [hunk 1]
```diff
@@ -221,18 +221,22 @@ ARROW_TESTING_EXPORT void AssertScalarsEqual(
...
-ARROW_TESTING_EXPORT void AssertBatchesEqual(const RecordBatch& expected,
-                                             const RecordBatch& actual,
-                                             bool check_metadata = false);
-ARROW_TESTING_EXPORT void AssertBatchesApproxEqual(const RecordBatch& expected,
-                                                   const RecordBatch& actual);
-ARROW_TESTING_EXPORT void AssertChunkedEqual(const ChunkedArray& expected,
-                                             const ChunkedArray& actual);
-ARROW_TESTING_EXPORT void AssertChunkedEqual(const ChunkedArray& actual,
-                                             const ArrayVector& expected);
+ARROW_TESTING_EXPORT void AssertBatchesEqual(
```
Comment (mapleFU) [inline cpp/src/arrow/testing/gtest_util.h:224]: Would `ASSERT_BATCHES_EQUAL` macro also add an options with 3 arguments?

File: cpp/src/arrow/testing/gtest_util.h [hunk 2]
```diff
@@ -221,18 +221,22 @@ ARROW_TESTING_EXPORT void AssertScalarsEqual(
...
+    const EqualOptions& options = TestingEqualOptions());
+ARROW_TESTING_EXPORT void AssertBatchesApproxEqual(
+    const RecordBatch& expected, const RecordBatch& actual,
+    const EqualOptions& options = TestingEqualOptions());
+ARROW_TESTING_EXPORT void AssertChunkedEqual(
+    const ChunkedArray& expected, const ChunkedArray& actual,
+    const EqualOptions& options = TestingEqualOptions());
+ARROW_TESTING_EXPORT void AssertChunkedEqual(
+    const ChunkedArray& actual, const ArrayVector& expected,
+    const EqualOptions& options = TestingEqualOptions());
```
Comment (mapleFU) [inline cpp/src/arrow/testing/gtest_util.h:235]: Also, so this change the syntax for comparing? (Though this LGTM)

**Review by mapleFU — COMMENTED** [review]
General LGTM!

Also cc @bkietz

File: cpp/src/arrow/testing/gtest_util.h (hunk 1 above)
Comment (Light-City) [reply cpp/src/arrow/testing/gtest_util.h:224]: It should not be necessary. If you want to pass the Options parameter, it is recommended to use the AssertXXX function directly.

File: cpp/src/arrow/testing/gtest_util.h (hunk 2 above)
Comment (Light-City) [reply cpp/src/arrow/testing/gtest_util.h:235]: yes, since AssertTablesEqual will invoke AssertChunkedEqual.

File: cpp/src/arrow/testing/gtest_util.h (hunk 1 above)
Comment (mapleFU) [reply cpp/src/arrow/testing/gtest_util.h:224]: Though I think it should be better to support extra arg in macro, `ASSERT_BATCHES_EQUAL` and other macro is not so widely used, if other thinks it's ok, we can leave them their

Comment (Light-City) [reply cpp/src/arrow/testing/gtest_util.h:224]: If we want to expand, these should all need to be added
```
#define ASSERT_ARRAYS_EQUAL(lhs, rhs) AssertArraysEqual((lhs), (rhs))
#define ASSERT_BATCHES_EQUAL(lhs, rhs) AssertBatchesEqual((lhs), (rhs))
#define ASSERT_BATCHES_APPROX_EQUAL(lhs, rhs) AssertBatchesApproxEqual((lhs), (rhs))
#define ASSERT_TABLES_EQUAL(lhs, rhs) AssertTablesEqual((lhs), (rhs))
```

Comment (mapleFU) [reply cpp/src/arrow/testing/gtest_util.h:224]: Yeah, seems that only json testing uses that, I think it's also ok to leave it here...

**Review by bkietz — CHANGES_REQUESTED** [review]
LGTM, but please fix the formatting

https://github.com/apache/arrow/actions/runs/6810325442/job/18518414647?pr=38642#step:5:915

**Comment by Light-City** [comment]
> LGTM, but please fix the formatting
> 
> https://github.com/apache/arrow/actions/runs/6810325442/job/18518414647?pr=38642#step:5:915

done @bkietz

**Review by bkietz — APPROVED** [review]
