### PR TITLE
GH-33723: [C++] re2::RE2::RE2() result must be checked

### LINKED ISSUE #33723: [C++] re2::RE2::RE2() result must be checked
### Describe the enhancement requested

`re2::RE2::RE2()` may be failed. We should check the `re2::RE2::RE2()` result with `re2::RE2::ok()`.

For example:

```diff
diff --git a/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc b/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc
index d3d0ac3201..b2b9d47c02 100644
--- a/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc
+++ b/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc
@@ -1681,6 +1681,10 @@ struct FindSubstringRegex {
 
   template <typename OutValue, typename... Ignored>
   OutValue Call(KernelContext*, std::string_view val, Status*) const {
+    if (!regex_match_->ok()) {
+      // TODO: Report error
+      return -1;
+    }
     re2::StringPiece piece(val.data(), val.length());
     re2::StringPiece match;
     if (RE2::PartialMatch(piece, *regex_match_, &match)) {
```

Gandiva also doesn't check `re2::RE2::RE2()` result.

If `re2::RE2::RE2()` is failed, a program is crashed like #25633 .

### Component(s)

C++, C++ - Gandiva

### PR DESCRIPTION
**Pull request by js8544**
### Rationale for this change

RE2 construction needs to be checked.

### What changes are included in this PR?

Check all RE2 object status.

### Are these changes tested?

Tested with existing tests.

### Are there any user-facing changes?

No.
* Closes: #33723

### CODE REVIEW

File: cpp/src/arrow/compute/kernels/scalar_string_ascii.cc [hunk 1]
```diff
@@ -1505,6 +1508,13 @@ struct MatchLike {
     static const RE2 kLikePatternIsStartsWith(R"(([^%_]*[^\\%_])?%+)", kRE2Options);
     // A LIKE pattern matching this regex can be translated into a suffix search.
     static const RE2 kLikePatternIsEndsWith(R"(%+([^%_]*))", kRE2Options);
+    static bool global_checked = false;
+    if (ARROW_PREDICT_FALSE(!global_checked)) {
+      RETURN_NOT_OK(RegexStatus(kLikePatternIsSubstringMatch));
+      RETURN_NOT_OK(RegexStatus(kLikePatternIsStartsWith));
+      RETURN_NOT_OK(RegexStatus(kLikePatternIsEndsWith));
+      global_checked = true;
+    }
```
Comment (js8544) [inline cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:1517]: Are there better ways to check global RE2 objects?

File: cpp/src/gandiva/regex_functions_holder.cc [hunk 2]
```diff
@@ -34,27 +31,44 @@ std::string& RemovePatternEscapeChars(const FunctionNode& node, std::string& pat
...
+  static const RE2 is_substr_regex(R"(\.\*([^\.\*])*\.\*)");
+
+  static bool global_checked = false;
+  if (ARROW_PREDICT_FALSE(!global_checked)) {
+    if (ARROW_PREDICT_FALSE(
+            !(starts_with_regex.ok() && ends_with_regex.ok() && is_substr_regex.ok()))) {
+      return node;
+    }
+    global_checked = true;
+  }
```
Comment (js8544) [inline cpp/src/gandiva/regex_functions_holder.cc:49]: Are there better ways to check global RE2 objects?

File: cpp/src/arrow/compute/kernels/scalar_string_ascii.cc [hunk 3]
```diff
@@ -1505,6 +1508,13 @@ struct MatchLike {
     static const RE2 kLikePatternIsStartsWith(R"(([^%_]*[^\\%_])?%+)", kRE2Options);
     // A LIKE pattern matching this regex can be translated into a suffix search.
     static const RE2 kLikePatternIsEndsWith(R"(%+([^%_]*))", kRE2Options);
+    static bool global_checked = false;
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:1511]: Can we use `std::once_flag`?

File: cpp/src/arrow/compute/kernels/scalar_string_ascii.cc [hunk 4]
```diff
@@ -1505,6 +1508,13 @@ struct MatchLike {
...
+    if (ARROW_PREDICT_FALSE(!global_checked)) {
+      RETURN_NOT_OK(RegexStatus(kLikePatternIsSubstringMatch));
+      RETURN_NOT_OK(RegexStatus(kLikePatternIsStartsWith));
+      RETURN_NOT_OK(RegexStatus(kLikePatternIsEndsWith));
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:1515]: If we have an error in these patterns, does this code report an error on the second call? (It seems that this code reports an error only on the first call.)

**Review by kou — COMMENTED** [review]
Could you also add tests for error pattern cases?

File: cpp/src/arrow/compute/kernels/scalar_string_ascii.cc (hunk 3 above)
Comment (js8544) [reply cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:1511]: I thought about using `std::call_once` but the only solution I can come up with uses exceptions:
```cpp
    static std::once_flag global_checked;
    try {
      std::call_once(global_checked, [] {
        auto check_global = [] {
          RETURN_NOT_OK(RegexStatus(kLikePatternIsSubstringMatch));
          RETURN_NOT_OK(RegexStatus(kLikePatternIsStartsWith));
          RETURN_NOT_OK(RegexStatus(kLikePatternIsEndsWith));
        };
        auto status = check_global();
        if (!status.ok()) { // throw an exception so that once_flag is not set
          throw std::invalid_argument(status.ToString());
        }
      });
    } catch (const std::invalid_argument& e) {
      return Status::Invalid(e.what());
    }
```
I couldn't find a more elegant solution. WDYT?

Comment (js8544) [reply cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:1511]: I also feel like a static boolean is enough for our case. As it avoids false positives, i.e., erroneous regexes are always checked.

**Comment by js8544** [comment]
> Could you also add tests for error pattern cases?

Added a TestBaseBinaryKernels: FindSubstringRegexWrongPattern test

File: cpp/src/arrow/compute/kernels/scalar_string_ascii.cc (hunk 3 above)
Comment (kou) [reply cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:1511]: Ah, I see. `std::call_once` isn't suitable here.

File: cpp/src/arrow/compute/kernels/scalar_string_ascii.cc (hunk 4 above)
Comment (kou) [reply cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:1515]: I see. Thanks.

**Review by kou — APPROVED** [review]
+1

File: cpp/src/arrow/compute/kernels/scalar_string_test.cc [hunk 5]
```diff
@@ -19,6 +19,7 @@
 #include <string>
 #include <utility>
 #include <vector>
+#include "arrow/compute/exec.h"
```
Comment (westonpace) [inline cpp/src/arrow/compute/kernels/scalar_string_test.cc:22]: Can you keep the includes grouped together?

File: cpp/src/gandiva/regex_functions_holder.cc [hunk 6]
```diff
@@ -17,15 +17,12 @@
 
 #include "gandiva/regex_functions_holder.h"
 #include <regex>
+#include "arrow/util/macros.h"
```
Comment (westonpace) [inline cpp/src/gandiva/regex_functions_holder.cc:20]: I am not very familiar with the gandiva code base.  Is it ok/normal to use Arrow macros here?  I assume so.

**Review by westonpace — APPROVED** [review]
One minor include nit would be nice to fix.

File: cpp/src/arrow/compute/kernels/scalar_string_test.cc (hunk 5 above)
Comment (js8544) [reply cpp/src/arrow/compute/kernels/scalar_string_test.cc]: done

File: cpp/src/gandiva/regex_functions_holder.cc (hunk 6 above)
Comment (js8544) [reply cpp/src/gandiva/regex_functions_holder.cc:20]: Yep. Gandiva uses various headers in the arrow/util directory.
