### PR TITLE
GH-35838: [C++] Fix asof join backpresure

### LINKED ISSUE #35838: [C++] Backpressure broken in asof join node
### Describe the bug, including details regarding any error messages, version, and platform.

Originally the `InputState` was created with...

```
  static Result<std::unique_ptr<InputState>> Make(
      size_t index, TolType tolerance, bool must_hash, bool may_rehash,
      KeyHasher* key_hasher, ExecNode* node, ExecNode* output,
      std::atomic<int32_t>& backpressure_counter,
      const std::shared_ptr<arrow::Schema>& schema, const col_index_t time_col_index,
      const std::vector<col_index_t>& key_col_index) {
    constexpr size_t low_threshold = 4, high_threshold = 8;
    std::unique_ptr<BackpressureControl> backpressure_control =
        std::make_unique<BackpressureController>(node, output, backpressure_counter);
...

          InputState::Make(i, tolerance_, must_hash_, may_rehash_, key_hashers_[i].get(),
                           inputs[i], this, backpressure_counter_,
                           inputs[i]->output_schema(), indices_of_on_key_[i],
                           indices_of_by_key_[i]));
```

The `BackpressureController` is given `node` (which is `inputs[i]`) and `output` (which is `this`).

After https://github.com/apache/arrow/commit/dcdeab76b4ba4bac0b4115925c820961ef70ae0d the code changed to:

```
  static Result<std::unique_ptr<InputState>> Make(
      size_t index, TolType tolerance, bool must_hash, bool may_rehash,
      KeyHasher* key_hasher, AsofJoinNode* node, ExecNode* output,
      std::atomic<int32_t>& backpressure_counter,
      const std::shared_ptr<arrow::Schema>& schema, const col_index_t time_col_index,
      const std::vector<col_index_t>& key_col_index) {
    constexpr size_t low_threshold = 4, high_threshold = 8;
    std::unique_ptr<BackpressureControl> backpressure_control =
        std::make_unique<BackpressureController>(node, output, backpressure_counter);

...

          InputState::Make(i, tolerance_, must_hash_, may_rehash_, key_hashers_[i].get(),
                           this, inputs[i], backpressure_counter_,
                           inputs[i]->output_schema(), indices_of_on_key_[i],
                           indices_of_by_key_[i]));
```

Note that `BackpressureControl` is now created with `node` (which is `this`) and then `output` (which is `inputs[i]`).  This means, when the asof join node decides to pause it will call `PauseProducing` on `AsofJoinNode` which currently does nothing:

```
  void PauseProducing(ExecNode* output, int32_t counter) override {}
  void ResumeProducing(ExecNode* output, int32_t counter) override {}
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by icexelloss**
### Rationale for this change

To fix a bug in asof join backpresure handling.

### What changes are included in this PR?

This is reverting a bug introduced in GH-34391 on this line that breaks asof join backpresure
https://github.com/apache/arrow/pull/34392/files#diff-5493b6ae7ea2a4d5cfb581034c076e9c4be7608382168de6d1301ef67b6c01eeR1410

### Are these changes tested?
No. However code change simply reverts to the state before the bug was introduced in GH-34391 and therefore should be pretty safe (we have tested that the code before GH-34391 is working). In the meantime @rtpsw is working on adding tests around this but I would like to merge this to unblock internal  issues around this.

### Are there any user-facing changes?

* Closes: #35838

### CODE REVIEW

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 1]
```diff
@@ -1407,7 +1407,7 @@ class AsofJoinNode : public ExecNode {
       ARROW_ASSIGN_OR_RAISE(
           auto input_state,
           InputState::Make(i, tolerance_, must_hash_, may_rehash_, key_hashers_[i].get(),
-                           this, inputs[i], backpressure_counter_,
+                           inputs[i], this, backpressure_counter_,
```
Comment (icexelloss) [inline cpp/src/arrow/acero/asof_join_node.cc:1410]: Simply reverting this line where the bug is introduced:
https://github.com/apache/arrow/pull/34392/files#diff-5493b6ae7ea2a4d5cfb581034c076e9c4be7608382168de6d1301ef67b6c01eeR1410

@rtpsw is working on adding tests but it could take some time.

**Comment by icexelloss** [comment]
cc @westonpace I prefer to merge this to unblock internal issues while @rtpsw  works on adding the test if that is OK

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 1 above)
Comment (rtpsw) [reply cpp/src/arrow/acero/asof_join_node.cc:1410]: Note that I have just added tests in #35874, though this PR can proceed, if so desired.

**Comment by icexelloss** [comment]
@rtpsw In order to get the head into a non buggy state first. I will going to merge this so that @rtpsw can pull this and continue to work on testing + reducing confusion of the variable naming per discussions https://github.com/apache/arrow/pull/35874#discussion_r1213516786

**Comment by westonpace** [comment]
@icexelloss makes sense
