### PR TITLE
GH-39527: [C++][Parquet] Validate page sizes before truncating to int32

### LINKED ISSUE #39527: [C++][Parquet]: Page sizes are not always validated before truncating to int32
### Describe the bug, including details regarding any error messages, version, and platform.

This can lead to writing corrupt data if the pages passed in are too large (for instance LargeString arrow columns that get sliced but still exceed 2GB).

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by emkornfield**
Be defensive instead of writing invalid data.

### Rationale for this change

Users can provide this API pages that are large to validly write and we silently truncate lengths before writing.

### What changes are included in this PR?

Add validations and throw an exception if sizes are too large (this was previously checked only if page indexes are being build).

### Are these changes tested?

Unit tested

### Are there any user-facing changes?

This might start raising exceptions instead of writing out invalid parquet files.

Closes #39527 

**This PR contains a "Critical Fix".** 
* Closes: #39527

### CODE REVIEW

**Review by emkornfield — COMMENTED** [review]
fix includes

File: cpp/src/parquet/column_writer_test.cc [hunk 1]
```diff
@@ -889,6 +891,44 @@ TEST_F(TestByteArrayValuesWriter, CheckDefaultStats) {
   ASSERT_TRUE(this->metadata_is_stats_set());
 }
 
+TEST(TestPageWriter, ThrowsOnPagesToLarge) {
```
Comment (wgtmac) [inline cpp/src/parquet/column_writer_test.cc:894]:
```suggestion
TEST(TestPageWriter, ThrowsOnPagesTooLarge) {
```

File: cpp/src/parquet/column_writer_test.cc [hunk 2]
```diff
@@ -889,6 +891,44 @@ TEST_F(TestByteArrayValuesWriter, CheckDefaultStats) {
...
+      PageWriter::Open(sink, Compression::UNCOMPRESSED,
+                       Codec::UseDefaultCompressionLevel(), metadata.get());
+
+  uint8_t data;
+  std::shared_ptr<Buffer> buffer =
+      std::make_shared<Buffer>(&data, std::numeric_limits<int32_t>::max() + int64_t{1});
+  DataPageV1 over_compressed_limit(buffer, /*num_values=*/100, Encoding::BIT_PACKED,
+                                   Encoding::BIT_PACKED, Encoding::BIT_PACKED,
+                                   /*uncompressed_size=*/100);
+  EXPECT_THROW(pager->WriteDataPage(over_compressed_limit), ParquetException);
```
Comment (mapleFU) [inline cpp/src/parquet/column_writer_test.cc:918]: Should we uses EXPECT_THAT to gurantee "overflows to INT32_MAX"?

File: cpp/src/parquet/column_writer.cc [hunk 3]
```diff
@@ -288,6 +291,9 @@ class SerializedPageWriter : public PageWriter {
     dict_page_header.__set_is_sorted(page.is_sorted());
 
     const uint8_t* output_data_buffer = compressed_data->data();
+    if (compressed_data->size() > std::numeric_limits<int32_t>::max()) {
+      throw ParquetException("Compressed page size overflows to INT32_MAX.");
```
Comment (mapleFU) [inline cpp/src/parquet/column_writer.cc:295]: should we note that the page type?

**Review by mapleFU — COMMENTED** [review]
General LGTM!

File: cpp/src/parquet/column_writer.cc (hunk 3 above)
Comment (mapleFU) [reply cpp/src/parquet/column_writer.cc:295]: ( Also can we print the page size? )

**Comment by mapleFU** [comment]
@emkornfield Could we move forward? I'll approve if comment fixed

**Comment by emkornfield** [comment]
Yes, will try to update this week.

File: cpp/src/parquet/column_writer_test.cc (hunk 2 above)
Comment (emkornfield) [reply cpp/src/parquet/column_writer_test.cc]: done.

File: cpp/src/parquet/column_writer.cc (hunk 3 above)
Comment (emkornfield) [reply cpp/src/parquet/column_writer.cc]: done.

**Comment by emkornfield** [comment]
@mapleFU apologies for the delay, I think I've addressed your feedback.

**Review by mapleFU — APPROVED** [review]
+1

**Comment by mapleFU** [comment]
cc @pitrou @wgtmac

**Review by wgtmac — APPROVED** [review]

File: cpp/src/parquet/column_writer.cc [hunk 4]
```diff
@@ -271,7 +271,12 @@ class SerializedPageWriter : public PageWriter {
   }
 
   int64_t WriteDictionaryPage(const DictionaryPage& page) override {
-    int64_t uncompressed_size = page.size();
+    int64_t uncompressed_size = page.buffer()->size();
+    if (uncompressed_size > std::numeric_limits<int32_t>::max()) {
+      throw ParquetException(
+          "Uncompressed dictionary page size overflows to INT32_MAX. Size:",
```
Comment (pitrou) [inline cpp/src/parquet/column_writer.cc:277]: Grammar is weird here. Would this be better?
```suggestion
          "Uncompressed dictionary page size overflows INT32_MAX. Size:",
```

File: cpp/src/parquet/column_writer.cc [hunk 5]
```diff
@@ -288,6 +293,11 @@ class SerializedPageWriter : public PageWriter {
     dict_page_header.__set_is_sorted(page.is_sorted());
 
     const uint8_t* output_data_buffer = compressed_data->data();
+    if (compressed_data->size() > std::numeric_limits<int32_t>::max()) {
+      throw ParquetException(
```
Comment (pitrou) [inline cpp/src/parquet/column_writer.cc:297]: Same here and below.

Comment (emkornfield) [reply cpp/src/parquet/column_writer.cc:297]: fixed.

File: cpp/src/parquet/column_writer_test.cc [hunk 6]
```diff
@@ -889,6 +895,45 @@ TEST_F(TestByteArrayValuesWriter, CheckDefaultStats) {
...
+  std::shared_ptr<Buffer> buffer =
+      std::make_shared<Buffer>(&data, std::numeric_limits<int32_t>::max() + int64_t{1});
+  DataPageV1 over_compressed_limit(buffer, /*num_values=*/100, Encoding::BIT_PACKED,
+                                   Encoding::BIT_PACKED, Encoding::BIT_PACKED,
+                                   /*uncompressed_size=*/100);
+  EXPECT_THAT([&]() { pager->WriteDataPage(over_compressed_limit); },
+              ThrowsMessage<ParquetException>(HasSubstr("overflows INT32_MAX")));
+  DictionaryPage dictionary_over_compressed_limit(buffer, /*num_values=*/100,
+                                                  Encoding::PLAIN);
+  EXPECT_THROW(pager->WriteDictionaryPage(dictionary_over_compressed_limit),
```
Comment (pitrou) [inline cpp/src/parquet/column_writer_test.cc:925]: Sorry, didn't spot this, but perhaps also use `EXPECT_THAT` to check the exception message here?

**Review by pitrou — APPROVED** [review]
LGTM except for one last suggestion

File: cpp/src/parquet/column_writer_test.cc [hunk 7]
```diff
@@ -889,6 +895,45 @@ TEST_F(TestByteArrayValuesWriter, CheckDefaultStats) {
...
+               ParquetException);
```
Comment (mapleFU) [inline cpp/src/parquet/column_writer_test.cc:926]:
```suggestion
  EXPECT_THAT([&]() { pager->WriteDictionaryPage(dictionary_over_compressed_limit); },
              ThrowsMessage<ParquetException>(HasSubstr("overflows INT32_MAX")));
```

File: cpp/src/parquet/column_writer_test.cc (hunk 6 above)
Comment (mapleFU) [reply cpp/src/parquet/column_writer_test.cc]: I've updated this now
