### PR TITLE
GH-38570: [R] Ensure that test-nix-libs is warning free

### LINKED ISSUE #38570: [R] Ensure that test-nix-libs is warning free
### Describe the enhancement requested

Although we stop / fail the CI job for warnings elsewhere, we don't seem to be doing that for our buildsystem tests. Let's change that so warnings + other output doesn't creep in.

### Component(s)

R

### PR DESCRIPTION
**Pull request by jonkeane**
### Rationale for this change

Although we stop / fail the CI job for warnings elsewhere, we don't seem to be doing that for our buildsystem tests. Let's change that so warnings + other output doesn't creep in.

- [x] Prevent `*** Failed to find latest nightly for 8.0.0.9000` from showing up when the file is sourced under test
- [x] fix `Warning ('test-nixlibs.R:140:3'): select_binary() with test program 'x' is NULL so the result will be NULL`
- [x] update version strings to be characters to avoid r-devel warnings

### What changes are included in this PR?

Added `stop_on_warning` to the test call, and fixes to make that pass

### Are these changes tested?

Yes, they are all part of the test suite 

### Are there any user-facing changes?

No.
* Closes: #38570

### CODE REVIEW

File: r/tools/nixlibs.R [hunk 1]
```diff
@@ -268,7 +272,7 @@ get_macos_openssl_dir <- function() {
       openssl_root_dir <- "/usr/local"
     }
   }
-  return(openssl_root_dir)
+  openssl_root_dir
```
Comment (jonkeane) [inline r/tools/nixlibs.R:275]: This wasn't technically necessary, but I wanted to clean up some of the inconsistencies in this file and follow our general style of no `return` if it's the last value in a function.

File: r/tools/nixlibs.R [hunk 2]
```diff
@@ -828,10 +832,10 @@ quietly <- !env_is("ARROW_R_DEV", "true")
 
 not_cran <- env_is("NOT_CRAN", "true")
 
-if (is_release) {
+if (is_release & !test_mode) {
   VERSION <- VERSION[1, 1:3]
   arrow_repo <- paste0(getOption("arrow.repo", sprintf("https://apache.jfrog.io/artifactory/arrow/r/%s", VERSION)), "/libarrow/")
-} else {
+} else if(!test_mode) {
```
Comment (jonkeane) [inline r/tools/nixlibs.R:838]: We could also wrap this whole block in `if (!test_mode) { ... }` since we don't want to run the actual detection yet, just check the functions. Unless I'm missing something and we actually do want this whole main chunk to run?

**Comment by jonkeane** [comment]
cc @paleolimbot in case this overlaps with anything you're working on

File: r/tools/nixlibs.R (hunk 2 above)
Comment (paleolimbot) [reply r/tools/nixlibs.R:838]: I think we do want the whole main chunk to run (or at least, from spending a few minutes with the script last week it seemed like that was the original intention). Wrapping the main logic in a function and testing that function would be another way to go about it but I don't feel to strongly about it (I'm just glad there's a place to put tests for these functions).

**Review by paleolimbot — COMMENTED** [review]
Thank you for taking this on! I think I'd prefer to keep the existing "run the whole script when in test mode" logic even though it's a little odd (unless @assignUser corrects me and it was never the original intention to run the entire script in the test block).

File: r/tools/nixlibs.R (hunk 2 above)
Comment (jonkeane) [reply r/tools/nixlibs.R:838]: And just to make sure I understand: you're suggesting leaving this as is rather than making the whole block skip while being tested.

We could also suppress the message more deeply (or even in the test script) but IMHO both of those are harder to figure out what's up / reason about than stopping this one bit from running during testing and producing distracting output. But happy to change it to elsewhere if you have strong feelings about it

Comment (paleolimbot) [reply r/tools/nixlibs.R:838]: I think most of the distracting output is fixed in https://github.com/apache/arrow/pull/38534 even with sourcing the script (output here: https://github.com/apache/arrow/actions/runs/6746935491/job/18341961924?pr=38534#step:5:23756 ). Is there any part of that output that could be improved?

Comment (jonkeane) [reply r/tools/nixlibs.R:838]: This bit here is about suppressing this part, which I see in that output:

```
 *** No nightly binaries were found for version 8.0.0.9000: falling back to libarrow build from source
```

**Review by paleolimbot — APPROVED** [review]
I remembered what I was thinking of: the comment `# Prevent error with binary selection during testing.` vs. the comment `# Flag so that we just load the functions and don't evaluate them like we do when called from configure.R`. I'll add a comment in #38534 to clarify that we don't actually want to run selection in the test file! (Or feel free to add here!)

File: r/tools/nixlibs.R (hunk 2 above)
Comment (assignUser) [reply r/tools/nixlibs.R:838]: I also just used the existing pattern so :shrug: I think it should be fine to fix it like this as further up is a block that sets the version specifically for testing and iirc we don't use the arrow repo option in any of the tests (other wise we would also see fails in ci).

**Review by assignUser — APPROVED** [review]
LGTM thanks
