### PR TITLE
GH-41323: [R] Redo how summarize() evaluates expressions

### LINKED ISSUE #29667: [R] Try to arrow_eval user-defined functions
**Proposed approach**:
- Investigate simple injection with `!!`
- Investigate injection with `rlang::inject()`
- Investigate the data mask levels approach
- investigate other (undefined) approaches
  
**Original description**:
The first test passes but the second one fails, even though they're equivalent. The user's function isn't being evaluated in the nse_funcs environment.

```Java

  expect_dplyr_equal(
    input %>%
      select(-fct) %>%
      filter(nchar(padded_strings) < 10) %>%
      collect(),
    tbl
  )
  isShortString <- function(x) nchar(x) < 10
  expect_dplyr_equal(
    input %>%
      select(-fct) %>%
      filter(isShortString(padded_strings)) %>%
      collect(),
    tbl
  )
```

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-14071) / @nealrichardson
**Assignee**: [Dragoș Moldovan-Grünfeld](https://issues.apache.org/jira/browse/ARROW-14071) / @dragosmg
#### Subtasks:
- [X] [[R] Investigate simple injection with !!](https://github.com/apache/arrow/issues/32241)
- [X] [[R] Investigate injection with rlang::inject()](https://github.com/apache/arrow/issues/32242)
- [X] [[R] Investigate the data mask levels approach](https://github.com/apache/arrow/issues/32243)
- [X] [[R] Investigate other (undefined) approaches](https://github.com/apache/arrow/issues/32244)
#### Related issues:
- [[R] Allow unrecognized R expressions to be callable as compute::Functions](https://github.com/apache/arrow/issues/20372) (relates to)
- [[R] arrow_eval user-defined generic functions  ](https://github.com/apache/arrow/issues/33156) (is related to)
#### PRs and other links:
- [GitHub Pull Request #13789](https://github.com/apache/arrow/pull/13789)
- [GitHub Pull Request #13960](https://github.com/apache/arrow/pull/13960)

<sub>**Note**: *This issue was originally created as [ARROW-14071](https://issues.apache.org/jira/browse/ARROW-14071). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #41323: [R] Redo how summarize() evaluates
### Describe the enhancement requested

See discussion on #41223, which solves this.

### Component(s)

R

### PR DESCRIPTION
**Pull request by nealrichardson**
### Rationale for this change

Previously, the NSE expression handling in `summarize()` worked differently from filter/mutate/etc. Among the implications, it would not have been possible to define bindings for other aggregation functions that can be translated into some combination of supported aggregations, such as `weighted.mean()`.  

### What changes are included in this PR?

* Expressions in `summarize()` can now be evaluated with "regular" `arrow_eval()`. Aggregation bindings stick the contents of the aggregation data they previously returned into an `..aggregations` list that lives in an enclosing environment, and then return a FieldRef pointing to that. This makes the code in e.g. `summarize_eval()` a little harder to follow, since it's grabbing and pointing to objects out of its immediate scope, but I've tried to comment thoroughly and am happy to add more.
* `arrow_eval()` inspects the expression it receives for any functions that are not in the NSE mask and not in some other package's namespace (i.e. hopefully just user functions) and inserts them into the NSE mask, setting the enclosing environment for that copy of the function to be the mask, so that if the function calls other functions that we do have bindings for, the bindings get called. This is the approach I suggested back in https://github.com/apache/arrow/issues/29667#issuecomment-1378049226, and it is what fixes #29667 and #40938.

### Are these changes tested?

Existing tests, which are pretty comprehensive, pass. But it would be good to try to be more evil in manual testing with the user-defined R function support.

### Are there any user-facing changes?

Yes.

* GitHub Issue: #41323

### CODE REVIEW

File: r/R/dplyr-eval.R [hunk 1]
```diff
@@ -20,6 +20,8 @@ arrow_eval <- function(expr, mask) {
   # with references to Arrays (if .data is Table/RecordBatch) or Fields (if
   # .data is a Dataset).
 
+  add_user_functions_to_mask(expr, mask)
```
Comment (jonkeane) [inline r/R/dplyr-eval.R:23]: It might be nice to have a comment here explaining what this is — it's right below on line 54, so maybe that's enough, but something quick and descriptive (mostly that this is _not_ UDFs and instead about R funcs in the parent/global environment

Comment (jonkeane) [reply r/R/dplyr-eval.R:23]: And here it might be nice to describe why: we do this because some functions can be reduced to functions that do have arrow bindings without needing to register one yourself or the like

File: r/R/dplyr-eval.R [hunk 2]
```diff
@@ -48,6 +50,43 @@ arrow_eval <- function(expr, mask) {
...
+          }
+          function_env[[i]] <- user_fun
+          # Also set the enclosing environment to be the function environment.
+          # This allows the function to reference other functions in the env.
+          # This may have other undesired side effects?
+          environment(function_env[[i]]) <- function_env
+        }
+      }
+    }
+  }
```
Comment (jonkeane) [inline r/R/dplyr-eval.R:84]: `i` here is the func name as a string, yeah? Maybe it would be clearer to call it `func_name` or simply `func`?

File: r/R/dplyr-eval.R [hunk 3]
```diff
@@ -88,10 +127,14 @@ arrow_mask <- function(.data, aggregation = FALSE) {
   }
 
   if (aggregation) {
+    pf <- parent.frame()
     # This should probably be done with an environment inside an environment
     # but a first attempt at that had scoping problems (ARROW-13499)
     for (f in names(agg_funcs)) {
       f_env[[f]] <- agg_funcs[[f]]
+      # Make sure that ..aggregations and ..post_mutate are in the search path
+      # This assumes being called from summarize
```
Comment (jonkeane) [inline r/R/dplyr-eval.R:136]: Mostly for my own education "This assumes being called from summarize" is because we're in `if (aggregation) {...}` yeah?

File: r/R/dplyr-summarize.R [hunk 4]
```diff
@@ -129,35 +129,71 @@ register_bindings_aggregate <- function() {
...
+
+find_aggregations_env <- function() {
+  # Find the environment where ..aggregations is stored,
+  # it's in parent.env of something in the call stack
+  for (f in sys.frames()) {
+    if (exists("..aggregations", envir = f)) {
+      return(f)
+    }
+  }
+  stop("Could not find ..aggregations")
```
Comment (jonkeane) [inline r/R/dplyr-summarize.R:194]: This should never happen in the normal course of execution, yeah?

File: r/R/dplyr-summarize.R [hunk 5]
```diff
@@ -221,25 +257,27 @@ do_arrow_summarize <- function(.data, ..., .groups = NULL) {
...
-      ctx,
+      mask,
       length(.data$group_by_vars) > 0
     )
   }
 
   # Apply the results to the .data object.
   # First, the aggregations
-  .data$aggregations <- ctx$aggregations
+  .data$aggregations <- ..aggregations
```
Comment (jonkeane) [inline r/R/dplyr-summarize.R:280]: I'm curious to know more about going from the `ctx` object to storing these as `..aggregations`. I'm not at all opposed, and think this looks more natural given some of our other machinery — but can't tell directly here if/why that's necessary

File: r/R/dplyr-summarize.R [hunk 6]
```diff
@@ -254,12 +292,35 @@ do_arrow_summarize <- function(.data, ..., .groups = NULL) {
...
+      # We can tell the expression is invalid if it references fields not in
+      # the schema of the data after summarize(). Evaulating its type will
+      # throw an error if it's invalid.
+      tryCatch(..post_mutate[[post]]$type(out$.data$schema), error = function(e) {
+        msg <- paste(
+          "Expression", as_label(exprs[[post]]),
+          "is not a valid aggregation expression or is"
+        )
+        arrow_not_supported(msg)
+      })
```
Comment (jonkeane) [inline r/R/dplyr-summarize.R:316]: Sneaky!

File: r/tests/testthat/test-dplyr-across.R [hunk 7]
```diff
@@ -279,7 +277,17 @@ test_that("purrr-style lambda functions are supported", {
   )
 })
 
-test_that("ARROW-14071 - function(x)-style lambda functions are not supported", {
+test_that("ARROW-14071 - user-defined R functions", {
```
Comment (jonkeane) [inline r/tests/testthat/test-dplyr-across.R:280]:
```suggestion
test_that("ARROW-14071 - R functions from a user's environment", {
```

Just to be super clear this _isn't_ about UDFs

File: r/tests/testthat/test-dplyr-summarize.R [hunk 8]
```diff
@@ -836,28 +835,68 @@ test_that("Expressions on aggregations", {
...
+        weighted_mean = division(sum(int * dbl), sum(dbl))
+      ) %>%
+      collect(),
+    tbl
+  )
+
+  # We can also define functions that call supported aggregation functions
+  # and it just works
+  wtd_mean <- function(x, w) sum(x * w) / sum(w)
+  withr::local_options(list(arrow.debug = TRUE))
```
Comment (jonkeane) [inline r/tests/testthat/test-dplyr-summarize.R:885]: Nice, this is a helpful catch / test that honestly I could see being helpful when debugging this too — but makes this super clear that it's hitting this code and not some other path

File: r/tests/testthat/test-dplyr-summarize.R [hunk 9]
```diff
@@ -1083,11 +1121,6 @@ test_that("summarise() can handle scalars and literal values", {
     tibble(y = 1L)
   )
 
-  expect_identical(
-    record_batch(tbl) %>% summarise(y = Expression$scalar(1L)) %>% collect(),
-    tibble(y = 1L)
-  )
```
Comment (jonkeane) [inline r/tests/testthat/test-dplyr-summarize.R:1089]: This is the same as the one above it, yeah?

**Review by jonkeane — APPROVED** [review]
Thanks for this! I haven't pulled it locally (but should sometime soon). A few comments, mostly around comments

File: r/R/dplyr-summarize.R (hunk 4 above)
Comment (nealrichardson) [reply r/R/dplyr-summarize.R:194]: Correct, yeah, seemed like logically this case needed to be caught but I don't anticipate it being hit. If you're in `set_agg()`, somewhere up in the list of parent/enclosing environments, you'll find the one from `summarize_eval()` that contains this. 

If you were to call the binding outside of `summarize()`, like this, you'd hit it, but that's not a real use case:

```
> arrow:::agg_funcs[["sum"]](1)
Error in find_aggregations_env() : Could not find ..aggregations
```

File: r/R/dplyr-summarize.R (hunk 5 above)
Comment (nealrichardson) [reply r/R/dplyr-summarize.R:280]: I'll explain here, and then I'll add more in comments. 

`summarize()` is complicated because you can do a mixture of scalar operations and aggregations, but that's not how acero works. So we have to pull out the aggregations, collect them in one list (that will become an Aggregate ExecNode), and in the expressions, replace them with FieldRefs so that further operations can happen (in what will become a ProjectNode that works on the result of the Aggregate).

In "normal" arrow_eval, like in `mutate()`, each expression/quosure results in a single Arrow Expression. But in `summarize()`, it could generate one or more aggregations that go into Aggregate, and then an Expression after that. Example from the comments in `do_arrow_summarize()`:

```
  # For example,
  #   summarize(mean = sum(x) / n())
  # is effectively implemented as
  #   summarize(..temp0 = sum(x), ..temp1 = n()) %>%
  #   mutate(mean = ..temp0 / ..temp1) %>%
  #   select(-starts_with("..temp"))
```

So, each aggregation binding needs to push a `..tempN` aggregation onto some list somewhere and return a FieldRef so that any projections happening after evaluate "normally".

`ctx` was useful previously because we weren't calling `arrow_eval()` on the expressions, we were walking them, looking for known aggregation functions, pulling them out and inserting into the expression the `..tempN` symbols, and then once it was all scalar functions left, calling `arrow_eval()`. But that doesn't allow for defining a `weighted.mean` binding as `function(x, w) sum(x * w) / sum(w)` because you can't just substitute into the call to `weighted.mean(x, w)`, you really just want to evaluate it and let the usual Arrow Expression logic work. 

The challenge was: where is that "somewhere" to collect the aggregations? It needs to be somewhere where the binding functions can find it, we can't pass it in as an argument everywhere. 

Generally, R looks up symbols in each parent frame of where the function is defined, like this:

```
> x <- 1
> f <- function() x
> f()
[1] 1
```

So you'd think that you could just have `..aggregations` in this function, and when you evaluate the expressions, they would find them in the enclosing environment. But no. It's like this:

```
> g <- function() {
+   x <- 2
+   f()
+ }
> g()
[1] 1
```

`f()` has its own environment and looks up symbols from its parents. 

So, I put `..aggregations` in this environment, and then set *this* environment as the parent for each of the aggregation bindings in `arrow_mask()`. That way, they can find it and assign into it. This seemed better than the alternatives I almost gave up and fell back to, like something global/in the package namespace.

After doing that, I realized that I could do a similar thing with user functions: copy them into the mask and set their environment to be the mask, so they'd find the other bindings there.

Does that make sense?

Comment (jonkeane) [reply r/R/dplyr-summarize.R:280]: Aaah yes, got it. I didn't totally put together that `..aggregations` wasn't at the package scope, but that's really clever. And because it's transient within the call we don't have to worry about flushing it at the end / cleaning it up / managing state, yeah?

Comment (nealrichardson) [reply r/R/dplyr-summarize.R:280]: Correct

File: r/tests/testthat/test-dplyr-summarize.R (hunk 9 above)
Comment (nealrichardson) [reply r/tests/testthat/test-dplyr-summarize.R:1089]: They're all kinda the same, this one just no longer works because of how the evaluation changed, and it didn't seem worth trying to support, it's not a natural thing to do.

Comment (jonkeane) [reply r/tests/testthat/test-dplyr-summarize.R:1089]: Right, right about them all being _basically_ the same.

Agreed that it's not really a useful feature, but what does the error look like when it is called? My slight worry is that folks who find themselves here might be the type that need a bit more handholding to get out of compared to others?

File: r/R/dplyr-eval.R (hunk 1 above)
Comment (nealrichardson) [reply r/R/dplyr-eval.R:25]: Revised, PTAL

Comment (jonkeane) [reply r/R/dplyr-eval.R:25]: That's fantastic, thanks

File: r/tests/testthat/test-dplyr-summarize.R (hunk 9 above)
Comment (nealrichardson) [reply r/tests/testthat/test-dplyr-summarize.R:1089]: I don't remember TBH. But there's no legitimate reason for anyone to directly create `Expression$scalar()`, right?

Comment (jonkeane) [reply r/tests/testthat/test-dplyr-summarize.R:1089]: Absolutely agree there. We can add this as follow on, but my concern is if someone has become convinced that `Expression$scalar()` is needed there, if the error is one of our more generic ones or isn't clear they won't know enough to get out of that.

Comment (nealrichardson) [reply r/tests/testthat/test-dplyr-summarize.R:1089]: Turns out this case no longer errors after my most recent simplification, but I'm still going to keep the test deleted because I don't think this is part of the API surface we need to guarantee.

**Comment by thisisnic** [comment]
This is cool.  A few additional tests it might be worth chucking in to show how it works (or in the docs somewhere?) that are illustrative of a few things I wanted to check:

``` r
library(dplyr)
library(arrow)

single_transform <- function(x){
  str_remove_all(x, "[aeiou]")
}

multistep_transform <- function(x){
  y = stringr::str_replace_all(x, "B", "c")
  z = str_remove_all(y, "[aeiou]")
  z2 = str_to_upper(z)
  z2
}

multistep_transform_in_one <- function(x){
  str_to_upper(str_remove_all(stringr::str_replace_all(x, "B", "c"), "[aeiou]"))
}

tibble::tibble(x = c("Foo", "Bar", "Baz", "Qux")) %>%
  arrow_table() %>%
  mutate(y = single_transform(x)) %>%
  collect()
#> # A tibble: 4 × 2
#>   x     y    
#>   <chr> <chr>
#> 1 Foo   F    
#> 2 Bar   Br   
#> 3 Baz   Bz   
#> 4 Qux   Qx

tibble::tibble(x = c("Foo", "Bar", "Baz", "Qux")) %>%
  arrow_table() %>%
  mutate(y = multistep_transform(x)) %>%
  collect()
#> # A tibble: 4 × 2
#>   x     y    
#>   <chr> <chr>
#> 1 Foo   F    
#> 2 Bar   CR   
#> 3 Baz   CZ   
#> 4 Qux   QX

tibble::tibble(x = c("Foo", "Bar", "Baz", "Qux")) %>%
  arrow_table() %>%
  mutate(y = multistep_transform_in_one(x)) %>%
  collect()
#> # A tibble: 4 × 2
#>   x     y    
#>   <chr> <chr>
#> 1 Foo   F    
#> 2 Bar   CR   
#> 3 Baz   CZ   
#> 4 Qux   QX
```

**Comment by thisisnic** [comment]
This is what I was referring to with "not supported in arrow" @nealrichardson though I hadn't realised it already works really well when calling functions via `mutate()` in terms of reporting the failed function, so things might be fine as-is, though printing out which function doesn't have bindings would be a nice-to-have.

``` r
library(arrow)
library(dplyr)

single_transform <- function(x){
  # this function does have bindings
  stringr::str_remove_all(x, "[aeiou]")
}

# succeeds
tibble::tibble(x = c("Foo", "Bar", "Baz", "Qux")) %>%
  arrow_table() %>%
  mutate(y = single_transform(x)) %>%
  collect()
#> # A tibble: 4 × 2
#>   x     y    
#>   <chr> <chr>
#> 1 Foo   F    
#> 2 Bar   Br   
#> 3 Baz   Bz   
#> 4 Qux   Qx

single_transform2 <- function(x){
  # this function doesn't have bindings
  stringr::str_to_sentence(x)
}

tibble::tibble(x = c("Foo", "Bar", "Baz", "Qux")) %>%
  arrow_table() %>%
  mutate(y = stringr::str_to_sentence(x)) %>%
  collect()
#> Warning: Expression stringr::str_to_sentence(x) not supported in Arrow; pulling
#> data into R
#> # A tibble: 4 × 2
#>   x     y    
#>   <chr> <chr>
#> 1 Foo   Foo  
#> 2 Bar   Bar  
#> 3 Baz   Baz  
#> 4 Qux   Qux

tibble::tibble(x = c("Foo", "Bar", "Baz", "Qux")) %>%
  arrow_table() %>%
  mutate(y = single_transform2(x)) %>%
  collect()
#> Warning: Expression single_transform2(x) not supported in Arrow; pulling data
#> into R
#> # A tibble: 4 × 2
#>   x     y    
#>   <chr> <chr>
#> 1 Foo   Foo  
#> 2 Bar   Bar  
#> 3 Baz   Baz  
#> 4 Qux   Qux
```

File: r/R/dplyr-summarize.R (hunk 5 above)
Comment (nealrichardson) [reply r/R/dplyr-summarize.R:299]: I added/reworked the comments in this function, and otherwise did some simplification so that I hope the code is more readable too. LMK what you think.

**Comment by nealrichardson** [comment]
This is ready to go AFAIK @jonkeane @thisisnic, LMK if you have any more feedback.

**Review by thisisnic — APPROVED** [review]
Looks good though probably worth addressing [this comment](https://github.com/apache/arrow/pull/41223#issuecomment-2064355518) in a follow-up ticket perhaps?

**Comment by nealrichardson** [comment]
> Looks good though probably worth addressing [this comment](https://github.com/apache/arrow/pull/41223#issuecomment-2064355518) in a follow-up ticket perhaps?

I don't think I can do any better than what it does now. With `single_transform2(x)` failing, there's not anything in that expression that would give away what is not supported, you have to step through the function, and it could be doing anything so IDK that looking for unsupported functions named within that would do much. And unfortunately the error that `stringr::str_to_sentence` raises isn't obvious either: if you set `options(arrow.debug=TRUE)`, the warning shown includes the actual error, saying: "Warning: In single_transform2(x), cannot coerce type 'environment' to vector of type 'character'; pulling data into R".

File: r/NEWS.md [hunk 10]
```diff
@@ -19,6 +19,9 @@
 
 # arrow 16.0.0.9000
 
+* R functions that users write that use functions that Arrow supports in dataset queries now can be used in queries too. Previously, only functions that used arithmetic operators worked. For example, `time_hours <- function(mins) mins / 60` worked, but `time_hours_rounded <- function(mins) round(mins / 60)` did not; now both work. These are not true user-defined functions (UDFs); for those, see `register_scalar_function()`. (#41223)
```
Comment (amoeba) [inline r/NEWS.md:22]: Late to looking at this but maybe the specifics around this can be documented better in user-facing help pages. If there are "true UDFs" (which these aren't), what would we call these? Further, it looks like this doesn't pull the data into R, is my read correct?

Comment (nealrichardson) [reply r/NEWS.md:22]: > Late to looking at this but maybe the specifics around this can be documented better in user-facing help pages. If there are "true UDFs" (which these aren't), what would we call these? 

🤷 I'm not sure there is an accepted term of art for this.

> Further, it looks like this doesn't pull the data into R, is my read correct?

Correct. In this case, `time_hours_rounded(x)` will evaluate to something like

```r
Expression$create("round",
  list(
    Expression$create("divide_checked", 
      list(Expression$fieldref("x"), Expression$scalar(60)))
  )
)
```

There will be no named `time_hours_rounded` function that acero sees, and data doesn't get pulled into R to compute it, it's all based on expressions that are supported in acero.

Comment (thisisnic) [reply r/NEWS.md:22]: If the phrasing is ambiguous here, perhaps we could update "These are not true user-defined functions (UDFs)" to "These are automatic translations rather than true user-defined functions (UDFs)"?

Comment (amoeba) [reply r/NEWS.md:22]: Thanks all. I took @thisisnic's language and rolled it into https://github.com/apache/arrow/pull/41368.
