### PR TITLE
GH-37110: [C++] Expression: SmallestTypeFor lost tz for Scalar

### LINKED ISSUE #37110: Cannot filter dataset with a timestamp (with timezone) column
### Describe the bug, including details regarding any error messages, version, and platform.

Pyarrow: 12.0.1

This is similar to #32366 but not exactly the same. I have a dataset where I am trying to filter by a column in my parquet files that is a timestamp with timezone type. Every way that I try to do the filter, pyarrow coerces the type to a non-timestamp type and fails to convert to a table. For example:
```
(ds is my dataset)
>>> dt
datetime.datetime(2023, 6, 29, 4, 0, tzinfo=<UTC>)
>>> dcast = pa.scalar(dt, type=pa.timestamp('ms', tz='UTC')
>>> filter = (ds.field('readout_time')>dcast)
>>> df = dataset.to_table(filter=filter,columns=['readout_time', 'acceleration_x', 'acceleration_y', 'acceleration_z']).to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/_dataset.pyx", line 546, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3449, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Cannot compare timestamp with timezone to timestamp without timezone, got: timestamp[ms, tz=UTC] and timestamp[ms]
```

This was just my latest attempt to use an actual arrow scaler with timezone, and it still changes the type to a non timestamp type in the comparison. It also fails using a datetime in the filter directly.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

This patch ( https://github.com/apache/arrow/pull/15180 ) adds a `SmallestTypeFor` to handling expression type. However, it lost timezone when handling.

### What changes are included in this PR?

Add `timezone` in `SmallestTypeFor`

### Are these changes tested?

Currently not

### Are there any user-facing changes?

Yeah it's a bugfix

* Closes: #37110

### CODE REVIEW

**Comment by mapleFU** [comment]
@bkietz @pitrou Would you mind take a look?

File: cpp/src/arrow/compute/expression_test.cc [hunk 1]
```diff
@@ -630,6 +630,12 @@ TEST(Expression, BindWithImplicitCasts) {
                       literal(std::make_shared<TimestampScalar>(0, TimeUnit::NANO))),
                   cmp(field_ref("ts_s"),
                       literal(std::make_shared<TimestampScalar>(0, TimeUnit::SECOND))));
+    // GH-37110
+    ExpectBindsTo(
+        cmp(field_ref("ts_s"),
+            literal(std::make_shared<TimestampScalar>(0, TimeUnit::NANO, "UTC"))),
+        cmp(field_ref("ts_s"),
+            literal(std::make_shared<TimestampScalar>(0, TimeUnit::SECOND, "UTC"))));
```
Comment (pitrou) [inline cpp/src/arrow/compute/expression_test.cc:638]: Since we are at it and the original PR didn't add many tests, can we also test non-zero values? For example (untested):
```suggestion
            literal(std::make_shared<TimestampScalar>(0, TimeUnit::SECOND, "UTC"))));
    ExpectBindsTo(
        cmp(field_ref("ts_s"),
            literal(std::make_shared<TimestampScalar>(123000, TimeUnit::NANO, "UTC"))),
        cmp(field_ref("ts_s"),
            literal(std::make_shared<TimestampScalar>(123, TimeUnit::MICRO, "UTC"))));         
```

**Review by pitrou — COMMENTED** [review]
Nice catch, @mapleFU ! LGTM but just a suggestion.

File: cpp/src/arrow/compute/expression_test.cc (hunk 1 above)
Comment (mapleFU) [reply cpp/src/arrow/compute/expression_test.cc:639]: Added, I also found that we need a UTC

```c++
field("ts_s_utc", timestamp(TimeUnit::SECOND, "UTC"))
```

**Review by pitrou — APPROVED** [review]

**Comment by brokenjacobs** [comment]
Great find!
