### PR TITLE
GH-37308: [C++][Docs] Change name for CPP tutorial and minor fixes to the job

### LINKED ISSUE #37308: [C++][Docs] cpp-tutorial-example fails building
### Describe the bug, including details regarding any error messages, version, and platform.

The `cpp-tutorial-example` Crossbow task fails building, as seen here:
https://github.com/ursacomputing/crossbow/actions/runs/5937066578

### Component(s)

C++, Documentation

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Fix the job and rename so it's picked up as part of the nightlies

### What changes are included in this PR?

Rename + fixes to the job.

### Are these changes tested?

Via CI

### Are there any user-facing changes?

No
* Closes: #37308

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit example-cpp-tutorial

File: cpp/examples/tutorial_examples/run.sh [hunk 1]
```diff
@@ -45,6 +45,8 @@ echo "== Running example project"
 echo "=="
 echo
 
+export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```
Comment (raulcd) [inline cpp/examples/tutorial_examples/run.sh:48]: @kou I am slightly confused on why if I don't add the `/usr/local/lib` to `LD_LIBRARY_PATH` the job fails with:
```
/build/example/dataset_example: error while loading shared libraries: libarrow_acero.so.1300: cannot open shared object file: No such file or directory
```
Any idea if I am missing something?

Comment (raulcd) [reply cpp/examples/tutorial_examples/run.sh]: Thanks @kou ! I had to add `CMAKE_PREFIX_PATH` too otherwise I was getting:
```
CMake Error at CMakeLists.txt:22 (find_package):
  By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Arrow", but
  CMake did not find one.

  Could not find a package configuration file provided by "Arrow" with any of
  the following names:

    ArrowConfig.cmake
    arrow-config.cmake

  Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
  "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
with all these changes it is still failing to find `libarrow_acero.so.1300` when executing.

**Comment by raulcd** [comment]
@github-actions crossbow submit example-cpp-tutorial

File: cpp/examples/tutorial_examples/CMakeLists.txt [hunk 2]
```diff
@@ -22,8 +22,7 @@ project(ArrowTutorialExamples)
 find_package(Arrow REQUIRED)
 
 get_filename_component(ARROW_CONFIG_PATH ${Arrow_CONFIG} DIRECTORY)
```
Comment (kou) [inline cpp/examples/tutorial_examples/CMakeLists.txt:24]:
```suggestion
```

File: cpp/examples/tutorial_examples/run.sh (hunk 1 above)
Comment (kou) [reply cpp/examples/tutorial_examples/run.sh]: Oh, sorry. How about specifying rpath to Arrow C++ too?

```diff
diff --git a/cpp/examples/tutorial_examples/run.sh b/cpp/examples/tutorial_examples/run.sh
index 4e5e8eeab..bc0078435 100755
--- a/cpp/examples/tutorial_examples/run.sh
+++ b/cpp/examples/tutorial_examples/run.sh
@@ -30,7 +30,8 @@ echo "== Building Arrow C++ library"
 echo "=="
 echo
 
-ARROW_CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=${ARROW_INSTALL_DIR}" \
+ARROW_CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=${ARROW_INSTALL_DIR} \
+                     -DCMAKE_INSTALL_RPATH=${ARROW_INSTALL_DIR}/lib" \
   ./build_arrow.sh
 
 echo
@@ -39,7 +40,8 @@ echo "== Building example project using Arrow C++ library"
 echo "=="
 echo
 
-EXAMPLE_CMAKE_OPTIONS="-DCMAKE_INSTALL_RPATH=${ARROW_INSTALL_DIR}/lib -DCMAKE_PREFIX_PATH=${ARROW_INSTALL_DIR}" \
+EXAMPLE_CMAKE_OPTIONS="-DCMAKE_INSTALL_RPATH=${ARROW_INSTALL_DIR}/lib \
+                       -DCMAKE_PREFIX_PATH=${ARROW_INSTALL_DIR}" \
   ./build_example.sh
 
 echo
```

**Comment by raulcd** [comment]
@github-actions crossbow submit example-cpp-tutorial

File: cpp/examples/tutorial_examples/run.sh (hunk 1 above)
Comment (raulcd) [reply cpp/examples/tutorial_examples/run.sh]: Thanks @kou ! This worked locally, running on archery now.

**Review by kou — APPROVED** [review]
+1
