### PR TITLE
GH-37969: [C++][Parquet] add more closed file checks for ParquetFileWriter

### LINKED ISSUE #37969: [R][C++] segfault when writing to ParquetFileWriter after closing
### Describe the bug, including details regarding any error messages, version, and platform.

Writing to a closed writer causes a segfault rather than an error. I ran into this while testing something unrelated, evaluating portions of a larger script in a REPL. Writing to a closed output errors as expected so the key here is `writer$Close()` and the subsequent `writer$WriteTable` call:

```r
library(arrow)

outfile <- tempfile(fileext = ".parquet")
sink <- FileOutputStream$create(outfile)

my_schema <- schema(letters = string())
writer <- ParquetFileWriter$create(
  schema = my_schema,
  sink,
  properties = ParquetWriterProperties$create(
    column_names = names(my_schema),
    compression = arrow:::default_parquet_compression()
  )
)
tbl_arrow <- as_arrow_table(data.frame(letters=LETTERS), schema = my_schema)
writer$WriteTable(tbl_arrow, chunk_size = 1)

writer$Close()
sink$close()

tbl_arrow <- as_arrow_table(data.frame(letters=LETTERS), schema = my_schema)
writer$WriteTable(tbl_arrow, chunk_size = 1)
```

Result:

```
 *** caught segfault ***
address 0x0, cause 'invalid permissions'

Traceback:
 1: parquet___arrow___FileWriter__WriteTable(self, table, chunk_size)
 2: writer$WriteTable(tbl_arrow, chunk_size = 1)
An irrecoverable exception occurred. R is aborting now ...
fish: Job 1, 'Rscript arrow_memorypool_crashe…' terminated by signal SIGSEGV (Address boundary error)
```

- OS/arch: macOS 14.0 (Sonoma), aarch64 (M2)
- R: 4.3.1
- arrow version: 13.0.0.1

### Component(s)

R

### PR DESCRIPTION
**Pull request by quanghgx**
### Rationale for this change
Operations on closed ParquetFileWriter are not allowed, but should not segfault. Somehow, ParquetFileWriter::Close() also reset its pimpl, so after that, any operators, those need this pointer will lead to segfault

### What changes are included in this PR?
Adding more checks for closed file.

### Are these changes tested?
Yes.

### Are there any user-facing changes?
No.

* Closes: #37969

### CODE REVIEW

**Comment by mapleFU** [comment]
(I didn't go through the issue carefully, but would `CheckClosed` function like S3 Filesystem better here?)

**Comment by quanghgx** [comment]
> (I didn't go through the issue carefully, but would `CheckClosed` function like S3 Filesystem better here?)
> 
> e.g. https://github.com/apache/arrow/blob/main/cpp/src/arrow/filesystem/s3fs.cc#L1249

Thanks for your hint.  Refactored the checking into separate method. Use "Assert" here because it will throw instead of return arrow::Status. As operation on closed object is not a normal application flow.

Please help take a look again, @mapleFU

File: cpp/src/parquet/arrow/writer.cc [hunk 1]
```diff
@@ -319,6 +319,7 @@ class FileWriterImpl : public FileWriter {
       closed_ = true;
       if (row_group_writer_ != nullptr) {
         PARQUET_CATCH_NOT_OK(row_group_writer_->Close());
+        row_group_writer_ = nullptr;  // To avoid double closing
```
Comment (mapleFU) [inline cpp/src/parquet/arrow/writer.cc:322]: Suggest:
```suggestion
      if (row_group_writer_ != nullptr) {
        auto row_group_writer = std::move(row_group_writer_);
        PARQUET_CATCH_NOT_OK(row_group_writer->Close());
```

Comment (mapleFU) [reply cpp/src/parquet/arrow/writer.cc:322]: Also, a bit curious that when would it double-close here?

**Comment by mapleFU** [comment]
>  Use "Assert" here because it will throw instead of return arrow::Status. As operation on closed object is not a normal application flow.

Ooops, I think you're choosing the right way, but thats maybe because `parquet` lib uses exception, and arrow uses `Status`. So I think we'd better use Exception here. If we are do it in `parquet/arrow` directory we need use `Status`

**Comment by mapleFU** [comment]
```c++
  Status Close() override {
    if (!closed_) {
      // Make idempotent
      closed_ = true;
      if (row_group_writer_ != nullptr) {
        auto row_group_writer = std::move(row_group_writer_);
        PARQUET_CATCH_NOT_OK(row_group_writer->Close());
      }
      PARQUET_CATCH_NOT_OK(writer_->Close());
    }
```

Actually this change LGTM. But I'm not fully understand why `row_group_writer_` will be double-closed. For example, when call `FileWriter::Close` twice, the `closed_` will be true, so `row_group_writer_` will only close once. Did I miss something?

File: cpp/src/parquet/arrow/writer.cc (hunk 1 above)
Comment (quanghgx) [reply cpp/src/parquet/arrow/writer.cc]: > Also, a bit curious that when would it double-close here?

It will be closed again, in:
https://github.com/apache/arrow/blob/450175b2dbfc7834be72883c5a0e6ac93e8ed5aa/cpp/src/parquet/arrow/writer.cc#L308-L314

This is surely not intended normal use case (use after closed). Let me do one more check for why calling ```row_group_writer_->Close()``` twice also causes segfault and report back.

Comment (mapleFU) [reply cpp/src/parquet/arrow/writer.cc]: You can leave this patch just checking here, and find out why it would close twice, then open a new issue for that?

I'm a bit tired today, maybe I'll gothrough the code here tomorrow

**Comment by quanghgx** [comment]
> Actually this change LGTM. But I'm not fully understand why `row_group_writer_` will be double-closed. For example, when call `FileWriter::Close` twice, the `closed_` will be true, so `row_group_writer_` will only close once. Did I miss something?

you are right, normally, it will not be called twice. However, in test case for use-after-close with ```writer->Close()``` and then ```writer->NewBufferedRowGroup()```:
https://github.com/apache/arrow/blob/450175b2dbfc7834be72883c5a0e6ac93e8ed5aa/cpp/src/parquet/arrow/arrow_reader_writer_test.cc#L5227-L5237

To be honest, I think I need to study a bit more to fully understand state diagram of these there attributes {```writer_```, ```row_group_writer_``` and ```closed_``` } of FileWriterImpl. If you have hints for me, that will be great?
https://github.com/apache/arrow/blob/450175b2dbfc7834be72883c5a0e6ac93e8ed5aa/cpp/src/parquet/arrow/writer.cc#L479-L483
Thank you so much @mapleFU

File: cpp/src/parquet/arrow/writer.cc (hunk 1 above)
Comment (quanghgx) [reply cpp/src/parquet/arrow/writer.cc]: You are right, we'd better open new issue for that.

**Comment by quanghgx** [comment]
Update:,
* Revised MR (simplified) so that it focuses on the fix for ```writer->Close(); writer->WriteTable(..)```
* Double closing and other cases of use after close will need further understanding. Will open a new issue with your help to clarify the intended flow of the code.
How do you think? Thank you so much for guiding me along the way; I don't mind to document it down, get your review along with MR for that. Thanks @mapleFU

**Comment by mapleFU** [comment]
Parquet is about two parts in this library
1. `parquet`: the core part of parquet, mostly it handles types like parquet defined physical-type and logical type.
2. `parquet/arrow`: the arrow part of parquet. It read / write arrow array, and maintaining some other infos.

The writer has the structure below:

```
arrow::parquet::FileWriter (Holding parquet::ParquetFileWriter, and some arrow-related schema/metadata)
parquet::ParquetFileWriter ( holds fileMetadata and at most one active row-group writer)
- parquet::FileSerializer extends parquet::ParquetFileWriter::Contents
parquet::RowGroupWriter (Holding some ColumnWriter)
- parquet::RowGroupSerializer extends parquet::RowGroupWriter::Contents
ColumnWriter
- May hold encoder and write multiple pages
```

Also, there are some `buffered` and `unbuffered` RowGroupWriter. You can go through the doc for that.

**Review by mapleFU — DISMISSED** [review]
<del>
+1

Also cc @wgtmac @pitrou
</del>

**Comment by quanghgx** [comment]
Thank you, @mapleFU, for providing a clear and detailed guideline. I've applied these changes and added back two simple tests.

I have one final comment regarding the `WriteTable` function:

We currently have two options for handling errors in this function:
* (A.) We can let `writer->WriteTable` throw a `ParquetException`. This is because, in [this part of the code](https://github.com/apache/arrow/blob/2ec5d63277e559607cf32a901c2969be33cdfcb4/cpp/src/parquet/arrow/writer.cc#L375), it calls this->properties, which directly returns a `ParquetException` from `writer_`.
* (B.) Alternatively, we can add `RETURN_NOT_OK(CheckClosed());` to the beginning of `WriteTable`, similar to `NewRowGroup` and `NewBufferedRowGroup`. This would consistently return `arrow::Status::Invalid`.

I personally lean towards option (B.) for the sake of consistency. However, considering that use-after-close is not a typical flow (usually requiring user code revision to fully handle this case), using an exception might be a viable option here.

This part is making me uncertain, so I would appreciate your input on this matter. Thanks mappleFU.

**Comment by mapleFU** [comment]
Sorry for delaying reply.

Nice catch, I missed `this->properties()` call here. I prefer we can also add a `CheckClosed` in `WriteTable`, this is much more easier... Personally `properties` might be called frequently, which might be hard to debug and reason.

**Review by mapleFU — APPROVED** [review]
LGTM

Also cc @pitrou @wgtmac

**Comment by mapleFU** [comment]
CI failed in unrelated

Will wait other committers review

**Review by pitrou — CHANGES_REQUESTED** [review]
Why aren't you protecting all public methods in `FileWriter`? I don't think it makes sense to only protect a couple of them.

**Comment by mapleFU** [comment]
@pitrou Should this better for adding it on

```
  Status WriteColumnChunk(const std::shared_ptr<ChunkedArray>& data, int64_t offset,
                          int64_t size) override {...} 

  Status WriteRecordBatch(const RecordBatch& batch) override;
```

I think other methods like `Init` and `schema()` is not so neccessary here?

**Comment by pitrou** [comment]
Everywhere where we rely on something that's destroyed by `Close`.

**Comment by mapleFU** [comment]
Well I think adding in functions I mentioned above is ok

Previously I think `NewRowGroup` is OK, because without `WriteRecordBatch`, every write operation will call `New{Buffered}RowGroup`, but this change also LGTM

**Comment by quanghgx** [comment]
Thanks @mapleFU and @pitrou 
Added:

- `WriteColumnChunk(.. )` // Actual implementation; other two overloads all delegate to this.
- `WriteRecordBatch(.. )`

Reviewed, safe to skip:

- `Init()`  // Internally implemented and called only within `FileWriter::Make`, with a newly created writer.
- `schema()` // Independent of the writer.
- `properties()` // Internal implementation, called by `WriteTable`, `WriteRecordBatch`, both already validated.
- `metadata()` // In the current implementation of `ParquetFileWriter::Content`, it's safe to be called when closed. Open to adding this.

**Comment by quanghgx** [comment]
update: 3 failing tests are unrelated, I believe.

**Comment by pitrou** [comment]
Indeed, the CI failures are unrelated.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
Thank you @quanghgx ! I will merge this PR now.
