### PR TITLE
GH-37712: [Go][Parquet] Fix ARM64 assembly for bitmap extract bits

### LINKED ISSUE #37712: [Go][Parquet] Reading a parquet file with a nested field that is null for all records panics when using Go 1.21.1
### Describe the bug, including details regarding any error messages, version, and platform.

When reading Parquet files containing a nested field that is null for all records, it panics when using go 1.21.1 but not when using go 1.20.8.

This is a small reproducible case:
https://github.com/chelseajonesr/rfarrow/blob/f7bef4585eeb4d7582014bc54b0fa7092651f774/panic_test.go#L13

The panic:
```
panic: runtime error: slice bounds out of range [:5] with capacity 0

goroutine 15 [running]:
github.com/apache/arrow/go/v13/parquet/internal/encoding.(*PlainByteArrayDecoder).DecodeSpaced(0x0?, {0x0?, 0x14000307ce8?, 0x103398720?}, 0x103d2ff20?, {0x14000140980?, 0x100307c01?, 0x2?}, 0x400010000001f?)
	/Users/chelseajones/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/parquet/internal/encoding/byte_array_decoder.go:83 +0x130
github.com/apache/arrow/go/v13/parquet/file.(*byteArrayRecordReader).ReadValuesSpaced(0x1400017eb00, 0x0, 0x20?)
	/Users/chelseajones/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/parquet/file/record_reader.go:841 +0x134
github.com/apache/arrow/go/v13/parquet/file.(*recordReader).ReadRecordData(0x14000103260, 0x1)
	/Users/chelseajones/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/parquet/file/record_reader.go:548 +0x288
github.com/apache/arrow/go/v13/parquet/file.(*recordReader).ReadRecords(0x14000103260, 0x1)
	/Users/chelseajones/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/parquet/file/record_reader.go:632 +0x32c
github.com/apache/arrow/go/v13/parquet/pqarrow.(*leafReader).LoadBatch(0x140001032c0, 0x1)
	/Users/chelseajones/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/parquet/pqarrow/column_readers.go:103 +0xd8
github.com/apache/arrow/go/v13/parquet/pqarrow.(*structReader).LoadBatch.func1()
	/Users/chelseajones/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/parquet/pqarrow/column_readers.go:241 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/chelseajones/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 13
	/Users/chelseajones/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
```

### Component(s)

Go, Parquet

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
The linked issue discovered a problem with the ARM64 implementation of the extractBits functionality which was being hidden because until `go1.21`, it looks like `golang.org/x/sys/cpu` wasn't properly detecting the ASIMD bit flag on the ARM processors and so it was using the pure go implementation. So we fix the assembly and add a test which was able to reproduce the failure without the fix on an ARM64 machine. 

### What changes are included in this PR?
There was a problem with the assembly as it existed as the short circuit case where the selection bitmap is 0 wasn't actually setting the 0 value back onto the stack as a return. The assembly which initialized that register to 0 only occurred AFTER the `CBZ` instruction which would jump to the bottom and return. This means that we *actually* returned whatever happened to be on the stack at that location (i.e. garbage!). This only occurred if you were using the ARM64-specific assembly implementation, not the amd64 or pure go versions.

We also include a test to ensure we get the correct values for a variety of bitmaps and selections, along with this ensuring there's enough data on the stack so that if this problem re-occured we would catch it in this test.

### Are these changes tested?
Test is added.

* Closes: #37712

### CODE REVIEW

**Comment by zeroshade** [comment]
Ugh, looks like ALL the neon assembly is borked, it just wasn't ACTUALLY being run because `golang.org/x/sys/cpu` wasn't registering the ASIMD bit, but `github.com/klauspost/cpuid/v2` DOES correctly recognize it and now we're seeing it die. 

I guess I'll take a stab at fixing and debugging that tomorrow.

**Comment by zeroshade** [comment]
Interestingly, it's only failing on linux/arm64 not macOS ARM64.... which is, well, odd. *sigh* Why can't things be easy. I'm guessing there's probably a feature flag that i should be checking for that I'm not

File: go/parquet/internal/bmi/bmi_arm64.go [hunk 1]
```diff
@@ -14,40 +14,38 @@
...
 	"os"
 	"strings"
-)
-import (
-	"golang.org/x/sys/cpu"
+
+	"github.com/klauspost/cpuid/v2"
 )
 
 func init() {
```
Comment (pitrou) [inline go/parquet/internal/bmi/bmi_arm64.go:29]: This code looks duplicated in two different source files, is it me?

File: go/parquet/internal/bmi/bmi_arm64.go [hunk 2]
```diff
@@ -14,40 +14,38 @@
...
-				cpu.ARM64.HasAES = true
+				cpuid.CPU.Enable(cpuid.AESARM)
 			case "PMULL":
-				cpu.ARM64.HasPMULL = true
+				cpuid.CPU.Enable(cpuid.PMULL)
 			default:
-				cpu.ARM64.HasASIMD = false
-				cpu.ARM64.HasAES = false
-				cpu.ARM64.HasPMULL = false
+				cpuid.CPU.Disable(cpuid.ASIMD, cpuid.AESARM, cpuid.PMULL)
```
Comment (pitrou) [inline go/parquet/internal/bmi/bmi_arm64.go:44]: Hmm, so if an invalid value is passed in `ARM_ENABLE_EXT`, all extensions are silently disabled? It would be more user-friendly to print a warning.

File: go/parquet/internal/bmi/bitmap_neon_arm64.s [hunk 3]
```diff
@@ -27,8 +27,8 @@ LBB0_2:
     MOVD R0, res+16(FP)
     RET
 LBB0_4:
-    WORD $0xaa1f03e0 // mov    x0, xzr
     WORD $0xa8c17bfd // ldp    x29, x30, [sp], #16
+    MOVD ZR, res+16(FP)
```
Comment (pitrou) [inline go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: Hmm, how did you come with this fix? I thought this assembly code wasn't written by hand?

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 1 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bmi_arm64.go:29]: the reason why the code is duplicated is because this runs at image startup (via the `init` function) which means if this package isn't imported, then this function never runs. The bottom of the function sets the appropriate function pointer based on whether or not the processor actually supports things or not, and this package is a low level utility that doesn't import anything else so there isn't a shared place I could put this initialization between the two places.

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 2 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bmi_arm64.go:44]: technically we aren't actually *disabling* the extensions on the CPU, we're just telling the library that anything that wants to check for those extensions should consider them disabled and act accordingly. For example if an invalid value is passed we behave as if those extensions weren't enabled regardless and default to the pure go implementation.

That said, I agree it would be more user-friendly to have an explicit "DISABLE" value, and then just print a warning for invalid values. I'll make that change.

Comment (pitrou) [reply go/parquet/internal/bmi/bmi_arm64.go:44]: > technically we aren't actually _disabling_ the extensions on the CPU

Yes, I figured that out :-)

File: go/parquet/internal/bmi/bitmap_neon_arm64.s (hunk 3 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: The assembly wasn't *generated* by hand, but this fix was absolutely written by hand (me) by way of looking at the code, the generated assembly, and stepping through the instructions to figure out what was happening incorrectly.

In this case, the problem was that the instructions which zero-out the return value got placed *after* the loop condition (checking if the selection bitmap was zero), so in that scenario we ended up returning whatever happened to be the next 8 bytes after the memory location the arguments were placed. I had to look up a bunch of stuff about how Go plan9 assembly works and also ARM64 assembly, to work out that zero'ing out one area was able to be done by simply storing from `ZR` the zero-register.

Comment (pitrou) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: Do you think it's a C/C++ compiler bug? That sounds a bit unlikely to me, given how simple the `extract_bits` function is.

Also, why are you compiling this code for Neon? I find it unlikely that Neon can be used to speed up your SW emulation of `PEXT`.

Also, we have a SW emulation in Parquet C++ that processes 5 bits at a time rather than one. You could perhaps try to compile that one (or rewrite it in Go) :-)

Comment (zeroshade) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: Without knowing how Yuqi originally generated the arm64 assembly, I'm not sure what the cause of this was. All i know is that this was never correct, but was hidden by the fact that we were unaware of a bug in the `golang.org/x/sys/cpu` package which was failing to detect ARM features correctly so the ARM builds were just using the pure go implementation.

> Also, why are you compiling this code for Neon? I find it unlikely that Neon can be used to speed up your SW emulation of PEXT.

From what I can tell, ARM doesn't have a `PEXT` instruction, again this C impl was provided by a contributor but doing a bit of research it looks like the implementation there is essentially the standard way to implement `PEXT` for ARM in C when I do some stack overflow searching. (There's also a couple variations I came across, but they roughly even out).

> Also, we have a SW emulation in Parquet C++ that processes 5 bits at a time rather than one. You could perhaps try to compile that one (or rewrite it in Go) :-)

The pure go impl already does it! if you look at `bmi.go` it's a direct port of the software emulation in `level_conversion_inc.h` from the C++ parquet impl. We only go to the assembly / non-pure-go impl if our CPU check says that it supports BMI2 so that we can call `pext_u64` directly at runtime. 

The compiling for NEON is to get the benefit of vectorization for the `levels_to_bitmap` function (i.e. the `GreaterThanBitmap` SIMD method).

Comment (pitrou) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: > Without knowing how Yuqi originally generated the arm64 assembly, I'm not sure what the cause of this was. 

There should be a well-defined way to generate the assembly, so that other people can later participate in maintenance.
(also, is it possible that the original arm64 assembly was simply out of sync with the current C source?)

> The pure go impl already does it!

Nice, so you just need to port it to C now :-)

Comment (cyb70289) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: > The assembly wasn't _generated_ by hand, but this fix was absolutely written by hand (me) by way of looking at the code, the generated assembly, and stepping through the instructions to figure out what was happening incorrectly.
> 

This is cool!

Might be bug from asm2plan9s. Or errors from manually converting/formatting from normal arm assembly to plan9.
Not sure the best approach to convert normal C/assembly to plan9 assembly. [asm2plan9s](https://github.com/minio/asm2plan9s) and [c2goasm](https://github.com/minio/c2goasm) are archived. Looks we should avoid them.

For this pext like function, the go version (lookup table) should perform better than this one. Maybe we can just delete this assembly implementation?

Comment (zeroshade) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: @cyb70289 I'd be fine with removing the arm assembly implementation of the pext function. I haven't benchmarked the lookup table vs the ARM assembly version yet. but I agree the lookup table would likely be faster.

The other issue i'm having is the bit packing side of things, though I think i may have figured out a solution to it... and i've learned more about ARM64 assembly in the last few days than i ever intended on learning LOL as I've needed to do a lot of handcoding assembly to get this to work. Looks like the issue boils down to needing anything with a label to be explicit in the assembly rather than using the `WORD`/`BYTE` syntax to pass them to the processor stream so that the labels get translated to the correct PC locations.

**Comment by zeroshade** [comment]
@cyb70289 @pitrou  holy crap i got it to work! :grin: now i just gotta document what i did before i forget so i never have to do this again lol

File: go/parquet/internal/bmi/bitmap_neon_arm64.s (hunk 3 above)
Comment (cyb70289) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: Wrote a [benchmark](https://github.com/cyb70289/mytests/blob/master/go/bmi/bmi_test.go), the golang version is indeed faster than assembly. Tested on Neoverse-N1.
```
$ go test -bench=.
goos: linux
goarch: arm64
pkg: bmi
BenchmarkGo-80               663           1759920 ns/op
BenchmarkAsm-80              435           2720235 ns/op
PASS
ok      bmi     2.838s
```

Comment (zeroshade) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s:31]: well that settles that :) i'll update this and remove the asm version for arm :smile: Thanks!

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 1 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bmi_arm64.go:30]: I switched this around so that it doens't need to be duplicated anymore.

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 2 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bmi_arm64.go]: updated so that if the value of the env var is "DISABLE" then we disable things, otherwise we just print any unrecognized options to stderr

File: go/parquet/internal/bmi/bitmap_neon_arm64.s (hunk 3 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bitmap_neon_arm64.s]: removed the ARM asm version so that it just uses the pure go lookup-table impl

**Comment by zeroshade** [comment]
@cyb70289 @pitrou this is ready for another look over and review now! thanks. Given the complexity i'm going to punt creating actual automation for the ARM assembly generation to follow-up PR instead

File: go/parquet/internal/bmi/bmi_arm64.go [hunk 4]
```diff
@@ -14,44 +14,51 @@
...
 
 package bmi
 
 import (
+	"fmt"
 	"os"
 	"strings"
-)
-import (
-	"golang.org/x/sys/cpu"
```
Comment (cyb70289) [inline go/parquet/internal/bmi/bmi_arm64.go:26]: `cpu.ARM64.HasASIMD` is false on some arm64 platform?
It does work correctly on my test machine (ubunt22.05, aarch64, golang1.21).

File: go/parquet/internal/utils/clib.go [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+
+package utils
+
+import "unsafe"
+
+//go:noescape
+func _ClibMemcpy(dst, src unsafe.Pointer, n uint) unsafe.Pointer
+
+//go:noescape
+func _ClibMemset(dst unsafe.Pointer, c int, n uint) unsafe.Pointer
```
Comment (pitrou) [inline go/parquet/internal/utils/clib.go:30]: I'm curious, what is this and what is it good for? Doesn't Go provide memcpy/memset replacements?

**Comment by pitrou** [comment]
Regardless of automation, there should be READMEs explaining the rationale and motivations, and also how to generate those files anew.

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 4 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bmi_arm64.go:26]: From what I could tell in my testing, it appears that on `golang1.20` and below, it was ending up false on arm64 platforms when it shouldn't. Try testing it on `golang1.20` instead of 1.21 and let me know, because that's what I was observing in my tests (and explains why we never caught this issue before now)

File: go/parquet/internal/utils/clib.go (hunk 5 above)
Comment (zeroshade) [reply go/parquet/internal/utils/clib.go:30]: this exists *purely* to test the assembly versions I provided. 

The issue is that the C implementation I'm using to generate the assembly makes calls to memset and memcpy, but C's calling conventions are different than Go's. So in the assembly when it calls memset/memcpy I replaced those CALL instructions to call these replacement versions (because I can't call out to libc from inside of Go like that, no guarantee that the lib is loaded). Which are essentially just ported versions of the C memcpy/memset to ensure that the Calling conventions and argument handling are the same. 

The underscore prefix there ensures that the methods are not exported from the package, so I'm only using these for `clib_test.go` in order to sanity check the assembly methods.

Comment (pitrou) [reply go/parquet/internal/utils/clib.go:30]: Yuck, is there a way to avoid the calls to memset and memcpy?

**Comment by zeroshade** [comment]
@pitrou fair point, I'll update / write the README stuff for this today.

File: go/parquet/internal/utils/clib.go (hunk 5 above)
Comment (zeroshade) [reply go/parquet/internal/utils/clib.go:30]: Even the original C++ implementations (bpacking_simd128_generated.h) use memset and memcpy. There might be ways to avoid those calls but they'd likely be much less efficient. We also already use amd64 versions of these anyways, so it's good to have arm64 implementations.

Comment (pitrou) [reply go/parquet/internal/utils/clib.go:30]: By the looks of it, the calls to memcpy/memset could easily be replaced by the equivalent `for` loop. Given the size is small and constant, I don't think calling a generic version of memcpy/memset would be a significant win.

Comment (zeroshade) [reply go/parquet/internal/utils/clib.go:30]: I'll give it a try

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 4 above)
Comment (cyb70289) [reply go/parquet/internal/bmi/bmi_arm64.go:26]: This is strange. I tested earlier golang versions. Also tried x/sys/cpu v0.5.0 (used by arrow) and latest 0.12.0. All tests are okay.
Curious what might be the reason. If possible, can your share info about the test env? E.g.. tested in arm64 baremetal or virtual machine, linux kernel version, output of "lscpu". Thanks.

File: go/parquet/internal/utils/_lib/README.md [hunk 6]
```diff
@@ -0,0 +1,148 @@
...
+  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+  KIND, either express or implied.  See the License for the
+  specific language governing permissions and limitations
+  under the License.
+-->
+
+# SIMD Bit Packing Implementation
+
+Go doesn't have any SIMD intrinsics so for some low-level optimizations we can 
+leverage auto-vectorization and the fact that Go lets you specify the body of a
```
Comment (pitrou) [inline go/parquet/internal/utils/_lib/README.md:23]:
```suggestion
leverage auto-vectorization by C++ compilers and the fact that Go lets you specify the body of a
```

File: go/parquet/internal/utils/_lib/README.md [hunk 7]
```diff
@@ -0,0 +1,148 @@
...
+* x86-64 assembly uses `#` for comments while arm64 assembly uses `//` for comments.
+  `c2goasm` assumes `#` for comments and splits lines based on them. For most lines
+  this isn't an issue, but for any constants this is important and will need to have
+  the comment character converted from `//` to `#`.
+* A `word` for x86-64 is 16 bits, a `double` word is 32 bits, and a `quad` is 64 bits.
+  For arm64, a `word` is 32 bits. This means that constants in the assembly need to be
+  modified. `c2goasm` and `asm2plan9s` expect the x86-64 meaning for the sizes, so
+  usage of `.word ######` needs to be converted to `.long #####` before running
+  `c2goasm`
+  * Because of this change in bits, `MOVQ` instructions will also be converted to
```
Comment (pitrou) [inline go/parquet/internal/utils/_lib/README.md:68]:
```suggestion
* Because of this change in bits, `MOVQ` instructions will also be converted to 
```

**Comment by pitrou** [comment]
I just read the README. This is horrifying :-o

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 4 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bmi_arm64.go:26]: It was a virtual machine launched via EC2 on AWS as a Debian 12 arm64 machine. I'll launch a new one when i get a chance and paste the output of lscpu here later on

**Comment by tschaub** [comment]
I just came across this and confirmed that it fixes the panic I found in #37968.

File: go/parquet/internal/utils/_lib/README.md [hunk 8]
```diff
@@ -0,0 +1,148 @@
...
+
+Unfortunately there are some caveats for arm64. c2goasm / asm2plan9s doesn't fully
+support arm64 correctly. However, proper assembly can be created with some slight
+manipulation of the result.
+
+The Makefile has the NEON flags for compiling the assembly by using 
+`make _lib/bit_packing_neon.s` and `make _lib/unpack_bool_neon.s` to generate the
+raw assembly sources. 
+
+Before calling `c2goasm` there's a few things that need to be modified in the assembly:
```
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/utils/_lib/README.md:57]: I did it with a series of regex's but until i write some automation, yes they are done by hand.

File: go/parquet/internal/bmi/bmi_arm64.go (hunk 4 above)
Comment (zeroshade) [reply go/parquet/internal/bmi/bmi_arm64.go:26]: @cyb70289 Here is the output of `lscpu` on the AWS EC2 instance that I've been using for testing:

```shell
admin@ip-172-31-78-97:~/arrow/go/parquet/internal/utils$ lscpu
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 1
  On-line CPU(s) list:  0
Vendor ID:              ARM
  Model name:           Neoverse-N1
    Model:              1
    Thread(s) per core: 1
    Core(s) per socket: 1
    Socket(s):          1
    Stepping:           r3p1
    BogoMIPS:           243.75
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
Caches (sum of all):
  L1d:                  64 KiB (1 instance)
  L1i:                  64 KiB (1 instance)
  L2:                   1 MiB (1 instance)
  L3:                   32 MiB (1 instance)
NUMA:
  NUMA node(s):         1
  NUMA node0 CPU(s):    0
Vulnerabilities:
  Gather data sampling: Not affected
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Mmio stale data:      Not affected
  Retbleed:             Not affected
  Spec rstack overflow: Not affected
  Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Mitigation; CSV2, BHB
  Srbds:                Not affected
  Tsx async abort:      Not affected
```

File: go/parquet/internal/utils/clib.go (hunk 5 above)
Comment (zeroshade) [reply go/parquet/internal/utils/clib.go]: Latest update has removed the `memset`/`memcpy` and replaced them with simple fixed size loops. My local testing showed all the tests passing, so assuming the CI is happy with things then we should be good here if you're happy with the results @pitrou. Let me know please when you get a chance.

File: go/parquet/internal/utils/_lib/README.md (hunk 8 above)
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/utils/_lib/README.md:57]: I've added a `script.sed` file which brings together *some* of the modifications to the assembly on the result of `c2goasm`, should make generating the file easier in the future if it comes to it.

**Comment by zeroshade** [comment]
@tschaub Can you please try testing with the latest version of this branch/PR and confirm for me that everything is still working on your end and there's no performance degradation vs the previous fix? I agree with @pitrou's statement that it's unlikely the generic `memset`/`memcpy` were giving us much of a benefit over a simple fixed length loop, but it'd be nice to confirm that there's no negative effects

**Comment by tschaub** [comment]
@zeroshade - I only tested a couple different cases, but I don't see any negative effect with the latest changes.

Here are some benchmarks transforming a `small.parquet` file (2400 rows, 20 physical columns, uncompressed):
```
Benchmark 1: ./gpq-noasm convert small.parquet small-noasm.parquet
  Time (mean ± σ):      72.2 ms ±   2.2 ms    [User: 103.9 ms, System: 25.2 ms]
  Range (min … max):    68.0 ms …  77.4 ms    41 runs
 
Benchmark 2: ./gpq-before convert small.parquet small-before.parquet
  Time (mean ± σ):      68.6 ms ±   2.2 ms    [User: 99.9 ms, System: 25.1 ms]
  Range (min … max):    63.1 ms …  74.9 ms    42 runs
 
Benchmark 3: ./gpq-after convert small.parquet small-after.parquet
  Time (mean ± σ):      68.5 ms ±   2.6 ms    [User: 99.0 ms, System: 24.5 ms]
  Range (min … max):    63.5 ms …  73.5 ms    40 runs
 
Summary
  ./gpq-after convert small.parquet small-after.parquet ran
    1.00 ± 0.05 times faster than ./gpq-before convert small.parquet small-before.parquet
    1.05 ± 0.05 times faster than ./gpq-noasm convert small.parquet small-noasm.parquet
```

And here are some numbers from a `medium.parquet` file (162709 rows, 20 physical columns, uncompressed):
```
Benchmark 1: ./gpq-noasm convert medium.parquet medium-noasm.parquet
  Time (mean ± σ):     986.3 ms ±  12.3 ms    [User: 1456.6 ms, System: 281.5 ms]
  Range (min … max):   965.2 ms … 1007.7 ms    10 runs
 
Benchmark 2: ./gpq-before convert medium.parquet medium-before.parquet
  Time (mean ± σ):     878.9 ms ±   7.2 ms    [User: 1343.1 ms, System: 269.5 ms]
  Range (min … max):   865.4 ms … 888.1 ms    10 runs
 
Benchmark 3: ./gpq-after convert medium.parquet medium-after.parquet
  Time (mean ± σ):     879.1 ms ±   9.7 ms    [User: 1341.6 ms, System: 268.6 ms]
  Range (min … max):   858.7 ms … 891.8 ms    10 runs
 
Summary
  ./gpq-before convert medium.parquet medium-before.parquet ran
    1.00 ± 0.01 times faster than ./gpq-after convert medium.parquet medium-after.parquet
    1.12 ± 0.02 times faster than ./gpq-noasm convert medium.parquet medium-noasm.parquet
```

So no significant difference in those between the before (c9693c5f9b33) and after (9d4c29b390a2) cases.  The other case is a build with `-tags noasm`.

File: go/parquet/internal/utils/clib_amd64.s [hunk 9]
```diff
@@ -44,6 +44,15 @@ MEMCPY_BYTE_DONE:
 	POPQ R8
 	RET
 
+// func _ClibMemcpy(dst, src unsafe.Pointer, n uint) unsafe.Pointer
+TEXT ·_ClibMemcpy(SB), NOSPLIT|NOFRAME, $16-24
```
Comment (pitrou) [inline go/parquet/internal/utils/clib_amd64.s:48]: Hmm, so is this file still useful?

**Review by pitrou — COMMENTED** [review]
Mostly LGTM.

**Comment by zeroshade** [comment]
Thanks for checking @tschaub! looks great

**Review by pitrou — APPROVED** [review]
LGTM, but it would be nice to have @cyb70289 's approval as wel

**Comment by zeroshade** [comment]
Thanks @pitrou I'll hold off on merging till the end of the week to give @cyb70289 a chance to approve

**Review by cyb70289 — APPROVED** [review]
LGTM, thanks @zeroshade !
