### PR TITLE
GH-36913: [C++] Skip empty buffer concatenation to fix UBSan error

### LINKED ISSUE #36913: [C++] ConcatenateBuffers triggers a UBSan error when called with an empty buffer
### Describe the bug, including details regarding any error messages, version, and platform.

If `buffer->data()` is `nullptr` [here](https://github.com/apache/arrow/blob/main/cpp/src/arrow/buffer.cc#L216), `ConcatenateBuffers` calls `std::memcpy` with `nullptr` for the `src` argument, which is [undefined behavior](https://en.cppreference.com/w/cpp/string/byte/memcpy):
> If either dest or src is an [invalid or null pointer](https://en.cppreference.com/w/cpp/language/pointer#Pointers), the behavior is undefined, even if count is zero.

The simplest fix is probably to skip the `std::memcpy` call if the buffer has zero length.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by sfc-gh-ebrossard**
### Rationale for this change

This is a trivial fix for a UBSan error in calls to `ConcatenateBuffers` with an empty buffer that has a null data pointer.

### What changes are included in this PR?

Conditional call to `std::memcpy` based on whether the buffer's length is 0.

### Are these changes tested?

Test added in buffer_test.cc.

### Are there any user-facing changes?

No
* Closes: #36913

### CODE REVIEW

**Comment by pitrou** [comment]
Hi @sfc-gh-ebrossard and thank you for your contribution.

> Please let me know if you'd like a test; I can add one to `buffer_test.cc`. I'm not sure if there are automated UBSan runs for Arrow unit tests.

Yes and yes. You'll find a "AMD64 Ubuntu 22.04 C++ ASAN UBSAN" CI job below.

File: cpp/src/arrow/buffer_test.cc [hunk 1]
```diff
@@ -1014,4 +1014,12 @@ TYPED_TEST(TypedTestBuffer, ResizeOOM) {
 #endif
 }
 
+TEST(TestBufferConcatenation, EmptyBuffer) {
+  const std::string contents = "hello, world";
```
Comment (pitrou) [inline cpp/src/arrow/buffer_test.cc:1018]: Add a comment explaining the test motivation here
```suggestion
  // GH-36913: UB shouldn't be triggered by copying from a null pointer
  const std::string contents = "hello, world";
```

**Review by pitrou — APPROVED** [review]
Thanks a lot. LGTM except for one suggestion, see below.

**Comment by pitrou** [comment]
The Windows 2019 build failure is unrelated and appears on other PRs.
