### PR TITLE
GH-38117: [C++][Parquet] Change DictEncoder dtor checking to warning log

### LINKED ISSUE #38117: [C++][Parquet] Debug Build might fail in `DictEncoder` dtor checking
### Describe the enhancement requested

This is the case described in https://github.com/apache/arrow/pull/35520 . But I didn't find it when previous meet the bug because I just use release build.

```c++
  void Close() override {
    if (!closed_) {
      closed_ = true;
      CheckRowsWritten();

      // Avoid invalid state if ColumnWriter::Close() throws internally.
      auto column_writers = std::move(column_writers_);
      for (size_t i = 0; i < column_writers.size(); i++) {
        if (column_writers[i]) {
          total_bytes_written_ += column_writers[i]->Close();
          total_compressed_bytes_written_ +=
              column_writers[i]->total_compressed_bytes_written();
        }
      }

      // Ensures all columns have been written
      metadata_->set_num_rows(num_rows_);
      metadata_->Finish(total_bytes_written_, row_group_ordinal_);
    }
  }
```

When close file with 10 columns, assume column writer 2 has exception on `Close`, it throw an exception. and the third one is a `DictEncoder`, so it would `DCHECK` failed:

```c++
  ~DictEncoderImpl() override { DCHECK(buffered_indices_.empty()); }
```

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

This is a minor change, just change `DCHECK` to warning log.

### What changes are included in this PR?

change `DCHECK` to warning log.

### Are these changes tested?

no, I don't know how to test this, any idea is welcome.

### Are there any user-facing changes?

no

* Closes: #38117

### CODE REVIEW

File: cpp/src/parquet/encoding.cc [hunk 1]
```diff
@@ -442,7 +442,13 @@ class DictEncoderImpl : public EncoderImpl, virtual public DictEncoder<DType> {
         dict_encoded_size_(0),
         memo_table_(pool, kInitialHashTableSize) {}
 
-  ~DictEncoderImpl() override { DCHECK(buffered_indices_.empty()); }
+  ~DictEncoderImpl() override {
+#ifndef NDEBUG
+    if (!buffered_indices_.empty()) {
+      ARROW_LOG(WARNING) << "DictEncoderImpl destroyed without flushing or closing";
```
Comment (wgtmac) [inline cpp/src/parquet/encoding.cc:448]:
```suggestion
      ARROW_LOG(WARNING) << "DictEncoderImpl is destroyed without flushing or closing";
```

Comment (wgtmac) [reply cpp/src/parquet/encoding.cc:448]: IIUC, the behavior has changed under debug mode, which calls abort() in the past.

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:448]: The reason is described here: https://github.com/apache/arrow/issues/38117

**Comment by pitrou** [comment]
I think we can just remove the check/warning. It does not seem very useful, and other encoders don't have it.

**Comment by mapleFU** [comment]
@pitrou removed now.

**Comment by pitrou** [comment]
Oops, I should have changed the PR title before merging...

**Comment by mapleFU** [comment]
My bad... So sorry for fotget changing the title.
