### PR TITLE
GH-14947 [R] Compatibility with dplyr 1.1.0

### LINKED ISSUE #14947: [R] Compatibility of arrow with dplyr 1.1.0
### Describe the bug, including details regarding any error messages, version, and platform.

dplyr 1.1.0 is planned for January 27 and includes breaking/behaviour changes that need to be addressed in arrow:

- `n_distinct()` no longer accepts zero arguments
- `union_all()` now requires compatible arguments
- `distinct()` now returns cols in supplied order
- `across()` now requires an argument
- A message generated in dplyr is compared to a hard-coded string in tests
- `semi_join()` and `anti_join()` are stricter with unexpected arguments. Causes an issue in tests with `keep`.
- `slice_min()` and `slice_max()` now require `order_by`

We plan to release on January 27. A pre-emptive release to fix the above would be helpful.

### Component(s)

R

### PR DESCRIPTION
**Pull request by lionel-**
Each commit in this PR fixes a breaking/behaviour change described in #14947.

I could not build the dev version of arrow so this is only tested against the CRAN version. Also there might be changes introduced since the last release that require compatibility adjustments. Could someone pick this up from here please?

Closes #14947.
* Closes: #14947

### CODE REVIEW

File: r/tests/testthat/test-dplyr-summarize.R [hunk 1]
```diff
@@ -298,12 +298,16 @@ test_that("n_distinct() on dataset", {
...
+  # Error now generated by dplyr (https://github.com/tidyverse/dplyr/pull/6543)
+  expect_snapshot(
+    error = TRUE,
+    compare_dplyr_binding(
+      .input %>%
+        summarize(distinct = n_distinct()) %>%
+        collect(),
+      tbl,
+      warning = "0 arguments"
+    )
```
Comment (paleolimbot) [inline r/tests/testthat/test-dplyr-summarize.R:310]:
```suggestion
  expect_snapshot(
    error = TRUE,
    tbl %>%
      summarize(distinct = n_distinct())
  )
```

File: r/tests/testthat/test-dataset.R [hunk 2]
```diff
@@ -586,16 +586,25 @@ test_that("UnionDataset can merge schemas", {
...
 
   # without unifying schemas, takes the first schema and discards any columns
   # in the second which aren't in the first
   ds <- open_dataset(list(ds1, ds2), unify_schemas = FALSE)
-  expected <- as_tibble(sub_df1) %>%
-    union_all(sub_df2 %>% as_tibble() %>% select(x))
+  expected <- union_all_common(
+    as_tibble(sub_df1),
+    as_tibble(sub_df2) %>% select(x)
+)
```
Comment (paleolimbot) [inline r/tests/testthat/test-dataset.R:607]:
```suggestion
  )
```

File: r/tests/testthat/test-dplyr-summarize.R (hunk 1 above)
Comment (paleolimbot) [reply r/tests/testthat/test-dplyr-summarize.R:310]: (A little more direct than going through `compare_dplyr_binding()`, which might evaluate the dplyr version and error for that first)

**Review by paleolimbot — COMMENTED** [review]
Thank you! Just a few suggestions and I approved the CI run, which may complain about something I didn't see here 🙂

**Comment by thisisnic** [comment]
> I could not build the dev version of arrow 

I don't suppose you'd mind elaborating more on this @lionel- ?  Only because we're looking at making the contribution process for Arrow a bit smoother.

**Review by thisisnic — APPROVED** [review]
LGTM, thanks @lionel- and @paleolimbot!
