### PR TITLE
GH-39965: [C++] DatasetWriter avoid creating zero-sized batch when `max_rows_per_file` enabled

### LINKED ISSUE #39965: [Python][Parquet] Empty row groups left behind after hitting max_rows_per_file in `ds.write_dataset`
### Describe the bug, including details regarding any error messages, version, and platform.

The `pyarrow.dataset.write_dataset` function leaves an empty row_group behind in the the parquet file after the writer hits the limit of max_rows_per_file. See reproducible example below:

```python
import pyarrow.dataset as ds
import pyarrow.parquet as pq
ds.write_dataset(data, "test_dataset", max_rows_per_file=1024*32, max_rows_per_group=1024 * 16, min_rows_per_group=8*1024, format='parquet')
metadata = pq.read_metadata("test_dataset/part-0.parquet")
```

```python
for i in range(metadata.num_row_groups):
    print(metadata.row_group(i))

<pyarrow._parquet.RowGroupMetaData object at 0x7f92b5168180>
  num_columns: 1
  num_rows: 16384
  total_byte_size: 61
<pyarrow._parquet.RowGroupMetaData object at 0x7f92b5185bc0>
  num_columns: 1
  num_rows: 16384
  total_byte_size: 61
<pyarrow._parquet.RowGroupMetaData object at 0x7f92b5185bc0>
  num_columns: 1
  num_rows: 0
  total_byte_size: 14
```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

`DatasetWriter` might create empty `RecordBatch` when `max_rows_per_file` enabled. This is because `NextWritableChunk` might return a zero-sized batch when the file exactly contains the dest data.

### What changes are included in this PR?

Check batch-size == 0 when append to file queue

### Are these changes tested?

Yes

### Are there any user-facing changes?

User can avoid zero-sized row-group/batch.

* Closes: #39965

### CODE REVIEW

**Comment by mapleFU** [comment]
cc @bkietz @kou

File: cpp/src/arrow/dataset/dataset_writer.cc [hunk 1]
```diff
@@ -610,31 +610,34 @@ class DatasetWriter::DatasetWriterImpl {
...
-          writer_state_.rows_in_flight_throttle.Acquire(next_chunk->num_rows());
-      if (!backpressure.is_finished()) {
-        EVENT_ON_CURRENT_SPAN("DatasetWriter::Backpressure::TooManyRowsQueued");
-        break;
-      }
-      if (will_open_file) {
-        backpressure = writer_state_.open_files_throttle.Acquire(1);
+      // GH-39965: `NextWritableChunk` may return empty batch if file reaches
+      // `max_rows_per_file`.
+      if (next_chunk->num_rows() > 0) {
```
Comment (mapleFU) [inline cpp/src/arrow/dataset/dataset_writer.cc:615]: This patch only add this check, other is indent change

Comment (mapleFU) [reply cpp/src/arrow/dataset/dataset_writer.cc:615]: ( This problem would happen when file already reaches `max_rows_per_file`, the `next_chunk` in this round would be 0, causing a zero-sized batch)

Comment (bkietz) [reply cpp/src/arrow/dataset/dataset_writer.cc:615]: Nit: I'd prefer to see this check as an independent branch rather than nesting more deeply
```suggestion
      if (next_chunk->num_rows() == 0) {
        // GH-39965: `NextWritableChunk` may return an empty batch to signal
        // that the current file has reached `max_rows_per_file` and should be
        // finished.
        batch = std::move(remainder);
        if (batch) {
          RETURN_NOT_OK(dir_queue->FinishCurrentFile());
        }
        continue;
      }
```

**Review by bkietz — CHANGES_REQUESTED** [review]

**Comment by mapleFU** [comment]
@bkietz comment resolved

**Comment by mapleFU** [comment]
Gentle ping @kou @bkietz for help...

File: cpp/src/arrow/dataset/dataset_writer_test.cc [hunk 2]
```diff
@@ -198,9 +198,7 @@ class DatasetWriterTestFixture : public testing::Test {
       int num_batches = 0;
       AssertBatchesEqual(*MakeBatch(expected_file.start, expected_file.num_rows),
                          *ReadAsBatch(written_file->data, &num_batches));
-      if (check_num_record_batches) {
```
Comment (kou) [inline cpp/src/arrow/dataset/dataset_writer_test.cc:201]: Can we remove `bool check_num_record_batches = true` argument?

**Review by kou — APPROVED** [review]
+1

File: cpp/src/arrow/dataset/dataset_writer_test.cc (hunk 2 above)
Comment (mapleFU) [reply cpp/src/arrow/dataset/dataset_writer_test.cc:201]: Sure, this is added in my previous patch https://github.com/apache/arrow/pull/38885 . Here if not passing `check_num_record_batches = false`, the check would failed because zero-sized batch.

In this patch, it would not be produced, so I can remove it

**Comment by mapleFU** [comment]
Will merge if no negative comment tommorrow.

File: cpp/src/arrow/dataset/dataset_writer_test.cc (hunk 2 above)
Comment (kou) [reply cpp/src/arrow/dataset/dataset_writer_test.cc:201]: OK. Please remove it before we merge this.
