### PR TITLE
GH-39051: [C++] Use Cast() instead of CastTo() for List Scalar in test

### LINKED ISSUE #39051: [C++] Add Compute Kernel for Casting from list_view to list
### Describe the enhancement requested

This is a sub-issue of the issue mentioned below.

* #35560 

As we can see in the parent issue, we can find tables organizing the related functions.

| file name         | code snippet                                                                               |
|-------------------|--------------------------------------------------------------------------------------------|
| scalar_test.cc    | `EXPECT_OK_AND_ASSIGN(auto cast_scalar, scalar.CastTo(to_type));`                          |
| scalar_test.cc    | `scalar.CastTo(to_type);`                                                                 |

> The functions require handling "Unsupported cast from list_view<item: int16> to list using function cast_list" error.

We need to implement casting from `list_view` to `list`. 

> [!WARNING]
> In this case, The additional casting function would vary depending on whether the `CheckListCast` or `CheckInvalidListCast` functions are called.

#### scalar_test.cc

Snippet to reproduce

```diff
template <typename ScalarType>
void CheckListCast(const ScalarType& scalar, const std::shared_ptr<DataType>& to_type) {
- EXPECT_OK_AND_ASSIGN(auto cast_scalar, scalar.CastTo(to_type));
- ASSERT_OK(cast_scalar->ValidateFull());
- ASSERT_EQ(*cast_scalar->type, *to_type);
+ EXPECT_OK_AND_ASSIGN(auto cast_scalar, Cast(scalar, to_type));
+ ASSERT_OK(cast_scalar.scalar()->ValidateFull());
+ ASSERT_EQ(*cast_scalar.scalar()->type, *to_type);

- ASSERT_EQ(scalar.is_valid, cast_scalar->is_valid);
+ ASSERT_EQ(scalar.is_valid, cast_scalar.scalar()->is_valid);
  ASSERT_TRUE(scalar.is_valid);
  ASSERT_ARRAYS_EQUAL(*scalar.value,
-                     *checked_cast<const BaseListScalar&>(*cast_scalar).value);
+                     *checked_cast<const BaseListScalar&>(*cast_scalar.scalar()).value);
}

void CheckInvalidListCast(const Scalar& scalar, const std::shared_ptr<DataType>& to_type,
                          const std::string& expected_message) {
  EXPECT_RAISES_WITH_CODE_AND_MESSAGE_THAT(StatusCode::Invalid,
                                           ::testing::HasSubstr(expected_message),
-                                          scalar.CastTo(to_type));
+                                          Cast(scalar, to_type));
}
```

#### Sub-task

- [x] Support list_view to list
- [x] Support list_view to fixed_size_list
- [x] Fix CheckInvalidListCast for TestMapScalar

### Component(s)

C++

### PR DESCRIPTION
**Pull request by llama90**
### Rationale for this change

Remove legacy code

### What changes are included in this PR?

Replace the legacy scalar CastTo implementation for List Scalar in test.

### Are these changes tested?

Yes. It is passed by existing test cases.

### Are there any user-facing changes?

No.

* Closes: #39051

### CODE REVIEW

File: cpp/src/arrow/scalar_test.cc [hunk 1]
```diff
@@ -1077,21 +1077,38 @@ std::shared_ptr<DataType> MakeListType<FixedSizeListType>(
 
 template <typename ScalarType>
 void CheckListCast(const ScalarType& scalar, const std::shared_ptr<DataType>& to_type) {
-  EXPECT_OK_AND_ASSIGN(auto cast_scalar, scalar.CastTo(to_type));
-  ASSERT_OK(cast_scalar->ValidateFull());
-  ASSERT_EQ(*cast_scalar->type, *to_type);
+  EXPECT_OK_AND_ASSIGN(auto cast_scalar, Cast(scalar, to_type));
```
Comment (kou) [inline cpp/src/arrow/scalar_test.cc:1080]: How about using `cast_scalar_datum` for this variable? `cast_scalar.scalar()` is strange.

```suggestion
  EXPECT_OK_AND_ASSIGN(auto cast_scalar_datum, Cast(scalar, to_type));
  auto cast_scalar = cast_scalar_datum.scalar();
```

File: cpp/src/arrow/scalar_test.cc [hunk 2]
```diff
@@ -1077,21 +1077,38 @@ std::shared_ptr<DataType> MakeListType<FixedSizeListType>(
...
+}
+
+template <typename ScalarType>
+void CheckInvalidListCast(const ScalarType& scalar,
+                          const std::shared_ptr<DataType>& to_type, const StatusCode code,
                           const std::string& expected_message) {
-  EXPECT_RAISES_WITH_CODE_AND_MESSAGE_THAT(StatusCode::Invalid,
-                                           ::testing::HasSubstr(expected_message),
-                                           scalar.CastTo(to_type));
+  EXPECT_RAISES_WITH_CODE_AND_MESSAGE_THAT(code, ::testing::HasSubstr(expected_message),
```
Comment (kou) [inline cpp/src/arrow/scalar_test.cc:1110]: It's strange that `CheckInvalidListCast()` may not expect `StatusCode::Invalid`.
Can we use better function name?

File: cpp/src/arrow/scalar_test.cc (hunk 1 above)
Comment (llama90) [reply cpp/src/arrow/scalar_test.cc]: I changed it.

File: cpp/src/arrow/scalar_test.cc (hunk 2 above)
Comment (llama90) [reply cpp/src/arrow/scalar_test.cc:1111]: Yes. You are correct. In the current situation, as you mentioned, both `Invalid` and `TypeError` can occur. I think `CheckListCastError` or `VerifyListCastFailure` would be more appropriate. What do you think?

Comment (llama90) [reply cpp/src/arrow/scalar_test.cc]: @kou Hello. When you have free time, could you please review it? Thank you :)

File: cpp/src/arrow/scalar_test.cc [hunk 3]
```diff
@@ -1087,11 +1088,28 @@ void CheckListCast(const ScalarType& scalar, const std::shared_ptr<DataType>& to
...
+        StatusCode::TypeError,
+        "Size of FixedSizeList is not the same. input list: " + type->ToString() +
+            " output list: " + invalidCastType->ToString());
+  } else {
+    return std::make_tuple(
+        StatusCode::Invalid,
+        "ListType can only be casted to FixedSizeListType if the lists are all the "
+        "expected size.");
+  }
+}
```
Comment (kou) [inline cpp/src/arrow/scalar_test.cc:1105]: How about moving this code to `CheckListCastError()`?
Why do you want to split this function and `CheckListCastError()`?

File: cpp/src/arrow/scalar_test.cc (hunk 2 above)
Comment (kou) [reply cpp/src/arrow/scalar_test.cc]: Sorry! I reviewed this!

File: cpp/src/arrow/scalar_test.cc (hunk 3 above)
Comment (llama90) [reply cpp/src/arrow/scalar_test.cc:1105]: This function(`CheckListCastError`) called from two cases as `TEST(TestMapScalar, Cast)` and  `void TestCast()` for `TYPED_TEST(TestListLikeScalar, Cast)`. That's why I added the function to avoid code duplication.

Comment (kou) [reply cpp/src/arrow/scalar_test.cc:1105]: Both of them just pass the returned value of `GetExpectedError()` to `CheckListCastError()`.
I think that we don't need to split `GetExpectedError()` and `CheckListCastError()` (I think that we don't have code duplication without splitting to them):

```diff
diff --git a/cpp/src/arrow/scalar_test.cc b/cpp/src/arrow/scalar_test.cc
index 3170a00e34..fefa8b8b52 100644
--- a/cpp/src/arrow/scalar_test.cc
+++ b/cpp/src/arrow/scalar_test.cc
@@ -1088,26 +1088,23 @@ void CheckListCast(const ScalarType& scalar, const std::shared_ptr<DataType>& to
                       *checked_cast<const BaseListScalar&>(*cast_scalar).value);
 }
 
-std::tuple<StatusCode, std::string> GetExpectedError(
-    const std::shared_ptr<DataType>& type,
-    const std::shared_ptr<DataType>& invalidCastType) {
-  if (type->id() == Type::FIXED_SIZE_LIST) {
-    return std::make_tuple(
-        StatusCode::TypeError,
-        "Size of FixedSizeList is not the same. input list: " + type->ToString() +
-            " output list: " + invalidCastType->ToString());
-  } else {
-    return std::make_tuple(
-        StatusCode::Invalid,
-        "ListType can only be casted to FixedSizeListType if the lists are all the "
-        "expected size.");
-  }
-}
-
 template <typename ScalarType>
 void CheckListCastError(const ScalarType& scalar,
-                        const std::shared_ptr<DataType>& to_type, const StatusCode code,
-                        const std::string& expected_message) {
+                        const std::shared_ptr<DataType>& from_type,
+                        const std::shared_ptr<DataType>& to_type) {
+  StatusCode code;
+  std::string expected_message;
+  if (from_type->id() == Type::FIXED_SIZE_LIST) {
+    code = StatusCode::TypeError;
+    expected_message =
+        "Size of FixedSizeList is not the same. input list: " + from_type->ToString() +
+        " output list: " + to_type->ToString();
+  } else {
+    code = StatusCode::Invalid;
+    expected_message =
+        "ListType can only be casted to FixedSizeListType if the lists are all the "
+        "expected size.";
+  }
   EXPECT_RAISES_WITH_CODE_AND_MESSAGE_THAT(code, ::testing::HasSubstr(expected_message),
                                            Cast(scalar, to_type));
 }
@@ -1197,9 +1194,7 @@ class TestListLikeScalar : public ::testing::Test {
         scalar, fixed_size_list(value_->type(), static_cast<int32_t>(value_->length())));
 
     auto invalidCastType = fixed_size_list(value_->type(), 5);
-    auto [expectedCode, expectedMessage] = GetExpectedError(type_, invalidCastType);
-
-    CheckListCastError(scalar, invalidCastType, expectedCode, expectedMessage);
+    CheckListCastError(scalar, type_, invalidCastType);
   }
 
  protected:
@@ -1257,9 +1252,7 @@ TEST(TestMapScalar, Cast) {
   CheckListCast(scalar, fixed_size_list(key_value_type, 2));
 
   auto invalidCastType = fixed_size_list(key_value_type, 5);
-  auto [expectedCode, expectedMessage] = GetExpectedError(scalar.type, invalidCastType);
-
-  CheckListCastError(scalar, invalidCastType, expectedCode, expectedMessage);
+  CheckListCastError(scalar, scalar.type, invalidCastType);
 }
 
 TEST(TestStructScalar, FieldAccess) {
```

File: cpp/src/arrow/scalar_test.cc [hunk 4]
```diff
@@ -1178,10 +1196,10 @@ class TestListLikeScalar : public ::testing::Test {
     CheckListCast(
         scalar, fixed_size_list(value_->type(), static_cast<int32_t>(value_->length())));
 
-    CheckInvalidListCast(scalar, fixed_size_list(value_->type(), 5),
-                         "Cannot cast " + scalar.type->ToString() + " of length " +
-                             std::to_string(value_->length()) +
-                             " to fixed size list of length 5");
+    auto invalidCastType = fixed_size_list(value_->type(), 5);
```
Comment (kou) [inline cpp/src/arrow/scalar_test.cc:1199]: Could you use `snake_case`?

```suggestion
    auto invalid_cast_type = fixed_size_list(value_->type(), 5);
```

File: cpp/src/arrow/scalar_test.cc [hunk 5]
```diff
@@ -1238,10 +1256,10 @@ TEST(TestMapScalar, Cast) {
   CheckListCast(scalar, large_list(key_value_type));
   CheckListCast(scalar, fixed_size_list(key_value_type, 2));
 
-  CheckInvalidListCast(scalar, fixed_size_list(key_value_type, 5),
-                       "Cannot cast " + scalar.type->ToString() + " of length " +
-                           std::to_string(value->length()) +
-                           " to fixed size list of length 5");
+  auto invalidCastType = fixed_size_list(key_value_type, 5);
```
Comment (kou) [inline cpp/src/arrow/scalar_test.cc:1259]: ditto.

File: cpp/src/arrow/scalar_test.cc (hunk 3 above)
Comment (llama90) [reply cpp/src/arrow/scalar_test.cc]: You are right. I changed.

File: cpp/src/arrow/scalar_test.cc (hunk 4 above)
Comment (llama90) [reply cpp/src/arrow/scalar_test.cc]: Fixed it.

File: cpp/src/arrow/scalar_test.cc (hunk 5 above)
Comment (llama90) [reply cpp/src/arrow/scalar_test.cc]: too.

File: cpp/src/arrow/scalar_test.cc (hunk 3 above)
Comment (kou) [reply cpp/src/arrow/scalar_test.cc]: Ah, sorry. Can we use `Scalar::type` instead of passing `from_type`?

```diff
diff --git a/cpp/src/arrow/scalar_test.cc b/cpp/src/arrow/scalar_test.cc
index 654e0510c6..8592765adc 100644
--- a/cpp/src/arrow/scalar_test.cc
+++ b/cpp/src/arrow/scalar_test.cc
@@ -1090,14 +1090,13 @@ void CheckListCast(const ScalarType& scalar, const std::shared_ptr<DataType>& to
 
 template <typename ScalarType>
 void CheckListCastError(const ScalarType& scalar,
-                        const std::shared_ptr<DataType>& from_type,
                         const std::shared_ptr<DataType>& to_type) {
   StatusCode code;
   std::string expected_message;
-  if (from_type->id() == Type::FIXED_SIZE_LIST) {
+  if (scalar.type->id() == Type::FIXED_SIZE_LIST) {
     code = StatusCode::TypeError;
     expected_message =
-        "Size of FixedSizeList is not the same. input list: " + from_type->ToString() +
+        "Size of FixedSizeList is not the same. input list: " + scalar.type->ToString() +
         " output list: " + to_type->ToString();
   } else {
     code = StatusCode::Invalid;
@@ -1195,7 +1194,7 @@ class TestListLikeScalar : public ::testing::Test {
         scalar, fixed_size_list(value_->type(), static_cast<int32_t>(value_->length())));
 
     auto invalid_cast_type = fixed_size_list(value_->type(), 5);
-    CheckListCastError(scalar, type_, invalid_cast_type);
+    CheckListCastError(scalar, invalid_cast_type);
   }
 
  protected:
@@ -1253,7 +1252,7 @@ TEST(TestMapScalar, Cast) {
   CheckListCast(scalar, fixed_size_list(key_value_type, 2));
 
   auto invalid_cast_type = fixed_size_list(key_value_type, 5);
-  CheckListCastError(scalar, scalar.type, invalid_cast_type);
+  CheckListCastError(scalar, invalid_cast_type);
 }
 
 TEST(TestStructScalar, FieldAccess) {
```

Comment (llama90) [reply cpp/src/arrow/scalar_test.cc]: Yes, that argument is redundant. Removed it.

**Review by kou — APPROVED** [review]
+1
