### PR TITLE
GH-39322: [C++] Forward arguments to ExceptionToStatus all the way to Status::FromArgs

### LINKED ISSUE #39322: [C++][FS] Forward arguments to ExceptionToStatus
### Describe the enhancement requested

`Status` can be constructed with multiple arguments and then it can take care of the conversion to string of each argument and concatenation. We should forward arguments of `ExceptionToStatus` to `Status::IOError` to simplify all the calls to `ExceptionToStatus`.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

This simplifies the creation of long error messages and leads to the use of a string builder to construct the error message.

### What changes are included in this PR?

 - std::forward in ExceptionToStatus
 - A few nitpicky changes
 - Simplification of the error message text
 - Moving the signature of `CheckIfHierarchicalNamespaceIsEnabled` to `azurefs_internal.h` to reduce the size of `azurefs.h` -- implementation remains in `azurefs.cc`

### Are these changes tested?

Yes. By existing tests.
* Closes: #39322

### CODE REVIEW

**Comment by felipecrv** [comment]
@Tom-Newton @kou

File: cpp/src/arrow/filesystem/azurefs.h [hunk 1]
```diff
@@ -21,6 +21,7 @@
 #include <string>
 #include <vector>
 
+#include "arrow/filesystem/azurefs_internal.h"
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/azurefs.h:24]: Is this a mistake? We should not include an internal header in a public header.

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 2]
```diff
@@ -571,15 +581,14 @@ class ObjectInputFile final : public io::RandomAccessFile {
   std::shared_ptr<const KeyValueMetadata> metadata_;
 };
 
-Status CreateEmptyBlockBlob(std::shared_ptr<Blobs::BlockBlobClient> block_blob_client) {
+Status CreateEmptyBlockBlob(Blobs::BlockBlobClient& block_blob_client) {
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/azurefs.cc:584]: If not const, can we pass it as pointer?
```suggestion
Status CreateEmptyBlockBlob(Blobs::BlockBlobClient* block_blob_client) {
```

**Review by pitrou — COMMENTED** [review]
Neat improvement.

File: cpp/src/arrow/filesystem/azurefs.h (hunk 1 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.h:24]: It's a mistake! Fixing.

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 2 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:584]: I can make it const. Pushing a fix.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
It seems you need to fix or circumvent the linting failure.

**Comment by felipecrv** [comment]
> It seems you need to fix or circumvent the linting failure.

Trying something! 🤞
