### PR TITLE
GH-14876: [Go] Handling Crashes in C Data interface

### LINKED ISSUE #14876: [Go] Address Crashes for empty C Data arrays with nil buffers
### Describe the bug, including details regarding any error messages, version, and platform.

Following up from #14805: Go's `cdata` package needs to address handling nil data buffers for 0 length empty arrays.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by zeroshade**
* Closes: #14876

### CODE REVIEW

File: go/arrow/cdata/cdata.go [hunk 1]
```diff
@@ -583,7 +597,19 @@ func (imp *cimporter) importFixedSizePrimitive() error {
 		}
 		values = imp.importBitsBuffer(1)
 	}
-	imp.data = array.NewData(imp.dt, int(imp.arr.length), []*memory.Buffer{nulls, values}, nil, int(imp.arr.null_count), int(imp.arr.offset))
+
+	var dict *array.Data
+	if dt, ok := imp.dt.(*arrow.DictionaryType); ok {
```
Comment (pitrou) [inline go/arrow/cdata/cdata.go:602]: Sorry, I don't really read Go, but what happens if `ok` is false here?

File: go/arrow/cdata/cdata.go [hunk 2]
```diff
@@ -613,6 +639,12 @@ func (imp *cimporter) checkNumBuffers(n int64) error {
 func (imp *cimporter) importBuffer(bufferID int, sz int64) *memory.Buffer {
 	// this is not a copy, we're just having a slice which points at the data
 	// it's still owned by the C.ArrowArray object and its backing C++ object.
+	if imp.cbuffers[bufferID] == nil {
+		if sz != 0 {
+			panic("invalid buffer")
```
Comment (pitrou) [inline go/arrow/cdata/cdata.go:644]: "panic" bubbles a regular catchable error, or it's a controlled crash?

File: go/arrow/cdata/cdata_exports.go [hunk 3]
```diff
@@ -353,7 +366,7 @@ func exportArray(arr arrow.Array, out *CArrowArray, outSchema *CArrowSchema) {
 		buffers := allocateBufferPtrArr(len(arr.Data().Buffers()))
 		for i := range arr.Data().Buffers() {
 			buf := arr.Data().Buffers()[i]
-			if buf == nil {
+			if buf == nil || buf.Len() == 0 {
```
Comment (pitrou) [inline go/arrow/cdata/cdata_exports.go:369]: This doesn't seem mandatory either.

File: go/arrow/cdata/test/test_export_to_cgo.py [hunk 4]
```diff
@@ -161,6 +162,73 @@ def test_batch_roundtrip(self):
...
+            b.validate(full=True)
+            assert a.to_pylist() == b.to_pylist()
+            assert a.type == b.type
+            del a
+            del b
+    return test
+
 
 if __name__ == '__main__':
+    for typ in _test_pyarrow_types:
```
Comment (pitrou) [inline go/arrow/cdata/test/test_export_to_cgo.py:230]: You don't have to do this manually, you can use a sub-test instead:
https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests

File: go/arrow/cdata/cdata.go (hunk 1 above)
Comment (zeroshade) [reply go/arrow/cdata/cdata.go:602]: if `ok` is false here, `dict` remains `nil` and we just construct the `ArrayData` object without a dictionary as normal.

File: go/arrow/cdata/cdata.go (hunk 2 above)
Comment (zeroshade) [reply go/arrow/cdata/cdata.go:644]: `panic` *can* be caught and handled via `defer` and `recover`, otherwise it will be a controlled crash with a stack trace (unless debug info was stripped when building).

File: go/arrow/cdata/cdata_exports.go (hunk 3 above)
Comment (zeroshade) [reply go/arrow/cdata/cdata_exports.go:369]: The reason for this is line 374 below. In the case where `buf.Len() == 0` there is no allocated data to grab a pointer to via `&buf.Bytes()[0]` and you end up panic'ing with an error of attempting to get index 0 of a 0 length slice. Thus if we create an empty array, it's better to just use a nil pointer.

The alternative here would be to use `&buf.Buf()[0]` instead, which points at the reserved bytes (since creating a new buffer will, by default, automatically reserve 64 bytes if it wasn't expanded) but I thought it better to not force us to keep that memory around for a 0 length array.

File: go/arrow/cdata/test/test_export_to_cgo.py (hunk 4 above)
Comment (zeroshade) [reply go/arrow/cdata/test/test_export_to_cgo.py:230]: Ah nice! I'll update this to use that. thanks!

File: go/arrow/cdata/cdata.go (hunk 2 above)
Comment (pitrou) [reply go/arrow/cdata/cdata.go:644]: Can't you return a regular error then?

Comment (zeroshade) [reply go/arrow/cdata/cdata.go]: sure, had to propagate the error through to the callers since this method previously didn't return an error. latest commit updates this with the error instead of panic.

File: go/arrow/cdata/cdata_exports.go (hunk 3 above)
Comment (pitrou) [reply go/arrow/cdata/cdata_exports.go:369]: Sounds ok to me.
