### PR TITLE
GH-38964: [C++] Fix spelling (compute)

### LINKED ISSUE #38964: [C++][Compute] Spelling errors identified by check-spelling
### Describe the bug, including details regarding any error messages, version, and platform.

The [check-spelling action](https://github.com/marketplace/actions/check-spelling) enabled me to identify some misspellings...

The misspellings have been reported at https://github.com/jsoref/apache-arrow/actions/runs/7008141484/attempts/1#summary-19063787889

### Component(s)

C++

### PR DESCRIPTION
**Pull request by jsoref**
### What changes are included in this PR?

Spelling fixes to cpp/src/arrow/compute/

### Are there any user-facing changes?

* Closes: #38964

### CODE REVIEW

**Review by mapleFU — APPROVED** [review]
/cc @felipecrv

File: cpp/src/arrow/compute/kernels/vector_run_end_encode.cc [hunk 1]
```diff
@@ -30,11 +30,11 @@ namespace compute {
...
 namespace {
 
-struct RunEndEncondingState : public KernelState {
-  explicit RunEndEncondingState(std::shared_ptr<DataType> run_end_type)
+struct RunEndEncodingState : public KernelState {
+  explicit RunEndEncodingState(std::shared_ptr<DataType> run_end_type)
       : run_end_type{std::move(run_end_type)} {}
 
-  ~RunEndEncondingState() override = default;
+  ~RunEndEncodingState() override = default;
```
Comment (felipecrv) [inline cpp/src/arrow/compute/kernels/vector_run_end_encode.cc:37]: I wrote this 🤡

**Review by felipecrv — APPROVED** [review]
