### PR TITLE
GH-38282: [C++] Implement ReplaceString with the right type signature

### LINKED ISSUE #38282: [C++] Compilation errors when re2::StringPiece is different from std::string_view
### Describe the bug, including details regarding any error messages, version, and platform.

Compilation errors when `re2::StringPiece` is different from `std::string_view`.

> @felipecrv I am validating but this seems to make the `test-build-vcpkg-win` build to fail on the maintenance branch:
> 
> ```
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1970,1): error C2664: 'arrow::Status arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>::ReplaceString(re2::StringPiece,arrow::TypedBufferBuilder<uint8_t,void> *) const': cannot convert argument 1 from 'std::string_view' to 're2::StringPiece' (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1970,1): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(2066,10): message : see declaration of 'arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>::ReplaceString' (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1962): message : while compiling class template member function 'arrow::Status arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::LargeStringType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>>::Replace(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,const Replacer &,arrow::compute::ExecResult *)' [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
>           with
>           [
>               Replacer=arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>
>           ] (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx)
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1958): message : see reference to function template instantiation 'arrow::Status arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::LargeStringType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>>::Replace(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,const Replacer &,arrow::compute::ExecResult *)' being compiled [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
>           with
>           [
>               Replacer=arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>
>           ] (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx)
> D:\a\crossbow\crossbow\arrow\cpp\src\arrow/compute/kernels/codegen_internal.h(1249): message : see reference to class template instantiation 'arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::LargeStringType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>>' being compiled (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(2158): message : see reference to function template instantiation 'arrow::compute::ArrayKernelExec (__cdecl *arrow::compute::internal::GenerateVarBinaryToVarBinary<arrow::compute::internal::`anonymous-namespace'::ReplaceSubstringRegex,>(arrow::compute::internal::detail::GetTypeId))(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,arrow::compute::ExecResult *)' being compiled (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> ```
> 
> See: https://github.com/ursacomputing/crossbow/actions/runs/6533642461/job/17739225267

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

The type signature of `ReplaceString` should be identical when arrow is compiled with or without `ARROW_WITH_RE2`.

### What changes are included in this PR?

The right signature + delegating to the implementation that takes `re2::StringPiece`. The conversion should be a no-op when compiled and optimized.

### Are these changes tested?

By existing tests and CI checks.

* Closes: #38282

### CODE REVIEW

**Comment by felipecrv** [comment]
@raulcd

**Comment by raulcd** [comment]
@github-actions crossbow submit test-build-vcpkg-win

File: cpp/src/arrow/compute/kernels/scalar_string_ascii.cc [hunk 1]
```diff
@@ -2063,7 +2063,12 @@ struct RegexSubstringReplacer {
         regex_find_("(" + options_.pattern + ")", MakeRE2Options<Type>()),
         regex_replacement_(options_.pattern, MakeRE2Options<Type>()) {}
 
-  Status ReplaceString(re2::StringPiece s, TypedBufferBuilder<uint8_t>* builder) const {
+  Status ReplaceString(std::string_view s, TypedBufferBuilder<uint8_t>* builder) const {
+    re2::StringPiece piece(s.data(), s.length());
+    return ReplaceStringImpl(piece, builder);
+  }
+
+  Status ReplaceStringImpl(re2::StringPiece s, TypedBufferBuilder<uint8_t>* builder) const {
```
Comment (raulcd) [inline cpp/src/arrow/compute/kernels/scalar_string_ascii.cc:2071]: I think this should fix the lint error:
```suggestion
  Status ReplaceStringImpl(re2::StringPiece s,
                           TypedBufferBuilder<uint8_t>* builder) const {
```

Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/scalar_string_ascii.cc]: Fixed and pushed. I lost my pre-commit hook and missed this.

**Comment by raulcd** [comment]
oh! sorry, @pitrou I meant to add you as reviewer not assign it to you

**Review by pitrou — APPROVED** [review]
