### PR TITLE
GH-37562: [Ruby] Add support for table.each_raw_record.to_a

### LINKED ISSUE #37562: [Ruby] Add support for table.each_raw_record.to_a
### Describe the enhancement requested

Currently, the method Arrow::Table#each_raw_record is expected to work with .to_a without a block. However, when attempting to do so, it raises a LocalJumpError indicating "no block given".

## Steps to Reproduce
Use the Arrow::Table method to create a new table instance.
Call each_raw_record followed by to_a without providing a block.

## Expected
```ruby
> Arrow::Table.new(number: [1, 2, 3]).each_raw_record.to_a
=> [[1], [2], [3]]
```

## Actual
```ruby
> Arrow::Table.new(number: [1, 2, 3]).each_raw_record.to_a
(irb):3:in `each_raw_record': no block given (LocalJumpError)
        from (irb):3:in `<main>'                                                                                         
        from /Users/otegami/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'    
        from /Users/otegami/.rbenv/versions/3.2.0/bin/irb:25:in `load'                                                   
        from /Users/otegami/.rbenv/versions/3.2.0/bin/irb:25:in `<main>'
```

### Component(s)

Ruby

### PR DESCRIPTION
**Pull request by otegami**
### Rationale for this change

This change aligns the behavior of `each_raw_record` with standard Ruby practices by returning an enumerator when no block is provided

### What changes are included in this PR?

- Made `Arrow::Table#each_raw_record` and `Arrow::RecordBatch#each_raw_record` return Enumerator when it was called without block.
- Added related tests
- Resolved warnings related to duplicate test classes which were caused by #37137

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No

* Closes: #37562

### CODE REVIEW

File: ruby/red-arrow/test/each-raw-record/test-struct-array.rb
Comment (otegami) [inline ruby/red-arrow/test/each-raw-record/test-struct-array.rb:1]: In the following PR #37137, I missed the following warnings happened. So I fixed it in this PR.
```console
red-arrow % bundle exec env DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/tmp/local/lib $(rbenv which ruby) test/run-test.rb
/Users/otegami/dev/project/arrow/ruby/red-arrow/test/raw-records/test-struct-array.rb:518: warning: method redefined; discarding old build
/Users/otegami/dev/project/arrow/ruby/red-arrow/test/each-raw-record/test-struct-array.rb:658: warning: previous definition of build was here
/Users/otegami/dev/project/arrow/ruby/red-arrow/test/raw-records/test-struct-array.rb:526: warning: method redefined; discarding old build
/Users/otegami/dev/project/arrow/ruby/red-arrow/test/each-raw-record/test-struct-array.rb:666: warning: previous definition of build was here
```

File: ruby/red-arrow/ext/arrow/raw-records.cpp [hunk 1]
```diff
@@ -306,6 +306,10 @@ namespace red_arrow {
 
   VALUE
   record_batch_each_raw_record(VALUE rb_record_batch){
+    if (!rb_block_given_p()) {
+      return rb_funcall(rb_record_batch, rb_intern("to_enum"), 1, ID2SYM(rb_intern("each_raw_record")));
```
Comment (otegami) [inline ruby/red-arrow/ext/arrow/raw-records.cpp:310]: If there is a good way to return a Enumerator object, could you teach me?🙏

File: ruby/red-arrow/test/test-record-batch.rb [hunk 2]
```diff
@@ -178,5 +178,29 @@ def setup
                      @record_batch[[:c, "a", -1, 3..4]])
       end
     end
+
+    sub_test_case("#each_raw_record") do
```
Comment (otegami) [inline ruby/red-arrow/test/test-record-batch.rb:182]: I was uncertain about the appropriate location to add the following test cases. 
I added it here because `each_raw_record` is one of the methods for Arrow::Table or Arrow::RecordBatch.
- ruby/red-arrow/test/each-raw-record/*
- ruby/red-arrow/test/test-record-batch.rb

Comment (kou) [reply ruby/red-arrow/test/test-record-batch.rb:182]: We can always use no block version like this:

```diff
diff --git a/ruby/red-arrow/test/each-raw-record/test-basic-arrays.rb b/ruby/red-arrow/test/each-raw-record/test-basic-arrays.rb
index dbbbd79ee..05f0e90ef 100644
--- a/ruby/red-arrow/test/each-raw-record/test-basic-arrays.rb
+++ b/ruby/red-arrow/test/each-raw-record/test-basic-arrays.rb
@@ -22,12 +22,8 @@ module EachRawRecordBasicArraysTests
       [nil],
       [nil],
     ]
-    iterated_records = []
     target = build({column: :null}, records)
-    target.each_raw_record do |record|
-      iterated_records << record
-    end
-    assert_equal(records, iterated_records)
+    assert_equal(records, target.each_raw_record.to_a)
   end
 
   def test_boolean
```

Because a returned `Enumerator` uses with-block version.

File: ruby/red-arrow/ext/arrow/raw-records.cpp (hunk 1 above)
Comment (otegami) [reply ruby/red-arrow/ext/arrow/raw-records.cpp]: fix: [f59e5ff](https://github.com/apache/arrow/pull/37600/commits/f59e5ff942fda34fd7c7ed1b5edce7ace0732020)
Thanks. I tried to use `RETURN_SIZED_ENUMERATOR()`🙏

File: ruby/red-arrow/ext/arrow/raw-records.cpp [hunk 3]
```diff
@@ -306,6 +306,10 @@ namespace red_arrow {
 
   VALUE
   record_batch_each_raw_record(VALUE rb_record_batch){
```
[the remark this answers is not in the document]
Comment (otegami) [reply ruby/red-arrow/ext/arrow/raw-records.cpp]: fix: [781f547](https://github.com/apache/arrow/pull/37600/commits/781f547d449d59489721246963d507cd5f43fa9b)

File: ruby/red-arrow/test/test-record-batch.rb (hunk 2 above)
Comment (otegami) [reply ruby/red-arrow/test/test-record-batch.rb]: fix: [bc23b9c](https://github.com/apache/arrow/pull/37600/commits/bc23b9c8e3c91e09b4023b057294663919ff7dac)

I misunderstood that we explicitly had to call the 'each_raw_record' with a block because I didn't understand how Enumerable#to_a worked.

I will unify tests with raw_records and each_raw_record at the following issue.
- https://github.com/apache/arrow/issues/37563

**Comment by otegami** [comment]
@kou
Thank you for reviewing 🙏 I've fixed all the points you commented on.

File: ruby/red-arrow/ext/arrow/raw-records.cpp [hunk 4]
```diff
@@ -305,9 +305,10 @@ namespace red_arrow {
   }
 
   VALUE
-  record_batch_each_raw_record(VALUE rb_record_batch){
+  record_batch_each_raw_record(VALUE rb_record_batch) {
     auto garrow_record_batch = GARROW_RECORD_BATCH(RVAL2GOBJ(rb_record_batch));
     auto record_batch = garrow_record_batch_get_raw(garrow_record_batch).get();
+    RETURN_SIZED_ENUMERATOR(rb_record_batch, 0, 0, record_batch->num_rows());
```
Comment (kou) [inline ruby/red-arrow/ext/arrow/raw-records.cpp:311]: We should use `nullptr` for a null pointer in C++:

```suggestion
    RETURN_SIZED_ENUMERATOR(rb_record_batch, 0, nullptr, record_batch->num_rows());
```

File: ruby/red-arrow/ext/arrow/raw-records.cpp [hunk 5]
```diff
@@ -323,6 +324,7 @@ namespace red_arrow {
   table_each_raw_record(VALUE rb_table) {
     auto garrow_table = GARROW_TABLE(RVAL2GOBJ(rb_table));
     auto table = garrow_table_get_raw(garrow_table).get();
+    RETURN_SIZED_ENUMERATOR(rb_table, 0, 0, table->num_rows());
```
Comment (kou) [inline ruby/red-arrow/ext/arrow/raw-records.cpp:327]:
```suggestion
    RETURN_SIZED_ENUMERATOR(rb_table, 0, nullptr, table->num_rows());
```

Comment (otegami) [reply ruby/red-arrow/ext/arrow/raw-records.cpp]: fix: [3563046](https://github.com/apache/arrow/pull/37600/commits/3563046fe239850350ad334908d0d79be641c94c)

File: ruby/red-arrow/ext/arrow/raw-records.cpp (hunk 4 above)
Comment (otegami) [reply ruby/red-arrow/ext/arrow/raw-records.cpp]: Thank you so much! 
fix: [3563046](https://github.com/apache/arrow/pull/37600/commits/3563046fe239850350ad334908d0d79be641c94c)

**Review by kou — APPROVED** [review]
+1
