### PR TITLE
GH-37102: [Go][Parquet] Encoding: Make BitWriter Reserve when ReserveBytes

### LINKED ISSUE #35718: [Go] [Parquet] panic writing with DeltaBinaryPacked when column only has nulls
### Describe the bug, including details regarding any error messages, version, and platform.

The writer panics if DeltaBinaryPacked encoding is requested for a column that is all null. The following small change to an existing test case demonstrates the issue. 

In case it matters, I'm using `go version go1.20.4 darwin/amd64`
I ran into this issue using arrow v12.0.0, but this changed testcase fails using the current head of main.

```
diff --git a/go/parquet/pqarrow/encode_arrow_test.go b/go/parquet/pqarrow/encode_arrow_test.go
index 877f584f2..0b83ec696 100644
--- a/go/parquet/pqarrow/encode_arrow_test.go
+++ b/go/parquet/pqarrow/encode_arrow_test.go
@@ -380,6 +380,8 @@ func TestWriteEmptyLists(t *testing.T) {
 
        props := parquet.NewWriterProperties(
                parquet.WithVersion(parquet.V1_0),
+               parquet.WithDictionaryDefault(false),
+               parquet.WithEncoding(parquet.Encodings.DeltaBinaryPacked),
        )
        arrprops := pqarrow.DefaultWriterProps()
        var buf bytes.Buffer
```

### Component(s)

Go

### LINKED ISSUE #37102: [Go][Parquet] panic when writing particular dataset encoded by DeltaBitPacked
### Describe the bug, including details regarding any error messages, version, and platform.

version: v12.0.1

here is the testcase which cause panic:
`parquet/internal/encoding/encoding_test.go` 
```go
func TestWriteDeltaBitPackedInt64(t *testing.T) {
	column := schema.NewColumn(schema.NewInt64Node("int64", parquet.Repetitions.Required, -1), 0, 0)

	tests := []struct {
		name     string
		toencode []int64
		expected []byte
	}{
		{"panic data", []int64{
			0, 3000000000000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 3000000000000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 3000000000000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 3000000000000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0,
		}, []byte{0, 0, 0, 0, 0}}, // ignore expected bytes
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			enc := encoding.NewEncoder(parquet.Types.Int64, parquet.Encodings.DeltaBinaryPacked, false, column, memory.DefaultAllocator)

			enc.(encoding.Int64Encoder).Put(tt.toencode)
			buf, _ := enc.FlushValues()        // <------------- panic on this line
			defer buf.Release()

			assert.Equal(t, tt.expected, buf.Bytes())

			dec := encoding.NewDecoder(parquet.Types.Int64, parquet.Encodings.DeltaBinaryPacked, column, memory.DefaultAllocator)

			dec.(encoding.Int64Decoder).SetData(len(tt.toencode), buf.Bytes())
			out := make([]int64, len(tt.toencode))
			dec.(encoding.Int64Decoder).Decode(out)
			assert.Equal(t, tt.toencode, out)
		})
	}

	// other subtests...
}
```
### what I expect:
no panic and data has been packed into bytes array
### what I actually get:
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestWriteDeltaBitPackedInt64$ github.com/apache/arrow/go/v13/parquet/internal/encoding -v

=== RUN   TestWriteDeltaBitPackedInt64
=== RUN   TestWriteDeltaBitPackedInt64/panic_data
--- FAIL: TestWriteDeltaBitPackedInt64 (0.00s)
    --- FAIL: TestWriteDeltaBitPackedInt64/panic_data (0.00s)
panic: runtime error: slice bounds out of range [:1026] with capacity 1024 [recovered]
        panic: runtime error: slice bounds out of range [:1026] with capacity 1024

goroutine 19 [running]:
testing.tRunner.func1.2({0x103b6c000, 0x1400019c618})
        /usr/local/go/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x364
panic({0x103b6c000, 0x1400019c618})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
github.com/apache/arrow/go/v13/parquet/internal/encoding.(*deltaBitPackEncoder).FlushValues(0x140001eec00)
        /Users/illyrix/Workspace/arrow/go/parquet/internal/encoding/delta_bit_packing.go:457 +0x33c
github.com/apache/arrow/go/v13/parquet/internal/encoding_test.TestWriteDeltaBitPackedInt64.func1(0x0?)
        /Users/illyrix/Workspace/arrow/go/parquet/internal/encoding/encoding_test.go:642 +0xac
testing.tRunner(0x14000185ba0, 0x14000401680)
        /usr/local/go/src/testing/testing.go:1576 +0x104
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x370
FAIL    github.com/apache/arrow/go/v13/parquet/internal/encoding        0.976s
```
--------------
there is another issue about  delta_bit_packing( #35718 ), but it may be a different bug. All values in our test case are non-null.

### Component(s)

Go, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

See https://github.com/apache/arrow/issues/37102. Also fixes #35718

Golang BitWriter didn't reserve when `ReserveBytes` called. So it make it wrong.

### What changes are included in this PR?

Change `ReserveBytes` impl

### Are these changes tested?

Currently not

### Are there any user-facing changes?

bugfix

* Closes: #37102

### CODE REVIEW

**Comment by zeroshade** [comment]
@mapleFU Does this solve the issue in the linked issue? Can you take the test from the issue and add it as a test to confirm this solves the problem here?

**Comment by zeroshade** [comment]
@mapleFU Thanks much! I'll take a look. at first glance it looks good

File: go/parquet/internal/utils/bit_writer.go [hunk 1]
```diff
@@ -81,11 +81,15 @@ func NewBitWriter(w io.WriterAt) *BitWriter {
...
-func (b *BitWriter) ReserveBytes(nbytes int) int {
+func (b *BitWriter) ReserveBytes(nbytes int) (int, error) {
 	b.Flush(true)
 	ret := b.byteoffset
 	b.byteoffset += nbytes
-	return ret
+	if _, err := b.wr.WriteAt(b.raw[:nbytes], int64(ret)); err != nil {
+		log.Println(err)
+		return 0, err
+	}
```
Comment (zeroshade) [inline go/parquet/internal/utils/bit_writer.go:91]: Instead of doing this would it make more sense to expand the `io.WriterAt` interface we're using to be something more like 

```go
type writer interface {
    io.WriterAt
    Reserve(nbytes int)
}
```

so that the `ReserveBytes` method here could just be 

```go
b.Flush(true)
ret := b.byteoffset
b.byteoffset += nbytes
b.wr.Reserve(nbytes)
return ret
```

Thoughts?

Comment (mapleFU) [reply go/parquet/internal/utils/bit_writer.go:91]: This looks ok, but I guess it need to modify some code. Let me do it later.

**Comment by mapleFU** [comment]
I'm afraid thats a bit hard for me.

The reason is that `RLE` also has this problem (see RleEncoder and FlushLiteralRun in cpp code). So almost  `io.WriterAt` should be refactor to the `writer`. It's ok but I've a long time didn't use golang, so maybe I will break the interface. You can edit it directly.

You can edit this patch directly or close it and create one :-)

File: go/parquet/internal/utils/bit_writer.go (hunk 1 above)
Comment (mapleFU) [reply go/parquet/internal/utils/bit_writer.go]: @zeroshade I guess a `Reserve` is not enough, maybe it should be "Reserve + Advance"

Comment (zeroshade) [reply go/parquet/internal/utils/bit_writer.go]: I did a quick update which solves the issue. what do you think? I agree we should probably change the name. Perhaps instead of `Reserve` we can call it `Advance` or `Skip` etc.?

Comment (mapleFU) [reply go/parquet/internal/utils/bit_writer.go]: Skip LGTM! Thanks!

**Comment by mapleFU** [comment]
Hi Matt, I found `Reserve` is confusing in our project. Some time it like C++ `stl` reserve(k): make sure elements upto k elements, some times it means `ensure k more slots`. Would it be confusing here?

File: go/parquet/internal/utils/bit_writer.go [hunk 2]
```diff
@@ -74,18 +79,19 @@ type BitWriter struct {
...
+// SkipBytes reserves the next aligned nbytes, skipping them and returning
 // the offset to use with WriteAt to write to those reserved bytes. Used for
 // RLE encoding to fill in the indicators after encoding.
-func (b *BitWriter) ReserveBytes(nbytes int) int {
+func (b *BitWriter) SkipBytes(nbytes int) (int, error) {
 	b.Flush(true)
 	ret := b.byteoffset
 	b.byteoffset += nbytes
-	return ret
+	b.wr.Reserve(b.byteoffset)
```
Comment (mapleFU) [inline go/parquet/internal/utils/bit_writer.go:93]:
```Go
// Reserve pre-allocates nbytes to ensure that the next write of that many bytes
// will not require another allocation.
func (b *PooledBufferWriter) Reserve(nbytes int) {
	if b.buf == nil {
		b.buf = bufferPool.Get().(*memory.Buffer)
	}

	newCap := utils.MaxInt(b.buf.Cap()+b.offset, 256)
	for newCap < b.pos+nbytes {
		newCap = bitutil.NextPowerOf2(newCap)
	}
	b.buf.Reserve(newCap)
}
```

Would it Reserve more bytes than expected here?

Comment (zeroshade) [reply go/parquet/internal/utils/bit_writer.go:93]: The bitwriter *only* uses `WriteAt` and never calls the regular `Write`. As a result the internal `b.pos` never gets incremented, so `Reserve` has to always include the whole size (in this situation) because we never advance the `b.pos` inside the buffer and only ever use `WriteAt`

Comment (mapleFU) [reply go/parquet/internal/utils/bit_writer.go:93]: Oh yeah, I mean that, would we use more memory than expected? Maybe we have:

```
LevelEncoder( holds PooledBufferWriter)
-> BitWriter ( holds PooledBufferWriter)
--> Call Reserve ( b.byteoffset)
```

I'm not sure would it harms...

Comment (zeroshade) [reply go/parquet/internal/utils/bit_writer.go:93]: hmm, can you elaborate? I'm not understanding what you're suggesting here.

Comment (mapleFU) [reply go/parquet/internal/utils/bit_writer.go:93]:
```go
func (b *BitWriter) SkipBytes(nbytes int) (int, error) {
	b.Flush(true)
	ret := b.byteoffset
	b.byteoffset += nbytes
	b.wr.Reserve(b.byteoffset)
```

(1) Here, the `b.wr.Reserve(b.byteoffset)` will try to Reserve the `b.byteoffset` bytes, which is the sum bytes the `WriterAtWithLen` owned.

And `PooledBufferWrite` will regard `Reserve(b.byteoffset)` as "reserve  `b.byteoffset` more bytes", would it allocate much more memory than it exactly want?

Comment (zeroshade) [reply go/parquet/internal/utils/bit_writer.go:93]: Because the `BitWriter` only ever calls `WriteAt`, the buffer's `pos` variable never updates. (Only `Write` updates the internal `pos`, i.e. position). When we call `Reserve` it verifies that `pos + nbytes < capacity`. So the `BitWriter` needs to always call `Reserve` with the full `b.byteoffset` in order to ensure that the bytes get reserved correctly. So it won't end up allocating more than we want to (aside from the fact that we always round up to the next power of two when allocating with reserve so that we don't have too many allocations)

Comment (mapleFU) [reply go/parquet/internal/utils/bit_writer.go:93]: Yeah I know what you mean. Assume that we want we `SkipBytes(4)`, and `b.byteoffset = 1024`.

1. `b.byteoffset = 1024 + 4`
2. `b.wr.Reserve(1028)`
3. dispatch to `PooledBufferWriter.Reserve(1028)`
4. `newCap: at lease 1024 + 1028`

I just want to make sure that in (4), would it better be `newCap: 1028`?

Comment (zeroshade) [reply go/parquet/internal/utils/bit_writer.go:93]: currently, 4 would be `newCap: at least 1028`, yes.

Comment (mapleFU) [reply go/parquet/internal/utils/bit_writer.go:93]: LGTM now, I'm no problem then

**Comment by mapleFU** [comment]
I've no problem now. Though it might get more memory than expected, the implement is right. So it LGTM
