### PR TITLE
GH-34363: [C++] Use equal size parts in S3 upload for R2 compatibility

### LINKED ISSUE #34363: [Python] Writing to cloudflare r2 fails for mutlipart upload
### Describe the bug, including details regarding any error messages, version, and platform.

When I try to write a pyarrow.table to cloudflare r2 object store, I got an error when files are larger than x MB (I do not know the exact threshold) and pyarrow internally switches  to multipart uploading.

I´ve used `s3fs.S3FileSystem` (fsspec) and also tried `pyarrow.fs.S3FileSystem`. Here is some example code:

```python
import pyarrow.fs as pafs
import s3fs
import pyarrow.parquet as pq
import pyarrow as pa

table_small = pq.read_table("small_data.parquet")
table_large = pq.read_table("large_data.parquet")

fs1 = s3fs.S3FileSystem(
  key="some_key", 
  secret="some_secret", 
  client_kwargs=dict(endpoint_url="https://123456.r2.cloudflarestorage.com"), 
  s3_additional_kwargs=dict(ACL="private") # <- this is neccessary for writing. 
) 

fs2 = pafs.S3FileSystem(
  access_key="some_key", 
  secret_key="some_secret", 
  endpoint_override="https://123456.r2.cloudflarestorage.com"
)


pq.write_table(table_small, "test/test.parquet", filesystem=fs1) # <- works 
pq.write_table(table_small, "test/test.parquet", filesystem=fs2) # <- works 

#  failed with OSError: [Errno 22] There was a problem with the multipart upload. 
pq.write_table(table_large, "test/test.parquet", filesystem=fs1) 

# failed with OSError: When initiating multiple part upload for key 'test.parquet' in bucket 'test': AWS Error NETWORK_CONNECTION during CreateMultipartUpload operation: curlCode: 28, Timeout was reached
pq.write_table(table_large, "test/test.parquet", filesystem=fs2) 
```

### Platform
Linux x86

### Versions
pyarrow 11.0.0
s3fs 2023.1.0

### Component(s)

Parquet, Python

### PR DESCRIPTION
**Pull request by wjones127**
### Rationale for this change

S3 and Minio allow varied part sizes, but R2 doesn't yet. So for now we'll change to only write 

### What changes are included in this PR?

Alters the `DoWrite` implementation to used fixed size parts.

### Are these changes tested?

* [x] Tested manually against R2
* [x] Tested manually against S3

### Are there any user-facing changes?

* Closes: #34363

### CODE REVIEW

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 1]
```diff
@@ -1154,7 +1154,7 @@ class ObjectInputFile final : public io::RandomAccessFile {
 // AWS doc says "5 MB" but it's not clear whether those are MB or MiB,
 // so I chose the safer value.
 // (see https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html)
-static constexpr int64_t kMinimumPartUpload = 5 * 1024 * 1024;
+static constexpr int64_t kMinimumPartUpload = 10 * 1024 * 1024;
```
Comment (wjones127) [inline cpp/src/arrow/filesystem/s3fs.cc:1157]: Previously our limit was ~2.4TB. In the new design, it is 100GB. It would be only 50GB if it was left at 5MB per part. I feel like this is an okay balance, but willing to hear other's opinions.

**Comment by wjones127** [comment]
✅ I've tested this locally against S3 and R2 with the following script:

```python
import pyarrow.fs as pa_fs
import os

# 25 MB across 7 pieces
pieces = 7
piece_size = 25 * 1024 * 1024 // pieces

bucket_name = os.environ["OBJECT_STORE_BUCKET"]

fs = pa_fs.S3FileSystem(
    access_key=os.environ["AWS_ACCESS_KEY_ID"],
    secret_key=os.environ["AWS_SECRET_ACCESS_KEY"],
    endpoint_override=os.environ.get("OBJECT_STORE_AWS_ENDPOINT"),
    region="us-west-2",
)

with fs.open_output_stream(f"{bucket_name}/my_test_file.txt") as f:
    for i in range(pieces):
        f.write(b"0" * piece_size)

info = fs.get_file_info(f"{bucket_name}/my_test_file.txt")
assert info.size == piece_size * pieces
```

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:1157]: It seems ok to me, it just means that we're using a bit more RAM to buffer outgoing bytes.

Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:1157]: Can you add a comment about the limit, though?

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 2]
```diff
@@ -1304,27 +1304,43 @@ class ObjectOutputStream final : public io::OutputStream {
...
     }
 
-    if (!current_part_ && nbytes >= part_upload_threshold_) {
-      // No current part and data large enough, upload it directly
-      // (without copying if the buffer is owned)
-      RETURN_NOT_OK(UploadPart(data, nbytes, owned_buffer));
-      pos_ += nbytes;
-      return Status::OK();
+    const int8_t* data_ptr = reinterpret_cast<const int8_t*>(data);
+    int64_t offset = 0;
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.cc:1308]: Instead of maintaining a separate offset, you can simply bump `data_ptr` and decrease `nbytes` as needed.

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 3]
```diff
@@ -1304,27 +1304,43 @@ class ObjectOutputStream final : public io::OutputStream {
...
+
+    // Handle case where we have some bytes bufferred from prior calls.
+    if (current_part_size_ > 0) {
+      // Try to fill current buffer
+      const int64_t to_copy =
+          std::min(nbytes - offset, part_upload_threshold_ - current_part_size_);
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.cc:1314]: If `part_upload_threshold_` isn't a threshold anymore, perhaps rename it and make it `const`?

**Review by pitrou — COMMENTED** [review]
This looks ok on the principle but could you add comments explaining the rationale for this strategy, and pointing to the corresponding GH issue?

**Review by pitrou — APPROVED** [review]

**Comment by wjones127** [comment]
> I suspect this shouldn't affect performance, but have you tried a large upload against a remote endpoint?

Just tested on an EC2 instance in the same region as an S3 bucket. They seem comparable.

Before:
```
Upload 200MB data in 25 pieces (8.0 MB per piece).
Avg: 2.4996164005998254 Min: 1.839938310999969 Max: 6.8072016670002995

Upload 200MB data in 4 pieces (50.0 MB per piece).
Avg: 2.3683339380998403 Min: 2.1181160359992646 Max: 3.710967674999665
```

After:

```
Upload 200MB data in 25 pieces (8.0 MB per piece).
Avg: 1.989240413999869 Min: 1.9223971040009928 Max: 2.2479570469986356

Upload 200MB data in 4 pieces (50.0 MB per piece).
Avg: 2.1779588877003335 Min: 2.1119931640005234 Max: 2.3420757010007947
```
<details>
<summary>Benchmark script</summary>

```python
import pyarrow.fs as pa_fs
import random
import os
import time

fs = pa_fs.S3FileSystem(
    region="us-west-2"
)

# 100 MB across 25 pieces
pieces = 25
piece_size = 200 * 1024 * 1024 // pieces

bucket_name = os.environ["OBJECT_STORE_BUCKET"]

fs = pa_fs.S3FileSystem(
    access_key=os.environ["AWS_ACCESS_KEY_ID"],
    secret_key=os.environ["AWS_SECRET_ACCESS_KEY"],
    region="us-west-2",
    background_writes=True, # Also test false
)

iterations = 10
times = []

for _ in range(iterations):
    start = time.monotonic()
    with fs.open_output_stream(f"{bucket_name}/my_test_file.bin") as f:
        for i in range(pieces):
            data = random.randbytes(piece_size)
            f.write(data)
    end = time.monotonic()
    times.append(end - start)

info = fs.get_file_info(f"{bucket_name}/my_test_file.bin")
assert info.size == piece_size * pieces

avg_time = sum(times) / len(times)
print(f"Upload 200MB data in {pieces} pieces ({piece_size / 1024 / 1024} MB per piece).")
print(f"Avg: {avg_time} Min: {min(times)} Max: {max(times)}")
```
</details>

**Comment by pitrou** [comment]
Thanks @wjones127 . This confirms that piece size doesn't seem to have much of an impact.

**Comment by pitrou** [comment]
Rebased to get the latest CI fixes.
