### PR TITLE
GH-38227: [R] Fix non-unicode character errors in nightly builds

### LINKED ISSUE #38227: [R]
### Describe the bug, including details regarding any error messages, version, and platform.

This seems to be a problem with LaTex:

```
❯ checking PDF version of manual ... [13s/13s] WARNING
  LaTeX errors when creating PDF version.
  This typically indicates Rd problems.
  LaTeX errors found:
  ! LaTeX Error: Unicode character ⁠ (U+2060)
                 not set up for use with LaTeX.

```

We could probably set `--no-manual` wherever `R CMD check` happens in `dev/tasks/r/azure.linux.yml`.

### Component(s)

R

### PR DESCRIPTION
**Pull request by paleolimbot**
### Rationale for this change

We have several nightly builds failing with errors building the manual as a result of unicode characters. The unicode characters aren't new, so I'm not sure why this happened now.

### What changes are included in this PR?

Install a distribution of latex that supports unicode characters (maybe)?

### Are these changes tested?

Yes

### Are there any user-facing changes?

No
* Closes: #38227

### CODE REVIEW

**Review by assignUser — APPROVED** [review]
What a fun issue to debug! Thanks!

File: r/R/csv.R [hunk 1]
```diff
@@ -22,8 +22,8 @@
 #' `readr::read_delim()`, and `col_select` was inspired by `vroom::vroom()`.
 #'
 #' `read_csv_arrow()` and `read_tsv_arrow()` are wrappers around
-#' `read_delim_arrow()` that specify a delimiter. `read_csv2_arrow()` uses `;`⁠ for
-#' the delimiter and `,` for the decimal point.
+#' `read_delim_arrow()` that specify a delimeter. `read_csv2_arrow()` uses `;` for
```
Comment (thisisnic) [inline r/R/csv.R:25]: I was corrected on this by someone else when working on this recently, but I believe that "delimiter" is the correct spelling here rather than "delimeter"?

Comment (thisisnic) [reply r/R/csv.R:25]: Sorry, didn't realise this has merged, I'll open a PR!
