### PR TITLE
GH-37952: [C++] Make unique->shared explicit to fix build failure on at least one compiler

### LINKED ISSUE #37952: [R][C++] Build failure on OpenSuse 15.3 nightly job relating to Parquet FileReader
### Describe the bug, including details regarding any error messages, version, and platform.

e.g. [test-r-rstudio-r-base-4.1-opensuse153](https://github.com/ursacomputing/crossbow/runs/17162402631)

```
[100%] Building CXX object src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_parquet.cc.o
/arrow/cpp/src/arrow/dataset/file_parquet.cc: In member function ‘arrow::Result<std::shared_ptr<parquet::arrow::FileReader> > arrow::dataset::ParquetFileFormat::GetReader(const arrow::dataset::FileSource&, const std::shared_ptr<arrow::dataset::ScanOptions>&, const std::shared_ptr<parquet::FileMetaData>&) const’:
/arrow/cpp/src/arrow/dataset/file_parquet.cc:465:10: error: could not convert ‘arrow_reader’ from ‘std::unique_ptr<parquet::arrow::FileReader>’ to ‘arrow::Result<std::shared_ptr<parquet::arrow::FileReader> >’
   return arrow_reader;
          ^~~~~~~~~~~~
make[2]: *** [src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/build.make:244: src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_parquet.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2454: src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
**** Error building Arrow C++. 
------------------------- NOTE ---------------------------
There was an issue preparing the Arrow C++ libraries.
See https://arrow.apache.org/docs/r/articles/install.html
---------------------------------------------------------
ERROR: configuration failed for package ‘arrow’
* removing ‘/arrow/r/check/arrow.Rcheck/arrow’
```

This has been failing for 11 days.

### Component(s)

R

### PR DESCRIPTION
**Pull request by paleolimbot**
### Rationale for this change

The [test-r-rstudio-r-base-4.1-opensuse153](https://github.com/ursacomputing/crossbow/runs/17162402631) nightly has been failing with a compile error for many days.

### What changes are included in this PR?

Made the unique->shared conversion explicit.

### Are these changes tested?

Yes (by existing tests)

### Are there any user-facing changes?

No.
* Closes: #37952

### CODE REVIEW

File: cpp/src/arrow/dataset/file_parquet.cc [hunk 1]
```diff
@@ -462,7 +462,9 @@ Result<std::shared_ptr<parquet::arrow::FileReader>> ParquetFileFormat::GetReader
   std::unique_ptr<parquet::arrow::FileReader> arrow_reader;
   RETURN_NOT_OK(parquet::arrow::FileReader::Make(
       options->pool, std::move(reader), std::move(arrow_properties), &arrow_reader));
-  return arrow_reader;
+
+  std::shared_ptr<parquet::arrow::FileReader> file_reader_shared(arrow_reader.release());
+  return file_reader_shared;
```
Comment (kou) [inline cpp/src/arrow/dataset/file_parquet.cc:467]: Does `return std::move(arrow_reader)` work?

**Review by mapleFU — APPROVED** [review]

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly

**Review by pitrou — APPROVED** [review]
LGTM, but please let's watch the nightly builds before merging
