### PR TITLE
GH-35866: [Go] Provide a copy in `arrow.NestedType.Fields()` implementations

### LINKED ISSUE #35866: [Go] `arrow.StructType` fields are mutable
### Describe the bug, including details regarding any error messages, version, and platform.

After `arrow.StructType` was constructed the fields are considered immutable (lice columns in `arrow.Schema`, but they aren't

### Component(s)

Go

### PR DESCRIPTION
**Pull request by candiduslynx**
### Rationale for this change

Data types should be left immutable after they've been constructed.

### What changes are included in this PR?

Provide a copy of fields in the following implementations:
* `*arrow.StructType.Fields()`
* `*arrow.unionType.Fields()`

### Are these changes tested?

`arrow.TestFieldsImmutability` was added to ensure the behavior.

### Are there any user-facing changes?

Now the fields for structs & unions will be immutable.

* Closes: #35866

### CODE REVIEW

File: go/arrow/datatype_nested.go [hunk 1]
```diff
@@ -288,7 +288,12 @@ func (t *StructType) String() string {
 	return o.String()
 }
 
-func (t *StructType) Fields() []Field   { return t.fields }
+func (t *StructType) Fields() []Field {
```
Comment (zeroshade) [inline go/arrow/datatype_nested.go:291]: Can you add a godoc comment on the methods to indicate to callers that this will make a copy of the Fields?

File: go/arrow/datatype_nested.go [hunk 2]
```diff
@@ -490,7 +495,12 @@ func (t *unionType) init(fields []Field, typeCodes []UnionTypeCode) {
 	}
 }
 
-func (t unionType) Fields() []Field            { return t.children }
+func (t unionType) Fields() []Field {
+	fields := make([]Field, len(t.children))
+	copy(fields, t.children)
+	return fields
+}
```
Comment (zeroshade) [inline go/arrow/datatype_nested.go:502]: same here. add a godoc comment to this to indicate it makes a copy of the fields

**Review by zeroshade — CHANGES_REQUESTED** [review]
LGTM just want to have the documentation indicate that it makes a copy so that callers can choose to instead use the `Field(i)` methods if they want to avoid the copies

**Comment by candiduslynx** [comment]
> LGTM just want to have the documentation indicate that it makes a copy so that callers can choose to instead use the `Field(i)` methods if they want to avoid the copies

Just FYI, `Field(i)` provides a copy of the `arrow.Field` (note: the `Type` field will point to the same instance, but the pointer itself is copied)

File: go/arrow/datatype_nested.go (hunk 1 above)
Comment (candiduslynx) [reply go/arrow/datatype_nested.go:296]: 1e81c723eb665da8f59519710c749e0fda435676

File: go/arrow/datatype_nested.go (hunk 2 above)
Comment (candiduslynx) [reply go/arrow/datatype_nested.go:509]: 1e81c723eb665da8f59519710c749e0fda435676

**Comment by zeroshade** [comment]
@candiduslynx true, (a mistake in my wording) i meant if they didn't want to make a copy of the entire slice of fields. Copying an individual field is extremely cheap, but under certain circumstances it could be desireable to avoid copying the entire slice of fields. 

Either way most times that a slice is returned from a method in go, the average usage assumes that it isn't making a copy of all the elements so it's good to ensure the godoc is clear.

**Review by zeroshade — APPROVED** [review]
