### PR TITLE
GH-38844: [C++] S3FileSystem export s3 sdk config "use_virtual_addressing" to arrow::fs::S3Options

### LINKED ISSUE #38844: Arrow S3 filesystem have bugs on virtual hosted config
### Describe the bug, including details regarding any error messages, version, and platform.

in the file  /arrow/cpp/src/arrow/filesystem/s3fs.cc , at the line:917 , the bool var "use_virtual_addressing"  should be set true if options_.endpoint_override is **not** empty , or it will throw error when connect to Oss . ref to  #38135 
image

### Component(s)

C++

### PR DESCRIPTION
**Pull request by liangjiawei1110**
### Rationale for this change
See #38844 . we should export s3 sdk config "use_virtual_addressing" to arrow::fs::S3Options so that user can decide whether to use virtual hosted by themselves. 

### Are these changes tested?
I tested it with my own OSS(aliyun object store service) bucket.As the it is a S3 compatiable service, I think 
 these changes are covered by existing tests)

### Are there any user-facing changes?

Closes: #38844  

* Closes: #38844

### CODE REVIEW

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 1]
```diff
@@ -951,7 +951,7 @@ class ClientBuilder {
       client_config_.caPath = ToAwsString(internal::global_options.tls_ca_dir_path);
     }
 
-    const bool use_virtual_addressing = options_.endpoint_override.empty();
+    const bool use_virtual_addressing = options_.use_virtual_addressing;
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.cc:954]: This will break the current behavior where, if `endpoint_override` is set, virtual addressing is disabled.

Perhaps we should make `use_virtual_addressing` a `std::optional<bool>` instead?

Or perhaps we could call it `force_virtual_addressing` and have the following logic:
```c++
    const bool use_virtual_addressing = options_.endpoint_override.empty() || options_.force_virtual_addressing;
```

Comment (liangjiawei1110) [reply cpp/src/arrow/filesystem/s3fs.cc]: ok, I have changed the code as the last logic

File: cpp/src/arrow/filesystem/s3fs.h [hunk 2]
```diff
@@ -144,6 +144,9 @@ struct ARROW_EXPORT S3Options {
   /// Type of credentials being used. Set along with credentials_provider.
   S3CredentialsKind credentials_kind = S3CredentialsKind::Default;
 
+  /// Whether to use virtual addressing of buckets
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.h:147]:
```suggestion
  /// Whether to use virtual addressing of buckets
  ///
  /// If true, then virtual addressing is always enabled.
  /// If false, then virtual addressing is only enabled if `endpoint_override` is empty.
```

**Review by felipecrv — COMMENTED** [review]
Can we call it `force_virtual_hosting` instead of "addressing" like the AWS docs do? [1] I see that the AWS SDK calls it "addressing", but we don't have to use this confusing name in the Arrow interface.

[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

File: cpp/src/arrow/filesystem/s3fs.h [hunk 3]
```diff
@@ -144,6 +144,12 @@ struct ARROW_EXPORT S3Options {
...
+  ///
+  /// If true, then virtual addressing is always enabled.
+  /// If false, then virtual addressing is only enabled if `endpoint_override` is empty.
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.h:150]:
```suggestion
  /// If false, then virtual addressing is only enabled if `endpoint_override` is empty.
  ///
  /// This can be used for non-AWS backends that only support virtual hosted-style access.
```

**Review by pitrou — APPROVED** [review]
+1, thank you for this @liangjiawei1110 !
