### PR TITLE
GH-49433: [C++] Buffer ARROW_LOG output to prevent thread interleaving

### LINKED ISSUE #49433: [C++] Multi-threaded logging can mix up messages
### Describe the bug, including details regarding any error messages, version, and platform.

When using the C++ logging macros (ARROW_LOG) from multiple threads, messages often get mingled together, which makes the log much less readable and useful.

We should probably add some internal buffering so that logging each message is "atomic" wrt other messages.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by Shockp**
### Rationale for this change

When using the C++ `ARROW_LOG` macros from multiple threads, messages often get mingled together in `stderr` because the `operator<<` writes directly to the global stream piece-by-piece, which is not thread-safe.

### What changes are included in this PR?

This PR introduces an internal `std::ostringstream` buffer to the fallback `CerrLog` class. 
Instead of writing to `std::cerr` immediately on every `<<` operation, the messages are accumulated locally within the `CerrLog` instance. The completed string is then flushed atomically to `std::cerr` upon the object's destruction.

### Are these changes tested?
Yes. I built the C++ project locally and ran the test suite (`ctest`) to ensure no existing logging behavior or IPC functionality was broken. 

### Are there any user-facing changes?
No API changes. Users will simply notice that multi-threaded `ARROW_LOG` console output is now cleanly separated per line instead of interleaved.

Closes #49433
* GitHub Issue: #49433

### CODE REVIEW

File: cpp/src/arrow/util/logging.cc [hunk 1]
```diff
@@ -67,7 +68,7 @@ class CerrLog {
 
   virtual ~CerrLog() {
     if (has_logged_) {
-      std::cerr << std::endl;
+      std::cerr << buffer_.str() << std::endl;
```
Comment (pitrou) [inline cpp/src/arrow/util/logging.cc:74]: Did you check whether this is sufficient or a mutex is also required?

You can add a multi-threaded test to `logging_test.cc` so that we can visually confirm this.

**Review by pitrou — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/util/logging.cc (hunk 1 above)
Comment (Shockp) [reply cpp/src/arrow/util/logging.cc:74]: Thanks for the review. Even with the stringstream buffer, the final write and the std::endl flush could still interleave at the OS level across multiple threads. I'll add a static mutex to the CerrLog destructor to lock the final write, and I'll add a test in logging_test.cc to spawn multiple threads to verify the clean output.

**Comment by Shockp** [comment]
Added the static std::mutex lock to the destuctor to protect the final flush, and verified it locally with a new 10-thread concurrent test in logging_test.cc.

**Review by pitrou — APPROVED** [review]
Thanks a lot @Shockp ! I made two minor changes but this otherwise looks good to me. I'll wait for CI and then merge.

**Comment by pitrou** [comment]
Ok, it looks like `std::stringstream::view` is not universally supported, so I'll revert that.

**Comment by Shockp** [comment]
Thank you so much for the review and the final tweaks, @pitrou! I really appreciate the guidance on my first PR. I will keep contributing more.
