### PR TITLE
GH-34230: [Java] Call allocation listener on BaseAllocator#wrapForeignAllocation

### LINKED ISSUE #34230: [Java]  Call allocation listener on BaseAllocator#wrapForeignAllocation
### Describe the bug, including details regarding any error messages, version, and platform.

Buffer created by BaseAllocator#wrapForeignAllocation calls `AllocationListener#onRelease` but the Allocator didn't call `AllocationListener#onAllocate()` when the buffer was created.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by zhztheplayer**
#34230 
* Closes: #34230

### CODE REVIEW

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/CountingAllocationListener.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.apache.arrow.memory;
+
+// Allocation listener
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/CountingAllocationListener.java:20]: nit, but please stick to JavaDoc syntax for this?

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java [hunk 2]
```diff
@@ -233,6 +233,41 @@ private void childClosed(final BaseAllocator childAllocator) {
...
+      final BufferLedger ledger = manager.associate(this);
+      final ArrowBuf buf =
+          new ArrowBuf(ledger, /*bufferManager=*/null, size, allocation.memoryAddress());
+      buf.writerIndex(size);
+      listener.onAllocation(size);
+      return buf;
+    } catch (Throwable t) {
+      try {
+        releaseBytes(size);
+        allocation.release0();
```
Comment (lidavidm) [inline java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java:263]: can this be in a separate try-catch?

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java [hunk 3]
```diff
@@ -233,6 +233,41 @@ private void childClosed(final BaseAllocator childAllocator) {
     listener.onChildRemoved(this, childAllocator);
   }
 
+  @Override
+  public ArrowBuf wrapForeignAllocation(ForeignAllocation allocation) {
+    assertOpen();
+    final long size = allocation.getSize();
+    listener.onPreAllocation(size);
+    AllocationOutcome outcome = this.allocateBytes(size);
```
Comment (lidavidm) [inline java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java:241]: Hmm, if we don't force allocation the behavior is different - the memory is already allocated, we're just trying to account for it. This will 'eagerly' release resources (via the listener) to make room while the existing behavior is to do it 'lazily' (the next allocation will trigger things if needed). Is that what you want?

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestForeignAllocation.java [hunk 4]
```diff
@@ -54,6 +54,55 @@ public void wrapForeignAllocation() {
...
+      assertEquals(0, listenedAllocator.getAllocatedMemory());
+    }
+    assertEquals(1, listener.getNumPreCalls());
+    assertEquals(1, listener.getNumCalls());
+    assertEquals(1, listener.getNumReleaseCalls());
+    assertEquals(16, listener.getTotalMem());
+  }
+
+  @Test(expected = OutOfMemoryException.class)
+  public void wrapForeignAllocationFailedWithAllocationListener() {
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestForeignAllocation.java:85]: Can we also test the case where the listener frees some memory and the allocation succeeds?

**Review by lidavidm — CHANGES_REQUESTED** [review]
Thanks, I left some comments.

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java (hunk 3 above)
Comment (zhztheplayer) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java:241]: Thanks for noticing this. I think it's not a very big issue as long as we treat "accountation of foreign allocation" as another type of "allocation" too. Since sometimes it can be tricky to track on actual foreign allocation at real-time from Java side.

Also another solution would be just excluding foreign allocation from `listener.release()` too. But in that way one will lose tracking if he didn't set up a independent path to report the foreign allocations.

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestForeignAllocation.java (hunk 4 above)
Comment (zhztheplayer) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestForeignAllocation.java:88]: Sure, I'll add a case

**Comment by zhztheplayer** [comment]
@lidavidm Would you like to take another look? Thanks.

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java (hunk 2 above)
Comment (zhztheplayer) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java:263]: Thanks but would you give some hints on this? Or would you suggest adding a local variable `Throwable xx` to save the error for further handling?

Comment (lidavidm) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java:263]: What I mean is that `release0` should be called even if `releaseBytes` throws.

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java (hunk 3 above)
Comment (lidavidm) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java:241]: As long as it's consistent. I think the behavior here is OK, and consistent with the "allocator" actually being a "ledger".

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java (hunk 2 above)
Comment (zhztheplayer) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/BaseAllocator.java:267]: Thanks. Updated.

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestForeignAllocation.java [hunk 5]
```diff
@@ -54,6 +57,80 @@ public void wrapForeignAllocation() {
...
+      }
+    }
+  }
+
+  @Test
+  public void wrapForeignAllocationWithAllocationListenerReclaimingSpace() {
+    final long bufferSize = 16;
+    final long limit = 2 * bufferSize - 1;
+
+    final List<ArrowBuf> bufferedToBeFreed = new ArrayList<>();
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestForeignAllocation.java:113]: nit: typo 

```suggestion
    final List<ArrowBuf> buffersToBeFreed = new ArrayList<>();
```

**Review by lidavidm — APPROVED** [review]
Thanks, just a typo.

**Review by lidavidm — APPROVED** [review]
