### PR TITLE
GH-38618: [C++] S3FileSystem: fix regression in deleting explicitly created sub-directories

### LINKED ISSUE #38618: [Python][C++] S3FileSystem delete_dir() regression in PyArrow 14
### Describe the bug, including details regarding any error messages, version, and platform.

I think I have found a regression for S3FileSystem in PyArrow 14. Using the delete_dir() method with PyArrow 13 will remove a "directory" object and all its children, i.e. it will delete everything with the directory prefix. However when I switch to PyArrow 14 this no longer works, after calling delete_dir() the object still exists (I am checking with get_file_info() != FileType.NotFound). The issue also seems to affect delete_dir_contents(). The delete_dir() method still works on empty directories, and if I remove all the objects inside a directory and then call delete_dir() it will also work.

Could this be something to do with the AWS call for removing objects by prefix? In the native APIs for GCP / Azure this is not possible and objects need to be listed and deleted in batches, but for S3 delete by prefix is available so I'm guessing the S3 FileSystem implementation uses this feature? These low level details are hidden by the Arrow FS abstraction though, so while delete_dir() is not working there is no effective way to work around without writing an implementation in the native AWS SDK - I'd prefer not to do that for the sake of one call!

I have seen this issue on macOS with Python 3.12 and 3.10, also on Ubuntu with Python 3.11. In all cases the Arrow 13 version worked and the Arrow 14 version didn't. I haven't tried Arrow 14 on Windows but I do know Arrow 13 used to work on Windows. Also I'm assuming this is in the C implementation so it could affect more than just the Python component, but I have only tested with Python.

Please let me know if there's anything I can do to help diagnose this issue. If it is a regression and it's possible to fix with a 14.0.1 that would be amazing but I don't know how possible that is.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
### Rationale for this change

See https://github.com/apache/arrow/issues/38618#issuecomment-1821252024 and below for the analysis. When deleting the dir contents, we use a GetFileInfo with recursive FileSelector to list all objects to delete, but when doing that the file paths for directories don't end in a trailing `/`, so for deleting explicitly created directories we need to add the `kSep` here as well to properly delete the object.

### Are these changes tested?

I tested them manually with an actual S3 bucket. The problem is that MinIO doesn't have the same problem, and so it's not actually tested with the test I added using our MinIO testing setup.

### Are there any user-facing changes?

Fixes the regression
* Closes: #38618

### CODE REVIEW

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 1]
```diff
@@ -2408,7 +2408,11 @@ class S3FileSystem::Impl : public std::enable_shared_from_this<S3FileSystem::Imp
                   std::vector<std::string> file_paths;
                   for (const auto& file_info : file_infos) {
                     DCHECK_GT(file_info.path().size(), bucket.size());
-                    file_paths.push_back(file_info.path().substr(bucket.size() + 1));
+                    auto file_path = file_info.path().substr(bucket.size() + 1);
+                    if (file_info.IsDirectory()) {
+                      file_path = file_path + kSep;
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/s3fs.cc:2413]: Can you `DCHECK` here that `file_path` doesn't end with a `/` (kSep)?

It looks like `FileInfo` is normalizing paths to never end with `/` and this `DCHECK` can protect us if that changes in the future.

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 2]
```diff
@@ -2408,7 +2408,11 @@ class S3FileSystem::Impl : public std::enable_shared_from_this<S3FileSystem::Imp
...
+                    }
+                    file_paths.push_back(file_path);
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/s3fs.cc:2415]: Now that `file_path` lives in a variable, you need to explicitly `std::move` it to avoid a copy when pushing:

```cpp
file_paths.push_back(std::move(file_path));
```

**Review by felipecrv — CHANGES_REQUESTED** [review]
Thanks for investigating and fixing this!

**Review by felipecrv — APPROVED** [review]

**Review by felipecrv — APPROVED** [review]

**Review by raulcd — APPROVED** [review]
LGTM. I would like to merge this to be added to 14.0.2

**Review by pitrou — CHANGES_REQUESTED** [review]

File: python/pyarrow/tests/test_fs.py [hunk 3]
```diff
@@ -760,6 +760,34 @@ def test_delete_dir(fs, pathfn):
         fs.delete_dir(d)
 
 
+def test_delete_dir_with_explicit_subdir(fs, pathfn):
+    skip_fsspec_s3fs(fs)
```
[the remark this answers is not in the document]
Comment (jorisvandenbossche) [reply python/pyarrow/tests/test_fs.py:766]: Added a link+comment, although the test itself doesn't actually catch the regression .. (minio doesn't have the same issue, the test only fails when actually running with AWS)

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 4]
```diff
@@ -2408,7 +2408,16 @@ class S3FileSystem::Impl : public std::enable_shared_from_this<S3FileSystem::Imp
                   std::vector<std::string> file_paths;
                   for (const auto& file_info : file_infos) {
                     DCHECK_GT(file_info.path().size(), bucket.size());
-                    file_paths.push_back(file_info.path().substr(bucket.size() + 1));
+                    auto file_path = file_info.path().substr(bucket.size() + 1);
+                    if (file_info.IsDirectory()) {
+                      // the selector returns FileInfo objects for directories with a
+                      // a path that never ends in a trailing slash, but for S3 the file
+                      // needs to have a trailing slash to recognize it as direcotory
+                      // (https://github.com/apache/arrow/issues/38618)
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.cc:2416]:
```suggestion
                      // The selector returns FileInfo objects for directories with a
                      // a path that never ends in a trailing slash, but for AWS the file
                      // needs to have a trailing slash to recognize it as directory
                      // (https://github.com/apache/arrow/issues/38618)
```

**Review by pitrou — APPROVED** [review]

**Review by felipecrv — APPROVED** [review]
