### PR TITLE
GH-34723: [Java] Enable log trace for Netty allocator memory usage

### LINKED ISSUE #34723: [Java] Incorrect memory usage log statement
### Describe the bug, including details regarding any error messages, version, and platform.

The log statement here:
https://github.com/apache/arrow/blob/45918a90a6ca1cf3fd67c256a7d6a240249e555a/java/memory/memory-netty/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java#L268

Outputs the incorrect log message.

Actual:
```
Memory Usage:
io.netty.buffer.PooledByteBufAllocatorL@7241d783
```

Expected: the output from `io.netty.buffer.PooledByteBufAllocatorL.InnerAllocator.toString()`, similar to:
```
Memory Usage:
1 direct arena(s):
SomeByteBuffer[pos=12 lim=34 cap=56]

Large buffers outstanding: 12 totaling 34 bytes.
Normal buffers outstanding: 56 totaling 78 bytes.
```

### Component(s)

Java

### PR DESCRIPTION
**Pull request by davisusanibar**
### Rationale for this change

To close https://github.com/apache/arrow/issues/34723

### What changes are included in this PR?

Enable log trace for Netty allocator memory usage 

### Are these changes tested?

New log enabled:

```xml
<configuration>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>

  <logger name="org.apache.arrow" additivity="false">
    <level value="trace" />
    <appender-ref ref="STDOUT" />
  </logger>

  <root level="trace">
    <appender-ref ref="STDOUT" />
  </root>

</configuration>
```

```java
try (ArrowBuf buf = new ArrowBuf(ReferenceManager.NO_OP, null,
    1024, new PooledByteBufAllocatorL().empty.memoryAddress())) {
  buf.memoryAddress();
}
```

Logs:

```
18:59:33.109 [allocation.logger] TRACE arrow.allocator - Memory Usage: 
32 direct arena(s):
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Chunk(s) at 0~25%:
none
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
small subpages:
Large buffers outstanding: 0 totaling 0 bytes.
Normal buffers outstanding: 0 totaling 0 bytes.
```

### Are there any user-facing changes?

No
* Closes: #34723

### CODE REVIEW

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 1]
```diff
@@ -1091,6 +1098,40 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+            Arrays.asList("Memory Usage: \n", "Large buffers outstanding: ", "Normal buffers outstanding: "),
+            Level.TRACE
+        );
+
+    assertTrue(contains);
+  }
+
+  class MemoryLogsAppender extends ListAppender<ILoggingEvent> {
+    public boolean contains(List<String> values, Level level) {
+      return list.stream()
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1125]: Just inline this? I don't see why we need a subclass and a method

File: java/memory/memory-netty/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java [hunk 2]
```diff
@@ -265,7 +265,7 @@ public MemoryStatusThread() {
       @Override
       public void run() {
         while (true) {
-          memoryLogger.trace("Memory Usage: \n{}", PooledByteBufAllocatorL.this.toString());
+          memoryLogger.trace("Memory Usage: \n{}", PooledByteBufAllocatorL.this.allocator);
```
Comment (lidavidm) [inline java/memory/memory-netty/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java:268]: Since this is a background thread, doesn't the test need to account for a potential race condition?

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 3]
```diff
@@ -1091,6 +1098,40 @@ public void testMemoryLeakWithReservation() throws Exception {
     }
   }
 
+  @Test
+  public void testMemoryUsage() {
+    MemoryLogsAppender memoryLogsAppender = new MemoryLogsAppender();
+    Logger logger = (Logger) LoggerFactory.getLogger("arrow.allocator");
+    logger.setLevel(Level.TRACE);
+    logger.addAppender(memoryLogsAppender);
+    memoryLogsAppender.start();
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1107]: This test will permanently add an appender to a global logger, can we remove the appender afterwards?

File: java/memory/memory-netty/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java (hunk 2 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java:268]: > Since this is a background thread, doesn't the test need to account for a potential race condition?

Oh, please could you help me how/when this method execute/run? Or Could you help me with an example about the current race condition problem? This will help me to understand in more detail how this run behind the scene.

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 3 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1108]: Added

File: java/memory/memory-netty/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java (hunk 2 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java:268]: Ok let's continue as it is now.

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 1 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Added

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 4]
```diff
@@ -1091,6 +1099,32 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+            .anyMatch(
+                log -> log.toString().contains(values.get(0)) &&
+                    log.toString().contains(values.get(1)) &&
+                    log.toString().contains(values.get(2)) &&
+                    log.getLevel().equals(level)
+            );
+    boolean result = listAppenderContains.apply(Arrays.asList("Memory Usage: \n", "Large buffers outstanding: ",
+            "Normal buffers outstanding: "),
+        Level.TRACE);
+    logger.detachAppender(memoryLogsAppender);
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1124]: this needs to be in a try-finally

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 5]
```diff
@@ -1091,6 +1099,32 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+        (List<String> values, Level level) -> memoryLogsAppender.list.stream()
+            .anyMatch(
+                log -> log.toString().contains(values.get(0)) &&
+                    log.toString().contains(values.get(1)) &&
+                    log.toString().contains(values.get(2)) &&
+                    log.getLevel().equals(level)
+            );
+    boolean result = listAppenderContains.apply(Arrays.asList("Memory Usage: \n", "Large buffers outstanding: ",
+            "Normal buffers outstanding: "),
+        Level.TRACE);
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1123]: Just write it as a loop...

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 6]
```diff
@@ -1091,6 +1099,32 @@ public void testMemoryLeakWithReservation() throws Exception {
     }
   }
 
+  @Test
+  public void testMemoryUsage() {
+    ListAppender<ILoggingEvent> memoryLogsAppender = new ListAppender<>();
+    Logger logger = (Logger) LoggerFactory.getLogger("arrow.allocator");
+    logger.setLevel(Level.TRACE);
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1106]: Reset the log level afterwards, too

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 7]
```diff
@@ -1091,6 +1099,32 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+    logger.addAppender(memoryLogsAppender);
+    memoryLogsAppender.start();
+    try (ArrowBuf buf = new ArrowBuf(ReferenceManager.NO_OP, null,
+        1024, new PooledByteBufAllocatorL().empty.memoryAddress())) {
+      buf.memoryAddress();
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1111]: What I'm saying is, you have no guarantee the logger will actually have logged anything by the time the next few lines run. So this is just adding a flaky test.

Comment (lidavidm) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1111]: And IMO, the easier way to test this would be to factor out a function that generates the log string, test that function, and use that function from the thread, rather than hooking into the physical logger.

**Review by lidavidm — CHANGES_REQUESTED** [review]

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 7 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Validation inside a loop

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 6 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Added

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 5 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Added

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 4 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Added

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 8]
```diff
@@ -1091,6 +1099,43 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+              .anyMatch(
+                  log -> log.toString().contains(values.get(0)) &&
+                      log.toString().contains(values.get(1)) &&
+                      log.toString().contains(values.get(2)) &&
+                      log.getLevel().equals(level)
+              );
+      boolean result = false;
+      long startTime = System.currentTimeMillis();
+      while (true && (System.currentTimeMillis() - startTime) < 20000) {
+        result = listAppenderContains.apply(Arrays.asList("Memory Usage: \n", "Large buffers outstanding: ",
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1125]: Again...why the lambda? Just write it out as a loop

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 9]
```diff
@@ -1091,6 +1099,43 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+          (List<String> values, Level level) -> memoryLogsAppender.list.stream()
+              .anyMatch(
+                  log -> log.toString().contains(values.get(0)) &&
+                      log.toString().contains(values.get(1)) &&
+                      log.toString().contains(values.get(2)) &&
+                      log.getLevel().equals(level)
+              );
+      boolean result = false;
+      long startTime = System.currentTimeMillis();
+      while (true && (System.currentTimeMillis() - startTime) < 20000) {
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1124]: Why the redundant condition?

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 10]
```diff
@@ -1091,6 +1099,43 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+                "Normal buffers outstanding: "), Level.TRACE);
+        if (result) {
+          break;
+        }
+      }
+      memoryLogsAppender.stop();
+      assertTrue(result);
+    } finally {
+      logger.detachAppender(memoryLogsAppender);
+      logger.setLevel(null);
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1135]: Shouldn't we reset it to what it originally was?

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 11]
```diff
@@ -1091,6 +1099,43 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+  public void testMemoryUsage() {
+    ListAppender<ILoggingEvent> memoryLogsAppender = new ListAppender<>();
+    Logger logger = (Logger) LoggerFactory.getLogger("arrow.allocator");
+    try {
+      logger.setLevel(Level.TRACE);
+      logger.addAppender(memoryLogsAppender);
+      memoryLogsAppender.start();
+      try (ArrowBuf buf = new ArrowBuf(ReferenceManager.NO_OP, null,
+          1024, new PooledByteBufAllocatorL().empty.memoryAddress())) {
+        buf.memoryAddress();
```
Comment (lidavidm) [inline java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1112]: Why can't we just use an allocator to create the buffer?

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 8 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Changed

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 9 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Moved inside de loop to try to read logs for 10 seconds maximum, then finished with error.

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java (hunk 10 above)
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java:1130]: Initially it was marked with null

File: java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java [hunk 12]
```diff
@@ -1091,6 +1097,40 @@ public void testMemoryLeakWithReservation() throws Exception {
...
+      long startTime = System.currentTimeMillis();
+      while (true) {
+        result = memoryLogsAppender.list.stream()
+            .anyMatch(
+                log -> log.toString().contains("Memory Usage: \n") &&
+                    log.toString().contains("Large buffers outstanding: ") &&
+                    log.toString().contains("Normal buffers outstanding: ") &&
+                    log.getLevel().equals(Level.TRACE)
+            );
+        if (result || (System.currentTimeMillis() - startTime) > 10000) { // 10 seconds maximum for time to write logs
```
[the remark this answers is not in the document]
Comment (davisusanibar) [reply java/memory/memory-netty/src/test/java/org/apache/arrow/memory/TestBaseAllocator.java]: Added

**Review by lidavidm — APPROVED** [review]
