### PR TITLE
GH-28994: [C++][JSON] Change the max rows to Unlimited(int_32) 

### LINKED ISSUE #28994: [C++][JSON] kMaxParserNumRows Value Increase/Removal
I'm a new pyArrow user and have been investigating occasional errors related to the Python exception: "ArrowInvalid: Exceeded maximum rows" when parsing JSON line files using pyarrow.json.read_json(). In digging in, it looks like the original source of this exception is in cpp/src/arrow/json/parser.cc on line 703, which appears to throw the error when the number of lines processed exceeds kMaxParserNumRows.
```java

for (; num_rows_ < kMaxParserNumRows; ++num_rows_) {
      auto ok = reader.Parse<parse_flags>(json, handler);
      switch (ok.Code()) {
        case rj::kParseErrorNone:
          // parse the next object
          continue;
        case rj::kParseErrorDocumentEmpty:
          // parsed all objects, finish
          return Status::OK();
        case rj::kParseErrorTermination:
          // handler emitted an error
          return handler.Error();
        default:
          // rj emitted an error
          return ParseError(rj::GetParseError_En(ok.Code()), " in row ", num_rows_);
      }
    }
    return Status::Invalid("Exceeded maximum rows");
  }
```
 

This constant appears to be set in arrow/json/parser.h on line 53, and has been set this way since that file's initial commit.
```java

constexpr int32_t kMaxParserNumRows = 100000;
```
 

There does not appear to be a comment in the code or in the commit or PR explaining this maximum number of lines.

 

I'm wondering what the reason for this maximum might be, and if it might be removed, increased, or made overridable in the C++ and the upstream Python. It is common to need to process JSON files of arbitrary length (logs from applications, third-party vendors, etc) where the user of the data does not have control over the size of the file.

**Reporter**: [Ryan Stalets](https://issues.apache.org/jira/browse/ARROW-13318)

<sub>**Note**: *This issue was originally created as [ARROW-13318](https://issues.apache.org/jira/browse/ARROW-13318). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by Ox0400**
### Rationale for this change
Unlimited parse max rows for parse json block. Raise `Row count overflowed int32_t` error when the loop times out of `init_32::max()`.

See issue: #28994

### What changes are included in this PR?
Delete const `kMaxParserNumRows`,  Minor code( C++ ) modifications and test code(python)

### Are these changes tested? Yes
New a test code for parse large (100100) rows json .

### Are there any user-facing changes?  No

* Closes: #28994

### CODE REVIEW

File: cpp/src/arrow/json/parser.cc [hunk 1]
```diff
@@ -46,6 +46,10 @@ namespace arrow {
 using internal::BitsetStack;
 using internal::checked_cast;
 
+static const char* kEnvJsonMaxNumRows = "ARROW_JSON_MAX_NUM_ROWS";
```
Comment (bkietz) [inline cpp/src/arrow/json/parser.cc:49]: Instead of exposing this as an environment variable, please add it to ReadOptions or ParseOptions.

File: python/pyarrow/tests/test_json.py [hunk 2]
```diff
@@ -322,6 +323,30 @@ def test_stress_block_sizes(self):
                         # Better error output
                         assert table.to_pydict() == expected.to_pydict()
 
+    def test_max_num_rows(self):
+        data, expected = make_random_json(num_cols=2, num_rows=10)
+        table = self.read_bytes(data)
+        assert table.num_rows == 10
+        with pytest.raises(pa.ArrowInvalid, match="Exceeded maximum rows"):
```
Comment (bkietz) [inline python/pyarrow/tests/test_json.py:330]: Instead of raising an error for exceeding the maximum number of rows, I think it'd be better to just skip the rest of the block. This is the behavior in CSV, which enables users to restrict expensive row processing to just a few rows in the case where only a few rows are required. If an error should be emitted instead that can be done after  checking the number of rows against the configured limit.

**Review by bkietz — CHANGES_REQUESTED** [review]
I'm not sure what the application is for this option in JSON parsing, and I'd lean toward removing it rather than making it configurable unless/until that capability is necessary to someone. (Unless I missed something, discussion on the issue did not reveal a use case for restricting json rows parsed per batch)

**Comment by Ox0400** [comment]
> I'm not sure what the application is for this option in JSON parsing, and I'd lean toward removing it rather than making it configurable unless/until that capability is necessary to someone. (Unless I missed something, discussion on the issue did not reveal a use case for restricting json rows parsed per batch)

🤔 You are right, will delete the limit for parse json.

File: cpp/src/arrow/json/parser.h [hunk 3]
```diff
@@ -56,7 +56,8 @@ struct Kind {
   static Status ForType(const DataType& type, Kind::type* kind);
 };
 
-constexpr int32_t kMaxParserNumRows = 100000;
+/// Set the max parse row is 2147483647.
+constexpr int32_t kMaxParserNumRows = std::numeric_limits<int32_t>::max();
```
Comment (bkietz) [inline cpp/src/arrow/json/parser.h:61]: IMO, it would be slightly more readable to use the limit directly below and modify the error return from "Exceeded maximum rows" to "Row count overflowed int32_t"
```suggestion
```

**Review by bkietz — APPROVED** [review]
This seems fine for now

File: cpp/src/arrow/json/parser.h (hunk 3 above)
Comment (Ox0400) [reply cpp/src/arrow/json/parser.h:61]: Hi @bkietz, thanks for your review. The error msg has update. 
I personally prefer to define the result of `int32_t::max()` as a constant in `parse.h` to be consistent with other constants. 
Do you suggest moving it to `parse.cc` or direct using it like `for (; num_rows_ < [kMaxParserNumRows](std::numeric_limits<int32_t>::max()); ++num_rows_) {}` on `parse.cc` ?

Comment (bkietz) [reply cpp/src/arrow/json/parser.h:62]: I think it's more readable with direct usage in this case; since the error message now explains that we are guarding against int32 overflow, we should make it clear inline that we are  checking against int32's max. A named constant can be introduced when we're limiting against something configurable instead of the numeric limits of int32.

Comment (Ox0400) [reply cpp/src/arrow/json/parser.h]: > I think it's more readable with direct usage in this case; since the error message now explains that we are guarding against int32 overflow, we should make it clear inline that we are checking against int32's max. A named constant can be introduced when we're limiting against something configurable instead of the numeric limits of int32.

Thank you for your explanation, I have removed the constant and now using it directly in the loop.

**Review by bkietz — APPROVED** [review]

**Comment by Ox0400** [comment]
Hi @bkietz, the CI some jobs is failed, some fail job look like because losted git runners. `The hosted runner: GitHub Actions 389 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.`

And one failed job it's same error with other PR CI job. 
```
Testing C ArrowArray from file 'map_non_canonical'
-- Skipping test because producer Java does not support C ArrowArray
======================================================================
Fatal Python error: Segmentation fault

Thread 0x00007fa43ba76640 (most recent call first):
  <no Python frame>

Thread 0x00007fa477307740 (most recent call first):
  File "/arrow/dev/archery/archery/integration/tester_java.py", line 154 in export_batch_from_json
  File "/arrow/dev/archery/archery/integration/runner.py", line 497 in do_run
  File "/arrow/dev/archery/archery/integration/runner.py", line 520 in _run_c_array_test_cases
  File "/arrow/dev/archery/archery/integration/runner.py", line 197 in case_wrapper
  File "/arrow/dev/archery/archery/integration/runner.py", line 206 in _run_test_cases
  File "/arrow/dev/archery/archery/integration/runner.py", line 435 in _compare_c_data_implementations
  File "/arrow/dev/archery/archery/integration/runner.py", line 129 in run_c_data
  File "/arrow/dev/archery/archery/integration/runner.py", line 638 in run_all_tests
  File "/arrow/dev/archery/archery/cli.py", line 787 in integration
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 783 in invoke
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1434 in invoke
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1688 in invoke
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1078 in main
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1157 in __call__
  File "/opt/conda/envs/arrow/bin/archery", line 33 in <module>

Extension modules: work._ruamel_yaml, _ruamel_yaml, _cffi_backend, _brotli, markupsafe._speedups, pygit2._pygit2, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, _jpype (total: 20)
/arrow/ci/scripts/integration_arrow.sh: line 62: 13169 Segmentation fault      (core dumped) archery integration --run-c-data --run-ipc --run-flight --with-cpp=$([ "$ARROW_INTEGRATION_CPP" == "ON" ] && echo "1" || echo "0") --with-csharp=$([ "$ARROW_INTEGRATION_CSHARP" == "ON" ] && echo "1" || echo "0") --with-go=$([ "$ARROW_INTEGRATION_GO" == "ON" ] && echo "1" || echo "0") --with-java=$([ "$ARROW_INTEGRATION_JAVA" == "ON" ] && echo "1" || echo "0") --with-js=$([ "$ARROW_INTEGRATION_JS" == "ON" ] && echo "1" || echo "0") --gold-dirs=$gold_dir/0.14.1 --gold-dirs=$gold_dir/0.17.1 --gold-dirs=$gold_dir/1.0.0-bigendian --gold-dirs=$gold_dir/1.0.0-littleendian --gold-dirs=$gold_dir/2.0.0-compression --gold-dirs=$gold_dir/4.0.0-shareddict

```
https://github.com/apache/arrow/actions/runs/6870662307/job/18685993426?pr=38721#step:8:17634
https://github.com/apache/arrow/actions/runs/6858477459/job/18674673496#step:8:17640

**Review by bkietz — CHANGES_REQUESTED** [review]
Most of the CI failures do seem unrelated.

However, could you ensure that the lint/format job passes? Also, please update the PR description since that's what winds up in the git log

**Comment by Ox0400** [comment]
> Most of the CI failures do seem unrelated.
> 
> However, could you ensure that the lint/format job passes? Also, please update the PR description since that's what winds up in the git log

Yes, am think so. The PR title & desc already updated.

**Comment by bkietz** [comment]
There's still a lingering python formatting error, then I think we can merge this https://github.com/apache/arrow/actions/runs/6858477451/job/18745903676#step:5:905

**Comment by Ox0400** [comment]
> There's still a lingering python formatting error, then I think we can merge this https://github.com/apache/arrow/actions/runs/6858477451/job/18745903676#step:5:905

Has recommitted the test code, plz review again.

**Review by bkietz — APPROVED** [review]
LGTM, will merge when CI completes

**Review by bkietz — CHANGES_REQUESTED** [review]
The linter needs one more change. Sorry for the churn; in the future I recommend getting the linter to pass locally so that iteration against CI isn't so tedious. https://arrow.apache.org/docs/developers/cpp/development.html#code-style-linting-and-ci

File: python/pyarrow/tests/test_json.py [hunk 4]
```diff
@@ -17,6 +17,7 @@
 
 from collections import OrderedDict
 from decimal import Decimal
+import os
```
[the remark this answers is not in the document]
Comment (Ox0400) [reply python/pyarrow/tests/test_json.py:20]: Oh, sorry .... 
I try `python3.10 -m pip install -e 'dev/archery[all]'` raise this error  `ERROR: dev/archery[all] is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp,  .....). `  ref: https://arrow.apache.org/docs/developers/python.html#coding-style

So I was run `pylint pyarrow/tests/test_json.py` on local not raise the error. I will remove the import.

[the remark this answers is not in the document]
Comment (Ox0400) [reply python/pyarrow/tests/test_json.py]: Hi @bkietz, fixed, plz try again, I have run `archery lint --python` on local and all passed.

```
➜  python git:(main) ✗ archery lint --python                           
INFO:archery:Running Python formatter (autopep8)
INFO:archery:Running Python linter (flake8)
INFO:archery:Running Cython linter (cython-lint)
➜  python git:(main) ✗ 
```

**Review by bkietz — APPROVED** [review]
