### PR TITLE
GH-37726: [Swift][FlightSQL] Update behavior to be similar to existing impls

### LINKED ISSUE #37726: [Swift][FlightSQL] Processing valid RecordBatch leads to invalid offset from body's data.
### Describe the bug, including details regarding any error messages, version, and platform.

**Bug**

During `FlightClient.doGet` call, `ArrowReader` process an empty `dataBody` on a valid flight data, raising `Fatal error: UnsafeRawBufferPointer.load with negative offset`. However, `dataHeader` is present.

---

**Details**

A valid flight call tested both in `python` and `rust` was also tested in the not yet released Swift package. The ticket is a simple `TEST` raw byte, in order for the server to start a simple stream of RecordBatch.

---

**Error Messages**

- Fatal error: UnsafeRawBufferPointer.load with negative offset

---

**System details**

- Using `Xcode Version 15.0 beta 8 (15A5229m)`
- Building for **Apple Vision Pro Simulator**.
- Swift-Driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1)

---

**Screenshots**

s1
s2

### Component(s)

Swift

### PR DESCRIPTION
**Pull request by abandy**
Swift Flight implementation behavior didn't match existing flight implementations.  The updates in this PR have been tested against python/examples/flight/server.py except for getSchemaTest and doExchangeTest which are not implemented in server.py.  I will follow up this PR with a cleanup refactoring PR.

This difference in behavior was found due to issue #37726.  
* Closes: #37726

### CODE REVIEW

**Comment by abandy** [comment]
Hi @kou, I apologize for the large review.  These changes are for a fix found in the attached issue.  I plan to follow up this change with a PR that I have ran swiftlint against to fix any whitespace/semicolon... issues.

File: swift/Arrow/Sources/Arrow/ArrowReader.swift [hunk 1]
```diff
@@ -200,4 +201,41 @@ public class ArrowReader {
             return .failure(.unknownError("Error loading file: \(error)"))
         }
     }
+
+    static public func MakeArrowReaderResult() -> ArrowReaderResult{
```
Comment (kou) [inline swift/Arrow/Sources/Arrow/ArrowReader.swift:205]:
```suggestion
    static public func MakeArrowReaderResult() -> ArrowReaderResult {
```

File: swift/Arrow/Sources/Arrow/ArrowWriter.swift [hunk 2]
```diff
@@ -38,7 +38,7 @@ public class ArrowWriter {
             self.data.append(data)
         }
     }
-
+
```
Comment (kou) [inline swift/Arrow/Sources/Arrow/ArrowWriter.swift:41]: Are this trailing spaces change and other similar changes intentional?

File: swift/ArrowFlight/Sources/ArrowFlight/FlightClient.swift [hunk 3]
```diff
@@ -28,6 +28,40 @@ public class FlightClient {
...
+        return arrowResult;
+    }
+    
+    private func writeBatches(_ requestStream: GRPCAsyncRequestStreamWriter<Arrow_Flight_Protocol_FlightData>, descriptor: FlightDescriptor, recordBatchs: [RecordBatch]) async throws {
+        let writer = ArrowWriter()
+        switch writer.toMessage(recordBatchs[0].schema) {
+        case .success(let schemaData):
+            try await requestStream.send(FlightData(schemaData, dataBody: Data(), flightDescriptor: descriptor).toProtocol())
+            for rc in recordBatchs {
+                switch writer.toMessage(rc) {
```
Comment (kou) [inline swift/ArrowFlight/Sources/ArrowFlight/FlightClient.swift:52]: `rc` -> `rb` ("R"ecord "B"atch) or `rc` -> `recordBatch` may be better.

File: swift/ArrowFlight/Sources/ArrowFlight/RecordBatchStreamReader.swift [hunk 4]
```diff
@@ -32,29 +33,35 @@ public class RecordBatchStreamReader: AsyncSequence, AsyncIteratorProtocol {
...
-                batches = rbResult.batches
-                batchIndex = 1
-                return batches[0]
+            let flightData = (streamData as! Arrow_Flight_Protocol_FlightData)
+            let dataBody = flightData.dataBody
+            let dataHeader = flightData.dataHeader
+            descriptor = FlightDescriptor(flightData.flightDescriptor)
+            switch reader.fromMessage(dataHeader, dataBody: dataBody, result: result) {
+            case .success(()):
+                if(result.batches.count > 0 ) {
```
Comment (kou) [inline swift/ArrowFlight/Sources/ArrowFlight/RecordBatchStreamReader.swift:60]:
```suggestion
                if result.batches.count > 0 {
```

File: swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift [hunk 5]
```diff
@@ -97,28 +102,33 @@ final class MyFlightServer : ArrowFlightServer {
...
         XCTAssertEqual(String(bytes: request.cmd, encoding: .utf8)!, "schema info")
         XCTAssertEqual(request.type, .cmd)
-        return try ArrowFlight.FlightSchemaResult(schemaToArrowStream(makeSchema()))
+        return try ArrowFlight.FlightSchemaResult(schemaToMessage(makeSchema()))
     }
     
     func getFlightInfo(_ request: ArrowFlight.FlightDescriptor) async throws -> ArrowFlight.FlightInfo {
-        return ArrowFlight.FlightInfo(Data())
+        let key = String(decoding: request.cmd, as: UTF8.self)
+        if(flights[key] != nil) {
```
Comment (kou) [inline swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift:110]:
```suggestion
        if flights[key] != nil {
```

File: swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift [hunk 6]
```diff
@@ -177,87 +187,104 @@ public class FlightClientTester {
...
+    func doActionTest(_ type: String, actionBody: Data) async throws {
+        let action = FlightAction(type, body: actionBody)
         var actionResults = [FlightResult]()
         try await client?.doAction(action, closure: { result in
             actionResults.append(result)
         })
         
-        XCTAssertEqual(actionResults.count, 1)
-        XCTAssertEqual(String(bytes:actionResults[0].body, encoding: .utf8), "test_action result")
+        XCTAssertEqual(actionResults.count, 0)
```
Comment (kou) [inline swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift:217]: It seems that this removes a test case for a `DoAction` that returns a result.
Is it intentional?

**Review by kou — COMMENTED** [review]
How about using the following steps instead of "merging this PR without SwiftLint and applying SwiftLint with a separated PR"?

1. PR1: Add a lint CI job
   * We can do it in https://github.com/apache/arrow/blob/main/ci/scripts/swift_test.sh
   * We can apply SwiftLint in PR1 to fix CI failure
   * We don't change any behavior in PR1 (Auto-generated changed by SwiftLint are only included in PR1)
2. PR2: Rebase this PR on main after PR1 is merged
   * Formatted changes are easier to review 
4. PR3: Add Swift to our integration test targets:
   * Add `tester_swift.py` to https://github.com/apache/arrow/tree/main/dev/archery/archery/integration
   * Enable the tester in https://github.com/apache/arrow/blob/main/dev/archery/archery/integration/runner.py#L534
   * Setup Swift in https://github.com/apache/arrow/blob/main/ci/docker/conda-integration.dockerfile

BTW, could you add a list of changed behavior in the description of this PR? It seems that no response cases are changed.

File: swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift (hunk 6 above)
Comment (abandy) [reply swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift:217]: This was intentional but I will put test case back.

File: swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift (hunk 5 above)
Comment (abandy) [reply swift/ArrowFlight/Tests/ArrowFlightTests/FlightTest.swift:110]: Will do.

File: swift/ArrowFlight/Sources/ArrowFlight/RecordBatchStreamReader.swift (hunk 4 above)
Comment (abandy) [reply swift/ArrowFlight/Sources/ArrowFlight/RecordBatchStreamReader.swift:60]: Will do.

File: swift/ArrowFlight/Sources/ArrowFlight/FlightClient.swift (hunk 3 above)
Comment (abandy) [reply swift/ArrowFlight/Sources/ArrowFlight/FlightClient.swift:52]: Will do.

File: swift/Arrow/Sources/Arrow/ArrowWriter.swift (hunk 2 above)
Comment (abandy) [reply swift/Arrow/Sources/Arrow/ArrowWriter.swift:41]: I wasn't too concerned with these style changes as I was going to follow up with a swiftlint PR.  Since we are planning on running swiftlint on the code as a prior PR to this one, then these will be resolved (should be) when swiftlint is run against the files.

File: swift/Arrow/Sources/Arrow/ArrowReader.swift (hunk 1 above)
Comment (abandy) [reply swift/Arrow/Sources/Arrow/ArrowReader.swift:205]: Will do

**Comment by abandy** [comment]
> How about using the following steps instead of "merging this PR without SwiftLint and applying SwiftLint with a separated PR"?
> 
> 1. PR1: Add a lint CI job
>    
>    * We can do it in https://github.com/apache/arrow/blob/main/ci/scripts/swift_test.sh
>    * We can apply SwiftLint in PR1 to fix CI failure
>    * We don't change any behavior in PR1 (Auto-generated changed by SwiftLint are only included in PR1)
> 2. PR2: Rebase this PR on main after PR1 is merged
>    
>    * Formatted changes are easier to review
> 3. PR3: Add Swift to our integration test targets:
>    
>    * Add `tester_swift.py` to https://github.com/apache/arrow/tree/main/dev/archery/archery/integration
>    * Enable the tester in https://github.com/apache/arrow/blob/main/dev/archery/archery/integration/runner.py#L534
>    * Setup Swift in https://github.com/apache/arrow/blob/main/ci/docker/conda-integration.dockerfile
> 
> BTW, could you add a list of changed behavior in the description of this PR? It seems that no response cases are changed.

Sounds good, I will give this a go.

**Comment by abandy** [comment]
@kou please review when you get a chance, thank you!

File: swift/ArrowFlight/Sources/ArrowFlight/FlightClient.swift (hunk 3 above)
Comment (kou) [reply swift/ArrowFlight/Sources/ArrowFlight/FlightClient.swift:62]: @abandy Could you check this?

Comment (abandy) [reply swift/ArrowFlight/Sources/ArrowFlight/FlightClient.swift:62]: Good catch, will update, thanks!

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
Oh, it seems that we still want to keep working on this PR.

**Comment by abandy** [comment]
@kou I had found that I had missed the requested change to revert the doActionTest and updated accordingly.  The PR is now ready.  I apologize for any confusion.

**Comment by kou** [comment]
OK. I'll merge this.

**Comment by abandy** [comment]
thank you!
