### PR TITLE
GH-37813: [R] add quoted_na argument to open_delim_dataset()

### LINKED ISSUE #37813: [R] read_delim_arrow recognizes empty string "" as NA but open_dataset does not
### Describe the bug, including details regarding any error messages, version, and platform.

I expected that the output from `read_delim_arrow` and `open_dataset` on the same CSV file should be equal. But empty string in the CSV file is being treated differently. 

In the reprex below, the empty string ("") from the CSV file is converted to \<NA\> when using `read_delim_arrow` . That does not occur when using `open_dataset`

Here goes a reprex. 
``` r
# Arrow read_delim_arrow recognizes empty string "" as NA
# open_dataset on the same data does not
# example

library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- data.frame(text = c('one', 'two', '', 'four'),
                 n = 1:4)
tfile <- tempfile()
write.csv(df, tfile,
          row.names = FALSE)

arrow_csv <- read_csv_arrow(tfile, as_data_frame = FALSE)
arrow_csv |> collect()
#> # A tibble: 4 × 2
#>   text      n
#>   <chr> <int>
#> 1 one       1
#> 2 two       2
#> 3 <NA>      3
#> 4 four      4

arrow_dataset <- open_dataset(tfile, format = 'csv')
arrow_dataset |> collect()
#> # A tibble: 4 × 2
#>   text       n
#>   <chr>  <int>
#> 1 "one"      1
#> 2 "two"      2
#> 3 ""         3
#> 4 "four"     4

sessionInfo()
#> R version 4.3.1 (2023-06-16)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.6 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
#> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: America/Sao_Paulo
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dplyr_1.1.2    arrow_12.0.1.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] vctrs_0.6.3       cli_3.6.1         knitr_1.43        rlang_1.1.1      
#>  [5] xfun_0.39         purrr_1.0.1       styler_1.10.1     generics_0.1.3   
#>  [9] assertthat_0.2.1  glue_1.6.2        bit_4.0.5         htmltools_0.5.5  
#> [13] fansi_1.0.4       rmarkdown_2.23    R.cache_0.16.0    tibble_3.2.1     
#> [17] evaluate_0.21     fastmap_1.1.1     yaml_2.3.7        lifecycle_1.0.3  
#> [21] compiler_4.3.1    fs_1.6.2          pkgconfig_2.0.3   rstudioapi_0.15.0
#> [25] R.oo_1.25.0       R.utils_2.12.2    digest_0.6.33     R6_2.5.1         
#> [29] utf8_1.2.3        tidyselect_1.2.0  reprex_2.0.2      pillar_1.9.0     
#> [33] magrittr_2.0.3    R.methodsS3_1.8.2 tools_4.3.1       withr_2.5.0      
#> [37] bit64_4.0.5
```

<sup>Created on 2023-09-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### Component(s)

R

### PR DESCRIPTION
**Pull request by thisisnic**
### Rationale for this change

The `open_delim_dataset()` family of functions were implemented to have the same arguments as the `read_delim_arrow()` functions where possible, but `quoted_na` was missed.

### What changes are included in this PR?

Adding `quoted_na` to those functions.

### Are these changes tested?

Yes 

### Are there any user-facing changes?

Yes

**This PR includes breaking changes to public APIs.**

Empty strings in input datasets now default to being read in by `open_delim_dataset()` and its derivates as NAs and not empty string

* Closes: #37813

### CODE REVIEW

File: r/tests/testthat/test-dataset-csv.R [hunk 1]
```diff
@@ -561,6 +561,18 @@ test_that("open_delim_dataset params passed through to open_dataset", {
 
   expect_named(ds, c("int", "dbl", "lgl", "chr", "fct", "ts"))
 
+  # quoted_na
+  dst_dir <- make_temp_dir()
+  dst_file <- file.path(dst_dir, "data.csv")
+  df <- data.frame(text = c("one", "two", "", "four"), num = 1:4)
+  write.csv(df, dst_file, row.names = FALSE, quote = FALSE)
```
Comment (paleolimbot) [inline r/tests/testthat/test-dataset-csv.R:568]: Is this the same as `write("one\ntwo\nthree\n\nfour")` (It might be a tiny bit clearer what's actually getting tested to just write the contents of the file or put it in a comment...I forget what all the arguments of `write.csv()` actually do!)

**Review by paleolimbot — APPROVED** [review]
Possibly a few opportunities for clarification but in general looks good to me!

File: r/tests/testthat/test-dataset-csv.R [hunk 2]
```diff
@@ -253,7 +253,7 @@ test_that("readr parse options", {
       tsv_dir,
       partitioning = "part",
       format = "text",
-      quo = "\"",
+      del = ","
```
[the remark this answers is not in the document]
Comment (thisisnic) [reply r/tests/testthat/test-dataset-csv.R:256]: Yep - because passing in a parameter as `quo` (not a valid parameter name) no longer constitutes a unique partial match to either the readr or arrow options, it is caught earlier on in input validation and so raises an "Unrecognized option" error instead of an "Ambiguous option" error.  This input validation is something it would be nice to refactor in another PR, but I figured here we just want to replace `quo` with something else that takes us down the "Ambiguous option" path to stick with the spirit of the test.

File: r/tests/testthat/test-dataset-csv.R (hunk 1 above)
Comment (thisisnic) [reply r/tests/testthat/test-dataset-csv.R]: Agreed, updated.
