### PR TITLE
GH-38254: [Java] Add reusable buffer getters to char/binary vectors

### LINKED ISSUE #38254: [Java] Allow passing pre-allocated buffers to VarCharVector
### Describe the bug, including details regarding any error messages, version, and platform.

Allow VarCharVector and LargeVarCharVector to let the caller take in a pre-allocated buffer. The Text class was originally designed for this purpose but VarCharVector does not currently let the caller supply their own Text object.

The purpose of this change would be to allow a caller iterating through a VarCharVector to re-use a buffer without having to do extra allocations.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by jduo**
### Rationale for this change
Provide a way for a user to reuse a buffer when iterating over byte-array-based ValueVectors to avoid excessive
reallocations.

### What changes are included in this PR?
Add a reusable buffer interface that can be populated by character and binary vectors to avoid allocations when consuming vector content.

Optimize getObject() on VarCharVector/LargeVarCharVector to avoid an extra allocation of a byte array (copy from ArrowBuf directly to the resulting Text).

### Are there any user-facing changes?

Yes.

**This PR includes breaking changes to public APIs.**

* Closes: #38254

### CODE REVIEW

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ * limitations under the License.
+ */
+
+package org.apache.arrow.memory;
+
+/**
+ * A lightweight, automatically expanding container for holding byte data.
+ * @param <ReturnTypeT> The type of the underlying buffer.
+ */
+public interface ReusableBuffer<ReturnTypeT> {
```
Comment (adamkennedy) [inline java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java:24]: Is the naming style ReturnTypeT used elsewhere? Or should we just use T

File: java/vector/src/main/java/org/apache/arrow/vector/FixedSizeBinaryVector.java [hunk 2]
```diff
@@ -116,6 +117,18 @@ public byte[] get(int index) {
...
   }
 
+  /**
+   * Read the value at the given position to the given output buffer.
+   * The caller is responsible for checking for nullity first.
+   *
+   * @param index position of element.
+   * @param outputBuffer the buffer to write into.
+   */
+  public void readBytes(int index, ReusableBuffer<?> outputBuffer) {
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/FixedSizeBinaryVector.java:127]: Why readBytes vs just overloading getObject? Or just "read"?

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java [hunk 3]
```diff
@@ -112,6 +113,20 @@ public byte[] get(int index) {
...
   }
 
+  /**
+   * Read the value at the given position to the given output buffer.
+   * The caller is responsible for checking for nullity first.
+   *
+   * @param index position of element.
+   * @param outputBuffer the buffer to write into.
+   */
+  public void readBytes(int index, ReusableBuffer<?> outputBuffer) {
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java:123]: Would we allow any reusable buffer here, when the reusable buffers may be specialized to byte vs string type

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java [hunk 4]
```diff
@@ -112,6 +113,20 @@ public byte[] get(int index) {
...
+    final long startOffset = getStartOffset(index);
+    final int dataLength =
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java:125]: Use getEndOffset instead? Do we need to worry about lengths exceeding max integer?

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarCharVector.java [hunk 5]
```diff
@@ -120,12 +123,28 @@ public byte[] get(int index) {
...
+  /**
+   * Read the value at the given position to the given output buffer.
+   * The caller is responsible for checking for nullity first.
+   *
+   * @param index position of element.
+   * @param outputBuffer the buffer to write into.
+   */
+  public void readBytes(int index, ReusableBuffer<?> outputBuffer) {
+    final long startOffset = getStartOffset(index);
+    final int dataLength =
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/LargeVarCharVector.java:145]: Similar to above comment, I thought main purpose of the Large variants was to allow for values larger than max integer.

**Comment by adamkennedy** [comment]
There's no unit tests written for these new classes, and we probably should have some.

File: java/vector/src/main/java/org/apache/arrow/vector/FixedSizeBinaryVector.java (hunk 2 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/FixedSizeBinaryVector.java:127]: I'll go with read(). Avoiding using getObject() since it sounds too much like it should return a value vs. populate a buffer.

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java (hunk 3 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java:123]: The idea is that users could implement ReusableBuffer on top of other byte-container types such as ByteBuffer or Netty ByteBuf objects.

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java (hunk 4 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java:125]: Oddly, getEndOffset() is part of BaseVariableWidthVector and _not_ part of BaseLargeVariableWidthVector, and BLVW doesn't extend VLW.

The existing getters on this class do the narrowing cast from long to int as well, so if this is a problem the scope is larger than this.

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableArrowBuf.java [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+package org.apache.arrow.vector.util;
+
+import org.apache.arrow.memory.ArrowBuf;
+import org.apache.arrow.memory.ReusableBuffer;
+
+/**
+ * A writable text buffer backed by an Arrow buffer.
+ */
+public class ReusableArrowBuf implements ReusableBuffer<ArrowBuf> {
+  private ArrowBuf buffer;
```
[the remark this answers is not in the document]
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableArrowBuf.java:27]: Actually it seems like the ArrowBuf version isn't really needed since the *Holder objects can be used to get ArrowBuf-slices.

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java (hunk 1 above)
Comment (jduo) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java]: Switched to T.

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableArrowBuf.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableArrowBuf.java]: Removed ReusableBuffer<ArrowBuf>

**Comment by jduo** [comment]
> There's no unit tests written for these new classes, and we probably should have some.

Added new tests.

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java (hunk 4 above)
Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java:125]: And I think that it's not possible for the current implementation to exceed `int`. However a Java 21+ memory module should actually be able to.

@danepitkin we should probably file some follow-up work for after your PR lands to shake out all the problems that are about to crop up.

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+  protected void setCapacity(int len, boolean keepData) {
+    if (bytes == null || bytes.length < len) {
+      if (bytes != null && keepData) {
+        bytes = Arrays.copyOf(bytes, Math.max(len, length << 1));
+      } else {
+        bytes = new byte[len];
+      }
+    }
+  }
+
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:79]: Does it make sense to have equals, toString, hashCode, etc. here?

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+  /**
+   * Set the buffer to the contents of the given ArrowBuf.
+   * The internal buffer must resize if it cannot fit the contents
+   * of the data.
+   *
+   * @param srcBytes  the data to copy from
+   * @param start     the first position of the new data
+   * @param len       the number of bytes of the new data
+   */
+  void set(ArrowBuf srcBytes, long start, int len);
```
[the remark this answers is not in the document]
Comment (jduo) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java:46]: I'll change ints to longs in this interface and its implementations here and in the read() function, but not cascade all the changes down to Text (for the length field and its inputs) and classes using Text.

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java (hunk 7 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:79]: I'm not sure what the implementation should be here for equals(). Should it be an identity, exact match on the array content and capacity, or an exact match on the valid content only?

Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:79]: Text overrides equals(), hashCode(), and toString(). Its equals() and hashCode() method are only on the valid section of the byte array. toString() wouldn't make sense to port to ReusableByteArray() since it is a higher-level interpretation of the data than just raw bytes (it encodes assuming it's UTF-8 byte content).

File: java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (lidavidm) [reply java/memory/memory-core/src/main/java/org/apache/arrow/memory/ReusableBuffer.java:46]: Yes, sounds good. Fixing the int-vs-long thing is going to be a bigger project but for brand-new interfaces it seems we should be able to use long from the start.

**Review by lidavidm — APPROVED** [review]

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java (hunk 7 above)
Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java]: I would say equals() can match Text (valid content only), and toString here could do something like base64 the bytes

**Comment by lidavidm** [comment]
I'm going to mark this a "breaking change" since `Text#getLength` now returns `long`

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java [hunk 9]
```diff
@@ -0,0 +1,130 @@
...
+    if (!(o instanceof ReusableByteArray)) {
+      return false;
+    }
+
+    final ReusableByteArray that = (ReusableByteArray) o;
+    if (this.getLength() != that.getLength()) {
+      return false;
+    }
+
+    // copied from Arrays.equals so we don'thave to copy the byte arrays
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:78]: OpenJDK is GPL, so we need to rewrite the code (though, yes, this is probably too trivial/can't be written many other ways)

That said, it doesn't look like it's directly copied? At least looking at the jdk11 source

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java [hunk 10]
```diff
@@ -0,0 +1,130 @@
...
+    int result = 1;
+    for (int i = 0; i < length; i++) {
+      result = 31 * result + bytes[i];
+    }
+
+    return result;
+  }
+
+  @Override
+  public String toString() {
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:108]: Can we add some simple unit tests of the new methods?

**Review by lidavidm — CHANGES_REQUESTED** [review]

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java (hunk 7 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java]: Done

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java (hunk 9 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:78]: This comment (and method implementation) were pulled from Text. I'm not too sure what to do about this.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:78]: oh %*(!

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:78]: Ok, it was introduced in c322cbf225b5da5e17ceec0e9e7373852bcba85c and that was contemporary with Java 7/Java 8 (Feb 2017). Looking at the OpenJDK source for both of those, it appears this is different than Arrays.equals in both (well, the algorithm is the same but it doesn't appear to be a copy-paste) so I think we're clear.

Can you remove the comments here and below?

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:78]: @danepitkin could you confirm my understanding here?

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java [hunk 11]
```diff
@@ -0,0 +1,130 @@
...
+  /**
+   * Sets the capacity of this object to <em>at least</em> <code>len</code> bytes. If the
+   * current buffer is longer, then the capacity and existing content of the buffer are unchanged.
+   * If <code>len</code> is larger than the current capacity, the Text object's capacity is
+   * increased to match.
+   *
+   * @param len      the number of bytes we need
+   * @param keepData should the old data be kept
+   */
+  protected void setCapacity(int len, boolean keepData) {
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:121]: Under what situation would we need to keep the existing data?

File: java/vector/src/main/java/org/apache/arrow/vector/FixedSizeBinaryVector.java [hunk 12]
```diff
@@ -116,6 +117,18 @@ public byte[] get(int index) {
...
   }
 
+  /**
+   * Read the value at the given position to the given output buffer.
+   * The caller is responsible for checking for nullity first.
+   *
+   * @param index position of element.
+   * @param outputBuffer the buffer to write into.
+   */
+  public void read(int index, ReusableBuffer<?> outputBuffer) {
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/FixedSizeBinaryVector.java:127]: I hate to bike shed, but since these names would end up in docs, auto-complete and API browsing...

Is "output" superfluous here, since it's a void method?

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java [hunk 13]
```diff
@@ -112,6 +113,20 @@ public byte[] get(int index) {
...
+   * Read the value at the given position to the given output buffer.
+   * The caller is responsible for checking for nullity first.
+   *
+   * @param index position of element.
+   * @param outputBuffer the buffer to write into.
+   */
+  public void read(int index, ReusableBuffer<?> outputBuffer) {
+    final long startOffset = getStartOffset(index);
+    final long dataLength =
+        offsetBuffer.getLong((long) (index + 1) * OFFSET_WIDTH) - startOffset;
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java:126]: Use getEndOffset instead here rather than reimplement?

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarCharVector.java [hunk 14]
```diff
@@ -120,12 +123,28 @@ public byte[] get(int index) {
    * @return Text object for non-null element, null otherwise
    */
   public Text getObject(int index) {
-    byte[] b = get(index);
-    if (b == null) {
+    assert index >= 0;
+    if (NULL_CHECKING_ENABLED && isSet(index) == 0) {
```
Comment (adamkennedy) [inline java/vector/src/main/java/org/apache/arrow/vector/LargeVarCharVector.java:127]: Won't this use of NULL_CHECKING_ENABLED completely change the behavior of this method? Instead of returning null it will return Text(null)?

It's a matter for a different PR, but I don't see how NULL_CHECKING_ENABLED is useful in any possible way, because it's global to all recursive dependencies of anything using Arrow for any purpose.

File: java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java (hunk 11 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/util/ReusableByteArray.java:121]: This method is ported from Text. It gets set to true when used by the append() method there.

File: java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java (hunk 13 above)
Comment (jduo) [reply java/vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java:126]: getEndOffset() is not implemented for Large*Vectors. I can use it for Var*Vector and write an implementation for Large*Vectors.

**Comment by lidavidm** [comment]
Can you rebase to pick up the compilation fix from this weekend?

**Review by lidavidm — APPROVED** [review]
