### PR TITLE
GH-39860: [C++] Expression ExecuteScalarExpression execute empty args function with a wrong result

### LINKED ISSUE #39860: [C++] Expression ExecuteScalarExpression execute empty args function with a wrong result
## Problem
We have some arrow-builtin functions with no arguments support, like random/count_all/hash_count_all.

When we use `call("random", {}, opts)` and execute the expression with `ExecuteScalarExpression(random_expr, cp::ExecBatch({}, 10))`, the result only output one row. What we expected is 10 rows array.
```c
 [
  0.5353881964857193
]
```
## Reproduce
```c
TEST(Expression, ExprWithNoArguments) {
   auto random_options = RandomOptions::FromSeed(/*seed=*/0);
   auto expr = call("random", {}, random_opts);
   ASSERT_OK_AND_ASSIGN(expr, expr.Bind(arrow::float64()));
  ASSERT_OK_AND_ASSIGN(auto out, ExecuteScalarExpression(
                                        expr, ExecBatch({}, 10)));
   std::cout << out.make_array()->ToString() << std::endl; // expect 10 rows but only get 1 row
}
```

## Reason
The `ExecuteScalarExpression` internal code do some checks like below:
```c
  bool all_scalar = true;
  for (size_t i = 0; i < arguments.size(); ++i) {
    ARROW_ASSIGN_OR_RAISE(
        arguments[i], ExecuteScalarExpression(call->arguments[i], input, exec_context));
    if (arguments[i].is_array()) {
      all_scalar = false;
    }
  }
```
The `all_scalar` will decide the output rows, if `all_scalar` is true, only output 1 row.
So we should consider the empty function arguments here? Or i missed some background here?

### Component(s)

C++

### PR DESCRIPTION
**Pull request by ZhangHuiGui**
### Rationale for this change

Try to fix #39860.

### What changes are included in this PR?

Deal with the call->arguments.size() == 0's condition in ExecuteScalarExpression when we call some functions
has no arguments, like (random, hash_count ...).

### Are these changes tested?

Yes

### Are there any user-facing changes?

No.
* Closes: #39860

### CODE REVIEW

File: cpp/src/arrow/compute/expression.cc [hunk 1]
```diff
@@ -750,15 +750,23 @@ Result<Datum> ExecuteScalarExpression(const Expression& expr, const ExecBatch& i
...
+  size_t num_args = call->arguments.size();
+  std::vector<Datum> arguments(num_args);
   bool all_scalar = true;
-  for (size_t i = 0; i < arguments.size(); ++i) {
-    ARROW_ASSIGN_OR_RAISE(
-        arguments[i], ExecuteScalarExpression(call->arguments[i], input, exec_context));
-    if (arguments[i].is_array()) {
-      all_scalar = false;
+
+  if (num_args) {
```
Comment (bkietz) [inline cpp/src/arrow/compute/expression.cc:757]: I'd prefer to see this special case produce an input length rather than modify all_scalar, to make the goal more clear:

```suggestion
  std::vector<Datum> arguments(call->arguments.size());
  
  bool all_scalar = true;
  for (size_t i = 0; i < arguments.size(); ++i) {
    ARROW_ASSIGN_OR_RAISE(
        arguments[i], ExecuteScalarExpression(call->arguments[i], input, exec_context));
    if (arguments[i].is_array()) {
      all_scalar = false;
    }
  }
  
  int64_t input_length;
  if (!arguments.empty() && all_scalar) {
    // all inputs are scalar, so use a 1-long batch to avoid
    // computing input.length equivalent outputs
    input_length = 1;
  } else {
    input_length = input.length;
  }
```

**Review by bkietz — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/compute/expression.cc (hunk 1 above)
Comment (ZhangHuiGui) [reply cpp/src/arrow/compute/expression.cc:757]: Agree, this is more reasonable.

File: cpp/src/arrow/compute/expression_test.cc [hunk 2]
```diff
@@ -863,6 +863,23 @@ TEST(Expression, ExecuteCall) {
...
+  Expression random_expr = call("random", {}, random_options);
+  ASSERT_OK_AND_ASSIGN(random_expr, random_expr.Bind(float64()));
+
+  ASSERT_OK_AND_ASSIGN(Datum actual, ExecuteScalarExpression(random_expr, input));
+  compute::ExecContext* exec_context = default_exec_context();
+  ASSERT_OK_AND_ASSIGN(auto function,
+                       exec_context->func_registry()->GetFunction("random"));
+  ASSERT_OK_AND_ASSIGN(Datum expected,
+                       function->Execute(input, &random_options, exec_context));
+  AssertDatumsEqual(actual, expected, /*verbose=*/true);
```
Comment (mapleFU) [inline cpp/src/arrow/compute/expression_test.cc:880]: Should we check the output length == 10 explicit?

**Review by bkietz — APPROVED** [review]
LGTM
