### PR TITLE
GH-33971: [C++] Fix AdaptiveIntBuilder to always populate data buffer

### LINKED ISSUE #33971: [Python] segfault when calling nbytes on empty table with dictionary field
### Describe the bug, including details regarding any error messages, version, and platform.

Using `pyarrow.Table.nbytes` on an empty table with a dictionary field causes a segmentation fault.

```python
import pyarrow as pa

schema = pa.schema(
    [
        pa.field("foo", pa.dictionary(pa.int32(), pa.string())),
    ]
)
table = pa.table({"foo": []}, schema=schema)

print(table.nbytes)  # segmentation fault  python
```

A few notes:
- `get_total_buffer_size` works (which is a good workaround for now)
- It works if the table has got one or more row (including nulls)
- It works if the table is empty but there are not dictionary fields
- I'm using `pyarrow==11.0.0` and Python 3.9.16 (but it is happening in `10.0.1` as well, so not a new bug)

### Component(s)

Python

### PR DESCRIPTION
**Pull request by westonpace**
If the AdaptiveIntBuilder was empty it would yield a null for the values buffer.  The byte_size.h utilities were not expecting this which led to the error reported in the issue.

Example:

```
>>> pa.array([], type=pa.dictionary(pa.int32(), pa.string())).buffers()
[None, None]
```
* Closes: #33971

### CODE REVIEW

File: cpp/src/arrow/array/array_dict_test.cc [hunk 1]
```diff
@@ -157,6 +157,18 @@ TYPED_TEST(TestDictionaryBuilder, MakeBuilder) {
   AssertArraysEqual(expected, *result);
 }
 
+TYPED_TEST(TestDictionaryBuilder, Empty) {
+  DictionaryBuilder<TypeParam> dictionary_builder;
+  ASSERT_OK_AND_ASSIGN(std::shared_ptr<Array> empty_arr, dictionary_builder.Finish());
+  std::shared_ptr<DictionaryArray> empty_dict_arr =
+      std::static_pointer_cast<DictionaryArray>(empty_arr);
```
Comment (pitrou) [inline cpp/src/arrow/array/array_dict_test.cc:164]: `checked_pointer_cast` here?

**Review by pitrou — CHANGES_REQUESTED** [review]
LGTM on the principle, just a nit.

File: cpp/src/arrow/array/array_dict_test.cc (hunk 1 above)
Comment (westonpace) [reply cpp/src/arrow/array/array_dict_test.cc]: Fixed in https://github.com/apache/arrow/pull/33994/commits/c2d0a3631d157698fb9cc78ae1bb8db852b92085#diff-b6db8f2d68f397dbb43cd18c35eaf00d28fea796dd870d7019ceafcf04eda7e7R164

**Review by lidavidm — APPROVED** [review]
