### PR TITLE
GH-34823: [C++][ORC] Fix ORC CHAR type mapping

### LINKED ISSUE #34823: [C++][ORC] Fix ORC CHAR type mapping
### Describe the bug, including details regarding any error messages, version, and platform.

Currently the ORC CHAR type is mapped to Arrow FIXED_SIZE_BINARY type. However, the meaning of length differs between these types. The length of ORC CHAR type means number of UTF8 characters while that of Arrow FIXED_SIZE_BINARY means number of bytes.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

Currently the ORC CHAR type is mapped to Arrow FIXED_SIZE_BINARY type. However, the meaning of length differs between these types. The length of ORC CHAR type means number of UTF8 characters while that of Arrow FIXED_SIZE_BINARY means number of bytes.

### What changes are included in this PR?

Use Arrow String type to read from ORC CHAR type.

### Are these changes tested?

Make sure all tests pass.

### Are there any user-facing changes?

Yes, the doc has been updated as well.
* Closes: #34823

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1

Do existing tests cover this case?

**Comment by wgtmac** [comment]
No, I don't think ORC VARCHAR type is covered by any test either.

**Comment by wgtmac** [comment]
Test failure seems related to https://github.com/apache/arrow/issues/34768

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 1]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+  auto batch = writer->createRowBatch(row_count);
+  auto struct_batch = internal::checked_cast<liborc::StructVectorBatch*>(batch.get());
+
+  // Verify that longer data will be truncated by ORC char and varchar types.
+  // In addition, ORC char type will pad the data with spaces if the data is shorter.
+  const std::vector<std::string> data = {"abcd", "ABCDEFGH"};
+  const std::vector<std::vector<std::string>> expected_data = {{"abcd  ", "ABCDEF"},
+                                                               {"abcd", "ABCDEF"}};
+
+  for (uint64_t col = 0; col < orc_type->getSubtypeCount(); col++) {
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:471]:
```suggestion
  for (uint64_t col = 0; col < orc_type->getSubtypeCount(); ++col) {
```

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 2]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+    auto str_batch =
+        internal::checked_cast<liborc::StringVectorBatch*>(struct_batch->fields[col]);
+    str_batch->hasNulls = false;
+    str_batch->numElements = row_count;
+    for (int64_t i = 0; i < row_count; ++i) {
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:476]: Should we use `row` instead of `i` here like the below loop?

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 3]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+      reinterpret_cast<const uint8_t*>(mem_stream.getData()),
+      static_cast<int64_t>(mem_stream.getLength())));
+  ASSERT_OK_AND_ASSIGN(
+      auto reader, adapters::orc::ORCFileReader::Open(in_stream, default_memory_pool()));
+  ASSERT_EQ(row_count, reader->NumberOfRows());
+  ASSERT_EQ(1, reader->NumberOfStripes());
+
+  EXPECT_OK_AND_ASSIGN(auto stripe_reader, reader->NextStripeReader(row_count));
+  std::shared_ptr<RecordBatch> record_batch;
+  ASSERT_TRUE(stripe_reader->ReadNext(&record_batch).ok());
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:495]: Can we use `ASSERT_OK()` here?

```suggestion
  ASSERT_OK(stripe_reader->ReadNext(&record_batch));
```

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 4]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+  ASSERT_NE(record_batch, nullptr);
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:496]: It seems that we use `expected, actual` order in this test.

```suggestion
  ASSERT_NE(nullptr, record_batch);
```

**Review by kou — COMMENTED** [review]
Thanks!

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 5]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+  ASSERT_EQ(row_count, reader->NumberOfRows());
+  ASSERT_EQ(1, reader->NumberOfStripes());
+
+  EXPECT_OK_AND_ASSIGN(auto stripe_reader, reader->NextStripeReader(row_count));
+  std::shared_ptr<RecordBatch> record_batch;
+  ASSERT_OK(stripe_reader->ReadNext(&record_batch));
+  ASSERT_NE(nullptr, record_batch);
+  ASSERT_EQ(row_count, record_batch->num_rows());
+
+  for (int col = 0; col < record_batch->num_columns(); col++) {
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:499]:
```suggestion
  for (int col = 0; col < record_batch->num_columns(); ++col) {
```

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 6]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+    auto str_array = checked_pointer_cast<StringArray>(record_batch->column(col));
+    for (int row = 0; row < row_count; row++) {
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:501]:
```suggestion
    for (int row = 0; row < row_count; ++row) {
```

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 7]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+      EXPECT_EQ(expected_data[col][row], str_array->GetString(row));
+    }
+  }
+  ASSERT_TRUE(stripe_reader->ReadNext(&record_batch).ok());
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:505]:
```suggestion
  ASSERT_OK(stripe_reader->ReadNext(&record_batch));
```

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 8]
```diff
@@ -453,6 +453,59 @@ TEST(TestAdapterRead, ReadIntAndStringFileMultipleStripes) {
...
+  ASSERT_EQ(record_batch, nullptr);
```
Comment (kou) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:506]:
```suggestion
  ASSERT_EQ(nullptr, record_batch);
```

**Review by kou — APPROVED** [review]
+1
