### PR TITLE
GH-34467: [R] Disable DuckDB tests on R versions < 4.0.0  

### LINKED ISSUE #34467: [R] Disable DuckDB tests on R versions < 4.0.0
### Describe the bug, including details regarding any error messages, version, and platform.

Tests in the Arrow R package involving DuckDB are failing for R < 4.0.0 due to a newly released version of DuckDB which uses a function from the `tools` package which was only introduced in `tools` 4.0.0; see https://github.com/duckdb/duckdb/issues/6589.  

We should skip DuckDB tests on these builds for now; we can re-enable them at a later point if supporting Arrow with DuckDB on old R versions is thought to be a priority and we implement a workaround, or DuckDB release their own fix.

### Component(s)

R

### PR DESCRIPTION
**Pull request by thisisnic**
This PR skips DuckDB tests on older versions of R.
* Closes: #34467

### CODE REVIEW

**Comment by eitsupi** [comment]
Maybe the following example test should also not be run < R 4.0?
https://github.com/apache/arrow/blob/3ca55cb258af6676f64d4dd11a84cf01bc9f7289/r/R/duckdb.R#L127-L138

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-versions

File: r/R/duckdb.R [hunk 1]
```diff
@@ -94,7 +94,8 @@ run_duckdb_examples <- function() {
     requireNamespace("duckdb", quietly = TRUE) &&
     packageVersion("duckdb") > "0.2.7" &&
     requireNamespace("dplyr", quietly = TRUE) &&
-    requireNamespace("dbplyr", quietly = TRUE)
+    requireNamespace("dbplyr", quietly = TRUE) &&
+    R.Version()$major >= 4
```
Comment (paleolimbot) [inline r/R/duckdb.R:98]: In `skip_r_older_than()` we use `getRversion()`, so maybe `getRversion() > "4.0.0"` for consistency?

**Review by paleolimbot — APPROVED** [review]
A suggestion about consistency in checking the R version, but other than that looks great! Thanks!

File: r/R/duckdb.R (hunk 1 above)
Comment (thisisnic) [reply r/R/duckdb.R]: Good catch!
