### PR TITLE
GH-46710: [C++] Fix ownership and lifetime issues in Dataset Writer

### LINKED ISSUE #45235: [C++] Fix ASAN issue in the arrow-dataset-dataset-writer-test
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/12739705161/job/35503788331?pr=45226

```
=================================================================
==9882==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x55777af7ebed in operator new(unsigned long) (/build/cpp/debug/arrow-dataset-dataset-writer-test+0x419bed) (BuildId: 22e936dc51f9bb18fc25ab7de9ec7c7ba97cc2c2)
    #1 0x55777b1376c0 in __gnu_cxx::new_allocator<std::shared_ptr<arrow::RecordBatch> >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/new_allocator.h:127:27
    #2 0x55777b13754c in std::allocator_traits<std::allocator<std::shared_ptr<arrow::RecordBatch> > >::allocate(std::allocator<std::shared_ptr<arrow::RecordBatch> >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:464:20
    #3 0x7f11941d29dc in std::_Deque_base<std::shared_ptr<arrow::RecordBatch>, std::allocator<std::shared_ptr<arrow::RecordBatch> > >::_M_allocate_node() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_deque.h:562:9
    #4 0x7f119420bdbd in std::_Deque_base<std::shared_ptr<arrow::RecordBatch>, std::allocator<std::shared_ptr<arrow::RecordBatch> > >::_M_create_nodes(std::shared_ptr<arrow::RecordBatch>**, std::shared_ptr<arrow::RecordBatch>**) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_deque.h:663:21
    #5 0x7f119420ae17 in std::_Deque_base<std::shared_ptr<arrow::RecordBatch>, std::allocator<std::shared_ptr<arrow::RecordBatch> > >::_M_initialize_map(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_deque.h:637:4
    #6 0x7f119420a2f4 in std::_Deque_base<std::shared_ptr<arrow::RecordBatch>, std::allocator<std::shared_ptr<arrow::RecordBatch> > >::_Deque_base() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_deque.h:439:9
    #7 0x7f119420a15f in std::deque<std::shared_ptr<arrow::RecordBatch>, std::allocator<std::shared_ptr<arrow::RecordBatch> > >::deque() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_deque.h:834:7
    #8 0x7f1194209e95 in arrow::dataset::internal::(anonymous namespace)::DatasetWriterFileQueue::DatasetWriterFileQueue(std::shared_ptr<arrow::Schema> const&, arrow::dataset::FileSystemDatasetWriteOptions const&, arrow::dataset::internal::(anonymous namespace)::DatasetWriterState*) /arrow/cpp/src/arrow/dataset/dataset_writer.cc:136:12
    #9 0x7f1194208165 in std::_MakeUniq<arrow::dataset::internal::(anonymous namespace)::DatasetWriterFileQueue>::__single_object std::make_unique<arrow::dataset::internal::(anonymous namespace)::DatasetWriterFileQueue, std::shared_ptr<arrow::Schema>&, arrow::dataset::FileSystemDatasetWriteOptions const&, arrow::dataset::internal::(anonymous namespace)::DatasetWriterState*&>(std::shared_ptr<arrow::Schema>&, arrow::dataset::FileSystemDatasetWriteOptions const&, arrow::dataset::internal::(anonymous namespace)::DatasetWriterState*&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:962:34
    #10 0x7f1194206a02 in arrow::dataset::internal::(anonymous namespace)::DatasetWriterDirectoryQueue::OpenFileQueue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /arrow/cpp/src/arrow/dataset/dataset_writer.cc:343:9
    #11 0x7f119418667a in arrow::dataset::internal::(anonymous namespace)::DatasetWriterDirectoryQueue::StartWrite(std::shared_ptr<arrow::RecordBatch> const&) /arrow/cpp/src/arrow/dataset/dataset_writer.cc:306:7
    #12 0x7f119417fcdd in arrow::dataset::internal::DatasetWriter::DatasetWriterImpl::DoWriteRecordBatch(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /arrow/cpp/src/arrow/dataset/dataset_writer.cc:660:27
    #13 0x7f119417c5b8 in arrow::dataset::internal::DatasetWriter::DatasetWriterImpl::WriteAndCheckBackpressure(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /arrow/cpp/src/arrow/dataset/dataset_writer.cc:539:14
    #14 0x7f119417b6ba in arrow::dataset::internal::DatasetWriter::DatasetWriterImpl::WriteRecordBatch(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::'lambda'()::operator()() /arrow/cpp/src/arrow/dataset/dataset_writer.cc:565:15
    #15 0x7f1194179b2b in arrow::util::AsyncTaskScheduler::SimpleTask<arrow::dataset::internal::DatasetWriter::DatasetWriterImpl::WriteRecordBatch(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::'lambda'()>::operator()() /arrow/cpp/src/arrow/util/async_util.h:153:53
    #16 0x7f117fb90b19 in arrow::util::(anonymous namespace)::AsyncTaskGroupImpl::AddTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >)::WrapperTask::operator()() /arrow/cpp/src/arrow/util/async_util.cc:433:9
    #17 0x7f117fb7d938 in arrow::util::(anonymous namespace)::ThrottledAsyncTaskSchedulerImpl::SubmitTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >, int, bool)::'lambda'()::operator()() /arrow/cpp/src/arrow/util/async_util.cc:351:11
    #18 0x7f117fb7d356 in arrow::util::AsyncTaskScheduler::SimpleTask<arrow::util::(anonymous namespace)::ThrottledAsyncTaskSchedulerImpl::SubmitTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >, int, bool)::'lambda'()>::operator()() /arrow/cpp/src/arrow/util/async_util.h:153:53
    #19 0x7f117fb57813 in arrow::util::(anonymous namespace)::AsyncTaskSchedulerImpl::DoSubmitTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >) /arrow/cpp/src/arrow/util/async_util.cc:197:38
    #20 0x7f117fb55d31 in arrow::util::(anonymous namespace)::AsyncTaskSchedulerImpl::SubmitTaskUnlocked(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >, std::unique_lock<std::mutex>&&) /arrow/cpp/src/arrow/util/async_util.cc:267:12
    #21 0x7f117fb5548d in arrow::util::(anonymous namespace)::AsyncTaskSchedulerImpl::AddTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >) /arrow/cpp/src/arrow/util/async_util.cc:173:5
    #22 0x7f117fb7bf9a in bool arrow::util::AsyncTaskScheduler::AddSimpleTask<arrow::util::(anonymous namespace)::ThrottledAsyncTaskSchedulerImpl::SubmitTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >, int, bool)::'lambda'()>(arrow::util::(anonymous namespace)::ThrottledAsyncTaskSchedulerImpl::SubmitTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >, int, bool)::'lambda'(), std::basic_string_view<char, std::char_traits<char> >) /arrow/cpp/src/arrow/util/async_util.h:171:12
    #23 0x7f117fb7544b in arrow::util::(anonymous namespace)::ThrottledAsyncTaskSchedulerImpl::SubmitTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >, int, bool) /arrow/cpp/src/arrow/util/async_util.cc:348:21
    #24 0x7f117fb7216a in arrow::util::(anonymous namespace)::ThrottledAsyncTaskSchedulerImpl::AddTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >) /arrow/cpp/src/arrow/util/async_util.cc:331:14
    #25 0x7f117fb87b6f in arrow::util::(anonymous namespace)::AsyncTaskGroupImpl::AddTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >) /arrow/cpp/src/arrow/util/async_util.cc:446:21
    #26 0x7f117fb999f8 in arrow::util::ThrottledAsyncTaskGroup::AddTask(std::unique_ptr<arrow::util::AsyncTaskScheduler::Task, std::default_delete<arrow::util::AsyncTaskScheduler::Task> >) /arrow/cpp/src/arrow/util/async_util.cc:511:25
    #27 0x7f119417796a in bool arrow::util::AsyncTaskScheduler::AddSimpleTask<arrow::dataset::internal::DatasetWriter::DatasetWriterImpl::WriteRecordBatch(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::'lambda'()>(arrow::dataset::internal::DatasetWriter::DatasetWriterImpl::WriteRecordBatch(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::'lambda'(), std::basic_string_view<char, std::char_traits<char> >) /arrow/cpp/src/arrow/util/async_util.h:171:12
    #28 0x7f119416c4cb in arrow::dataset::internal::DatasetWriter::DatasetWriterImpl::WriteRecordBatch(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /arrow/cpp/src/arrow/dataset/dataset_writer.cc:562:19
    #29 0x7f119416bdec in arrow::dataset::internal::DatasetWriter::WriteRecordBatch(std::shared_ptr<arrow::RecordBatch>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /arrow/cpp/src/arrow/dataset/dataset_writer.cc:725:17
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

The dataset writer currently uses raw pointers of the pieces of state it needs to track, even though some of this state is accessed in async callbacks that might run at arbitrary points in time (especially in the case an error forces an early return of the synchronously running logic).

### What changes are included in this PR?

This PR strives to strengthen the dataset writer code by using safe pointers everywhere possible, and also trying to guard against potential leaks due to cyclic shared_ptr references.

Besides making it potentially more robust, it should also make future maintenance and evolutions easier.

This PR seems to fix #45235, though it will have to be confirmed after multiple CI runs.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.

* GitHub Issue: #46710

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@zanmato1984 Would you have time to look at this? I fear that not many devs are able to review this code...

**Comment by pitrou** [comment]
Also cc @bkietz

**Comment by zanmato1984** [comment]
Sorry for being late. I'm actually reviewing this today. Didn't touch much of this part of the code so it may take some time.

**Comment by pitrou** [comment]
Thank you! I'll rebase to get a newer baseline for CI.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

File: cpp/src/arrow/dataset/dataset_writer.cc [hunk 1]
```diff
@@ -217,21 +227,26 @@ class DatasetWriterFileQueue {
   Status Finish() {
     writer_state_->staged_rows_count -= rows_currently_staged_;
     while (!staged_batches_.empty()) {
-      RETURN_NOT_OK(PopAndDeliverStagedBatch());
+      auto st = PopAndDeliverStagedBatch().status();
+      if (!st.ok()) {
+        file_tasks_.reset();
+        return st;
+      }
```
Comment (zanmato1984) [inline cpp/src/arrow/dataset/dataset_writer.cc:234]:
```suggestion
      RETURN_NOT_OK_ELSE(PopAndDeliverStagedBatch(), file_tasks_.reset());
```

File: cpp/src/arrow/util/async_util.cc [hunk 2]
```diff
@@ -316,15 +316,11 @@ class ThrottledAsyncTaskSchedulerImpl
...
-      maybe_backoff->AddCallback(
-          [weak_self = std::weak_ptr<ThrottledAsyncTaskSchedulerImpl>(
-               shared_from_this())](const Status& st) {
-            if (st.ok()) {
-              if (auto self = weak_self.lock()) {
-                self->ContinueTasks();
-              }
-            }
-          });
+      maybe_backoff->AddCallback([weak_self = weak_from_this()](const Status& st) {
```
Comment (zanmato1984) [inline cpp/src/arrow/util/async_util.cc:319]: Just for the record, this is a style only change right?

File: cpp/src/arrow/util/async_util.cc [hunk 3]
```diff
@@ -350,8 +346,9 @@ class ThrottledAsyncTaskSchedulerImpl
          self = shared_from_this()]() mutable -> Result<Future<>> {
           ARROW_ASSIGN_OR_RAISE(Future<> inner_fut, (*inner_task)());
           if (!inner_fut.TryAddCallback([&] {
-                return [latched_cost, self = std::move(self)](const Status& st) -> void {
-                  if (st.ok()) {
+                return [latched_cost,
+                        weak_self = self->weak_from_this()](const Status& st) -> void {
```
Comment (zanmato1984) [inline cpp/src/arrow/util/async_util.cc:350]: Why change to capturing a weak ptr? Will capturing shared ptr cause any problem?

File: cpp/src/arrow/util/async_util.cc [hunk 4]
```diff
@@ -377,8 +375,8 @@ class ThrottledAsyncTaskSchedulerImpl
       if (maybe_backoff) {
         lk.unlock();
         if (!maybe_backoff->TryAddCallback([&] {
-              return [self = shared_from_this()](const Status& st) {
-                if (st.ok()) {
+              return [weak_self = weak_from_this()](const Status& st) {
```
Comment (zanmato1984) [inline cpp/src/arrow/util/async_util.cc:378]: Ditto.

File: cpp/src/arrow/dataset/dataset_writer.cc [hunk 5]
```diff
@@ -520,11 +543,26 @@ class DatasetWriter::DatasetWriterImpl {
...
-                      CalculateMaxRowsStaged(max_rows_queued)),
+        writer_state_(std::make_shared<DatasetWriterState>(
+            max_rows_queued, write_options_.max_open_files,
+            CalculateMaxRowsStaged(max_rows_queued))),
         pause_callback_(std::move(pause_callback)),
         resume_callback_(std::move(resume_callback)) {}
 
+  ~DatasetWriterImpl() {
+    // In case something went wrong (e.g. an IO error occurred), some tasks
+    // may be left dangling in a ThrottledAsyncTaskScheduler and that may
```
Comment (zanmato1984) [inline cpp/src/arrow/dataset/dataset_writer.cc:554]: How are such tasks left dangling exactly?

File: cpp/src/arrow/util/async_util.cc (hunk 2 above)
Comment (pitrou) [reply cpp/src/arrow/util/async_util.cc:319]: Yes. `weak_from_this` is much nicer than the pre-C++17 incantation.

File: cpp/src/arrow/util/async_util.cc (hunk 3 above)
Comment (pitrou) [reply cpp/src/arrow/util/async_util.cc:350]: Potential reference cycles through captured shared_ptr in async closures, yes. Not sure this is a problem currently, but it could certainly become one.

File: cpp/src/arrow/dataset/dataset_writer.cc (hunk 5 above)
Comment (pitrou) [reply cpp/src/arrow/dataset/dataset_writer.cc:554]: Honestly I haven't tried to analyze this very deeply. It might be the `file_finish_task` actually? In any case, this is necessary to suppress the memory leaks in error cases.

File: cpp/src/arrow/dataset/dataset_writer.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/dataset/dataset_writer.cc:234]: I had forgotten about this little-used macro. I honestly find it a bit confusing, I had to look up the definition to ensure I understood the semantics correctly.

Comment (zanmato1984) [reply cpp/src/arrow/dataset/dataset_writer.cc:234]: I agree the name is confusing. I do believe when given a less confusing name, this can be an actually useful macro. How about we rename it to something like `RETURN_NOT_OK_AFTER` (in follow-up PR)?

File: cpp/src/arrow/util/async_util.cc (hunk 3 above)
Comment (zanmato1984) [reply cpp/src/arrow/util/async_util.cc:350]: Hmm, what about the shared ptr captured in line 346?

File: cpp/src/arrow/dataset/dataset_writer.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/dataset/dataset_writer.cc:234]: Well, I'm not sure `RETURN_NOT_OK_AFTER` would be much less confusing, honestly.
I wonder if we can add some kind of functional API to `Status`, for example:
```c++
      RETURN_NOT_OK(PopAndDeliverStagedBatch().OrElse([&] { file_tasks_.reset() }));
```

File: cpp/src/arrow/util/async_util.cc (hunk 3 above)
Comment (pitrou) [reply cpp/src/arrow/util/async_util.cc:350]: At that point, it seems the `AddSimpleTask` call will always be synchronous (it calls the underlying non-throttled `AsyncTaskScheduler`). What do you think?

Comment (zanmato1984) [reply cpp/src/arrow/util/async_util.cc:350]: OK. It does seem so. Thanks.

**Review by zanmato1984 — APPROVED** [review]
Though we are not sure about how exactly this fix addresses the issue, I think it's generally safe and improves the life-cycle safety. +1.

**Comment by pitrou** [comment]
Thanks for the review @zanmato1984 !
