### PR TITLE
GH-39163: [C++] Add missing data copy in StreamDecoder::Consume(data)

### LINKED ISSUE #39163: [C++] `arrow::ipc::StreamDecoder` may return a broken RecordBatch with `Consume(const uint8_t* data, int64_t size)` API
### Describe the bug, including details regarding any error messages, version, and platform.

`arrow::ipc::StreamDecoder::Consume(const uint8_t* data, int64_t size)` can't assume the given data is still valid after the next `Consume(const uint8_t* data, int64_t size)` call. So we need to copy the given data for metadata message. Because the metadata message is used in the next body message. The next body message may be happen in the next `Consume(const uint8_t* data, int64_t size)` call.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We need to copy data for metadata message. Because it may be used in subsequent `Consume(data)` calls. We can't assume that the given `data` is still valid in subsequent `Consume(data)`.

We also need to copy buffered `data` because it's used in subsequent `Consume(data)` calls.

### What changes are included in this PR?

* Add missing copies.
* Clean up existing buffer copy codes.
* Change tests to use ephemeral `data` to detect this case.
* Add `copy_record_batch` option to `CollectListener` to copy decoded record batches.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.

* Closes: #39163

### CODE REVIEW

File: cpp/src/arrow/ipc/message.cc [hunk 1]
```diff
@@ -830,8 +849,7 @@ class MessageDecoder::MessageDecoderImpl {
       }
       buffered_size_ -= next_required_size_;
     } else {
-      ARROW_ASSIGN_OR_RAISE(auto metadata, AllocateBuffer(next_required_size_, pool_));
-      metadata_ = std::shared_ptr<Buffer>(metadata.release());
+      ARROW_ASSIGN_OR_RAISE(metadata_, AllocateBuffer(next_required_size_, pool_));
```
Comment (kou) [inline cpp/src/arrow/ipc/message.cc:852]: This is just a clean up. This is not related to this fix.

File: cpp/src/arrow/ipc/message.cc [hunk 2]
```diff
@@ -846,9 +864,8 @@ class MessageDecoder::MessageDecoderImpl {
     next_required_size_ = skip_body_ ? 0 : body_length;
     RETURN_NOT_OK(listener_->OnBody());
     if (next_required_size_ == 0) {
-      ARROW_ASSIGN_OR_RAISE(auto body, AllocateBuffer(0, pool_));
-      std::shared_ptr<Buffer> shared_body(body.release());
-      return ConsumeBody(&shared_body);
+      auto body = std::make_shared<Buffer>(nullptr, 0);
+      return ConsumeBody(&body);
```
Comment (kou) [inline cpp/src/arrow/ipc/message.cc:868]: This is just a clean up. This is not related to this fix.

File: cpp/src/arrow/ipc/message.cc [hunk 3]
```diff
@@ -872,10 +889,10 @@ class MessageDecoder::MessageDecoderImpl {
       buffered_size_ -= used_size;
       return Status::OK();
     } else {
-      ARROW_ASSIGN_OR_RAISE(auto body, AllocateBuffer(next_required_size_, pool_));
+      ARROW_ASSIGN_OR_RAISE(std::shared_ptr<Buffer> body,
+                            AllocateBuffer(next_required_size_, pool_));
       RETURN_NOT_OK(ConsumeDataChunks(next_required_size_, body->mutable_data()));
-      std::shared_ptr<Buffer> shared_body(body.release());
-      return ConsumeBody(&shared_body);
+      return ConsumeBody(&body);
```
Comment (kou) [inline cpp/src/arrow/ipc/message.cc:895]: This is just a clean up. This is not related to this fix.

File: cpp/src/arrow/ipc/reader.h [hunk 4]
```diff
@@ -317,7 +317,12 @@ class ARROW_EXPORT Listener {
 /// \since 0.17.0
 class ARROW_EXPORT CollectListener : public Listener {
  public:
-  CollectListener() : schema_(), filtered_schema_(), record_batches_(), metadatas_() {}
+  CollectListener(bool copy_record_batch = false)
```
Comment (kou) [inline cpp/src/arrow/ipc/reader.h:320]: I'm not sure this is a good API...
Should we create a new `CopyCollectListener` or something instead?

File: cpp/src/arrow/ipc/reader.cc [hunk 5]
```diff
@@ -2052,6 +2052,39 @@ Status Listener::OnRecordBatchWithMetadataDecoded(
   return OnRecordBatchDecoded(std::move(record_batch_with_metadata.batch));
 }
 
+namespace {
+Status CopyArrayData(std::shared_ptr<ArrayData> data) {
```
Comment (kou) [inline cpp/src/arrow/ipc/reader.cc:2056]: Maybe, we should not do this...

Comment (mapleFU) [reply cpp/src/arrow/ipc/reader.cc:2056]: Would `ArrayData*` be better in this place?

Comment (kou) [reply cpp/src/arrow/ipc/reader.cc:2056]: Good catch!
It will reduce reference count related cost.
I'll do it after we get a consensus with this copy approach is reasonable. (I hope that we have better approach...)

**Comment by kou** [comment]
@pitrou @felipecrv Do you have any opinion for this approach?

File: cpp/src/arrow/ipc/reader.h [hunk 6]
```diff
@@ -317,7 +317,12 @@ class ARROW_EXPORT Listener {
 /// \since 0.17.0
 class ARROW_EXPORT CollectListener : public Listener {
  public:
-  CollectListener() : schema_(), filtered_schema_(), record_batches_(), metadatas_() {}
+  explicit CollectListener(bool copy_record_batch = false)
```
Comment (pitrou) [inline cpp/src/arrow/ipc/reader.h:320]: I don't understand why this is needed. Can you elaborate?

File: cpp/src/arrow/ipc/read_write_test.cc [hunk 7]
```diff
@@ -1334,7 +1334,7 @@ struct StreamDecoderWriterHelper : public StreamWriterHelper {
   Status ReadBatches(const IpcReadOptions& options, RecordBatchVector* out_batches,
                      ReadStats* out_stats = nullptr,
                      MetadataVector* out_metadata_list = nullptr) override {
-    auto listener = std::make_shared<CollectListener>();
+    auto listener = std::make_shared<CollectListener>(true);
```
Comment (pitrou) [inline cpp/src/arrow/ipc/read_write_test.cc:1337]: Please mention the parameter name
```suggestion
    auto listener = std::make_shared<CollectListener>(/*xxx=*/ true);
```

Comment (pitrou) [reply cpp/src/arrow/ipc/read_write_test.cc:1337]: Also, why do we set it to true here? Can you add a comment?

File: cpp/src/arrow/ipc/reader.h (hunk 6 above)
Comment (kou) [reply cpp/src/arrow/ipc/reader.h:320]: Oh, sorry. My comment was outdated: https://github.com/apache/arrow/pull/39164#discussion_r1421772936

But it doesn't elaborate enough...

`StreamDecoder::Consume(const uint8_t* data, int64_t size)` (not `Consume(Buffer* buffer)`) assumes that the given `data` is alive while `Consume()` is calling. (The `data` may be freed after `Consume()` call is finished.)
So decoded record batches that are passed to `Listener` are valid while `Consume()` is calling. But `CollectListener` keeps decoded record batches after `Consume()` is finished. If we want to make decoded record batches are valid after `Consume()` call, we need to copy these record batches.

This is only happen with `Consume(const uint8_t* data, int64_t size)`. This is not happen with `Consume(Buffer* buffer)` because it refers the given `buffer`. So I want to avoid copying all decoded record batches. This is why I added `copy_record_batch` option here.

I hope that this explains why...

File: cpp/src/arrow/ipc/message.cc [hunk 8]
```diff
@@ -626,10 +626,24 @@ class MessageDecoder::MessageDecoderImpl {
...
-            auto buffer = std::make_shared<Buffer>(data, next_required_size_);
+            // We need to copy metadata because it's used in
+            // ConsumeBody(). ConsumeBody() may be called from another
+            // ConsumeData(). We can't assume that the given data for
+            // the current ConsumeData() call is still valid in the
+            // next ConsumeData() call. So we need to copy metadata
+            // here.
+            ARROW_ASSIGN_OR_RAISE(std::shared_ptr<Buffer> buffer,
+                                  AllocateBuffer(next_required_size_, pool_));
+            memcpy(buffer->mutable_data(), data, next_required_size_);
```
Comment (felipecrv) [inline cpp/src/arrow/ipc/message.cc:637]: Wouldn't this be solved more elegantly by changing `ConsumeMetadataBuffer`?

```diff
   Status ConsumeMetadataBuffer(const std::shared_ptr<Buffer>& buffer) {
-    if (buffer->is_cpu()) {
-      metadata_ = buffer;
-    } else {
       ARROW_ASSIGN_OR_RAISE(metadata_,
                             Buffer::ViewOrCopy(buffer, CPUDevice::memory_manager(pool_)));
-    }
     return ConsumeMetadata();
   }
```

Comment (kou) [reply cpp/src/arrow/ipc/message.cc:637]: It works but it causes needless copy with `Consume(buffer)` API.

If we use `Buffer::ViewOrCopy()` for copying a buffer, we should do this in `Consume(data, size)`:

```diff
diff --git a/cpp/src/arrow/ipc/message.cc b/cpp/src/arrow/ipc/message.cc
index fbcd6f139b..351fa6c6db 100644
--- a/cpp/src/arrow/ipc/message.cc
+++ b/cpp/src/arrow/ipc/message.cc
@@ -632,9 +632,10 @@ class MessageDecoder::MessageDecoderImpl {
             // the current ConsumeData() call is still valid in the
             // next ConsumeData() call. So we need to copy metadata
             // here.
-            ARROW_ASSIGN_OR_RAISE(std::shared_ptr<Buffer> buffer,
-                                  AllocateBuffer(next_required_size_, pool_));
-            memcpy(buffer->mutable_data(), data, next_required_size_);
+            ARROW_ASSIGN_OR_RAISE(
+                auto buffer,
+                Buffer::ViewOrCopy(std::make_shared<Buffer>(data, next_required_size_),
+                                   CPUDevice::memory_manager(pool_)));
             RETURN_NOT_OK(ConsumeMetadataBuffer(buffer));
           } break;
           case State::BODY: {
```

BTW, we should use `arrow::default_cpu_memory_manager()` for `arrow::default_memory_pool()`... I'll open a issue for it later.

```diff
diff --git a/cpp/src/arrow/ipc/message.cc b/cpp/src/arrow/ipc/message.cc
index fbcd6f139b..a0005a0e59 100644
--- a/cpp/src/arrow/ipc/message.cc
+++ b/cpp/src/arrow/ipc/message.cc
@@ -607,6 +607,7 @@ class MessageDecoder::MessageDecoderImpl {
                               MemoryPool* pool, bool skip_body)
       : listener_(std::move(listener)),
         pool_(pool),
+        memory_manager_(pool_ == default_memory_pool() ? default_cpu_memory_manager() : CPUDevice::memory_manager(pool_)),
         state_(initial_state),
         next_required_size_(initial_next_required_size),
         chunks_(),
@@ -823,7 +824,7 @@ class MessageDecoder::MessageDecoderImpl {
       metadata_ = buffer;
     } else {
       ARROW_ASSIGN_OR_RAISE(metadata_,
-                            Buffer::ViewOrCopy(buffer, CPUDevice::memory_manager(pool_)));
+                            Buffer::ViewOrCopy(buffer, memory_manager_));
     }
     return ConsumeMetadata();
   }
@@ -836,14 +837,14 @@ class MessageDecoder::MessageDecoderImpl {
         } else {
           ARROW_ASSIGN_OR_RAISE(
               metadata_,
-              Buffer::ViewOrCopy(chunks_[0], CPUDevice::memory_manager(pool_)));
+              Buffer::ViewOrCopy(chunks_[0], memory_manager_));
         }
         chunks_.erase(chunks_.begin());
       } else {
         metadata_ = SliceBuffer(chunks_[0], 0, next_required_size_);
         if (!chunks_[0]->is_cpu()) {
           ARROW_ASSIGN_OR_RAISE(
-              metadata_, Buffer::ViewOrCopy(metadata_, CPUDevice::memory_manager(pool_)));
+            metadata_, Buffer::ViewOrCopy(metadata_, memory_manager_));
         }
         chunks_[0] = SliceBuffer(chunks_[0], next_required_size_);
       }
@@ -912,7 +913,7 @@ class MessageDecoder::MessageDecoderImpl {
       return util::SafeLoadAs<int32_t>(buffer->data());
     } else {
       ARROW_ASSIGN_OR_RAISE(auto cpu_buffer,
-                            Buffer::ViewOrCopy(buffer, CPUDevice::memory_manager(pool_)));
+                            Buffer::ViewOrCopy(buffer, memory_manager_));
       return util::SafeLoadAs<int32_t>(cpu_buffer->data());
     }
   }
@@ -925,7 +926,7 @@ class MessageDecoder::MessageDecoderImpl {
     for (auto& chunk : chunks_) {
       if (!chunk->is_cpu()) {
         ARROW_ASSIGN_OR_RAISE(
-            chunk, Buffer::ViewOrCopy(chunk, CPUDevice::memory_manager(pool_)));
+            chunk, Buffer::ViewOrCopy(chunk, memory_manager_));
       }
       auto data = chunk->data();
       auto data_size = chunk->size();
@@ -951,6 +952,7 @@ class MessageDecoder::MessageDecoderImpl {
 
   std::shared_ptr<MessageDecoderListener> listener_;
   MemoryPool* pool_;
+  std::shared_ptr<MemoryManager> memory_manager_;
   State state_;
   int64_t next_required_size_;
   std::vector<std::shared_ptr<Buffer>> chunks_;
```

Comment (kou) [reply cpp/src/arrow/ipc/message.cc:637]: #39270 for memory manager.

Comment (felipecrv) [reply cpp/src/arrow/ipc/message.cc:637]: > It works but it causes needless copy with Consume(buffer) API.

Wouldn't it be the same number of copies?

Comment (kou) [reply cpp/src/arrow/ipc/message.cc:637]: If we use the change, all buffers are copied because we're using `CPUDevice::memory_manager(pool_)` not `arrow::default_cpu_memory_manager()`.
If we don't use the change, all buffers aren't copied.

If we use the change with #39270, all buffers aren't copied.

File: cpp/src/arrow/ipc/reader.h (hunk 6 above)
Comment (kou) [reply cpp/src/arrow/ipc/reader.h:320]: @pitrou Does this elaborate enough?

File: cpp/src/arrow/ipc/message.cc (hunk 8 above)
Comment (felipecrv) [reply cpp/src/arrow/ipc/message.cc:637]: Would it work if `ConsumeMetadataBuffer` took a memory manager parameter?

(Keep in mind that I'm not familiar with this code and don't understand how it's used)

Comment (pitrou) [reply cpp/src/arrow/ipc/message.cc:637]: > If we use the change, all buffers are copied because we're using `CPUDevice::memory_manager(pool_)` not `arrow::default_cpu_memory_manager()`.

This is not supposed to trigger a copy.

**Comment by ianmcook** [comment]
@kou It would be very nice to have this merged in time for the 15.0.0 release if possible (code freeze planned 8 January)

**Comment by felipecrv** [comment]
> @kou It would be very nice to have this merged in time for the 15.0.0 release if possible (code freeze planned 8 January)

To be clear: I don't oppose the merge at all. I just don't understand what's going on in this class to judge the solution. cc @ianmcook @pitrou

**Comment by kou** [comment]
Sorry. I forgot to reply this. I'll do it today.

File: cpp/src/arrow/ipc/message.cc (hunk 8 above)
Comment (kou) [reply cpp/src/arrow/ipc/message.cc:637]: Sorry. I was wrong.
But we can't use `Buffer::ViewOrCopy()` for this because `Buffer::ViewOrCopy()` doesn't copy for this case. It returns a view for this case. So we need to copy the given data by `AllocateBuffer()`+`memcpy()` or `std::make_shared<Buffer>()`+`Buffer::Copy()` explicitly. I think the former is better because the latter needs to create 2 `Buffer`s but the former needs to create only 1 `Buffer`.

File: cpp/src/arrow/ipc/reader.h (hunk 6 above)
Comment (kou) [reply cpp/src/arrow/ipc/reader.h]: I reverted this change add a create new `CopyCollectListener()` only for test because I'm not sure whether this API is good or not.
We can defer the API change decision by this because this doesn't change public APi. We can reconsider public API later if needed.

**Comment by kou** [comment]
I've replied:
* https://github.com/apache/arrow/pull/39164#discussion_r1442630986
* https://github.com/apache/arrow/pull/39164#discussion_r1442633352

I've reverted `CollectListener` API change. So we don't need to think about public API change in this PR.
If `std::make_shared<Buffer>()`+`Buffer::Copy()` is better, please change it directly and merge this for 15.0.0. I don't have strong opinion for the approach.

**Comment by kou** [comment]
I'll merge this for 15.0.0.
If there is a problem in this change, I'll work on it in a follow-up PR.
