### PR TITLE
GH-37056: [Java] Fix importing an empty data array from c-data

### LINKED ISSUE #37056: [Java][C][Dataset] Exception when importing a vector with empty data array from c-data
### Describe the bug, including details regarding any error messages, version, and platform.

Java import from c-data arrays throws an exception when attempting to construct a vector for which the data buffer is empty.
Example: importing an empty list of Int32 primitives throws the following 

 
```
Exception in thread "main" java.lang.IllegalArgumentException: Could not load buffers for field $data$: Int(32, true). error message: Buffer 1 for type Int(32, true) cannot be null
	at org.apache.arrow.c.ArrayImporter.doImport(ArrayImporter.java:131)
	at org.apache.arrow.c.ArrayImporter.importChild(ArrayImporter.java:84)
	at org.apache.arrow.c.ArrayImporter.doImport(ArrayImporter.java:97)
	at org.apache.arrow.c.ArrayImporter.importChild(ArrayImporter.java:84)
	at org.apache.arrow.c.ArrayImporter.doImport(ArrayImporter.java:97)
	at org.apache.arrow.c.ArrayImporter.importArray(ArrayImporter.java:71)
	at org.apache.arrow.c.Data.importIntoVector(Data.java:289)
	at org.apache.arrow.c.Data.importIntoVectorSchemaRoot(Data.java:332)
	at org.apache.arrow.dataset.jni.NativeScanner$NativeReader.loadNextBatch(NativeScanner.java:151)
```

### Creation of a sample document (Jupyter notebook) :
python: 3.10.4
pyarrow: 12.0.1
pandas: 2.0.3
```python
import pyarrow as pa
import pyarrow.feather as pf
import pandas as pd

schema = pa.schema([
    pa.field("a", pa.list_(pa.int32()), True),
])
df = pd.DataFrame(columns=["a"],index=range(1))
df.iloc[0] = [[]]
table = pa.table(df, schema)
pf.write_feather(table, "/tmp/sample.feather", compression="uncompressed")
```

### Access the document via Java DataSet API (kotlin):
JVM: openjdk/20.0.1
arrow: 12.0.1
kotlin: 1.9.0
```kotlin
    val allocator = RootAllocator()
    val nativeMemoryPool = NativeMemoryPool.getDefault()
    
    val factory = FileSystemDatasetFactory(allocator, nativeMemoryPool, FileFormat.ARROW_IPC, "file:/tmp/sample.feather")
    factory.finish().use { dataset ->
        dataset.newScan(ScanOptions(10L)).use { scanner ->
            scanner.scanBatches().use { reader ->
                println("$path: schema=${reader.vectorSchemaRoot.schema.toJson()}")

                while (reader.loadNextBatch()) {
                    println(reader.vectorSchemaRoot.contentToTSVString())
                }
            }
        }
    }
```

### Comment
Quick look at the Java code shows that the [ArrayImporter](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/ArrayImporter.java#L126) class uses an instance of [BufferImportTypeVisitor](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java) which performs import vector's buffers based on the knowledge of the field data type.

In this case the [visit(ArrowType.Int type)](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java#L181-L183) method is called which accepts nullable bit mask buffer ([here](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java#L124-L132)) but demands non-nullable data buffer ([here](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java#L93-L99) & then [here](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java#L83-L91)).

As my understanding is from the Vector perspective the data buffer must not be null hence the visitor enforces it, however according to the C data ArrowArray [spec](https://arrow.apache.org/docs/dev/format/CDataInterface.html#the-arrowarray-structure) it can hold null buffers: 
> The buffer pointers MAY be null only in two situations:
>
> 1. for the null bitmap buffer, if ArrowArray.null_count is 0;
> 2. for any buffer, if the size in bytes of the corresponding buffer would be 0.

Based on the above, seems to me, the BufferImportTypeVisitor could create an empty data buffer if the corresponding c data one is null and the filed is empty (fieldNode.length == 0) or throw if the field is not empty.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by janosik47**
### Rationale for this change

Fix java lib bug that prevents from importing specific data via c-data interface.
Currently an attempt to load a vector with empty data buffer results in an IllegalStateException error.

### What changes are included in this PR?
Updated BufferImportTypeVisitor to correctly handle a situation when underlying c-data array pointer is NULL (0) and the expected length of data is zero (0). 

### Are these changes tested?
Yes, updated the existing unit tests

### Are there any user-facing changes?
No

* Closes: #37056

### CODE REVIEW

**Comment by pitrou** [comment]
Thanks @janosik47 . Would you also like to add a new test to https://github.com/apache/arrow/blob/main/java/c/src/test/python/integration_tests.py ?

File: java/c/src/test/java/org/apache/arrow/c/ArrowArrayUtilityTest.java [hunk 1]
```diff
@@ -56,19 +56,39 @@ void afterEach() {
...
+    try (BufferImportTypeVisitor emptyDataVisitor =
+        new BufferImportTypeVisitor(allocator, dummyHandle, new ArrowFieldNode(/* length= */ 0, 0), new long[]{0})) {
+
+      // Too few buffers
+      assertThrows(IllegalStateException.class, () -> emptyDataVisitor.importBuffer(new ArrowType.Bool(), 1, 1));
+
+      // Expected capacity not zero but c arry ptr is NULL (zero)
+      assertThrows(IllegalStateException.class, () -> emptyDataVisitor.importBuffer(new ArrowType.Bool(), 0, 1));
+
+      // Expected capacity is zero and c arry ptr is NULL (zero)
```
Comment (lidavidm) [inline java/c/src/test/java/org/apache/arrow/c/ArrowArrayUtilityTest.java:86]:
```suggestion
      // Expected capacity is zero and c array ptr is NULL (zero)
```

**Review by lidavidm — COMMENTED** [review]
Java LGTM, I left some nits

**Comment by lidavidm** [comment]
Just to make sure, do you plan on adding the integration tests in this PR, or later?

**Comment by janosik47** [comment]
hi - I think I will try to add an integration test ...

**Comment by pitrou** [comment]
> hi - I think I will try to add an integration test ...
> […](#)

For the record, we can help if necessary.

File: java/c/src/test/python/integration_tests.py [hunk 2]
```diff
@@ -195,7 +196,18 @@ def test_list_array(self):
...
+        with pa.BufferOutputStream() as bos:
+            schema = pa.schema([pa.field("f0", pa.list_(pa.int32()), True)])
+            with ipc.new_stream(bos, schema) as writer:
+                src = pa.RecordBatch.from_arrays([pa.array([[]])], schema=schema)
+                writer.write(src)
+        with pa.input_stream(bos.getvalue()) as ios:
+            with ipc.open_stream(ios) as reader:
+                batch = reader.read_next_batch()
+
+        self.round_trip_record_batch(lambda: batch)
```
Comment (janosik47) [inline java/c/src/test/python/integration_tests.py:210]: This may look like an overkill, however I could not came with a better way to create a c-data structures which represents a vector with NULL data buffer, which is what this PR is targeting.

Making just regular batch will create non empty buffers, which is not going to test anything.
Using stream forces the c-data to produce 'optimised' NULL data buffer.

Confirmed, the test fails with upstream and passes with this PR's change.

Comment (lidavidm) [reply java/c/src/test/python/integration_tests.py:210]: I think you can (ab)use ListArray.from_buffers and pyarrow.py_buffer to manually construct such an array from first principles, though this is probably also OK so long as we assert that the batch it produces has the structure we expect

Comment (pitrou) [reply java/c/src/test/python/integration_tests.py:210]: I think this is ok indeed.

[the remark this answers is not in the document]
Comment (janosik47) [reply java/c/src/test/python/integration_tests.py]: ah, good point, refactored

**Review by pitrou — APPROVED** [review]
Thanks a lot @janosik47 for diagnosing and fixing this! Let's wait for CI now.

**Comment by pitrou** [comment]
Hmm, I assume the CI failure on [AMD64 Windows Server 2022 Java JDK 11](https://github.com/apache/arrow/actions/runs/6102854844/job/16589356506?pr=37531#logs) is unrelated, but I'm not sure. @lidavidm could you perhaps take a look?

**Comment by lidavidm** [comment]
That module shouldn't run any JNI code, so I don't think it relates here, but it should be investigated separately. CC @davisusanibar @danepitkin

**Comment by pitrou** [comment]
FTR, I ran the same job again on the main branch and it succeeded:
https://github.com/apache/arrow/actions/runs/6110911458/job/16590554484

**Comment by pitrou** [comment]
... all the while it failed 3 times in a row in this PR.

So it might deserve investigating before merging?

**Comment by pitrou** [comment]
Ok, I've rebased first to make sure it wasn't due to being based on an old commit.

**Comment by danepitkin** [comment]
Looks like several PRs were failing on this job recently, but is now fixed on main?

**Comment by pitrou** [comment]
Rebasing fixed it, so I assume some older commits had the issue. Will merge!
