### PR TITLE
GH-39355: [Java] Improve JdbcConsumer exceptions

### LINKED ISSUE #39355: [Java] Improve JdbcConsumer errors
### Describe the enhancement requested

Currently, when an error occurs while consuming a JDBC ResultSet, it's impossible to debug what might have happened. For example, here's a redacted stack trace:

```
java.lang.RuntimeException: Error occurred while getting next schema root.
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.next(ArrowVectorIterator.java:181)
        ...
Caused by: java.lang.RuntimeException: Error occurred while consuming data.
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.consumeData(ArrowVectorIterator.java:117)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.load(ArrowVectorIterator.java:159)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.next(ArrowVectorIterator.java:177)
	... 10 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Decimal size greater than 16 bytes: 17
	at org.apache.arrow.vector.util.DecimalUtility.writeByteArrayToArrowBufHelper(DecimalUtility.java:175)
	at org.apache.arrow.vector.util.DecimalUtility.writeBigDecimalToArrowBuf(DecimalUtility.java:136)
	at org.apache.arrow.vector.DecimalVector.set(DecimalVector.java:365)
	at org.apache.arrow.adapter.jdbc.consumer.DecimalConsumer.set(DecimalConsumer.java:79)
	at org.apache.arrow.adapter.jdbc.consumer.DecimalConsumer$NullableDecimalConsumer.consume(DecimalConsumer.java:101)
	at org.apache.arrow.adapter.jdbc.consumer.CompositeJdbcConsumer.consume(CompositeJdbcConsumer.java:46)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.consumeData(ArrowVectorIterator.java:106)
	... 12 common frames omitted
```

These types of errors are likely due to an incorrect mapping from `JdbcType` to `ArrowType`, but at this point there's no insight into that mapping. My proposal is to introduce a `JdbcConsumerException` that stores a `JdbcFieldInfo` for the ResultSet column and `ArrowType` for the vector. The easiest way to do this would be in a `try/catch` inside the `CompositeJdbcConsumer` and then bubble it up in `ArrowVectorIterator`. Users would then be able to extract that information from the exception to make more informative logs.

It would be nice to also store the actual value that caused the exception, but that could potentially expose PII so maybe not the best idea.

I'll make a PR and can discuss further.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by aiguofer**
### Rationale for this change

This helps debug Arrow conversion errors from JDBC by exposing the JdbcFieldInfo for the related column and the ArrowType for the corresponding vector.

### What changes are included in this PR?

A new JdbcConsumerException which is thrown by the CompositeJdbcConsumer while consuming data for a specific vector.

### Are these changes tested?

N/A

### Are there any user-facing changes?

Users can now catch `JdbcConsumerException`s and extract the related ArrowType and JdbcFieldInfo from it for debugging.

* Closes: #39355

### CODE REVIEW

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java [hunk 1]
```diff
@@ -74,3 +87,26 @@ public void resetVectorSchemaRoot(VectorSchemaRoot root) {
     }
   }
 }
+
+/**
```
Comment (aiguofer) [inline java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java:91]: I'm not sure where to add this exception. It doesn't seem like there's any custom exceptions. I was thinking `java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/exceptions/JdbcConsumerException.java`?

**Comment by davisusanibar** [comment]
Thanks to @aiguofer for this enhancement. Would it be possible to add a unit test to cover these new exception improvements?

**Comment by vibhatha** [comment]
@aiguofer agreeing with @davisusanibar here. 
It would be better to add a test case which is failing as expected and verify the exception message as an assertion. 
Also just curious would this require documentation update?

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java [hunk 2]
```diff
@@ -43,7 +46,18 @@ public CompositeJdbcConsumer(JdbcConsumer[] consumers) {
   @Override
   public void consume(ResultSet rs) throws SQLException, IOException {
     for (int i = 0; i < consumers.length; i++) {
-      consumers[i].consume(rs);
+      try {
+        consumers[i].consume(rs);
```
Comment (vibhatha) [inline java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java:50]: just curious what if `consume` method throws the defined exception rather than catching and throwing it back?

Comment (aiguofer) [reply java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java:50]: What do you mean?

If you mean that every consumer that extends BaseConsumer should implement its own `try/catch` to throw the `JdbcConsumerException` within its `consume` method then I think it's doable, but it would require more changes and require more effort when implementing a custom consumer (users would need to ensure they add the try/catch logic as well). Handling it here seems easier to both implement and use since custom consumers can just extend `BaseConsumer`.

**Comment by aiguofer** [comment]
@davisusanibar @vibhatha It would certainly be great to have tests for consumer! unfortunately there's not much prior art regarding this. I'm not very familiar with the test suite in general and this would likely require mocking a ResultSet along with the corresponding ResultSetMetaData in order to properly test this, which seems like a lot of work.

**Review by lidavidm — APPROVED** [review]
For testing, we do use hsqldb in the suite to integration test against an actual database (instead of mocking everything). That said mocking may be easier here overall

**Comment by lidavidm** [comment]
> Also just curious would this require documentation update?

It would be good to add a `@throws` in the docstring for `ArrowVectorIterator`. Actually, this might be considered a breaking change since people may expect SQLException currently. (And it's documented in `sqlToArrowVectorIterator`.)

Possibly we should extend SQLException instead?

**Comment by vibhatha** [comment]
> Possibly we should extend SQLException instead?

+1

**Comment by vibhatha** [comment]
> For testing, we do use hsqldb in the suite to integration test against an actual database (instead of mocking everything). That said mocking may be easier here overall

should we include it in this PR itself or should we create follow up?

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java (hunk 2 above)
Comment (vibhatha) [reply java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java:50]: I understand your point. Let's keep it as it is.

**Review by vibhatha — APPROVED** [review]

**Comment by aiguofer** [comment]
Sorry all, I'm just getting back from break. Hmm, I think it might be better to add a `throws` instead. The exceptions are not always a `SQLException`. For example, in our case what prompted this PR was this redacted stack trace:

```
java.lang.RuntimeException: Error occurred while getting next schema root.
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.next(ArrowVectorIterator.java:181)
        ...
Caused by: java.lang.RuntimeException: Error occurred while consuming data.
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.consumeData(ArrowVectorIterator.java:117)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.load(ArrowVectorIterator.java:159)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.next(ArrowVectorIterator.java:177)
	... 10 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Decimal size greater than 16 bytes: 17
	at org.apache.arrow.vector.util.DecimalUtility.writeByteArrayToArrowBufHelper(DecimalUtility.java:175)
	at org.apache.arrow.vector.util.DecimalUtility.writeBigDecimalToArrowBuf(DecimalUtility.java:136)
	at org.apache.arrow.vector.DecimalVector.set(DecimalVector.java:365)
	at org.apache.arrow.adapter.jdbc.consumer.DecimalConsumer.set(DecimalConsumer.java:79)
	at org.apache.arrow.adapter.jdbc.consumer.DecimalConsumer$NullableDecimalConsumer.consume(DecimalConsumer.java:101)
	at org.apache.arrow.adapter.jdbc.consumer.CompositeJdbcConsumer.consume(CompositeJdbcConsumer.java:46)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.consumeData(ArrowVectorIterator.java:106)
	... 12 common frames omitted
```

**Comment by lidavidm** [comment]
Ok, thanks. Then I think just documenting it in `@throws` is sufficient.

**Comment by aiguofer** [comment]
@lidavidm done!

**Review by lidavidm — APPROVED** [review]
