### PR TITLE
GH-33932: [Go] Fix build RecordBuilder with non-nullable items map field

### LINKED ISSUE #33932: [Go] RecordBuilder doesn't allow setting map items as non-nullable
### Describe the bug, including details regarding any error messages, version, and platform.

There is currently no way to set the items for a map as "non-nullable" when constructing with a builder.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by forsaken628**
### Rationale for this change

Fix build RecordBuilder with non-nullable items map field

### Are these changes tested?

yes
### Are there any user-facing changes?

bug fix

* Closes: #33932

### CODE REVIEW

File: go/arrow/array/record_test.go [hunk 1]
```diff
@@ -390,6 +390,28 @@ func TestRecordBuilder(t *testing.T) {
...
+		b := array.NewRecordBuilder(mem, schema)
+		defer b.Release()
+
+		mb := b.Field(0).(*array.MapBuilder)
+		mb.Append(true)
+		mb.KeyBuilder().(*array.StringBuilder).AppendValues([]string{"1", "2", "3"}, nil)
+		mb.ItemBuilder().(*array.StringBuilder).AppendValues([]string{"a", "b", "c"}, nil)
+
+		rec := b.NewRecord()
+		defer rec.Release()
```
Comment (zeroshade) [inline go/arrow/array/record_test.go:413]: shouldn't this be compared against something to ensure it created the map properly?

File: go/arrow/datatype_nested.go [hunk 2]
```diff
@@ -205,6 +205,8 @@ func (t *FixedSizeListType) String() string {
 	return fmt.Sprintf("fixed_size_list<%s: %s>[%d]", t.elem.Name, t.elem.Type, t.n)
 }
 
+func (t *FixedSizeListType) SetElemNullable(n bool) { t.elem.Nullable = n }
+
```
Comment (zeroshade) [inline go/arrow/datatype_nested.go:209]: Add a test for this please?

File: go/arrow/array/map.go [hunk 3]
```diff
@@ -249,6 +265,10 @@ func (b *MapBuilder) NewArray() arrow.Array {
 // NewMapArray creates a new Map array from the memory buffers used by the builder, and
 // resets the builder so it can be used again to build a new Map array.
 func (b *MapBuilder) NewMapArray() (a *Map) {
+	if !b.etype.ItemField().Nullable && b.ItemBuilder().NullN() > 0 {
+		panic("arrow/array: item not nullable")
+	}
```
Comment (zeroshade) [inline go/arrow/array/map.go:270]: Add a test for this please

File: go/arrow/array/map.go [hunk 4]
```diff
@@ -126,26 +126,25 @@ type MapBuilder struct {
 // building using keys in sorted order for each value. The KeysSorted value will just be
 // used when creating the DataType for the map.
 //
-// Example
+// # Example
```
Comment (zeroshade) [inline go/arrow/array/map.go:129]: Go documentation doesn't need the `#` here. A single line without a period becomes a header like so: https://pkg.go.dev/github.com/apache/arrow/go/v10@v10.0.1/arrow/array#hdr-Example

**Review by zeroshade — CHANGES_REQUESTED** [review]
Thanks for the PR, there's a couple comments I have/changes requested.

File: go/arrow/array/map_test.go [hunk 5]
```diff
@@ -78,16 +78,42 @@ func TestMapArray(t *testing.T) {
...
+		bldr.Append(true)
+		kb.Append(1)
+		ib.AppendNull()
+
+		defer func() {
+			if recover() == nil {
+				t.Fatal("this should have panicked")
+			}
+		}()
+		_ = bldr.NewArray()
```
Comment (zeroshade) [inline go/arrow/array/map_test.go:115]: use `assert.Panics`

**Review by zeroshade — APPROVED** [review]
