### PR TITLE
GH-40755: [JS] fix decimal conversions

### LINKED ISSUE #40755: [JS] - Decimal conversions are broken
### Describe the bug, including details regarding any error messages, version, and platform.

Converting a decimal to a number is broken for negatives and those with decimal places.

I'd like to add support for this.

### Component(s)

JavaScript

### PR DESCRIPTION
**Pull request by dioptre**
### Rationale for this change

Fixes  https://github.com/apache/arrow/issues/40755

Further work is required to complete:
https://github.com/apache/arrow-js/issues/77

Decimals are broken - need a correct way to convert decimals to numbers in js

Also included an option to include a denominator (BigInt(1/scale)) as scale is part of the metadata

### What changes are included in this PR?

Submitting a correct way to convert decimals to numbers

### Are these changes tested?
Yes, includes a test

### Are there any user-facing changes?
No

 **This PR contains a "Critical Fix".**
* GitHub Issue: apache/arrow-js#77
* GitHub Issue: apache/arrow#40755
* GitHub Issue: #40755

### CODE REVIEW

File: js/src/util/bn.ts [hunk 1]
```diff
@@ -68,25 +68,36 @@ Object.assign(SignedBigNum.prototype, BigNum.prototype, { 'constructor': SignedB
...
 
+//FOR ES2020 COMPATIBILITY
+const TWO_TO_THE_64 = BigInt(4294967296) * BigInt(4294967296); // 2^32 * 2^32 = 0x10000000000000000n
+const TWO_TO_THE_64_MINUS_1 = TWO_TO_THE_64 - BigInt(1); // (2^32 * 2^32) - 1 = 0xFFFFFFFFFFFFFFFFn
+
 /** @ignore */
-function bigNumToNumber<T extends BN<BigNumArray>>(bn: T) {
-    const { buffer, byteOffset, length, 'signed': signed } = bn;
-    const words = new BigUint64Array(buffer, byteOffset, length);
+export const bigNumToNumber: { <T extends BN<BigNumArray>>(bn: T, denominator?: bigint): number } = (<T extends BN<BigNumArray>>(bn: T, denominator?: bigint) => {
```
Comment (domoritz) [inline js/src/util/bn.ts:76]: Let's leave this as a function. I think the "functions" below also should be functions and not consts with an arrow function.

**Comment by domoritz** [comment]
Thanks for the pull request.

This does not yet fix encoding so we cannot close https://github.com/apache/arrow/issues/37920.

```ts
arrow.vectorFromArray([1, 12, 34], new arrow.Decimal(3, 18))
```

Also, it seems like this still ignores the scale. If I try the example in https://github.com/apache/arrow/issues/37920#issue-1916512787, I still get 1000 instead of 1 (the scale is ignored).

```ts
const hex = 'FFFFFFFF780000001000000000000A000C000600050008000A000000000104000C000000080008000000040008000000040000000100000014000000100014000800060007000C00000010001000000000000107100000001C0000000400000000000000010000006400000008000C0004000800080000001200000003000000FFFFFFFF8800000014000000000000000C0016000600050008000C000C0000000003040018000000300000000000000000000A0018000C00040008000A0000003C00000010000000030000000000000000000000020000000000000000000000000000000000000000000000000000003000000000000000000000000100000003000000000000000000000000000000E8030000000000000000000000000000E02E0000000000000000000000000000D0840000000000000000000000000000FFFFFFFF00000000';
const bytes = Uint8Array.from(hex.match(/.{1,2}/g).map(s => parseInt(s, 16)));
const vec = arrow.tableFromIPC(bytes).getChild('d')!;

console.log(vec.get(0))         // [1000, 0, 0, 0] <- byte array looks correct
console.log(`${vec.get(0)}`)    // "1000" <- incorrect, should be 1; ignores scale
console.log(Number(vec.get(0))) // 1000 <- incorrect, should be 1
```

File: js/src/util/bn.ts [hunk 2]
```diff
@@ -68,25 +68,36 @@ Object.assign(SignedBigNum.prototype, BigNum.prototype, { 'constructor': SignedB
 Object.assign(UnsignedBigNum.prototype, BigNum.prototype, { 'constructor': UnsignedBigNum, 'signed': false, 'TypedArray': Uint32Array, 'BigIntArray': BigUint64Array });
 Object.assign(DecimalBigNum.prototype, BigNum.prototype, { 'constructor': DecimalBigNum, 'signed': true, 'TypedArray': Uint32Array, 'BigIntArray': BigUint64Array });
 
+//FOR ES2020 COMPATIBILITY
+const TWO_TO_THE_64 = BigInt(4294967296) * BigInt(4294967296); // 2^32 * 2^32 = 0x10000000000000000n
```
Comment (domoritz) [inline js/src/util/bn.ts:72]: Why not just this?

```suggestion
const TWO_TO_THE_64 = BigInt(2) ** BigInt(64); // 2^64 = 0x10000000000000000n
```

**Comment by domoritz** [comment]
`vec.get(0).valueOf(1000n)` return the correct value but it would be nice to pass the scale though. It's in the type but I don't know what is the best way to get that. This otherwise looks correct.

**Comment by dioptre** [comment]
Are the tests off? I’ll take a look soon.

I made it so you pass the denominator through instead of scale. The reason
for this is that with 10^9 numbers to convert you don’t need to do a scale
to denominator conversion for each number. Passing the denominator as a
bigint instead will make the function much faster.

**Comment by domoritz** [comment]
Thanks for looking at the tests. 

I see. How do you imagine someone using get then? We should probably do the correct conversion there. Maybe we can cache the scale to denominator conversion somewhere if you're worried about performance.

**Comment by domoritz** [comment]
I think the best way forward is to get this pull request in but make a new issue that this pull request is attached to. We probably need to refactor the whole decimal handling in ways that are orthogonal to this fix. How does that sound @dioptre?

**Comment by dioptre** [comment]
I was thinking the same. Perhaps we go for the scale first if you want to
keep it in that format for the future and we can optimize later.

If you are happy with that I can change denominator to scale and we can
look at cache later.

**Comment by domoritz** [comment]
Let's change to scale and make a new issue. Then we can merge.

**Comment by dioptre** [comment]
Updated the PR, tests look ok?

**Comment by dioptre** [comment]
Ah your [suggestion broke it](https://github.com/apache/arrow/pull/40729/commits/cff7709d63f03f497dbdc3e97a6fcbd16a1d2f62) so I reverted. I also made it a function per your request.

It was my understanding that the scale is included in the metadata, and there's no real metadata in the arrow bytes. This confused me at first as I was looking for it. So seems we need the valueOf(scale)?

> console.log(vec.get(0))         // [1000, 0, 0, 0] <- byte array looks correct
> console.log(`${vec.get(0)}`)    // "1000" <- incorrect, should be 1; ignores scale
> console.log(Number(vec.get(0))) // 1000 <- incorrect, should be 1
> ```

**Comment by domoritz** [comment]
> Ah your [suggestion broke it](https://github.com/apache/arrow/pull/40729/commits/cff7709d63f03f497dbdc3e97a6fcbd16a1d2f62) so I reverted.

What did it break?

**Comment by domoritz** [comment]
Also, please make a new issue that this pull request refers to since it doesn't address the referenced issue fully yet.

**Comment by dioptre** [comment]
It wouldn't build, we had the same issue on our older code (pre es2020) -
think ** and bigint support is no bueno for older builds

**Comment by dioptre** [comment]
Updated the fix issue above, kept a reference ^^^

**Comment by domoritz** [comment]
I fixed the title of this pull request. Now we just need the integration tests to pass.

**Comment by dioptre** [comment]
Think should be good to run again

File: js/src/util/bn.ts [hunk 3]
```diff
@@ -68,24 +68,36 @@ Object.assign(SignedBigNum.prototype, BigNum.prototype, { 'constructor': SignedB
...
+    }
+    if (scale) {
+        const denominator = BigInt(Math.pow(10, scale));
+        const quotient = number / denominator;
+        const remainder = number % denominator;
+        const n = Number(quotient) + (Number(remainder) / Number(denominator));
+        return n;
     }
-    return number;
+    return Number(number);
```
Comment (domoritz) [inline js/src/util/bn.ts:100]: Isn't this incorrect when we have larger numbers?

**Comment by dioptre** [comment]
I took the literal definition bignum to number?

**Comment by domoritz** [comment]
Fair. We're need to refactor how all of this is used for decimals a bit anyway so lets leave it.

**Comment by dioptre** [comment]
Sounds good. Let me know if there’s anything else I can help with.

File: js/test/unit/bn-tests.ts [hunk 4]
```diff
@@ -83,4 +83,19 @@ describe(`BN`, () => {
...
+        const n2 = new BN(new Uint32Array([0xFFFFFFFE, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF]), true);
+        expect(n2.valueOf()).toBe(-2);
+        const n3 = new BN(new Uint32Array([0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF]), true);
+        expect(n3.valueOf()).toBe(-1);
+        const n4 = new BN(new Uint32Array([0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF]), true);
+        expect(n4.valueOf(1)).toBe(-0.1);
+        const n5 = new BN(new Uint32Array([0x00000000, 0x00000000, 0x00000000, 0x80000000]), false);
+        expect(n5.valueOf()).toBe(1.7014118346046923e+38);
+        // const n6 = new BN(new Uint32Array([0x00000000, 0x00000000, 0x00000000, 0x80000000]), false);
+        // expect(n6.valueOf(1)).toBe(1.7014118346046923e+37);
```
Comment (domoritz) [inline js/test/unit/bn-tests.ts:99]: Why is this commented out?

**Review by domoritz — CHANGES_REQUESTED** [review]

**Comment by dioptre** [comment]
Because the CI tool expects all transformations to be reversible and
converting from a decimal to a number is a one way operation - so I had to
comment it out.

File: js/src/util/bn.ts [hunk 5]
```diff
@@ -68,24 +68,36 @@ Object.assign(SignedBigNum.prototype, BigNum.prototype, { 'constructor': SignedB
...
         }
     } else {
         for (const word of words) {
-            number += ~word * (BigInt(1) << (BigInt(32) * i++));
+            number |= (word ^ TWO_TO_THE_64_MINUS_1) * (BigInt(1) << BigInt(64 * i++));
         }
         number *= BigInt(-1);
+        number -= BigInt(1);
+    }
+    if (scale) {
```
Comment (trxcllnt) [inline js/src/util/bn.ts:93]:
```suggestion
    if (typeof scale === 'number') {
```

File: js/test/unit/bn-tests.ts (hunk 4 above)
Comment (domoritz) [reply js/test/unit/bn-tests.ts:99]: > Because the CI tool expects all transformations to be reversible and
converting from a decimal to a number is a one way operation - so I had to
comment it out.

I don't understand. What does reversible mean here? Will this ever work or should we just delete it?

File: js/src/util/bn.ts (hunk 5 above)
Comment (dioptre) [reply js/src/util/bn.ts]: This is going to further slow down execution, also it won't account for NaN.

After all this I'd like to bring something back (maybe an additional method) that is efficient after getting this change in. Think good enough it replaces the broken method for now.

File: js/test/unit/bn-tests.ts (hunk 4 above)
Comment (dioptre) [reply js/test/unit/bn-tests.ts:99]: > I don't understand. What does reversible mean here? Will this ever work or should we just delete it?

The CI tool does not allow transformations from BigInt to number as data (correctly) will be lost. What the CI tool is not smart enough to realize is, this is on purpose.

It's important that people still realize this is still possible and testable, so removing it from the test is not as good an option as leaving this commented out in the test.

I think considering we have a very broken library at present, this should probably not be of consequence. So whatever you prefer. My preference is to get the fix in and we can talk about this later.

**Comment by dioptre** [comment]
Hey @domoritz looks like you introduced another breaking change, while testing for number may seem ok, it will break for NaN, and further slow down the method.

**Comment by dioptre** [comment]
Honestly doing anything is an improvement on where the code is - so please just do what you'd like.

**Comment by domoritz** [comment]
Yep. let's get this in and improve things in follow up PRs. I think we should introduce a new class so we can automatically apply the right scale from the type.

**Comment by domoritz** [comment]
Thank you

**Comment by domoritz** [comment]
@dioptre there seems to be an issue with fractional scales

```
const n5 = new BN(new Uint32Array([0x00000000, 0x00000000, 0x00000000, 0x80000000]), false);
expect(n5.valueOf(0.1)).toBe(1.7014118346046923e+38);
```

Which leads to `RangeError: The number 1.2589254117941673 cannot be converted to a BigInt because it is not an integer`. 

This is supposed to work since decimals can be fractions, right?

**Comment by domoritz** [comment]
We can get the scale from the type. I misunderstood how the scale works. Thanks for the link that explained what I was missing. 

```
 const n3 = new BN(new Uint32Array([0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF]), true);
 expect(n3.valueOf()).toBe(-1);
 expect(n3.valueOf(1)).toBe(-0.1);
 expect(n3.valueOf(2)).toBe(-0.01);
```

**Comment by dioptre** [comment]
No worries, this drove me nuts at first - I was expecting something more like this - https://en.wikipedia.org/wiki/Binary-coded_decimal
