### PR TITLE
GH-36318: [Go] only decode lengths for the number of existing values, not for all nvalues.

### LINKED ISSUE #36318: [Go][Parquet] DeltaLengthByteArray encoding breaks with null values in go library
### Describe the bug, including details regarding any error messages, version, and platform.

The DeltaLengthByteArray encoding cannot handle null values in the go library.
It fails on 
a) all nulls in one batch - here it reaches an index out of bounds error when initializing the delta bit packing decoder
b) some nulls in one batch - here it continues to decode the lengths for all rows and interprets actual data for lengths information. Data that later is missing when it wants to decode it.

I have a fix and will update the Issue as soon as the PR is created.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by convoi**
### Rationale for this change

Fixes issue 36318.
DeltaLengthBinaryArray Encoding fails to handle null values.

### What changes are included in this PR?

Instead of decoding lengths for "all" values (even the undefined ones), we only decode the lengths for the actually set values.
The Go Version of arrow was unable to read parquet files it produced itself if the mentioned encoding was used but the values contain nulls.

### Are these changes tested?

Tests are included.

### Are there any user-facing changes?

No.

**This PR contains a "Critical Fix".**
* Closes: #36318

### CODE REVIEW

**Review by zeroshade — APPROVED** [review]

File: go/parquet/internal/encoding/delta_byte_array_test.go [hunk 1]
```diff
@@ -0,0 +1,31 @@
+package encoding
```
Comment (zeroshade) [inline go/parquet/internal/encoding/delta_byte_array_test.go:1]: You need to add the Apache license to the top of this file please. That will fix the failing CI
