### PR TITLE
GH-38923: [GLib] Fix spelling

### LINKED ISSUE #38923: [GLIB] Spelling errors identified by check-spelling
### Describe the bug, including details regarding any error messages, version, and platform.

The [check-spelling action](https://github.com/marketplace/actions/check-spelling) enabled me to identify some misspellings...

The misspellings have been reported at https://github.com/jsoref/apache-arrow/actions/runs/7008141484/attempts/1#summary-19063787889

### Component(s)

GLib

### PR DESCRIPTION
**Pull request by jsoref**
### What changes are included in this PR?

Spelling fixes to c_glib/

### Are there any user-facing changes?

* Closes: #38923

### CODE REVIEW

File: c_glib/test/test-array.rb [hunk 1]
```diff
@@ -141,12 +141,12 @@ def test_no_diff
 
     def test_diff
       array = build_string_array(["Start", "Shutdown", "Reboot"])
-      other_array = build_string_array(["Start", "Shutdonw", "Reboot"])
+      other_array = build_string_array(["Start", "Shutdown_", "Reboot"])
```
Comment (kou) [inline c_glib/test/test-array.rb:144]:
```suggestion
      other_array = build_string_array(["Start", "Shutdown", "Reboot"])
```

File: c_glib/test/test-array.rb [hunk 2]
```diff
@@ -141,12 +141,12 @@ def test_no_diff
...
       assert_equal(<<-STRING.chomp, array.diff_unified(other_array))
 
 @@ -1, +1 @@
 -"Shutdown"
-+"Shutdonw"
++"Shutdown_"
```
Comment (kou) [inline c_glib/test/test-array.rb:149]:
```suggestion
+"Shutdown"
```

**Review by kou — COMMENTED** [review]
Thanks. We have many typos...

File: c_glib/test/test-array.rb (hunk 2 above)
Comment (jsoref) [reply c_glib/test/test-array.rb:149]: This didn't work. It's doing some sorting to an array. It was my initial correction and tests failed when I did it.

(I know it looks like I'm just fixing things randomly without testing stuff, but I really do try to get CI to pass before I make my initial PRs.)

Comment (kou) [reply c_glib/test/test-array.rb:149]: I took a look at this test again.
We should not change this because it's a test to detect difference of two arrays. The "Shutdonw" typo is for the difference.

Or we can use other entirely different word something like:

```diff
diff --git a/c_glib/test/test-array.rb b/c_glib/test/test-array.rb
index c03aecf17..4da641b20 100644
--- a/c_glib/test/test-array.rb
+++ b/c_glib/test/test-array.rb
@@ -141,12 +141,12 @@ class TestArray < Test::Unit::TestCase
 
     def test_diff
       array = build_string_array(["Start", "Shutdown", "Reboot"])
-      other_array = build_string_array(["Start", "Shutdonw", "Reboot"])
+      other_array = build_string_array(["Start", "Running", "Reboot"])
       assert_equal(<<-STRING.chomp, array.diff_unified(other_array))
 
 @@ -1, +1 @@
 -"Shutdown"
-+"Shutdonw"
++"Running"
 
       STRING
     end
```

Comment (jsoref) [reply c_glib/test/test-array.rb:149]: I'll take running.

File: c_glib/test/test-array.rb (hunk 1 above)
Comment (kou) [inline c_glib/test/test-array.rb:144]:
```suggestion
      other_array = build_string_array(["Start", "Running", "Reboot"])
```

File: c_glib/test/test-array.rb (hunk 2 above)
Comment (kou) [inline c_glib/test/test-array.rb:149]:
```suggestion
+"Running"
```

**Review by kou — APPROVED** [review]
+1
