### PR TITLE
GH-37834: [Gandiva] Migrate to new LLVM PassManager API

### LINKED ISSUE #37834: [C++][Gandiva] Support LLVM 17
### Describe the bug, including details regarding any error messages, version, and platform.

Arrow couldn't find llvm 17.0.1 because It's not listed.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by niyue**
### Rationale for this change
In https://github.com/apache/arrow/issues/37834, to support LLVM 17, we need to migrate to use the new LLVM PassManager API.

### What changes are included in this PR?

 This PR tries to migrate the legacy PassManager to the new PassManager.

### Are these changes tested?
It should be covered by existing unit tests. But more performance tests may be needed to verify this change.

### Are there any user-facing changes?
No

* Closes: #37834

### CODE REVIEW

**Comment by kou** [comment]
We have some micro benchmarkes in https://github.com/apache/arrow/blob/main/cpp/src/gandiva/tests/micro_benchmarks.cc . Can we use them?

**Comment by niyue** [comment]
> We have some micro benchmarkes in https://github.com/apache/arrow/blob/main/cpp/src/gandiva/tests/micro_benchmarks.cc . Can we use them?

Let me check it out. I've compared the old/new LLVM IR generated by the particular test code today, and they are exactly the same (at least for this test case), so I assume the change is probably not too risky.

**Comment by niyue** [comment]
> Could you also apply [#37834 (comment)](https://github.com/apache/arrow/issues/37834#issuecomment-1732419801) to accept LLVM 17?

I applied your patch for LLVM 17 a moment ago, and it should help to address some issues in the CI.

# LLVM incompatible API changes (or new API)
But I realized my current changes use some APIs that are not available in lower version of LLVM, for example, this CI check failed (https://github.com/apache/arrow/actions/runs/6307346371/job/17123835292?pr=37867), there are at least 4 incompatible changes:
1) llvm::GVNPass() (I confirmed this is a newly added API in Nov. 2021, either introduced in LLVM 13.0.1 or LLVM 14.0.0 [1])
2) llvm::ModuleInlinerPass()
3) llvm::OptimizationLevel
4) `void llvm::PassBuilder::registerPipelineStartEPCallback(const std::function<void(llvm::PassManager<llvm::Module>&)>&)`

I used LLVM 14.0.6 locally.
For such cases, do we need to use macro to call different APIs? Currently, the lowest version of LLVM listed in the support list is `7.0`, we probably won't be able to verify many different versions of LLVMs, an option is we use two implementations for `PassManager`:
1) the legacy PassManager one for LLVM version < 14 (the old implementation)
2) the new PassManager for LLVM version >= 14 (the implementation in this PR) (use version 14 because at least one of the API `llvm::GVNPass()` is likely introduced in LLVM 14.0)

@kou what do you think?

# linker error
This CI check (https://github.com/apache/arrow/actions/runs/6307346377/job/17123834680?pr=37867) failed with some linker error `undefined reference`, but it is not a compiler error, do we have multiple version of LLVMs installed in the environment?

# links
[1] https://github.com/llvm/llvm-project/blame/7675f541f75baa20e8ec007cd625a837e89fc01f/llvm/include/llvm/Transforms/Scalar/GVN.h#L117
[2] LLVM release dates, https://releases.llvm.org

**Comment by kou** [comment]
> I've compared the old/new LLVM IR generated by the particular test code today, and they are exactly the same

Great!

> For such cases, do we need to use macro to call different APIs? Currently, the lowest version of LLVM listed in the support list is `7.0`, we probably won't be able to verify many different versions of LLVMs, one option is we use two implementations for `PassManager`:
> 
>     1. the legacy PassManager one for LLVM version < 14 (the old implementation)
>     2. the new PassManager for LLVM version >= 14 (the implementation in this PR)

Is it something like the following?

```diff
diff --git a/cpp/src/gandiva/engine.cc b/cpp/src/gandiva/engine.cc
index 6abe81405..b5104c5b7 100644
--- a/cpp/src/gandiva/engine.cc
+++ b/cpp/src/gandiva/engine.cc
@@ -308,6 +308,7 @@ Status Engine::FinalizeModule() {
     ARROW_RETURN_NOT_OK(RemoveUnusedFunctions());
 
     if (optimize_) {
+#if LLVM_VERSION_MAJOR >= 14
       // Setup an optimiser pipeline
       llvm::PassBuilder pass_builder;
       llvm::LoopAnalysisManager loop_am;
@@ -345,6 +346,30 @@ Status Engine::FinalizeModule() {
 
       pass_builder.buildPerModuleDefaultPipeline(llvm::OptimizationLevel::O3)
           .run(*module_, module_am);
+#else
+      // misc passes to allow for inlining, vectorization, ..
+      std::unique_ptr<llvm::legacy::PassManager> pass_manager(
+          new llvm::legacy::PassManager());
+
+      llvm::TargetIRAnalysis target_analysis =
+          execution_engine_->getTargetMachine()->getTargetIRAnalysis();
+      pass_manager->add(llvm::createTargetTransformInfoWrapperPass(target_analysis));
+      pass_manager->add(llvm::createFunctionInliningPass());
+      pass_manager->add(llvm::createInstructionCombiningPass());
+      pass_manager->add(llvm::createPromoteMemoryToRegisterPass());
+      pass_manager->add(llvm::createGVNPass());
+      pass_manager->add(llvm::createNewGVNPass());
+      pass_manager->add(llvm::createCFGSimplificationPass());
+      pass_manager->add(llvm::createLoopVectorizePass());
+      pass_manager->add(llvm::createSLPVectorizerPass());
+      pass_manager->add(llvm::createGlobalOptimizerPass());
+
+      // run the optimiser
+      llvm::PassManagerBuilder pass_builder;
+      pass_builder.OptLevel = 3;
+      pass_builder.populateModulePassManager(*pass_manager);
+      pass_manager->run(*module_);
+#endif
     }
 
     ARROW_RETURN_IF(llvm::verifyModule(*module_, &llvm::errs()),
```

I like the approach.

> # linker error
> 
> This CI check (https://github.com/apache/arrow/actions/runs/6307346377/job/17123834680?pr=37867) failed with some linker error `undefined reference`, but it is not a compiler error, do we have multiple version of LLVMs installed in the environment?

It uses static linking. I think that we need to add more components for the new PassManager API at:

https://github.com/apache/arrow/blob/23c1bf9ff74b749c11385b38911d6aa8d85e180c/cpp/cmake_modules/FindLLVMAlt.cmake#L89-L98

If you're not familiar with CMake, I can do it. But I can't work on it in this week...

**Comment by niyue** [comment]
> Is it something like the following?

Yes, I am thinking something like you said. 

> It uses static linking. I think that we need to add more components for the new PassManager API at

Cool. I am not aware that the new PassManager needs to change LLVM components. Why this issue doesn't happen in other CI environments? Anyway, let me give it a try to see if I can figure it out by adding some more components.

**Comment by niyue** [comment]
For the `FinalizeModule` method, I added back the old implementation using the legacy pass manager for LLVM version < 14 for compatibility. 

For the `RemoveUnusedFunctions` method, I verified the APIs used and they all seem introduced long time ago, and there should not be compatibility issue, but I don't actually verify against LLVM 7.0, but only check github history for verification.

Here are the major APIs used in `RemoveUnusedFunctions` method:
### PassBuilder.registerModuleAnalyses
Feb 1, 2015, LLVM 3.6.0
https://github.com/llvm/llvm-project/blame/3bb89b6bfbb549a4b129698b0e56d758a1dcd8df/llvm/include/llvm/Passes/PassBuilder.h#L103

### ModulePassManager
May 13, 2017, LLVM 5.0
https://github.com/llvm/llvm-project/blame/3bb89b6bfbb549a4b129698b0e56d758a1dcd8df/llvm/include/llvm/IR/PassManager.h#L25

### InternalizePass
Apr 27, 2016, LLVM 3.9.0
https://github.com/llvm/llvm-project/blame/3bb89b6bfbb549a4b129698b0e56d758a1dcd8df/llvm/include/llvm/Transforms/IPO/Internalize.h#L34

### GlobalDCEPass
May 4, 2016, LLVM 3.9.0
https://github.com/llvm/llvm-project/blame/3bb89b6bfbb549a4b129698b0e56d758a1dcd8df/llvm/include/llvm/Transforms/IPO/GlobalDCE.h#L36

I didn't change the CMake LLVM components yet, since if we use legacy LLVM PassManager API for old versions of LLVM, we probably don't need to change it any more. I will keep an eye on the CI results to see if it works for LLVM 17 environments.

**Comment by kou** [comment]
Sorry. Only for the linker error: We may be able to reproduce the linker error with `-DARROW_LLVM_USE_SHARED=OFF`.

**Comment by niyue** [comment]
After switching to use 2 implementations for legacy/new PassManager API, there are still 2 relevant CI checks failed:
* https://github.com/apache/arrow/actions/runs/6333190457/job/17200939461?pr=37867
* https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/48144061

Both seemed to be related with LLVM linking issue. I will do some further investigation but may have to be off for a few days

File: cpp/src/gandiva/engine.cc [hunk 1]
```diff
@@ -268,49 +283,104 @@ Status Engine::LoadPreCompiledIR() {
...
 
   std::unordered_set<std::string> used_functions;
   used_functions.insert(functions_to_compile_.begin(), functions_to_compile_.end());
 
-  pass_manager->add(
-      llvm::createInternalizePass([&used_functions](const llvm::GlobalValue& func) {
-        return (used_functions.find(func.getName().str()) != used_functions.end());
+  module_pm.addPass(
+      llvm::InternalizePass([&used_functions](const llvm::GlobalValue& GV) -> bool {
+        return used_functions.find(GV.getName().str()) != used_functions.end();
```
Comment (kou) [inline cpp/src/gandiva/engine.cc:297]: How about lower case for like others?

```suggestion
      llvm::InternalizePass([&used_functions](const llvm::GlobalValue& gv) -> bool {
        return used_functions.find(gv.getName().str()) != used_functions.end();
```

Or can we use `variable` instead of `gv` for readability?

**Review by kou — APPROVED** [review]
+1

I've fixed the remained CI failures.

File: cpp/src/gandiva/engine.cc (hunk 1 above)
Comment (kou) [reply cpp/src/gandiva/engine.cc:297]: I'll use `variable` and merge this to fix CI failures for now:

```suggestion
      llvm::InternalizePass([&used_functions](const llvm::GlobalValue& variable) -> bool {
        return used_functions.find(variable.getName().str()) != used_functions.end();
```

We can improve this later in a follow-up PR if it's need.

**Comment by niyue** [comment]
@kou thanks so much for fixing the remaining issues!
