### PR TITLE
GH-34532: [Java][FlightSQL] Change JDBC to handle multi-endpoints

### LINKED ISSUE #34532: [Java] JDBC Flight SQL driver should follow Flight RPC spec
### Describe the bug, including details regarding any error messages, version, and platform.

The JDBC Flight SQL driver assumes that the endpoints are all the same as the main server connection, but this is wrong. It should connect to individual endpoints specified by GetFlightInfo.

#13900 tried to fix it but the original contributor isn't interested - this would be a starting point for future contributors

### Component(s)

FlightRPC, Java

### PR DESCRIPTION
**Pull request by jduo**
### Rationale for this change
The Flight SQL JDBC Driver currently doesn't fetch at multiple endpoints correctly when the data is not at the same location as the original connection.

### What changes are included in this PR?
- Create new clients to connect to new locations in endpoints.
- If no location is reported using the current connection.
- Make ArrowFlightSqlClientHandler's builder's build() function to be idempodent.
- Add functionality to clone ArrowFlightSqClientHandler's builder so that it can be used for temporary connections to locations returned by getFlightInfo().
- Add utility classes in unit tests for constructing a distributed Flight SQL Server

### Are these changes tested?
Yes.

### Are there any user-facing changes?
The behavior for when there are reported endpoints from getFlightInfo is now fixed. However if users relied on the previous behavior of just getting streams from the same node, and their server only ever reported the original node, they may observe more Flight client connections opening and closing than before (since new connections get spawned for each partition that has at least one Location now).

* Closes: apache/arrow#34532
* GitHub Issue: #34532

### CODE REVIEW

**Comment by jduo** [comment]
This work is partially based off #13900.

**Comment by jduo** [comment]
@lidavidm

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java [hunk 1]
```diff
@@ -95,11 +102,48 @@ private CallOption[] getOptions() {
...
+
+          final ArrowFlightSqlClientHandler endpointHandler = builderForEndpoint.build();
+          try {
+            endpoints.add(new CloseableEndpointStreamPair(
+                endpointHandler.sqlClient.getStream(endpoint.getTicket(),
+                    endpointHandler.getOptions()), endpointHandler.sqlClient));
+          } catch (Exception ex) {
+            AutoCloseables.close(endpointHandler);
+            throw ex;
+          }
```
[the remark this answers is not in the document]
Comment (lidavidm) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java:131]: Also, having a cache of clients instead of opening new ones every time (e.g. via https://github.com/ben-manes/caffeine)

**Review by lidavidm — APPROVED** [review]

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java:131]: Added #38573 and #38574 for these topics.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java [hunk 2]
```diff
@@ -364,6 +415,31 @@ public static final class Builder {
...
+
+    }
+
+    /**
+     * Copies the builder.
+     *
+     * @param original The builder to base this copy off of.
+     */
+    private Builder(Builder original) {
+      this.middlewareFactories.addAll(original.middlewareFactories);
```
Comment (aiguofer) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java:428]: I just want to verify, this would ensure the CookiesMiddleware gets copied over for the Endpoint clients, correct?

Comment (lidavidm) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java:428]: Ah, I didn't think about that, but yes, it should mean that the middleware gets shared between the clients. That might be good or bad depending on the server implementation but we can follow up if it turns out to be an issue.

Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java:428]: A new CookieMiddlewareFactory is created for subsequent connections (same with the AuthMiddlewareFactory). This was intentional but should actually be configurable.

Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java:428]: Added #38576 . This one can cause breakage for existing users that are relying on the same cookie/auth token from being sent so I'll pick it up next.

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java:428]: Awesome thanks! we depend on cookies to maintain state and expect the callOptions we set to go out with every request so that will be important for us!
