### PR TITLE
GH-40038: [Java] Export non empty offset buffer for variable-size layout through C Data Interface

### LINKED ISSUE #40038: [Java] The offset buffer of empty BaseVariableWidthVector should not be empty when exposed through C Data Interface
### Describe the bug, including details regarding any error messages, version, and platform.

We encountered an error when exchanging string array from Java to Rust through Arrow C data interface. At Rust side, it complains that the buffer at position 1 (offset buffer) is null. After tracing down and some debugging, it looks like the issue is Java Arrow `BaseVariableWidthVector` class assigns an empty offset buffer if the array is empty (value count 0).

According to Arrow [spec](https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-layout) for variable size binary layout:

> The offsets buffer contains length + 1 signed integers ...

So for an empty string array, its offset buffer should be a buffer with one element (generally it is `0`).

### Component(s)

Java

### PR DESCRIPTION
**Pull request by viirya**
### Rationale for this change

We encountered an error when exchanging string array from Java to Rust through Arrow C data interface. At Rust side, it complains that the buffer at position 1 (offset buffer) is null. After tracing down and some debugging, it looks like the issue is Java Arrow `BaseVariableWidthVector` class assigns an empty offset buffer if the array is empty (value count 0).

According to Arrow [spec](https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-layout) for variable size binary layout:

> The offsets buffer contains length + 1 signed integers ...

So for an empty string array, its offset buffer should be a buffer with one element (generally it is `0`).

### What changes are included in this PR?

This patch replaces current empty offset buffer in variable-size layout vector classes when exporting arrays through C Data Interface.

### Are these changes tested?

Added test cases.

### Are there any user-facing changes?

No

* Closes: #40038

### CODE REVIEW

File: java/vector/src/main/java/org/apache/arrow/vector/complex/AbstractStructVector.java [hunk 1]
```diff
@@ -233,6 +233,11 @@ public <T extends FieldVector> T getChild(String name, Class<T> clazz) {
 
   protected ValueVector add(String childName, FieldType fieldType) {
     FieldVector vector = fieldType.createNewSingleVector(childName, allocator, callBack);
+
+    if (conflictPolicy == ConflictPolicy.CONFLICT_REPLACE && vectors.containsKey(childName)) {
+      vectors.getAll(childName).forEach(c -> c.close());
+    }
```
Comment (viirya) [inline java/vector/src/main/java/org/apache/arrow/vector/complex/AbstractStructVector.java:239]: This address test failure in `TestStructVector`. When duplicate field names exist in `initializeChildrenFromFields` call, the initial offset buffer in previous vectors will cause memory leak. So these duplicate vectors are closed here.

File: java/vector/src/main/java/org/apache/arrow/vector/complex/BaseRepeatedValueVector.java [hunk 2]
```diff
@@ -97,11 +98,13 @@ public boolean allocateNewSafe() {
...
 
-  protected void allocateOffsetBuffer(final long size) {
+  protected void allocateOffsetBuffer(final long size, boolean init) {
     final int curSize = (int) size;
     offsetBuffer = allocator.buffer(curSize);
     offsetBuffer.readerIndex(0);
-    offsetAllocationSizeInBytes = curSize;
+    if (!init) {
+      offsetAllocationSizeInBytes = curSize;
+    }
```
Comment (viirya) [inline java/vector/src/main/java/org/apache/arrow/vector/complex/BaseRepeatedValueVector.java:107]: This is to avoid changing `offsetAllocationSizeInBytes` to the initial 4 byte size. Otherwise, `reallocOffsetBuffer` will take it and cause some tests failed.

File: java/adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/ResultSetUtilityTest.java [hunk 3]
```diff
@@ -50,6 +50,7 @@ public void testZeroRowResultSet() throws Exception {
         assertNotNull("VectorSchemaRoot from first next() result should never be null", root);
         assertEquals("VectorSchemaRoot from empty ResultSet should have zero rows", 0, root.getRowCount());
         assertFalse("hasNext() should return false on empty ResultSets after initial next() call", iter.hasNext());
+        root.close();
```
Comment (viirya) [inline java/adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/ResultSetUtilityTest.java:53]: This is needed to release initial offset buffer for empty array.

**Review by viirya — COMMENTED** [review]
I've run vector tests locally and they are passed. The tests in other modules might still have failure. If any, I will look at them later.

**Review by lidavidm — CHANGES_REQUESTED** [review]
Java is correct here.

https://lists.apache.org/thread/w7g1zfqrjxx0bvrct0mt5zwxvdnc9nob

**Comment by viirya** [comment]
Ah, okay, I see. I've not found the ticket. Looks like both cases (empty or single zero element) are acceptable. I will close this. Thanks for the info.

**Comment by lidavidm** [comment]
Are you using arrow2? It's possible it was never updated to fix this, but arrow-rs appears to have been fixed

**Comment by lidavidm** [comment]
Hmm. While we allow that for IPC, I think I'm wrong about C Data: we explicitly specify this is not allowable https://arrow.apache.org/docs/format/CDataInterface.html#c.ArrowArray.buffers

@pitrou presumably Java should actually be fixed here, but what do other implementations do/we appear to be missing tests for this case?

**Comment by viirya** [comment]
> The buffer pointers MAY be null only in two situations:
> for the null bitmap buffer, if ArrowArray.null_count is 0;
> for any buffer, if the size in bytes of the corresponding buffer would be 0.

Isn't it allowed for second situation?

File: java/adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/ResultSetUtilityTest.java (hunk 3 above)
Comment (pitrou) [reply java/adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/ResultSetUtilityTest.java:53]: Perhaps we can use a `try` instead of calling `close` explicitly?

**Comment by lidavidm** [comment]
Ah, fair. It reads as a bit ambiguous to me: would the size of the buffer be 0, or is it that it should not be 0, but we allowed 0 as an exception before? I guess both interpretations lead to the buffer being 0-sized, though, and so it applies. Maybe we should spell out the case...

Regardless, it does seem we're missing an integration test then.

**Comment by pitrou** [comment]
> @pitrou presumably Java should actually be fixed here, but what do other implementations do/we appear to be missing tests for this case?

Yes, I think it should be fixed. Zero-length columns _are_ tested in the integration test, but whether they actually miss an offsets buffer depends on how the JSON reader behaves.

**Comment by lidavidm** [comment]
Sorry, this is for the C Data integration tests

**Comment by lidavidm** [comment]
Ah ok, now I see what you mean

File: java/flight/flight-core/src/test/java/org/apache/arrow/flight/TestDictionaryUtils.java [hunk 4]
```diff
@@ -87,6 +87,8 @@ public void testCreateSchema() {
 
       assertEquals(1, dictionaryUsed.size());
       assertEquals(0, dictionaryUsed.first());
+
+      dictVec.close();
```
Comment (pitrou) [inline java/flight/flight-core/src/test/java/org/apache/arrow/flight/TestDictionaryUtils.java:91]: Same here?

File: java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java [hunk 5]
```diff
@@ -73,7 +73,8 @@ public BaseLargeVariableWidthVector(Field field, final BufferAllocator allocator
     lastValueCapacity = INITIAL_VALUE_ALLOCATION - 1;
     valueCount = 0;
     lastSet = -1;
-    offsetBuffer = allocator.getEmpty();
+    // According to Arrow spec, the offsets buffer contains length + 1 elements
+    allocateOffsetBuffer(OFFSET_WIDTH);
```
Comment (pitrou) [inline java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:77]: It might be expensive to do this up front every time an empty vector is created. Should this be done lazily?

File: java/vector/src/main/java/org/apache/arrow/vector/complex/AbstractStructVector.java (hunk 1 above)
Comment (pitrou) [reply java/vector/src/main/java/org/apache/arrow/vector/complex/AbstractStructVector.java:239]: Shouldn't this be done in `putVector` instead?

**Comment by pitrou** [comment]
It seems this fix might be a bit heavy-handed if it adds a heap allocation for every empty var-width vector? AFAIU, Arrow Java uses empty vectors quite liberally.

**Comment by viirya** [comment]
> Ah, fair. It reads as a bit ambiguous to me: would the size of the buffer be 0, or is it that it should not be 0, but we allowed 0 as an exception before? I guess both interpretations lead to the buffer being 0-sized, though, and so it applies. Maybe we should spell out the case...

I think it should mean that the buffer size is 0, the buffer pointers may be null, for the second situation.

**Comment by pitrou** [comment]
> I think it should mean that the buffer size is 0, the buffer pointers may be null, for the second situation.

Yes, but it's the _buffer size_, not the array size. For an empty array, the buffer size should be 4 (or 8 for a large offsets type), so the buffer can't be null.

**Comment by viirya** [comment]
> It seems this fix might be a bit heavy-handed if it adds a heap allocation for every empty var-width vector? AFAIU, Arrow Java uses empty vectors quite liberally.

Yea, and I believe that @lidavidm meant that these empty offsets for empty var-width vector are valid. That's why I closed this and proposed a fix at ffi module at Rust instead.

**Comment by viirya** [comment]
> Yes, but it's the buffer size, not the array size. For an empty array, the buffer size should be 4 (or 8 for a large offsets type), so the buffer can't be null.

That's what I thought at the beginning and the reason I proposed this fix.

But somehow from the context @lidavidm provided:
https://lists.apache.org/thread/w7g1zfqrjxx0bvrct0mt5zwxvdnc9nob

I think he means that it is a valid case (empty offset).

File: java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java (hunk 5 above)
Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:77]: Hmm, maybe I should update the export code of C data interface here? I think previously the empty offset buffer works like a lazy offset buffer in var-wide arrays. They are expanded to valid format (length + 1) once the array has elements.

**Comment by viirya** [comment]
I guess that this might be something we really need to fix (at least for the C data export part for var-size arrays). Reopened it.

**Comment by viirya** [comment]
> Yes, but it's the buffer size, not the array size. For an empty array, the buffer size should be 4 (or 8 for a large offsets type), so the buffer can't be null.

Except for empty array, I cannot image any other case that could result in empty offset buffer. So I guess that it means we should not never have null offset buffer in C data interface?

But from above context and the implementation in arrow-rs, it looks like we allow empty offset buffer for empty array?

**Comment by viirya** [comment]
> As long as data stays internal to Arrow Java, the missing buffer is ok, but for purposes of exchanging data, a proper offsets buffers should be exported (this one can easily be statically allocated, by the way).

I see. Then it makes sense. So seems I should not change these empty offset buffers as currently did in this PR but should change C data interface in Java to properly export it for empty offset cases.

**Comment by pitrou** [comment]
Yes, I think it would be the most reasonable change here.

File: java/vector/src/main/java/org/apache/arrow/vector/FieldVector.java [hunk 6]
```diff
@@ -60,6 +60,17 @@ public interface FieldVector extends ValueVector {
...
+
+  /**
+   * Get the buffers for C Data Interface, (same size as getFieldVectors() since it is their content).
+   * By default, it returns the same as getFieldBuffers().
+   *
+   * @return the buffers containing the data for this vector (ready for exporting through C Data Interface)
+   */
+  default List<ArrowBuf> getCDataBuffers() {
+    return getFieldBuffers();
+  }
```
Comment (viirya) [inline java/vector/src/main/java/org/apache/arrow/vector/FieldVector.java:72]: I thought a few approaches to achieve the goal to fix this issue. This is less intrusive one I can think of.

I've tried to modify `getFieldBuffers` directly. But it seems also used not only for C Data Interface. So that change causes some test failures.

File: java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java [hunk 7]
```diff
@@ -476,11 +507,12 @@ private void allocateBytes(final long valueBufferSize, final int valueCount) {
   }
 
   /* allocate offset buffer */
-  private void allocateOffsetBuffer(final long size) {
+  private ArrowBuf allocateOffsetBuffer(final long size) {
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: Is the intent of this change to avoid changing the existing offset buffer, and only change it for the exported version? Then I must ask

(1) why? If we're allocating the buffer, we may as well use it for the vector as well.
(2) is this safe in terms of leaking memory? since apparently nothing will hold on to the buffer after allocating it above

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: For 2, this is only for exporting the vectors through C Data Interface. By it means, it is intended to be released by the importer side. At Java Arrow, I remember ArrayExporter only increases the reference count for the buffers to be exported to prevent them to be released automatically.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: For 1, they are allocated for using only at imported side. I think as per discussed with @pitrou above, the idea is these empty buffers exist internally and it is okay.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: I think Antoine's idea was that you could statically allocate one such buffer to use in such situations, if you're talking about this

> As long as data stays internal to Arrow Java, the missing buffer is ok, but for purposes of exchanging data, a proper offsets buffers should be exported (this one can easily be statically allocated, by the way).

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: And yes, it seems ArrayExporter will increase the reference count by 1. But since it starts with a reference count of 1, that means these buffers will never be freed.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: > And yes, it seems ArrayExporter will increase the reference count by 1. But since it starts with a reference count of 1, that means these buffers will never be freed.

No. There is callback in exported structured that is used to release buffer. The responsibility of calling the callback is on imported side (for example, Rust arrow, for our case). Once the imported side doesn't need the vector anymore, it will trigger the callback to release the buffer allocated in exported side.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: Which will decrement the refcount by 1, but the refcount of this buffer will be 2, right? It starts at 1 when you allocate it, and is increased by 1 when you export it. Then Rust calls the callback and the refcount is decremented by 1. It will not get freed.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: See:

https://github.com/apache/arrow/blob/0dbbd43ca9133912d1809394727784560cc5e797/java/c/src/main/cpp/jni_wrapper.cc#L142
https://github.com/apache/arrow/blob/0dbbd43ca9133912d1809394727784560cc5e797/java/c/src/main/java/org/apache/arrow/c/ArrayExporter.java#L57

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: I'm well aware of how C Data works. I'm asking about how the reference counting is supposed to work here.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: Closing the vector here won't affect the reference count of this buffer because it explicitly isn't set as the vector's offset buffer.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:510]: Okay, I got your point. I don't familiar with Java Arrow buffer allocation mechanism. I traced how it is allocated now so the ref count is increased automatically once it is allocated.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: > I think Antoine's idea was that you could statically allocate one such buffer to use in such situations, if you're talking about this
> 
> > As long as data stays internal to Arrow Java, the missing buffer is ok, but for purposes of exchanging data, a proper offsets buffers should be exported (this one can easily be statically allocated, by the way).

Hmm, I think what Antoine means is, we should export a proper offset buffer (instead of empty one currently) for exporting purpose, isn't?

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: Yes, we can export a proper offset buffer, **but all such cases can share the same buffer** because the data is always the same

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: I'm saying that once you export the buffer, you might as well set it to be the offset buffer? Not when you create the vector. (That may also be surprising to users, sure.) But it would be the only way to avoid this memory leak.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: Hmm, I think I got your point. But I am wondering if it makes sense. I doubt that after exporting an array, it still makes sense to hold and modify it at exported side.

Especially,

https://arrow.apache.org/docs/format/CDataInterface.html#mutability

> Both the producer and the consumer SHOULD consider the exported data (that is, the data reachable through the buffers member of ArrowArray) to be immutable, as either party could otherwise see inconsistent data while the other is mutating it.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: If you insist that the offset buffer must keep same buffer between Java Arrow and exported side. The only way is to set it (the one value offset) to the offset of the vector. But as I said before, it will cause a lot inconsistency in Java Arrow.

I don't think an inconsistent offset (sometimes it is empty sometimes it is one value buffer) is a good idea. Very confused and easy to cause bugs.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: > Now the created one value buffer only has one ref count for imported side.

I've gone over this: when a buffer is allocated, it starts with a refcount of 1. As you yourself pointed out, exporting it increases the refcount. And when the consumer calls the release callback, the refcount is only decreased by 1. So the refcount does not reach 0.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: This works for the other buffers of the vector because the vector holds the buffer, so when the vector itself is closed it decrements the refcounts of the buffers, so they reach 0. But for the buffer which we allocate on the fly here, that is not true.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: > I don't think an inconsistent offset (sometimes it is empty sometimes it is one value buffer) is a good idea. Very confused and easy to cause bugs.

Code shouldn't make assumptions because we've already documented that those assumptions are wrong. It would be equally true for code working with imported arrays: they may have a one value buffer.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: The mutability ship has sailed for the Java implementation. It would be no different for any array here no matter what we do.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: > > Now the created one value buffer only has one ref count for imported side.
> 
> I've gone over this: when a buffer is allocated, it starts with a refcount of 1. As you yourself pointed out, exporting it increases the refcount. And when the consumer calls the release callback, the refcount is only decreased by 1. So the refcount does not reach 0.

Hmm, don't you see my latest commit? It doesn't increase ref count when exporting.

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: This is making the problem worse for all non-offset buffers (which now get an extra refcount) while not changing it for the offset buffer (because, again, please see the sequence of events that I keep outlining above...)

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: > > I don't think an inconsistent offset (sometimes it is empty sometimes it is one value buffer) is a good idea. Very confused and easy to cause bugs.
> 
> Code shouldn't make assumptions because we've already documented that those assumptions are wrong. It would be equally true for code working with imported arrays: they may have a one value buffer.

Hmm, but this is the current code status...

You can see how these var-size vectors handle offset buffer, they assume that the initial capacity of offset buffer is 0. That's why I got some many test failure after I changed the initial offset buffer.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: To move this forward instead of arguing continuously. I would like confirm that if the following approach is acceptable to you.

1. Not change current initial offset buffer when creating vector, i.e., they are empty as usual.
2. Allocate one value offset buffer when exporting vector and replace the existing (empty) offset buffer.
3. For the places in var-size vectors which have the assumption about initial offset buffer capacity (zero), changing it or throwing some error (as these places are going to re-allocate offset buffer).

WDYT?

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: Or, alternatively you would like to work on this if you have time and are willing to fix it soon (as we are blocked by this somehow). Although we could apply currently fix internally to unblock us, I would like to have consistent code between fork and open source and avoid resolving conflict later.

WDYT?

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: >> Hmm, don't you see my latest commit? It doesn't increase ref count when exporting.
>> Or I miss anything?
> This is making the problem worse for all non-offset buffers (which now get an extra refcount) while not changing it for the offset buffer (because, again, please see the sequence of events that I keep outlining above...)

I know what you meant, and I guess you don't see committed code but only the comment, so there is confusion.

In latest commit, I don't increase ref count when exporting offset buffer. For non-offset buffers, of course their refcounts are increased as before.

Comment (vibhatha) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: @viirya would it be possible to do a simple end-to-end experiment and log how the refcout varies in the original source vs the new change (at least the new change) and see what is actually happening. So if we have some call cancelling a mistake we made in the refcount could be thus reflected and clear our doubts. Is this a viable?

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: Hmm, this is a good suggestion. I'm not sure if it is viable now. I will try to find time looking into it.

Comment (vibhatha) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: I understand. Let me also evaluate this a bit thoroughly.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: @vibhatha I've added some more checks (buffer ref count, allocated memory) into the existing roundtrip tests of C data interface. Please take a look. Thanks.

Comment (vibhatha) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: I will take a look at this as soon as possible.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: Hi @vibhatha, sorry for pinging you. Do you have a chance to look at this recently? One important feature is blocked by the issue and we are looking forward to move this into Java Arrow library. Thank you. 🙏

**Comment by viirya** [comment]
cc @sunchao for another eyes on this. Thanks.

File: java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java (hunk 7 above)
Comment (vibhatha) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: @viirya I couldn't take a look. But let me see if I can allocate some time to do this probably earlier next week?

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java:504]: @vibhatha It will be great! Thank you so much!

File: java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java [hunk 8]
```diff
@@ -336,6 +336,31 @@ public List<ArrowBuf> getFieldBuffers() {
...
+    // are not updated. this may cause some data in the data buffer being lost.
+    // for details, please see TestValueVector#testUnloadVariableWidthVector.
+    fillHoles(valueCount);
+
+    exportBuffer(validityBuffer, buffers, buffersPtr, nullValue, true);
+
+    if (offsetBuffer.capacity() == 0) {
+      // Empty offset buffer is allowed for historical reason.
+      // To export it through C Data interface, we need to allocate a buffer with one offset.
+      exportBuffer(allocateOffsetBuffer(OFFSET_WIDTH), buffers, buffersPtr, nullValue, false);
```
Comment (andygrove) [inline java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:356]: @viirya I just want to make sure I understand what is happening here. It seems we are creating a new buffer which will have ref count of zero, then you specify `retain = false` when calling `exportBuffer` so the ref count is still zero, right? Then the export will increment to 1, which is the desired behavior.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:356]: Yes. By default when creating a new buffer the allocator will increase ref count to retain the buffer for the holder (i.e., the vector). The array exporter increases ref count that represents the buffer is retained by the importer.

This offset buffer is not retained by the vector actually, but only for the importer. So it doesn't increase the ref count when creating it (as it is not held by the vector). In array exporter, it will increase ref count for the buffer as usual.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:356]: By default when creating a new buffer the allocator will increase ref count to retain the buffer for the holder, so its initial ref count is 1.

When we are going to export an empty offset buffer, we create a new offset with one offset value zero. `exportBuffer` is called with `retain = false` so it won't increase its ref count. Its ref count is 1 which is for importer.

For other buffers, `exportBuffer` will increase ref count by 1 which represents a new reference by the importer.

Comment (viirya) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:359]: Added some more comments.

Comment (andygrove) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:359]: Thanks for the clarification @viirya. 

@lidavidm Does this address the specific concern that you had about how reference counting is working here?

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java:359]: Probably, thanks for the explanation. I still want to take a closer look which I'll try to do in time for 16.0.0 code freeze but I will probably need a few days before I can get to this.

**Review by lidavidm — APPROVED** [review]

**Comment by andygrove** [comment]
Thanks for the review @lidavidm

**Comment by viirya** [comment]
Thank you @lidavidm @pitrou @vibhatha @andygrove for the review
