### PR TITLE
GH-44214: [C++] JsonExtensionType equality check ignores storage type

### LINKED ISSUE #44214: [C++] JsonExtensionType equality check ignores storage type
### Describe the bug, including details regarding any error messages, version, and platform.

As noted here: https://github.com/apache/arrow/pull/13901#discussion_r1772765813

### Component(s)

C++

### PR DESCRIPTION
**Pull request by rok**
### Rationale for this change

As noted in https://github.com/apache/arrow/pull/13901#pullrequestreview-2324294761:
```cpp
bool JsonExtensionType::ExtensionEquals(const ExtensionType& other) const {
  return other.extension_name() == this->extension_name();
}
```
> This equality check does not take into account the storage type, but only the name.
> As a consequence, a JsonExtensionType<string> type will be seen as equal to JsonExtensionType<large_string>.

### What changes are included in this PR?

This change introduces storage equality check into `JsonExtensionType` equality check.

This also fixes a storage type check in `JsonExtensionType::Make`.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #44214

### CODE REVIEW

File: cpp/src/arrow/extension/json.h [hunk 1]
```diff
@@ -45,12 +45,14 @@ class ARROW_EXPORT JsonExtensionType : public ExtensionType {
...
+  static Result<std::shared_ptr<DataType>> Make(const std::shared_ptr<DataType>& storage_type);
+
  private:
   std::shared_ptr<DataType> storage_type_;
 };
 
 /// \brief Return a JsonExtensionType instance.
 ARROW_EXPORT std::shared_ptr<DataType> json(
-    std::shared_ptr<DataType> storage_type = utf8());
+    const std::shared_ptr<DataType>& storage_type = utf8());
```
Comment (pitrou) [inline cpp/src/arrow/extension/json.h:56]: The original signature was slightly better, since it didn't imply a `std::shared_ptr` copy. Though it arguably doesn't matter much.

File: cpp/src/parquet/arrow/arrow_schema_test.cc [hunk 2]
```diff
@@ -763,7 +763,7 @@ TEST_F(TestConvertParquetSchema, ParquetSchemaArrowExtensions) {
     props.set_arrow_extensions_enabled(true);
     auto arrow_schema = ::arrow::schema(
         {::arrow::field("json_1", ::arrow::extension::json(), true),
-         ::arrow::field("json_2", ::arrow::extension::json(::arrow::large_utf8()),
+         ::arrow::field("json_2", ::arrow::extension::json(::arrow::utf8()),
```
Comment (pitrou) [inline cpp/src/parquet/arrow/arrow_schema_test.cc:766]: Instead of making the test easier, can you keep `large_utf8` and ensure it passes?

**Review by pitrou — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/extension/json.h (hunk 1 above)
Comment (rok) [reply cpp/src/arrow/extension/json.h]: Sorry for that. Restoring.

File: cpp/src/parquet/arrow/arrow_schema_test.cc (hunk 2 above)
Comment (rok) [reply cpp/src/parquet/arrow/arrow_schema_test.cc]: Can we reconstruct storage type if it is not stored? In this case we know data is of JSON logical type, but we don't know what was it's storage type at write time. Am I missing something?

Comment (rok) [reply cpp/src/parquet/arrow/arrow_schema_test.cc]: (There was a test where arrow schema was available and wasn't used at read time. I've addressed that)

Comment (pitrou) [reply cpp/src/parquet/arrow/arrow_schema_test.cc]: > Can we reconstruct storage type if it is not stored? In this case we know data is of JSON logical type, but we don't know what was it's storage type at write time. Am I missing something?

No, I'm asking you to write the test so that it reflects that.

Comment (rok) [reply cpp/src/parquet/arrow/arrow_schema_test.cc]: Something like this? https://github.com/apache/arrow/pull/44215/commits/e522efb7a0d291573e8c44548b68e9d120e70328

Comment (pitrou) [reply cpp/src/parquet/arrow/arrow_schema_test.cc]: Yes.

File: cpp/src/parquet/arrow/schema.cc [hunk 3]
```diff
@@ -1017,7 +1017,9 @@ Result<bool> ApplyOriginalMetadata(const Field& origin_field, SchemaField* infer
 
       // Restore extension type, if the storage type is the same as inferred
       // from the Parquet type
-      if (ex_type.storage_type()->Equals(*inferred->field->type())) {
+      if (ex_type.storage_type()->Equals(*inferred->field->type()) ||
+          (ex_type.extension_name() == "arrow.json" &&
+           !ex_type.storage_type()->Equals(*inferred->field->type()))) {
```
Comment (jorisvandenbossche) [inline cpp/src/parquet/arrow/schema.cc:1022]: This "types are not equal" check is superfluous? Because if they were equal, the first part of the if check would have passed and we wouldn't get here?

I assume that in case of JSON extension type, we either just have to assume that the data will correctly use string, or we check explicitly that the inferred type is string type?

Comment (rok) [reply cpp/src/parquet/arrow/schema.cc]: It is superfluous indeed. Changed as per your suggestion: https://github.com/apache/arrow/pull/44215/commits/3364c0f0f70a37c84e134043537c4ee4d55fbbd6

File: cpp/src/arrow/extension/json.cc [hunk 4]
```diff
@@ -51,11 +47,18 @@ std::shared_ptr<Array> JsonExtensionType::MakeArray(
...
+  if (storage_type->id() != Type::STRING && storage_type->id() != Type::STRING_VIEW &&
+      storage_type->id() != Type::LARGE_STRING) {
+    return Status::Invalid("Invalid storage type for JsonExtensionType: ",
+                           storage_type->ToString());
+  }
   return std::make_shared<JsonExtensionType>(storage_type);
 }
 
+std::shared_ptr<DataType> json(std::shared_ptr<DataType> storage_type) {
+  return JsonExtensionType::Make(storage_type).ValueOrDie();
```
Comment (pitrou) [inline cpp/src/arrow/extension/json.cc:61]:
```suggestion
  return JsonExtensionType::Make(std::move(storage_type)).ValueOrDie();
```

Also, please ensure that `JsonExtensionType::Make` takes a `std::shared_ptr<DataType>`.

Comment (rok) [reply cpp/src/arrow/extension/json.cc]: Done.

File: cpp/src/arrow/extension/json.cc [hunk 5]
```diff
@@ -28,17 +28,13 @@
...
 
 Result<std::shared_ptr<DataType>> JsonExtensionType::Deserialize(
     std::shared_ptr<DataType> storage_type, const std::string& serialized) const {
-  if (storage_type->id() != Type::STRING && storage_type->id() != Type::STRING_VIEW &&
-      storage_type->id() != Type::LARGE_STRING) {
-    return Status::Invalid("Invalid storage type for JsonExtensionType: ",
-                           storage_type->ToString());
-  }
-  return std::make_shared<JsonExtensionType>(storage_type);
+  return JsonExtensionType::Make(storage_type);
```
Comment (pitrou) [inline cpp/src/arrow/extension/json.cc:37]:
```suggestion
  return JsonExtensionType::Make(std::move(storage_type));
```

File: cpp/src/arrow/extension/json.cc [hunk 6]
```diff
@@ -51,11 +47,18 @@ std::shared_ptr<Array> JsonExtensionType::MakeArray(
...
-              storage_type->id() != Type::STRING_VIEW ||
-              storage_type->id() != Type::LARGE_STRING);
+Result<std::shared_ptr<DataType>> JsonExtensionType::Make(
+    std::shared_ptr<DataType> storage_type) {
+  if (storage_type->id() != Type::STRING && storage_type->id() != Type::STRING_VIEW &&
+      storage_type->id() != Type::LARGE_STRING) {
+    return Status::Invalid("Invalid storage type for JsonExtensionType: ",
+                           storage_type->ToString());
+  }
   return std::make_shared<JsonExtensionType>(storage_type);
```
Comment (pitrou) [inline cpp/src/arrow/extension/json.cc:57]:
```suggestion
  return std::make_shared<JsonExtensionType>(std::move(storage_type));
```

**Review by pitrou — COMMENTED** [review]
Remaining nits

**Comment by rok** [comment]
> Remaining nits

@pitrou added your changes.

File: cpp/src/arrow/extension/json.cc [hunk 7]
```diff
@@ -51,11 +47,18 @@ std::shared_ptr<Array> JsonExtensionType::MakeArray(
...
 }
 
-std::shared_ptr<DataType> json(const std::shared_ptr<DataType> storage_type) {
-  ARROW_CHECK(storage_type->id() != Type::STRING ||
-              storage_type->id() != Type::STRING_VIEW ||
-              storage_type->id() != Type::LARGE_STRING);
-  return std::make_shared<JsonExtensionType>(storage_type);
+Result<std::shared_ptr<DataType>> JsonExtensionType::Make(
+    std::shared_ptr<DataType> storage_type) {
+  if (storage_type->id() != Type::STRING && storage_type->id() != Type::STRING_VIEW &&
```
Comment (wgtmac) [inline cpp/src/arrow/extension/json.cc:52]: Should we add the following static function to `JsonExtensionType` to remove repeated code here and in cpp/src/parquet/arrow/schema.cc below?

```
static bool IsSupportedStorageType(Type::type type_id) {
  return type_id == Type::STRING || type_id == Type::STRING_VIEW || type_id == Type::LARGE_STRING;
}
```

Comment (rok) [reply cpp/src/arrow/extension/json.cc]: Changed as suggested: https://github.com/apache/arrow/pull/44215/commits/1dd3ec2fe99e986dcb67335f0543b18f1904bc86

**Comment by rok** [comment]
@pitrou do you think you'd have time to review this for the 18.0.0 (~mid next week)?

File: cpp/src/parquet/arrow/schema.cc [hunk 8]
```diff
@@ -1017,7 +1016,10 @@ Result<bool> ApplyOriginalMetadata(const Field& origin_field, SchemaField* infer
 
       // Restore extension type, if the storage type is the same as inferred
       // from the Parquet type
-      if (ex_type.storage_type()->Equals(*inferred->field->type())) {
+      if (ex_type.storage_type()->Equals(*inferred->field->type()) ||
```
Comment (pitrou) [inline cpp/src/parquet/arrow/schema.cc:1019]: So suddently this condition only covers `arrow.json`, while it used to cover all extension types. Is this deliberate?

File: cpp/src/parquet/arrow/schema.cc [hunk 9]
```diff
@@ -1017,7 +1016,10 @@ Result<bool> ApplyOriginalMetadata(const Field& origin_field, SchemaField* infer
...
+          ((ex_type.extension_name() == "arrow.json") &&
+           ::arrow::extension::JsonExtensionType::IsSupportedStorageType(
```
Comment (pitrou) [inline cpp/src/parquet/arrow/schema.cc:1021]: The `IsSupportedStorageType` condition should always be true here, since `ex_type` is a JSONExtensionType and `inferred->field->type` is equal to `ex_type`'s storage type.

Comment (rok) [reply cpp/src/parquet/arrow/schema.cc]: Huh, yes `IsSupportedStorageType` is indeed redundant here. Removed.

File: cpp/src/parquet/arrow/schema.cc (hunk 8 above)
Comment (rok) [reply cpp/src/parquet/arrow/schema.cc:1019]: It was, but in light of your comment I'd say it's not a good idea.

**Comment by rok** [comment]
Thanks for the review @pitrou. I addressed the comments.

File: cpp/src/parquet/arrow/schema.cc (hunk 8 above)
Comment (pitrou) [reply cpp/src/parquet/arrow/schema.cc:1019]: Hmm, but why are we keeping the logical `||` condition here?

Comment (rok) [reply cpp/src/parquet/arrow/schema.cc:1019]: Sorry, I only removed the `IsSupportedStorageType` part. The reason being if we have an extension type with `large_utf8` storage the following test bellow will fail, because (if I remember correctly) we take parquet json logical type to mean storage type will be `utf8`. To fix that this proposes to override with inferred type whenever `arrow.json`.

https://github.com/apache/arrow/blob/6d156d1daf09c7f15fb25f95b81a45cce1dc3c71/cpp/src/parquet/arrow/arrow_schema_test.cc#L804-L820

Comment (rok) [reply cpp/src/parquet/arrow/schema.cc]: That would make it more idiomatic indeed. Changed.

**Comment by rok** [comment]
Sorry for the slow turnaround @pitrou. I've pushed a change.

File: cpp/src/parquet/arrow/schema.cc [hunk 10]
```diff
@@ -1009,6 +1008,20 @@ Result<bool> ApplyOriginalMetadata(const Field& origin_field, SchemaField* infer
       // Origin type is restored as Arrow should be considered the source of truth.
       inferred->field = inferred->field->WithType(origin_type);
       RETURN_NOT_OK(ApplyOriginalStorageMetadata(origin_field, inferred));
+    } else if (inferred_type->id() == ::arrow::Type::EXTENSION &&
+               ex_type.extension_name() == std::string("arrow.json") &&
+               ::arrow::extension::JsonExtensionType::IsSupportedStorageType(
+                   inferred_type->storage_id())) {
```
Comment (pitrou) [inline cpp/src/parquet/arrow/schema.cc:1014]: This condition `IsSupportedStorageType(inferred_type->storage_id()` should always be true, right? We cannot infer a json type with an incorrect storage type.

Comment (rok) [reply cpp/src/parquet/arrow/schema.cc]: Indeed. Removing this check.

**Review by pitrou — APPROVED** [review]
Thanks a lot @rok ! This looks good now.
