### PR TITLE
GH-37148: [C++] Explicitly list the integer values of the Type::type enum

### LINKED ISSUE #37148: [C++] Implementation (like R) rely on implicit numeric assignment of enum Type entries
### Describe the bug, including details regarding any error messages, version, and platform.

The `enum type` in C++ leaves the integer values implicitly defined and let the compiler assign the values to them automatically. This means an insertion of a new entry that is not at the end, causes implementations that rely on specific values (like R) to break with confusing error messages [1].

Assigning the values explicitly can communicate that these enum entry values are relied upon and can allow a more natural ordering of the list that is different from the numeric order the entries receive.

[1] https://github.com/apache/arrow/issues/37091

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

The enum type in C++ leaves the integer values implicitly defined and let the compiler assign the values to them automatically. This means an insertion of a new entry that is not at the end, causes implementations that rely on specific values (like R) to break with confusing error messages [1].

Assigning the values explicitly can communicate that these enum entry values are relied upon and can allow a more natural ordering of the list that is different from the numeric order the entries receive.

[1] https://github.com/apache/arrow/issues/37091

### What changes are included in this PR?

 - Setting numeric values of the enum entries explicitly
 - Completing an equivalent enum on the R side 
 
### Are these changes tested?

N/A

### Are there any user-facing changes?

No.
* Closes: #37148

### CODE REVIEW

**Review by zeroshade — APPROVED** [review]

**Comment by pitrou** [comment]
Would should we do about `MAX_ID` then?

**Comment by felipecrv** [comment]
> Would should we do about `MAX_ID` then?

Leave it unset, so the compiler sets it to the maximum.

File: r/R/enums.R [hunk 1]
```diff
@@ -79,6 +79,8 @@ Type <- enum("Type::type",
   LARGE_STRING = 34L,
   LARGE_BINARY = 35L,
   LARGE_LIST = 36L
+  INTERVAL_MONTH_DAY_NANO = 37L,
```
Comment (thisisnic) [inline r/R/enums.R:82]: Thanks for fixing this! Just missing a comma on the line above this one, and then hopefully tests should pass.

Comment (felipecrv) [reply r/R/enums.R:82]: Thank you! I fixed it and pushed again.

**Review by thisisnic — APPROVED** [review]

**Comment by thisisnic** [comment]
CI failures look to be a timeout and something with the dev script - I've re-triggered them both, but I *think* we can probably merge this once we're happy that's all they are?

**Review by bkietz — APPROVED** [review]
Explicit values for a large enumeration seems more readable to me, thanks!

**Comment by felipecrv** [comment]
@bkietz can you merge this?
