### PR TITLE
GH-34405: [C++] Add support for custom names in QueryOptions.  Wire this up to Substrait

### LINKED ISSUE #33434: [C++] Add Acero test to ensure names in the root relation of Substrain plans are retained
Currently, Acero retains the names in the root relation when it executes a Substrait plan but there isn't a unit test in place to prevent a future regression.

**Reporter**: [Bryce Mecum](https://issues.apache.org/jira/browse/ARROW-18252) / @amoeba

<sub>**Note**: *This issue was originally created as [ARROW-18252](https://issues.apache.org/jira/browse/ARROW-18252). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #34405: [C++] Make it possible to specify custom field names in QueryOptions
### Describe the enhancement requested

This is needed, for example, to run Substrait queries because those queries specify the output column names explicitly.  In general, it seems that it would be a pretty common ask to support column aliases instead of the auto-generated names (which can be quite unwieldy when casts are involved).

### Component(s)

C++

### PR DESCRIPTION
**Pull request by westonpace**
### Rationale for this change

Users want to be able to specify custom column names / aliases instead of using the ones generated by Acero

### What changes are included in this PR?

It is now possible to specify custom column names in QueryOptions.  In addition, the python Substrait bindings now use this feature so that the Substrait plan's names will be respsected.

### Are these changes tested?

Yes.  These are tested directly.  In addition, I added a python test for the Substrait bindings as this is actually a regression there and this should close https://github.com/apache/arrow/issues/33434.

### Are there any user-facing changes?

There is new API surface but nothing breaking.
* Closes: #34405
* Closes: gh-33434

### CODE REVIEW

File: cpp/src/arrow/compute/exec/options.h [hunk 1]
```diff
@@ -614,6 +616,13 @@ class ARROW_EXPORT TableSinkNodeOptions : public ExecNodeOptions {
   ///
   /// \see QueryOptions for more details
   std::optional<bool> sequence_output;
+  /// \brief Custom names to use for the columns.
+  ///
+  /// If specified then names must be provided for all fields. Currently, only a flat
+  /// schema is supported (see ARROW-15901).
```
Comment (lidavidm) [inline cpp/src/arrow/compute/exec/options.h:622]: nit: maybe we should refer to the GitHub issue instead? (I assume this was copied from above)

File: cpp/src/arrow/compute/exec/exec_plan.cc [hunk 2]
```diff
@@ -925,14 +943,32 @@ struct BatchConverter {
...
+  Result<std::shared_ptr<Schema>> InitializeSchema(
+      const std::vector<std::string>& names) {
+    // By this point this->schema will have been set by the SinkNode.  We potentially
+    // rename it with the names provided by the user and then return this in case the user
+    // wants to know the output schema.
+    if (!names.empty()) {
+      if (static_cast<int>(names.size()) != schema->num_fields()) {
+        return Status::Invalid(
+            "A plan was created with custom field names but the number of names did not "
+            "match the number of output columns");
```
Comment (lidavidm) [inline cpp/src/arrow/compute/exec/exec_plan.cc:955]: nit: include expected/actual count in the message for convenience?

**Review by lidavidm — APPROVED** [review]

File: cpp/src/arrow/compute/exec/exec_plan.cc (hunk 2 above)
Comment (westonpace) [reply cpp/src/arrow/compute/exec/exec_plan.cc]: Done.

**Review by lidavidm — APPROVED** [review]
