### PR TITLE
GH-36523: [C++] Fix TSan-detected lock ordering issues in S3

### LINKED ISSUE #36523: [C++] TSAN error in s3 (maybe false positive?)
### Describe the bug, including details regarding any error messages, version, and platform.

I encountered this while stress testing #35440 with TSAN enabled but I believe it's not related to #35440 and, indeed, not a bug at all.  I'm attaching the log from TSAN here but I'll give a summary.
[tsan_out.txt](https://github.com/apache/arrow/files/11973450/tsan_out.txt)

There are three locks involved and so it is quite confusing.

M0: The holder lock (`std::mutex S3ClientHolder::mutex_`)
M1: The finalizer lock (`std::shared_mutex S3ClientFinalizer::mutex_`)
M2: The upload state lock (`std::mutex UploadState::mutex`)

TSAN reports `Cycle in lock order graph: M0 => M1 => M2 => M0`

The task is "creating a bunch of files in parallel".

In the main thread we are calling create dir.  This all happens in `arrow::fs::S3FileSystem::Impl::CreateBucket`.  As part of this process we:

 * Obtain Exclusive Lock M0
 * Obtain Shared Lock M1

In a CPU thread we are closing a file, which causes us to upload the final part.  This all happens as part of `arrow::fs::(anonymous namespace)::ObjectOutputStream::UploadPart`.  As part of this process we:

 * Obtain Shared Lock M1
 * Obtain Exclusive Lock M2

In an I/O thread we are handling the upload outcome which causes us to call close on the file.  This all happens as part of `arrow::fs::(anonymous namespace)::ObjectOutputStream::HandleUploadOutcome`.  As part of this process we:

 * Obtain Exclusive Lock M2
 * Obtain Exclusive Lock M0

However, given that M1 is a shared lock, I'm not sure this deadlock that TSAN is reporting is possible.

Unfortunately, I think there is actually a potential deadlock here, just not the one that TSAN is reporting.  As part of `HandleUploadOutcome` it seems we are first locking the upload state and then locking the client holder (`M2` then `M0`).  As part of `UploadPart` we are first locking the client holder and then locking the upload state (`M0` then `M2`).  TSAN is reporting this latter operation as `M1` then `M2` which is also true, but not as interesting.

A good fix would probably be to release the upload state lock in `HandleUploadOutcome` before marking `pending_parts_completed` finished (in general it's not a good idea to mark futures finished when holding locks).  I want to reproduce and confirm this is actually a problem and this fix actually works.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by pitrou**
It is counter-intuitive, but lock ordering issues can happen even with a shared mutex locked in shared mode.
The reason is that locking again in shared mode can block while there are threads waiting to take the lock in exclusive mode. For this reason, we must avoid to keep the S3ClientLock taken before is it taken again.

* Closes: #36523

### CODE REVIEW

**Comment by pitrou** [comment]
Can you run this with your stress test @westonpace ?

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 1]
```diff
@@ -1158,7 +1179,7 @@ class ObjectInputFile final : public io::RandomAccessFile {
     req.SetKey(ToAwsString(path_.key));
 
     ARROW_ASSIGN_OR_RAISE(auto client_lock, holder_->Lock());
-    auto outcome = client_lock->HeadObject(req);
+    auto outcome = std::move(client_lock)->HeadObject(req);
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.cc:1182]: TBH I'm not sure if calling `std::move` here is enough to destroy `client_lock` at the end of this statement. @bkietz Can you advise?

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@raulcd Ideally we would have this PR in the release, because it fixes a late regression (we're not sure the regression can happen concretely, though).

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 1 above)
Comment (bkietz) [reply cpp/src/arrow/filesystem/s3fs.cc:1182]: `std::move` will not destroy this lock (in general, it's useful to think of `std::move` as doing nothing except flagging a reference as legal to move construct from). What you want here is
```suggestion
    S3Model::HeadObjectOutcome outcome;
    {
      ARROW_ASSIGN_OR_RAISE(auto client_lock, holder_->Lock());
      outcome = std::move(client_lock)->HeadObject(req);
    } // client lock goes out of scope here
```

or maybe
```suggestion
    ARROW_ASSIGN_OR_RAISE(auto outcome, holder_->Lock().Map([&](auto client_lock) {
      return client_lock->HeadObject(req);
    }));
```

Comment (bkietz) [reply cpp/src/arrow/filesystem/s3fs.cc:1182]: Or you might even prefer
```c++
template <auto MemberPtr, typename... Args>
auto S3ClientHolder::LockThenCall(Args&&... args) {
  return Lock().Map([&](S3ClientLock client_lock) {
    return (client_lock.get()->*MemberPtr)(std::forward<Args>(args)...);
  });
}
```

used like
```suggestion
    ARROW_ASSIGN_OR_RAISE(auto outcome, holder_->LockThenCall<&S3Client::HeadObject>(req));
```

**Review by westonpace — COMMENTED** [review]
I'll wait for this to merge and then update #35440 .  The approach there will need to change as it currently holds the client lock for the duration of the request and since `DeleteDirContents` calls `GetFileInfo` this will be a problem.  However, it should be easy enough to change it back to locking on the spot when needed.

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:1182]: Thanks @bkietz !

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel -g cpp

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc]: Ok, I opted for a more manual approach because mixing `arrow::Result` and `Aws::Outcome` is not really convenient:
https://github.com/apache/arrow/pull/36536/files#diff-27b767cd06b879c40106ea98d21d3b12f13ec6e9f9aa49218d10583c5c1899c4R725-R726

**Comment by pitrou** [comment]
@westonpace Are you available quickly for review?

**Review by kou — APPROVED** [review]
+1

(I don't know why `S3ClinetLock::Move()` works but LGTM if it works as we expect.)

**Comment by westonpace** [comment]
+1, after running my test multiple times with and without CPU stress I no longer see any TSAN errors.  I've included one minor comment tweak in #35440

**Comment by pitrou** [comment]
Great, thank you @westonpace :-)
