### PR TITLE
GH-35306: [Go] Fix Schema.Fields() to return copy of fields

### LINKED ISSUE #35306: [Go]: Schema Fields returns reference instead of copy
### Describe the bug, including details regarding any error messages, version, and platform.

All methods on `Schema` returns objects that shouldn't mutate the schema itself apart from `Fields()`.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by yevgenypats**
* Closes: #35306

### CODE REVIEW

File: go/arrow/schema.go [hunk 1]
```diff
@@ -194,7 +194,11 @@ func (sc *Schema) WithEndianness(e endian.Endianness) *Schema {
 func (sc *Schema) Endianness() endian.Endianness { return sc.endianness }
 func (sc *Schema) IsNativeEndian() bool          { return sc.endianness == endian.NativeEndian }
 func (sc *Schema) Metadata() Metadata            { return sc.meta }
-func (sc *Schema) Fields() []Field               { return sc.fields }
+func (sc *Schema) Fields() []Field { 
+	fields := make([]Field, len(sc.fields))
+	copy(fields, sc.fields)
+	return fields
+}
```
Comment (zeroshade) [inline go/arrow/schema.go:201]: I'm not sure I like this. From a performance standpoint, I'd prefer to return the slice as-is rather than a copy of the slice. Perhaps we should add a new function like `FieldsCopy()` or something to that end?

Comment (yevgenypats) [reply go/arrow/schema.go:201]: We can do that but currently all methods return copy of things - like `Metadata` for example and `Field(i)` apart from this one (which also bit me in our code as I wasn't expecting the returned value to change the internal state)

Comment (zeroshade) [reply go/arrow/schema.go:201]: @yevgenypats can you just add a test for this?
