### PR TITLE
GH-35571: [C++][CI][Parquet] Change `EQ` to `FLOAT_EQ` in Decryption tests

### LINKED ISSUE #35571: [C++][Parquet] Tests failing when comparing a std::vector of floating point values
### Describe the bug, including details regarding any error messages, version, and platform.

I saw this in the CI output for Windows AMD64 MINGW builds:

```
[----------] 6 tests from DecryptionTests/TestDecryptionConfiguration
[ RUN      ] DecryptionTests/TestDecryptionConfiguration.TestDecryption/0
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
[  FAILED  ] DecryptionTests/TestDecryptionConfiguration.TestDecryption/3, where GetParam() = (4, 0xd00c20 pointing to "encrypt_columns_and_footer_aad.parquet.encrypted") (12 ms)
[ RUN      ] DecryptionTests/TestDecryptionConfiguration.TestDecryption/4
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
[  FAILED  ] DecryptionTests/TestDecryptionConfiguration.TestDecryption/4, where GetParam() = (5, 0xd00c54 pointing to "encrypt_columns_and_footer_disable_aad_storage.parquet.encrypted") (4 ms)
[ RUN      ] DecryptionTests/TestDecryptionConfiguration.TestDecryption/5
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
  expected_column_data.values
    Which is: { 0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 11, 12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22, 23.1, 24.2, 25.3, 26.4, 27.5, 28.6, 29.7, 30.8, 31.9, 33, 34.1, ... }
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:325: Failure
Expected equality of these values:
  read_col_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
  expected_column_data.values
    Which is: { 0, 1.11111, 2.22222, 3.33333, 4.44444, 5.55556, 6.66667, 7.77778, 8.88889, 10, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778, 18.8889, 20, 21.1111, 22.2222, 23.3333, 24.4444, 25.5556, 26.6667, 27.7778, 28.8889, 30, 31.1111, 32.2222, 33.3333, 34.4444, ... }
[  FAILED  ] DecryptionTests/TestDecryptionConfiguration.TestDecryption/5, where GetParam() = (6, 0xd00c98 pointing to "encrypt_columns_and_footer_ctr.parquet.encrypted") (7 ms)
[----------] 6 tests from DecryptionTests/TestDecryptionConfiguration (71 ms total)
```

I don't have a Windows machine, but I have an idea for a fix that I'm trying to pass through CI.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

CI would failed in Decrypt test in Windows MinGW. This is because in some MinGW version, it may generate
truncated stream test data in `GenerateSampleData<FloatType>`, as a fixing, here using `EXPECT_FLOAT_EQ`
to handle that problem

### What changes are included in this PR?

Change comparing float with `_EQ` to `FLOAT_EQ` and `DOUBLE_EQ` in unittest.

### Are these changes tested?

No

### Are there any user-facing changes?

No

* Closes: #35571

### CODE REVIEW

**Comment by mapleFU** [comment]
```
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 19.8
  read_col_data.values[i]
    Which is: 19.8
values at index 18 not equal read is 19.800001, expect 19.799999
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 25.3
  read_col_data.values[i]
    Which is: 25.3
values at index 23 not equal read is 25.300001, expect 25.299999
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 26.4
  read_col_data.values[i]
    Which is: 26.4
values at index 24 not equal read is 26.400002, expect 26.400000
D:/a/arrow/arrow/cpp/src/parquet/encryption/test_encryption_util.cc:343: Failure
Expected equality of these values:
  expected_column_data.values[i]
    Which is: 30.8
  read_col_data.values[i]
    Which is: 30.8
values at index 28 not equal read is 30.800001, expect 30.799999
```

I guess the problem comes from floating point equality. @felipecrv

**Comment by mapleFU** [comment]
Another problem occured when casting decimal to string:

```
[----------] 2 tests from TestDecimalFromReal/1, where TypeParam = std::pair<arrow::Decimal128, double>
[ RUN      ] TestDecimalFromReal/1.TestSuccess
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "4611686000000000000"
  expected
    Which is: "4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-4611686000000000000"
  expected
    Which is: "-4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "9223372000000000000"
  expected
    Which is: "9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-9223372000000000000"
  expected
    Which is: "-9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "18446744000000000000"
  expected
    Which is: "18446744073709551616"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-18446744000000000000"
  expected
    Which is: "-18446744073709551616"
[  FAILED  ] TestDecimalFromReal/1.TestSuccess, where TypeParam = std::pair<arrow::Decimal128, double> (0 ms)
[ RUN      ] TestDecimalFromReal/1.TestErrors
[       OK ] TestDecimalFromReal/1.TestErrors (0 ms)
[----------] 2 tests from TestDecimalFromReal/1 (0 ms total)

[----------] 2 tests from TestDecimalFromReal/2, where TypeParam = std::pair<arrow::Decimal256, float>
[ RUN      ] TestDecimalFromReal/2.TestSuccess
[       OK ] TestDecimalFromReal/2.TestSuccess (0 ms)
[ RUN      ] TestDecimalFromReal/2.TestErrors
[       OK ] TestDecimalFromReal/2.TestErrors (0 ms)
[----------] 2 tests from TestDecimalFromReal/2 (0 ms total)

[----------] 2 tests from TestDecimalFromReal/3, where TypeParam = std::pair<arrow::Decimal256, double>
[ RUN      ] TestDecimalFromReal/3.TestSuccess
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "4611686000000000000"
  expected
    Which is: "4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-4611686000000000000"
  expected
    Which is: "-4611686018427387904"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "9223372000000000000"
  expected
    Which is: "9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-9223372000000000000"
  expected
    Which is: "-9223372036854775808"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "18446744000000000000"
  expected
    Which is: "18446744073709551616"
D:/a/arrow/arrow/cpp/src/arrow/util/decimal_test.cc:766: Failure
Expected equality of these values:
  dec.ToString(scale)
    Which is: "-18446744000000000000"
  expected
    Which is: "-18446744073709551616"
[  FAILED  ] TestDecimalFromReal/3.TestSuccess, where TypeParam = std::pair<arrow::Decimal256, double> (0 ms)
[ RUN      ] TestDecimalFromReal/3.TestErrors
```


I gothrough the related code.

**Comment by mapleFU** [comment]
@pitrou @wjones127 Would you mind take a look at this fixing?

**Comment by pitrou** [comment]
```
values at index 28 not equal read is 30.800001, expect 30.799999
```

This is not right. Reading Parquet values should be bit-precise, not approximate.

**Comment by mapleFU** [comment]
I guess the error and https://github.com/apache/arrow/issues/35606 have same underlying reason. Maybe there is some prevision loss in MinGW

**Comment by pitrou** [comment]
There shouldn't be any precision loss simply when copying values. Perhaps the tests are doing something wrong.

**Comment by mapleFU** [comment]
Got it, I'm at office and didn't have a Windows machine, I'll try to reproduce it later after I'm home

**Comment by felipecrv** [comment]
> There shouldn't be any precision loss simply when copying values. Perhaps the tests are doing something wrong.

Could this be tracked in a separate issue and the CI fix merged sooner rather than later?

**Comment by pitrou** [comment]
Rather than complicating the test routine, I'd rather generate data that doesn't trigger truncation issues (wherever they might happen):
```diff
diff --git a/cpp/src/parquet/encryption/test_encryption_util.cc b/cpp/src/parquet/encryption/test_encryption_util.cc
index 012712c7b..8193e6525 100644
--- a/cpp/src/parquet/encryption/test_encryption_util.cc
+++ b/cpp/src/parquet/encryption/test_encryption_util.cc
@@ -143,7 +143,7 @@ template <>
 ColumnData<FloatType> GenerateSampleData<FloatType>(int rows) {
   ColumnData<FloatType> float_col;
   for (int i = 0; i < rows; i++) {
-    float value = static_cast<float>(i) * 1.1f;
+    float value = static_cast<float>(i) * 1.5f;
     float_col.values.push_back(value);
   }
   return float_col;
```

**Comment by mapleFU** [comment]
I guess MinGW with unstable CI may generate or truncate data when getting `GenerateSampleData`, so I guess previous fixing in https://github.com/apache/arrow/pull/35605/commits/6265cc17f8b35501f793d3f3c25a972e2ecd2841 is ok
@pitrou What would you think of this?

**Comment by pitrou** [comment]
> https://github.com/apache/parquet-testing/tree/master/data The data is already here, I guess maybe it cannot help?

Ahaha! Well, that explains why there might be a discrepancy then...

File: cpp/src/parquet/encryption/test_encryption_util.cc [hunk 1]
```diff
@@ -322,9 +322,24 @@ void ReadAndVerifyColumn(RowGroupReader* rg_reader, RowGroupMetadata* rg_md,
...
+      }
+      if constexpr (std::is_same_v<float, typename DType::c_type>) {
+        EXPECT_FLOAT_EQ(expected_column_data.values[i], read_col_data.values[i]);
+      } else {
+        EXPECT_DOUBLE_EQ(expected_column_data.values[i], read_col_data.values[i]);
+      }
+    }
+  } else {
+    // make sure we got the same number of values the metadata says
+    ASSERT_EQ(col_md->num_values(), rows_read);
```
Comment (pitrou) [inline cpp/src/parquet/encryption/test_encryption_util.cc:341]: This should be done always, not only for non-floating-point values.
Also, you still need to compare values for non-floating-point.

File: cpp/src/parquet/encryption/test_encryption_util.cc [hunk 2]
```diff
@@ -322,9 +322,24 @@ void ReadAndVerifyColumn(RowGroupReader* rg_reader, RowGroupMetadata* rg_md,
   }
   ASSERT_EQ(rows_read, rows_should_read);
   ASSERT_EQ(values_read, rows_should_read);
-  ASSERT_EQ(read_col_data.values, expected_column_data.values);
-  // make sure we got the same number of values the metadata says
-  ASSERT_EQ(col_md->num_values(), rows_read);
+  if constexpr (std::is_floating_point_v<typename DType::c_type>) {
+    ASSERT_EQ(read_col_data.rows(), expected_column_data.rows());
+    for (int i = 0; i < read_col_data.rows(); ++i) {
+      if (std::isnan(expected_column_data.values[i])) {
```
Comment (pitrou) [inline cpp/src/parquet/encryption/test_encryption_util.cc:328]: There doesn't seem to be any NaN in the generated data, this can be removed.

**Review by pitrou — CHANGES_REQUESTED** [review]

**Comment by mapleFU** [comment]
Comment fixed. The case here ( https://github.com/apache/arrow/pull/35605#issuecomment-1549078718 ) need to be fixed later, so "C++ / AMD64 Windows MinGW MINGW64 C++" still failed

**Comment by mapleFU** [comment]
Comment fixed. The case here ( https://github.com/apache/arrow/pull/35605#issuecomment-1549078718 ) need to be fixed later, so "C++ / AMD64 Windows MinGW MINGW64 C++" still failed
