### PR TITLE
GH-34326: [C++][Parquet] Page null_count is incorrect if stats is disabled

### LINKED ISSUE #34326: [C++][Parquet] Page null_count is incorrect if stats is disabled
### Describe the bug, including details regarding any error messages, version, and platform.

Parquet ColumnWriter obtains null_count of a page from page stats as below ([link](https://github.com/apache/arrow/blob/main/cpp/src/parquet/column_writer.cc#L952))
```cpp
  EncodedStatistics page_stats = GetPageStatistics();

  int32_t null_count = static_cast<int32_t>(page_stats.null_count);

  DataPageV2 page(combined, num_values, null_count, num_rows, encoding_,
                    def_levels_byte_length, rep_levels_byte_length, uncompressed_size,
                    pager_->has_compressor(), page_stats);
```

However, the null_count is uninitialized if page stat is not enabled:
```cpp
  EncodedStatistics GetPageStatistics() override {
    EncodedStatistics result;
    if (page_statistics_) result = page_statistics_->Encode();
    return result;
  }
```

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

Parquet ColumnWriter obtains null_count of a page from page stats as below ([link](https://github.com/apache/arrow/blob/main/cpp/src/parquet/column_writer.cc#L952))
```cpp
  EncodedStatistics page_stats = GetPageStatistics();

  int32_t null_count = static_cast<int32_t>(page_stats.null_count);

  DataPageV2 page(combined, num_values, null_count, num_rows, encoding_,
                    def_levels_byte_length, rep_levels_byte_length, uncompressed_size,
                    pager_->has_compressor(), page_stats);
```

However, the null_count is uninitialized if page stat is not enabled:
```cpp
  EncodedStatistics GetPageStatistics() override {
    EncodedStatistics result;
    if (page_statistics_) result = page_statistics_->Encode();
    return result;
  }
```

### What changes are included in this PR?

ColumnWriter collects null_count by itself. To be safe, it also checks that from page stats if available.

### Are these changes tested?

Added a test case to cover null counts of optional and repeated fields are properly set.

### Are there any user-facing changes?

No.
* Closes: #34326

### CODE REVIEW

**Comment by wgtmac** [comment]
@emkornfield @wjones127 @westonpace Could you please take a look?

File: cpp/src/parquet/column_writer.cc [hunk 1]
```diff
@@ -1362,7 +1375,7 @@ class TypedColumnWriterImpl : public ColumnWriterImpl, public TypedColumnWriter<
           *out_spaced_values_to_write +=
               def_levels[x] >= level_info_.repeated_ancestor_def_level ? 1 : 0;
         }
-        *null_count = *out_values_to_write - *out_spaced_values_to_write;
+        *null_count = batch_size - *out_values_to_write;
```
Comment (westonpace) [inline cpp/src/parquet/column_writer.cc:1378]: Why did this calculation need to change?

File: cpp/src/parquet/column_writer.cc [hunk 2]
```diff
@@ -949,11 +954,17 @@ void ColumnWriterImpl::BuildDataPageV2(int64_t definition_levels_rle_size,
...
   int32_t num_values = static_cast<int32_t>(num_buffered_values_);
-  int32_t null_count = static_cast<int32_t>(page_stats.null_count);
+  int32_t null_count = static_cast<int32_t>(num_buffered_nulls_);
   int32_t num_rows = static_cast<int32_t>(num_buffered_rows_);
   int32_t def_levels_byte_length = static_cast<int32_t>(definition_levels_rle_size);
   int32_t rep_levels_byte_length = static_cast<int32_t>(repetition_levels_rle_size);
 
+  // page_stats.null_count is not set when page_statistics_ is nullptr. It is only used
+  // here for safety check.
+  if (page_stats.has_null_count && page_stats.null_count != num_buffered_nulls_) {
```
Comment (westonpace) [inline cpp/src/parquet/column_writer.cc:964]: Should this maybe be a `DCHECK` since users shouldn't be able to influence these values and wouldn't understand the exception?

**Review by westonpace — COMMENTED** [review]
A few minor questions

File: cpp/src/parquet/column_writer.cc (hunk 1 above)
Comment (wgtmac) [reply cpp/src/parquet/column_writer.cc:1378]: If this line does not change, the test cases `StatsTests::ParameterizedStatisticsTest` in the `arrow_statistics_test.cc` simply fail due to incorrect null_count. Here is why:
- `out_values_to_write`: number of non-null values only
- `out_spaced_values_to_write`: number of non-null values and null values
- `batch_size`: number of all values including non-null values, null values, and empty list (which is null from ancestor)

File: cpp/src/parquet/column_writer.cc (hunk 2 above)
Comment (wgtmac) [reply cpp/src/parquet/column_writer.cc:964]: I agree. Will switch to `DCHECK` accordingly.

**Comment by wgtmac** [comment]
@wjones127 @emkornfield @pitrou Could you take a look please?

**Review by wjones127 — APPROVED** [review]
This looks good. I appreciate the thorough testing :)

**Comment by wgtmac** [comment]
> This looks good. I appreciate the thorough testing :)

Thanks for your review! @wjones127 @westonpace
