### PR TITLE
GH-39297: [C++][FS]: Inform caller of container not-existing when checking for HNS support

### LINKED ISSUE #39297: [C++] Inform caller of Azure Storage container not-existing when checking for HNS support
### Describe the enhancement requested

An operation checking for Hierarchical Namespace support shouldn't fail completely when the reason for the check failing is the container not existing. We can allow the caller to decide what to do in that situation by returning a result that indicates the check didn't succeed because the container doesn't exist.

**Related Issues:**
- https://github.com/apache/arrow/issues/18014 (is a child of)

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

An operation checking for Hierarchical Namespace support shouldn't fail completely when the reason for the check failing is the container not existing. We can allow the caller to decide what to do in that situation by returning a result that indicates the check didn't succeed because the container doesn't exist.

### What changes are included in this PR?

 - Removal of the `azurefs_intern.h/cc` files
 - Implementation of the check as a free-function instead of a class
 - Memoization of the result in the `AzureFileSystem` class

### Are these changes tested?

Yes. The tests were improved to cover all cases.
* Closes: #39297

### CODE REVIEW

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 1]
```diff
@@ -879,11 +968,14 @@ class AzureFileSystem::Impl {
...
-          // If the hierarchical namespace is enabled, then the storage account will have
-          // explicit directories. Neither a file nor a directory was found.
+        auto adlfs_client =
+            datalake_service_client_->GetFileSystemClient(location.container);
+        ARROW_ASSIGN_OR_RAISE(auto hns_support,
+                              HierarchicalNamespaceSupport(adlfs_client));
+        if (hns_support == HNSSupport::kContainerNotFound ||
+            hns_support == HNSSupport::kEnabled) {
+          // If the hierarchical namespace is enabled, then the storage account will
+          // have explicit directories. Neither a file nor a directory was found.
```
Comment (felipecrv) [inline cpp/src/arrow/filesystem/azurefs.cc:978]: These refactorings preserve the existing semantics as the goal of this PR is just rewriting the HNS check, but I'm changing the semantics of directory operations in a follow-up PR.

**Comment by felipecrv** [comment]
@kou @Tom-Newton

**Comment by Tom-Newton** [comment]
Is there a specific reason to combine everything back into a single file? Personally, I thought we should probably split more stuff into `azurefs_internal.cc` given the size of `azurefs.cc`.

**Review by Tom-Newton — COMMENTED** [review]
There were a some things I liked about the old implementation but as a C++ noob my opinion probably doesn't have much weight here.

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 2]
```diff
@@ -786,8 +789,71 @@ class ObjectAppendStream final : public io::OutputStream {
...
+          return HNSSupport::kDisabled;
+        }
+        return ExceptionToStatus("Check for hierarchical namespace support on '" +
+                                     adlfs_client.GetUrl() +
+                                     "' failed with an unexpected error.",
+                                 exception);
+    }
+  }
+  DCHECK(false) << "Unreachable";
+  return HNSSupport::kUnknown;
```
Comment (kou) [inline cpp/src/arrow/filesystem/azurefs.cc:852]: Do we need this?
It seems that all cases have `return`. Does compiler complain without this?

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 3]
```diff
@@ -1177,18 +1269,19 @@ class AzureFileSystem::Impl {
...
 
-    ARROW_ASSIGN_OR_RAISE(auto hierarchical_namespace_enabled,
-                          hns_detector_.Enabled(location.container));
-    if (!hierarchical_namespace_enabled) {
+    auto adlfs_client = datalake_service_client_->GetFileSystemClient(location.container);
+    ARROW_ASSIGN_OR_RAISE(auto hns_support, HierarchicalNamespaceSupport(adlfs_client));
+    if (hns_support == HNSSupport::kContainerNotFound) {
+      return PathNotFound(location);
+    }
+    if (hns_support == HNSSupport::kDisabled && !IsDfsEmulator(options_)) {
```
Comment (kou) [inline cpp/src/arrow/filesystem/azurefs.cc:1277]: Do we need `&& !IsDfsEmulator(options_)` here?

File: cpp/src/arrow/filesystem/azurefs.cc [hunk 4]
```diff
@@ -798,7 +864,7 @@ class AzureFileSystem::Impl {
 
   std::unique_ptr<DataLake::DataLakeServiceClient> datalake_service_client_;
   std::unique_ptr<Blobs::BlobServiceClient> blob_service_client_;
-  internal::HierarchicalNamespaceDetector hns_detector_;
+  HNSSupport cached_hns_support_ = HNSSupport::kUnknown;
```
[the remark this answers is not in the document]
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:867]: This split separates the stateful part of HNS checking from the request and error handling logic. To counter the possibility of inadvertent misuse of the value, I renamed it to `cached_...`. There are valid uses for this value directly and the name describes that it's a cached value that could contain much more than the two states of a boolean.

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 3 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:1277]: We do need it.

In the Azure environment we will get `HNSSupport::kContainerNotFound` when a container is not found even if the storage account doesn't support HNS.

On Azurite we get `HNSSupport` even when the container doesn't exist, so returning `Status::OK()` is this situation would be a bogus success report. There is a test expecting this function to fail on accounts with and without HNS support *iff* the container doesn't exist.

Running the tests with `&& !IsDFSEmulator(options_)`:

```
[ RUN      ] TestAzuriteFileSystem.CreateDirFailureDirectoryWithMissingContainer
/Users/felipe/code/arrow/cpp/src/arrow/filesystem/azurefs_test.cc:1062: Failure
Failed
Expected 'fs_->CreateDir(path, false)' to fail with IOError, but got OK
```

This extra condition is going to be removed in the fix for https://github.com/apache/arrow/issues/38772 where I'm fixing the semantics of directory operations.

**Comment by felipecrv** [comment]
> Is there a specific reason to combine everything back into a single file? Personally, I thought we should probably move more stuff into `azurefs_internal.cc` given the size of `azurefs.cc`.

@Tom-Newton This split caused 2 `ExceptionToStatus` functions to exist and would force me to expose `IsDfsEmulator` and `IsContainerNotFound` in the `azurefs_internal.h` header since I need them to implement the HNS check and other filesystem operations that now live in `azurefs.cc`. I'm not opposed to partitioning `azurefs.cc` into smaller files, but that split should be one that minimizes the shared interfaces between the partitions -- a more natural split will be more obvious when we finish the implementation.

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs.cc:865]: > There are valid uses for this value directly

Can you give some examples? I can't think of any

**Comment by Tom-Newton** [comment]
> @Tom-Newton This split caused 2 `ExceptionToStatus` functions to exist and would force me to expose `IsDfsEmulator` and `IsContainerNotFound` in the `azurefs_internal.h` header since I need them to implement the HNS check and other filesystem operations that now live in `azurefs.cc`. I'm not opposed to partitioning `azurefs.cc` into smaller files, but that split should be one that minimizes the shared interfaces between the partitions that have to be announced in a header -- a more natural split will be more evident when we finish the implementation.

I think personally I would have moved `IsDfsEmulator` and `IsContainerNotFound` in the `azurefs_internal.h` but I don't feel strongly.

File: cpp/src/arrow/filesystem/azurefs.h [hunk 5]
```diff
@@ -117,6 +118,54 @@ struct ARROW_EXPORT AzureOptions {
   MakeDataLakeServiceClient() const;
 };
 
+namespace internal {
+
+enum class HNSSupport {
```
Comment (Tom-Newton) [inline cpp/src/arrow/filesystem/azurefs.h:123]: Again I don't feel strongly, but I would not have abbreviated so much. Yes, the docstring explains in detail but someone who just sees that name and Googles it will find themselves learning about the [Croatian Football Federation](https://en.wikipedia.org/wiki/Croatian_Football_Federation) :smile:

Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.h:123]: I abbreviated the enum class because it gets repeated a lot, but kept the function names with the full name :-)

HNS is used in Microsoft documentation together with SMB, FTP... so it's not so bad.

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-feature-support-in-storage-accounts

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:865]: An operation could decide to use the `DataLakeFileSystemClient` if `cached_hns_support` in `kUnknown/kContainerNotFound/kEnabled` and set the value of `cached_hns_support_` based on the error/success handling of that operation. This would save the mandatory extra request in the uncached case.

Another scenario is if we were to add threads to the mix, we would like to avoid having multiple HNS check requests going in parallel by having `cached_hns_support_` be some kind of atomic variable or protected by a mutex that also protects other member variables in the `AzureFileSystem::Impl` class.

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 3 above)
Comment (kou) [reply cpp/src/arrow/filesystem/azurefs.cc:1275]: Thanks. I see.

**Comment by felipecrv** [comment]
@kou can you look again? I had forgotten to push the unit test fixing commit before. Note that I added some error message cleanups as well.

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 3 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc]: I pushed a commit that removes this from the code. It properly fixes all possible cases.

**Review by kou — APPROVED** [review]
+1

I think that we can merge this after @felipecrv and @Tom-Newton reach a consensus (and apply necessary changes if needed).
I don't have strong opinion for on going discussion.

**Comment by Tom-Newton** [comment]
I would have done some of this slightly differently but I don't feel strongly. @felipecrv feel free to merge

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (Tom-Newton) [reply cpp/src/arrow/filesystem/azurefs.cc:902]: To be honest I'm not really convinced by either of these, but it probably doesn't matter. 

Technically you could avoid the call to check for hierarchical NS but I don't think it really makes sense because of the very small performance cost and the high added complexity cost. `DataLakeFileSystemClient` largely works on flat NS accounts so it would require extra error handling on every call and as we know from the hierarchical namespace detection code Azure often gives strange responses and its difficult to determine if the failure is genuine or if the error is just because hierarchical namespace is detected. 

I don't really see why we would need to protects other member variables of `AzureFileSystem::Impl` behind the same mutex. I would have kept the separate detector class which could have just one mutex. When `AzureFileSystem::Impl` needs to check whether hierarchical NS is enabled in parallel it would hit the mutex but otherwise I would want `AzureFileSystem::Impl` to be free to make other calls to blob storage without any mutexs getting in the way. Additionally, I was under the impression that `AzureFileSystem` would never be used in multiple threads. I think only `RandomAccessFile::ReadAt` is used concurrently.

[the remark this answers is not in the document]
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:902]: I will consider extracting the memoized `HierarchicalNamespaceSupport()` check to a separate class (added to my TODO list together with splitting the `azurefs.cc` file), but I maintain that having an underlying function that doesn't do any mutable state manipulation (just the request to the backend) makes it easier to reason about the correctness and cost of the calls.

> AzureFileSystem would never be used in multiple threads. I think only RandomAccessFile::ReadAt is used concurrently.

I meant `AzureFileSystem` itself would be using multiple threads to run the operations.

File: cpp/src/arrow/filesystem/azurefs.h [hunk 6]
```diff
@@ -117,6 +118,54 @@ struct ARROW_EXPORT AzureOptions {
...
+/// https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob-service-properties?tabs=azure-ad#authorization
+///
+/// IMPORTANT: If the result is kEnabled or kDisabled, it doesn't necessarily mean that
+/// the container exists.
+///
+/// \param adlfs_client A DataLakeFileSystemClient for a container of the storage
+/// account.
+/// \return kEnabled/kDisabled/kContainerNotFound (kUnknown is never
+/// returned).
+Result<HNSSupport> CheckIfHierarchicalNamespaceIsEnabled(
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/azurefs.h:163]: I don't understand why this is exposed in `azurefs.h`? Normally the user wouldn't interact with Azure SDK types directly, only through the `FileSystem` abstraction.

File: cpp/src/arrow/filesystem/azurefs.h (hunk 5 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/azurefs.h:123]: I would rather have the full name as well, even if unfortunately long.

File: cpp/src/arrow/filesystem/azurefs.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.cc:902]: > ...its difficult to determine if the failure is genuine or if the error is just because hierarchical namespace is detected.

I noticed this and I'm working on changes that puts us in a position where we never have to make that distinction. Because we can never cover all possible cases and Azurite being very broken when we make Data Lake Storage API calls to it makes it even worse.

File: cpp/src/arrow/filesystem/azurefs.h (hunk 6 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.h:163]: Because this is called from tests. But note that it's in the `internal` namespace.

I removed `azurefs_internal.h` and moved everything to `azurefs.cc` to minimize the export of utilities that mention Azure SDK types and this was the only one left in the `internal` namespace because it's called directly from unit tests (cc @Tom-Newton).

Comment (pitrou) [reply cpp/src/arrow/filesystem/azurefs.h:163]: Hmm, I would have rather kept the `azurefs_internal.{h,cc}` as that's a useful separation, and it makes reading the headers easier.

File: cpp/src/arrow/filesystem/azurefs.h (hunk 5 above)
Comment (felipecrv) [reply cpp/src/arrow/filesystem/azurefs.h:123]: Can I at least alias it in `azurefs.cc`?

**Comment by felipecrv** [comment]
@pitrou @Tom-Newton follow-up PR addressing your feedback and simplifying error messages https://github.com/apache/arrow/pull/39323
