### PR TITLE
GH-15203: [Java] Implement writing compressed files

### LINKED ISSUE #15203: [Java] ArrowFileWriter/ArrowStreamWriter lack compression support
### Describe the enhancement requested

Their reader counterparts support compression, but the writers don't give you any way to enable it. Furthermore, the design of the compression API means that enabling this will require modifying several classes: the compression API closes the input buffer after compression, but this runs contrary to the expectation of VectorUnloader, which isn't supposed to mutate the source VectorSchemaRoot. (Arguably, this is a flaw in the VectorUnloader API that prevents efficient memory usage, but fixing _that_ would mean invalidating essentially all current Arrow Java code.)

Also there are various other flaws (e.g. VectorUnloader says it is OK to pass a null compression codec but will crash if you do so because it assumes the codec is never null.)

See also: #15102

It is possible to manually generate compressed data yourself in Java, but this requires taping together several low-level APIs yourself.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by lidavidm**
* Closes: #15203

### CODE REVIEW

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/message/ArrowRecordBatch.java [hunk 1]
```diff
@@ -89,7 +107,9 @@ public ArrowRecordBatch(
     List<ArrowBuffer> arrowBuffers = new ArrayList<>(buffers.size());
     long offset = 0;
     for (ArrowBuf arrowBuf : buffers) {
-      arrowBuf.getReferenceManager().retain();
+      if (retainBuffers) {
```
Comment (davisusanibar) [inline java/vector/src/main/java/org/apache/arrow/vector/ipc/message/ArrowRecordBatch.java:110]: Could you try to explain why working with compression options impact or is needed to add this flag  "retainBuffers"? 

What will be the error if this flag retainBuffers is not added?

Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/ipc/message/ArrowRecordBatch.java:110]: https://github.com/apache/arrow/blob/8199fa79a4440ca3976c5712ccf3bc3eaff0eae2/java/vector/src/main/java/org/apache/arrow/vector/VectorUnloader.java#L102-L105

**Comment by lidavidm** [comment]
@lwhite1 would you also like to take a look?

**Review by davisusanibar — APPROVED** [review]
