### PR TITLE
GH-38738: [C++] Check variadic buffer counts in bounds

### LINKED ISSUE #38738: [C++] Check for valid variadic buffer counts
### Describe the bug, including details regarding any error messages, version, and platform.

Variadic buffer count is stored as int64 and is used to presize vectors when reading IPC. These aren't validated for representability in a positive int32, which led to some fuzzer failures.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by bkietz**
### Rationale for this change

Invalid variadic buffer counts can cause allocating storage for variadic buffers to fail.

### What changes are included in this PR?

Check variadic buffer counts are valid before they are used as an allocator argument.

### Are these changes tested?

They pass with the fuzzer testcase.

### Are there any user-facing changes?

No

* Closes: #38738

### CODE REVIEW

**Comment by bkietz** [comment]
Should the fuzzer testcases be added to testing/data/arrow-ipc-stream/ ?

File: cpp/src/arrow/ipc/reader.cc [hunk 1]
```diff
@@ -254,7 +254,12 @@ class ArrayLoader {
     if (i >= static_cast<int>(variadic_counts->size())) {
       return Status::IOError("variadic_count_index out of range.");
     }
-    return static_cast<size_t>(variadic_counts->Get(i));
+    int64_t count = variadic_counts->Get(i);
+    if (count < 0 || count > std::numeric_limits<int32_t>::max()) {
+      return Status::IOError(
+          "variadic_count must be represenable as a positive int32_t, got ", count, ".");
```
Comment (pitrou) [inline cpp/src/arrow/ipc/reader.cc:260]:
```suggestion
          "variadic_count must be representable as a positive int32_t, got ", count, ".");
```

**Review by pitrou — APPROVED** [review]

**Comment by bkietz** [comment]
fuzz regression file added in https://github.com/apache/arrow-testing/pull/98
