### PR TITLE
GH-38395: [Go] fix rounding errors in decimal256 string functions

### LINKED ISSUE #38395: [Go] rounding errors in decimal256 string functions
There are rounding errors when constructing decimal256 values from string and when serializing them to string.

Affected version: main branch, v13 (maybe even older versions).

Similar issues were already reported in the past (https://github.com/apache/arrow/issues/35310).

```
func TestFromString(t *testing.T) {
	const decStr = "11111111111111111111111111111111111111.00000000000000000000000000000000000000"

	num, err := decimal256.FromString(decStr, 76, 38)
	if err != nil {
		t.Error(err)
	} else if decStr != num.ToString(38) {
		t.Errorf("expected: %s, actual: %s\n", decStr, num.ToString(38))

		actualCoeff := num.BigInt()
		expectedCoeff, _ := (&big.Int{}).SetString(strings.Replace(decStr, ".", "", -1), 10)
		t.Errorf("expected(hex): %X, actual(hex): %X\n", expectedCoeff.Bytes(), actualCoeff.Bytes())
	}
}
```
fails with
```
expected: 11111111111111111111111111111111111111.00000000000000000000000000000000000000
actual:   11111111111111110860978869272892669951.88888888888888889139021130727107330048

expected(hex): 0274DDD9AC9F3B4D00D24CF6A80B3D7F3DCD982490C8B30EE27EDFC000000000
actual(hex):   0274DDD9AC9F3B4904B40E1450CD9B8435D513ED4B465C000000000000000000
```

The hex numbers show that the error is in the FromString function.

However, there are also rounding issues in the ToString function:

```
func TestToString(t *testing.T) {
	const decStr = "3379334159166193114608287418738414931564221155305735605033949613740461239999"

	integer, _ := (&big.Int{}).SetString(decStr, 10)
	dec := decimal256.FromBigInt(integer)

	expected := "0." + decStr
	actual := dec.ToString(76)

	if expected != actual {
		t.Errorf("expected: %s, actual: %s\n", expected, actual)
	}
}
```
fails with
```
expected: 0.3379334159166193114608287418738414931564221155305735605033949613740461239999
actual:   0.3379334159166193114608287418738414931564221155305735605033949613740461240000
```

In case of ToString it seem to be off-by-one errors only.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
Slight modifications to the `ToString` and `FromString` methods of decimal 256 to ensure proper accurate and proper conversion given precision and scale.

### Are these changes tested?
Yes

* Closes: #38395

### CODE REVIEW

File: go/arrow/decimal256/decimal256.go [hunk 1]
```diff
@@ -506,7 +506,7 @@ func (n Num) FitsInPrecision(prec int32) bool {
 
 func (n Num) ToString(scale int32) string {
 	f := (&big.Float{}).SetInt(n.BigInt())
-	f.Quo(f, (&big.Float{}).SetInt(scaleMultipliers[scale].BigInt()))
+	f.SetPrec(256).Quo(f, (&big.Float{}).SetInt(scaleMultipliers[scale].BigInt()))
```
Comment (felipecrv) [inline go/arrow/decimal256/decimal256.go:509]: Is 256 precision always required? Is there a way to know what precision is needed? Or why it doesn't matter?

**Review by felipecrv — APPROVED** [review]

File: go/arrow/decimal128/decimal128.go [hunk 2]
```diff
@@ -266,23 +266,36 @@ func FromString(v string, prec, scale int32) (n Num, err error) {
...
+		// the value instead because of edge cases so that we match how other implementations
+		// (e.g. C++) handles Decimal values. So if we're negative we'll subtract 0.5 and if
+		// we're positive we'll add 0.5.
+		p := (&big.Float{}).SetFloat64(float64PowersOfTen[scale+38])
+		out.Mul(out, p).SetPrec(precInBits)
+		if out.Signbit() {
+			out.Sub(out, pt5)
+		} else {
+			out.Add(out, pt5)
+		}
```
Comment (felipecrv) [inline go/arrow/decimal128/decimal128.go:288]: This is done because the round is a "round up", right?

Comment (zeroshade) [reply go/arrow/decimal128/decimal128.go:288]: more accurately it's a round away from zero

File: go/arrow/decimal128/decimal128.go [hunk 3]
```diff
@@ -266,23 +266,36 @@ func FromString(v string, prec, scale int32) (n Num, err error) {
...
 
-	var tmp big.Int
-	val, _ := out.Int(&tmp)
-	if val.BitLen() > 127 {
-		return Num{}, errors.New("bitlen too large for decimal128")
+		// Since we're going to truncate this to get an integer, we need to round
+		// the value instead because of edge cases so that we match how other implementations
+		// (e.g. C++) handles Decimal values. So if we're negative we'll subtract 0.5 and if
+		// we're positive we'll add 0.5.
+		p := (&big.Float{}).SetFloat64(float64PowersOfTen[scale+38])
```
Comment (felipecrv) [inline go/arrow/decimal128/decimal128.go]: Why not `+76` here?

File: go/arrow/decimal128/decimal128.go [hunk 4]
```diff
@@ -275,12 +275,11 @@ func FromString(v string, prec, scale int32) (n Num, err error) {
 		n = FromBigInt(val)
 		n, _ = n.Div(scaleMultipliers[-scale])
 	} else {
-
 		// Since we're going to truncate this to get an integer, we need to round
 		// the value instead because of edge cases so that we match how other implementations
 		// (e.g. C++) handles Decimal values. So if we're negative we'll subtract 0.5 and if
 		// we're positive we'll add 0.5.
-		p := (&big.Float{}).SetFloat64(float64PowersOfTen[scale+38])
+		p := (&big.Float{}).SetInt(scaleMultipliers[scale].BigInt())
```
Comment (felipecrv) [inline go/arrow/decimal128/decimal128.go:282]: A-ha! I was reviewing commit by commit :)

**Review by felipecrv — APPROVED** [review]

File: go/arrow/decimal128/decimal128.go (hunk 2 above)
Comment (felipecrv) [reply go/arrow/decimal128/decimal128.go:288]: So -7.0 will become -7.0-0.5=-7.5 and round to -8.0?

File: go/arrow/decimal128/decimal128.go (hunk 3 above)
Comment (felipecrv) [reply go/arrow/decimal128/decimal128.go]: Saw the fix on the next commit.

Comment (zeroshade) [reply go/arrow/decimal128/decimal128.go]: dec128 maxes at 38, dec256 maxes at 76. That's why, but as you saw i ended up changing this because of floating point precision issues.

File: go/arrow/decimal128/decimal128.go (hunk 2 above)
Comment (zeroshade) [reply go/arrow/decimal128/decimal128.go:288]: Not quite, check the comment above the spot: we truncate the value to get an integer. So -7.0 with a scale of 0 becomes -7.5 and then we truncate it to -7. -7.5 becomes -8.0 and then we truncate it to -8. 

A better example would be if we're given the value -0.75 with a scale of 1: The scale of 1 means that our final Decimal value is going to be the integer -8 because of rounding.

Comment (felipecrv) [reply go/arrow/decimal128/decimal128.go:288]: Thank you for the explanation!

File: go/arrow/decimal256/decimal256_test.go [hunk 5]
```diff
@@ -575,3 +577,31 @@ func TestFromString(t *testing.T) {
 		})
 	}
 }
+
```
Comment (bkietz) [inline go/arrow/decimal256/decimal256_test.go:580]: Could you add some tests which hit the bitlen overflow?

**Review by bkietz — CHANGES_REQUESTED** [review]
Mostly this looks good to me, just a couple comments on the tests

File: go/arrow/decimal256/decimal256_test.go (hunk 5 above)
Comment (zeroshade) [reply go/arrow/decimal256/decimal256_test.go:580]: added!

**Review by bkietz — APPROVED** [review]
