### PR TITLE
GH-38131: [Swift][CI] Add linting and fix linting errors

### LINKED ISSUE #38131: [Swift] Add linting to CI job
### Describe the enhancement requested

Currently swift doesn't include linting.  The plan is to add swiftlint to docker file and run it as part of CI job as suggested https://github.com/apache/arrow/pull/37764#pullrequestreview-1634127556. 

### Component(s)

Swift

### PR DESCRIPTION
**Pull request by abandy**
Description:

- Added swiftlint to swift CI job: swift_test.sh.
- Fixed swiftlint errors in swift files.
* Closes: #38131

### CODE REVIEW

**Comment by abandy** [comment]
Added swiftlint source and reference artifacts to checkin.  Initially I had attempted to include SwiftLint as a plugin in the Package.swift files but the download took too long during CI build and the plugin didn't seem to fail the arrow swift build using spm.  Also, tried adding git clone of swiftlint in the dockerfile but this took too long during CI build and tried including just the swiftlint source without the artifacts but again this was too slow for CI build (these took over 15 minutes).

**Comment by abandy** [comment]
@kou Please review again when you get a chance.

File: ci/scripts/swift_test.sh [hunk 1]
```diff
@@ -19,13 +19,32 @@
 
 set -ex
 
+cd /arrow/swift/swiftlint && tar -xzvf SwiftLint-0.53.0.tar.gz
+cd /arrow/swift/swiftlint && unzip -o SwiftLintBinary-macos.artifactbundle.zip
+cp /arrow/swift/swiftlint/SwiftLint-Package.swift /arrow/swift/swiftlint/SwiftLint-0.53.0/Package.swift 
+cd /arrow/swift/swiftlint/SwiftLint-0.53.0 && swift build
+cp /arrow/swift/swiftlint/SwiftLint-0.53.0/.build/debug/swiftlint /usr/bin
```
Comment (kou) [inline ci/scripts/swift_test.sh:26]: Can we download them in `ci/docker/ubuntu-swift.dockerfile` instead of putting them to this repository?

File: swift/Arrow/.swiftlint.yml [hunk 2]
```diff
@@ -0,0 +1,11 @@
+included:
```
[the remark this answers is not in the document]
Comment (abandy) [reply swift/Arrow/.swiftlint.yml:1]: Will do

File: ci/docker/ubuntu-swift.dockerfile [hunk 3]
```diff
@@ -20,5 +20,5 @@ FROM swift:5.7.3
 # Install golang
 RUN apt-get update -y -q && \
     apt-get install -y -q --no-install-recommends \
-        golang-go && \
+        unzip golang-go && \
```
[the remark this answers is not in the document]
Comment (abandy) [reply ci/docker/ubuntu-swift.dockerfile:23]: Good idea, will do.

File: swift/Arrow/.swiftlint.yml
[the remark this answers is not in the document]
Comment (abandy) [reply swift/Arrow/.swiftlint.yml:1]: Good idea. I will move .swiftlint.yml to the swiftlint folder and then add a step in the testing script to move the yml file to the directories .

**Comment by abandy** [comment]
@kou I believe I have made all the requested changes.  Please re-review when you get a chance. Thank you!

File: swift/swiftlint/SwiftLint-Package.swift [hunk 4]
```diff
@@ -0,0 +1,120 @@
+// swift-tools-version:5.7
```
Comment (raulcd) [inline swift/swiftlint/SwiftLint-Package.swift:1]: the linter is failing due to missing license header:
```
 apache-rat license violation: swift/swiftlint/SwiftLint-Package.swift
```
https://github.com/apache/arrow/actions/runs/6590875064/job/17908328499?pr=38133#step:5:1052

Comment (abandy) [reply swift/swiftlint/SwiftLint-Package.swift:1]: Good catch, thank you!  Will add.

File: ci/scripts/swift_test.sh (hunk 1 above)
Comment (kou) [reply ci/scripts/swift_test.sh]: @abandy Hmm. Could you try the following? Or can I push it to this branch directly?

```diff
diff --git a/ci/docker/ubuntu-swift.dockerfile b/ci/docker/ubuntu-swift.dockerfile
index 4b9cb7b2b..4789c9188 100644
--- a/ci/docker/ubuntu-swift.dockerfile
+++ b/ci/docker/ubuntu-swift.dockerfile
@@ -17,9 +17,18 @@
 
 FROM swift:5.7.3
 
-# Install golang
+# Go is needed for generating test data
 RUN apt-get update -y -q && \
     apt-get install -y -q --no-install-recommends \
         golang-go \
-        unzip && \
-    apt-get clean
\ No newline at end of file
+        unzip \
+        wget && \
+    apt-get clean
+
+ARG swift_lint=0.53.0
+RUN wget https://github.com/realm/SwiftLint/releases/download/${swift_lint}/swiftlint_linux.zip && \
+    unzip swiftlint_linux.zip && \
+    mv swiftlint /usr/local/bin/ && \
+    mkdir -p /usr/local/share/doc/swiftlint/ && \
+    mv LICENSE /usr/local/share/doc/swiftlint/ && \
+    rm -rf swiftlint_linux.zip
diff --git a/ci/scripts/swift_test.sh b/ci/scripts/swift_test.sh
index c2d221132..b6cff9819 100755
--- a/ci/scripts/swift_test.sh
+++ b/ci/scripts/swift_test.sh
@@ -21,11 +21,6 @@ set -ex
 
 cp ${1}/swift/swiftlint/.swiftlint.yml ${1}/swift/Arrow
 cp ${1}/swift/swiftlint/.swiftlint.yml ${1}/swift/ArrowFlight
-cd ${1}/swift/swiftlint && tar -xzvf SwiftLint-0.53.0.tar.gz
-cd ${1}/swift/swiftlint && unzip -o SwiftLintBinary-macos.artifactbundle.zip
-cp ${1}/swift/swiftlint/SwiftLint-Package.swift ${1}/swift/swiftlint/SwiftLint-0.53.0/Package.swift 
-cd ${1}/swift/swiftlint/SwiftLint-0.53.0 && swift build
-cp ${1}/swift/swiftlint/SwiftLint-0.53.0/.build/debug/swiftlint /usr/bin
 
 data_gen_dir=${1}/swift/data-generator/swift-datagen
 export GOPATH=/
```

Comment (abandy) [reply ci/scripts/swift_test.sh]: @kou I can try it later but if you have it ready and have tested please push to this branch

Comment (kou) [reply ci/scripts/swift_test.sh]: @abandy OK! I'll do it.

File: ci/scripts/swift_test.sh [hunk 5]
```diff
@@ -19,13 +19,29 @@
 
 set -ex
 
+cp ${1}/swift/swiftlint/.swiftlint.yml ${1}/swift/Arrow
```
Comment (kou) [inline ci/scripts/swift_test.sh:22]: @abandy How about simplifying this? (Can I push this to this branch?)

```diff
diff --git a/ci/scripts/swift_test.sh b/ci/scripts/swift_test.sh
index b6cff9819..b523e3891 100755
--- a/ci/scripts/swift_test.sh
+++ b/ci/scripts/swift_test.sh
@@ -19,9 +19,6 @@
 
 set -ex
 
-cp ${1}/swift/swiftlint/.swiftlint.yml ${1}/swift/Arrow
-cp ${1}/swift/swiftlint/.swiftlint.yml ${1}/swift/ArrowFlight
-
 data_gen_dir=${1}/swift/data-generator/swift-datagen
 export GOPATH=/
 pushd ${data_gen_dir}
@@ -30,16 +27,9 @@ go run .
 cp *.arrow ../../Arrow
 popd
 
-source_dir=${1}/swift/Arrow
+source_dir=${1}/swift
 pushd ${source_dir}
-swiftlint --strict ${1}/Sources/Arrow/*.swift
-swiftlint --strict ${1}/Tests/ArrowTests/*.swift
-popd
-
-source_dir=${1}/swift/ArrowFlight
-pushd ${source_dir}
-swiftlint --strict ${1}/Sources/ArrowFlight/*.swift
-swiftlint --strict ${1}/Tests/ArrowFlightTests/*.swift
+swiftlint --strict
 popd
 
 source_dir=${1}/swift/Arrow
diff --git a/swift/swiftlint/.swiftlint.yml b/swift/.swiftlint.yml
similarity index 65%
rename from swift/swiftlint/.swiftlint.yml
rename to swift/.swiftlint.yml
index 89e8d7bb9..9ce377285 100644
--- a/swift/swiftlint/.swiftlint.yml
+++ b/swift/.swiftlint.yml
@@ -16,15 +16,18 @@
 # under the License.
 
 included:
-  - Sources
+  - Arrow/Sources
+  - Arrow/Tests
+  - ArrowFlight/Sources
+  - ArrowFlight/Tests
 excluded:
-  - Sources/Arrow/File_generated.swift
-  - Sources/Arrow/Message_generated.swift
-  - Sources/Arrow/Schema_generated.swift
-  - Sources/Arrow/SparseTensor_generated.swift  
-  - Sources/Arrow/Tensor_generated.swift
-  - Sources/ArrowFlight/Flight.grpc.swift
-  - Sources/ArrowFlight/Flight.pb.swift
+  - Arrow/Sources/Arrow/File_generated.swift
+  - Arrow/Sources/Arrow/Message_generated.swift
+  - Arrow/Sources/Arrow/Schema_generated.swift
+  - Arrow/Sources/Arrow/SparseTensor_generated.swift
+  - Arrow/Sources/Arrow/Tensor_generated.swift
+  - ArrowFlight/Sources/ArrowFlight/Flight.grpc.swift
+  - ArrowFlight/Sources/ArrowFlight/Flight.pb.swift
 identifier_name:
   min_length: 2 # only warning
-allow_zero_lintable_files: false
\ No newline at end of file
+allow_zero_lintable_files: false
```

Comment (abandy) [reply ci/scripts/swift_test.sh:22]: @kou please do, that would be great!  Thank you!

Comment (kou) [reply ci/scripts/swift_test.sh]: Done!

**Comment by abandy** [comment]
@kou if everything looks ok, please merge when you get a chance.

**Review by kou — APPROVED** [review]
+1
