### PR TITLE
GH-33824: [C++] Improve error message on discovery failure

### LINKED ISSUE #33824: [Python] Double . in error message
### Describe the bug, including details regarding any error messages, version, and platform.

I am getting an error

```
pyarrow.lib.ArrowInvalid: Error creating dataset. Could not read schema from 'data/flights-200k.arrow': Could not open Parquet input source 'data/flights-200k.arrow': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.. Is this a 'parquet' file?
```

Note the double `..`.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by saltgen**
### Rationale for this change

Grammatical correctness of message on an exception from pyarrow.lib.ArrowInvalid

### What changes are included in this PR?

Removed a redundant period in the exception message

### Are these changes tested?

No, this is a more of a string amendment and should cause any failures or issues.
I can test it out if this deems to be mandatory.

### Are there any user-facing changes?

User will be greeted with a correct(grammatically) exception message in case of an error.
* Closes: #33824

### CODE REVIEW

File: cpp/src/arrow/dataset/discovery.cc [hunk 1]
```diff
@@ -244,7 +244,7 @@ Result<std::vector<std::shared_ptr<Schema>>> FileSystemDatasetFactory::InspectSc
     if (ARROW_PREDICT_FALSE(!result.ok())) {
       return result.status().WithMessage(
           "Error creating dataset. Could not read schema from '", info.path(),
-          "': ", result.status().message(), ". Is this a '", format_->type_name(),
+          "': ", result.status().message(), " Is this a '", format_->type_name(),
```
Comment (westonpace) [inline cpp/src/arrow/dataset/discovery.cc:247]: Minor bike-shedding nit.  Should we surround the inner exception with `()`?

```
pyarrow.lib.ArrowInvalid: Error creating dataset. Could not read schema from 'data/flights-200k.arrow': (Could not open Parquet input source 'data/flights-200k.arrow': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.) Is this a 'parquet' file?
```

Comment (saltgen) [reply cpp/src/arrow/dataset/discovery.cc:247]: I agree, I think `()` would help with emphasizing an inner exception.
Additionally, I see file type repeated, may I modify the last line of the inner exception, like so?

`pyarrow.lib.ArrowInvalid: Error creating dataset. Could not read schema from 'data/flights-200k.arrow': (Could not open Parquet input source 'data/flights-200k.arrow': Parquet magic bytes not found in footer. This file might be corrupted.) Is this a 'parquet' file?`

P.S. I might also need to make respective change in the Go component.

Comment (westonpace) [reply cpp/src/arrow/dataset/discovery.cc:247]: Hmm, the inner exception can occur in other contexts too though.  For example, when reading a single parquet file without datasets.  In that case the idea that it might not be a parquet file could be helpful.  I think the double-sentence might be preferred still.

Comment (kou) [reply cpp/src/arrow/dataset/discovery.cc:247]: How about changing order instead of using `()`?

```diff
diff --git a/cpp/src/arrow/dataset/discovery.cc b/cpp/src/arrow/dataset/discovery.cc
index a38ec00bb9..2aca85e6ad 100644
--- a/cpp/src/arrow/dataset/discovery.cc
+++ b/cpp/src/arrow/dataset/discovery.cc
@@ -244,8 +244,7 @@ Result<std::vector<std::shared_ptr<Schema>>> FileSystemDatasetFactory::InspectSc
     if (ARROW_PREDICT_FALSE(!result.ok())) {
       return result.status().WithMessage(
           "Error creating dataset. Could not read schema from '", info.path(),
-          "': ", result.status().message(), ". Is this a '", format_->type_name(),
-          "' file?");
+          "'. Is this a '", format_->type_name(), "' file?: ", result.status().message());
     }
     schemas.push_back(result.MoveValueUnsafe());
   }
```

Comment (saltgen) [reply cpp/src/arrow/dataset/discovery.cc:247]: @kou From a developer's perspective the inner exception msg showing up in the middle makes sense for me, holistically.

That said, I do not have a deep understanding of the project at the moment :sweat_smile:

@westonpace Thoughts?

Comment (saltgen) [reply cpp/src/arrow/dataset/discovery.cc:247]: @westonpace Ah okay, sounds good :+1:  I'll incorporate both the suggestions and push shortly.

Comment (saltgen) [reply cpp/src/arrow/dataset/discovery.cc]: Change pushed

Comment (saltgen) [reply cpp/src/arrow/dataset/discovery.cc]: Checking tests

**Comment by kou** [comment]
Could you fix a lint error?
You can fix it by `ninja format` or something.
See also: https://arrow.apache.org/docs/dev/developers/cpp/development.html#code-style-linting-and-ci

File: cpp/src/arrow/dataset/discovery.cc (hunk 1 above)
Comment (saltgen) [reply cpp/src/arrow/dataset/discovery.cc]: Please excuse the delay on this from my end, I will update this PR in a day or two, thank you.

**Comment by saltgen** [comment]
Please excuse the delay on this from my end, I will update this PR in a day or two, thank you.

**Review by kou — APPROVED** [review]
+1

I've fixed format error and an expected message.
