### PR TITLE
GH-37751: [C++][Gandiva] Avoid registering exported functions multiple times in gandiva

### LINKED ISSUE #37751: [C++] [Gandiva] Exported functions are registered multiple times in gandiva
### Describe the bug, including details regarding any error messages, version, and platform.

The exported functions defined in gandiva are registered multiple times unnecessarily.

Currently, in gandiva, exported functions are registered to the function registry in `exported_funcs.h` by using a macro `REGISTER_EXPORTED_FUNCS`, which internally defines a static variable to call the registration. Since this header file (`exported_funcs.h`) is included in multiple times in different files (7 different files more specifically), this makes the registration happens 7 times for the same set of functions, which is not necessary. It makes the initialization slower, additionally, it makes the registration to contain duplicated functions (although it still works so far).

### Component(s)

C++ - Gandiva

### PR DESCRIPTION
**Pull request by niyue**
### Rationale for this change
Try to fix https://github.com/apache/arrow/issues/37751

### What changes are included in this PR?

The exported functions defined in gandiva are registered multiple times unnecessarily. This PR tries to address this issue.

### Are these changes tested?

Yes.

### Are there any user-facing changes?
No
* Closes: #37751

### CODE REVIEW

File: cpp/src/gandiva/engine.cc [hunk 1]
```diff
@@ -319,6 +319,10 @@ Status Engine::FinalizeModule() {
 
   // do the compilation
   execution_engine_->finalizeObject();
+  ARROW_RETURN_IF(
+      execution_engine_->hasError(),
+      Status::CodeGenError("Compilation failed: ", execution_engine_->getErrorMessage()));
```
Comment (niyue) [inline cpp/src/gandiva/engine.cc:324]: This change is not directly to this PR, but previously error will not be reported after calling `finalizedObject`, which makes troubleshooting difficult.

File: cpp/src/gandiva/exported_funcs.cc [hunk 2]
```diff
@@ -0,0 +1,10 @@
+#include "exported_funcs.h"
+
+namespace gandiva {
+REGISTER_EXPORTED_FUNCS(ExportedStubFunctions);
+REGISTER_EXPORTED_FUNCS(ExportedContextFunctions);
+REGISTER_EXPORTED_FUNCS(ExportedTimeFunctions);
+REGISTER_EXPORTED_FUNCS(ExportedDecimalFunctions);
+REGISTER_EXPORTED_FUNCS(ExportedStringFunctions);
+REGISTER_EXPORTED_FUNCS(ExportedHashFunctions);
```
Comment (niyue) [inline cpp/src/gandiva/exported_funcs.cc:9]: All the `REGISTER_EXPORTED_FUNCS` are moved into a `exported_funcs.cc` file, which makes the registration API to be called from 7 * 6 times down to 6 times.

File: cpp/src/gandiva/engine.cc (hunk 1 above)
Comment (niyue) [reply cpp/src/gandiva/engine.cc]: It turns out this `hasError` API is only available in some (newer) version of LLVM, I reverted this piece of change

File: cpp/src/gandiva/exported_funcs_registry.h [hunk 3]
```diff
@@ -36,19 +36,11 @@ class ExportedFuncsRegistry {
...
-  static list_type& registered() {
-    static list_type registered_list;
-    return registered_list;
-  }
+  static list_type& registered();
 };
-
-#define REGISTER_EXPORTED_FUNCS(classname) \
-  static bool _registered_##classname =    \
-      ExportedFuncsRegistry::Register(std::make_shared<classname>())
```
Comment (js8544) [inline cpp/src/gandiva/exported_funcs_registry.h:52]: Can this macro be kept? I'm afraid this may be a breaking change for some users, if they have used this macro in their.code.

File: cpp/src/gandiva/engine.cc [hunk 4]
```diff
@@ -88,6 +89,7 @@ std::once_flag llvm_init_once_flag;
 static bool llvm_init = false;
 static llvm::StringRef cpu_name;
 static llvm::SmallVector<std::string, 10> cpu_attrs;
+std::once_flag register_exported_funcs_flag;
```
Comment (js8544) [inline cpp/src/gandiva/engine.cc:92]: If you use the `REGISTER_EXPORTED_FUNCS` macro in `exported_funcs.cc`, can the changes to this file be skipped?

**Review by js8544 — COMMENTED** [review]
Some minor nits. Can you also add a unit test to make sure each function is only registered once?

**Comment by js8544** [comment]
Can you also fix the lint issue in CI?

File: cpp/src/gandiva/exported_funcs_registry.h (hunk 3 above)
Comment (niyue) [reply cpp/src/gandiva/exported_funcs_registry.h:52]: No problem. I added back the macro, but the `static bool _registered_##classname` variable is never used, and when this macro is used inside a function, this triggers a compiler warning `unused variable '_registered_ExportedStubFunctions' [-Werror,-Wunused-variable]` which fails the build, and I have to add an additional `[[maybe_unused]]` (C++17 attribute) to this macro to suppress this warning.

**Comment by niyue** [comment]
> Can you also fix the lint issue in CI?

Sure. I fixed the lint issue in CI in the new commit.

**Comment by niyue** [comment]
> Can you also add a unit test to make sure each function is only registered once?

I tried to do that, but currently the `registered()` method of `ExportedFuncsRegistry` is a private method, and it is not possible to retrieve the list of currently registered functions from the registry externally, so it is not possible to add such a unit test unless we make the `registered()` method public. Do you have any recommendation for this? Thanks.

File: cpp/src/gandiva/engine.cc (hunk 4 above)
Comment (niyue) [reply cpp/src/gandiva/engine.cc:92]: > If you use the REGISTER_EXPORTED_FUNCS macro in exported_funcs.cc
Do you mean using the `REGISTER_EXPORTED_FUNCS` macro in `exported_funcs.cc` without putting them in a function? That is what I did initially, but I found one of the test case in CI `gandiva-projector-test-static` failed with a segfault (for example, this job https://github.com/apache/arrow/actions/runs/6210920546/job/16859620873?pr=37752).

With the initial approach, I could pass all the tests locally (macOS 13, Apple M1 Max) but there is only `gandiva-projector-test` but  no such `gandiva-projector-test-static` test when running locally (I probably have to look into what CI did to understand the difference). 

After looking at the code, I guess it may be caused by the C++ static initialization order issue (https://pabloariasal.github.io/2020/01/02/static-variable-initialization/#the-red-zone---static-initialization-order-fiasco). The `REGISTER_EXPORTED_FUNCS` macro used to register all the functions in `exported_funcs.cc` directly are not guaranteed to happen before their usage (registration and their usage are in different compilation units). That's why I made another change to put all the registration inside a function, and call this function explicitly once to guarantee the registration happens before its usage.

Please let me know if there is any better way to address this issue. Thanks.

File: cpp/src/gandiva/exported_funcs_registry_test.cc [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+#include "gandiva/exported_funcs_registry.h"
+#include <gtest/gtest.h>
+#include "gandiva/exported_funcs.h"
+
+namespace gandiva {
+TEST(ExportedFuncsRegistry, RegistrationOnlyOnce) {
+  gandiva::RegisterExportedFuncs();
+  auto const& registered_list = ExportedFuncsRegistry::registered();
+  EXPECT_EQ(registered_list.size(), 6);
```
Comment (niyue) [inline cpp/src/gandiva/exported_funcs_registry_test.cc:26]: > Can you also add a unit test to make sure each function is only registered once?
@js8544 I figured out I can use `FRIEND_TEST` macro to test a private method, and I added a test case to verify each `ExportedFuncsBase` is only registered once, but currently I have to use a hard coded value `6` here since we have 6 set of functions to be registered (ExportedStubFunctions, ExportedContextFunctions, ExportedTimeFunctions, ExportedDecimalFunctions, ExportedStringFunctions, ExportedHashFunctions), but this test case needs additional maintenance if we add more  `ExportedFuncsBase` in the future. Let me know if there is other approach for addressing this concern. Thanks.

**Comment by niyue** [comment]
@js8544 this PR is ready for review. There is still one check failing, but it seemed irrelevant with my change (may be caused by CI network issue as far as I can tell). Any comment is appreciated. Thanks.

File: cpp/src/gandiva/engine.cc (hunk 4 above)
Comment (js8544) [reply cpp/src/gandiva/engine.cc:92]: I see. Then having an explicit init process is necessary.

File: cpp/src/gandiva/exported_funcs_registry_test.cc (hunk 5 above)
Comment (js8544) [reply cpp/src/gandiva/exported_funcs_registry_test.cc:26]: Can we make the registered function public, to make it simpler? And so that code doesn't need to know about tests.

I think hard coding the number of functions is fine.

Comment (niyue) [reply cpp/src/gandiva/exported_funcs_registry_test.cc:26]: I've made the `registered` API public, and remove the `FRIEND_TEST` from the `ExportedFuncsRegistry`

File: cpp/src/gandiva/exported_funcs_registry.h [hunk 6]
```diff
@@ -21,34 +21,31 @@
...
+    registered().emplace_back(std::move(entry));
     return true;
   }
 
- private:
-  static list_type& registered() {
-    static list_type registered_list;
-    return registered_list;
-  }
+  static list_type& registered();
```
Comment (pitrou) [inline cpp/src/gandiva/exported_funcs_registry.h:44]: Our style conventions favors pointers over mutable refs.
```suggestion
  static list_type* registered();
```

Comment (niyue) [reply cpp/src/gandiva/exported_funcs_registry.h]: Fixed accordingly.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Review by js8544 — APPROVED** [review]
+1, just a simple nit.

File: cpp/src/gandiva/exported_funcs_registry.h [hunk 7]
```diff
@@ -21,34 +21,31 @@
...
+    registered()->emplace_back(std::move(entry));
     return true;
   }
 
- private:
-  static list_type& registered() {
-    static list_type registered_list;
-    return registered_list;
-  }
+  static list_type* registered();
```
Comment (js8544) [inline cpp/src/gandiva/exported_funcs_registry.h:44]: Sorry I didn't notice this previously. Is it possible to keep registered() as private and add a new public function
`static const list_type& Registered()`? It will be safer if the mutable instance is not exposed to users and they can still access a const reference.

**Review by js8544 — CHANGES_REQUESTED** [review]

File: cpp/src/gandiva/exported_funcs_registry.h (hunk 7 above)
Comment (niyue) [reply cpp/src/gandiva/exported_funcs_registry.h:48]: Sure. A new API `static const list_type& Registered()` is added, and the `registered()` API is still private, but I changed the private `registered()` API to return a pinter instead of mutable ref according to Antoine's suggestion above.

**Comment by js8544** [comment]
Thanks! LGTM now. Will need @pitrou's approval to merge.

**Review by pitrou — APPROVED** [review]
