### PR TITLE
GH-34640: [R] Can't read in partitioning column in CSV datasets when both (non-hive) partition and schema supplied

### LINKED ISSUE #34640: [R] Can't read in partitioning column in CSV datasets when both (non-hive) partition and schema supplied
### Describe the bug, including details regarding any error messages, version, and platform.

Surfaced via R:

``` r
library(dplyr)
library(arrow)

# set up temporary directory
tf <- tempfile()
dir.create(tf)

# set up dummy dataset
df <- tibble::tibble(group = rep(1:2, each = 5), value = 1:10)
df
#> # A tibble: 10 × 2
#>    group value
#>    <int> <int>
#>  1     1     1
#>  2     1     2
#>  3     1     3
#>  4     1     4
#>  5     1     5
#>  6     2     6
#>  7     2     7
#>  8     2     8
#>  9     2     9
#> 10     2    10

# write dataset
write_dataset(df, tf, format = "csv", partitioning = "group", hive_style = FALSE)

list.files(tf, recursive = TRUE)
#> [1] "1/part-0.csv" "2/part-0.csv"

# with just partitioning, successfully can read back in partitioning variable
open_dataset(
  tf,
  format = "csv",
  partitioning = "group"
) %>% collect()
#> # A tibble: 10 × 2
#>    value group
#>    <int> <int>
#>  1     1     1
#>  2     2     1
#>  3     3     1
#>  4     4     1
#>  5     5     1
#>  6     6     2
#>  7     7     2
#>  8     8     2
#>  9     9     2
#> 10    10     2

# with partitioning and schema supplied, "group" variable is not included
open_dataset(
  tf,
  format = "csv",
  schema = schema(value = int32()),
  skip = 1,
  partitioning = schema(group = int32())
) %>% collect()
#> # A tibble: 10 × 1
#>    value
#>    <int>
#>  1     1
#>  2     2
#>  3     3
#>  4     4
#>  5     5
#>  6     6
#>  7     7
#>  8     8
#>  9     9
#> 10    10

# we can't add the partitioning variable to the schema or we get an error
open_dataset(
  tf,
  format = "csv",
  schema = schema(value = int32(), group = int32()),
  skip = 1,
  partitioning = schema(group = int32())
) %>% collect()
#> Error in `compute.Dataset()` at r/R/dplyr-collect.R:33:2:
#> ! Invalid: Could not open CSV input source '/tmp/RtmpUTGEHf/file492ad7322363a/1/part-0.csv': Invalid: CSV parse error: Row #2: Expected 2 columns, got 1: 1
#> /home/nic2/arrow/cpp/src/arrow/csv/parser.cc:477  (ParseLine<SpecializedOptions, false>(values_writer, parsed_writer, data, data_end, is_final, &line_end, bulk_filter))
#> /home/nic2/arrow/cpp/src/arrow/csv/parser.cc:566  ParseChunk<SpecializedOptions>( &values_writer, &parsed_writer, data, data_end, is_final, rows_in_chunk, &data, &finished_parsing, bulk_filter)
#> /home/nic2/arrow/cpp/src/arrow/csv/reader.cc:426  parser->ParseFinal(views, &parsed_size)

#> Backtrace:
#>      ▆
#>   1. ├─... %>% collect()
#>   2. ├─dplyr::collect(.)
#>   3. └─arrow:::collect.Dataset(.)
#>   4.   ├─arrow:::collect.ArrowTabular(compute.Dataset(x), as_data_frame) at r/R/dplyr-collect.R:33:2
#>   5.   │ └─base::as.data.frame(x, ...) at r/R/dplyr-collect.R:27:4
#>   6.   └─arrow:::compute.Dataset(x) at r/R/dplyr-collect.R:33:2
#>   7.     └─base::tryCatch(...) at r/R/dplyr-collect.R:40:2
#>   8.       └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>   9.         └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  10.           └─value[[3L]](cond)
#>  11.             └─arrow:::augment_io_error_msg(e, call, schema = schema()) at r/R/dplyr-collect.R:49:6
#>  12.               └─rlang::abort(msg, call = call) at r/R/util.R:251:2
```

This was discussed on #32938 but the solution mentioned there works for Parquet files but not CSV.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by thisisnic**
### Rationale for this change

It wasn't possible to use the partitioning column in the dataset when reading in CSV datasets and supplying both a schema and a partition variable.

### What changes are included in this PR?

This PR updates the code which creates the `CSVReadOptions` object and makes sure we don't pass in the partition variable column name as a column name there, as previously this was resulting in an error.

### Are these changes tested?

Yes

### Are there any user-facing changes?

Yes 

* Closes: #34640

### CODE REVIEW

File: r/R/dataset-format.R [hunk 1]
```diff
@@ -223,7 +227,7 @@ check_csv_file_format_args <- function(args) {
   }
 
   if (is.null(args$read_options)) {
-    options$read_options <- do.call(csv_file_format_read_opts, args)
+    options$read_options <- do.call(csv_file_format_read_opts, c(args, partitioning = partitioning))
```
Comment (paleolimbot) [inline r/R/dataset-format.R:230]:
```suggestion
    options$read_options <- do.call(csv_file_format_read_opts, c(args, list(partitioning = partitioning)))
```

(I think `c(something_that_is_a_list, some_name = something_that_could_be_anything)` often, but not always, results in the output being a list...wrapping the second bit in a `list()` always works)

File: r/tests/testthat/test-dataset-csv.R [hunk 2]
```diff
@@ -593,3 +593,36 @@ test_that("CSVReadOptions field access", {
...
+    format = "csv",
+    schema = target_schema,
+    skip = 1
+  )
+  expect_r6_class(ds$format, "CsvFileFormat")
+  expect_r6_class(ds$filesystem, "LocalFileSystem")
+  expect_identical(names(ds), c(names(df1), "part"))
+  expect_identical(dim(ds), c(20L, 7L))
+  expect_equal(schema(ds), target_schema)
+
```
Comment (paleolimbot) [inline r/tests/testthat/test-dataset-csv.R:616]: Maybe also:

```r
expect_identical(names(collect(ds)), c(names(df1), "part"))
```

(I seem to remember there are some things that don't happen until a dataset is collected)

**Review by paleolimbot — APPROVED** [review]
A few minor suggestions! This is an amazingly parsimonious solution to a very annoying and long-standing bug!
