### PR TITLE
GH-35289: [Python] Support large variable width types in numpy conversion

### LINKED ISSUE #35289: [Python] Converting from NumPy to large_string or large_binary returns not implemented
### Describe the bug, including details regarding any error messages, version, and platform.

```

arr = np.array(["a", "b"])
pa.array(arr, type=pa.large_string())
```

This returns

```
    pa.array(arr, type=pa.large_string())
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: NumPyConverter doesn't implement <large_string> conversion. 
```

I think this should work?

### Component(s)

Python

### PR DESCRIPTION
**Pull request by Kimahriman**
### Rationale for this change
Add support for LargeBinaryType, BinaryViewType, LargeStringType, and StringViewType in NumPy to Arrow conversion.

### What changes are included in this PR?
Adds new `Visit` methods in `NumPyConverter` for `LargeStringType`, `StringViewType`, `LargeBinaryType`, and `BinaryViewType`. These are built on top of new templated `VisitString` and `VisitBinary` methods.

Also adds the Arrow -> NumPy type map for the large binary types.

### Are these changes tested?
New test added showing a string and binary array over 2 GiB is valid and still a single chunk. Also added the new Arrow to NumPy maps to a schema test.

### Are there any user-facing changes?
Adds support for converting NumPy string/binary lists to large binary types.

* Closes: #35289
* GitHub Issue: #35289

### CODE REVIEW

**Comment by AlenkaF** [comment]
Thank you for the contribution @Kimahriman !

The PR looks good!
As you have mentioned, there might be some improvement possible with consolidating the common code.

In the C++ part, where I am a novice also - but, I would try with creating a heper Status function and see if I can make it work with both builder instances or not (am not really sure it will work).

As for the python test, it could also be consolidated with `test_numpy_binary_overflow_to_chunked` with parametrizing the test function as for example in https://github.com/apache/arrow/blob/9ecd0f2a5fb76cca859269a6ff13eaf315abac62/python/pyarrow/tests/test_array.py#L635.

File: python/pyarrow/src/arrow/python/numpy_to_arrow.cc [hunk 1]
```diff
@@ -656,6 +693,33 @@ Status AppendUTF32(const char* data, int itemsize, int byteorder,
       reinterpret_cast<const uint8_t*>(PyBytes_AS_STRING(utf8_obj.obj())), length);
 }
 
+Status AppendUTF32(const char* data, int itemsize, int byteorder,
+                   ::arrow::LargeStringBuilder* builder) {
```
Comment (jorisvandenbossche) [inline python/pyarrow/src/arrow/python/numpy_to_arrow.cc:697]: For this function, only the final line of the function actually uses `builder`. So I think it should be possible to factor out most part of this function into something that can be reused, and only have the actual `builder->Append(..)` in a type-specific AppendUTF32?

**Comment by jorisvandenbossche** [comment]
> If there's a way to consolidate the common code let me know, this is my first C++ in a long time.

In the Visit functions, I think the main (only?) difference is the type of `builder` that was created? In that case I _think_ it should be possible to template this: have a single `VisitString()` that is templated on the builder type, and then the `Visit(const StringType& type)` could be a small wrapper around calling `VisitString<ChunkedStringBuilder>()`. Although the builder having different parameters to instantiate it might complicate things ..

**Comment by Kimahriman** [comment]
Thanks for the ideas, I'll see if I can figure anything out 😅

**Comment by Kimahriman** [comment]
Ok I learned about C++ templates and deduped the different functions, and I just parametrized the existing python test

File: python/pyarrow/src/arrow/python/numpy_to_arrow.cc (hunk 1 above)
Comment (Kimahriman) [reply python/pyarrow/src/arrow/python/numpy_to_arrow.cc]: Figured out how to get it working as a template, wasn't expecting it to be possible without a common base class for the two builders

**Review by AlenkaF — APPROVED** [review]
Great work! The PR looks good IMO +1.
@jorisvandenbossche could you give one more look before merging?

**Comment by Kimahriman** [comment]
@jorisvandenbossche gentle ping again. Merged in master and resolved the conflict

File: python/pyarrow/src/arrow/python/numpy_to_arrow.cc [hunk 2]
```diff
@@ -223,10 +223,16 @@ class NumPyConverter {
...
 
   // NumPy ascii string arrays
+  template <typename T>
+  Status VisitBinary(T* builder);
   Status Visit(const BinaryType& type);
+  Status Visit(const LargeBinaryType& type);
 
   // NumPy unicode arrays
+  template <typename T>
+  Status VisitString(T* builder);
```
Comment (jorisvandenbossche) [inline python/pyarrow/src/arrow/python/numpy_to_arrow.cc:233]: Small nitpick, but could you move those declarations of the helpers into `protected:` (eg just below `VisitNative` definition) 

(I don't think anyone outside of pyarrow is using this, but just to keep it consistent)

**Review by jorisvandenbossche — COMMENTED** [review]
Looks good! 

And apologies for the _very_ slow follow-up ..

I have one more request: could you add a simple test for this as well (the large_memory test you edited it good to have, but in most our CI builds those are skipped, so it would be good to have a simple small test as well that is run everywhere). 
For example there is a `test_array_from_numpy_ascii` and `test_array_from_numpy_unicode`. You could add one case to those tests with specifying the type as the large variant.

File: python/pyarrow/src/arrow/python/numpy_to_arrow.cc (hunk 2 above)
Comment (Kimahriman) [reply python/pyarrow/src/arrow/python/numpy_to_arrow.cc:233]: Just the `VisitBinary` and `VisitString` declarations specifically?

**Comment by Kimahriman** [comment]
> Looks good!
> 
> And apologies for the _very_ slow follow-up ..
> 
> I have one more request: could you add a simple test for this as well (the large_memory test you edited it good to have, but in most our CI builds those are skipped, so it would be good to have a simple small test as well that is run everywhere). For example there is a `test_array_from_numpy_ascii` and `test_array_from_numpy_unicode`. You could add one case to those tests with specifying the type as the large variant.

Parameterized those tests to specify the type and use regular and large types

File: python/pyarrow/src/arrow/python/numpy_to_arrow.cc (hunk 2 above)
Comment (jorisvandenbossche) [reply python/pyarrow/src/arrow/python/numpy_to_arrow.cc]: Yes, exactly as what you did

File: python/pyarrow/tests/test_array.py [hunk 3]
```diff
@@ -2355,32 +2355,33 @@ def test_array_from_numpy_timedelta_incorrect_unit():
             pa.array(data)
 
 
-def test_array_from_numpy_ascii():
+@pytest.mark.parametrize('binary_type', [pa.binary(), pa.large_binary()])
```
Comment (jorisvandenbossche) [inline python/pyarrow/tests/test_array.py:2358]: OK, one last comment (promised! ;)): I think we want to keep testing the below also in the case of not specifying the type (in which case we infer the small types), and I am not entirely sure this is explicitly covered elsewhere (implicitly for sure). But so could parametrize this slightly differently with:

```suggestion
@pytest.mark.parametrize('typ, expected_type', [(None, pa.binary()), (pa.binary(), pa.binary()), (pa.large_binary(), pa.large_binary())])
```

And then the same for string test below.

Or, maybe simpler, just duplicate the first case to have a version without a type specified:

```
    # without specified type, always binary
    arrow_arr = pa.array(arr)
    assert arrow_arr.type == 'binary'
    expected = ..

    arrow_arr = pa.array(arr, binary_type)
    assert arrow_arr.type == binary_type
    expected = ..
```

(I assume that for the inference it shouldn't matter if there are strides or not)

Comment (Kimahriman) [reply python/pyarrow/tests/test_array.py:2358]: Yeah I thought about that as I was making the update hah, will add back the inferring

Comment (Kimahriman) [reply python/pyarrow/tests/test_array.py]: Added a third parameter and just set the expected type in the func
```python

**Comment by rok** [comment]
I can review or pickup next week. @Kimahriman are you interested in continuing this work?

**Comment by Kimahriman** [comment]
> I can review or pickup next week. @Kimahriman are you interested in continuing this work?

I was able to get this up to date with main, I don't know much about the view types

**Comment by rok** [comment]
Thank you @Kimahriman! Depending on how adventurous you feel we can make a separate PR or add view types here.

**Comment by Kimahriman** [comment]
Probably would be good to do in a follow on, not sure how quickly I can figure out and get the views working

**Comment by rok** [comment]
@Kimahriman agreed!

**Comment by Kimahriman** [comment]
Nevermind adding the views was pretty simple

File: python/pyarrow/tests/test_array.py [hunk 4]
```diff
@@ -3286,24 +3295,34 @@ def test_numpy_binary_overflow_to_chunked():
...
-            chunk = arrow_arr.chunk(i)
-            for val in chunk:
-                assert val.as_py() == case[value_index]
-                value_index += 1
+            value_index = 0
+            for i in range(arrow_arr.num_chunks):
+                chunk = arrow_arr.chunk(i)
+                for val in chunk:
+                    assert val.as_py() == case[value_index]
+                    value_index += 1
```
[the remark this answers is not in the document]
Comment (Kimahriman) [reply python/pyarrow/tests/test_array.py:3325]: It's because of the if else inserted. I guess the non overflow for large types could just be a separate test

[the remark this answers is not in the document]
Comment (rok) [reply python/pyarrow/tests/test_array.py:3325]: Oh sorry, I didn't read the diff right.

[the remark this answers is not in the document]
Comment (rok) [reply python/pyarrow/tests/test_array.py:3325]: I think it's ok to keep it as is.

**Review by AlenkaF — APPROVED** [review]
Thank you for continuing to work on this PR @Kimahriman, it is much appreciated! And thanks @pitrou for the ping.

The PR LGTM with all the comments addressed. I think you can update the description tiny bit (`AppendUTF32` is updated, no copy was needed AFAIU).

**Comment by Kimahriman** [comment]
All the open discussions should be resolved, and I updated the description a bit with the current implementation

**Comment by AlenkaF** [comment]
@github-actions crossbow submit -g python

**Review by rok — APPROVED** [review]
Looks great, thanks for doing this @Kimahriman !
