### PR TITLE
GH-38930: [Java] Fix spelling

### LINKED ISSUE #38930: [Java] Spelling errors identified by check-spelling
### Describe the bug, including details regarding any error messages, version, and platform.

The [check-spelling action](https://github.com/marketplace/actions/check-spelling) enabled me to identify some misspellings...

The misspellings have been reported at https://github.com/jsoref/apache-arrow/actions/runs/7008141484/attempts/1#summary-19063787889

### Component(s)

Java

### PR DESCRIPTION
**Pull request by jsoref**
### What changes are included in this PR?

Spelling fixes to java/

### Are there any user-facing changes?

* Closes: #38930

### CODE REVIEW

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java [hunk 1]
```diff
@@ -142,15 +142,15 @@ public void testConnectWithInsensitiveCasePropertyKeys() throws Exception {
              driver.connect("jdbc:arrow-flight://" +
                      dataSource.getConfig().getHost() + ":" +
                      dataSource.getConfig().getPort() + "?" +
-                     "UseEncryptiOn=false",
+                     "UseEncryptIon=false",
```
Comment (vibhatha) [inline java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java:145]: shouldn't it be?

```suggestion
                     "UseEncryption=false",
```

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java [hunk 2]
```diff
@@ -142,15 +142,15 @@ public void testConnectWithInsensitiveCasePropertyKeys() throws Exception {
...
                  dataSource.getProperties(dataSource.getConfig().getUser(), dataSource.getConfig().getPassword()))) {
       assertTrue(connection.isValid(300));
     }
     try (Connection connection =
              driver.connect("jdbc:arrow-flight-sql://" +
                      dataSource.getConfig().getHost() + ":" +
                      dataSource.getConfig().getPort() + "?" +
-                     "UseEncryptiOn=false",
+                     "UseEncryptIon=false",
```
Comment (vibhatha) [inline java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java:153]: shouldn't it be?

```suggestion
                     "UseEncryption=false",
```

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java [hunk 3]
```diff
@@ -162,7 +162,7 @@ public void testConnectWithInsensitiveCasePropertyKeys2() throws Exception {
     final Driver driver = new ArrowFlightJdbcDriver();
     Properties properties =
         dataSource.getProperties(dataSource.getConfig().getUser(), dataSource.getConfig().getPassword());
-    properties.put("UseEncryptiOn", "false");
+    properties.put("UseEncryptIon", "false");
```
Comment (vibhatha) [inline java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java:165]: same?

File: java/vector/src/main/java/org/apache/arrow/vector/complex/impl/StructOrListWriterImpl.java [hunk 4]
```diff
@@ -88,7 +88,7 @@ public StructOrListWriter struct(final String name) {
    *
    * @param name Unused.
    */
-  public StructOrListWriter listoftstruct(final String name) {
+  public StructOrListWriter listofstruct(final String name) {
```
Comment (vibhatha) [inline java/vector/src/main/java/org/apache/arrow/vector/complex/impl/StructOrListWriterImpl.java:91]: Just curious, should it be?

```suggestion
  public StructOrListWriter listOfStruct(final String name) {
```

**Review by vibhatha — APPROVED** [review]
Thank you for working on this. This PR LGTM, and I added a few suggestions too.

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java (hunk 1 above)
Comment (jsoref) [reply java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java:145]: That is covered by the normal test flow:
https://github.com/apache/arrow/blob/16fd249385aba5a1c80708de894185cebd601cad/java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java#L115-L122

These tests, otoh are for nonstandard forms:
https://github.com/apache/arrow/blob/16fd249385aba5a1c80708de894185cebd601cad/java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcDriverTest.java#L138-L145

I've selected `Encrypt` + `Ion` because both are words while still honoring the requirement that it be a non-standard case of `Encryption`.

File: java/vector/src/main/java/org/apache/arrow/vector/complex/impl/StructOrListWriterImpl.java (hunk 4 above)
Comment (jsoref) [reply java/vector/src/main/java/org/apache/arrow/vector/complex/impl/StructOrListWriterImpl.java:91]: That'd be my preference, yes. But I'm not sure how much changes people would tolerate, so I tend to make minimal suggested changes.

I'm willing to make this change if requested.

File: java/vector/src/main/codegen/templates/BaseWriter.java [hunk 5]
```diff
@@ -117,7 +117,7 @@ public interface StructOrListWriter {
     void start();
     void end();
     StructOrListWriter struct(String name);
-    StructOrListWriter listoftstruct(String name);
+    StructOrListWriter listofstruct(String name);
```
Comment (lidavidm) [inline java/vector/src/main/codegen/templates/BaseWriter.java:120]: This is a public method. I don't think we can just replace it, we should deprecate the old one and add the new one.

Comment (jsoref) [reply java/vector/src/main/codegen/templates/BaseWriter.java:120]: would you prefer `listOfStruct` or `listofstruct`

Comment (lidavidm) [reply java/vector/src/main/codegen/templates/BaseWriter.java:120]: `listOfStruct` would be better if we're already doing a rename.

**Review by lidavidm — APPROVED** [review]
