### PR TITLE
GH-46636: [R] Fix evaluation of external objects not in global environment in `case_when()`

### LINKED ISSUE #46636: `case_when()` sometimes doesn't find existing objects in the environment
### Describe the bug, including details regarding any error messages, version, and platform.

When running the example below `foo.R` with `source("foo.R", local = new.env())`, the object `pattern` is not found by `arrow` while it is defined in this new environment. It seems `arrow` doesn't search the objects in the correct environment when using `case_when()`. 

The same code using `dplyr` instead of `arrow` works fine. The `arrow` code also works fine interactively or with `source()` only. 

`foo.R`:
```r
library(arrow)
library(dplyr)

dat <- arrow_table(x = c("a", "b", "c"))
pattern <- "a"
dat |>
  mutate(x2 = case_when(pattern == "a" ~ "foo")) |>
  collect()
```

---

R 4.5.0
`arrow` 19.0.1.1

### Component(s)

R

### PR DESCRIPTION
**Pull request by etiennebacher**
### Rationale for this change

When a script is called in an environment that isn't the global environment (for instance with `source("my-script.R", local = new.env())`, `case_when()` would fail to detect external objects used in conditions.

This PR fixes this behavior.

Fixes #46636 

### What changes are included in this PR?

When evaluating expressions in `dplyr` functions, `eval_tidy()` now takes into account `mask` as an environment where it should look for external objects.

@thisisnic suggested in #46636 that the bug might be due to https://github.com/apache/arrow/blob/main/r/R/dplyr-funcs-conditional.R#L116 but I couldn't find a way to fix it there.

### Are these changes tested?

I added a test for this scenario. I ensured it failed before the change and succeeds after.

### Are there any user-facing changes?

There is one user-facing, non-breaking change, illustrated both in the related issue and in the new test.

* GitHub Issue: #46636

### CODE REVIEW

**Comment by etiennebacher** [comment]
I don't know the cause of the "Dev" workflow failure, it just says the job was cancelled at some point.

Edit: looks related to https://github.com/apache/arrow/pull/46668/

**Comment by thisisnic** [comment]
Thanks for the PR @etiennebacher, much appreciated!

OK, this is a bit long-winded, but I'm a bit unsure about something so wanted to spell out my reasoning.

* In `arrow_mask()`, we take the functions created in the .cache environment and add them to the mask in order to be able to use our bindings from R functions to Arrow compute functions here.  We add the column references to the mask too.
* In `arrow_eval()` we call `add_user_functions_to_mask()` (which is used to enable user-created R functions in Arrow without needing to use the UDF functionality), which looks for R functions in expressions being evaluated which are currently absent from the mask, and see if we can find them in the mask's "grandparent" environment and adds them to the data mask.
  * In the comment in `add_user_functions_to_mask()` we reference `case_when()` which makes me think that this gives a clue to why it specifically doesn't work there.
* When we now pass `mask` to the `env` param in this PR (`eval_tidy(expr, data = mask, env = mask)`), we get to add those items manually
  * Also: "Objects in `data` have priority over those in `env`" (from the `eval_tidy()` docs).

Source of the issue:
* In `case_when()` the mask passed to `arrow_eval()` is based on the `caller_env()`.  
  * We also do this in other places, e.g. bindings for verbs like `mutate()` but I can't reproduce the original issue when using those functions.
    * But in `mutate()` we use `expand_across()` which calls `quo_get_env()` which does the job of getting the environment - (from the docs:) "A quosure is guaranteed to evaluate in its original environment and can refer to local objects safely".
    * I don't know what "safely" means here, but I'm wondering if there's some reason we might want `case_when()` to be able to refer to the relevant environment instead of blanket updating for `eval_tidy()`, if there's a reason we didn't pass the mask in as `env` beyond just leaving things as the default?
      * So for example, in `case_when()`, where we have the code `mask <- caller_env()`, maybe instead we actually want `mask <- caller_env(n=2)` or something like that, because if that works we've got less risk of unintended consequences?

Or, are there no unintended consequences likely (as `data` takes precedent over `env` anyway), and we can just do this as-is and everyone's happy.

cc @nealrichardson - is this good to go as-is?

**Comment by etiennebacher** [comment]
>  in case_when(), where we have the code mask <- caller_env(), maybe instead we actually want mask <- caller_env(n=2) or something like that, because if that works we've got less risk of unintended consequences?

Thanks for the detailed reasoning. I should have probably explained a bit more what I had tried.

My first attempt was indeed to use `caller_env(2)` and I thought it would easily solve the issue, but it turns out this generates a warning, in addition to the original error (I locally reverted the change in `arrow_eval()` so I'm basically using the `main` branch):

> Passing an environment as data mask is deprecated. Please use `new_data_mask()` to transform your environment to a mask.
>
> env <- env(foo = "bar")
>
> \# Bad: as_data_mask(env) eval_tidy(expr, env)
>
> \# Good: mask <- new_data_mask(env) eval_tidy(expr, mask)

This doesn't make any sense to me, `caller_env()` and `caller_env(2)` both return an environment, but only the latter triggers this warning.

I tried to play with the `n` in `caller_env()`, with the parent environments, but nothing worked. In the end, I tried this:

- I put `browser()` after `mask <- caller_env()`, ran `source("foo.R", local = new.env())`, and exported its value with `mask_local <<- mask`
- did the same with `source("foo.R")` and exported the value to `mask_global`

(it's important to do local first, and then global).

Here's the output of `waldo::compare()`:

```r
> waldo::compare(mask_global, mask_local)
`old$.data$x$.:xp:.` is <pointer: 0x000001b2a2bee6d0>
`new$.data$x$.:xp:.` is <pointer: 0x000001b2a2bee330>

`old$.data$x$schema$.:xp:.` is <pointer: 0x000001b2a2bee7d0>
`new$.data$x$schema$.:xp:.` is <pointer: 0x000001b2a2bee3d0>

`old$.data$x$schema$fields[[1]]$.:xp:.` is <pointer: 0x000001b2a2bee350>
`new$.data$x$schema$fields[[1]]$.:xp:.` is <pointer: 0x000001b2a2bee650>

`old$.data$x$schema$fields[[1]]$type$.:xp:.` is <pointer: 0x000001b2a2bee750>
`new$.data$x$schema$fields[[1]]$type$.:xp:.` is <pointer: 0x000001b2a2bee870>

`parent.env(old$.env)` is <env:global>
`parent.env(new$.env)` is <env:0x000001b2a6293438>

`parent.env(old$.top_env)` is <env:global>
`parent.env(new$.top_env)` is <env:0x000001b2a6293438>
```

I see that the parent environment is different, but I can't figure out where this could be fixed. I'm open to suggestions on this, I agree that modifying `eval_tidy()` just for this is a bit clumsy, but I thought if this had unanticipated consequences then the test suite would catch those.

**Comment by thisisnic** [comment]
Thanks for the extra context there, that's super helpful!  I agree it should probably be in the test suite if anything else could affect it though there's always weird edge cases.  I'll give it a few days so other folks get the chance to give it a look in case I'm missing anything here, but if not, happy to merge.  Thanks again!

**Comment by nealrichardson** [comment]
> cc @nealrichardson - is this good to go as-is?

As long as the new test fails without the fix and it passes with it, I guess so? I don't understand how passing the `mask` in `eval_tidy()` twice would make a difference, but if everything is working and tests cover it, I don't need to understand 🤠

**Comment by thisisnic** [comment]
> > cc @nealrichardson - is this good to go as-is?
> 
> As long as the new test fails without the fix and it passes with it, I guess so? I don't understand how passing the `mask` in `eval_tidy()` twice would make a difference, but if everything is working and tests cover it, I don't need to understand 🤠

Cool, just checking there wasn't anything "obvious" I was missing.  I'll approve then.  Cheers @etiennebacher for fixing this!

**Review by thisisnic — APPROVED** [review]
Fantastic, thanks for fixing!

File: r/tests/testthat/test-dplyr-funcs-conditional.R [hunk 1]
```diff
@@ -491,3 +491,20 @@ test_that("coalesce()", {
...
+  expect_identical(
+    dat |>
+      mutate(x2 = case_when(x == pattern ~ "foo")) |>
+      collect(),
+    tibble(x = c("a", "b"), x2 = c("foo", NA))
+  )
+  expect_identical(
+    dat |>
+      mutate(x2 = if_else(x == pattern, "foo", NA_character_)) |>
+      collect(),
```
Comment (eitsupi) [inline r/tests/testthat/test-dplyr-funcs-conditional.R]: I suppose base pipe `|>` should be replaced by `%>%`.
https://github.com/apache/arrow/blob/fbed20a9a23f23dc256539179a90ab465d1b1c2e/r/DESCRIPTION#L24

Comment (etiennebacher) [reply r/tests/testthat/test-dplyr-funcs-conditional.R]: Thanks, good catch
