### PR TITLE
GH-33782: [Release] Vote email number of issues is querying JIRA and producing a wrong number

### LINKED ISSUE #33782: [Release] Vote email number of issues is querying JIRA and producing a wrong number
### Describe the bug, including details regarding any error messages, version, and platform.

When generating the vote email for RC 0 on 11.0.0 I've realised that the vote email generated contains the following:
```
This is a release consisting of 274 resolved JIRA issues[1].
```
This number is extracted from:
```
jira_url="https://issues.apache.org/jira"
  jql="project%20%3D%20ARROW%20AND%20status%20in%20%28Resolved%2C%20Closed%29%20AND%20fixVersion%20%3D%20${version}"
  n_resolved_issues=$(curl "${jira_url}/rest/api/2/search/?jql=${jql}" | jq ".total")
```
This is wrong now, we should extract this from the GitHub milestone:
https://github.com/apache/arrow/milestone/1?closed=1
I've updated this manually for the current email vote but we should fix it on the `dev/release/02-source.sh` script.

### Component(s)

Release

### PR DESCRIPTION
**Pull request by rok**
### What changes are included in this PR?

Release RC vote email now gets issue number and verify release PR's url from GitHub's GraphQL API.

### Are these changes tested?

Changes were tested stand-alone from the rest of this script.

### Are there any user-facing changes?

ARROW_GITHUB_API_TOKEN is now mandatory for generating the release vote email.
* Closes: #33782

### CODE REVIEW

**Comment by raulcd** [comment]
It seems we have to modify the test to match the new URL: https://github.com/apache/arrow/blob/master/dev/release/02-source-test.rb#L152

**Comment by rok** [comment]
@raulcd indeed. It also required some Ruby changes. I think this is ready for review.

File: dev/release/02-source-test.rb [hunk 1]
```diff
@@ -93,33 +93,26 @@ def test_python_version
...
+
+    n_issues_query = "{\"query\":\"query {search(query: \\\"repo:apache/arrow is:issue is:closed milestone:#{@release_version}\\\", type:ISSUE) {issueCount}}\"}"
+    req.body = n_issues_query
     n_resolved_issues = nil
-    search_url = URI("#{jira_url}/rest/api/2/search?jql=#{CGI.escape(jql)}")
-    search_url.open do |response|
-      n_resolved_issues = JSON.parse(response.read)["total"]
+    https.request(req) do |response|
+        n_resolved_issues = JSON.parse(response.body)["data"]["search"]["issueCount"]
     end
```
Comment (kou) [inline dev/release/02-source-test.rb:107]: We can use `Net::HTTP.post`:

```ruby
uri = URI.parse("https://api.github.com/graphql")
n_issues_query = {
  "query" => <<-QUERY,
    query {
      search(query: "repo:apache/arrow is:issue is:closed milestone:#{@release_version}",
             type: ISSUE) {
        issueCount
      }
    }
  QUERY
}
response = Net::HTTP.post(uri,
                          n_issues_query.to_json,
                          "Content-Type" => "application/json",
                          "Authorization" => "Bearer #{github_token}")
n_resolved_issues = JSON.parse(response.body)["data"]["search"]["issueCount"]
```

File: dev/release/02-source-test.rb [hunk 2]
```diff
@@ -93,33 +93,26 @@ def test_python_version
...
-    github_token = ENV["ARROW_GITHUB_API_TOKEN"]
-    if github_token
-      headers["Authorization"] = "Bearer #{github_token}"
-    end
-    verify_prs.open(headers) do |response|
-      verify_pr_url = (JSON.parse(response.read)[0] || {})["html_url"]
+    https.request(req) do |response|
+      verify_pr_url = JSON.parse(response.body)["data"]["repository"]["refs"]["nodes"][0]["associatedPullRequests"]["edges"][0]["node"]["url"]
     end
+
```
Comment (kou) [inline dev/release/02-source-test.rb:115]: Do we need to change this? It seems that we can still use the current simple REST API.

File: dev/release/02-source.sh [hunk 3]
```diff
@@ -142,18 +142,18 @@ if [ ${SOURCE_PR} -gt 0 ]; then
...
-  n_resolved_issues=$(curl "${jira_url}/rest/api/2/search/?jql=${jql}" | jq ".total")
-  curl_options=(--header "Accept: application/vnd.github+json")
-  if [ -n "${ARROW_GITHUB_API_TOKEN:-}" ]; then
-    curl_options+=(--header "Authorization: Bearer ${ARROW_GITHUB_API_TOKEN}")
-  fi
-  curl_options+=(--get)
-  curl_options+=(--data "state=open")
-  curl_options+=(--data "head=apache:${rc_branch}")
-  curl_options+=(https://api.github.com/repos/apache/arrow/pulls)
-  verify_pr_url=$(curl "${curl_options[@]}" | jq -r ".[0].html_url")
```
Comment (kou) [inline dev/release/02-source.sh:156]: Do we need to change this? It seems that we can still use the current simple REST API.

File: dev/release/02-source-test.rb (hunk 1 above)
Comment (rok) [reply dev/release/02-source-test.rb]: Used your proposal.

File: dev/release/02-source-test.rb (hunk 2 above)
Comment (rok) [reply dev/release/02-source-test.rb]: I proposed the change to use a single API endpoint, it's not that important I suppose. Reverting.

File: dev/release/02-source.sh (hunk 3 above)
Comment (rok) [reply dev/release/02-source.sh]: Same as above. Reverting.

**Review by kou — APPROVED** [review]
+1
