### PR TITLE
GH-38096: [Java] FlightStream with metadata can cause error when closing

### LINKED ISSUE #38096: [Java] Flight stream with metadata gives an error if closed twice
### Describe the bug, including details regarding any error messages, version, and platform.

If the FlightStream has metadata and ends up being closed twice, the metadata buffer will decrement the reference count below zero and throw an error.

```
java.lang.IllegalStateException: RefCnt has gone negative
	at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:458)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:130)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
	at org.apache.arrow.memory.ArrowBuf.close(ArrowBuf.java:1044)
	at org.apache.arrow.util.AutoCloseables.close(AutoCloseables.java:97)
	at org.apache.arrow.flight.FlightStream.close(FlightStream.java:208)
```

### Component(s)

Java

### PR DESCRIPTION
**Pull request by BryanCutler**
### Rationale for this change

The Java FlightStream can raise an error if metadata is transferred and ends up being closed twice.

```
java.lang.IllegalStateException: RefCnt has gone negative
	at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:458)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:130)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
	at org.apache.arrow.memory.ArrowBuf.close(ArrowBuf.java:1044)
	at org.apache.arrow.util.AutoCloseables.close(AutoCloseables.java:97)
	at org.apache.arrow.flight.FlightStream.close(FlightStream.java:208)
```

### What changes are included in this PR?

When FlightStream is closed, remove any reference of previous metadata to prevent reference count going negative if closed again. Also added `ExchangeReaderWriter.getResult()` for convenience and clear up ambiguity on error handling.

### Are these changes tested?

Unit tests added for closing with metadata and 

### Are there any user-facing changes?

Added `ExchangeReaderWriter.getResult()`
* Closes: #38096

### CODE REVIEW

**Comment by BryanCutler** [comment]
@lidavidm I was playing around with the DoExchange call and noticed a couple of issues. At first I was a little confused as to why `getWriter().getResult()` wasn't being called until I realized that errors were coming through the reader. If `getWriter().getResult()` is called before `getReader().next()` is called a final time, then it seems to hang.

So I noticed that you really need to call `getReader().next()` a final time, so it will return false or raise any errors that happened after exchanging all the batches. To hopefully make this more clear to the user I added `ExchangeReaderWriter.getResult()` so it will be obvious to call this instead. I'm not 100% sure that it's a good idea, so let me know what you think. Thanks!

File: java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java [hunk 1]
```diff
@@ -412,6 +412,16 @@ public ClientStreamListener getWriter() {
...
     }
 
+    /**
+     * Make sure stream is drained. You must call this to be notified of any errors that may have
+     * happened after the exchange is complete. This should be called after `getWriter().completed()`
+     * and instead of `getWriter().getResult()`.
+     */
+    public void getResult() {
+      // After exchange is complete, make sure stream is drained to propagate errors through reader
+      reader.next();
```
Comment (lidavidm) [inline java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java:422]: Possibly loop while reader.next()?

File: java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightStream.java [hunk 2]
```diff
@@ -207,6 +207,8 @@ public void close() throws Exception {
         } else {
           AutoCloseables.close(closeables);
         }
+        // Remove any metadata after closing to prevent negative refcnt
+        applicationMetadata = null;
```
Comment (lidavidm) [inline java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightStream.java:211]: Should this go in the finally instead? I suppose if this throws the application is unlikely to close again.

File: java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java [hunk 3]
```diff
@@ -412,6 +412,16 @@ public ClientStreamListener getWriter() {
...
+    }
+
     /** Shut down the streams in this call. */
     @Override
     public void close() throws Exception {
```
Comment (lidavidm) [inline java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java:427]: Should we drain the stream in close as well?

**Review by lidavidm — APPROVED** [review]
Thanks, just some nits

File: java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightStream.java (hunk 2 above)
Comment (BryanCutler) [reply java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightStream.java:211]: I put it here because if something throws and error before this, it's likely the buffer was not closed then. So at least this way, the buffer could be examined, but either way I don't think the application could recover.

File: java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java (hunk 3 above)
Comment (BryanCutler) [reply java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java:427]: It is drained already in the call to `reader.close()`. From what I can tell, it will suppress any exception though. So probably better off draining with the call to `getResult()` before closing to handle any errors, wdyt?

**Comment by BryanCutler** [comment]
> We try to expose 'independent' readers/writers but in actuality in gRPC they are tied + the reader is the only source of errors (which in some sense makes sense, I suppose) so this is perhaps more of a mistake in our API design

Makes sense, thanks for the explanation

File: java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java (hunk 3 above)
Comment (lidavidm) [reply java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java:427]: Sounds good.

**Review by lidavidm — APPROVED** [review]

**Comment by BryanCutler** [comment]
Thanks @lidavidm !
