### PR TITLE
GH-38462: [Go][Parquet] Handle Boolean RLE encoding/decoding

### LINKED ISSUE #38345: [Release][Go] Verification tasks for the Release Candidate fail on Go parquet encryption tests
### Describe the bug, including details regarding any error messages, version, and platform.

We have created the RC 2 for the Apache Arrow 14.0.0 release and currently we are facing the following error on the release verification for the go sources:
```
 /tmp/parquet-encryption-test-3157156869
--- FAIL: TestFileEncryptionDecryption (0.40s)
    --- FAIL: TestFileEncryptionDecryption/TestDecryption (0.34s)
        --- FAIL: TestFileEncryptionDecryption/TestDecryption/uniform_encryption.parquet.encrypted (0.07s)
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/uniform_encryption.parquet.encrypted/config_1 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/uniform_encryption.parquet.encrypted/config_1
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/uniform_encryption.parquet.encrypted/config_3 (0.01s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/uniform_encryption.parquet.encrypted/config_3
        --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer.parquet.encrypted (0.06s)
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer.parquet.encrypted/config_1 (0.01s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer.parquet.encrypted/config_1
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer.parquet.encrypted/config_3 (0.01s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer.parquet.encrypted/config_3
        --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_plaintext_footer.parquet.encrypted (0.08s)
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_plaintext_footer.parquet.encrypted/config_1 (0.01s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_plaintext_footer.parquet.encrypted/config_1
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_plaintext_footer.parquet.encrypted/config_3 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_plaintext_footer.parquet.encrypted/config_3
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_plaintext_footer.parquet.encrypted/config_4 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_plaintext_footer.parquet.encrypted/config_4
        --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_aad.parquet.encrypted (0.06s)
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_aad.parquet.encrypted/config_1 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_aad.parquet.encrypted/config_1
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_aad.parquet.encrypted/config_2 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_aad.parquet.encrypted/config_2
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_aad.parquet.encrypted/config_3 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_aad.parquet.encrypted/config_3
        --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_disable_aad_storage.parquet.encrypted (0.02s)
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_disable_aad_storage.parquet.encrypted/config_2 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_disable_aad_storage.parquet.encrypted/config_2
        --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_ctr.parquet.encrypted (0.05s)
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_ctr.parquet.encrypted/config_1 (0.00s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_ctr.parquet.encrypted/config_1
            --- FAIL: TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_ctr.parquet.encrypted/config_3 (0.01s)
                encryption_read_config_test.go:217: 
                    	Error Trace:	/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:217
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:406
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:430
                    	            				/tmp/arrow-14.0.0.Rm87k/apache-arrow-14.0.0/go/parquet/encryption_read_config_test.go:468
                    	            				/tmp/arrow-14.0.0.Rm87k/go/gopath/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
                    	Error:      	Not equal: 
                    	            	expected: int(0)
                    	            	actual  : int64(50)
                    	Test:       	TestFileEncryptionDecryption/TestDecryption/encrypt_columns_and_footer_ctr.parquet.encrypted/config_3
/tmp/parquet-encryption-test-3429813239
FAIL
FAIL	github.com/apache/arrow/go/v14/parquet	0.464s
```
This is reproducible locally with:
```
archery docker run  -e VERIFY_VERSION="14.0.0" -e VERIFY_RC="2" -e TEST_DEFAULT=0 -e TEST_GO=1 almalinux-verify-rc
```
We didn't noticed before because this doesn't fail with non-official releases (local source):
```
archery docker run  -e VERIFY_VERSION="" -e VERIFY_RC="" -e TEST_DEFAULT=0 -e TEST_GO=1 almalinux-verify-rc
```
See error here: https://github.com/ursacomputing/crossbow/actions/runs/6572466559/job/17853633830
And workflow file: https://github.com/ursacomputing/crossbow/actions/runs/6572466559/workflow

Successful one on maintenance branch where we test from local: https://github.com/ursacomputing/crossbow/actions/runs/6572711355/job/17854324601
And workflow file: https://github.com/ursacomputing/crossbow/actions/runs/6572711355/workflow

### Component(s)

Go, Release

### LINKED ISSUE #38462: [Go][Parquet] Handle Boolean RLE encoding/decoding
### Describe the enhancement requested

In addition to the plain boolean encoding (done as a bitmap) we should also support the bit-packed RLE/hybrid boolean encoding/decoding for parquet files in the Go Parquet implementation. This is also relevant more now because several of the parquet-testing repo files have been updated to utilize boolean columns that have the RLE encoding type.

### Component(s)

Go, Parquet

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
Looks like the parquet-testing repo files have been updated and now include boolean columns which use the RLE encoding type. This causes the Go parquet lib to fail verification tests when it pulls the most recent commits for the parquet-testing repository. So a solution for this is to actually implement the RleBoolean encoder and decoder.

### What changes are included in this PR?
Adding `RleBooleanEncoder` and `RleBooleanDecoder` and updating the `parquet-testing` repo.

### Are these changes tested?
Unit tests are added, and this is also tested via the `parquet-testing` golden files.

* Closes: #38345
* Closes: #38462

### CODE REVIEW

File: go/parquet/internal/encoding/boolean_decoder.go [hunk 1]
```diff
@@ -109,3 +114,76 @@ func (dec *PlainBooleanDecoder) DecodeSpaced(out []bool, nullCount int, validBit
...
+		return fmt.Errorf("invalid length - %d (corrupt data page?)", len(data))
+	}
+
+	// load the first 4 bytes in little-endian which indicates the length
+	nbytes := binary.LittleEndian.Uint32(data[:4])
+	if nbytes > uint32(len(data)-4) {
+		return fmt.Errorf("received invalid number of bytes - %d (corrupt data page?)", nbytes)
+	}
+
+	dec.data = data[4:]
```
Comment (kou) [inline go/parquet/internal/encoding/boolean_decoder.go:141]: Do we need to use `nbytes` here? 

```suggestion
	dec.data = data[4:(4 + nbytes)]
```

File: go/parquet/internal/encoding/boolean_decoder.go [hunk 2]
```diff
@@ -109,3 +114,76 @@ func (dec *PlainBooleanDecoder) DecodeSpaced(out []bool, nullCount int, validBit
...
+func (dec *RleBooleanDecoder) Decode(out []bool) (int, error) {
+	max := shared_utils.MinInt(len(out), dec.nvals)
+
+	var (
+		buf [1024]uint64
+		n   = max
+	)
+
+	for n > 0 {
+		batch := shared_utils.MinInt(1024, n)
```
Comment (kou) [inline go/parquet/internal/encoding/boolean_decoder.go:159]:
```suggestion
		batch := shared_utils.MinInt(len(buf), n)
```

File: go/parquet/internal/encoding/boolean_encoder.go [hunk 3]
```diff
@@ -87,3 +89,53 @@ func (enc *PlainBooleanEncoder) FlushValues() (Buffer, error) {
...
+}
+
+func (enc *RleBooleanEncoder) PutSpaced(in []bool, validBits []byte, validBitsOffset int64) {
+	bufferOut := make([]bool, len(in))
+	nvalid := spacedCompress(in, bufferOut, validBits, validBitsOffset)
+	enc.Put(bufferOut[:nvalid])
+}
+
+func (enc *RleBooleanEncoder) EstimatedDataEncodedSize() int64 {
+	const rleLengthInBytes = 4
```
Comment (kou) [inline go/parquet/internal/encoding/boolean_encoder.go:114]: Can we share this value in here, `FlushValues()` and `RleBooleanDecoder.SetData()` instead of defining this value in multiple places (or use `4` as a magic number)?

**Review by kou — COMMENTED** [review]
(I think that we don't need to rush to implement this for 14.0.0 because it's already feature freezed.)

File: go/parquet/internal/encoding/boolean_encoder.go [hunk 4]
```diff
@@ -87,3 +89,53 @@ func (enc *PlainBooleanEncoder) FlushValues() (Buffer, error) {
...
+func (enc *RleBooleanEncoder) FlushValues() (Buffer, error) {
+	const rleLengthInBytes = 4
+	rleBufferSizeMax := enc.maxRleBufferSize()
+	enc.sink.SetOffset(rleLengthInBytes)
+	enc.sink.Reserve(rleBufferSizeMax)
+
+	encoder := utils.NewRleEncoder(enc.sink, 1)
+	for _, v := range enc.bufferedValues {
+		if v {
+			encoder.Put(1)
```
Comment (pitrou) [inline go/parquet/internal/encoding/boolean_encoder.go:131]: Is the RLE encoder thoroughly tested somewhere else?

File: go/parquet/internal/encoding/boolean_decoder.go [hunk 5]
```diff
@@ -109,3 +114,76 @@ func (dec *PlainBooleanDecoder) DecodeSpaced(out []bool, nullCount int, validBit
...
+	var (
+		buf [1024]uint64
+		n   = max
+	)
+
+	for n > 0 {
+		batch := shared_utils.MinInt(len(buf), n)
+		decoded := dec.rleDec.GetBatch(buf[:batch])
+		if decoded != batch {
+			return max - n, io.ErrUnexpectedEOF
```
Comment (pitrou) [inline go/parquet/internal/encoding/boolean_decoder.go:162]: Is there a point in returning `max - n` here? What is the caller supposed to do with it?
(note you aren't actually writing out the decoded values, so I assume the decoded bytes are lost, which means the decoder can't be used anymore afterwards)

File: go/parquet/internal/encoding/boolean_decoder.go [hunk 6]
```diff
@@ -109,3 +114,76 @@ func (dec *PlainBooleanDecoder) DecodeSpaced(out []bool, nullCount int, validBit
...
+	}
+	return nil
+}
+
+func (dec *RleBooleanDecoder) Decode(out []bool) (int, error) {
+	max := shared_utils.MinInt(len(out), dec.nvals)
+
+	var (
+		buf [1024]uint64
+		n   = max
```
Comment (pitrou) [inline go/parquet/internal/encoding/boolean_decoder.go:155]: I'm curious, what is the rationale for using `var` vs. `:=`? Is there a well-known guideline for this?

**Review by pitrou — CHANGES_REQUESTED** [review]
Should there be a higher-level roundtrip test?

Also, can you add a file read test from `data/rle_boolean_encoding.parquet`?

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 1 above)
Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:141]: Seems C++ do the same here...Though we can check equality `nbytes == uint32(len(data)-4)`  here and use ` data[4:(4 + nbytes)]` here.

File: go/parquet/internal/encoding/boolean_decoder.go [hunk 7]
```diff
@@ -109,3 +114,76 @@ func (dec *PlainBooleanDecoder) DecodeSpaced(out []bool, nullCount int, validBit
...
+	)
+
+	for n > 0 {
+		batch := shared_utils.MinInt(len(buf), n)
+		decoded := dec.rleDec.GetBatch(buf[:batch])
+		if decoded != batch {
```
Comment (mapleFU) [inline go/parquet/internal/encoding/boolean_decoder.go:161]: Should `dec.nvals` dec in this branch?

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 1 above)
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:141]: I don't think we need to as it would be implied given that `nbytes` == `len(data)`

File: go/parquet/internal/encoding/boolean_encoder.go [hunk 8]
```diff
@@ -87,3 +89,53 @@ func (enc *PlainBooleanEncoder) FlushValues() (Buffer, error) {
...
+	enc.Put(bufferOut[:nvalid])
+}
+
+func (enc *RleBooleanEncoder) EstimatedDataEncodedSize() int64 {
+	const rleLengthInBytes = 4
+	return rleLengthInBytes + int64(enc.maxRleBufferSize())
+}
+
+func (enc *RleBooleanEncoder) maxRleBufferSize() int {
+	return utils.MaxBufferSize(1, len(enc.bufferedValues))
```
[the remark this answers is not in the document]
Comment (pitrou) [reply go/parquet/internal/encoding/boolean_encoder.go:119]: Not really, the C++ implementation calls `RlePreserveBufferSize` which is much more sophisticated than this (and, if I'm not mistaken, it would return `len(enc.bufferedValues) / 4` for booleans).

File: go/parquet/internal/encoding/boolean_encoder.go (hunk 4 above)
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_encoder.go:131]: It's tested thoroughly at https://github.com/apache/arrow/blob/main/go/parquet/internal/utils/bit_reader_test.go#L214

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 5 above)
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: We *are* writing out the decoded values via the loop at line 165. The input to this function is an output slice to write to and we populate it after the call to `GetBatch`. So returning `max - n` here informs the user of how many values were populated into that slice before the error was hit.

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 6 above)
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:155]: In general for me, I tend to use the following guidelines:

1. If I'm declaring a group of variables, i'll put them together into a `var` block to improve readability
2. If i'm not using a block / grouped declaration, then if I'm just using the zero-value I'll use `var`, (like declaring an array / uninitialized slice)
3. If i'm not using a block / grouped declaration, I'll generally use `:=` if I'm initializing it to a particular value. 

Otherwise it's generally a purely aesthetic decision of code style

File: go/parquet/internal/encoding/boolean_decoder.go [hunk 9]
```diff
@@ -109,3 +114,76 @@ func (dec *PlainBooleanDecoder) DecodeSpaced(out []bool, nullCount int, validBit
...
+
+func (dec *RleBooleanDecoder) DecodeSpaced(out []bool, nullCount int, validBits []byte, validBitsOffset int64) (int, error) {
+	if nullCount > 0 {
+		toRead := len(out) - nullCount
+		valuesRead, err := dec.Decode(out[:toRead])
+		if err != nil {
+			return 0, err
+		}
+		if valuesRead != toRead {
+			return valuesRead, xerrors.New("parquet: rle boolean decoder: number of values / definition levels read did not match")
```
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:184]: at the time I originally wrote the parquet code, `xerrors` was used for particular benefits of wrapping and otherwise that weren't available in the stdlib. Since then, all the features of `xerrors` have been folded into the go stdlib and there really isn't a reason to use it anymore, I intend to phase it out as I make changes to the code. So I'm going to fix this to just use `errors`, it was my mistake to propagate `xerrors` here so thanks for catching it.

File: go/parquet/internal/encoding/boolean_encoder.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_encoder.go:119]: `RlePreserveBufferSize` is implemented as `MaxBufferSize(bit_width, num_values) + MinBufferSize(bit_width)` I just skipped the middle `RlePreserveBufferSize` here, though I should add the `+ MinBufferSize(1)` here so I will.

File: go/parquet/internal/encoding/boolean_encoder.go [hunk 10]
```diff
@@ -87,3 +89,53 @@ func (enc *PlainBooleanEncoder) FlushValues() (Buffer, error) {
...
+
+	encoder := utils.NewRleEncoder(enc.sink, 1)
+	for _, v := range enc.bufferedValues {
+		if v {
+			encoder.Put(1)
+		} else {
+			encoder.Put(0)
+		}
+	}
+	n := encoder.Flush()
```
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_encoder.go:136]: added

File: go/parquet/internal/encoding/boolean_encoder.go [hunk 11]
```diff
@@ -87,3 +89,53 @@ func (enc *PlainBooleanEncoder) FlushValues() (Buffer, error) {
...
+	return utils.MaxBufferSize(1, len(enc.bufferedValues))
+}
+
+func (enc *RleBooleanEncoder) FlushValues() (Buffer, error) {
+	const rleLengthInBytes = 4
+	rleBufferSizeMax := enc.maxRleBufferSize()
+	enc.sink.SetOffset(rleLengthInBytes)
+	enc.sink.Reserve(rleBufferSizeMax)
+
+	encoder := utils.NewRleEncoder(enc.sink, 1)
```
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_encoder.go]: better?

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 5 above)
Comment (pitrou) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: But `dec.rleDec.GetBatch` has consumed some input and decoded some bytes that are just lost in `buf`, right?

File: go/parquet/internal/encoding/boolean_encoder.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (pitrou) [reply go/parquet/internal/encoding/boolean_encoder.go]: Are you saying that `utils.MaxBufferSize` is a RLE-specific utility? The name is not really informative...

File: go/parquet/internal/encoding/boolean_encoder.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (pitrou) [reply go/parquet/internal/encoding/boolean_encoder.go]: Definitely!

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 5 above)
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: Correct. After receiving an error, a given decoder should not continue to be used, but we return the number of successfully output values so that a caller knows what values are there before the error was encountered.

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 7 above)
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:161]: in theory the return of the error would indicate that the decoder should not be used any further, so I don't know if we necessarily need to decode `dec.nvals` but it also wouldn't be wrong to do so.

**Comment by kou** [comment]
@zeroshade Could you open a new issue for boolean RLE support?

File: go/parquet/internal/encoding/boolean_encoder.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_encoder.go]: renamed the functions

File: go/parquet/internal/encoding/encoding_test.go [hunk 12]
```diff
@@ -363,6 +363,16 @@ func (b *BaseEncodingTestSuite) TestBasicRoundTrip() {
 	b.checkRoundTrip(parquet.Encodings.Plain)
 }
 
+func (b *BaseEncodingTestSuite) TestRleBooleanEncodingRoundTrip() {
+	switch b.typ {
+	case reflect.TypeOf(true):
+		b.initData(2000, 200)
```
[the remark this answers is not in the document]
Comment (zeroshade) [reply go/parquet/internal/encoding/encoding_test.go:369]: Added to the `TestSpacedRoundTrip` case which will test with different probabilities of null values

**Comment by zeroshade** [comment]
@pitrou I don't think we need a higher level roundtrip test than the tests we currently have and use for this.

As for an individual file, we've confirmed that the updated `parquet-testing` files use the RLE encoding for boolean columns, so I believe i need to add a separate test for that particular file. Thoughts?

**Comment by zeroshade** [comment]
I'd like to get this in relatively soon as all CI for go that runs the parquet tests is going to fail on the main branch until this is merged

**Comment by pitrou** [comment]
> As for an individual file, we've confirmed that the updated `parquet-testing` files use the RLE encoding for boolean columns, so I believe i need to add a separate test for that particular file.

Yes.

**Comment by zeroshade** [comment]
@pitrou added the test for the rle_boolean_encoding.parquet file

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 5 above)
Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: > We are writing out the decoded values via the loop at line 165. The input to this function is an output slice to write to and we populate it after the call to GetBatch. So returning max - n here informs the caller of how many values were populated into that slice before the error was hit.

No, `max` is not the real maximum of the underlying data. For rep-def existing scenerio, it means "rep-def" size, rather than the actual size. So it may greater than existing value.

**Comment by mapleFU** [comment]
LGTM beside the syntax here: https://github.com/apache/arrow/pull/38367/files#r1375773113

Don't know if this is expected.

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 5 above)
Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: > No, max is not the real maximum of the underlying data. For rep-def existing scenerio, it means "rep-def" size, rather than the actual size. So it may greater than existing value. (At least this is the case in C++)

this is a level above where we are here. This is *solely* the value decoder. In this function `max` is the maximum number of *values* that are decoded by a single call to this function (i.e. the minimum of the length of the output slice and the number of values left to decode). 

The handling of rep and def levels is taken care of a level above this by the actual page reader / column chunk reader, which determines how many physical values it wants to read from the decoder. The intent of this function is that the return value is the *number of physical values populated into the output slice*.

File: go/parquet/file/file_reader_test.go [hunk 13]
```diff
@@ -385,3 +387,56 @@ func TestDeltaLengthByteArrayPackingWithNulls(t *testing.T) {
...
+		false, true, true, false, false, true, true,
+		true, false, false, true, true, false, false,
+		true, true, true, false, true, true, false,
+		true, true, false, false, true, true, true,
+	}
+	expectedNulls := []int{2, 15, 23, 38, 48, 60}
+
+	for _, v := range expectedNulls {
+		assert.Zero(t, defLvls[v])
+	}
```
Comment (pitrou) [inline go/parquet/file/file_reader_test.go:439]: Is there a way to assert that the other `defLvls` are equal to one? I assume you have developed helpers for that.

File: go/parquet/internal/encoding/encoding_test.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (pitrou) [reply go/parquet/internal/encoding/encoding_test.go:369]: Great, thank you!

**Review by pitrou — APPROVED** [review]
LGTM. Just one testing but you may ignore it if you prefer.

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 5 above)
Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:162]:
```go
func (dec *RleBooleanDecoder) SetData(nvals int, data []byte) error {
	dec.nvals = nvals


func (dec *RleBooleanDecoder) Decode(out []bool) (int, error) {
	max := shared_utils.MinInt(len(out), dec.nvals)
```


I totally agree your response. What I mean is that, during `SetData`, the `nvals` is `max-levels`. So in `Decode`,  `shared_utils.MinInt(len(out), dec.nvals)` would be more than existing value.

File: go/parquet/file/file_reader_test.go (hunk 13 above)
Comment (zeroshade) [reply go/parquet/file/file_reader_test.go]: updated test to confirm other values are 1

File: go/parquet/internal/encoding/boolean_decoder.go (hunk 5 above)
Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: .i.e

For:

```
nonnull: [false, false, false, false]
```

Decode(5) with length 10 will get `4, nil`

For 

```
nullable: [false, false, false, false, null]
```

Decode(5) will get `4, err`

Would this happens?

Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: No, that wouldn't happen because parquet doesn't include nulls in the underlying data. If the data is 

```
nullable: [false, false, false, false, null]`
```

Then the *physical data in the file* is just `[false, false, false, false]` and the def levels would have `[1, 1, 1, 1, 0]`.

Decode(5) would still get `4, nil` because only 4 *physical values* were decoded. This scenario is also tested in the unit tests.

Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: I know your meaning, but the problem is that, when we get a page. The `num_values` is including the nulls. ( see https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L533  ). So when:

```
nullable: [false, false, false, false, null]
```

The data size is `4`. But the `dec.nvals` is 5.

Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: This wouldn't matter without using raw-decode api. Because RecordReader will handing `Decode` well. But it's still make the syntax a bit inconsistent

Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: Hmm, you have a point though I think that would be a greater issue to think about attempting to fix. 

For DataPageV2Header it contains the number of nulls so we can easily handle changing `dec.nvals` to the correct number, but for DataPageV1 you have a point that *technically* this might be slightly off or is at least a bug waiting to happen that should be addressed.

Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: Yeah, lets create an issue for that. I think user would not easily touch it because we always suggest using RecordReader, right?

Comment (zeroshade) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: or going through the ColumnChunkReader which has similar correct handling. We don't actually expose the raw decoder api for users to access at all.

Comment (mapleFU) [reply go/parquet/internal/encoding/boolean_decoder.go:162]: Aha that's right.
