### PR TITLE
GH-39737: [Release][Docs] Update post release documentation task

### LINKED ISSUE #39737: [Website][Docs] index page shows wrong warning bar at top when 15.0 is selected
When version 15.0 is selected, a warning at the top says that the selected version is `0.14.0`, and prompts to switch.

https://arrow.apache.org/docs/index.html

image

### Component(s)

Documentation

### PR DESCRIPTION
**Pull request by AlenkaF**
This PR updates the `dev/release/post-08-docs.sh` task so that

- `DOCUMENTATION_OPTIONS.theme_switcher_version_match` changes from `""` to `"{previous_version}"` 
- `DOCUMENTATION_OPTIONS.show_version_warning_banner` changes from `false` to `true`

for the documentation that is moved to a subfolder when a new major release is done.
* Closes: #39737

### CODE REVIEW

File: dev/release/post-08-docs.sh [hunk 1]
```diff
@@ -84,6 +84,12 @@ if [ "$is_major_release" = "yes" ] ; then
   previous_series=${previous_version%.*}
   mv docs_temp docs/${previous_series}
 fi
+# Update DOCUMENTATION_OPTIONS.theme_switcher_version_match and
+# DOCUMENTATION_OPTIONS.show_version_warning_banner
+cd docs/${previous_version}
+find ./ -type f -exec sed -i "s/DOCUMENTATION_OPTIONS.theme_switcher_version_match = '';/DOCUMENTATION_OPTIONS.theme_switcher_version_match = '${previous_version}';/g" {} \;
```
[the remark this answers is not in the document]
Comment (AlenkaF) [reply dev/release/post-08-docs.sh:90]: Oh, didn't know that. Thank you for pointing it out!

If I understand correctly, all the `.html` files will first be copied (backed-up) to `*.bak` files and then the original files (not copied `*.bak` files) will be corrected if needed? And after substituting we delete the backed up files?

Hope this will not cause an issue in the time to finish the task (lots of html files!)?

**Review by kou — APPROVED** [review]
+1

Just to confirm, did you try this change?

FYI: You can use dry-run by `PUSH=0 dev/release/post-08-docs.sh VERSION PREVIOUS_VERSION`.

**Comment by AlenkaF** [comment]
No didn't try, had no idea how to :) Will do as you suggest, thank you!

And if it looks good locally, I will go ahead and merge.

**Comment by AlenkaF** [comment]
@kou, can the post release tasks be run (or dry-run) on MacOS?

**Comment by kou** [comment]
Yes. It should work on macOS. Because a release manager may use macOS.

Did you get any error?

**Comment by AlenkaF** [comment]
Yes, sorry:

```
alenkafrim@Alenkas-MacBook-Pro arrow % PUSH=0 dev/release/post-08-docs.sh 15.0.0 14.0.0             
~/repos/arrow-site ~/repos/arrow
dev/release/post-08-docs.sh: line 48: nproc: command not found
error: switch `j' requires a value
```

**Comment by kou** [comment]
Oh, could you try the following?

```diff
diff --git a/dev/release/post-08-docs.sh b/dev/release/post-08-docs.sh
index f18f7d10c7..a7529fdb2f 100755
--- a/dev/release/post-08-docs.sh
+++ b/dev/release/post-08-docs.sh
@@ -45,7 +45,16 @@ esac
 
 pushd "${ARROW_SITE_DIR}"
 source "${SOURCE_DIR}/git-vars.sh"
-git fetch --all --prune --tags --force -j$(nproc)
+n_cpus=1
+case $(uname) in
+  Linux)
+    n_cpus=$(nproc)
+    ;;
+  Darwin)
+    n_cpus=$(sysctl -n hw.logicalcpu)
+    ;;
+esac
+git fetch --all --prune --tags --force -j${n_cpus}
 git checkout .
 git checkout ${DEFAULT_BRANCH}
 git clean -d -f -x
```

**Comment by AlenkaF** [comment]
The suggested change fixes the issue 👍
Will add it as a commit to this PR if you agree.

I am dealing with next error currently:

```
alenkafrim@Alenkas-MacBook-Pro arrow % PUSH=0 dev/release/post-08-docs.sh 15.0.0 14.0.0 
~/repos/arrow-site ~/repos/arrow
Fetching origin
Fetching apache
Enter passphrase for key '/Users/alenkafrim/.ssh/id_ed25519': 
Updated 242 paths from the index
error: Your local changes to the following files would be overwritten by checkout:
        docs/1.0/_sources/python/generated/pyarrow.Array.rst.txt
.
.
.
Aborting
```

Tried adding a fresh clone of `arrow-site` to see if that helps. Still waiting on this step (looks like it's stuck):

```
alenkafrim@Alenkas-MacBook-Pro arrow % PUSH=0 dev/release/post-08-docs.sh 15.0.0 14.0.0 
~/repos/arrow-site ~/repos/arrow
Fetching origin
Fetching apache
Enter passphrase for key '/Users/alenkafrim/.ssh/id_ed25519': 

```

**Comment by kou** [comment]
Hmm. Could you enable trace log by `PUSH=0 bash -x dev/release/post-08-docs.sh 15.0.0 14.0.0`?

**Comment by AlenkaF** [comment]
Sure. It still just hangs. Something with my connection to GitHub I guess?

```
(pyarrow-dev) alenkafrim@Alenkas-MacBook-Pro arrow % PUSH=0 bash -x dev/release/post-08-docs.sh 15.0.0 14.0.0
+ set -e
+ set -u
+++ dirname dev/release/post-08-docs.sh
++ cd dev/release
++ pwd
+ SOURCE_DIR=/Users/alenkafrim/repos/arrow/dev/release
+ ARROW_DIR=/Users/alenkafrim/repos/arrow/dev/release/../..
+ : /Users/alenkafrim/repos/arrow/dev/release/../../../arrow-site
+ '[' 2 -ne 2 ']'
+ version=15.0.0
+ previous_version=14.0.0
+ release_tag=apache-arrow-15.0.0
+ branch_name=release-docs-15.0.0
+ case "${version}" in
+ is_major_release=yes
+ pushd /Users/alenkafrim/repos/arrow/dev/release/../../../arrow-site
~/repos/arrow-site ~/repos/arrow
+ source /Users/alenkafrim/repos/arrow/dev/release/git-vars.sh
+++ git rev-parse --abbrev-ref origin/HEAD
+++ sed s@origin/@@
++ DEFAULT_BRANCH=master
+ n_cpus=1
+ case $(uname) in
++ uname
++ sysctl -n hw.logicalcpu
+ n_cpus=8
+ git fetch --all --prune --tags --force -j8
Fetching origin
Fetching apache
Enter passphrase for key '/Users/alenkafrim/.ssh/id_ed25519': 
```

**Comment by kou** [comment]
Ah, you need to enter your passphrase for `/Users/alenkafrim/.ssh/id_ed25519`. Did you enter it?

**Comment by AlenkaF** [comment]
Yes, I did. First time it worked, now it gets stuck every time ...

**Comment by AlenkaF** [comment]
Ha, I tried hitting enter again (twice that is) and got:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
could not fetch 'origin' (exit code: 128)
From github.com:apache/arrow-site
   1c75ee2aac8..fb0b8437439  asf-site   -> apache/asf-site
   87135b28d69..2dc7804b653  main       -> apache/main
```

I just started using ssh key with github so need to check why it is not working. Sorry for the spam!

**Comment by kou** [comment]
No problem. :-)
You may want to use ssh-agent or something to avoid entering passphrase multiple times.

File: dev/release/post-08-docs.sh [hunk 2]
```diff
@@ -84,6 +84,18 @@ if [ "$is_major_release" = "yes" ] ; then
   previous_series=${previous_version%.*}
   mv docs_temp docs/${previous_series}
 fi
+# Update DOCUMENTATION_OPTIONS.theme_switcher_version_match and
```
Comment (raulcd) [inline dev/release/post-08-docs.sh:87]: I would keep doing a single commit for updating the documentation and another for the banner, in case a review is necessary is much easier to do.

```suggestion
git add docs
git commit -m "[Website] Update documentations for ${version}"

# Update DOCUMENTATION_OPTIONS.theme_switcher_version_match and
```

File: dev/release/post-08-docs.sh [hunk 3]
```diff
@@ -84,6 +84,18 @@ if [ "$is_major_release" = "yes" ] ; then
...
+# DOCUMENTATION_OPTIONS.show_version_warning_banner
+pushd docs/${previous_version}
```
Comment (raulcd) [inline dev/release/post-08-docs.sh:89]: This is `previous_series` as we move the old docs to `14.0` instead of `14.0.0`
```suggestion
pushd docs/${previous_series}
```

File: dev/release/post-08-docs.sh [hunk 4]
```diff
@@ -84,6 +84,18 @@ if [ "$is_major_release" = "yes" ] ; then
...
+  -type f \
+  -exec \
+    sed -i.bak \
+      -e "s/DOCUMENTATION_OPTIONS.theme_switcher_version_match = '';/DOCUMENTATION_OPTIONS.theme_switcher_version_match = '${previous_version}';/g" \
+      -e "s/DOCUMENTATION_OPTIONS.show_version_warning_banner = false/DOCUMENTATION_OPTIONS.show_version_warning_banner = true/g" \
+      {} \;
+find ./ -name '*.bak' -delete
+popd
 git add docs
 git commit -m "[Website] Update documentations for ${version}"
```
Comment (raulcd) [inline dev/release/post-08-docs.sh:100]:
```suggestion
git add docs/${previous_series}
git commit -m "[Website] Update warning banner for ${previous_series}"
```

**Review by raulcd — COMMENTED** [review]
I have tested locally and there is one change required (`previous_series` instead of `previous_version`) and a couple minor changes in order to split the commits in two so it's easier if we require to review them.

**Review by raulcd — APPROVED** [review]
Tested locally with `PUSH=0` and it works as expected!

**Review by kou — APPROVED** [review]
+1
