### PR TITLE
GH-34843: [R] Fix R build failed caused by Acero refactor

### LINKED ISSUE #34843: [R] Windows R build fails
### Describe the bug, including details regarding any error messages, version, and platform.

An issue with build R on windows is introduced by #34711:

https://github.com/apache/arrow/pull/34711#issuecomment-1492971506

### Component(s)

R

### PR DESCRIPTION
**Pull request by icexelloss**
### Rationale for this change
There was an issue with window R build introduced by this PR:
https://github.com/apache/arrow/pull/34711

### What changes are included in this PR?
Many changes to the build files

### Are these changes tested?
crossbow builds

### Are there any user-facing changes?

* Closes: #34843

### CODE REVIEW

**Comment by icexelloss** [comment]
@github-actions crossbow submit -g r -g cpp

**Comment by icexelloss** [comment]
@github-actions crossbow submit -g r -g cpp

**Comment by icexelloss** [comment]
@github-actions crossbow submit -g r -g cpp

**Comment by icexelloss** [comment]
For the mac build: https://github.com/ursacomputing/crossbow/actions/runs/4596858239/jobs/8118844443

I noticed "ARROW_ACERO" is not on from log on 
(L815)
```
==> Installing apache-arrow-static --HEAD
```

(L900)
```
==> cmake ../cpp -DCMAKE_INSTALL_PREFIX=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/build-apache-arrow-static/Cellar/apache-arrow-static/HEAD-0c234be -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -DARROW_BUILD_SHARED=OFF -DARROW_BUILD_UTILITIES=ON -DARROW_COMPUTE=ON -DARROW_CSV=ON -DARROW_DATASET=ON -DARROW_FILESYSTEM=ON -DARROW_GCS=ON -DARROW_JEMALLOC=ON -DARROW_JSON=ON -DARROW_MIMALLOC=ON -DARROW_PARQUET=ON -DARROW_S3=ON -DARROW_VERBOSE_THIRDPARTY_BUILD=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_BZ2=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_ZSTD=ON -DLZ4_HOME=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/build-apache-arrow-static/opt/lz4 -DPARQUET_BUILD_EXECUTABLES=ON -DTHRIFT_HOME=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/build-apache-arrow-static/opt/thrift
```

But I have yet to figure out where is the macOS build file for this.

**Comment by icexelloss** [comment]
@assignUser per comments here: https://github.com/apache/arrow/pull/34844#issuecomment-1494455625

I am not too familiar with the build system - do you by chance know where the build script for "R on mac" is? (Or knows who might know that)?

**Comment by assignUser** [comment]
Yes they are in `dev/tasks/homebrew-formulae` there are multiple once for homebrew and autpbrew (the shadow version of homebrew for use on CRAN/EOL macOS)

**Comment by icexelloss** [comment]
@github-actions crossbow submit -g r -g cpp

**Comment by icexelloss** [comment]
Thanks @assignUser! Sorry to bother u with another question, looks like my attempt to fix window build is unsuccessful after passing (-larrow_acero) to the linking option. I suspect that the Arrow C++ library is not build with Acero in the window R build. Do you by any chance knows which file controls the Arrow C++ build flag in the "windows R build?

**Comment by icexelloss** [comment]
cc @westonpace - add u as collaborator to my repo - feel free to push

**Comment by assignUser** [comment]
@icexelloss it looks like you need to add  these changes to `ci/scripts/r_windows_build.sh` and `ci/scripts/PKGBUIL`

**Comment by westonpace** [comment]
These jobs are incredibly long running :astonished: .  In the meantime I verified that the `test-alpine-linux-cpp` failure is unrelated and have a fix proposed in https://github.com/apache/arrow/pull/34870.

**Comment by thisisnic** [comment]
Linting CI failure should be fixable by running `./lint.sh --fix` from the R directory

**Comment by icexelloss** [comment]
@github-actions crossbow submit test-r-minimal-build

**Comment by westonpace** [comment]
@icexelloss I've created a PR into your branch.  Let me know if you'd rather I just push it.  With those changes I can get the minimal build to pass.

**Comment by icexelloss** [comment]
> @icexelloss I've created a PR into your branch. Let me know if you'd rather I just push it. With those changes I can get the minimal build to pass.

@westonpace feel free to push directly to my branch in case I am not around to merge it.

**Comment by icexelloss** [comment]
@github-actions crossbow submit test-r-minimal-build

**Comment by westonpace** [comment]
@github-actions crossbow submit -g r -g cpp

**Comment by westonpace** [comment]
@github-actions crossbow submit homebrew-r-autobrew

**Comment by westonpace** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by westonpace** [comment]
@assignUser @kou do one of you want to do a quick sanity check?  Or maybe @thisisnic or @paleolimbot for R.  I think this is ready to go.  There are some open questions in https://github.com/apache/arrow/issues/34887 but I think we can merge this to unblock the tests and then have discussion in #34887 if we want to change anything.

File: dev/tasks/homebrew-formulae/apache-arrow.rb [hunk 1]
```diff
@@ -72,6 +72,7 @@ def install
     # link against system libc++ instead of llvm provided libc++
     ENV.remove "HOMEBREW_LIBRARY_PATHS", Formula["llvm"].opt_lib
     args = %W[
+      -DARROW_ACERO=ON
```
Comment (kou) [inline dev/tasks/homebrew-formulae/apache-arrow.rb:75]: Do we need this?
`ARROW_DATASET=ON` must enable `ARROW_ACERO` automatically: https://github.com/apache/arrow/blob/ee42b908f5102fe8c73b5e84b58b155e49ada747/cpp/cmake_modules/DefineOptions.cmake#L308-L313

File: dev/tasks/homebrew-formulae/autobrew/apache-arrow-static.rb [hunk 2]
```diff
@@ -53,6 +53,7 @@ def install
     args = %W[
       -DARROW_BUILD_SHARED=OFF
       -DARROW_BUILD_UTILITIES=ON
+      -DARROW_ACERO=ON
```
Comment (kou) [inline dev/tasks/homebrew-formulae/autobrew/apache-arrow-static.rb:56]: ditto.

File: dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb [hunk 3]
```diff
@@ -44,6 +44,7 @@ def install
     args = %W[
       -DARROW_BUILD_SHARED=OFF
       -DARROW_BUILD_UTILITIES=ON
+      -DARROW_ACERO=ON
```
Comment (kou) [inline dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb:47]: ditto.

File: r/inst/build_arrow_static.sh [hunk 4]
```diff
@@ -55,6 +55,7 @@ ${CMAKE} -DARROW_BOOST_USE_SHARED=OFF \
     -DARROW_BUILD_TESTS=OFF \
     -DARROW_BUILD_SHARED=OFF \
     -DARROW_BUILD_STATIC=ON \
+    -DARROW_ACERO=${ARROW_ACERO:-$ARROW_DEFAULT_PARAM} \
```
Comment (kou) [inline r/inst/build_arrow_static.sh:58]: How about using `ON` as the default value because `ARROW_DATASET` uses `ON` as the default value?

```suggestion
    -DARROW_ACERO=${ARROW_ACERO:-ON} \
```

File: r/tools/autobrew [hunk 5]
```diff
@@ -62,7 +62,7 @@ fi
 # Hardcode this for my custom autobrew build
 rm -f $BREWDIR/lib/*.dylib
 AWS_LIBS="-laws-cpp-sdk-config -laws-cpp-sdk-transfer -laws-cpp-sdk-identity-management -laws-cpp-sdk-cognito-identity -laws-cpp-sdk-sts -laws-cpp-sdk-s3 -laws-cpp-sdk-core -laws-c-event-stream -laws-checksums -laws-c-common -laws-crt-cpp -laws-c-io -laws-c-s3 -laws-c-auth -laws-c-http -laws-c-cal -laws-c-compression -laws-c-mqtt -lpthread -lcurl"
-PKG_LIBS="-lparquet -larrow_dataset -larrow -larrow_bundled_dependencies -lthrift -lbrotlienc-static -lbrotlidec-static -lbrotlicommon-static -llz4 -lsnappy -lzstd $AWS_LIBS"
+PKG_LIBS="-lparquet -larrow_dataset -larrow_acero -larrow -larrow_bundled_dependencies -lthrift -lbrotlienc-static -lbrotlidec-static -lbrotlicommon-static -llz4 -lsnappy -lzstd $AWS_LIBS"
```
Comment (kou) [inline r/tools/autobrew:65]:
```suggestion
PKG_LIBS="-larrow_dataset -larrow_acero -lparquet -larrow -larrow_bundled_dependencies -lthrift -lbrotlienc-static -lbrotlidec-static -lbrotlicommon-static -llz4 -lsnappy -lzstd $AWS_LIBS"
```

**Review by paleolimbot — APPROVED** [review]
Thank you for tackling this!

These changes look good to me. I'll add a note on the issue you opened as well...it was sort of an undocumented pitfall that you couldn't build the Arrow R package against Arrow C++ without compute and it's the right call to deal with it separately.

File: dev/tasks/homebrew-formulae/apache-arrow.rb (hunk 1 above)
Comment (westonpace) [reply dev/tasks/homebrew-formulae/apache-arrow.rb:75]: I'm not sure what the guidelines are.  R uses Acero directly, in addition to transitively through datasets.  So if R decided to stop using datasets then it would still need the acero dependency.  However, if we want to leave it out so things are concise then it should work.  I am fine either way.

File: r/inst/build_arrow_static.sh (hunk 4 above)
Comment (westonpace) [reply r/inst/build_arrow_static.sh:58]: That is the main question in https://github.com/apache/arrow/issues/34887

`ARROW_DEFAULT_PARAM=ON` unless `LIBARROW_MINIMAL` is set.  If I change this to `ON` then there will be no testing where this is off.

However, your point is valid.  It would not make sense for `ARROW_DATASET` to be `ON` and `ARROW_ACERO` to be `OFF`.  I will change this back to `ON` and we can fix the testing as part of #34887 if we want to support this.

**Comment by westonpace** [comment]
@github-actions crossbow submit test-r-minimal-build

**Review by assignUser — APPROVED** [review]
+1 merging this to unblock the tests Thanks working on this!

**Comment by icexelloss** [comment]
@github-actions crossbow submit test-r-minimal-build r-binary-packages homebrew-r-autobrew

**Comment by assignUser** [comment]
I'll merge this to get things going again!

File: dev/tasks/homebrew-formulae/apache-arrow.rb (hunk 1 above)
Comment (kou) [reply dev/tasks/homebrew-formulae/apache-arrow.rb:75]: I see. Thanks.

For `dev/tasks/homebrew-formulae/apache-arrow.rb`, this is a file for Homebrew's CI. (We should sync with https://github.com/Homebrew/homebrew-core/blob/master/Formula/apache-arrow.rb .) This is not only for R. In general, Homebrew enables all features as much as possible. So I think that we don't need to assume that we may disable only `ARROW_DATASET` in this file. (We should omit redundant `-DARROW_ACERO=ON`.)

For `dev/tasks/homebrew-formulae/autobrew/`, they are only for R. So I think that your point is valid.

**Comment by nealrichardson** [comment]
👍  @thisisnic @assignUser reminder that these changes will need to be upstreamed to autobrew at CRAN release time (fyi @jeroen)
