### PR TITLE
GH-48241: [Python] Scalar inferencing doesn't infer UUID

### LINKED ISSUE #48241: [Python] Scalar inferencing doesn't infer UUID
### Describe the bug, including details regarding any error messages, version, and platform.

```
>>> import uuid
>>> pa.scalar(uuid.uuid4())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/scalar.pxi", line 1673, in pyarrow.lib.scalar
    chunked = GetResultValue(ConvertPySequence(value, None, options, pool))
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
    return check_status(status)
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
    raise convert_status(status)
pyarrow.lib.ArrowInvalid: Could not convert UUID('69db4352-8da4-425b-bb36-0b2b35953f32') with type UUID: did not recognize Python value type when inferring an Arrow data type
>>> pa.scalar(uuid.uuid4().bytes, type=pa.uuid())
<pyarrow.UuidScalar: UUID('30897c0a-f649-4155-800a-ed6581f9c08f')>
>>> pa.scalar(uuid.uuid4().bytes, type=pa.uuid()).as_py()
UUID('f96615a8-dee4-4379-803d-a067225a166f')
>>>
```
But seems like it should be supported, since as_py for UUIDScalar returns it.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by tadeja**
### Rationale for this change
This closes #48241, #44224 and #43855.
Currently uuid.UUID objects are not inferred/converted automatically in PyArrow, requiring users to explicitly specify the type.

### What changes are included in this PR?
Adding support for Python's uuid.UUID objects in PyArrow's type inference and conversion.

### Are these changes tested?
Yes, added test_uuid_scalar_from_python() and test_uuid_array_from_python() in `test_extension.py`.

### Are there any user-facing changes?
Users can now pass Python uuid.UUID objects directly to PyArrow functions like pa.scalar() and pa.array() without specifying the type;
```python
import uuid
import pyarrow as pa

pa.scalar(uuid.uuid4())
``` 
<pyarrow.UuidScalar: UUID('958174b9-3a5c-4cdd-8fc5-d51a2fc55784')>
```python
pa.array([uuid.uuid4()])
```
 <pyarrow.lib.UuidArray object at 0x1217725f0>
[
  73611FD81F764A209C8B9CDBADDA1F53
]
* GitHub Issue: #48241

### CODE REVIEW

**Comment by tadeja** [comment]
@AlenkaF Would you recommend any good place to document this UUID change? - I see @amoeba indicated the need for documentation in his draft pull request #44242.
ӇƛƤƤƳ_ƝЄƜ_ƳЄƛƦ:)

**Comment by AlenkaF** [comment]
Happy New Year! ❤️ 

I would suggest adding the documentation to the [Extending PyArrow page](https://arrow.apache.org/docs/python/extending_types.html#canonical-extension-types) under the **Canonical extension types** section as a separate subsection next to [Fixed size tensor](https://arrow.apache.org/docs/python/extending_types.html#fixed-size-tensor) one.

**Comment by tadeja** [comment]
@AlenkaF, @rok do you have the chance to review this one - should enable multiple UUID use-cases.

File: python/pyarrow/src/arrow/python/helpers.cc [hunk 1]
```diff
@@ -296,6 +296,67 @@ bool PyFloat_IsNaN(PyObject* obj) {
...
+}
+#else
+void InitUuidStaticData() {
+  if (uuid_static_initialized) {
+    return;
+  }
+  GetUuidStaticSymbols();
+  uuid_static_initialized = true;
+}
+#endif
```
Comment (rok) [inline python/pyarrow/src/arrow/python/helpers.cc]: Perhaps we could use `std::call_once` for both cases here?

File: python/pyarrow/src/arrow/python/python_to_arrow.cc [hunk 2]
```diff
@@ -512,7 +513,12 @@ class PyValue {
 
   static Status Convert(const FixedSizeBinaryType* type, const O&, I obj,
                         PyBytesView& view) {
-    ARROW_RETURN_NOT_OK(view.ParseString(obj));
+    // Check if obj is a uuid.UUID instance
+    if (type->byte_width() == 16 && internal::IsPyUuid(obj)) {
```
Comment (rok) [inline python/pyarrow/src/arrow/python/python_to_arrow.cc]: A nit: it seems `uuid.UUID` can't have other bitwidths, so we don't really need the `type->byte_width() == 16` check.

**Review by rok — APPROVED** [review]
Looks good to me. Two minor nits.

File: python/pyarrow/src/arrow/python/helpers.cc (hunk 1 above)
Comment (tadeja) [reply python/pyarrow/src/arrow/python/helpers.cc]: Probably not as this part is based on Pandas section with past fixes to specifically avoid the C++ lock - see past comments [here](https://github.com/tadeja/arrow/blame/d4522cb649616c6f03068f954d2eacc4813754e4/python/pyarrow/src/arrow/python/helpers.cc#L360) and [here](https://github.com/tadeja/arrow/blame/d4522cb649616c6f03068f954d2eacc4813754e4/python/pyarrow/src/arrow/python/helpers.cc#L436).
Current UUID change already includes comment about `std::call_once` [higher up](https://github.com/apache/arrow/pull/48727/changes/3e889fd4c9775bf6726c930b81d314a775e9f12a#diff-1d716e04aaef2cef726c7c6cac5c4ff77b4597a0b362ee55fb9fc42c48e6a09bR300).

Comment (rok) [reply python/pyarrow/src/arrow/python/helpers.cc]: I see! Perhaps add this [permalink](https://github.com/tadeja/arrow/blob/934554d6e72146d854341ce61e6d1197b6695794/python/pyarrow/src/arrow/python/helpers.cc#L369-L383) then? Or just indicate this is happening in a comment.

File: python/pyarrow/src/arrow/python/python_to_arrow.cc (hunk 2 above)
Comment (rok) [reply python/pyarrow/src/arrow/python/python_to_arrow.cc]: I hope this doesn't have performance implications :).

File: python/pyarrow/src/arrow/python/helpers.cc [hunk 3]
```diff
@@ -296,6 +296,67 @@ bool PyFloat_IsNaN(PyObject* obj) {
...
+void GetUuidStaticSymbols() {
+  OwnedRef uuid_module;
+
+  // Import uuid module
+  Status s = ImportModule("uuid", &uuid_module);
+  if (!s.ok()) {
+    return;
+  }
+
+#ifndef Py_GIL_DISABLED
```
Comment (rok) [inline python/pyarrow/src/arrow/python/helpers.cc:318]:
```suggestion
#ifndef Py_GIL_DISABLED
  // Since ImportModule can release the GIL, another thread could have
  // already initialized the static data.
```

File: python/pyarrow/src/arrow/python/helpers.cc [hunk 4]
```diff
@@ -296,6 +296,67 @@ bool PyFloat_IsNaN(PyObject* obj) {
...
+    uuid_UUID = ref.obj();
+  }
+}
+
+#ifdef Py_GIL_DISABLED
+void InitUuidStaticData() {
+  std::call_once(uuid_static_initialized, GetUuidStaticSymbols);
+}
+#else
+void InitUuidStaticData() {
```
Comment (rok) [inline python/pyarrow/src/arrow/python/helpers.cc]:
```suggestion
void InitUuidStaticData() {
  // NOTE: This is called with the GIL held.  We needn't (and shouldn't,
  // to avoid deadlocks) use an additional C++ lock (ARROW-10519).
```

**Review by rok — APPROVED** [review]
Looks good. Just minor suggestions for comments.

**Comment by rok** [comment]
@pitrou could you take a look at this PR? Especially cython change could use your expertise.

**Comment by tadeja** [comment]
@pitrou, any wise thoughts on changes here?

File: python/pyarrow/src/arrow/python/helpers.cc [hunk 5]
```diff
@@ -296,6 +296,71 @@ bool PyFloat_IsNaN(PyObject* obj) {
...
+  // NOTE: This is called with the GIL held.  We needn't (and shouldn't,
+  // to avoid deadlocks) use an additional C++ lock (ARROW-10519).
+  if (uuid_static_initialized) {
+    return;
+  }
+  GetUuidStaticSymbols();
+  uuid_static_initialized = true;
+}
+#endif
```
Comment (pitrou) [inline python/pyarrow/src/arrow/python/helpers.cc:335]: We're duplicating code here between different module imports. It would be really nice to write something like this:
```c++
struct UuidModuleData {
  PyObject* UUID_class = nullptr;
};

UuidModuleData* InitUuidStaticData() {
  static ModuleOnceRunner runner("uuid");
  return runner.Run([&](OwnedRef module) -> UuidModuleData {
    UuidModuleData data;
    OwnedRef ref;
    if (ImportFromModule(module.obj(), "UUID", &ref).ok()) {
      data.UUID_class = ref.obj();
    }
    return data;
  });
}
```

```c++
struct ModuleOnceRunner {
  std::string module_name;
#ifdef Py_GIL_DISABLED
  std::once_flag initialized;
#else
  bool initialized = false;
#endif

  template <typename Func>
  auto Run(Func&& func) -> decltype(func(OwnedRef()) {
    using RetType = decltype(func(OwnedRef());
    RetType ret{};
    auto wrapper_func = [&]() {
      OwnerRef module;
      if (ImportModule("uuid", &module).ok()) {
        ret = func(std::move(module));
      }
    };
#ifdef Py_GIL_DISABLED
    std::call_once(initialized, wrapper_func);
#else
    if (!initialized) {
      initialized = true;
      wrapper_func();
    }
#endif
    return ret;
  };
};

```

I think @rok can help.

File: python/pyarrow/src/arrow/python/helpers.cc [hunk 6]
```diff
@@ -296,6 +296,71 @@ bool PyFloat_IsNaN(PyObject* obj) {
...
+
+bool IsPyUuid(PyObject* obj) {
+  InitUuidStaticData();
+  if (!uuid_UUID) return false;
+  int result = PyObject_IsInstance(obj, uuid_UUID);
+  if (result < 0) {
+    PyErr_Clear();
+    return false;
+  }
+  return result == 1;
```
Comment (pitrou) [inline python/pyarrow/src/arrow/python/helpers.cc]:
```suggestion
  return result != 0;
```

File: python/pyarrow/src/arrow/python/python_to_arrow.cc [hunk 7]
```diff
@@ -1268,16 +1274,24 @@ Result<std::shared_ptr<ChunkedArray>> ConvertPySequence(PyObject* obj, PyObject*
...
+      extension_type = options.type;
+      options.type = checked_cast<const ExtensionType&>(*options.type).storage_type();
+    }
   } else {
     options.strict = true;
   }
   ARROW_DCHECK_GE(size, 0);
 
   ARROW_ASSIGN_OR_RAISE(auto converter, (MakeConverter<PyConverter, PyConverterTrait>(
                                             options.type, options, pool)));
```
Comment (pitrou) [inline python/pyarrow/src/arrow/python/python_to_arrow.cc:1293]: Does `MakeConverter` support extension types here? I see that we only unwrap the extension type in the inference path above.

File: python/pyarrow/tests/test_extension_type.py [hunk 8]
```diff
@@ -1399,6 +1399,91 @@ def test_uuid_extension():
...
+    import uuid
+
+    class BadUuid(uuid.UUID):
+        @property
+        def bytes(self):
+            raise RuntimeError("broken")
+
+    bad = BadUuid(uuid.uuid4().hex)
+    with pytest.raises(RuntimeError, match="broken"):
+        pa.array([bad], type=pa.uuid())
```
Comment (rok) [inline python/pyarrow/tests/test_extension_type.py:1480]: Similar as above:
```suggestion
    with pytest.raises(RuntimeError, match="broken"):
        pa.array([bad], type=pa.uuid())
    with pytest.raises(RuntimeError, match="broken"):
        pa.scalar(bad, type=pa.uuid())
    with pytest.raises(RuntimeError, match="broken"):
        pa.array([bad])
    with pytest.raises(RuntimeError, match="broken"):
        pa.scalar(bad)
```

File: python/pyarrow/src/arrow/python/helpers.cc (hunk 5 above)
Comment (rok) [reply python/pyarrow/src/arrow/python/helpers.cc:335]: I think this is now in place, albeit slightly modified. Looks good to me.

File: python/pyarrow/src/arrow/python/python_to_arrow.cc (hunk 7 above)
Comment (rok) [reply python/pyarrow/src/arrow/python/python_to_arrow.cc:1293]: I think Python will always unwrap to storage type before sending to `MakeConverter`. Except if it was an extension of extension?

File: python/pyarrow/tests/test_extension_type.py [hunk 9]
```diff
@@ -1399,6 +1399,91 @@ def test_uuid_extension():
...
+    class BadUuid(uuid.UUID):
+        @property
+        def bytes(self):
+            return bytes_value
+
+    bad = BadUuid(uuid.uuid4().hex)
+    with pytest.raises(exc_type, match=match):
+        pa.array([bad], type=pa.uuid())
+    with pytest.raises(exc_type, match=match):
+        pa.scalar(bad, type=pa.uuid())
```
Comment (rok) [inline python/pyarrow/tests/test_extension_type.py:1465]: Perhaps overly careful:
```suggestion
    with pytest.raises(exc_type, match=match):
        pa.array([bad], type=pa.uuid())
    with pytest.raises(exc_type, match=match):
        pa.scalar(bad, type=pa.uuid())
    with pytest.raises(exc_type, match=match):
        pa.array([bad])
    with pytest.raises(exc_type, match=match):
        pa.scalar(bad)
```

**Review by rok — APPROVED** [review]
I think all code paths should be well covered now. Suggesting some defensive tests.

File: python/pyarrow/src/arrow/python/python_to_arrow.cc (hunk 7 above)
Comment (rok) [reply python/pyarrow/src/arrow/python/python_to_arrow.cc:1293]: [Unwrap](https://github.com/tadeja/arrow/blob/1be3445282d20adb53b26f925a463f919bf13919/python/pyarrow/array.pxi#L241) and [convert](https://github.com/tadeja/arrow/blob/1be3445282d20adb53b26f925a463f919bf13919/python/pyarrow/array.pxi#L369).

**Comment by rok** [comment]
I did a pass @pitrou and I think this is ready now. Could you do another one as well?

File: docs/source/python/extending_types.rst
Comment (pitrou) [inline docs/source/python/extending_types.rst:472]: Side note: I think this section doesn't belong in an "extending PyArrow" document, since this is not about the user extending anything. Can we open a separate issue to deal with that?

File: python/pyarrow/tests/test_extension_type.py [hunk 10]
```diff
@@ -1399,6 +1399,91 @@ def test_uuid_extension():
     assert isinstance(array[0], pa.UuidScalar)
 
 
+def test_uuid_scalar_from_python():
+    import uuid
```
Comment (pitrou) [inline python/pyarrow/tests/test_extension_type.py]: Nit: can probably this at top level? This is not an optional module.

**Review by pitrou — COMMENTED** [review]
Mostly LGTM, thanks a lot

File: python/pyarrow/tests/test_extension_type.py (hunk 10 above)
Comment (tadeja) [reply python/pyarrow/tests/test_extension_type.py]: Indeed, thanks! I've cleaned redundant imports as there's already [from uuid import uuid4, UUID](https://github.com/tadeja/arrow/blob/6e1fdd041c23fca05395ac2dbd8e002d8e1551af/python/pyarrow/tests/test_extension_type.py#L23) at the top.

File: docs/source/python/extending_types.rst
Comment (tadeja) [reply docs/source/python/extending_types.rst:472]: Ah, I was about to open an issue but found past discussion about this here: https://github.com/apache/arrow/pull/34957#pullrequestreview-1380631147 and existing open issue #35064
