### PR TITLE
GH-34023: [Docs] Version warning about viewing old docs doesn't work for versions >= 10

### LINKED ISSUE #34023: [Docs] Version warning about viewing old docs doesn't work for versions >= 10
Currently, if viewing older docs (eg https://arrow.apache.org/docs/9.0/python/index.html), you get a warning about that you are not viewing the latest docs. However, now that the newest "old" docs (those that are stored in a version/ subdirectory) is 10.0, that doesn't seem to work for this version (eg https://arrow.apache.org/docs/10.0/python/index.html doesn't show the warning)

My first guess is that it's caused by a bump in number of characters in the major version number (7, 8, 9 etc -> 10), and that this if check no longer works as expected because of that:

https://github.com/apache/arrow/blob/177a0d4400e61f44dbd045ce05150bba28dd1d74/docs/source/_static/versionwarning.js#L104-L105

### PR DESCRIPTION
**Pull request by AlenkaF**
### Rationale for this change
Due to a bump in number of characters in the major version number (7, 8, 9 etc -> 10) the check for versions in `versionwarning.js` no longer works as expected.

### What changes are included in this PR?
Update of the checks in `versionwarning.js` file.

### Are these changes tested?
Yes, on the apache/arrow-site PR:

- https://github.com/apache/arrow-site/pull/312
- https://arrow.apache.org/docs/10.0/index.html

### Are there any user-facing changes?
No.
* Closes: #34023

### CODE REVIEW

File: docs/source/_static/versionwarning.js [hunk 1]
```diff
@@ -30,6 +30,7 @@
             // Path of the page
             var location_array = location.pathname.split('/');
             var versionPath = location_array[2];
+            var versionNumber = Number(versionPath.match(/^\d+/))
```
Comment (raulcd) [inline docs/source/_static/versionwarning.js:33]: This is `majorVersionNumber` from the `major.minor.patch` format, right? A really minor nit I would probably rename it so it does not cause confusion.

**Review by raulcd — APPROVED** [review]
Thanks @AlenkaF ! LGTM just a really minor nit

File: docs/source/_static/versionwarning.js (hunk 1 above)
Comment (AlenkaF) [reply docs/source/_static/versionwarning.js:33]: Yes, correct. It is the major part of the version format. Will rename 👍
