### PR TITLE
GH-14923: [C++][Parquet] Fix DELTA_BINARY_PACKED problem on reading the last block with malford bit-width

### LINKED ISSUE #14923: [C++][Parquet] DeltaBitPackDecoder expects all miniblock bitwidths to be present for the last block
### Describe the bug, including details regarding any error messages, version, and platform.

This is a follow-up to [this discussion](https://github.com/apache/arrow/pull/14191#discussion_r1042303944).
Arrow's reader is not compliant with the spec, and requires all miniblock bitwidth values of the last block even if not necessary. This forces arrow writer to write all miniblock bitwidths to be able to roundtrip which is not a big issue. However it does mean Arrow reader would not be able to read bitpacked buffer written by another parquet writer that does not write all miniblock bitwidths.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
Problem is mentioned here: https://github.com/apache/arrow/issues/14923

This patch fixes that issue. And the code is a bit complex.
- Rename variables, since original name is confusing for me. 
  - `block_initialized_` -> `first_block_initialized_`, because it's a mask that indicates that if the first block in page is initialized.
  - `total_value_count_` -> `total_values_remaining_`. Because it's not `total values within a page`, it means `remaing values to be decoded within a page`
  - `values_count_current_mini_block_` -> `values_remaining_current_mini_block_`, ditto
- Add variables
  - `total_value_count_`: the total value numbers within a page.
- Change Syntax
  -  Change `InitBlock()` to `InitBlock()` and `InitMiniBlock`
- Implemention, most logic is in `InitBlock()` and `InitMiniBlock`
- Testing. Thanks @rok. I use a page within 65 values with bitwidth `32 32 165 165`.

And personally, I use the code here for testing:

```c++
   for (uint32_t i = num_miniblocks; i < mini_blocks_per_block_; i++) {
-    bit_width_data[i] = 0;
+    //    bit_width_data[i] = 0;
+    bit_width_data[i] = static_cast<uint8_t>(random());
   }
```

The code works well in both debug and release mode.

* Closes: #14923

### CODE REVIEW

**Comment by mapleFU** [comment]
@pitrou @rok PTAL (^_^)

**Comment by mapleFU** [comment]
Wait, it's still some bug, sorry. Let me fix it

**Comment by mapleFU** [comment]
I change the code to 

```c++
    for (uint32_t j = values_current_mini_block; j < values_per_mini_block_; j++) {
      bit_writer_.PutValue(random(), bit_width);
    }
```

And run multiple times with ASAN, test still passed. Though I don't know how to mock in release, seens we cannot use gmock when `DeltaBitPackEncoder` is always in `.cc` file.

**Comment by mapleFU** [comment]
@pitrou @rok PTAL (^_^) I think I fix it, and leaving some comments.

**Comment by mapleFU** [comment]
Well, it's a bit weird.

```c++
TEST_F(DeltaBitPackEncoding, MalfordMiniblockBitWidth) {
  std::shared_ptr<ColumnDescriptor> descr_ = ExampleDescr<Int32Type>();
  auto decoder = MakeTypedDecoder<Int32Type>(Encoding::DELTA_BINARY_PACKED, descr_.get());
  using c_type = parquet::Int32Type::c_type;

  unsigned char good_data[] = "\200\001\004A\237\224\316\362\r\242\220\203-  ";
  int encode_buffer_size = 273;
  int num_values = 65;
  std::vector<uint8_t> output_bytes = std::vector<uint8_t>(num_values * sizeof(c_type));
  auto decode_buf = reinterpret_cast<c_type*>(output_bytes.data());
  decoder->SetData(num_values, &good_data[0], encode_buffer_size);
```

@rok How do you build the `good_data`? Seems `encode_buffer_size = 273` is too large for `good_data`, and in `Release` mode, memcpy will reach the stack guard, and raise an asan exception.

**Comment by mapleFU** [comment]
Well, seems that both buffer is 273B. And I need to padding the `good_data`. @rok would you mind add the generating method of these two datas? Seems leaving a bit-string here is confusing.

**Comment by mapleFU** [comment]
This time it failed because unpack32_avx512 meets an ASAN issue. Maybe I need to know how input data is generated and do some adjustions. Go to sleep now.

**Comment by mapleFU** [comment]
(By the way, my PC using AMD's CPU, which I can't reproduce unpack32_avx512 problem. So it's important for me to know how test data generated...)

**Comment by rok** [comment]
Hey @mapleFU, sorry for not replying earlier, I am preoccupied with the Jira->Github migration :).
I generated the data by applying [this diff](https://github.com/apache/arrow/issues/14923#issuecomment-1366657071) and stepping through GDB in CLion probably up [to here](https://github.com/apache/arrow/blob/6c35c4ae4124a5012234ac485ea1ee22f2a5259a/cpp/src/parquet/encoding_test.cc#L1340) and copied the data. I am on AMD Ryzen 7 5700G, Ubuntu 22.02.
I can try getting the data string in some other way as GDB could be interfering somehow?

**Comment by mapleFU** [comment]
Sorry for being crazy and at you for multiple times. I finally make clear the meaning of them, and put the meaning in `encoding_test.cc`:

```
  // Both good_data and bad_data is a DELTA_BINARY_PACKED INT32 Page with 65 values.
  // For needed miniblocks, there bit-widths are all 32.
  // There bit-widths for unneeded miniblocks are different:
  // * good_data's unneeded bit-width is 0.
  // * bad_data's unneeded bit-width is 165.
```

**Comment by mapleFU** [comment]
Test regenerated, and representing using Hex.

**Comment by mapleFU** [comment]
@pitrou @wjones127 Mind take a look? Since I made lots of naming changes( described https://github.com/apache/arrow/pull/15241#issue-1523751523 ), and update a Hex testing format. Don't know whether it's ok.

File: cpp/src/parquet/encoding.cc [hunk 1]
```diff
@@ -2542,10 +2558,21 @@ class DeltaBitPackDecoder : public DecoderImpl, virtual public TypedDecoder<DTyp
   uint32_t values_per_block_;
   uint32_t mini_blocks_per_block_;
   uint32_t values_per_mini_block_;
-  uint32_t values_current_mini_block_;
   uint32_t total_value_count_;
 
-  bool block_initialized_;
+  uint32_t total_value_remaining_;
```
Comment (pitrou) [inline cpp/src/parquet/encoding.cc:2563]:
```suggestion
  uint32_t total_values_remaining_;
```

File: cpp/src/parquet/encoding.cc [hunk 2]
```diff
@@ -2542,10 +2558,21 @@ class DeltaBitPackDecoder : public DecoderImpl, virtual public TypedDecoder<DTyp
...
+  // Remaining values in current mini block. If the current block is the last mini block,
+  // values_remaining_current_mini_block_ may greater than total_value_remaining_.
+  uint32_t values_remaining_current_mini_block_;
+
+  // If the page doesn't contain any block, `first_block_initialized_` will
+  // always be false. Otherwise, it will be true when first block initialized.
+  bool first_block_initialized_;
+  // The sum of values up to current block.
```
Comment (pitrou) [inline cpp/src/parquet/encoding.cc:2571]:
```suggestion
  // The number of values up to current mini-block (non including).
```

File: cpp/src/parquet/encoding_test.cc [hunk 3]
```diff
@@ -1427,5 +1429,66 @@ TYPED_TEST(TestDeltaBitPackEncoding, BasicRoundTrip) {
...
+  auto decoder = MakeTypedDecoder<Int32Type>(Encoding::DELTA_BINARY_PACKED, descr.get());
+  using c_type = parquet::Int32Type::c_type;
+
+  int encode_buffer_size = 274;
+  int num_values = 65;
+  c_type* decode_buf = nullptr;
+  std::vector<uint8_t> output_bytes;
+  int values_decoded = 0;
+
+  // Both good_data and bad_data is a DELTA_BINARY_PACKED INT32 Page with 65 values.
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1443]: Both of these data are "good", neither is "bad".

File: cpp/src/parquet/encoding_test.cc [hunk 4]
```diff
@@ -1427,5 +1429,66 @@ TYPED_TEST(TestDeltaBitPackEncoding, BasicRoundTrip) {
...
+  // For needed miniblocks, there bit-widths are all 32.
+  // There bit-widths for unneeded miniblocks are different:
+  // * good_data's unneeded bit-width is 0.
+  // * bad_data's unneeded bit-width is 165.
+  // We use Hex to represent good_data and bad_data.
+  {
+    char good_data_hex[] =
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1450]: Should use `std::string` or `std::string_view` to have length information.

File: cpp/src/parquet/encoding_test.cc [hunk 5]
```diff
@@ -1427,5 +1429,66 @@ TYPED_TEST(TestDeltaBitPackEncoding, BasicRoundTrip) {
...
+        "80010441BDA08DB708A488C0F1012020000089F79E53946D93CA242D48B21478591FDE6E4855CC03"
+        "7024A4E8E56E1D20687C8BFB4DE880E73CE2E49E873BEB0B1DAD0E0169C7951C411CA76AD949D8ED"
+        "FD9E07A485DF4410B4486253A6280335BB87494B7D61E40A8D487731BBC83A37E1E8EE2F5431150C"
+        "F46D7224B3C7C271AC3220F2C6663289427E1CE3B00F8C34D5DDA845664AF36F56ACF6FED2339911"
+        "7AB54F6667A80EA78D08DC61B4262CE28960B46B2D93785ED9933175A910415B50B30E9889C70ECD"
+        "84C8856531E78B4E05B2AB27B1233E4BAB722869D785F5B8B1049955EFE200000000C6C2201E1836"
+        "C0579B202A6A7395C761044AD151D5CEE992CBBA5AE937E54F29D28F86CC0627B9D1";
+    unsigned char good_data[274];
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1458]: Please don't hard code values like that. Instead you can use a `std::string` or a `std::vector<uint8_t>`.

File: cpp/src/parquet/encoding_test.cc [hunk 6]
```diff
@@ -1427,5 +1429,66 @@ TYPED_TEST(TestDeltaBitPackEncoding, BasicRoundTrip) {
...
+    for (int i = 0; i < 274; ++i) {
+      auto s = ::arrow::ParseHexValue(&good_data_hex[i * 2], &good_data[i]);
+      ASSERT_TRUE(s.ok());
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1461]: ASSERT_OK

File: cpp/src/parquet/encoding_test.cc [hunk 7]
```diff
@@ -1427,5 +1429,66 @@ TYPED_TEST(TestDeltaBitPackEncoding, BasicRoundTrip) {
...
+
+  {
+    char bad_data_hex[] =
+        "80010441BDA08DB708A488C0F1012020A5A589F79E53946D93CA242D48B21478591FDE6E4855CC03"
+        "7024A4E8E56E1D20687C8BFB4DE880E73CE2E49E873BEB0B1DAD0E0169C7951C411CA76AD949D8ED"
+        "FD9E07A485DF4410B4486253A6280335BB87494B7D61E40A8D487731BBC83A37E1E8EE2F5431150C"
+        "F46D7224B3C7C271AC3220F2C6663289427E1CE3B00F8C34D5DDA845664AF36F56ACF6FED2339911"
+        "7AB54F6667A80EA78D08DC61B4262CE28960B46B2D93785ED9933175A910415B50B30E9889C70ECD"
+        "84C8856531E78B4E05B2AB27B1233E4BAB722869D785F5B8B1049955EFE200000000C6C2201E1836"
+        "C0579B202A6A7395C761044AD151D5CEE992CBBA5AE937E54F29D28F86CC0627B9D1";
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1479]: Is this different from the other data above? IIUC, the trailing bytes should be different, but they seem identical.

File: cpp/src/parquet/encoding_test.cc [hunk 8]
```diff
@@ -1427,5 +1429,66 @@ TYPED_TEST(TestDeltaBitPackEncoding, BasicRoundTrip) {
...
+    unsigned char bad_data[274];
+    for (int i = 0; i < 274; ++i) {
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1481]: Please don't copy/paste code while it could trivially be factored out.

**Review by pitrou — COMMENTED** [review]
It's not obvious to me why you're making so many changes to the decoder. Was the suggested fix in https://github.com/apache/arrow/issues/14923#issuecomment-1369902019 not sufficient?

File: cpp/src/parquet/encoding_test.cc (hunk 7 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding_test.cc:1479]: Other data is equal. (In fact, they're all generated by `this->Execute(65, 1)` )

**Comment by mapleFU** [comment]
In most case, https://github.com/apache/arrow/issues/14923#issuecomment-1369902019 is right. But we may have the case above:

```c++
if (total_value_count_ != 1) {
  InitBlock();
}
```

Here handling it would becoming trickey. And update so much code because some name really makes me feel confusing. But maybe I can make it simplier

**Comment by pitrou** [comment]
I don't understand, what would be tricky?

**Comment by mapleFU** [comment]
Let's go back to the original code:

```c++
      if (ARROW_PREDICT_FALSE(values_remaining_current_mini_block_ == 0)) {
        if (ARROW_PREDICT_FALSE(!first_block_initialized_)) {
          buffer[i++] = last_value_;
          DCHECK_EQ(i, 1);  // we're at the beginning of the page
          DCHECK_EQ(values_num_up_to_current_mini_block_, 0);
          values_num_up_to_current_mini_block_ = 1;
          if (ARROW_PREDICT_FALSE(i == max_values)) {
            // When block is uninitialized and i reaches max_values we have two
            // different possibilities:
            // 1. total_value_count_ == 1, which means that the page may have only
            // one value (encoded in the header), and we should not initialize
            // any block.
            // 2. total_value_count_ != 1, which means we should initialize the
            // incoming block for subsequent reads.
            if (total_value_count_ != 1) {
              InitBlock();
            }
            break;
          }
          InitBlock();
        }
```

And assume the page has 33 values:
1. `total_value_count_ == 1`, call `InitBlock`
2. `current_num_values = 0`, read block one, change to 32.
3. `current_num_values = 32`, read block one, change to 64.

But here, it should be `1` firstly.

**Comment by pitrou** [comment]
Why not, but can you add a test that would reproduce the issue?

**Comment by mapleFU** [comment]
> Why not, but can you add a test that would reproduce the issue?

Yes, but adding test case is trickey... I cannot use `gmock` to mock writing non-zero-values...

**Comment by pitrou** [comment]
> Sure, it's easy to write that in my personal develop enviroment. But I cannot submit these "mock" code to the codebase, which make writing unit test a bit more trickey.

You can write the code that mutates the encoder output directly in the unit test. Schematically:
```c++
std::vector<uint8_t> encoded = ...;
for (auto i = encoded.length() - 33; i < encoded.length() - 2; ++i) {
  encoded[i] = 0xFF;
}
```

> By the way, do you think using Hex to represent binary is ok?

That works, yes.

**Comment by mapleFU** [comment]
Well, I found that rok's testing data already covers that case:

And assume the page has 65 values and 32 values per-mini-block:

```
total_value_count_ == 1, call InitBlock
current_num_values = 0, read block one, change to 32.
current_num_values = 32, read block one, change to 64.
current_num_values = 64, read block one, change to 96.
```

When changing to `InitBlock(is_init_page)`, I meet another trickey problem:

```c++
while (i < max_values) {
  ... decode values from miniblocks
}
total_values_remaining_ -= max_values;
```

So, `InitBlock()` should have a counter, or it should decrease `total_values_remaining_` per loop.

I think there are some fixing:
1. current my implemention is ok here, because it maintains a `current miniblock counter`
2. The change like below:

```c++
while (i < max_values) {
  ... decode values from miniblocks, when i increase, decrease remaining
  ... or passing i into InitBlock
}
CHECK_EQ(i, max_values);
```

@pitrou what's your optionion here? Maintaining a `current value counter` or `passing i into InitBlock`, like `InitBlock(int prefix_counter)`, or decrease `remaining counter` every time we inc?

(Personally I'd like to call `InitBlock(int prefix_counter)`, but I'd like to know what's your opinion)

**Comment by mapleFU** [comment]
I change my implemention to use `i` counter. If you have some ideas you can edit my patch directly https://github.com/apache/arrow/pull/15241#issue-1523751523

**Comment by mapleFU** [comment]
(By the way, no idea why Travis CI failed...)

**Comment by pitrou** [comment]
Ok, I was not satisfied with the test and implementation, so I ended up rewriting them.

**Comment by mapleFU** [comment]
I update the description here: https://github.com/apache/arrow/pull/15241#issue-1523751523

If you like, you can edit it for your new changes

**Review by rok — APPROVED** [review]
This looks great. I didn't realize ULEB128 values were byte aligned. Good to know!
Thanks for doing this @mapleFU & @pitrou and sorry I was not able to contribute more.

**Comment by pitrou** [comment]
Hmm, interestingly, there are test failures...

**Comment by mapleFU** [comment]
> Hmm, interestingly, there are test failures...

@pitrou I think I got why it failed, when read batches data, previously, we will point miniblock to a "bad" miniblock, and never read from it. But now, our code may `InitMiniBlock` for last "bad" miniblock, causing the failure.

**Comment by mapleFU** [comment]
```c++
        } else {
          ++mini_block_idx_;
          if (mini_block_idx_ < mini_blocks_per_block_) {
            InitMiniBlock(delta_bit_widths_->data()[mini_block_idx_]);
          } else {
            InitBlock();
          }
        }
```

Previously, `bit_width_` will point to a "bad" width, but it will never been read. Now, `InitMiniBlock` will read it

**Comment by mapleFU** [comment]
I guess change the code like this would work:

```c++
          if (mini_block_idx_ < mini_blocks_per_block_) {
            if (i >= total_values_remaining_) {
                break;
            }
            InitMiniBlock(delta_bit_widths_->data()[mini_block_idx_]);
          } else {
            InitBlock();
          }
```

@pitrou

**Comment by mapleFU** [comment]
On my MacOs:

```
[DELTA_BINARY_PACKED] values_per_block: 128, mini_blocks_per_block: 4, total_value_count: 2, last_value: -49
Header consume 5 bytes
Block mini delta is: 83, consume bytes: 2
miniblock bitwidth: 255
miniblock bitwidth: 255
miniblock bitwidth: 255
miniblock bitwidth: 0
miniblock bitwidth consume bytes: 4
```

**Comment by pitrou** [comment]
Thanks @mapleFU !

**Comment by mapleFU** [comment]
@wjones127 Mind take a look :) ?

**Comment by mapleFU** [comment]
@pitrou would you mind merge this patch? Or I should wait @wjones127  to take a look?

**Comment by pitrou** [comment]
I'll wait a bit for @wjones127 to chime in. Otherwise I'll probably merge tomorrow.
