### PR TITLE
GH-37907: [R] Setting rosetta variable is missing

### LINKED ISSUE #37907: [R] Setting rosetta variable is missing
### Describe the bug, including details regarding any error messages, version, and platform.

Since the last release, this line is missing in /r/R/install_arrow.R. This causes the R script to fail execution

https://github.com/apache/arrow/blame/b7d2f7ffca66c868bd2fce5b3749c6caa002a7f0/r/R/install-arrow.R#L83

Proposed solution: put back this line:
`rosetta <- identical(sysname, "darwin") && identical(system("sysctl -n sysctl.proc_translated", intern = TRUE), "1")`

### Component(s)

R

### PR DESCRIPTION
**Pull request by fernandomayer**
### Rationale for this change

The latest version of `r/R/install-arrow.R`  was not working properly, since it was relying on the `on_rosetta()` function, which is not defined elsewhere. I just fixed the identification of rosetta in the script.

With the current code, the following gives an error

````r
> source("https://raw.githubusercontent.com/apache/arrow/master/r/R/install-arrow.R") 
> install_arrow()
Error in on_rosetta() : could not find function "on_rosetta"
````

### What changes are included in this PR?

It only removed the `on_rosetta()` function, which was not defined elsewhere, and reverted back to the `rosetta` object to identify if rosetta is present or not on a user's system.

### Are these changes tested?

Yes. It was tested with the current code and the proposed PR. The proposed PR works as expected.

### Are there any user-facing changes?

No.

* Closes: #37907

### CODE REVIEW

File: r/R/install-arrow.R [hunk 1]
```diff
@@ -61,6 +61,7 @@ install_arrow <- function(nightly = FALSE,
                           verbose = Sys.getenv("ARROW_R_DEV", FALSE),
                           repos = getOption("repos"),
                           ...) {
+  sysname <- tolower(Sys.info()[["sysname"]])
```
Comment (thisisnic) [inline r/R/install-arrow.R:64]:
```suggestion
```

File: r/R/install-arrow.R [hunk 2]
```diff
@@ -79,7 +80,8 @@ install_arrow <- function(nightly = FALSE,
     # On the M1, we can't use the usual autobrew, which pulls Intel dependencies
     apple_m1 <- grepl("arm-apple|aarch64.*darwin", R.Version()$platform)
     # On Rosetta, we have to build without JEMALLOC, so we also can't autobrew
-    if (on_rosetta()) {
+    rosetta <- identical(sysname, "darwin") && identical(system("sysctl -n sysctl.proc_translated", intern = TRUE), "1")
+    if (rosetta) {
```
Comment (thisisnic) [inline r/R/install-arrow.R:84]:
```suggestion
    rosetta <- on_rosetta()
    if (rosetta) {
```

Another PR implemented a function `on_rosetta()` that already does these checks, so we can simplify this bit here, and remove the creation of the `sysname` variable above.

**Comment by thisisnic** [comment]
Thanks for making this PR! One small change, otherwise looks good to go :)

**Review by thisisnic — CHANGES_REQUESTED** [review]

File: r/R/install-arrow.R (hunk 2 above)
Comment (fernandomayer) [reply r/R/install-arrow.R:84]: Hi @thisisnic 

I believe that for the package this is fine. I saw that the `on_rosetta()` function was defined in `r/R/arrow-package.R` and that should work.

However, I'm thinking of the case where the user just uses the `r/R/install-arrow.R` as a standalone script, as suggested [here](https://arrow.apache.org/docs/r/articles/install.html#using-install_arrow) (as it's the way I use, for example). In this way, the `on_rosetta()` function is not found, as the script is not self-contained anymore.

So my proposal would be to just change the `in_rosetta()` function from `r/R/arrow-package.R` to `r/R/install-arrow.R`, as this would not affect the former, but it would make the latter self-contained again.

Comment (assignUser) [reply r/R/install-arrow.R]: I don't see the standalone use being suggested, maybe we need to clarify the docs? As I understand it `install_arrow` is for use when you have the arrow package installed but want to do one of the following:
```
You have arrow installed and want to upgrade to a different version
You want to try to reinstall and fix issues with Linux C++ binaries
You want to install a development build
```
@thisisnic please correct me if my assessment on that is wrong?

Comment (thisisnic) [reply r/R/install-arrow.R]: @assignUser It's here: https://arrow.apache.org/docs/r/articles/install.html?q=install_arrow#using-install_arrow

> Although this function is part of the arrow package, it is also available as a standalone script, so you can access it without first installing the package:

In the case of "You want to install a development build", folks may not already have arrow installed.  

On a different note, there have been other PRs in this area of the codebase merged recently, so this PR may need a rebase to see how the changes affect it, and what needs doing.

**Comment by assignUser** [comment]
@thisisnic should we merge this before the release?

**Comment by thisisnic** [comment]
@jonkeane You most recently worked on the code that this PR touches and I'm not sure where is best for this function - I don't suppose you'd mind giving this a quick look over?

**Comment by thisisnic** [comment]
> @thisisnic should we merge this before the release?

Yes, but it'll need a final change before merging

File: r/R/install-arrow.R (hunk 2 above)
Comment (jonkeane) [reply r/R/install-arrow.R]: > So my proposal would be to just change the on_rosetta() function from r/R/arrow-package.R to r/R/install-arrow.R, as this would not affect the former, but it would make the latter self-contained again.

This is a good catch, I'm working on a review, but overall I'm pro moving this function to `install-arrow.R` so that it remains self-contained. Thank you for catching it!

>  In this way, the on_rosetta() function is not found, as the script is not self-contained anymore.

We don't have to do this here, but we should at least make an issue that we should write a test that tests that the script remains self-contained. It would have caught this bug, for example!

**Review by jonkeane — CHANGES_REQUESTED** [review]
Thanks @fernandomayer for the catch + the fix. Like I mentioned in a comment up above, I'm supportive of moving the function definition to `arrow-install.R` so that it can be self contained again.

Would you mind also moving the test for this from `test-arrow-package.R` (and delete that file since it's the only test there) and put the test in `test-install-arrow.R` ?

Thanks!

**Comment by assignUser** [comment]
It looks like this would also fix a nightly fail/cran warning: https://github.com/ursacomputing/crossbow/actions/runs/6463099167/job/17545762151#step:6:3794

**Comment by jonkeane** [comment]
I hope you don't mind that I pushed those changes requested to this branch so that we can get this in before the upcoming release.

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-install-local

**Comment by jonkeane** [comment]
Once the crossbow build is done I'm going to merge this, unless there are objections

**Comment by jonkeane** [comment]
I've also created https://github.com/apache/arrow/issues/38251 to track adding a test for this self-containedness

File: r/R/install-arrow.R [hunk 3]
```diff
@@ -267,3 +268,9 @@ wslify_path <- function(path) {
   end_path <- strsplit(path, drive_expr)[[1]][-1]
   file.path(wslified_drive, end_path)
 }
+
+on_rosetta <- function() {
+  # make sure to suppress warnings and ignore the stderr so that this is silent where proc_translated doesn't exist
+  identical(tolower(Sys.info()[["sysname"]]), "darwin") &&
+    identical(suppressWarnings(system("sysctl -n sysctl.proc_translated", intern = TRUE, ignore.stderr = TRUE)), "1")
+}
```
Comment (jonkeane) [inline r/R/install-arrow.R:276]:
```suggestion
}

```

To appease the linter

**Review by jonkeane — APPROVED** [review]

**Review by thisisnic — APPROVED** [review]

**Comment by fernandomayer** [comment]
Thanks @jonkeane and @thisisnic 

I can confirm that now the command 

```r
source("https://raw.githubusercontent.com/apache/arrow/main/r/R/install-arrow.R")
install_arrow()
```

works as expected again, as stated in the documentation https://arrow.apache.org/docs/r/articles/install.html?q=install_arrow#using-install_arrow

**Comment by jonkeane** [comment]
Thanks again @fernandomayer for the issue + PR
