### PR TITLE
GH-34106: [C++][Parquet] Fix updating page stats for WriteArrowDictionary

### LINKED ISSUE #34106: [C++][Parquet] Fix updating page statistics for WriteArrowDictionary
### Describe the bug, including details regarding any error messages, version, and platform.

Commit for this issue https://github.com/apache/arrow/issues/15042 has fixed the missing statistics, but it still has some issues. For example, if a single write has been split into more than one batch which results in several data pages, the statistics of each page is not correctly updated.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

`ColumnWriter::WriteArrowDictionary` has tried to update stats but has problem if a single write has been split into batches and more than one page is written.

### What changes are included in this PR?

Make sure every write of batch has updated the stats.

### Are these changes tested?

Add test case which fails without the fix.

### Are there any user-facing changes?

No.
* Closes: #34106

### CODE REVIEW

**Comment by wgtmac** [comment]
Converted to draft because I hit another issue: https://github.com/apache/arrow/issues/14870. The C++ parquet reader does not parse column statistics correctly here: https://github.com/apache/arrow/blob/master/cpp/src/parquet/column_reader.cc#L214
```cpp
// Extracts encoded statistics from V1 and V2 data page headers
template <typename H>
EncodedStatistics ExtractStatsFromHeader(const H& header) {
  EncodedStatistics page_statistics;
  if (!header.__isset.statistics) {
    return page_statistics;
  }
  const format::Statistics& stats = header.statistics;
  if (stats.__isset.max) {
    page_statistics.set_max(stats.max);
  }
  if (stats.__isset.min) {
    page_statistics.set_min(stats.min);
  }
  if (stats.__isset.null_count) {
    page_statistics.set_null_count(stats.null_count);
  }
  if (stats.__isset.distinct_count) {
    page_statistics.set_distinct_count(stats.distinct_count);
  }
  return page_statistics;
}

```

File: cpp/src/parquet/column_writer.cc [hunk 1]
```diff
@@ -1471,6 +1504,7 @@ Status TypedColumnWriterImpl<DType>::WriteArrowDictionary(
                       AddIfNotNull(rep_levels, offset));
     std::shared_ptr<Array> writeable_indices =
         indices->Slice(value_offset, batch_num_spaced_values);
+    update_stats(/*num_chunk_levels=*/batch_size, writeable_indices);
```
Comment (mapleFU) [inline cpp/src/parquet/column_writer.cc:1507]: Would `page_statistics_` be a nullptr here?

Comment (wgtmac) [reply cpp/src/parquet/column_writer.cc:1507]: Yes, please check: https://github.com/apache/arrow/blob/master/cpp/src/parquet/column_writer.cc#L1069

Comment (mapleFU) [reply cpp/src/parquet/column_writer.cc:1507]: Well, I think here we should:
`if (page_statistics) update_stats(/*num_chunk_levels=*/batch_size, writeable_indices);`

Comment (wgtmac) [reply cpp/src/parquet/column_writer.cc]: Good catch!

**Comment by wgtmac** [comment]
@westonpace @wjones127 Please take a look. Thanks!

File: cpp/src/parquet/column_writer.cc [hunk 2]
```diff
@@ -1484,6 +1484,39 @@ Status TypedColumnWriterImpl<DType>::WriteArrowDictionary(
...
+      PARQUET_ASSIGN_OR_THROW(
+          ::arrow::Datum referenced_dictionary_datum,
+          ::arrow::compute::Take(dictionary, referenced_indices,
+                                 ::arrow::compute::TakeOptions(/*boundscheck=*/false),
+                                 &exec_ctx));
+      referenced_dictionary = referenced_dictionary_datum.make_array();
+    }
+
+    int64_t non_null_count = chunk_indices->length() - chunk_indices->null_count();
+    page_statistics_->IncrementNullCount(num_chunk_levels - non_null_count);
```
Comment (wjones127) [inline cpp/src/parquet/column_writer.cc:1515]: Question: is the reason this isn't just set to `chunk_indices->null_count()` that the null count stats isn't meant to include cases where higher levels (parent fields) are null? Or something else?

**Review by wjones127 — APPROVED** [review]
Thanks for fixing this!

File: cpp/src/parquet/column_writer.cc (hunk 2 above)
Comment (wgtmac) [reply cpp/src/parquet/column_writer.cc:1515]: Yes. `chunk_indices->null_count()` is the null count for the current leaf only. `num_chunk_levels - non_null_count` also counts null values from ancestor (e.g. empty list is also considered as null but not included in the `chunk_indices->null_count()`).

**Comment by wgtmac** [comment]
Gentle ping @wjones127
