### PR TITLE
GH-38432: [C++][Parquet] Try to fix performance regression in the DictByteArrayDecoderImpl

### LINKED ISSUE #38432: [C++] Parquet reading performance regressions
Looking at some of the Parquet read benchmarks we have (https://conbench.ursa.dev/c-benchmarks/file-read), there are two small regressions to be observed the last months.

For example, zooming in on that time for nyctaxi_2010 with snappy compression (https://conbench.ursa.dev/benchmark-results/0653775157e07b6980005bce6e59a2ad/):

image

And for fanniemae (https://conbench.ursa.dev/benchmark-results/0653774cc429733d8000b2db91fa63fa/); here only the first bump is noticeable:

image

There are two small bumps, which I think are caused by the following two PRs, in order of the bumps:

- https://github.com/apache/arrow/pull/14341 
  This PR added a new encoding option, but so my expectation is that it shouldn't have to slow down the default (the new encoding isn't used)? (cc @rok)
- https://github.com/apache/arrow/pull/37854
  While this change is mostly useful for cloud filesystems, and could be detrimental for fast local disk, the general assumption was that this effect for local disk would not be significant, so we could simply enable it for all filesystems. But based on this benchmark it seems the impact might actually not be fully insignificant? Should we consider making the default for `pre_buffer` depend on the type of filesystem?

### LINKED ISSUE #38577: Reading parquet file behavior change from 13.0.0 to 14.0.0
### Describe the bug, including details regarding any error messages, version, and platform.

Hi,

We have a parquet that used to read fine in 13.0.0, but now I got an error when calling via `pandas.read_parquet` using 14.0.0. The relevant error is:
```
  File "/opt/venv/lib/python3.10/site-packages/pyarrow/parquet/core.py", line 3003, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,   
  File "/opt/venv/lib/python3.10/site-packages/pyarrow/parquet/core.py", line 2631, in read
    table = self._dataset.to_table(  
  File "pyarrow/_dataset.pyx", line 556, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3713, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowCapacityError: array cannot contain more than 2147483646 bytes, have 2148480400
```

Is this an intended behavior? I skimmed through the changelog but did not find this. Thanks.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Do some changes mentioned in https://github.com/apache/arrow/issues/38432

I believe this might fix https://github.com/apache/arrow/issues/38577

Problem1:

The `BinaryHelper` might call `Prepare()` and `Prepare(estimated-output-binary-length)` for data. This might because:

1. For Plain Encoding ByteArray, the `len_` is similar to the data-page size, so `Reserve` is related.
2. For Dict Encoding. The Data Page is just a RLE encoding Page, it's `len_` might didn't directly related to output-binary. 

Problem2:

`Prepare` using `::arrow::kBinaryMemoryLimit` as min-value, we should use `this->chunk_space_remaining_`.

Problem3:

`std::optional<int64_t>` is hard to optimize for some compilers

### What changes are included in this PR?

Mention the behavior of BinaryHelper. And trying to fix it.

### Are these changes tested?

No

### Are there any user-facing changes?

Regression fixes

* Closes: #38432

### CODE REVIEW

**Comment by mapleFU** [comment]
@rok @pitrou I try to figure out how the regression happened, and add comment for it. Would you mind take a look?

File: cpp/src/parquet/encoding.cc [hunk 1]
```diff
@@ -904,7 +904,12 @@ class DecoderImpl : virtual public Decoder {
 
  protected:
   explicit DecoderImpl(const ColumnDescriptor* descr, Encoding::type encoding)
-      : descr_(descr), encoding_(encoding), num_values_(0), data_(NULLPTR), len_(0) {}
+      : descr_(descr),
+        encoding_(encoding),
+        num_values_(0),
+        data_(NULLPTR),
+        len_(0),
+        type_length_(0) {}
```
Comment (rok) [inline cpp/src/parquet/encoding.cc:912]: Could you get `type_lenght` from the `ColumnDescriptor` for fixed width types? I don't remember if type is available here or not.

**Comment by rok** [comment]
Thanks for working on this @mapleFU !

**Comment by mapleFU** [comment]
@ursabot please benchmark

File: cpp/src/parquet/encoding.cc (hunk 1 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc]: Revert this :-(

This only works in FLBA, just ignore it...

File: cpp/src/parquet/encoding.cc [hunk 2]
```diff
@@ -1196,6 +1196,10 @@ struct ArrowBinaryHelper<ByteArrayType> {
         chunk_space_remaining_(::arrow::kBinaryMemoryLimit -
                                acc_->builder->value_data_length()) {}
 
+  // Prepare will Reserve the number of entries remaining in the current chunk.
```
Comment (wgtmac) [inline cpp/src/parquet/encoding.cc:1199]:
```suggestion
  // Prepare will reserve the number of entries remaining in the current chunk.
```

File: cpp/src/parquet/encoding.cc [hunk 3]
```diff
@@ -1205,6 +1209,9 @@ struct ArrowBinaryHelper<ByteArrayType> {
     return Status::OK();
   }
 
+  // If estimated_remaining_data_length is provided, it will also Reserve the estimated
```
Comment (wgtmac) [inline cpp/src/parquet/encoding.cc:1212]:
```suggestion
  // If estimated_remaining_data_length is provided, it will also reserve the estimated
```

**Review by wgtmac — APPROVED** [review]
How should we interpret the benchmark report to verify the regression is fixed?

**Comment by jorisvandenbossche** [comment]
> How should we interpret the benchmark report to verify the regression is fixed?

The problem is that the machine `ursa-i9-9960x` is currently not running (not fully sure why), and it's on this one that the affected benchmark is run (see https://github.com/apache/arrow/pull/38437#issuecomment-1782469556 in the previous PR where I linked to the relevant in the benchmark run back then)

**Comment by mapleFU** [comment]
Would you mind help re-run or trigger that running? @jorisvandenbossche 🤔

**Comment by mapleFU** [comment]
@ursabot please benchmark

**Comment by pitrou** [comment]
@mapleFU Can you please make your PR message more descriptive? It should help understand what this PR is about.

**Comment by pitrou** [comment]
Also, I don't understand why this would fix dictionary decoding, and why this would be ok for non-dictionary decoding. This lacks a serious analysis IMHO.

**Comment by mapleFU** [comment]
> Also, I don't understand why this would fix dictionary decoding, and why this would be ok for non-dictionary decoding. This lacks a serious analysis IMHO.

This is easy because:
1. `len_` is the size of `Page`'s data payload
2. `PlainByteArrayDecoder`'s `len_` is similiar to the final result(each record might have a length). But for dictionary, the `len_` might be unrelated to the ByteArray size, which could make the Program reserve unneccessary memory. Evenmore, it doesn't decrease `len_` after each decode.

**Comment by mapleFU** [comment]
oh sorry I think maybe I'm wrong 😅 I found another bad problem here.

**Comment by mapleFU** [comment]
@pitrou I've updated the comment and the description, would you mind take a look again?

File: cpp/src/parquet/encoding.cc [hunk 4]
```diff
@@ -1983,7 +1990,7 @@ class DictByteArrayDecoderImpl : public DictDecoderImpl<ByteArrayType>,
     int values_decoded = 0;
 
     ArrowBinaryHelper<ByteArrayType> helper(out, num_values);
-    RETURN_NOT_OK(helper.Prepare(len_));
+    RETURN_NOT_OK(helper.Prepare());
```
Comment (pitrou) [inline cpp/src/parquet/encoding.cc:1993]: I still don't understand why we don't want to presize here.... This can be called for non-dict decoding, right?

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1993]: right!

`len_` is page size, for dict, the page size is a RLE buffer rather than a data-buffer, so this `size_` is misleading...

Comment (pitrou) [reply cpp/src/parquet/encoding.cc:1993]: Ok, so can we distinguish between dict and non-dict decoding here?

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1993]: 🤔I'm not sure what do you mean `between dict and non-dict decoding`.

```c++
  inline void DecodeDict(TypedDecoder<Type>* dictionary) {
    dictionary_length_ = static_cast<int32_t>(dictionary->values_left());
    PARQUET_THROW_NOT_OK(dictionary_->Resize(dictionary_length_ * sizeof(T),
                                             /*shrink_to_fit=*/false));
    dictionary->Decode(reinterpret_cast<T*>(dictionary_->mutable_data()),
                       dictionary_length_);
  }

```

Do you mean decoding to Dict? Or just decoding a RLE_DICT encoding data? I think for decoing `RLE_DICT` or `DELTA_BYTE_ARRAY`, we cannot find the exactly length for the page, so I don't think it's proper to `Prepare` here...

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1993]: The Plain and `DeltaLengthByteArray` has a feature that it knows the remaining size in the page, so I think that's ok...

Comment (pitrou) [reply cpp/src/parquet/encoding.cc:1993]: Yes, I mean decoding to dict.

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1993]:
```c++
template <>
void DictDecoderImpl<ByteArrayType>::SetDict(TypedDecoder<ByteArrayType>* dictionary) {
  DecodeDict(dictionary);

  auto dict_values = reinterpret_cast<ByteArray*>(dictionary_->mutable_data());

  int total_size = 0;
  for (int i = 0; i < dictionary_length_; ++i) {
    total_size += dict_values[i].len;
  }
  PARQUET_THROW_NOT_OK(byte_array_data_->Resize(total_size,
                                                /*shrink_to_fit=*/false));
  PARQUET_THROW_NOT_OK(
      byte_array_offsets_->Resize((dictionary_length_ + 1) * sizeof(int32_t),
                                  /*shrink_to_fit=*/false));

```

I think it already handled this well :-)

Comment (pitrou) [reply cpp/src/parquet/encoding.cc:1993]: Oops, sorry! I was misreading the context...

I think we just need an additional comment here to make sure the next reader will understand this :-)

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1993]: Maybe I missed something but I should comment on what? Decoding or other?😊

Comment (pitrou) [reply cpp/src/parquet/encoding.cc:1993]: I mean comment on why we are not passing a length here.

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1999]: done!

**Review by pitrou — APPROVED** [review]
LGTM. Sorry for the misunderstandings @mapleFU !

**Comment by mapleFU** [comment]
That's ok, these decoder interface is so misleading :-|

**Comment by austin3dickey** [comment]
Unfortunately the benchmark jobs [were killed](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/builds/3715#018bf2f5-7c2e-4d5b-a48f-cf43434c5408) because Buildkite is having issues. Once [those issues](https://www.buildkitestatus.com/) are resolved maybe you could rebase and try benchmarks again? Sorry for the inconvenience.

**Comment by austin3dickey** [comment]
Actually, some of the benchmark results were successfully uploaded to Conbench before the jobs were killed. Here's a [comparison](https://conbench.ursa.dev/compare/runs/a4480f445a8a4a32806b9b040a4e4c93...68b51333397d4800b8714eb9fbf037a3/) between this PR's benchmark run and the last matching run I could find (from 2023-11-02).

I see some possible regressions, and if you order the "z-score" column the other way, some improvements. Those could be noise but maybe not? It's probably worth trying the benchmarks again.

**Comment by jorisvandenbossche** [comment]
@ursabot please benchmark

**Comment by jorisvandenbossche** [comment]
According to this linked benchmark run, the latest version of this PR might no longer improve the performance (eg https://conbench.ursa.dev/benchmark-results/0655cfefb9bc7ea180009d2cd664f22c/ is one that clearly improved on the previous PR, xref https://github.com/apache/arrow/pull/38437#issuecomment-1782469556)

**Comment by mapleFU** [comment]
Interesting, since https://github.com/apache/arrow/pull/38437#issuecomment-1782469556 is not far from our logic, let me modify some code and use ursabench to test how other code could make it slow

**Comment by mapleFU** [comment]
After gothrough the test code I know why the regression happens...

Code path:

```
pyarrow.read_table
- pyarrow ParquetFile.read
-- C++ parquet::arrow::ReadTable
--- parquet::arrow::ReadColumn for all column
```

So finally the code goes to:

```
  Status ReadColumn(int i, const std::vector<int>& row_groups, ColumnReader* reader,
                    std::shared_ptr<ChunkedArray>* out) {
    BEGIN_PARQUET_CATCH_EXCEPTIONS
    // TODO(wesm): This calculation doesn't make much sense when we have repeated
    // schema nodes
    int64_t records_to_read = 0;
    for (auto row_group : row_groups) {
      // Can throw exception
      records_to_read +=
          reader_->metadata()->RowGroup(row_group)->ColumnChunk(i)->num_values();
    }
    return reader->NextBatch(records_to_read, out);
    END_PARQUET_CATCH_EXCEPTIONS
  }
```

The size of `records_to_read` is the row-number of the file. Than it goes to `LeafReader::LoadBatch` and `LeadReader::BuildArray`.

`BuildArray` is so simple:

```
  ::arrow::Status BuildArray(int64_t length_upper_bound,
                             std::shared_ptr<::arrow::ChunkedArray>* out) final {
    *out = out_;
    return Status::OK();
  }
```

So we focus on `LoadBatch`. The underlying is `parquet::ByteArrayChunkedRecordReader`. This would use a extramly use a huge batch-size

**Comment by mapleFU** [comment]
@ursabot please benchmark

File: cpp/src/parquet/encoding.cc [hunk 5]
```diff
@@ -1196,15 +1196,22 @@ struct ArrowBinaryHelper<ByteArrayType> {
...
+  // Prepare will reserve the number of entries remaining in the current chunk.
+  // If estimated_data_length is provided, it will also reserve the estimated data length,
+  // and the caller should better call `UnsafeAppend` instead of `Append` to avoid
+  // double-checking the data length.
   Status Prepare(std::optional<int64_t> estimated_data_length = {}) {
     RETURN_NOT_OK(acc_->builder->Reserve(entries_remaining_));
     if (estimated_data_length.has_value()) {
       RETURN_NOT_OK(acc_->builder->ReserveData(
-          std::min<int64_t>(*estimated_data_length, ::arrow::kBinaryMemoryLimit)));
+          std::min<int64_t>(*estimated_data_length, this->chunk_space_remaining_)));
```
Comment (mapleFU) [inline cpp/src/parquet/encoding.cc:1207]: Using `::arrow::kBinaryMemoryLimit` is too large here.

**Comment by mapleFU** [comment]
@ursabot please benchmark

File: cpp/src/parquet/encoding.cc (hunk 5 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1207]: Also I think this might fixes https://github.com/apache/arrow/issues/38577

**Comment by mapleFU** [comment]
@pitrou Perhaps I need some help:

1. I found an extra problem here: https://github.com/apache/arrow/pull/38784#discussion_r1403570575 . This might the root cause of https://github.com/apache/arrow/issues/38577 . It reserve more data than expected
2. I use the code below to generate test data

```
>>> from pyarrow import parquet
>>> parquet.read_table("yellow_tripdata_2010-01.parquet")
>>> parquet.write_table(table, 'arrow-out.parquet')
```

When I disable `Prepare` in `DecodeArrowDenseNonNull` and `DecodeArrowDenseNonNull`, the program execute faster. The file has 14863778 rows, which means 15 row-groups. I thought that might be some reason on that but I cannot make sure. So I need some help and benchmark on that...

**Comment by mapleFU** [comment]
@ursabot please benchmark

**Comment by mapleFU** [comment]
1. https://github.com/apache/arrow/pull/38784#issuecomment-1824802225
2. https://github.com/apache/arrow/pull/38784#issuecomment-1824941921
3. https://github.com/apache/arrow/pull/38784#issuecomment-1825214663

@jorisvandenbossche Would you mind check these three results, I use different code here to check which code cause the regression...

**Comment by jorisvandenbossche** [comment]
Neither of them shows an improvement .. 
You can find the plot I am looking at by going to "full Conbench report" -> "Pull Request Run on ursa-i9-9960x at [2023-11-23 15:46:24Z](https://conbench.ursa.dev/runs/34aee21814944f278f429aaad8bbe948)" (in section "All benchmark runs analyzed:" on that page) -> "compare to baseline run from fork point commit (recommended)" -> sort on benchmark name -> find "file-read" for "compression=snappy, dataset=fanniemae_2016Q4, file_type=parquet, language=R, output_type=table" (typically around page 7)

(or if there is actually an improvement, you can also sort by "z-score" with positive values first)

For the three runs, I get those three pages:

* https://conbench.ursa.dev/compare/benchmark-results/0655f5af97857ba780005944ff57195f...0655f85d79c77f8e8000bec63a9a83ff/
* https://conbench.ursa.dev/compare/benchmark-results/0655f5adc28975398000ef0b9ea87352...0655fb3943c77f648000b1280c84716e/
* https://conbench.ursa.dev/compare/benchmark-results/0655f5adc28975398000ef0b9ea87352...065603346d0f7c1b800042fdd468a614/

I am also not fully sure the R version seems to show a much bigger slowdown than the Python version (https://conbench.ursa.dev/compare/benchmark-results/0655f5af97857ba780005944ff57195f...0655f85d79c77f8e8000bec63a9a83ff/ vs https://conbench.ursa.dev/compare/benchmark-results/0655f5263a32767a80008e5f53bf5830...0655f7d37080706a80000b9cc3264c89/), because they are both reading the same file with same compression, both into a table (so no conversion to Python pandas DataFrame or R data.frame).

**Comment by mapleFU** [comment]
Sigh, let me try a more time

**Comment by mapleFU** [comment]
@ursabot please benchmark

**Comment by jorisvandenbossche** [comment]
If you want to more easily be able to reproduce it locally, the benchmark code is not that easy to re-use, so I extracted the necessary bits in a small script:

This creates the parquet file:
<details>

```python
import pyarrow
import pyarrow.csv
import pyarrow.parquet as pq

# download https://ursa-qa.s3.amazonaws.com/fanniemae_loanperf/2016Q4.csv.gz CSV file
path = "Downloads/2016Q4.csv.gz"

schema = pyarrow.schema([
    pyarrow.field("LOAN_ID", pyarrow.string()),
    # date. Monthly reporting period
    pyarrow.field("ACT_PERIOD", pyarrow.string()),
    pyarrow.field("SERVICER", pyarrow.string()),
    pyarrow.field("ORIG_RATE", pyarrow.float64()),
    pyarrow.field("CURRENT_UPB", pyarrow.float64()),
    pyarrow.field("LOAN_AGE", pyarrow.int32()),
    pyarrow.field("REM_MONTHS", pyarrow.int32()),
    pyarrow.field("ADJ_REM_MONTHS", pyarrow.int32()),
    # maturity date
    pyarrow.field("MATR_DT", pyarrow.string()),
    # Metropolitan Statistical Area code
    pyarrow.field("MSA", pyarrow.string()),
    # Int of months, but `X` is a valid value. New versions pad with `0`/`X` to two characters
    pyarrow.field("DLQ_STATUS", pyarrow.string()),
    pyarrow.field("RELOCATION_MORTGAGE_INDICATOR", pyarrow.string()),
    # 0-padded 2 digit ints representing categorical levels, e.g. "01" -> "Prepaid or Matured"
    pyarrow.field("Zero_Bal_Code", pyarrow.string()),
    pyarrow.field("ZB_DTE", pyarrow.string()),  # date
    pyarrow.field("LAST_PAID_INSTALLMENT_DATE", pyarrow.string()),
    pyarrow.field("FORECLOSURE_DATE", pyarrow.string()),
    pyarrow.field("DISPOSITION_DATE", pyarrow.string()),
    pyarrow.field("FORECLOSURE_COSTS", pyarrow.float64()),
    pyarrow.field("PROPERTY_PRESERVATION_AND_REPAIR_COSTS", pyarrow.float64()),
    pyarrow.field("ASSET_RECOVERY_COSTS", pyarrow.float64()),
    pyarrow.field(
        "MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS", pyarrow.float64()
    ),
    pyarrow.field("ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY", pyarrow.float64()),
    pyarrow.field("NET_SALES_PROCEEDS", pyarrow.float64()),
    pyarrow.field("CREDIT_ENHANCEMENT_PROCEEDS", pyarrow.float64()),
    pyarrow.field("REPURCHASES_MAKE_WHOLE_PROCEEDS", pyarrow.float64()),
    pyarrow.field("OTHER_FORECLOSURE_PROCEEDS", pyarrow.float64()),
    pyarrow.field("NON_INTEREST_BEARING_UPB", pyarrow.float64()),
    # all null
    pyarrow.field("MI_CANCEL_FLAG", pyarrow.string()),
    pyarrow.field("RE_PROCS_FLAG", pyarrow.string()),
    # all null
    pyarrow.field("LOAN_HOLDBACK_INDICATOR", pyarrow.string()),
    pyarrow.field("SERV_IND", pyarrow.string()),
])
csv_read_options = pyarrow.csv.ReadOptions(
    autogenerate_column_names=False,
    column_names=schema.names,
)
csv_convert_options = pyarrow.csv.ConvertOptions(
    column_types=schema,
    strings_can_be_null=True,
)
csv_parse_options = pyarrow.csv.ParseOptions(delimiter="|")
table = pyarrow.csv.read_csv(
    path,
    read_options=csv_read_options,
    parse_options=csv_parse_options,
    convert_options=csv_convert_options,
)
pq.write_table(table, "fanniemae_2016Q4.parquet", compression="snappy")
```

</details>

and then it is reading that file:

```
import pyarrow.parquet as pq
pq.read_table("fanniemae_2016Q4.parquet")
```

When timing that with released versions of 13.0.0 vs 14.0.1, I do see a small but consistent difference (2.5 vs 2.9s for reading the whole file in parallel with the statement above). 

Trying to pin it down something smaller, reading a single binary (string) column for one row group in one thread:

```
In [6]: f = pq.ParquetFile("fanniemae_2016Q4.parquet")

In [7]: %timeit -n 50 f.read_row_group(0, columns=["LOAN_ID"], use_threads=False)
21.7 ms ± 359 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)
25.6 ms ± 289 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

this also gives a small but consistent difference of 21 vs 25ms.

**Comment by mapleFU** [comment]
Aha I use nycdata to testing it for a whole night in cpp...Maybe I should use that way

**Comment by mapleFU** [comment]
>  this also gives a small but consistent difference of 21 vs 25ms.

from 13.0.1 to 14.0 we also update the prefetch options

File: cpp/src/parquet/encoding.cc [hunk 6]
```diff
@@ -1983,7 +2001,10 @@ class DictByteArrayDecoderImpl : public DictDecoderImpl<ByteArrayType>,
     int values_decoded = 0;
 
     ArrowBinaryHelper<ByteArrayType> helper(out, num_values);
-    RETURN_NOT_OK(helper.Prepare(len_));
+    // The `len_` in the ByteArrayDictDecoder is the total length of the
+    // RLE/Bit-pack encoded data size, so, we cannot use `len_` to reserve
+    // space for binary data.
+    // RETURN_NOT_OK(helper.Prepare());
 
     auto dict_values = reinterpret_cast<const ByteArray*>(dictionary_->data());
```
Comment (jorisvandenbossche) [inline cpp/src/parquet/encoding.cc:2010]: A little bit below, there is a `PrepareNextInput(val.len)` (current line 1999, new line 2020), which is showing up in a profile of reading the binary column.

(now, you also already updated the implementation of `PrepareNextInput`, so that might already have addressed it on this branch. Will run my profile with this branch as well)

**Comment by jorisvandenbossche** [comment]
> from 13.0.1 to 14.0 we also update the prefetch options

Good point, which is relevant for reading the full file with `pq.read_table`. But I think for my timing of reading a single column, using `pq.ParquetFile` the `pre_buffer` option didn't change (it's still False by default)

**Comment by mapleFU** [comment]
https://conbench.ursa.dev/compare/runs/f12445ad2fb84f32a924a483ab75e0db...8015bc26c02a4f239ae20e3bed46c42f/

Did the current benchmark ok? ( I found most of them doesn't regression now)

File: cpp/src/parquet/encoding.cc (hunk 6 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:2010]: I separate the `PrepareNextInput` into two functions. And the one without length doesn't `Reserve`

**Comment by jorisvandenbossche** [comment]
Hmm, for some reason the R benchmarks didn't run in the last run (and those showed the biggest difference)

**Comment by jorisvandenbossche** [comment]
FWIW, when comparing locally this branch vs main with the example as in https://github.com/apache/arrow/pull/38784#issuecomment-1825335216, I do see a speed-up with this branch (bringing it more or less on par with 13.0.0 again). 
So I think this PR is all good! (and the actual code changes also look logical to me)

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by mapleFU** [comment]
I just finished my work, I'll do some final survey around the case.

**Comment by mapleFU** [comment]
Sigh, maybe `std::optional<int64_t>` making it hard to optimize out...

**Comment by mapleFU** [comment]
@ursabot please benchmark

**Comment by mapleFU** [comment]
@jorisvandenbossche I think problem is fixed, aha

See https://conbench.ursa.dev/compare/runs/f12445ad2fb84f32a924a483ab75e0db...8015bc26c02a4f239ae20e3bed46c42f/

I'll merge this later if no negative comments

File: cpp/src/parquet/encoding.cc (hunk 5 above)
Comment (pitrou) [reply cpp/src/parquet/encoding.cc:1207]: Does this make a practical difference? We're taking `std::min` here...

File: cpp/src/parquet/encoding.cc [hunk 7]
```diff
@@ -1196,24 +1196,40 @@ struct ArrowBinaryHelper<ByteArrayType> {
...
   }
 
+  Status PrepareNextInput(int64_t next_value_length) {
+    if (ARROW_PREDICT_FALSE(!CanFit(next_value_length))) {
+      // This element would exceed the capacity of a chunk
+      RETURN_NOT_OK(PushChunk());
+      RETURN_NOT_OK(acc_->builder->Reserve(entries_remaining_));
+    }
+    return Status::OK();
+  }
```
Comment (pitrou) [inline cpp/src/parquet/encoding.cc:1219]: What difference does it make to have a separate method?

**Comment by pitrou** [comment]
@mapleFU Please don't merge a change if you don't understand how it works.

File: cpp/src/parquet/encoding.cc (hunk 5 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1207]: No...Just a style fix.

**Comment by pitrou** [comment]
Note that @jorisvandenbossche above didn't test the same changes...

File: cpp/src/parquet/encoding.cc (hunk 5 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1207]: ( However this might never triggered, it's a bit hard to construct a boundary case like this. I just think `this->chunk_space_remaining_` should be more safety

**Comment by mapleFU** [comment]
https://github.com/apache/arrow/pull/38784#issuecomment-1825790415

@pitrou I think the critical reason is here. The compiler is hard to optimize:

```
Status PrepareNextInput(int64_t, std::optional<int64_t> = std::nullopt)
```

Another two reason is about the https://github.com/apache/arrow/issues/38577

**Comment by mapleFU** [comment]
I've try benchmark here: https://github.com/apache/arrow/pull/38784#issuecomment-1825964494

**Comment by pitrou** [comment]
> @pitrou I think the critical reason is here. The compiler is hard to optimize:

Are you able to measure a difference between those two versions of the code? Is there a micro-benchmark?

**Comment by mapleFU** [comment]
Sure, please wait for a minute

**Comment by mapleFU** [comment]
The current benchmark is out. @jorisvandenbossche would you mind take a look?

@pitrou https://godbolt.org/z/5bf1K55a5 I use same compiler-options, and the `std::optional` one seems contruct more instr in hot path?

File: cpp/src/parquet/encoding.cc (hunk 7 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:1219]: https://godbolt.org/z/5bf1K55a5

Found it might not optimized with hot path.

File: cpp/src/parquet/encoding.cc (hunk 5 above)
Comment (jorisvandenbossche) [reply cpp/src/parquet/encoding.cc:1207]: I can confirm that this change actually fixes the regression (https://github.com/apache/arrow/issues/38577#issuecomment-1826032128). 

When the decoder/builder is reused (eg reading a second row group or batch of a row group), `chunk_space_remaining_` is smaller than `kBinaryMemoryLimit`. So if `estimated_data_length` is larger than `chunk_space_remaining_`, we are trying to reserve too many values.

**Comment by jorisvandenbossche** [comment]
Strangely on the latest version I don't directly see any effect locally, but, at least the online benchmarks now seem to confirm some improvement (several of the similar benchmarks are consistent): for example https://conbench.ursa.dev/compare/benchmark-results/0655f5af97857ba780005944ff57195f...06560d57f1f772cc800009452aab4863/

**Comment by mapleFU** [comment]
The difference between current version and 13.0.0 version is it call more `BinaryBuilder->Reserve()`, I don't think it would make performance worse, so I revert some change in https://github.com/apache/arrow/pull/38784/commits/60cdb808c9ab6d25b2e00474a6307a8bf35b7b24 . Maybe we can considering this later.

This patch also separate `PrepareNextInput`. Maybe it's a compiler specific problem, I've check a similar case in quick-bench, it doesn't benfit the performance if we remove `std::optional<>` as argument in gcc-12.3 with C++17. However benchmark shows that the performance has benefits. Maybe we can ask some C++ experts for help.

You can decide how to handle this patch later, maybe I'm becoming crazy because spending long time but don't know why previously, at least we found that:
1. `Reserve` might related to the problem
2. `PrepareInput` in the patch might make compiler doesn't do some optimizations in ursa bot benchmark

**Review by pitrou — APPROVED** [review]

**Comment by mapleFU** [comment]
Will wait util monday night to see any futher request for review

**Comment by mapleFU** [comment]
@pitrou Would you like to checkin this?
