### PR TITLE
GH-38304: [C++][Parquet] Fix Valgrind memory leak in arrow-dataset-file-parquet-encryption-test

### LINKED ISSUE #38304: [C++][CI] test-conda-cpp-valgrind fails on arrow-dataset-file-parquet-encryption-test
### Describe the bug, including details regarding any error messages, version, and platform.

The arrow-dataset-file-parquet-encryption-test seems to have an issue when running the valgrind jobs both on the maintenance branch and main:
* Main: [test-conda-cpp-valgrind](https://github.com/ursacomputing/crossbow/runs/17763269445)
* maint-14.0.0: https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=55816&view=logs&j=50a69d0a-7972-5459-cdae-135ee6ebe312&t=13df7b5c-76db-5c26-6592-75581a9ed64a

The error:
```
66/87 Test #66: arrow-dataset-file-parquet-encryption-test ...***Failed   15.28 sec
==12896== Memcheck, a memory error detector
==12896== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==12896== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==12896== Command: /build/cpp/debug//arrow-dataset-file-parquet-encryption-test
==12896== 
Running main() from /build/cpp/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from DatasetEncryptionTest
[ RUN      ] DatasetEncryptionTest.WriteReadDatasetWithEncryption
[       OK ] DatasetEncryptionTest.WriteReadDatasetWithEncryption (1647 ms)
[ RUN      ] DatasetEncryptionTest.ReadSingleFile
[       OK ] DatasetEncryptionTest.ReadSingleFile (79 ms)
[----------] 2 tests from DatasetEncryptionTest (1733 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (8572 ms total)
[  PASSED  ] 2 tests.
==12896== 
==12896== HEAP SUMMARY:
==12896==     in use at exit: 30,776 bytes in 254 blocks
==12896==   total heap usage: 37,143 allocs, 36,889 frees, 6,508,003 bytes allocated
==12896== 
==12896== 904 bytes in 1 blocks are definitely lost in loss record 59 of 70
==12896==    at 0x4849724: malloc (vg_replace_malloc.c:431)
==12896==    by 0x7053989: CRYPTO_zalloc (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x70094A9: ossl_err_get_state_int (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x700A189: ERR_set_mark (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x6F8D9EF: CONF_modules_load_file_ex (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x6F8DDD5: ossl_config_int (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x705282B: ossl_init_config_ossl_ (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x6C0DEE7: __pthread_once_slow (pthread_once.c:116)
==12896==    by 0x7060919: CRYPTO_THREAD_run_once (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x70530B3: OPENSSL_init_crypto (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x700775C: ossl_engine_table_select (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x71389D5: RAND_get_rand_method (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896==    by 0x7139319: RAND_bytes_ex (in /opt/conda/envs/arrow/lib/libcrypto.so.3)
==12896== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==12896== 
==12896== For lists of detected and suppressed errors, rerun with: -s
==12896== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)

```

### Component(s)

C++, Continuous Integration

### PR DESCRIPTION
**Pull request by pitrou**
If OpenSSL initializes itself from a non-main thread, it can fail deallocating all memory at shutdown.

This is really a benign leak, but we don't want any spurious CI errors.

* Closes: #38304

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
cc @tolleybot @ggershinsky

File: cpp/src/parquet/encryption/openssl_internal.cc [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+#include <openssl/crypto.h>
+
+#include "parquet/exception.h"
+
+namespace parquet::encryption::openssl {
+
+void EnsureInitialized() {
+  // Initialize ciphers and random engines
+  if (!OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_ALL_BUILTIN | OPENSSL_INIT_ADD_ALL_CIPHERS,
```
Comment (wgtmac) [inline cpp/src/parquet/encryption/openssl_internal.cc:28]: I assume this is safe to be called multiple times, right?

Comment (pitrou) [reply cpp/src/parquet/encryption/openssl_internal.cc:28]: Yes, it is. It's actually called implicitly by many OpenSSL APIs.

**Review by wgtmac — APPROVED** [review]
Thanks! +1

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc [hunk 2]
```diff
@@ -58,6 +59,13 @@ class DatasetEncryptionTest : public ::testing::Test {
   // partitioning scheme. The function also checks if the written files exist in the file
   // system.
   static void SetUpTestSuite() {
+#ifdef ARROW_VALGRIND
+    // Not necessary otherwise, but prevents a Valgrind leak by making sure
+    // OpenSSL initialization is done from the main thread
+    // (see GH-38304 for analysis).
+    ::parquet::encryption::EnsureBackendInitialized();
```
Comment (mapleFU) [inline cpp/src/arrow/dataset/file_parquet_encryption_test.cc:66]: This only ensure initialized in tests, right? A encryption can still be loaded in a non-main thread.

Comment (pitrou) [reply cpp/src/arrow/dataset/file_parquet_encryption_test.cc:66]: Yes, and only under Valgrind (see `#ifdef`).

File: cpp/src/parquet/encryption/openssl_internal.cc (hunk 1 above)
Comment (mapleFU) [reply cpp/src/parquet/encryption/openssl_internal.cc:28]: I've checkout the code and find that the openssl has a `once` here. So I think it would be safe

File: cpp/src/arrow/dataset/file_parquet_encryption_test.cc (hunk 2 above)
Comment (mapleFU) [reply cpp/src/arrow/dataset/file_parquet_encryption_test.cc:66]: I think the code works. So the user would better call `EnsureBackendInitialized` when initializing, like initialize S3?

The current code works but would it bring some global locking or other problem?

**Review by mapleFU — APPROVED** [review]
I'm +1 for this change but I'm not familiar with openssl api enough. Maybe the one who familiar with this can approve or give some idea.

**Comment by kou** [comment]
@github-actions crossbow submit centos-7-amd64
