### PR TITLE
GH-34385: [Go] Read IPC files with compression enabled but uncompressed buffers

### LINKED ISSUE #34385: [Go] Read IPC files with compression enabled but uncompressed buffers
### Describe the bug, including details regarding any error messages, version, and platform.

Observed in #15194; an IPC file with compression may still have uncompressed buffers but Go appears not to handle this (just as C++ didn't)

### Component(s)

Go

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
Fixing a bug in compressing buffers by prepending -1 when a buffer is not compressed due to size.

### Are these changes tested?
Unit tests added, and other tests will be enabled via integration tests in #15194

* Closes: #34385

### CODE REVIEW

File: go/arrow/ipc/ipc.go [hunk 1]
```diff
@@ -168,6 +169,26 @@ func WithDictionaryDeltas(v bool) Option {
...
+//
+// For example, if minSpaceSavings = 0.1, a 100-byte body buffer won't
+// undergo compression if its expected compressed size exceeds 90 bytes.
+// If this option is unset, compression will be used indiscriminately. If
+// no codec was supplied, this option is ignored.
+//
+// Values outside of the range [0,1] are handled as errors.
+//
+// Note that enabling this option may result in unreadable data for Arrow
+// C++ versions prior to 12.0.0.
```
Comment (lidavidm) [inline go/arrow/ipc/ipc.go:185]: Doesn't this also apply to go? (Or else, why did we have problems in the integration test if this only affected C++ readers?)

**Review by lidavidm — APPROVED** [review]
Should we unskip the integration tests here?

**Comment by lidavidm** [comment]
Hmm, looks like CGO is having issues across multiple PRs

**Comment by zeroshade** [comment]
@lidavidm Yea, looks like the issue is that macOS is missing the openssl lib for some reason, I 'll open a PR for it soon

File: go/arrow/ipc/ipc.go (hunk 1 above)
Comment (zeroshade) [reply go/arrow/ipc/ipc.go:185]: gah, my fault for copying the comment, i'll fix it and update.

**Review by lidavidm — APPROVED** [review]

**Comment by zeroshade** [comment]
Addressed the failing macos issue with #34488
