### PR TITLE
GH-36189: [C++][Parquet] StreamReader::SkipRows() skips to incorrect place in multi-row-group files

### LINKED ISSUE #36189: [C++][Parquet] StreamReader::SkipRows() skips to wrong spot in files containing multiple row groups
### Describe the bug, including details regarding any error messages, version, and platform.

The issue arises due to a simple arithmetic error when calculating the offset from the current row group. As far as I can tell this affects all platforms and the bug has existed since the introduction of the StreamReader skip code in https://github.com/apache/arrow/commit/56adb6a7ecd5f189f03f4a73a6df1c9a2af1eeb0 

I will submit a PR with a unit test case and proposed fix shortly. 

### Component(s)

C++

### PR DESCRIPTION
**Pull request by KarateSnowMachine**
### Rationale for this change

The behavior of Parquet `StreamReader::SkipRows()` is wrong due to an error in calculating the row offset from the current row group. 

### What changes are included in this PR?

A unit test case demonstrating the failure and a trivial fix. 

### Are these changes tested?

Yes 

### Are there any user-facing changes?

No

I am not sure if this bug is critical given how long it has existed in the code and no one has seemed to notice. There are two manifestations of this bug that might give the user the wrong impression about what is in their data: 

* sometimes a negative return value is returned, which is unexpected given the nature of the API, so the user should know something is up (this is how I discovered the bug)
* the `SkipRows()` call leads to setting of the `eof` flag prematurely, which might lead the user to think there is less data in the file than there is. 
* Closes: #36189

### CODE REVIEW

File: cpp/src/parquet/stream_reader_test.cc [hunk 1]
```diff
@@ -947,5 +947,77 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
   EXPECT_EQ(i, 25);
 }
 
+class TestMultiRowGroupStreamReader : public ::testing::Test {
+ public:
+  TestMultiRowGroupStreamReader() { createTestFile(); }
+
+ protected:
+  const char* GetDataFile() const { return "stream_reader_multirowgroup_test.parquet"; }
```
Comment (wgtmac) [inline cpp/src/parquet/stream_reader_test.cc:955]: It would be better to write this to an in-memory file.

File: cpp/src/parquet/stream_reader_test.cc [hunk 2]
```diff
@@ -947,5 +947,77 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+                                                 Type::INT32, ConvertedType::UINT_16));
+
+    fields.push_back(schema::PrimitiveNode::Make("row_number", Repetition::REQUIRED,
+                                                 Type::INT64, ConvertedType::UINT_64));
+
+    return std::static_pointer_cast<schema::GroupNode>(
+        schema::GroupNode::Make("schema", Repetition::REQUIRED, fields));
+  }
+
+  void createTestFile() {
```
Comment (wgtmac) [inline cpp/src/parquet/stream_reader_test.cc:977]:
```suggestion
  void CreateTestFile() {
```

File: cpp/src/parquet/stream_reader_test.cc [hunk 3]
```diff
@@ -947,5 +947,77 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+  StreamReader reader_;
+  static constexpr int num_row_groups = 5;
+  static constexpr int num_rows_per_group = 10;
+};
+
+TEST_F(TestMultiRowGroupStreamReader, SkipRows) {
+  // skip somewhere in the middle that is a few row groups in to the file
+  auto num_rows_to_skip = 33;
+
+  auto retval = reader_.SkipRows(num_rows_to_skip);
```
Comment (wgtmac) [inline cpp/src/parquet/stream_reader_test.cc:1006]: Could you add more `SkipRows` call here to make sure multiple skips are correct?

**Review by wgtmac — COMMENTED** [review]
Thanks for the fix! I have left some comments.

**Review by mapleFU — APPROVED** [review]
This Patch LGTM,

File: cpp/src/parquet/stream_reader_test.cc (hunk 1 above)
Comment (KarateSnowMachine) [reply cpp/src/parquet/stream_reader_test.cc:955]: I am happy to make that change but as this is my first contribution I'm not sure how to do this. This test fixture is simply a copy/paste of the existing `TestStreamReader` fixture above but with different initialization code.  Could you provide an example of how to do an in-memory file?

Comment (wgtmac) [reply cpp/src/parquet/stream_reader_test.cc:955]: I see. That's fine. Thanks!

File: cpp/src/parquet/stream_reader_test.cc [hunk 4]
```diff
@@ -947,5 +947,111 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+  reader_ >> current_global_row;
+  EXPECT_EQ(current_global_row, 40);
+  reader_.EndRow();
+
+  // finally, skip off the end of the file
+  retval = reader_.SkipRows(10);
+  ASSERT_GE(retval, 0);
+
+  EXPECT_TRUE(reader_.eof());
+
```
Comment (wgtmac) [inline cpp/src/parquet/stream_reader_test.cc:1053]:
```suggestion
```

**Review by wgtmac — APPROVED** [review]

**Comment by kou** [comment]
Could you fix a lint failure?

https://github.com/apache/arrow/actions/runs/5334518109/jobs/9670310791?pr=36191#step:5:926

```text
FAILED: CMakeFiles/check-format 
cd /tmp/arrow-lint-89g59kh1/cpp-build && /usr/local/bin/python /arrow/cpp/build-support/run_clang_format.py --clang_format_binary /usr/bin/clang-format-14 --exclude_globs /arrow/cpp/build-support/lint_exclusions.txt --source_dir /arrow/cpp/src --source_dir /arrow/cpp/examples --source_dir /arrow/cpp/tools --quiet

--- /arrow/cpp/src/parquet/stream_reader_test.cc
+++ /arrow/cpp/src/parquet/stream_reader_test.cc (after clang format)
@@ -984,13 +984,13 @@
 
     int nrows = 0;
     for (auto group = 0; group < num_row_groups; ++group) {
-        for (auto i = 0; i < num_rows_per_group; ++i) {
-          os << static_cast<uint16_t>(group);
-          os << static_cast<uint64_t>(nrows);
-          os << EndRow;
-          nrows++;
-        }
-        os.EndRowGroup();
+      for (auto i = 0; i < num_rows_per_group; ++i) {
+        os << static_cast<uint16_t>(group);
+        os << static_cast<uint64_t>(nrows);
+        os << EndRow;
+        nrows++;
+      }
+      os.EndRowGroup();
     }
   }
 
@@ -1013,7 +1013,7 @@
   uint16_t current_row_group = 0;
   uint64_t current_global_row = 0;
   reader_ >> current_row_group;
-  EXPECT_EQ(current_row_group, current_row/10);
+  EXPECT_EQ(current_row_group, current_row / 10);
 
   reader_ >> current_global_row;
   EXPECT_EQ(current_global_row, current_row);
@@ -1026,7 +1026,7 @@
   // we read row 33 (were at 34, then skipped 4 => 38)
   current_row = 38;
   reader_ >> current_row_group;
-  EXPECT_EQ(current_row_group, current_row/10);
+  EXPECT_EQ(current_row_group, current_row / 10);
 
   reader_ >> current_global_row;
   EXPECT_EQ(current_global_row, current_row);
@@ -1050,7 +1050,6 @@
   ASSERT_GE(retval, 0);
 
   EXPECT_TRUE(reader_.eof());
-
 }
 
 }  // namespace test
/arrow/cpp/src/parquet/stream_reader_test.cc had clang-format style issues
```

You can fix it by `ninja format`/`make format` or something.

**Comment by KarateSnowMachine** [comment]
I can't tell if the last CI failure is my fault or just something timing out. Is there anything else I need to do or contribute for this PR?

**Comment by mapleFU** [comment]
@wgtmac @pitrou would you mind take a look? If ci passed I think this could be merged?

File: cpp/src/parquet/stream_reader_test.cc [hunk 5]
```diff
@@ -947,5 +947,110 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+        os << EndRow;
+        nrows++;
+      }
+      os.EndRowGroup();
+    }
+  }
+
+  StreamReader reader_;
+  static constexpr int num_row_groups = 5;
+  static constexpr int num_rows_per_group = 10;
```
Comment (pitrou) [inline cpp/src/parquet/stream_reader_test.cc:999]: Let's use our common conventions for constants:
```suggestion
  static constexpr int kNumGroups = 5;
  static constexpr int kNumRowsPerGroup = 10;
```

File: cpp/src/parquet/stream_reader_test.cc (hunk 2 above)
Comment (pitrou) [reply cpp/src/parquet/stream_reader_test.cc:977]: This change doesn't seem to have been made?

File: cpp/src/parquet/stream_reader_test.cc [hunk 6]
```diff
@@ -947,5 +947,110 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+  ASSERT_GE(retval, 0);
+
+  // there are 50 total rows, so definitely not EOF
+  ASSERT_FALSE(reader_.eof());
+
+  // make sure we skipped to where we expected
+  uint16_t current_row_group = 0;
+  uint64_t current_global_row = 0;
+  reader_ >> current_row_group;
+  EXPECT_EQ(current_row_group, current_row / 10);
```
Comment (pitrou) [inline cpp/src/parquet/stream_reader_test.cc:1016]:
```suggestion
  EXPECT_EQ(current_row_group, current_row / kNumRowsPerGroup);
```

File: cpp/src/parquet/stream_reader_test.cc [hunk 7]
```diff
@@ -947,5 +947,110 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+
+  reader_ >> current_global_row;
+  EXPECT_EQ(current_global_row, current_row);
+  reader_.EndRow();
+
+  // skip a few more rows but stay inside of this row group
+  retval = reader_.SkipRows(4);
+  ASSERT_GE(retval, 0);
```
Comment (pitrou) [inline cpp/src/parquet/stream_reader_test.cc:1024]: Again, test `retval` more precisely.

**Review by pitrou — CHANGES_REQUESTED** [review]

**Comment by wgtmac** [comment]
@KarateSnowMachine Just want to check if you get the chance to do what @pitrou has suggested?

**Comment by KarateSnowMachine** [comment]
Sorry, I didn't get a chance to make the suggested changes before leaving
on vacation. I'll make the changes in two weeks.

**Comment by wgtmac** [comment]
Thanks for the reply. Take your time and enjoy the vacation!

File: cpp/src/parquet/stream_reader_test.cc [hunk 8]
```diff
@@ -947,5 +947,110 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+
+  StreamReader reader_;
+  static constexpr int num_row_groups = 5;
+  static constexpr int num_rows_per_group = 10;
+};
+
+TEST_F(TestMultiRowGroupStreamReader, SkipRows) {
+  // skip somewhere into the middle of a row group somewhere in the middle of the file
+  auto current_row = 33;
+
```
[the remark this answers is not in the document]
Comment (KarateSnowMachine) [reply cpp/src/parquet/stream_reader_test.cc:1016]: Fixed. I made the helper name a bit more verbose to make it clear that it will have the side effect of consuming the row.

File: cpp/src/parquet/stream_reader_test.cc [hunk 9]
```diff
@@ -947,5 +947,110 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+  reader_ >> current_row_group;
+  EXPECT_EQ(current_row_group, current_row / 10);
+
+  reader_ >> current_global_row;
+  EXPECT_EQ(current_global_row, current_row);
+  reader_.EndRow();
+
+  // skip to the exact start of the next row group 4
+  // read 38 (were at 39, then skip 1 => 40)
+  retval = reader_.SkipRows(1);
```
[the remark this answers is not in the document]
Comment (KarateSnowMachine) [reply cpp/src/parquet/stream_reader_test.cc:1031]: Fixed

File: cpp/src/parquet/stream_reader_test.cc [hunk 10]
```diff
@@ -947,5 +947,98 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
 }
 
+class TestMultiRowGroupStreamReader : public ::testing::Test {
+ public:
+  TestMultiRowGroupStreamReader() {}
+
+ protected:
+  const char* GetDataFile() const { return "stream_reader_multirowgroup_test.parquet"; }
+
+  void SetUp() {
```
Comment (wgtmac) [inline cpp/src/parquet/stream_reader_test.cc:957]:
```suggestion
  void SetUp() override {
```

File: cpp/src/parquet/stream_reader_test.cc [hunk 11]
```diff
@@ -947,5 +947,98 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+        os << static_cast<uint64_t>(nrows);
+        os << EndRow;
+        nrows++;
+      }
+      os.EndRowGroup();
+    }
+  }
+
+  void ReadRowAndAssertPosition(uint64_t expected_row_num) {
+    const uint16_t expected_group_num = ((uint16_t)expected_row_num) / kNumRowsPerGroup;
```
Comment (wgtmac) [inline cpp/src/parquet/stream_reader_test.cc:999]:
```suggestion
    auto expected_group_num = static_cast<uint16_t>(expected_row_num / kNumRowsPerGroup);
```

File: cpp/src/parquet/stream_reader_test.cc (hunk 10 above)
Comment (wgtmac) [reply cpp/src/parquet/stream_reader_test.cc:957]: BTW, SetUp and TearDown are public by default.

File: cpp/src/parquet/stream_reader_test.cc [hunk 12]
```diff
@@ -947,5 +947,98 @@ TEST_F(TestReadingDataFiles, ByteArrayDecimal) {
...
+  const char* GetDataFile() const { return "stream_reader_multirowgroup_test.parquet"; }
+
+  void SetUp() {
+    CreateTestFile();
+    PARQUET_ASSIGN_OR_THROW(auto infile, ::arrow::io::ReadableFile::Open(GetDataFile()));
+    auto file_reader = parquet::ParquetFileReader::Open(infile);
+    reader_ = StreamReader{std::move(file_reader)};
+  }
+
+  void TearDown() { reader_ = StreamReader{}; }
```
[the remark this answers is not in the document]
Comment (wgtmac) [reply cpp/src/parquet/stream_reader_test.cc:964]: It seems TearDown() is not required to implement.

**Review by wgtmac — CHANGES_REQUESTED** [review]
Thanks for updating! I have left some comments for minor changes.

**Review by wgtmac — APPROVED** [review]
