### PR TITLE
GH-33697: [CI][Python] Nightly test for PySpark 3.2.0 fail with AttributeError on numpy.bool

### LINKED ISSUE #33697: [CI][Python] Nightly test for PySpark 3.2.0 fail with AttributeError on numpy.bool
### Describe the bug, including details regarding any error messages, version, and platform.

Nightly integration tests with PySpark 3.2.0 are failing with the following error:
[test-conda-python-3.8-spark-v3.2.0](https://github.com/ursacomputing/crossbow/actions/runs/3926041499/jobs/6711398638)
```
ERROR: test_with_key_complex (pyspark.sql.tests.test_pandas_cogrouped_map.CogroupedMapInPandasTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/spark/python/pyspark/sql/tests/test_pandas_cogrouped_map.py", line 160, in test_with_key_complex
    result = self.data1 \
  File "/spark/python/pyspark/sql/pandas/conversion.py", line 168, in toPandas
    pandas_type = PandasConversionMixin._to_corrected_pandas_type(field.dataType)
  File "/spark/python/pyspark/sql/pandas/conversion.py", line 238, in _to_corrected_pandas_type
    return np.bool
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
```

### Component(s)

Continuous Integration, Python

### PR DESCRIPTION
**Pull request by AlenkaF**
### Rationale for this change
Fix for nightly integration tests with PySpark 3.2.0 failure.

### What changes are included in this PR?
NumPy version pin in `docker-compose.yml`.

### Are these changes tested?
Will test on the open PR with the CI.

### Are there any user-facing changes?
No.
* Closes: #33697

### CODE REVIEW

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-v3.2.0

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-v3.2.0

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-v3.2.0

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-v3.2.0

File: ci/docker/conda-python-spark.dockerfile [hunk 1]
```diff
@@ -22,10 +22,15 @@ FROM ${repo}:${arch}-conda-python-${python}
 
 ARG jdk=8
 ARG maven=3.5
+# https://github.com/apache/arrow/issues/33697
+# numpy version pin should be removed with new apache spark release
+# that includes https://github.com/apache/spark/pull/37817
+ARG numpy=1.23
```
Comment (raulcd) [inline ci/docker/conda-python-spark.dockerfile:28]: we already test spark master nightly, this is the current testing combination:
```
{% for python_version, spark_version, test_pyarrow_only in [("3.7", "v3.1.2", "false"),
                                                            ("3.8", "v3.2.0", "false"),
                                                            ("3.9", "master", "false")] %}
```
And the build for spark master is currently passing: https://github.com/ursacomputing/crossbow/actions/runs/3934958561/jobs/6730195747#step:5:10
Maybe we can add the numpy version to the task definition only for 3.2.0 and if it is different than latest install the pinned version. I am thinking on something like:
```
{% for python_version, spark_version, test_pyarrow_only, numpy_version in [("3.7", "v3.1.2", "false", "latest"),
                                                            ("3.8", "v3.2.0", "false", "1.23"),
                                                            ("3.9", "master", "false", "latest")] %}
```
And the corresponding if to validate if we have to install numpy or not?
@kiszk you are  spark committer. I suppose this fix won't get backported to spark 3.2.0 and we have to pin numpy always for it?  Should we update the tasks for our nightlies to test with spark 3.3.0 maybe remove 3.2.0?

**Review by raulcd — COMMENTED** [review]
Thanks @AlenkaF for the PR! I have some questions because the nightly build with both spark master and 3.1.2 are already working without pinning numpy. I've pinged @kiszk as he's a spark committer because I am not sure if this will ever get backported to 3.2.0

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-v3.2.0

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-v3.2.0

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-*-spark-*

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-*-spark-*

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-*-spark-*

**Comment by jorisvandenbossche** [comment]
Looking at the logs, I think the line "#7 7.578 /bin/bash: /arrow/ci/scripts/install_numpy.sh: Permission denied" is the problem (the file wasn't copied, so installing numpy using the nonexisting file fails)

However, I don't see any difference with what we already do in `conda-python-pandas.dockerfile` (that also does such a copy), so not directly sure why that is going wrong.

**Comment by AlenkaF** [comment]
> Looking at the logs, I think the line "#7 7.578 /bin/bash: /arrow/ci/scripts/install_numpy.sh: Permission denied" is the problem (the file wasn't copied, so installing numpy using the nonexisting file fails)
> 
> However, I don't see any difference with what we already do in `conda-python-pandas.dockerfile` (that also does such a copy), so not directly sure why that is going wrong.

Yeah, I am trying out different things locally but none work 🤷‍♀️  Also asked Raul for help, if he has any ideas what could be the issue.

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-*-spark-*

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-*-spark-*

**Comment by AlenkaF** [comment]
@raulcd the fix is working now, thank you!
The CI failure is not related (maybe I need a rebase?).

File: ci/scripts/install_numpy.sh [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+
+set -e
+
+if [ "$#" -lt 1 ]; then
```
Comment (kou) [inline ci/scripts/install_numpy.sh:22]: * We don't need `"..."` because `$#` is a number
* We need to accept `ci/scripts/install_numpy.sh` (no argument)

```suggestion
if [ $# -gt 1 ]; then
```

File: ci/docker/conda-python-spark.dockerfile [hunk 3]
```diff
@@ -23,11 +23,16 @@ FROM ${repo}:${arch}-conda-python-${python}
...
 
+ARG numpy=latest
+COPY ci/scripts/install_numpy.sh /arrow/ci/scripts/
+
 RUN mamba install -q -y \
         openjdk=${jdk} \
         maven=${maven} \
         pandas && \
     mamba clean --all
+RUN mamba uninstall -q -y numpy && \
```
Comment (kou) [inline ci/docker/conda-python-spark.dockerfile:34]: How about concatenating these commands to reduce intermediate Docker image?

```suggestion
    mamba clean --all && \
    mamba uninstall -q -y numpy && \
```

**Review by raulcd — APPROVED** [review]
Thanks @AlenkaF I am going to trigger a final run just to validate and will merge once it finishes.

**Comment by raulcd** [comment]
@github-actions crossbow submit test-conda-python-*-spark-*
