### PR TITLE
GH-35526: [CI][C++] Fixing arrow::internal::IsNullRunEndEncoded redeclared

### LINKED ISSUE #35526: [CI][C++] arrow::internal::IsNullRunEndEncoded redeclared
### Describe the bug, including details regarding any error messages, version, and platform.

Error messages would be like: 

```
D:/a/arrow/arrow/cpp/src/arrow/array/data.h:530:15: warning: 'bool arrow::internal::IsNullRunEndEncoded(const arrow::ArrayData&, int64_t)' redeclared without dllimport attribute after being referenced with dll linkage
  530 |   friend bool internal::IsNullRunEndEncoded(const ArrayData& span, int64_t i);
      |               ^~~~~~~~
[122/131] Linking CXX shared library release\libparquet.dll
[123/131] Linking CXX shared library release\libarrow_dataset.dll
[124/131] Linking CXX shared library release\libarrow_substrait.dll
[125/131] Building CXX object src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_4_cxx.cxx.obj
In file included from D:/a/arrow/arrow/cpp/src/arrow/array/array_base.h:26,
                 from D:/a/arrow/arrow/cpp/src/arrow/array.h:41,
                 from D:/a/arrow/arrow/cpp/src/gandiva/arrow.h:23,
                 from D:/a/arrow/arrow/cpp/src/gandiva/simple_arena.h:27,
                 from D:/a/arrow/arrow/cpp/src/gandiva/execution_context.h:22,
                 from D:/a/arrow/arrow/cpp/src/gandiva/interval_holder.h:27,
                 from D:/a/arrow/arrow/cpp/src/gandiva/interval_holder.cc:18,
                 from D:/a/arrow/arrow/build/cpp/src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_4_cxx.cxx:3:
D:/a/arrow/arrow/cpp/src/arrow/array/data.h:530:15: warning: 'bool arrow::internal::IsNullRunEndEncoded(const arrow::ArrayData&, int64_t)' redeclared without dllimport attribute after being referenced with dll linkage
  530 |   friend bool internal::IsNullRunEndEncoded(const ArrayData& span, int64_t i);
      |               ^~~~~~~~
In file included from D:/a/arrow/arrow/build/cpp/src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_4_cxx.cxx:5:
D:/a/arrow/arrow/cpp/src/gandiva/llvm_generator.cc: In member function 'arrow::Status gandiva::LLVMGenerator::CodeGenExprValue(gandiva::DexPtr, int, gandiva::FieldDescriptorPtr, int, std::string&, gandiva::SelectionVector::Mode)':
D:/a/arrow/arrow/cpp/src/gandiva/llvm_generator.cc:362:27: warning: 'selection_vector_type' may be used uninitialized [-Wmaybe-uninitialized]
  362 |         builder->CreateGEP(selection_vector_type, arg_selection_vector, loop_var);
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/arrow/arrow/cpp/src/gandiva/llvm_generator.cc:282:15: note: 'selection_vector_type' was declared here
  282 |   llvm::Type* selection_vector_type;
      |               ^~~~~~~~~~~~~~~~~~~~~
```

See https://github.com/apache/arrow/actions/runs/4935627139/jobs/8822177881?pr=35520 and https://github.com/apache/arrow/actions/runs/4926681476/jobs/8802598792?pr=35428

Personally I guess it was introduced in https://github.com/apache/arrow/commit/fde31ed1cb1de1a0d2b9ade257e66104160d31bb 

### Component(s)

C++, Continuous Integration

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Fixing arrow::internal::IsNullRunEndEncoded redeclared. The CI will report:

```
'bool arrow::internal::IsNullRunEndEncoded(const arrow::ArrayData&, int64_t)' redeclared without dllimport attribute after being referenced with dll linkage
```

And:

```
warning: 'selection_vector_type' may be used uninitialized
```

### What changes are included in this PR?

1. Add `ARROW_FRIEND_EXPORT` for friend function
2. Initialize pointer in gandiva with `nullptr`

### Are these changes tested?

No

### Are there any user-facing changes?

No

* Closes: #35526

### CODE REVIEW

**Comment by mapleFU** [comment]
This fixing is wrong, it's not anonymous namespace problem

**Comment by mapleFU** [comment]
@kou Mind take a look?
cc @felipecrv

**Comment by mapleFU** [comment]
```
[421/916] Building CXX object src/arrow/util/CMakeFiles/arrow-utility-test.dir/iterator_test.cc.obj
In file included from D:/a/_temp/msys64/mingw64/include/c++/13.1.0/bits/shared_ptr.h:53,
                 from D:/a/_temp/msys64/mingw64/include/c++/13.1.0/condition_variable:45,
                 from D:/a/arrow/arrow/cpp/src/arrow/util/iterator_test.cc:21:
```

Seems that it reports shared_ptr is wrong in this case, another case is that:

```
    // Move into itself
    moved_moved_ints = std::move(moved_moved_ints);
```

in `small_vector_test.cc`. I don't know why they're reported. So I just leave them here.

File: cpp/src/gandiva/llvm_generator.cc [hunk 1]
```diff
@@ -295,6 +295,8 @@ Status LLVMGenerator::CodeGenExprValue(DexPtr value_expr, int buffer_count,
       selection_vector_type = types()->i64_type();
       break;
   }
+  ARROW_RETURN_IF((selection_vector_type == nullptr),
+                  Status::CodeGenError("Error creating selection_vector_type."));
```
Comment (pitrou) [inline cpp/src/gandiva/llvm_generator.cc:299]: IMHO it would be clearer to move this into a `default` clause in the `switch` statement above.

Comment (mapleFU) [reply cpp/src/gandiva/llvm_generator.cc:299]: The switch case doesn't has a default. So I've no idea that why it reports compilation error. Maybe a stale compiler is used when building Windows in CI ?

Comment (pitrou) [reply cpp/src/gandiva/llvm_generator.cc:299]: Hmm, if that's the case, then just remove this line?

**Review by felipecrv — APPROVED** [review]

**Review by pitrou — APPROVED** [review]
+1, let's wait for CI now

**Comment by mapleFU** [comment]
For Python Pandas assertion, here is a patch: https://github.com/apache/arrow/pull/35530
I wonder if it helps...

**Comment by pitrou** [comment]
Hmm, it seems there's another issue now on MinGW GLib build:
https://github.com/apache/arrow/actions/runs/4938674894/jobs/8829920058?pr=35527

@kou, would you be able to take a look here?
```

2023-05-10T17:13:11.8253839Z [126/131] Building CXX object src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_2_cxx.cxx.obj
2023-05-10T17:13:11.8256428Z FAILED: src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_2_cxx.cxx.obj 
2023-05-10T17:13:13.7339400Z C:\msys64\ucrt64\bin\ccache.exe C:\msys64\ucrt64\bin\c++.exe -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_WITH_RE2 -DARROW_WITH_TIMING_TESTS -DARROW_WITH_UTF8PROC -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=11 -DAWS_SDK_VERSION_PATCH=67 -DAWS_USE_IO_COMPLETION_PORTS -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DBOOST_USE_WINDOWS_H=1 -DGANDIVA_EXPORTING -DGANDIVA_LLVM_VERSION=16 -DUSE_IMPORT_EXPORT -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -Dgandiva_shared_EXPORTS -ID:/a/arrow/arrow/build/cpp/src -ID:/a/arrow/arrow/cpp/src -ID:/a/arrow/arrow/cpp/src/generated -isystem D:/a/arrow/arrow/cpp/thirdparty/flatbuffers/include -isystem D:/a/arrow/arrow/cpp/thirdparty/hadoop/include -isystem D:/a/arrow/arrow/build/cpp/google_cloud_cpp_ep-install/include -isystem D:/a/arrow/arrow/build/cpp/crc32c_ep-install/include -Wno-noexcept-type -Wno-subobject-linkage  -fdiagnostics-color=always  -Wa,-mbig-obj -Wall -Wno-conversion -Wno-sign-conversion -Wunused-result -fno-semantic-interposition -mxsave -msse4.2  -O3 -DNDEBUG -O2 -ftree-vectorize -std=c++17 -MD -MT src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_2_cxx.cxx.obj -MF src\gandiva\CMakeFiles\gandiva_shared.dir\Unity\unity_2_cxx.cxx.obj.d -o src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_2_cxx.cxx.obj -c D:/a/arrow/arrow/build/cpp/src/gandiva/CMakeFiles/gandiva_shared.dir/Unity/unity_2_cxx.cxx
```

**Comment by kou** [comment]
Oh, it was failed without error message...

I can try this on my local environment next week. (I attend [RubyKaigi 2023](https://rubykaigi.org/2023/) in this week.)

**Comment by mapleFU** [comment]
@pitrou Could we get this fixing merged or need to wait some testing or failed ci passing?

**Comment by pitrou** [comment]
@mapleFU I've restarted some CI jobs now that GitHub seems to be doing a bit better :-)

**Comment by mapleFU** [comment]
Github has problem these three days...But I wonder that why these UT failed is related :-(

**Comment by pitrou** [comment]
The MinGW C++ errors and segfaults don't look related, so I'm going to merge this PR. Thanks @mapleFU !
