### PR TITLE
GH-48470: [Python] Construct UuidArray from list of UuidScalars

### LINKED ISSUE #48470: [Python] Cannot construct `UuidArray` from list of `UuidScalar`s
### Describe the bug, including details regarding any error messages, version, and platform.

Might be the same issue as https://github.com/apache/arrow/issues/43855, feel free to close if this is the case.

```pytb
>>> import pyarrow as pa
>>> pa.array([pa.scalar(b'1'*16, type=pa.uuid())], type=pa.uuid())
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
File …/pyarrow/array.pxi:375, in pyarrow.lib.array()
File …/pyarrow/array.pxi:46, in pyarrow.lib._sequence_to_array()
File …/pyarrow/error.pxi:155, in pyarrow.lib.pyarrow_internal_check_status()
File …/pyarrow/error.pxi:92, in pyarrow.lib.check_status()
ArrowInvalid: Cannot append scalar of type extension<arrow.uuid> to builder for type fixed_size_binary[16]
```

Version: 22.0.0
Platform: MacOS, but probably everywhere

### Component(s)

Python

### PR DESCRIPTION
**Pull request by tadeja**
### Rationale for this change
Fixes #48470. Also fixes all extension types, not just UUID.

### What changes are included in this PR?
An extension scalar is unwrapped to its storage type when building arrays.

### Are these changes tested?
Yes, new `test_array_from_extension_scalars` covers builtin (uuid, bool8, json_, opaque) and custom types across all storage types (int, float, bool, string, binary, large string/binary, decimal, fixed-size binary, struct, timestamp, duration, date).

### Are there any user-facing changes?
Now user can run such an example to get the output below instead of `ArrowInvalid` message.
This now works for any extension type, not just UUID.
```python
import pyarrow as pa
pa.array([pa.scalar(b'1'*16, type=pa.uuid())], type=pa.uuid())
``` 

```
<pyarrow.lib.UuidArray object at 0x128186970>
[
  31313131313131313131313131313131
]
```
* GitHub Issue: #48470

### CODE REVIEW

File: python/pyarrow/src/arrow/python/python_to_arrow.cc [hunk 1]
```diff
@@ -584,6 +584,14 @@ class PyConverter : public Converter<PyObject*, PyConversionOptions> {
...
 };
 
+// Helper function to unwrap extension scalar to its storage scalar
+const Scalar& GetStorageScalar(const Scalar& scalar) {
+  if (scalar.type->id() == Type::EXTENSION) {
+    return *checked_cast<const ExtensionScalar&>(scalar).value;
+  }
+  return scalar;
+}
+
```
Comment (rok) [inline python/pyarrow/src/arrow/python/python_to_arrow.cc:594]: How about using `Result` here?
```suggestion
// Helper function to unwrap extension scalar to its storage scalar
Result<const Scalar*> GetStorageScalar(const Scalar& scalar) {
  if (scalar.type->id() != Type::EXTENSION) {
    return &scalar;
  }
  const auto& extension_scalar = checked_cast<const ExtensionScalar&>(scalar);
  return extension_scalar.value.get();
}
```

File: python/pyarrow/src/arrow/python/python_to_arrow.cc [hunk 2]
```diff
@@ -663,7 +671,8 @@ class PyPrimitiveConverter<
     } else if (arrow::py::is_scalar(value)) {
       ARROW_ASSIGN_OR_RAISE(std::shared_ptr<Scalar> scalar,
                             arrow::py::unwrap_scalar(value));
-      ARROW_RETURN_NOT_OK(this->primitive_builder_->AppendScalar(*scalar));
+      ARROW_RETURN_NOT_OK(
+          this->primitive_builder_->AppendScalar(GetStorageScalar(*scalar)));
```
Comment (rok) [inline python/pyarrow/src/arrow/python/python_to_arrow.cc:675]: If we change to `Result` we'll also need:
```suggestion
      ARROW_ASSIGN_OR_RAISE(const Scalar* storage_scalar, GetStorageScalar(*scalar));
      ARROW_RETURN_NOT_OK(
          this->primitive_builder_->AppendScalar(*storage_scalar));
```

File: python/pyarrow/tests/test_extension_type.py [hunk 3]
```diff
@@ -1486,6 +1486,71 @@ def bytes(self):
...
+            expected = pa.array(values, type=ext_type)
+            assert result.equals(expected)
+
+    # Null handling
+    uuid_type = pa.uuid()
+    scalars = [pa.scalar(b"0123456789abcdef", type=uuid_type),
+               pa.scalar(None, type=uuid_type)]
+    result = pa.array(scalars, type=uuid_type)
+    assert result[0].is_valid and not result[1].is_valid
+
```
Comment (rok) [inline python/pyarrow/tests/test_extension_type.py:1520]: Maybe test `pa.ExtensionScalar.from_storage` path too?
```suggestion
    scalars = [
        pa.ExtensionScalar.from_storage(uuid_type, b"0123456789abcdef"),
        pa.ExtensionScalar.from_storage(uuid_type, None),
    ]
    result = pa.array(scalars, type=uuid_type)
    assert result.to_pylist() == [UUID(bytes=b"0123456789abcdef"), None]
```

File: python/pyarrow/tests/test_extension_type.py [hunk 4]
```diff
@@ -1486,6 +1486,71 @@ def bytes(self):
         pa.scalar(bad)
```
Comment (rok) [inline python/pyarrow/tests/test_extension_type.py:1489]: Should such a test pass or fail?
```suggestion
def test_array_from_mismatched_extension_scalar_type():
    scalar = pa.scalar(b"1" * 16, type=ExampleUuidType())
    with pytest.raises(TypeError):
        pa.array([scalar], type=ExampleUuidType2())
```

**Review by rok — CHANGES_REQUESTED** [review]
Looks good. Some minor change and more extensive tests suggestions.

File: python/pyarrow/tests/test_extension_type.py (hunk 4 above)
Comment (tadeja) [reply python/pyarrow/tests/test_extension_type.py:1489]: I've tried this one and it doesn't raise TypeError - it seems C++ converter doesn't see extension type and can't detect mismatch. A new validation raising TypeError could be added in Python in array.pxi for this but maybe as a follow-up?

Comment (tadeja) [reply python/pyarrow/tests/test_extension_type.py:1489]: @rok I've removed this suggested mismatch test for now ^^

File: python/pyarrow/src/arrow/python/python_to_arrow.cc (hunk 1 above)
Comment (tadeja) [reply python/pyarrow/src/arrow/python/python_to_arrow.cc:594]: Perhaps `Result` is not needed here - if its kind of failure path is unlikely then `const Scalar&` might be better?
Looking at the line 757 check [if (PyValue::IsNull(this->options_, value)) {](https://github.com/tadeja/arrow/blame/02387746bb6235ec73c6ee4f75f616af48b2f50e/python/pyarrow/src/arrow/python/python_to_arrow.cc#L757) ...
( For an (unlikely?) non-None extension scalar with internal storage .value of a null shared_ptr both approaches don't avoid it? )

**Comment by tadeja** [comment]
For the C++ part of changes, @pitrou would you have a chance to take a look?

**Review by rok — APPROVED** [review]

File: python/pyarrow/src/arrow/python/python_to_arrow.cc (hunk 1 above)
Comment (pitrou) [reply python/pyarrow/src/arrow/python/python_to_arrow.cc:594]: `Result` is probably not needed indeed, since no error can be returned here. As you prefer @tadeja.

File: python/pyarrow/tests/test_extension_type.py [hunk 5]
```diff
@@ -1486,6 +1486,62 @@ def bytes(self):
...
 
 
+def test_array_from_extension_scalars():
+    import datetime
```
Comment (pitrou) [inline python/pyarrow/tests/test_extension_type.py]: Can move this stdlib import to the top of file.

**Review by pitrou — APPROVED** [review]
Neat @tadeja ! Just minor suggestions below.

**Review by rok — APPROVED** [review]

**Comment by rok** [comment]
Thanks for sanity check @pitrou! Merging.
