### PR TITLE
GH-36939: [C++][Parquet] Direct put of BooleanArray is incorrect when called several times

### LINKED ISSUE #36939: [C++][Parquet] Boolean encoding has inconsistent implemention
### Describe the bug, including details regarding any error messages, version, and platform.

For `PlainEncoder<BooleanType>`:

1. For Encoding without arrow:

```c++
  void PutSpaced(const bool* src, int num_values, const uint8_t* valid_bits,
                 int64_t valid_bits_offset) override {
    if (valid_bits != NULLPTR) {
      PARQUET_ASSIGN_OR_THROW(auto buffer, ::arrow::AllocateBuffer(num_values * sizeof(T),
                                                                   this->memory_pool()));
      T* data = reinterpret_cast<T*>(buffer->mutable_data());
      int num_valid_values = ::arrow::util::internal::SpacedCompress<T>(
          src, num_values, valid_bits, valid_bits_offset, data);
      Put(data, num_valid_values);
    } else {
      Put(src, num_values);
    }
  }
```

If values contains null, this only puts length for `valid_bits`.

2. For Array

```c++
  void Put(const ::arrow::Array& values) override {
    if (values.type_id() != ::arrow::Type::BOOL) {
      throw ParquetException("direct put to boolean from " + values.type()->ToString() +
                             " not supported");
    }
    ...
    sink_.UnsafeAdvance(data.length());
  }
```

This will always output the length with null. These two implement is inconsistent.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

This is from a bug in PLAIN encoding with `BooleanArray` input. Boolean will introduce bad length when writing arrow data.

This interface is not widely used.

### What changes are included in this PR?

Rewrite PLAIN boolean encoder to use `TypedBufferBuilder` instead of an incorrect hand-baked implementation.

### Are these changes tested?

Yes

### Are there any user-facing changes?

No.

* Closes: #36939

### CODE REVIEW

File: cpp/src/parquet/encoding_test.cc [hunk 1]
```diff
@@ -665,6 +666,33 @@ class EncodingAdHocTyped : public ::testing::Test {
...
+
+    BuilderType acc(arrow_type(), ::arrow::default_memory_pool());
+    ASSERT_EQ(values->length() - values->null_count(),
+              decoder->DecodeArrow(static_cast<int>(values->length()),
+                                   static_cast<int>(values->null_count()),
+                                   values->null_bitmap_data(), values->offset(), &acc));
+
+    std::shared_ptr<::arrow::Array> result;
+    ASSERT_OK(acc.Finish(&result));
+    ASSERT_EQ(100, result->length());
```
[the remark this answers is not in the document]
Comment (wgtmac) [reply cpp/src/parquet/encoding_test.cc:692]: Or values->length() ?

File: cpp/src/parquet/encoding_test.cc [hunk 2]
```diff
@@ -665,6 +666,33 @@ class EncodingAdHocTyped : public ::testing::Test {
     ::arrow::AssertArraysEqual(*values, *result, /*verbose=*/true);
   }
 
+  void PlainTwice(int seed) {
+    auto values_single = GetValues(seed);
```
Comment (wgtmac) [inline cpp/src/parquet/encoding_test.cc:670]:
```suggestion
    auto random_values = GetValues(seed);
```

single looks strange here.

File: cpp/src/parquet/encoding_test.cc [hunk 3]
```diff
@@ -665,6 +666,33 @@ class EncodingAdHocTyped : public ::testing::Test {
     ::arrow::AssertArraysEqual(*values, *result, /*verbose=*/true);
   }
 
+  void PlainTwice(int seed) {
```
Comment (wgtmac) [inline cpp/src/parquet/encoding_test.cc:669]: Is it possible to extend `void Plain(int seed)` to be something like `void Plain(int seed, int round = 1)` to avoid duplicate code?

**Review by wgtmac — CHANGES_REQUESTED** [review]

File: cpp/src/parquet/encoding_test.cc (hunk 3 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding_test.cc:669]: That would be better, I'll do like this tomorrow.

File: cpp/src/parquet/encoding.cc [hunk 4]
```diff
@@ -340,6 +340,8 @@ class PlainEncoder<BooleanType> : public EncoderImpl, virtual public BooleanEnco
       throw ParquetException("direct put to boolean from " + values.type()->ToString() +
                              " not supported");
     }
+    // Put arrow array cannot mix with PlainEncoder<BooleanType>::PutImpl.
+    DCHECK_EQ(0, bit_writer_.bytes_written());
```
[the remark this answers is not in the document]
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:345]: I've update the comment here.

File: cpp/src/parquet/encoding_test.cc [hunk 5]
```diff
@@ -882,6 +894,12 @@ TYPED_TEST(EncodingAdHocTyped, PlainArrowDirectPut) {
   }
 }
 
+TYPED_TEST(EncodingAdHocTyped, PlainArrowDirectPut2) {
```
Comment (wgtmac) [inline cpp/src/parquet/encoding_test.cc:897]:
```suggestion
TYPED_TEST(EncodingAdHocTyped, PlainArrowDirectPutMultiRound) {
```

**Review by wgtmac — APPROVED** [review]

**Comment by wgtmac** [comment]
@pitrou @emkornfield Do you want to take a look?

File: cpp/src/parquet/encoding_test.cc [hunk 6]
```diff
@@ -882,6 +894,12 @@ TYPED_TEST(EncodingAdHocTyped, PlainArrowDirectPut) {
   }
 }
 
+TYPED_TEST(EncodingAdHocTyped, PlainArrowDirectPutMultiRound) {
+  for (auto seed : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}) {
```
Comment (emkornfield) [inline cpp/src/parquet/encoding_test.cc:898]: A random test is great but it would be nice to have a direct test which demonstrates the regression and fix.

File: cpp/src/parquet/encoding.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (emkornfield) [reply cpp/src/parquet/encoding.cc:345]: should this be an exception instead of a dcheck?

File: cpp/src/parquet/encoding.cc [hunk 7]
```diff
@@ -365,7 +369,7 @@ class PlainEncoder<BooleanType> : public EncoderImpl, virtual public BooleanEnco
       }
       writer.Finish();
     }
-    sink_.UnsafeAdvance(data.length());
+    sink_.UnsafeAdvance(data.length() - data.null_count());
```
Comment (emkornfield) [inline cpp/src/parquet/encoding.cc:372]: shouldn't this be n_valid?

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:372]: @emkornfield Parquet encoding stores "valid" value. The invalid value will be marked in rep-levels and def-levels

File: cpp/src/parquet/encoding_test.cc (hunk 6 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding_test.cc:898]: Actually using `round >= 1` point out the error case

File: cpp/src/parquet/encoding.cc (hunk 7 above)
Comment (emkornfield) [reply cpp/src/parquet/encoding.cc:372]: I was referring to the entire value passed into sink_.UnsafeAdvance

This seems like it was incorrect even for all present values because we are advancing the Byte buffer by number of values and not number of bits?

**Comment by emkornfield** [comment]
General question, is this code path actually used in practice?  (should we just delete the code)?

File: cpp/src/parquet/encoding.cc (hunk 7 above)
Comment (emkornfield) [reply cpp/src/parquet/encoding.cc:372]: (i.e. we seem to be advancing by more bytes then are being reserved in both cases)

**Comment by mapleFU** [comment]
> General question, is this code path actually used in practice? (should we just delete the code)?

We use parquet boolean type to store bool value. And this is exposed in python for a long time. So I think:
1. Boolean type is not widely used, otherwise it would be found earier
2. However, I think there're someone using it. So I think we'd better fix this

File: cpp/src/parquet/encoding.cc [hunk 8]
```diff
@@ -354,6 +357,7 @@ class PlainEncoder<BooleanType> : public EncoderImpl, virtual public BooleanEnco
                                                       sink_.length(), n_valid);
```
Comment (emkornfield) [inline cpp/src/parquet/encoding.cc:357]: this line also seems problematic if this method is called multiple times with in a row with boolean arrays (not sure actual code does this though).

File: cpp/src/parquet/encoding.cc (hunk 7 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:372]: Yes, the logic here is confusing, but it's right after my change. When input k boolean values.

1. `sink_.Reserve` will only reserve bytes for bits (k).
2. `sink_.UnsafeAdvance` will advance k bytes.

However, when used, `sink_.length()` will only be regarded as bits. So (2) has a bug, but it works here...

I'd like to fix the bug first, and take time to optimize the code later.

File: cpp/src/parquet/encoding.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:345]: You're right. it's better to be an exception

File: cpp/src/parquet/encoding_test.cc (hunk 6 above)
Comment (emkornfield) [reply cpp/src/parquet/encoding_test.cc:898]: Randomized tests should be a backup.  If there is a known regression, lets add a test for it.

File: cpp/src/parquet/encoding.cc (hunk 8 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:357]: https://github.com/apache/arrow/pull/36972#discussion_r1285158838 
You're right. This would not produce bug if PutArrow is not mixed with PutImpl, but will make Boolean leaves a larger space than expected

File: cpp/src/parquet/encoding.cc (hunk 7 above)
Comment (emkornfield) [reply cpp/src/parquet/encoding.cc:372]: In that case we need to be reserving k bytes and not k/8.  I think this wasn't caught sooner because columnwriter appears to have a specialization for Boolean values that bypasses this method (e.g. I don't think anything but encoder tests will pass if you put `throw exception(....)` in this method in general.

File: cpp/src/parquet/encoding.cc (hunk 8 above)
Comment (emkornfield) [reply cpp/src/parquet/encoding.cc:357]: You mentioned this below, using sink_.length() to store the actual values seems wrong.

**Comment by emkornfield** [comment]
> We use parquet boolean type to store bool value. And this is exposed in python for a long time. So I think:

Yes, I think we got lucky here because I think the python/c++ column writer code calls put_spaced.

**Comment by mapleFU** [comment]
Thats lucky! Maybe I'll just fix like this and add some comments

**Comment by mapleFU** [comment]
@emkornfield I'd like to leave `sink_.AdvanceUnsafe` here, this patch just tent to fix the bug. Glad to find that arrow array encoding is not used.

**Comment by emkornfield** [comment]
> @emkornfield I'd like to leave sink_.AdvanceUnsafe here, this patch just tent to fix the bug. Glad to find that arrow array encoding is not used.

The problem is I think we end up potentially writing out unitialized memory even with the temporary fix.  I think the write "fix" here it likely to just delete this code or fix it properly (and start using it on the write code path).

**Comment by mapleFU** [comment]
https://github.com/apache/arrow/pull/36972#issuecomment-1666737682

I've make it wrong. We're not using Boolean arrow, but I think fix it it's not hard.

File: cpp/src/parquet/encoding_test.cc (hunk 6 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding_test.cc:898]: Added as `TestPlainBooleanArrayEncoding.AdHocRoundTrip`

File: cpp/src/parquet/encoding.cc [hunk 9]
```diff
@@ -340,32 +340,28 @@ class PlainEncoder<BooleanType> : public EncoderImpl, virtual public BooleanEnco
...
     if (data.null_count() == 0) {
-      PARQUET_THROW_NOT_OK(sink_.Reserve(bit_util::BytesForBits(data.length())));
-      // no nulls, just dump the data
-      ::arrow::internal::CopyBitmap(data.data()->GetValues<uint8_t>(1), data.offset(),
-                                    data.length(), sink_.mutable_data(), sink_.length());
+      ArrowPoolVector<bool> boolean_data(data.length(), this->memory_pool());
+      for (int i = 0; i < data.length(); ++i) {
+        boolean_data[i] = data.Value(i);
+      }
+      PutImpl(boolean_data, static_cast<int>(data.length()));
```
Comment (pitrou) [inline cpp/src/parquet/encoding.cc:350]: Won't this be much slower than simply calling `CopyBitmap`?

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:350]: Yes, but it's right :-)

**Comment by mapleFU** [comment]
@pitrou I've change the description

The previous implemention for `Put(BooleanArray)` regard `sink_.size()` as bits, and reserve less of space for it. Seems that we already uses `PutSpace` and `Put` for Boolean ( see ColumnWriter ). I think it's ok to have a naive implemention for convert `BooleanArray` to `std::vector<bool>` and use `PutImpl` to unify them.

**Comment by pitrou** [comment]
@ursabot please benchmark lang=C++

**Comment by pitrou** [comment]
@mapleFU If `BufferBuilder` is incorrect for this, perhaps we should use `TypedBufferBuilder<bool>`? Or, if that doesn't work, handle the accumulation buffer by hand.

**Comment by mapleFU** [comment]
Actually:

1. For non-spaced put: I can enhance `PutImpl` to make it accept a `BooleanArray`.
2. For spaced put, maybe current implemention is ok.

But I think since we already have `PutImpl`, it's better to use same code here.

**Comment by pitrou** [comment]
I'd rather not suffer a potentially significant performance regression here. Ideally, writing a boolean Arrow array would go through this function (I'm not sure why it doesn't).

File: cpp/src/parquet/encoding.cc (hunk 9 above)
Comment (wgtmac) [reply cpp/src/parquet/encoding.cc:350]: Catching up the discussion. If this code path is unused, then probably benchmark cannot catch any regression here.

Comment (pitrou) [reply cpp/src/parquet/encoding.cc:350]: You're right, it seems unused (by us!) for now. But ideally we _should_ use it in `TypedColumnWriterImpl<BooleanType>::WriteArrowDense` (see `column_writer.cc`), instead of wasting CPU time unpacking then repacking the boolean bitmap.

**Comment by mapleFU** [comment]
> I'd rather not suffer a potentially significant performance regression here. Ideally, writing a boolean Arrow array would go through this function (I'm not sure why it doesn't).

Sure I'll rewrite it :-)

But I wonder that how can we optimize `PutSpaced`. Should we just regard it as before?

**Comment by pitrou** [comment]
> But I wonder that how can we optimize PutSpaced. Should we just regard it as before?

For now, yes, but it could perhaps be improved if it's often used.

**Comment by mapleFU** [comment]
I've changed to `bit_writer_.PutValue` try to make non-spaced Put faster.  Though it would still slower than `CopyBitmap`, but I think it's right...

File: cpp/src/parquet/encoding.cc [hunk 10]
```diff
@@ -340,32 +340,41 @@ class PlainEncoder<BooleanType> : public EncoderImpl, virtual public BooleanEnco
       throw ParquetException("direct put to boolean from " + values.type()->ToString() +
                              " not supported");
     }
-
     const auto& data = checked_cast<const ::arrow::BooleanArray&>(values);
+
     if (data.null_count() == 0) {
-      PARQUET_THROW_NOT_OK(sink_.Reserve(bit_util::BytesForBits(data.length())));
-      // no nulls, just dump the data
-      ::arrow::internal::CopyBitmap(data.data()->GetValues<uint8_t>(1), data.offset(),
```
Comment (wgtmac) [inline cpp/src/parquet/encoding.cc:348]: If the problem here is the incorrect use of `sink_.Reserve` and `sink_.UnsafeAdvance`, why not directly fix them? The current change gives me an illusion that `CopyBitmap` and `FirstTimeBitmapWriter` are the root cause of the bug.

Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:348]: You're right...Let me just revert that and correct the `sink_` here.

**Comment by pitrou** [comment]
Again, why not use `TypedBufferBuilder<bool>`?

**Comment by mapleFU** [comment]
> Again, why not use `TypedBufferBuilder<bool>`?

Because `PutImpl` already uses `sink`. And I think `TypedBufferBuilder<bool>` is as slow as current implemention.

**Comment by pitrou** [comment]
`TypedBufferBuilder<bool>` uses `CopyBitmap` internally, so it should be faster. It should also help automate some of the bookkeeping you're doing by hand.

**Comment by mapleFU** [comment]
Okay, I've refactor all into a `TypedBufferBuilder`

File: cpp/src/parquet/encoding_test.cc [hunk 11]
```diff
@@ -641,27 +642,38 @@ class EncodingAdHocTyped : public ::testing::Test {
...
-    ASSERT_NO_THROW(encoder->Put(*values));
+    for (int i = 0; i < round; ++i) {
+      ASSERT_NO_THROW(encoder->Put(*random_array));
+    }
+    std::shared_ptr<::arrow::Array> values;
+    if (round == 1) {
+      values = random_array;
+    } else {
+      ::arrow::ArrayVector arrays;
+      arrays.resize(round, random_array);
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:659]: Small simplification:
```suggestion
      ::arrow::ArrayVector arrays(round, random_array);
```

File: cpp/src/parquet/encoding_test.cc [hunk 12]
```diff
@@ -1627,6 +1645,39 @@ TEST_F(TestRleBooleanEncoding, AllNull) {
       /*null_probability*/ 1));
 }
 
+class TestPlainBooleanEncoding : public TestEncodingBase<BooleanType> {};
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1648]: Is this class used?

File: cpp/src/parquet/encoding_test.cc [hunk 13]
```diff
@@ -1627,6 +1645,39 @@ TEST_F(TestRleBooleanEncoding, AllNull) {
...
+
+TEST(TestPlainBooleanArrayEncoding, AdHocRoundTrip) {
+  std::vector<std::shared_ptr<::arrow::Array>> arrays{
```
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:1651]: Add a comment pointing to the GH issue number?

File: cpp/src/parquet/encoding_test.cc (hunk 6 above)
Comment (pitrou) [inline cpp/src/parquet/encoding_test.cc:898]:
```suggestion
  // Check that one can put several Arrow arrays into a given encoder
  // and decode to the right values (see GH-36939)
  for (auto seed : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}) {
```

**Review by pitrou — CHANGES_REQUESTED** [review]
This is a nice simplification :-)

File: cpp/src/parquet/encoding.cc [hunk 14]
```diff
@@ -340,97 +334,42 @@ class PlainEncoder<BooleanType> : public EncoderImpl, virtual public BooleanEnco
...
-
     const auto& data = checked_cast<const ::arrow::BooleanArray&>(values);
+
     if (data.null_count() == 0) {
-      PARQUET_THROW_NOT_OK(sink_.Reserve(bit_util::BytesForBits(data.length())));
       // no nulls, just dump the data
-      ::arrow::internal::CopyBitmap(data.data()->GetValues<uint8_t>(1), data.offset(),
-                                    data.length(), sink_.mutable_data(), sink_.length());
+      PARQUET_THROW_NOT_OK(sink_.Reserve(data.length()));
+      sink_.UnsafeAppend(data.data()->GetValues<uint8_t>(1), /*offset=*/0, data.length());
```
[the remark this answers is not in the document]
Comment (mapleFU) [reply cpp/src/parquet/encoding.cc:342]: Oh I miss this. Thanks!

File: cpp/src/parquet/encoding_test.cc (hunk 13 above)
Comment (mapleFU) [reply cpp/src/parquet/encoding_test.cc:1652]: done

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly-tests

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly-tests
