### PR TITLE
GH-37487: [C++][Parquet] Dataset: Implement sync `ParquetFileFormat::GetReader`

### LINKED ISSUE #37487: [Python] FileFormat::GetReaderAsync hangs when ARROW_IO_THREADS is set to 1
### Describe the bug, including details regarding any error messages, version, and platform.

```
# test.py
import pyarrow.dataset as pads

ds = pads.dataset("/tmp/test.parq", format="parquet") # can be any parquet
ds.count_rows(use_threads=False)
```
`ARROW_IO_THREADS=1 python test.py` hangs forever. I traced this and it's stuck in `GetReader`.
```
arrow::FutureImpl::Wait
> arrow::dataset::ParquetFileFormat::GetReader
> arrow::dataset::ParquetFileFragment::EnsureCompleteMetadata
```
It works normally if I use any `ARROW_IO_THREADS` larger than 1. I reproduced this on mac with version `13.0.0` and linux with version `12.0.0`.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

As https://github.com/apache/arrow/issues/37487 says. When thread cnt == 1, the thread might blocking in `ParquetFileFormat::GetReaderAsync`, that's because:

1. `ParquetFileFormat::CountRows` would call `EnsureCompleteMetadata` in `io_executor`
2. `EnsureCompleteMetadata` call `ParquetFileFormat::GetReader`, which dispatch real request to async mode
3. `async` is executed in `io_executor`.

1/3 in same fix-sized executor, causing deadlock.

### What changes are included in this PR?

Implement sync `ParquetFileFormat::GetReader`.

### Are these changes tested?

Currently not

### Are there any user-facing changes?

Bugfix

* Closes: #37487

### CODE REVIEW

**Comment by mapleFU** [comment]
@pitrou @westonpace would you mind take a look?

**Comment by mapleFU** [comment]
@westonpace By the way, call Blocking Get in same thread pool might cause the deadlock, should we try to find out which would causing this and trying to fix them?

**Comment by westonpace** [comment]
I'll try and look in more detail later today but here is the general advice.

Async methods which return a future.
Sync methods do not

User calls always start out as synchronous methods (e.g. we don't have adapters for python's asyncio)

We can convert from synchronous to asynchronous using something like...

```
... Foo(...) {
    Future<...> fut = FooAsync(...);
    return fut.result();
}
```

This is ok.  One conversion from synchronous to asynchronous is ok and inevitable (since user calls start as sync).

However, it is not ok to convert from asynchronous to synchronous.  For example, if `Foo` is defined as above then this would not be ok:

```
... BarAsync(...) {
   Future<...> fut = SomeAsyncMethod();
   return fut.Then([&] (...) {
       return Foo(...);
   });
}
```

This is also not ok:

```
... BarAsync(...) {
    auto x = Foo(...);
    return SomeAsyncMethod(x, ...);
}
```

Normally the fix is for `BarAsync` to call `FooAsync`.

Creating a `Bar` that is a synchronous method that mirrors `BarAsync` is ok, but leads to more code.

At a glance, it looks like that is what is happening here, which is maybe ok.  However, I have to look in more detail.

**Comment by mapleFU** [comment]
Thanks for your nice advice!

I think this patch would be OK, I can check more Async usage around dataset.

**Comment by mapleFU** [comment]
@westonpace can we try to review this patch first? Since I believe at least this patch might solve the problem :-)

**Comment by mapleFU** [comment]
@pitrou Would you mind help take a look? Since the logic is easy and simple here...

**Comment by mapleFU** [comment]
ping @pitrou @westonpace for help...

**Comment by bkietz** [comment]
This isn't tested and we don't have follow up from the original issue's poster that this patch fixes the deadlock.

@mapleFU could you add (something like) the original repro as a test? It'd be best if we can confirm that `main` hangs with a single IO thread and `use_threads=False`, then confirm that we no longer hang with this fix.
```python
# test.py
import pyarrow.dataset as pads

ds = pads.dataset("/tmp/test.parq", format="parquet") # can be any parquet
ds.count_rows(use_threads=False)

ARROW_IO_THREADS=1 python test.py
```

@yiteng-guo could you try out this patch and confirm it fixes the deadlock for you?

**Comment by mapleFU** [comment]
Hi @bkietz , I've write a test using a extended file-reader, it can reproduce the case.

```
class AsyncBufferReader : public ::arrow::io::BufferReader {
 public:
  explicit AsyncBufferReader(std::shared_ptr<Buffer> buffer, const ::arrow::io::IOContext& ctx): ::arrow::io::BufferReader(std::move(buffer)), ctx_(ctx) {}
  /// EXPERIMENTAL: Read data asynchronously.
  Future<std::shared_ptr<Buffer>> ReadAsync(const ::arrow::io::IOContext& ctx, int64_t position,
                                            int64_t nbytes) override {
    auto self = checked_pointer_cast<AsyncBufferReader>(shared_from_this());
    return DeferNotOk(ctx.executor()->Submit([self, position, nbytes]() {
      return self->ReadAt(position, nbytes);
    }));
  }

  const ::arrow::io::IOContext& io_context() const override {
    return ctx_;
  }

  private:
   ::arrow::io::IOContext ctx_;
};
```

However, default io-pool is widely used in scanner, it's a bit hard to hook all io_context( Might need to change `EnsureCompleteMetadata` to below) :

```c++
Status EnsureCompleteMetadata(parquet::arrow::FileReader* reader = NULLPTR, const std::shared_ptr<ScanOptions>& scan_options=NULLPTR);
```

So I change the global thread pool during testing, would you mind take a look?

File: cpp/src/arrow/dataset/file_parquet.cc [hunk 1]
```diff
@@ -410,13 +410,50 @@ Result<std::shared_ptr<Schema>> ParquetFileFormat::Inspect(
...
+
+  auto reader_opt = open_parquet_file();
+  if (!reader_opt.ok()) {
+    return WrapSourceError(reader_opt.status(), source.path());
+  }
+  auto reader = std::move(reader_opt).ValueOrDie();
+
+  std::shared_ptr<parquet::FileMetaData> reader_metadata = reader->metadata();
+  auto arrow_properties = MakeArrowReaderProperties(*this, *reader_metadata);
+  arrow_properties.set_batch_size(options->batch_size);
```
Comment (bkietz) [inline cpp/src/arrow/dataset/file_parquet.cc:444]: Please extract as much repeated code as possible to helper/private member functions. For example, ArrowReaderPropertiesFromOptions or add an optional ScanOptions argument to MakeArrowReaderProperties

File: cpp/src/arrow/dataset/file_parquet_test.cc [hunk 2]
```diff
@@ -367,6 +369,69 @@ TEST_F(TestParquetFileFormat, MultithreadedScan) {
...
+      Status s = pool->SetCapacity(origin_capacity);
+      if (!s.ok()) {
+        std::cerr << "Failed to reset pool capacity: " << s.ToString() << std::endl;
+      }
+    }
+
+    ::arrow::internal::ThreadPool* pool;
+    int origin_capacity;
+  };
+  PoolResetGuard guard(pool_executor, origin_capacity);
```
Comment (bkietz) [inline cpp/src/arrow/dataset/file_parquet_test.cc:415]: I think you can use `SetIOThreadPoolCapacity` and `GetIOThreadPoolCapacity` here:

```suggestion
  // Reset capacity for pool_executor
  struct PoolResetGuard {
    int original_capacity = io::GetIOThreadPoolCapacity();
    ~PoolResetGuard() {
      DCHECK_OK(io::SetIOThreadPoolCapacity(original_capacity));
    }
  } guard;
```

Since this directly mutates the IO thread pool (pointed to by the default IO context), you shouldn't need `AsyncBufferReader::ReadAsync`

I agree that it's odd `BufferReader::ReadAsync` and `MemoryMappedFile::ReadAsync` (the only overrides I see) ignore the io context argument. @lidavidm do you think they should transfer to the other executor if it's different?

**Review by bkietz — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/dataset/file_parquet_test.cc (hunk 2 above)
Comment (mapleFU) [reply cpp/src/arrow/dataset/file_parquet_test.cc:415]: > I agree that it's odd BufferReader::ReadAsync and MemoryMappedFile::ReadAsync (the only overrides I see) ignore the io context argument

I think `BufferReader::ReadAsync` is so lightweight that we can ignore it?

**Comment by mapleFU** [comment]
@bkietz I've tried to resolve the comments, would you mind take a look again?

File: cpp/src/arrow/dataset/file_parquet_test.cc (hunk 2 above)
Comment (lidavidm) [reply cpp/src/arrow/dataset/file_parquet_test.cc]: Given both access memory/"memory" I think that's quite intentional

**Review by bkietz — APPROVED** [review]
LGTM, thanks!
