### PR TITLE
GH-39584: [R] fallback to source gracefully

### LINKED ISSUE #39584: [R] Macos build cleanups
### Describe the bug, including details regarding any error messages, version, and platform.

We need to clean up:

- [x] don't checksum something that hasn't been downloaded
- [x] bundle boost if macos build from source to avoid thrift errors
- [x] test on macbuilder (with a malignant source build)

### Component(s)

R

### PR DESCRIPTION
**Pull request by jonkeane**
### Rationale for this change

Resolves #39584 

### What changes are included in this PR?

We now only check the checksum after the download succeeded, and try to be quieter about it when we do. We also use bundled boost and lz4 source on macos by default (to avoid system versions of each on cran that seem to have issues)

### Are these changes tested?

I submitted a download-malignant (and verbose) build to [CRAN's macbuilder](https://mac.r-project.org/macbuilder/results/1705088784-991a5beacf4ec26e/) and it succeeds.

### Are there any user-facing changes?

In principle the macos source build is slightly altered + we have a cleaner path when file downloads fail. But both of these should be relatively non-impactful since most macos users are getting binaries from CRAN. Most importantly it helps us stay on CRAN. 

**This PR contains a "Critical Fix".**
* Closes: #39584

### CODE REVIEW

File: r/tools/nixlibs.R [hunk 1]
```diff
@@ -96,53 +96,76 @@ try_download <- function(from_url, to_file, hush = quietly) {
...
-  binary_url <- paste0(arrow_repo, "bin/", lib, "/arrow-", VERSION, ".zip")
-  if (try_download(binary_url, libfile)) {
-      lg("Successfully retrieved libarrow (%s)", lib)
-  } else {
-      lg(
-        "Downloading libarrow failed for version %s (%s)\n    at %s",
-        VERSION, lib, binary_url
-      )
-    libfile <- NULL
-  }
```
Comment (jonkeane) [inline r/tools/nixlibs.R:110]: The way that GH is rendering this change is awkward because I factored the checksumming out into a function. It might be easier to review in split diff and not unified

File: r/tools/nixlibs.R [hunk 2]
```diff
@@ -539,10 +562,25 @@ build_libarrow <- function(src_dir, dst_dir) {
     env_var_list <- c(env_var_list, ARROW_DEPENDENCY_SOURCE = "BUNDLED")
   }
 
+  # On macOS, if not otherwise set, let's override Boost_SOURCE to be bundled
+  if (on_macos) {
+    deps_to_bundle <- c("Boost", "lz4")
+    for (dep_to_bundle in deps_to_bundle) {
+      env_var <- paste0(dep_to_bundle, "_SOURCE")
+      if (Sys.getenv(env_var) == "") {
```
Comment (jonkeane) [inline r/tools/nixlibs.R:570]: We might _also_ want to check `Sys.getenv(toupper(env_var))` here in case someone also has the upper variant laying around. But this should be very rare (and only really developers)

File: r/tools/nixlibs.R [hunk 3]
```diff
@@ -539,10 +562,25 @@ build_libarrow <- function(src_dir, dst_dir) {
...
+    }
+  }
+
   env_var_list <- with_cloud_support(env_var_list)
 
   # turn_off_all_optional_features() needs to happen after
   # with_cloud_support(), since it might turn features ON.
+  # TODO: could we, should we have download_ok also include "download has succeeded"
+  # so we can disable these things if someone's machine is suddenly offline but they
+  # find themselves here and demand a working compilation?
```
Comment (jonkeane) [inline r/tools/nixlibs.R:583]: Though it should be noted that we _always_ need a modern cmake even if we are skipping all of the optional dependencies, so this won't give us a fully offline build in that case (old cmake + no internet)

**Review by thisisnic — APPROVED** [review]
Looks good to me; changes make sense and additional comments are helpful for clarification, though would like another set of eyes on it before merging.

File: r/tools/nixlibs.R (hunk 2 above)
Comment (thisisnic) [reply r/tools/nixlibs.R:570]: No harm in adding it just in case?

File: r/inst/build_arrow_static.sh [hunk 4]
```diff
@@ -74,6 +74,8 @@ ${CMAKE} -DARROW_BOOST_USE_SHARED=OFF \
     -DARROW_DATASET=${ARROW_DATASET:-ON} \
     -DARROW_DEPENDENCY_SOURCE=${ARROW_DEPENDENCY_SOURCE:-AUTO} \
     -DAWSSDK_SOURCE=${AWSSDK_SOURCE:-} \
+    -DBoost_SOURCE=${BOOST_SOURCE:-} \
+    -Dlz4_SOURCE=${LZ4_SOURCE:-} \
```
Comment (kou) [inline r/inst/build_arrow_static.sh:78]: How about using same name for CMake variable? (We did so for `re2_SOURCE`/`xsimd_SOURCE`/`zstd_SOURCE`.)

```suggestion
    -DBoost_SOURCE=${Boost_SOURCE:-} \
    -Dlz4_SOURCE=${lz4_SOURCE:-} \
```

File: r/tools/nixlibs.R (hunk 2 above)
Comment (assignUser) [reply r/tools/nixlibs.R:570]: \<Dependency\>_SOURCE is actually a CMake only variable outside of the few variants we use in `build_arrow_static.sh` (a fact that cost me 2 hours debugging a workflow change once xD). So it should be fine to only check the _right_ version.

**Comment by assignUser** [comment]
@github-actions crossbow submit -g r

**Review by assignUser — APPROVED** [review]
Thanks, this is great! I have kicked of a round of crossbow jobs but don't anticipate any issues.

File: r/tools/nixlibs.R [hunk 5]
```diff
@@ -96,53 +96,76 @@ try_download <- function(from_url, to_file, hush = quietly) {
...
-      unlink(libfile)
-      libfile <- NULL
-    } else {
-      lg("Checksum validated successfully for libarrow: %s/%s", lib, libfile)
+        if (checksum_ok != 0) {
+          lg("Checksum validation failed for libarrow: %s/%s", lib, libfile)
+          unlink(libfile)
+          stop("The checksum failed")
+        } else {
+          lg("Checksum validated successfully for libarrow: %s/%s", lib, libfile)
```
Comment (assignUser) [inline r/tools/nixlibs.R:138]: `lib` isn't available https://github.com/ursacomputing/crossbow/actions/runs/7508393664/job/20443922655#step:13:1612
probably easiest just to pass it as another arg

File: r/tools/nixlibs.R [hunk 6]
```diff
@@ -96,53 +96,76 @@ try_download <- function(from_url, to_file, hush = quietly) {
...
-    checksum_args <- c("--status", "-a", "512", "-c", checksum_file)
-
-    # shasum is not available on all linux versions
-    status_shasum <- try(
-      suppressWarnings(
-        system2("shasum", args = c("--help"), stdout = FALSE, stderr = FALSE)
-      ),
-      silent = TRUE
-    )
+  # we do this in a try so that if it fails for any reason, we don't pollute the log
```
Comment (nealrichardson) [inline r/tools/nixlibs.R:106]: Pollute with what? Might it be useful debug information if it fails? There are already a bunch of trys inside here, this feels unnecessary.

File: r/tools/nixlibs.R [hunk 7]
```diff
@@ -96,53 +96,76 @@ try_download <- function(from_url, to_file, hush = quietly) {
...
 
-    if (inherits(status_shasum, "try-error") || is.integer(status_shasum) && status_shasum != 0) {
-      checksum_cmd <- "sha512sum"
-      checksum_args <- c("--status", "-c", checksum_file)
-    }
+        # if shasum doens't exist, then change the command to sha512sum
+        if (inherits(status_shasum, "try-error") || is.integer(status_shasum) && status_shasum != 0) {
+          checksum_cmd <- "sha512sum"
+          checksum_args <- c("--status", "-c", checksum_file)
+        }
```
Comment (nealrichardson) [inline r/tools/nixlibs.R:129]: (I know this is just moved and not new code but) to me this would be more readable in its intent like:

```

# Check for `shasum`, and try `sha512sum` if not found
if (nzchar(Sys.which("shasum"))) {
  checksum_cmd <- "shasum"
  checksum_args <- c("--status", "-a", "512", "-c", checksum_file)
} else {
  checksum_cmd <- "sha512sum"
  checksum_args <- c("--status", "-c", checksum_file)
}

File: r/tools/nixlibs.R [hunk 8]
```diff
@@ -96,53 +96,76 @@ try_download <- function(from_url, to_file, hush = quietly) {
...
-    if (checksum_ok != 0) {
-      lg("Checksum validation failed for libarrow: %s/%s", lib, libfile)
-      unlink(libfile)
-      libfile <- NULL
-    } else {
-      lg("Checksum validated successfully for libarrow: %s/%s", lib, libfile)
+        if (checksum_ok != 0) {
+          lg("Checksum validation failed for libarrow: %s/%s", lib, libfile)
+          unlink(libfile)
+          stop("The checksum failed")
```
Comment (nealrichardson) [inline r/tools/nixlibs.R:136]: I don't think you need these, IIUC `download_binary()` will do the unlinking

```suggestion
```

File: r/tools/nixlibs.R [hunk 9]
```diff
@@ -96,53 +96,76 @@ try_download <- function(from_url, to_file, hush = quietly) {
...
-      checksum_args <- c("--status", "-c", checksum_file)
-    }
+        # if shasum doens't exist, then change the command to sha512sum
+        if (inherits(status_shasum, "try-error") || is.integer(status_shasum) && status_shasum != 0) {
+          checksum_cmd <- "sha512sum"
+          checksum_args <- c("--status", "-c", checksum_file)
+        }
 
-    checksum_ok <- system2(checksum_cmd, args = checksum_args)
+        checksum_ok <- system2(checksum_cmd, args = checksum_args)
```
Comment (nealrichardson) [inline r/tools/nixlibs.R:131]: I might make this `checksum_ok <- system2(checksum_cmd, args = checksum_args) == 0`. 

Then your message is based on `if(checksum_ok)`, and you return `checksum_ok` from the function.

File: r/tools/nixlibs.R (hunk 5 above)
Comment (nealrichardson) [reply r/tools/nixlibs.R:138]: Cleaner would be to drop it from the message here, the next message printed (in `download_binary()`) will include `lib` so it's not needed.

Comment (nealrichardson) [reply r/tools/nixlibs.R:138]: In fact, you can probably just say "Checksum validated/failed". (Might be nice to print the checksum here, or even show the output of shasum, in case it's useful to show receipts.)

File: r/tools/nixlibs.R (hunk 7 above)
Comment (jonkeane) [reply r/tools/nixlibs.R:129]: Agreed that is much cleaner + more readable. Slight tangent: this current code I was baffled by cause I didn't get at first that the call to shasum was `--help` just to identify it (I thought we were trying once and if failing falling back to sha512sum which is a totally valid otherway to do things).

 @assignUser is there any specific reason you shell out to help rather than what Neal's suggesting here? There aren't any comments to suggest this approach isn't better but want to give you a chance to add some commentary here.

File: r/inst/build_arrow_static.sh (hunk 4 above)
Comment (jonkeane) [reply r/inst/build_arrow_static.sh:78]: Happy to change these — they are currently all caps due to the comment above this one: https://github.com/apache/arrow/pull/39587/files#r1450998393

We have separate code that is demanding all env vars are supposed to be all caps, so I just fit into that paradigm (and for a smaller patch) but I'm happy to remove that here and now.

File: r/tools/nixlibs.R (hunk 3 above)
Comment (jonkeane) [reply r/tools/nixlibs.R:583]: > So this would really just be for cases where the internet goes down mid run.

It also could happen on a CRAN system which has old cmake + is offline and is attempting to check. If that does happen, we should ask about upgrading cmake to modern versions (like is documented in their docs is how it is supposed to be).

File: r/tools/nixlibs.R (hunk 2 above)
Comment (jonkeane) [reply r/tools/nixlibs.R:570]: Given kou's comment (and my incoming changes to use the mix-case version) I think I'll keep this as mixed case to match the (current) cmake args. I probably should also add this to the documentation of our build variables in the package

File: r/tools/nixlibs.R (hunk 9 above)
Comment (jonkeane) [reply r/tools/nixlibs.R:131]: _nods_ yeah, I tried to be as tactical as possible (at least with the first pass) so it was clear I was taking the same code and moving it not changing behavior (too much).

But agreed, I'll clean it up in a bit in this PR so what we have here going forward is nicer

File: r/tools/nixlibs.R (hunk 6 above)
Comment (jonkeane) [reply r/tools/nixlibs.R:106]: Like I said in a comment below: I'll clean this up and I'll also pull this level of nesting out too while I'm at it. 

The main reason I kept it was the second checksum doesn't eat it's own output and the unlink step could fail. 

Of those, the second is likely not possible / never going to happen given this structure, but the first might do something we don't want. I'll wrap that in a try + clean this up so that we're checking the output of the command there.

File: r/inst/build_arrow_static.sh (hunk 4 above)
Comment (kou) [reply r/inst/build_arrow_static.sh:78]: I see.

But it (all caps) may not work for existing `re2_SOURCE`/`xsimd_SOURCE`/`zstd_SOURCE`: https://github.com/apache/arrow/blob/87ed8ac432dc7e77fa0275a24e3edda9b0bc2a2e/r/inst/build_arrow_static.sh#L100-L102

(Sorry. I haven't execute these scripts. I just read the existing codes.)

Comment (jonkeane) [reply r/inst/build_arrow_static.sh:78]: _nods_ yeah, those should have been untouched in this case, but regardless I've taken your suggestion here and made these match the cmake args through out. Thanks!

File: r/tools/nixlibs.R (hunk 8 above)
Comment (jonkeane) [reply r/tools/nixlibs.R:136]: Definitely don't need the stop, but I'm not seeing a place this would be unlinked before we start building (it might get cleaned up in the teardown generally.

I'm going to leave it be for now. `unlink` also _won't error_ if you try and unlink something that exists, which is a bit surprising frankly, but good for us in this case.

File: r/inst/build_arrow_static.sh (hunk 4 above)
Comment (jonkeane) [reply r/inst/build_arrow_static.sh]: This is done now. Thank you again for the suggestion

File: r/tools/nixlibs.R (hunk 5 above)
Comment (jonkeane) [reply r/tools/nixlibs.R]: This is done now, thanks

File: r/tools/nixlibs.R (hunk 7 above)
Comment (jonkeane) [reply r/tools/nixlibs.R]: I'm not going to resolve this yet, but I've updated the logic here to simplify. @assignUser could you take a look and ensure that this new flow is matching what your intent was in the first round?

File: r/tools/nixlibs.R [hunk 10]
```diff
@@ -116,33 +105,56 @@ download_binary <- function(lib) {
   # validate binary checksum for CRAN release only
   if (!skip_checksum && dir.exists(checksum_path) && is_release ||
     enforce_checksum) {
```
Comment (jonkeane) [inline r/tools/nixlibs.R:107]: With this logic now we will skip the checksum (in this case, get to this function and then reply with `checksum_ok == TRUE` if any of these are true:

* the skip var is set
* it's not a release
* the directory `tools/checksums` does not exist

Is that last one right? I get that we're trying to be protective here, and if there's no checksum file we will fail the checksum. But do we want to have this particular escape hatch here rather than failing the checksum (and then presumably building from source)?

Thoughts @assignUser ?

File: r/tools/nixlibs.R [hunk 11]
```diff
@@ -116,33 +105,56 @@ download_binary <- function(lib) {
...
+    if (nzchar(Sys.which("shasum"))) {
+      checksum_cmd <- "shasum"
+      checksum_args <- c("--status", "-a", "512", "-c", checksum_file)
+    } else {
       checksum_cmd <- "sha512sum"
       checksum_args <- c("--status", "-c", checksum_file)
     }
 
-    checksum_ok <- system2(checksum_cmd, args = checksum_args)
+    checksum_ok <- system2(checksum_cmd, args = checksum_args) == 0
```
Comment (jonkeane) [inline r/tools/nixlibs.R:122]: This now (and maybe it did before and I just didn't notice it) will produce output in the log from the command. See below when I'm enforcing checksumming on a non-release (with no checksum file):

```
*** Latest available nightly for 14.0.2.9000: 14.0.2.100000424
*** Found libcurl and OpenSSL >= 3.0.0
shasum: tools/checksums/darwin-x86_64-openssl-3.0/arrow-14.0.2.100000424.zip.sha512: No such file or directory
*** Checksum validation failed for libarrow
*** Unable to retrieve libarrow for version 14.0.2.100000424 (darwin-x86_64-openssl-3.0)
*** Found local C++ source: 'tools/cpp'
*** Building libarrow from source
```

This is probably ok (and in fact @nealrichardson asked if this is what we wanted in another comment), but I wanted to confirm with everyone here this is the behavior + what we will get.

**Comment by jonkeane** [comment]
This is ready fro review again

**Comment by jonkeane** [comment]
@github-actions crossbow submit -g r

**Comment by jonkeane** [comment]
The r-binary job fails on windows. It doesn't look related, but can you confirm that @assignUser ?

Did test-r-rhub-ubuntu-gcc-release-latest timeout? It looks like it did install, but later in the check failed (possibly during tests?). Regardless, it doesn't look related, but is strange.

```
* checking tests ...
  Running ‘testthat.R’
Error: R CMD check process failed with exit status -9

Standard output and error:
* using log directory ‘/arrow/r/check/arrow.Rcheck’
* using R version 4.3.2 (2023-10-31)
* using platform: x86_64-pc-linux-gnu (64-bit)
* R was compiled by
    gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
    GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
* running under: Ubuntu 20.04.6 LTS
* using session charset: UTF-8
* using options ‘--run-donttest --no-manual --ignore-vignettes’
* checking for file ‘arrow/DESCRIPTION’ ... OK
* this is package ‘arrow’ version ‘14.0.2.9000’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether packag
Execution halted
1
```

File: r/tools/nixlibs.R [hunk 12]
```diff
@@ -116,33 +105,56 @@ download_binary <- function(lib) {
...
-      ),
-      silent = TRUE
-    )
 
-    if (inherits(status_shasum, "try-error") || is.integer(status_shasum) && status_shasum != 0) {
+    # Check for `shasum`, and try `sha512sum` if not found
+    if (nzchar(Sys.which("shasum"))) {
+      checksum_cmd <- "shasum"
+      checksum_args <- c("--status", "-a", "512", "-c", checksum_file)
+    } else {
```
Comment (assignUser) [inline r/tools/nixlibs.R:117]: I think this is the reason for the windows fail. It seems to run in the git bash not rtools bash so finds shasum in the gitbash path but that then[ fails to work](https://github.com/ursacomputing/crossbow/actions/runs/7520694560/job/20470863023#step:18:62). The previous version tries to run that and falls back on sha256sum (which comes with rtools).

Comment (jonkeane) [reply r/tools/nixlibs.R:117]: Ooph, thanks for digging into that.

I'll send a fix for that.

**Comment by jonkeane** [comment]
@github-actions crossbow submit r-binary-packages

File: r/tools/nixlibs.R [hunk 13]
```diff
@@ -116,33 +105,64 @@ download_binary <- function(lib) {
...
+      system2(
+        "shasum",
+        args = c("--status", "-a", "512", "-c", checksum_file),
+        stdout = FALSE,
+        stderr = FALSE
+      ) == 0
+    },
+    error = function(e) {
+      system2(
+        "shasum",
```
Comment (nealrichardson) [inline r/tools/nixlibs.R:124]: If I read the old code correctly, this should be 
```suggestion
        "sha512sum",
```

Comment (jonkeane) [reply r/tools/nixlibs.R]: Ack yes, of course copy-pasta mistake 🤦

**Comment by jonkeane** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by jonkeane** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by jonkeane** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by jonkeane** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by jonkeane** [comment]
@github-actions crossbow submit r-binary-packages

File: r/tools/nixlibs.R [hunk 14]
```diff
@@ -116,33 +105,66 @@ download_binary <- function(lib) {
...
+      )) == 0
+
+    if (!checksum_ok) {
+      checksum_ok <- suppressWarnings(system2(
+        "sha512sum",
+        args = c("--status", "-c", checksum_file),
+        stdout = ifelse(quietly, FALSE, ""),
+        stderr = ifelse(quietly, FALSE, "")
+      )) == 0
     }
```
Comment (jonkeane) [inline r/tools/nixlibs.R:132]: OOPH this was fun to deal with. I tried a bunch of things (after forgetting how system2 handles errors that it gets from the shell) and this is the most clean way I could get it working given the oddity of shasum _existing_ when checked, but not functional on some platforms (i.e. windows).

I tried to get as much detail as I could about the various oddities in the comment for future-us, but LMK if there's more I should add here.

The binary job is clean 🎉

File: r/tools/nixlibs.R (hunk 3 above)
Comment (assignUser) [reply r/tools/nixlibs.R:582]:
```suggestion
```
With cmake now in the sys reqs this comment can be removed.

File: r/tools/nixlibs.R [hunk 15]
```diff
@@ -539,10 +561,25 @@ build_libarrow <- function(src_dir, dst_dir) {
     env_var_list <- c(env_var_list, ARROW_DEPENDENCY_SOURCE = "BUNDLED")
   }
 
+  # On macOS, if not otherwise set, let's override Boost_SOURCE to be bundled
```
Comment (assignUser) [inline r/tools/nixlibs.R:564]:
```suggestion
  # On macOS, if not otherwise set, let's override Boost_SOURCE to be bundled 
  # Necessary due to #39590 for CRAN 
```

**Review by assignUser — APPROVED** [review]
Looks good, thanks! I will add the minor comment changes and merge in a bit unless there are objections.

File: r/tools/nixlibs.R (hunk 14 above)
Comment (assignUser) [reply r/tools/nixlibs.R:132]: Nice

File: r/tools/nixlibs.R (hunk 7 above)
Comment (assignUser) [reply r/tools/nixlibs.R]: Ah I missed this initially
