### PR TITLE
GH-35095: [C++] Prevent write after close in arrow::ipc::IpcFormatWriter

### LINKED ISSUE #35095: [C++] RecordBatchWriter::Close does not prevent future writes
### Describe the bug, including details regarding any error messages, version, and platform.

```python
import pyarrow as pa

data = [
    pa.array([1, 2, 3, 4]),
    pa.array(['foo', 'bar', 'baz', None]),
    pa.array([True, None, False, True])
]

batch = pa.record_batch(data, names=['f0', 'f1', 'f2'])

f = pa.ipc.new_stream('test.arrow', batch.schema)
f.write_batch(batch)
f.close()
# still writable
f.write_batch(batch)

with pa.ipc.new_file('test2.arrow', batch.schema) as f2:
    f2.write_batch(batch)
# still writable
f2.write_batch(batch)
```

Maybe related to #34423?
I tried with `gc` but no luck.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by chrisjordansquire**
This addresses GH-35095 by adding a flag to IpcFormatWriter to track when a writer has been closed, and check this flag before writes.

### Rationale for this change

This addresses #35095 , preventing stream and file IPC writers from writing record batches once the IPC writer has been closed. 

### What changes are included in this PR?

Adding a flag so that an IpcFormatWriter to track when it's been closed, a check before writes in IpcFormatWriter, and two tests to confirm it works as expected. 

### Are these changes tested?

Yes, the changes are tested. The two tests were added, and the C++ test suite ran. No unexpected failures appeared. 

### Are there any user-facing changes?

Other than newly returning an invalid status when writing after close, no, there should not be any user-facing changes. 

* Closes: #35095

### CODE REVIEW

File: cpp/src/arrow/ipc/read_write_test.cc [hunk 1]
```diff
@@ -1519,6 +1519,23 @@ class ReaderWriterMixin : public ExtensionTypesMixin {
...
+    std::shared_ptr<Schema> schema = batch_ints->schema();
+
+    WriterHelper writer_helper;
+    ASSERT_OK(writer_helper.Init(schema, IpcWriteOptions::Defaults()));
+    ASSERT_OK(writer_helper.WriteBatch(batch_ints));
+    ASSERT_OK(writer_helper.Finish());
+
+    // Write after close raises status
+    auto foo = writer_helper.WriteBatch(batch_ints);
+    // ASSERT_RAISES(Invalid, writer_helper.WriteBatch(batch_ints));
```
Comment (kou) [inline cpp/src/arrow/ipc/read_write_test.cc:1536]: Why is this assertion commented out?

Comment (chrisjordansquire) [reply cpp/src/arrow/ipc/read_write_test.cc]: Whoops. An extremely embarrassing mistake. Thank you for catching it. It's been fixed.

File: cpp/src/arrow/ipc/writer.cc [hunk 2]
```diff
@@ -1070,6 +1070,9 @@ class ARROW_EXPORT IpcFormatWriter : public RecordBatchWriter {
   Status WriteRecordBatch(
       const RecordBatch& batch,
       const std::shared_ptr<const KeyValueMetadata>& custom_metadata) override {
+    if (closed_) {
+      return Status::Invalid("Destination already closed");
+    }
```
Comment (kou) [inline cpp/src/arrow/ipc/writer.cc:1075]: Do we need similar check in `WriteTable` too?

Comment (chrisjordansquire) [reply cpp/src/arrow/ipc/writer.cc:1075]: Good question. 
It appears that WriteTable ultimately calls WriteRecordBatch. This appears to be documented as well, in that the documentation for RecordBatchWriter::WriteTable is that a a table is written by creating a sequence of record batches. So testing WriteTable doesn't seem to be necessary.

File: cpp/src/arrow/ipc/read_write_test.cc [hunk 3]
```diff
@@ -1519,6 +1519,22 @@ class ReaderWriterMixin : public ExtensionTypesMixin {
     }
   }
 
+  void TestWriteAfterClose() {
+    // Part of GH-35095.
+    std::shared_ptr<RecordBatch> batch_ints;
+    ASSERT_OK(MakeIntRecordBatch(&batch_ints));
+
+    std::shared_ptr<Schema> schema = batch_ints->schema();
```
Comment (kou) [inline cpp/src/arrow/ipc/read_write_test.cc:1527]:
```suggestion
    auto schema = batch_ints->schema();
```

File: cpp/src/arrow/ipc/writer.cc (hunk 2 above)
Comment (kou) [reply cpp/src/arrow/ipc/writer.cc:1075]: Thanks. I see.

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
Could you check the "C++ / AMD64 Ubuntu 22.04 C++ ASAN UBSAN" failure?

https://github.com/apache/arrow/actions/runs/6242111241/job/16945464958?pr=37783#step:6:3569

```text
==15144==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
...
```

**Comment by chrisjordansquire** [comment]
Yep, taking a look. Rebasing on main first, in case it was fixed elsewhere.

**Comment by kou** [comment]
Oh, the failure has gone.
It'll not be related to this change.
I'll merge this.
