### PR TITLE
GH-34262: [C++][ORC] Support union type

### LINKED ISSUE #34262: [C++] Support for union type in ORC writer
### Describe the enhancement requested

I've built an union manually with `pa.UnionArray.from_dense()`, not using inference,

In python I'm trying to write that union to an ORC file and I'm getting the following error:

```
pyarrow.lib.ArrowNotImplementedError: Unknown or unsupported Arrow type: dense_union<int64: int64=0, float64: double=1, string: string=2>
```

It seems that this in not supported even in C++ code that, IMO, python uses:

https://github.com/apache/arrow/blob/f2d632e727d4eb7e8a693354c9116ea2518e50a6/cpp/src/arrow/adapters/orc/util.cc#L920

Any plans on adding this feature to arrow?

### Component(s)

C++, Python

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

The ORC adapter does not support union type yet.

### What changes are included in this PR?

Support union type to both ORC reader and writer.

### Are these changes tested?

To be added.

### Are there any user-facing changes?

No.
* Closes: #34262

### CODE REVIEW

**Comment by wgtmac** [comment]
@westonpace @wjones127 Could you take a look please?

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 1]
```diff
@@ -840,6 +840,23 @@ TEST_F(TestORCWriterSingleArray, WriteListOfMap) {
...
+      sparse_union({field("_union_0", utf8()), field("_union_1", int32())}, {0, 1});
+  auto array = checked_pointer_cast<SparseUnionArray>(rand.ArrayOf(type, num_rows, 0.4));
+  ArrayVector children;
+  for (int i = 0; i < array->num_fields(); ++i) {
+    ASSERT_OK_AND_ASSIGN(auto flattened_child, array->GetFlattenedField(i));
+    children.emplace_back(std::move(flattened_child));
+  }
+  auto flattened_array = std::make_shared<SparseUnionArray>(
+      array->type(), array->length(), std::move(children), array->type_codes(),
+      array->offset());
```
Comment (westonpace) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:855]: Why is this flattening needed?

File: cpp/src/arrow/adapters/orc/util.cc [hunk 2]
```diff
@@ -994,7 +1125,6 @@ Result<std::shared_ptr<DataType>> GetArrowType(const liborc::Type* type) {
       } else {
         return decimal128(precision, scale);
       }
-      break;
```
Comment (westonpace) [inline cpp/src/arrow/adapters/orc/util.cc:997]: Why remove this break?

**Review by westonpace — COMMENTED** [review]
This looks good.  Thank you for adding this.  I have some small questions (probably just my misunderstanding)

**Comment by westonpace** [comment]
Does your test cover the read path?  Also, do you want a test with a dense union?

File: cpp/src/arrow/adapters/orc/adapter_test.cc (hunk 1 above)
Comment (wgtmac) [reply cpp/src/arrow/adapters/orc/adapter_test.cc:855]: The random array generator fill random unselected values in the child arrays of `SparseUnionArray`. However, orc file only contains dense union type meaning that these unselected values will not be written to the file (so we can never read them back and compare equality in the unit test). In this PR, I fill unselected values to nulls when reading from the file. So flattening the `SparseUnionArray` before writing makes it easy for the roundtrip equality check of `SparseUnionArray`.

File: cpp/src/arrow/adapters/orc/util.cc (hunk 2 above)
Comment (wgtmac) [reply cpp/src/arrow/adapters/orc/util.cc:997]: Because it is unreachable.

**Comment by wgtmac** [comment]
> Does your test cover the read path? Also, do you want a test with a dense union?

Yes, I have added a roundtrip test for sparse union type. The read path of dense union will never happen because we always convert orc union to arrow sparse union type. Let me add a test case for batch conversion roundtrip of dense union to make it coverred.

File: cpp/src/arrow/adapters/orc/util.h [hunk 3]
```diff
@@ -35,8 +35,9 @@ Result<std::shared_ptr<DataType>> GetArrowType(const liborc::Type* type);
 
 Result<ORC_UNIQUE_PTR<liborc::Type>> GetOrcType(const Schema& schema);
 
-Status AppendBatch(const liborc::Type* type, liborc::ColumnVectorBatch* batch,
-                   int64_t offset, int64_t length, arrow::ArrayBuilder* builder);
+ARROW_EXPORT Status AppendBatch(const liborc::Type* type,
```
Comment (wgtmac) [inline cpp/src/arrow/adapters/orc/util.h:38]: I have to mark them as `ARROW_EXPORT`. Otherwise the windows build will complain unresolved references for the new tests.

File: cpp/src/arrow/adapters/orc/util.cc (hunk 2 above)
Comment (westonpace) [reply cpp/src/arrow/adapters/orc/util.cc:997]: Ah, I see now :).  Thanks.

File: cpp/src/arrow/adapters/orc/adapter_test.cc (hunk 1 above)
Comment (westonpace) [reply cpp/src/arrow/adapters/orc/adapter_test.cc]: Can you maybe add a small comment explaining this for future readers that might not be as familiar with orc?

Comment (westonpace) [reply cpp/src/arrow/adapters/orc/adapter_test.cc]: nevermind, I see you already did.  Thanks!

**Review by westonpace — APPROVED** [review]
Thanks for adding this support.
