### PR TITLE
GH-46998: [C++] Fix mockfs.cc compiling error with C++23

### LINKED ISSUE #46998: [C++] mockfs.cc fails to build with -DCMAKE_CXX_STANDARD=23
### Describe the bug, including details regarding any error messages, version, and platform.

On MacOS, I use the following command to configure arrow:

```
cmake ../cpp/ -DARROW_FILESYSTEM=ON -DARROW_PARQUET=ON -DARROW_POSITION_INDEPENDENT_CODE=ON -DARROW_BUILD_SHARED=ON -DARROW_WITH_ZLIB=ON -DZLIB_SOURCE=SYSTEM -DARROW_DEPENDENCY_SOURCE=BUNDLED -DCMAKE_CXX_STANDARD=23
```

Compiler:

```
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: x86_64-apple-darwin24.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

The compile fails on mockfs.cc with the following error:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:79:19: error: invalid application of 'sizeof' to an incomplete type 'arrow::fs::internal::(anonymous namespace)::Entry'
   79 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
      |                   ^~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7: note: in instantiation of member function 'std::default_delete<arrow::fs::internal::(anonymous namespace)::Entry>::operator()' requested here
  293 |       __ptr_.second()(__tmp);
      |       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:233:5: note: in instantiation of member function 'std::unique_ptr<arrow::fs::internal::(anonymous namespace)::Entry>::reset' requested here
  233 |     reset(__u.release());
      |     ^
/Users/zhjwpku/zhjwpku/arrow/cpp/src/arrow/filesystem/mockfs.cc:113:16: note: in instantiation of member function 'std::unique_ptr<arrow::fs::internal::(anonymous namespace)::Entry>::operator=' requested here
  113 |     entries[s] = std::move(entry);
      |                ^
/Users/zhjwpku/zhjwpku/arrow/cpp/src/arrow/filesystem/mockfs.cc:57:7: note: forward declaration of 'arrow::fs::internal::(anonymous namespace)::Entry'
   57 | class Entry;
      |       ^
1 error generated.
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by zhjwpku**
### Rationale for this change

When compiling with C++23, mockfs.cc fails due to a static assertion failure, as described in issue #46998.

### What changes are included in this PR?

Move the implementation of AssignEntry after the definition of Entry.

### Are these changes tested?

Yes, I test the changes with C++23, and the error gone.

### Are there any user-facing changes?

No, the changes are within an anonymous namespace.

* GitHub Issue: #46998

### CODE REVIEW

File: cpp/src/arrow/filesystem/mockfs.cc [hunk 1]
```diff
@@ -187,6 +184,11 @@ class Entry : public EntryBase {
   ARROW_DISALLOW_COPY_AND_ASSIGN(Entry);
 };
 
+void Directory::AssignEntry(const std::string& s, std::unique_ptr<Entry> entry) {
```
Comment (wgtmac) [inline cpp/src/arrow/filesystem/mockfs.cc:187]: I don't quite understand how does this fix the issue...

Comment (zhjwpku) [reply cpp/src/arrow/filesystem/mockfs.cc:187]: The AssignEntry implementation is now placed after the full definition of Entry so it can access its structure. Previously, Entry was only forward declared, and as the error message indicated, the `sizeof` a forward declaration is 0, which triggered the static_assert.

I'm not sure this is the most appropriate fix, though.

**Review by kou — APPROVED** [review]
+1

Could you use our PR template instead of removing it entirely? We use the PR title and description for commit message on merge.

**Comment by zhjwpku** [comment]
> +1
> 
> Could you use our PR template instead of removing it entirely? We use the PR title and description for commit message on merge.

I've done that, can you see it again?

**Comment by zhjwpku** [comment]
> After merging your PR, Conbench analyzed the 4 benchmarking runs that have been run so far on merge-commit [1e01c52](https://github.com/apache/arrow/commit/1e01c520e9fb4ffddedeb7179d99a8cacfb9d347).
> 
> There were 3 benchmark results indicating a performance regression:
> 
> * Commit Run on `test-mac-arm` at [2025-07-07 06:41:51Z](https://conbench.ursa.dev/compare/runs/729e6817da914505a3e1fa474bbda8e6...ab10508f7f9d4e27b7feb05aeae6c788/)
>   
>   * [`tpch` (R) with engine=arrow, format=native, language=R, memory_map=False, query_id=TPCH-03, scale_factor=1](https://conbench.ursa.dev/compare/benchmarks/0686a6b5ddd674f28000832372e7c4b9...0686b771feba77948000ac3209cb66b7)
>   * [`tpch` (R) with engine=arrow, format=native, language=R, memory_map=False, query_id=TPCH-07, scale_factor=1](https://conbench.ursa.dev/compare/benchmarks/0686a6bb8deb7b8280008da195e99b3d...0686b777c38d7c1d80003613ed1787e5)
> * and 1 more (see the report linked below)
> 
> The [full Conbench report](https://github.com/apache/arrow/runs/45470355740) has more details. It also includes information about 54 possible false positives for unstable benchmarks that are known to sometimes produce them.

I don't quite understand why these performance regression, do these cases use mockfs? Kou san, can you give me some hints how to diagnose this? @kou

**Comment by kou** [comment]
You can ignore this.

Unfortunately, our continuous benchmarking mechanism is broken recently...

**Comment by zhjwpku** [comment]
> You can ignore this.
> 
> Unfortunately, our continuous benchmarking mechanism is broken recently...

Sure, thanks for confirming.
