### PR TITLE
GH-38958: [C++][Parquet] Fix spelling

### LINKED ISSUE #38958: [C++][Parquet] Spelling errors identified by check-spelling
### Describe the bug, including details regarding any error messages, version, and platform.

The [check-spelling action](https://github.com/marketplace/actions/check-spelling) enabled me to identify some misspellings...

The misspellings have been reported at https://github.com/jsoref/apache-arrow/actions/runs/7008141484/attempts/1#summary-19063787889

### Component(s)

Parquet

### PR DESCRIPTION
**Pull request by jsoref**
### What changes are included in this PR?

Spelling fixes to *parquet*

### Are there any user-facing changes?

* Closes: #38958

### CODE REVIEW

File: cpp/src/generated/parquet_types.cpp [hunk 1]
```diff
@@ -325,7 +325,7 @@ std::string to_string(const ConvertedType::type& val) {
 
 int _kFieldRepetitionTypeValues[] = {
   /**
-   * This field is required (can not be null) and each record has exactly 1 value.
+   * This field is required (cannot be null) and each record has exactly 1 value.
```
Comment (wgtmac) [inline cpp/src/generated/parquet_types.cpp:328]: Please do not change generated files.

File: cpp/src/generated/parquet_types.h [hunk 2]
```diff
@@ -192,7 +192,7 @@ std::string to_string(const ConvertedType::type& val);
 struct FieldRepetitionType {
   enum type {
     /**
-     * This field is required (can not be null) and each record has exactly 1 value.
+     * This field is required (cannot be null) and each record has exactly 1 value.
```
Comment (wgtmac) [inline cpp/src/generated/parquet_types.h:195]: ditto

**Review by wgtmac — CHANGES_REQUESTED** [review]

File: cpp/src/parquet/parquet.thrift [hunk 3]
```diff
@@ -182,7 +182,7 @@ enum ConvertedType {
  * Representation of Schemas
  */
 enum FieldRepetitionType {
-  /** This field is required (can not be null) and each record has exactly 1 value. */
```
Comment (mapleFU) [inline cpp/src/parquet/parquet.thrift:185]: We shouldn't modify the `parquet.thrift`, since it's from parquet-format repo: https://github.com/apache/parquet-format

**Comment by mapleFU** [comment]
Rest LGTM

**Review by mapleFU — APPROVED** [review]
+1

File: cpp/src/parquet/reader_test.cc [hunk 4]
```diff
@@ -425,7 +425,7 @@ TEST_F(TestAllTypesPlain, TestBatchRead) {
   ASSERT_FALSE(col->HasNext());
 }
 
-TEST_F(TestAllTypesPlain, RowGroupColumnBoundchecking) {
+TEST_F(TestAllTypesPlain, RowGroupColumnBoundschecking) {
```
Comment (mapleFU) [inline cpp/src/parquet/reader_test.cc:428]:
```suggestion
TEST_F(TestAllTypesPlain, RowGroupColumnBoundsChecking) {
```

File: cpp/src/parquet/encoding.h [hunk 5]
```diff
@@ -233,7 +233,7 @@ class DictEncoder : virtual public TypedEncoder<DType> {
 
   /// \brief EXPERIMENTAL: Append dictionary indices into the encoder. It is
   /// assumed (without any boundschecking) that the indices reference
-  /// pre-existing dictionary values
+  /// preexisting dictionary values
```
Comment (mapleFU) [inline cpp/src/parquet/encoding.h:236]: Actually I'm not a native english speaker, so I wonder what's the differences between `pre-existing`  and `preexisting`?

File: cpp/src/parquet/statistics.h [hunk 6]
```diff
@@ -205,7 +205,7 @@ class PARQUET_EXPORT Statistics {
       ::arrow::MemoryPool* pool = ::arrow::default_memory_pool());
 
   /// \brief Create a new statistics instance given a column schema
-  /// definition and pre-existing state
+  /// definition and preexisting state
```
Comment (mapleFU) [inline cpp/src/parquet/statistics.h:208]: ditto

**Review by mapleFU — COMMENTED** [review]
This patch LGTM, just a few naive questions

Will merge it if problem resolve and CI passed

File: cpp/src/parquet/encoding.h (hunk 5 above)
Comment (jsoref) [reply cpp/src/parquet/encoding.h:236]: Hyphenation is an interim step in English. Eventually some words come into common usage and the hyphenation is dropped.

**Review by mapleFU — APPROVED** [review]

**Comment by mapleFU** [comment]
Will merge it tomorrow night if no other's comment

**Review by wgtmac — APPROVED** [review]
