### PR TITLE
GH-38242: [Java] Fix incorrect internal struct accounting for DenseUnionVector#getBufferSizeFor

### LINKED ISSUE #38242: [Java] Incorrect getBufferSize for a dense union vector
### Describe the bug, including details regarding any error messages, version, and platform.

`DenseUnionVector.getBufferSizeFor` takes a count parameter. My expectation is the count represents the number of elements in the union you wish to account for. 

However, that count is passed directly to `internalStruct.getBufferSizeFor`, which I suspect is a bug.

This is because struct fields normally have the same valueCount, but this is not likely true when used in a union. If your children have different lengths:

- for fixed vectors, you will calculate the size of the leg contents incorrectly
- dynamic vectors like VarBinary may require reading buffer contents to find the data size, potentially causing an out-of-bounds dereference

Observed on `13.0.0` and `12.0.1`.

Repro:

```java

package org.apache.arrow.vector.complex;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Arrays;
import java.util.List;

import org.apache.arrow.memory.BoundsChecking;
import org.apache.arrow.memory.BufferAllocator;
import org.apache.arrow.memory.RootAllocator;
import org.apache.arrow.vector.BaseValueVector;
import org.apache.arrow.vector.complex.DenseUnionVector;
import org.apache.arrow.vector.holders.NullableIntHolder;
import org.apache.arrow.vector.holders.NullableVarBinaryHolder;
import org.apache.arrow.vector.types.UnionMode;
import org.apache.arrow.vector.types.pojo.ArrowType;
import org.apache.arrow.vector.types.pojo.Field;
import org.apache.arrow.vector.types.pojo.FieldType;
import org.junit.jupiter.api.Test;

public class TestDuvBufferCount {
  @Test
  public void testBufferSize() {
    try (BufferAllocator allocator = new RootAllocator();
         DenseUnionVector duv = new DenseUnionVector("duv", allocator,
                 FieldType.nullable(new ArrowType.Union(UnionMode.Dense, null)), null)) {

      List<Field> fields = Arrays.asList(
              new Field("a", FieldType.notNullable(new ArrowType.Int(32, true)), null),
              new Field("b", FieldType.notNullable(new ArrowType.Binary()), null)
      );

      duv.initializeChildrenFromFields(fields);

      NullableIntHolder nih = new NullableIntHolder();
      NullableVarBinaryHolder nvbh = new NullableVarBinaryHolder();

      int ac = BaseValueVector.INITIAL_VALUE_ALLOCATION + 1;
      for (int i = 0; i < ac; i++) {
        duv.setTypeId(i, (byte) 0);
        duv.setSafe(i, nih);
      }

      int bc = 1;
      for (int i = 0; i < bc; i++) {
        duv.setTypeId(i + ac, (byte) 1);
        duv.setSafe(i + ac, nvbh);
      }

      duv.setValueCount(ac + bc);

      // will not necessarily see an error unless bounds checking is on.
      assertTrue(BoundsChecking.BOUNDS_CHECKING_ENABLED);
      assertDoesNotThrow(duv::getBufferSize);
    }
  }
}

```

### Component(s)

Java

### PR DESCRIPTION
**Pull request by wotbrew**
### What changes are included in this PR?

Fix incorrect implementation of `DenseUnionVector.getBufferSizeFor`.
Sum the type id counts before calling `getBufferSizeFor` on the union's child vectors.

### Are these changes tested?

Yes. A test verifies the OOB read (requires bounds check), and an example count is correct, fails as expected before fix.

**This PR contains a "Critical Fix".** 

For users of DenseUnionVector the size can calculated incorrectly, as well as cause of out-of-bounds buffer reads which may return garbage (or potentially segfaulting) if bounds checking is off.

* Closes: #38242

### CODE REVIEW

**Comment by pitrou** [comment]
cc @jduo

File: java/vector/src/main/codegen/templates/DenseUnionVector.java [hunk 1]
```diff
@@ -714,8 +714,22 @@ public int getBufferSizeFor(final int count) {
     if (count == 0) {
       return 0;
     }
+
+    int[] legCounts = new int[typeFields.length];
```
Comment (pitrou) [inline java/vector/src/main/codegen/templates/DenseUnionVector.java:718]: What is a "leg" here? This is not common terminology in Arrow.

Comment (pitrou) [reply java/vector/src/main/codegen/templates/DenseUnionVector.java:718]: Could call this `typeCounts` or `childCounts`.

File: java/vector/src/main/codegen/templates/DenseUnionVector.java [hunk 2]
```diff
@@ -714,8 +714,22 @@ public int getBufferSizeFor(final int count) {
...
+    for (int i = 0; i < count; i++) {
+      byte tid = getTypeId(i);
+      legCounts[tid]++;
+    }
+
+    long legBytes = 0;
```
Comment (pitrou) [inline java/vector/src/main/codegen/templates/DenseUnionVector.java:724]: Same here: call this `totalChildBytes` for example.

File: java/vector/src/main/codegen/templates/DenseUnionVector.java [hunk 3]
```diff
@@ -714,8 +714,22 @@ public int getBufferSizeFor(final int count) {
...
+    byte tid = 0;
+    for (ValueVector v : internalStruct) {
+      legBytes += (long)v.getBufferSizeFor(legCounts[tid]);
+      tid++;
+    }
```
Comment (pitrou) [inline java/vector/src/main/codegen/templates/DenseUnionVector.java:729]: I don't think this is right: `internalStruct` has its fields indexed by physical child id (that is: 0, 1, 2...) but the type ids are logical values that are unrelated to the physical structure.

But I think that you should just copy what is already done in `setChildVectorValueCounts` and adapt it for the use case of counting buffer bytes.

File: java/vector/src/main/codegen/templates/DenseUnionVector.java [hunk 4]
```diff
@@ -714,8 +714,22 @@ public int getBufferSizeFor(final int count) {
...
+
     return (int) (count * TYPE_WIDTH + (long) count * OFFSET_WIDTH
-        + DataSizeRoundingUtil.divideBy8Ceil(count) + internalStruct.getBufferSizeFor(count));
+        + DataSizeRoundingUtil.divideBy8Ceil(count) + legBytes);
```
Comment (pitrou) [inline java/vector/src/main/codegen/templates/DenseUnionVector.java:732]: I think `DataSizeRoundingUtil.divideBy8Ceil(count)` is a mistake: union vectors don't have a validity bitmap, so they don't need any buffer for it.

File: java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+import org.apache.arrow.vector.holders.NullableIntHolder;
+import org.apache.arrow.vector.holders.NullableVarBinaryHolder;
+import org.apache.arrow.vector.types.UnionMode;
+import org.apache.arrow.vector.types.pojo.ArrowType;
+import org.apache.arrow.vector.types.pojo.Field;
+import org.apache.arrow.vector.types.pojo.FieldType;
+import org.apache.arrow.vector.util.DataSizeRoundingUtil;
+import org.junit.jupiter.api.Test;
+
+public class TestDUVBufferSize {
```
Comment (pitrou) [inline java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java:39]: I'm not sure "DUV" is a common abbreviation, can you just spell it out in full? (also in the file name)

File: java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+    try (BufferAllocator allocator = new RootAllocator();
+         DenseUnionVector duv = new DenseUnionVector("duv", allocator,
+                 FieldType.nullable(new ArrowType.Union(UnionMode.Dense, null)), null)) {
+
+      List<Field> fields = Arrays.asList(
+              new Field("a", FieldType.notNullable(new ArrowType.Int(32, true)), null),
+              new Field("b", FieldType.notNullable(new ArrowType.Binary()), null)
+      );
+
+      duv.initializeChildrenFromFields(fields);
```
Comment (pitrou) [inline java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java:51]: Ok, but that's the easy case as it will use auto-incremented type ids (0,1,2...).
Instead, I would recommend calling `DenseUnionVector.addVector` which allows you to add child fields with non-trivial type ids (7,6,5 for example).

File: java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+        duv.setSafe(i, nih);
+      }
+
+      int bc = 1;
+      for (int i = 0; i < bc; i++) {
+        duv.setTypeId(i + ac, (byte) 1);
+        duv.setSafe(i + ac, nvbh);
+      }
+
+      int count = ac + bc;
```
Comment (pitrou) [inline java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java:68]: Please, can you avoid cryptic variable names? (`nih`, `ac`, etc.)

File: java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+      duv.setValueCount(count);
+
+      // will not necessarily see an error unless bounds checking is on.
+      assertDoesNotThrow(duv::getBufferSize);
```
Comment (pitrou) [inline java/vector/src/test/java/org/apache/arrow/vector/complex/TestDUVBufferSize.java:72]: Can we also test `getBufferSize` with an explicit argument?

**Review by pitrou — CHANGES_REQUESTED** [review]

File: java/vector/src/main/codegen/templates/DenseUnionVector.java (hunk 1 above)
Comment (wotbrew) [reply java/vector/src/main/codegen/templates/DenseUnionVector.java]: Forgive the name 😓, internal team term leakage! 

Fixed by adapting setChildVectorValueCounts (using `counts`)

**Review by lidavidm — APPROVED** [review]

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
Thanks a lot for the update @wotbrew ! CI failure is unrelated, so I'll merge.
