### PR TITLE
GH-38332: [CI][Release] Resolve symlinks in RAT lint

### LINKED ISSUE #38332: [Release] RAT error for 14.0.0 RC1 source archive
### Describe the bug, including details regarding any error messages, version, and platform.

```console
$ dev/release/02-source.sh 14.0.0 1
Preparing source for tag apache-arrow-14.0.0
Using commit 7a814d1de2d8f81642a5e6a795e3d716ec4981b7
NOT APPROVED: python/cmake_modules/snappy.diff (apache-arrow-14.0.0/python/cmake_modules/snappy.diff): false
1 unapproved licences. Check rat report: rat.txt
```

It's caused because we un-symlink `python/cmake_modules/` for source archive. (See also: #4028)
We run RAT against only our repository itself not our source archive in our CI.  So we can't detect this before we create RC.

### Component(s)

Release

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Our release script (`dev/release/02-source.sh`) resolves symlinks in source archive but our lint script (`dev/archery/archery/utils/source.py`) doesn't resolve symlinks. So we may detect RAT problem by our CI.

### What changes are included in this PR?

Resolve symlinks in our lint script too.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #38332

### CODE REVIEW

**Comment by kou** [comment]
I confirmed that the original problem can be caught by CI: 

https://github.com/apache/arrow/actions/runs/6568194718/job/17842233859?pr=38337#step:5:941

```text
apache-rat license violation: python/cmake_modules/snappy.diff
```

I'll fix the problem.

**Comment by kou** [comment]
Green: https://github.com/apache/arrow/actions/runs/6568660813/job/17843413441?pr=38337

**Comment by pitrou** [comment]
@raulcd Could you review this?

File: dev/release/02-source.sh [hunk 1]
```diff
@@ -65,7 +65,9 @@ rm -rf ${tag}
   git archive ${release_hash} --prefix ${tag}/) | \
   tar xf -
 
-# Resolve all hard and symbolic links
+# Resolve all hard and symbolic links.
+# If we change this, we must change Source.archive in
```
Comment (raulcd) [inline dev/release/02-source.sh:69]:
```suggestion
# If we change this, we must change ArrowSources.archive in
```

**Review by raulcd — APPROVED** [review]
Thanks @kou
