### PR TITLE
GH-15212: [C++] fix sliced list array writing in ORC

### LINKED ISSUE #15212: ORC writer doesn't work on sliced list arrays
### Describe the bug, including details regarding any error messages, version, and platform.

Follow up on #15210, where there was another misuse of `BaseListArray.values()`.

This can be reproduced with the unit test:

```cpp
TEST_F(TestORCWriterTrivialNoConversion, writeSlicedBatch) {
  std::shared_ptr<Table> table = GenerateRandomTable(table_schema, /*size=*/100, /*min_num_chunks=*/1, /*max_num_chunks*/1, /*probability=*/0);
  table = table->Slice(20, 60);
  
  AssertTableWriteReadEqual(table, table, kDefaultSmallMemStreamSize / 16);
}
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by wjones127**
Writing sliced list and map arrays will produce incorrect data. This happens because the arrays are recreated using `BaseListArray.values()`, which doesn't account for the offsets, and the offsets was not passed. To fix, I changed to pass along the offsets.
* Closes: #15212

### CODE REVIEW

File: cpp/src/arrow/adapters/orc/adapter_test.cc [hunk 1]
```diff
@@ -536,6 +536,15 @@ TEST_F(TestORCWriterTrivialNoConversion, writeFilledChunkAndSelectField) {
                             &selected_indices);
 }
 
+TEST_F(TestORCWriterTrivialNoConversion, writeSlicedBatch) {
+  std::shared_ptr<Table> table =
+      GenerateRandomTable(table_schema, /*size=*/100, /*min_num_chunks=*/1,
```
Comment (wgtmac) [inline cpp/src/arrow/adapters/orc/adapter_test.cc:541]: Does it cover type like `list<list<X>>` to make sure that offset of the inner list is correct?

Comment (wjones127) [reply cpp/src/arrow/adapters/orc/adapter_test.cc:541]: The test doesn't cover that case. But it should be fine, since `NormalizeArray` is recursive. So  `NormalizeArray(list<list<X>>)` calls `NormalizeArray(list<X>)`, which calls `NormalizeArray(X)`. The offsets at each level should be handled.

**Comment by pitrou** [comment]
Can we rephrase the PR title to describe what the PR does? "XXX doesn't work" is ambiguous (does it describe what the PR is supposed to fix?).

**Review by pitrou — APPROVED** [review]
