### PR TITLE
GH-37111: [C++][Parquet] Dataset: Fixing Schema Cast

### LINKED ISSUE #37111: Dataset filtering from disk broken for duration type
### Describe the bug, including details regarding any error messages, version, and platform.

Using `pyarrow-12.0.1` on RHEL8 Intel.

dataset filters work when the table is read into memory, but break when the table is a referenced Parquet file. The following code demonstrates the issue:
```
import pyarrow as pa
import pyarrow.dataset as ds
import pyarrow.parquet as pq

value_type = pa.duration("s")

# Create a file with a single row
table = pa.table([pa.array([1], value_type)], ["t"])
filename = "test.parquet"
pq.write_table(table, filename, version="2.6")

# Filter the row in-memory using dataset, THIS WORKS
table2 = pq.read_table(filename)
dataset = ds.dataset(table2)
x = dataset.to_table(filter=ds.field("t") == pa.scalar(1, type=value_type))

# Filter the row using dataset from disk, THIS BREAKS
dataset = ds.dataset(filename, format="parquet")
y = dataset.to_table(filter=ds.field("t") == pa.scalar(1, type=value_type))

assert x == y
```

The assert is not reached, instead we get the error:
```
Traceback (most recent call last):
  File "break_filter.py", line 19, in <module>
    y = dataset.to_table(filter=ds.field("t") == pa.scalar(1, type=value_type))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 546, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3449, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Function 'equal' has no kernel matching input types (duration[us], int8)
```

Superficially, it appears as though the duration scalar is being prematurely unboxed.

The issue is not present with other value_types (such as `int64`, `timestamp`, `date32`), but a potentially related issue occurs with `value_type = pa.time32("s")`:
```
pyarrow.lib.ArrowNotImplementedError: Function 'equal' has no kernel matching input types (time32[ms], time32[s])
```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Parquet and Arrow has two schema:
1. Parquet has a SchemaElement[1], it's language and implement independent. Parquet Arrow will extract the schema and decude it.
2. Parquet arrow stores schema and possible `field_id` in `key_value_metadata`[2] when `store_schema` enabled. When deserializing, it will first parse `SchemaElement`[1], and if self-defined key_value_metadata exists, it will use `key_value_metadata` to override the [1]

[1] https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L356
[2] https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L1033

The bug raise from that, when dataset parsing `SchemaManifest`, it doesn't use `key_value_metadata` from `Metadata`, which raises the problem.

For duration, when `store_schema` enabled, it will store `Int64` as physical type, and add a `::arrow::Duration` in `key_value_metadata`. And there is no `equal(Duration, i64)`. So raise the un-impl

### What changes are included in this PR?

Set `key_value_metadata` in implemented.

### Are these changes tested?

Yes

### Are there any user-facing changes?

bugfix

* Closes: #37111

### CODE REVIEW

**Comment by mapleFU** [comment]
@bkietz I've rewrite a fixing, which is much more clear with testing. The previous fixing is ugly and wrong, so sorry for that.

File: cpp/src/arrow/dataset/file_parquet_test.cc [hunk 1]
```diff
@@ -703,6 +707,25 @@ TEST_P(TestParquetFileFormatScan, PredicatePushdownRowGroupFragmentsUsingStringC
   CountRowGroupsInFragment(fragment, {0, 3}, equal(field_ref("x"), literal("a")));
 }
 
+TEST_P(TestParquetFileFormatScan, PredicatePushdownRowGroupFragmentsUsingDurationColumn) {
+  auto table = TableFromJSON(schema({field("t", duration(TimeUnit::NANO))}),
```
Comment (bkietz) [inline cpp/src/arrow/dataset/file_parquet_test.cc:711]: Would you mind also checking for time32 since that was mentioned in the issue? If it isn't fixed by this patch then we should make a follow up issue to address it

```suggestion
  for (auto type : {duration(TimeUnit::NANO), time32(TimeUnit::SECOND)}) {
    auto table = TableFromJSON(schema({field("t", type)}),
```

Also, please describe the bug in GH-37111 and how this test checks it

**Review by bkietz — CHANGES_REQUESTED** [review]
Nice! Just a small comment

File: cpp/src/arrow/dataset/file_parquet_test.cc (hunk 1 above)
Comment (mapleFU) [reply cpp/src/arrow/dataset/file_parquet_test.cc:711]: I think this is a different problem, after check this patch not fixed that, I'll create another issue and try to fix it before 14.0

**Comment by mapleFU** [comment]
@bkietz I've write a test about Timestamp in my local machine:

```c++
TEST_P(TestParquetFileFormatScan, PredicatePushdownRowGroupFragmentsUsingTimestampColumn) {
  auto table = TableFromJSON(schema({field("t", time32(TimeUnit::SECOND))}),
                             {
                                 R"([{"t": 1}])",
                                 R"([{"t": 2}, {"t": 3}])",
                             });
  TableBatchReader table_reader(*table);
  SCOPED_TRACE("TestParquetFileFormatScan.PredicatePushdownRowGroupFragmentsUsingTimestampColumn");
  ASSERT_OK_AND_ASSIGN(
      auto buffer,
      ParquetFormatHelper::Write(
          &table_reader, ArrowWriterProperties::Builder().store_schema()->build()));
  auto source = std::make_shared<FileSource>(buffer);
  SetSchema({field("t", time32(TimeUnit::SECOND))});
  ASSERT_OK_AND_ASSIGN(auto fragment, format_->MakeFragment(*source));

  auto expr = equal(field_ref("t"), literal(::arrow::Time32Scalar(1, TimeUnit::SECOND)));
  CountRowGroupsInFragment(fragment, {0}, expr);
}
```

The test failed because:

```
 Function 'equal' has no kernel matching input types (time32[s], time32[ms])
```

1. Parquet doesn't have second in parquet, so it was convert to store as `ms`
2. In our expr system, we use `equal(time32[s], time32[ms])`

I'll separate a pr for this.

**Review by bkietz — APPROVED** [review]
LGTM, thanks!
