### PR TITLE
GH-39562: [C++][Parquet] Fix crash in test_parquet_dataset_lazy_filtering

### LINKED ISSUE #39562: [CI][Python] Some macOS wheels are failing with a segmentation fault when running test_parquet_dataset_lazy_filtering
### Describe the bug, including details regarding any error messages, version, and platform.

Some jobs seem to fail sometimes with the following error:
```
Fatal Python error: Aborted

Current thread 0x00000001e28b2100 (most recent call first):
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pyarrow/tests/test_dataset.py", line 3753 in test_parquet_dataset_lazy_filtering
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/python.py", line 194 in pytest_pyfunc_call
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/python.py", line 1792 in runtest
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/runner.py", line 341 in from_call
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/runner.py", line 133 in runtestprotocol
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/main.py", line 350 in pytest_runtestloop
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/main.py", line 325 in _main
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/main.py", line 271 in wrap_session
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/main.py", line 318 in pytest_cmdline_main
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_callers.py", line 77 in _multicall
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_manager.py", line 115 in _hookexec
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pluggy/_hooks.py", line 493 in __call__
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/config/__init__.py", line 169 in main
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/_pytest/config/__init__.py", line 192 in console_main
  File "/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/test-arm64-env/lib/python3.11/site-packages/pytest/__main__.py", line 5 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pyarrow.lib, pyarrow._hdfsio, pyarrow._fs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, cython.cimports.libc.math, pyarrow._compute, pyarrow._acero, pyarrow._csv, pyarrow._json, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, pyarrow._dataset, pyarrow._dataset_orc, pyarrow._parquet, pyarrow._parquet_encryption, pyarrow._dataset_parquet_encryption, pyarrow._dataset_parquet, pyarrow._orc, pyarrow._flight, pyarrow._substrait, _cffi_backend, pyarrow._pyarrow_cpp_tests, pyarrow._feather, numpy.linalg.lapack_lite, pandas._libs.hashing, google._upb._message, markupsafe._speedups, grpc._cython.cygrpc, charset_normalizer.md, crc32c (total: 82)
arrow/ci/scripts/python_wheel_unix_test.sh: line 95: 13092 Abort trap: 6           python -m pytest -r s --pyargs pyarrow
...............................................s.....
```

* [wheel-macos-big-sur-cp311-arm64](https://github.com/ursacomputing/crossbow/actions/runs/7472224253/job/20333965500)
* [wheel-macos-big-sur-cp312-arm64](https://github.com/ursacomputing/crossbow/actions/runs/7472224675/job/20333968477)
* [wheel-macos-catalina-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/7463685047/job/20308928759)

### Component(s)

Continuous Integration, Python

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

`ParquetFileFragment` stores a `SchemaManifest` that has a raw pointer to a `SchemaDescriptor`. The `SchemaDescriptor` is originally provided by a `FileMetadata` instance but, in some cases, the `FileMetadata` instance can be destroyed while the `ParquetFileFragment` is still in use. This can typically lead to bugs or crashes.

### What changes are included in this PR?

Ensure that `ParquetFileFragment` keeps an owning pointer to the `FileMetadata` instance that provides its `SchemaManifest`'s schema descriptor.

### Are these changes tested?

An assertion is added that would fail deterministically in the Python test suite.

### Are there any user-facing changes?

No.

* Closes: #39562

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos*

File: cpp/src/arrow/dataset/file_parquet.cc [hunk 1]
```diff
@@ -813,11 +813,17 @@ Status ParquetFileFragment::EnsureCompleteMetadata(parquet::arrow::FileReader* r
...
 Status ParquetFileFragment::SetMetadata(
     std::shared_ptr<parquet::FileMetaData> metadata,
-    std::shared_ptr<parquet::arrow::SchemaManifest> manifest) {
+    std::shared_ptr<parquet::arrow::SchemaManifest> manifest,
+    std::shared_ptr<parquet::FileMetaData> original_metadata) {
   DCHECK(row_groups_.has_value());
 
   metadata_ = std::move(metadata);
   manifest_ = std::move(manifest);
+  original_metadata_ = original_metadata ? std::move(original_metadata) : metadata_;
```
Comment (mapleFU) [inline cpp/src/arrow/dataset/file_parquet.cc:822]: This is ok for be but should we check `Subset` for this?

**Comment by raulcd** [comment]
This https://github.com/apache/arrow/commit/b59082a72094f112f95914a1d8ad469db87a34c9 might have broken the crossbow submissions for committers that don't have their membership set to Public (https://github.com/orgs/apache/people?query=pitrou)

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-macos*

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos*

File: cpp/src/arrow/dataset/file_parquet.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/dataset/file_parquet.cc:822]: Do you mean `FileMetaData::Subset`?

Comment (mapleFU) [reply cpp/src/arrow/dataset/file_parquet.cc:822]: Yeah, I misunderstand this previously, `metadata_` is from Subset, but `manifest` is shared and having lifetime problem here.

**Review by mapleFU — APPROVED** [review]
LGTM.

**Comment by pitrou** [comment]
@jorisvandenbossche This seems to have addressed the issue. Should we run the tests another time?

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel -g python

**Comment by jorisvandenbossche** [comment]
Nice! Yes, running once more to be sure is best (it happened before there were no failures in a single run of all wheel builds)

**Comment by pitrou** [comment]
@raulcd I marked this for 15.0.
