### PR TITLE
GH-36141: [Go] Support large and fixed types in csv

### LINKED ISSUE #36141: [Go] Support large and fixed types in csv
### Describe the enhancement requested

I think large and fixed types should be supported by csv reader and writer (like their normal version).
New supported types: `LargeList`, `FixedSizeList`, `LargeString`, `LargeBinary`, `FixedSizeBinary`.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by izveigor**
### Are these changes tested?
Yes

### Are there any user-facing changes?
Yes

* Closes: #36141

### CODE REVIEW

File: go/arrow/csv/reader.go [hunk 1]
```diff
@@ -783,6 +814,64 @@ func (r *Reader) parseList(field array.Builder, str string) {
...
+		// string is empty
+		return
+	}
+	valueBldr := fixedSizeListBldr.ValueBuilder()
+	reader := csv.NewReader(strings.NewReader(str))
+	items, err := reader.Read()
+	if err != nil {
+		r.err = err
+		return
+	}
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:869]: Add a validation that the number of items matches the `n` of the list, erroring if they pass the wrong number of items.

File: go/arrow/csv/reader.go [hunk 2]
```diff
@@ -796,6 +885,32 @@ func (r *Reader) parseBinaryType(field array.Builder, str string) {
...
+	// specialize the implementation when we know we cannot have nulls
+	if r.isNull(str) {
+		field.AppendNull()
+		return
+	}
+	decodedVal, err := base64.StdEncoding.DecodeString(str)
+	if err != nil {
+		panic("cannot decode base64 string " + str)
+	}
+	field.(*array.FixedSizeBinaryBuilder).Append(decodedVal)
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:911]: `Append` will panic if it is the wrong size, can we check the size first to ensure it is the write length for the fixed size binary and error (or truncate / pad) if it is incorrect?

**Review by zeroshade — CHANGES_REQUESTED** [review]
LGTM just two nitpicks

File: go/arrow/csv/reader.go [hunk 3]
```diff
@@ -475,10 +490,26 @@ func (r *Reader) initFieldConverter(bldr array.Builder) func(string) {
...
 		return func(s string) {
 			r.parseBinaryType(bldr, s)
 		}
+	case *arrow.LargeBinaryType:
+		return func(s string) {
+			r.parseLargeBinaryType(bldr, s)
+		}
+	case *arrow.FixedSizeBinaryType:
+		return func(s string) {
+			r.parseFixedSizeBinaryType(bldr, s, dt.BitWidth())
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:511]: use `dt.Bytes()` instead, so you don't need to do the `8*` in the parsing function since it will return the number of bytes directly.

File: go/arrow/csv/reader.go [hunk 4]
```diff
@@ -783,6 +814,68 @@ func (r *Reader) parseList(field array.Builder, str string) {
...
+	if err != nil {
+		r.err = err
+		return
+	}
+	if len(items) == n {
+		for _, str := range items {
+			r.initFieldConverter(valueBldr)(str)
+		}
+	} else {
+		r.err = errors.New("invalid fixed size list format. the length of the items should be equal the length of the fixed size list")
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:875]: let's use `fmt.Errorf("%w: fixed size list items should match the fixed size list length, expected %d, got %d", arrow.ErrInvalid, n, len(items))` to be more informative in the error.

File: go/arrow/csv/reader.go [hunk 5]
```diff
@@ -796,6 +889,36 @@ func (r *Reader) parseBinaryType(field array.Builder, str string) {
...
 
+func (r *Reader) parseLargeBinaryType(field array.Builder, str string) {
+	// specialize the implementation when we know we cannot have nulls
+	if r.isNull(str) {
+		field.AppendNull()
+		return
+	}
+	decodedVal, err := base64.StdEncoding.DecodeString(str)
+	if err != nil {
+		panic("cannot decode base64 string " + str)
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:900]: set `r.err` instead of panicing?

File: go/arrow/csv/reader.go [hunk 6]
```diff
@@ -796,6 +889,36 @@ func (r *Reader) parseBinaryType(field array.Builder, str string) {
...
+
+func (r *Reader) parseFixedSizeBinaryType(field array.Builder, str string, bitWidth int) {
+	// specialize the implementation when we know we cannot have nulls
+	if r.isNull(str) {
+		field.AppendNull()
+		return
+	}
+	decodedVal, err := base64.StdEncoding.DecodeString(str)
+	if err != nil {
+		panic("cannot decode base64 string " + str)
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:913]: set `r.err` instead of panicing?

File: go/arrow/csv/reader.go [hunk 7]
```diff
@@ -796,6 +889,36 @@ func (r *Reader) parseBinaryType(field array.Builder, str string) {
...
+	}
+	if len(decodedVal) == bitWidth {
+		field.(*array.FixedSizeBinaryBuilder).Append(decodedVal)
+	} else {
+		r.err = errors.New("invalid fixed size binary format. the bytes of the value should be equal the bit width of the fixed size binary")
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:918]: same as with fixed size list, can we include the information of the expected byte size and how many bytes we got?

Also, please re-name `bitWidth` to be `byteWidth` so it's obvious

File: go/arrow/csv/reader.go [hunk 8]
```diff
@@ -884,7 +884,7 @@ func (r *Reader) parseBinaryType(field array.Builder, str string) {
 	}
 	decodedVal, err := base64.StdEncoding.DecodeString(str)
 	if err != nil {
-		panic("cannot decode base64 string " + str)
+		r.err = fmt.Errorf("cannot decode base64 string %s", str)
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:887]: should probably AppendNull instead of appending the value anyways after getting this error.

File: go/arrow/csv/reader.go [hunk 9]
```diff
@@ -897,25 +897,25 @@ func (r *Reader) parseLargeBinaryType(field array.Builder, str string) {
...
+func (r *Reader) parseFixedSizeBinaryType(field array.Builder, str string, byteWidth int) {
 	// specialize the implementation when we know we cannot have nulls
 	if r.isNull(str) {
 		field.AppendNull()
 		return
 	}
 	decodedVal, err := base64.StdEncoding.DecodeString(str)
 	if err != nil {
-		panic("cannot decode base64 string " + str)
+		r.err = fmt.Errorf("cannot decode base64 string %s", str)
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:913]: same as above

**Review by zeroshade — APPROVED** [review]
