### PR TITLE
GH-38766: [R] Add timeout option to try_download

### LINKED ISSUE #38766: [R] Ensure timeout for download.file is set appropriately
### Describe the bug, including details regarding any error messages, version, and platform.

From the documentation for `download.file()`:

```
The timeout for many parts of the transfer can be set by the option timeout
which defaults to 60 seconds. This is often insufficient for downloads of large
files (50MB or more) and so should be increased when download.file is used in
packages to do so. Note that the user can set the default timeout by the
environment variable R_DEFAULT_INTERNET_TIMEOUT in recent versions of
R, so to ensure that this is not decreased packages should use something like

    options(timeout = max(300, getOption("timeout")))
  
(It is unrealistic to require download times of less than 1s/MB.)
```

I recently ran into an issue on macbuilder with adbcsnowflake where the default value of 60 was insufficient to download the Go dependency sources (34 MB). Our Windows static libs are ~70 MB, and so a timeout might have caused the issue we see with R-devel on Windows (`Arrow C++ library was not found`).

### Component(s)

R

### PR DESCRIPTION
**Pull request by paleolimbot**
### Rationale for this change

The download of static libraries during installation might be causing an install failure: https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/arrow-00install.html

### What changes are included in this PR?

The timeout value is temporarily increased according to guidance in the help for `download.file()`

### Are these changes tested?

Yes, this code runs during install for at least some CI jobs (also used to download cmake)

### Are there any user-facing changes?

No
* Closes: #38766

### CODE REVIEW

File: r/tools/nixlibs.R [hunk 1]
```diff
@@ -79,6 +79,10 @@ find_latest_nightly <- function(description_version,
 }
 
 try_download <- function(from_url, to_file, hush = quietly) {
+  # We download some fairly large files, so ensure the timeout is set appropriately
+  opts <- options(timeout = max(300, getOption("timeout")))
```
Comment (jonkeane) [inline r/tools/nixlibs.R:83]: How big are our binaries? We could back of the envelope math for downloading that in worst-case speed. You might have already done this calculation, if so, would be nice to add that to the comment so we know

Comment (paleolimbot) [reply r/tools/nixlibs.R]: Currently one the windows one is 70 MB. I added a note!

Comment (jonkeane) [reply r/tools/nixlibs.R]: That's wonderful. Thank you!

**Review by assignUser — APPROVED** [review]
Good idea! I have experienced intermittent slower download speeds from the artifactory before. With the option users can set a longer timeout if they have a slower connection so 100 sec seems reasonable.

**Comment by assignUser** [comment]
@github-actions crossbow submit r-binary-packages

(I don't think any of the PR CI jobs exercise this code path, I will merge after)

**Comment by assignUser** [comment]
The failure is unrelated (seems to be a fluke in r-lib setup-r-dependencies during pak install on 4.2, hasn't happened in the nightlies so :shrug: )

**Comment by assignUser** [comment]
> hasn't happened in the nightlies
;/ it has now see https://github.com/apache/arrow/issues/38779
