### PR TITLE
GH-29887: [C++] Implement dictionary array sorting

### LINKED ISSUE #29887: [C++] Sorting dictionary array not implemented
From R, taking the stock `mtcars` dataset and giving it a dictionary type column:

```Java

mtcars %>% 
  mutate(cyl = as.factor(cyl)) %>% 
  Table$create() %>% 
  arrange(cyl) %>% 
  collect()

Error: Type error: Sorting not supported for type dictionary<values=string, indices=int8, ordered=0>
../src/arrow/compute/kernels/vector_array_sort.cc:427  VisitTypeInline(type, this)
../src/arrow/compute/kernels/vector_sort.cc:148  GetArraySorter(*physical_type_)
../src/arrow/compute/kernels/vector_sort.cc:1206  sorter.Sort()
../src/arrow/compute/api_vector.cc:259  CallFunction("sort_indices", {datum}, &options, ctx)
../src/arrow/compute/exec/order_by_impl.cc:53  SortIndices(table, options_, ctx_)
../src/arrow/compute/exec/sink_node.cc:292  impl_->DoFinish()
../src/arrow/compute/exec/exec_plan.cc:297  iterator_.Next()
../src/arrow/record_batch.cc:318  ReadNext(&batch)
../src/arrow/record_batch.cc:329  ReadAll(&batches)
```

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-14314) / @nealrichardson
**Assignee**: [Ariana Villegas](https://issues.apache.org/jira/browse/ARROW-14314) / @ArianaVillegas
#### PRs and other links:
- [GitHub Pull Request #13334](https://github.com/apache/arrow/pull/13334)

<sub>**Note**: *This issue was originally created as [ARROW-14314](https://issues.apache.org/jira/browse/ARROW-14314). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by benibus**
### Rationale for this change

Sorting for `DictionaryArray`s is not currently supported.

### What changes are included in this PR?

- Adds support for dictionaries in the `array_sort_indices` kernel
- Adds tests and benchmarks
- Alters the internal `ArraySortFunc` definition to return an error status and accept the caller's `ExecContext` as an argument

### Are these changes tested?

Yes

### Are there any user-facing changes?

Yes

### Notes

This picks up where https://github.com/apache/arrow/pull/13334 left off. Those commits have been squashed and included in this PR.
* Closes: #29887

### CODE REVIEW

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc [hunk 1]
```diff
@@ -173,6 +173,116 @@ class ArrayCompareSorter {
...
 
+template <>
+class ArrayCompareSorter<DictionaryType> {
+ public:
+  Result<NullPartitionResult> operator()(uint64_t* indices_begin, uint64_t* indices_end,
+                                         const Array& array, int64_t offset,
+                                         const ArraySortOptions& options,
+                                         ExecContext* ctx) {
+    const auto& dict_array = checked_cast<const DictionaryArray&>(array);
+    // TODO: These methods should probably return a const&? They seem capable.
```
Comment (westonpace) [inline cpp/src/arrow/compute/kernels/vector_array_sort.cc:184]: Seems reasonable. Do you want to open a separate issue for this follow up and tag that issue here?  E.g. `TODO (GH-123): These methods...`

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc [hunk 2]
```diff
@@ -173,6 +173,116 @@ class ArrayCompareSorter {
...
+ private:
+  static bool IsAllNulls(const DictionaryArray& dict_array) {
+    auto indices = dict_array.indices();
+    auto values = dict_array.dictionary();
+    if (values->null_count() == values->length() ||
+        indices->null_count() == indices->length()) {
+      return true;
+    }
+    for (int64_t i = 0; i < dict_array.length(); ++i) {
+      // TODO: Special handling for dictionary types in Array::IsValid/Null?
```
Comment (westonpace) [inline cpp/src/arrow/compute/kernels/vector_array_sort.cc:232]: I'm not sure what this todo is referring to.  Are you suggesting we move this logic into `DictionaryArray`?  @felipecrv has been handling special cases for `IsNull/IsValid` recently and might be interested too.

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc [hunk 3]
```diff
@@ -173,6 +173,116 @@ class ArrayCompareSorter {
...
+      if (indices->IsValid(i) && values->IsValid(dict_array.GetValueIndex(i))) {
+        return false;
+      }
+    }
+    return true;
+  }
+
+  static Result<std::shared_ptr<Array>> MakeNullUInt64Array(int64_t length,
```
Comment (westonpace) [inline cpp/src/arrow/compute/kernels/vector_array_sort.cc:240]: Use `arrow::MakeArrayOfNull` in `src/arrow/array/util.cc` instead?

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc [hunk 4]
```diff
@@ -173,6 +173,116 @@ class ArrayCompareSorter {
...
+      null_bitmap = array->null_bitmap();
+      data = array->data()->Copy();
+      if (data->offset > 0) {
+        ARROW_ASSIGN_OR_RAISE(null_bitmap, arrow::internal::CopyBitmap(
+                                               ctx->memory_pool(), null_bitmap->data(),
+                                               data->offset, data->length));
+      }
+      data->buffers[0] = nullptr;
+      data->null_count = 0;
+    }
```
Comment (westonpace) [inline cpp/src/arrow/compute/kernels/vector_array_sort.cc:272]: I'm not sure I follow what is happening here.  Is `data` used after this if statement?

File: cpp/src/arrow/compute/kernels/vector_sort_benchmark.cc [hunk 5]
```diff
@@ -82,6 +86,55 @@ static void ArraySortFuncInt64Benchmark(benchmark::State& state, const Runner& r
...
+  auto dict_values = rand.Int64(kDictionarySize, min, max, args.null_proportion / 2);
+  auto dict_indices =
+      rand.Int64(array_size, 0, kDictionarySize - 1, args.null_proportion / 2);
+  auto dict_array = *DictionaryArray::FromArrays(dict_indices, dict_values);
+
+  ArraySortFuncBenchmark(state, runner, dict_array);
+}
+
+template <typename Runner>
+static void ArraySortFuncStringBenchmark(benchmark::State& state, const Runner& runner) {
```
Comment (westonpace) [inline cpp/src/arrow/compute/kernels/vector_sort_benchmark.cc:106]: I'm not sure if I'm just confused or maybe this PR needs a rebase from main but it appears there is already an `ArraySortFuncStringBenchmark` at https://github.com/apache/arrow/blob/be12888997c81b1fb7947f6284be1256edd4d3e4/cpp/src/arrow/compute/kernels/vector_sort_benchmark.cc#L103

Also, the version I linked to uses the actual length of the strings instead of `sizeof(int64_t)` which I think is more consistent.  Then `args.size` is the size in bytes and items processed is the number of records.

File: cpp/src/arrow/compute/kernels/vector_sort_test.cc [hunk 6]
```diff
@@ -368,6 +368,129 @@ TEST(ArraySortIndicesFunction, Array) {
...
+  // (["b", "c", null, null, null, "b", "c", "c", "a"])
+
+  std::vector<std::string> expected_str = {
+      "[8, 0, 5, 1, 6, 7, 2, 3, 4]",  // SortOrder::Ascending NullPlacement::AtEnd
+      "[2, 3, 4, 8, 0, 5, 1, 6, 7]",  // SortOrder::Ascending NullPlacement::AtStart
+      "[1, 6, 7, 0, 5, 8, 2, 3, 4]",  // SortOrder::Descending NullPlacement::AtEnd
+      "[2, 3, 4, 1, 6, 7, 0, 5, 8]"   // SortOrder::Descending NullPlacement::AtStart
+  };
+
+  for (auto index_type : all_dictionary_index_types()) {
```
Comment (westonpace) [inline cpp/src/arrow/compute/kernels/vector_sort_test.cc:382]:
```suggestion
  for (const auto& index_type : all_dictionary_index_types()) {
```

**Review by westonpace — COMMENTED** [review]
A few questions but looks good overall

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc (hunk 2 above)
Comment (benibus) [reply cpp/src/arrow/compute/kernels/vector_array_sort.cc:232]: Yeah, basically just an equivalent of the next few lines. In practice, it would need to be added to `Array` itself since `IsValid` isn't virtual.

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc (hunk 4 above)
Comment (benibus) [reply cpp/src/arrow/compute/kernels/vector_array_sort.cc:272]: Apparently not... (it should be passed to `rank`). Will fix.

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc (hunk 2 above)
Comment (felipecrv) [reply cpp/src/arrow/compute/kernels/vector_array_sort.cc:232]: `Array::IsValid` is testing the type in conditionals to dispatch call to the appropriate implementation. As the special cases are less than ~7, this way of dispatching the calls is better than vtable dispatching [1] and with #35149 the compiler can even inline the conditional checks away.

[1] https://twitter.com/_Felipe/status/1645237327780880385

File: cpp/src/arrow/compute/kernels/vector_array_sort.cc (hunk 1 above)
Comment (benibus) [reply cpp/src/arrow/compute/kernels/vector_array_sort.cc:184]: https://github.com/apache/arrow/issues/35437 (also included in the TODO)

**Comment by benibus** [comment]
I did some refactoring/reorganizing of the benchmarks so the new ones should hopefully make more sense. The original intent should still be intact (although I changed some of the string length parameters to be consistent with the existing non-dictionary string benchmarks).

**Review by pitrou — COMMENTED** [review]
Very neat, thanks. A couple comments and questions below.

**Comment by pitrou** [comment]
Just for the record, it's a pity that the all-or-mostly-null case is a bit slower:
```
ArraySortIndicesInt64WideDict/32768/10000         254 us          254 us         2756 bytes_per_second=122.985M/s items_per_second=16.1199M/s null_percent=0.01 size=32.768k
ArraySortIndicesInt64WideDict/32768/100           272 us          272 us         2615 bytes_per_second=115.005M/s items_per_second=15.0739M/s null_percent=1 size=32.768k
ArraySortIndicesInt64WideDict/32768/10            324 us          324 us         2162 bytes_per_second=96.5235M/s items_per_second=12.6515M/s null_percent=10 size=32.768k
ArraySortIndicesInt64WideDict/32768/2             386 us          386 us         1811 bytes_per_second=80.9335M/s items_per_second=10.6081M/s null_percent=50 size=32.768k
ArraySortIndicesInt64WideDict/32768/1             357 us          357 us         1956 bytes_per_second=87.483M/s items_per_second=11.4666M/s null_percent=100 size=32.768k
ArraySortIndicesInt64WideDict/32768/0             254 us          254 us         2751 bytes_per_second=122.957M/s items_per_second=16.1163M/s null_percent=0 size=32.768k
ArraySortIndicesInt64WideDict/1048576/100        3398 us         3396 us          205 bytes_per_second=294.442M/s items_per_second=38.593M/s null_percent=1 size=1048.58k
ArraySortIndicesInt64WideDict/8388608/100       31369 us        31341 us           22 bytes_per_second=255.253M/s items_per_second=33.4566M/s null_percent=1 size=8.38861M
```

This can be left to another issue or PR, though. Overall the improvement is very nice, especially for strings.

**Comment by benibus** [comment]
After some ad-hoc testing, the benchmark' array lengths/sizes should be essentially the same now between the dict and non-dict versions. For strings, the dict versions _slightly_ overshoot the others (in terms of bytes) due to some null overlap between the index/value arrays.

I also added some special-casing for the 100% null benchmarks - primarily to ensure that the input `DictionaryArray` was actually 0 bytes (like the `StringArray` equivalents). Caveat: it only tests the best-case scenario - i.e. where the index and/or value array is entirely null.

File: cpp/src/arrow/compute/kernels/vector_sort_test.cc [hunk 7]
```diff
@@ -368,6 +368,138 @@ TEST(ArraySortIndicesFunction, Array) {
   AssertDatumsEqual(expected, actual, /*verbose=*/true);
 }
 
+TEST(ArraySortIndicesFunction, DictionaryArray) {
```
Comment (pitrou) [inline cpp/src/arrow/compute/kernels/vector_sort_test.cc:371]: Perhaps add a test with a non-zero array indices and/or values offset somewhere?

**Review by pitrou — CHANGES_REQUESTED** [review]
Thanks for the update @benibus . Looks mostly good to me, just one more suggestion. Also, can you rebase?

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
I will note that the string benchmark numbers are lower with the latest benchmarking changes (which reduce the actual string array length), but that reflects the non-trivial fixed costs in the sorting routine:
```
ArraySortIndicesStringWide/32768/10000            585 us          584 us         1202 bytes_per_second=53.4765M/s items_per_second=1.75232M/s null_percent=0.01 size=32.768k
ArraySortIndicesStringWide/32768/100              606 us          605 us         1169 bytes_per_second=51.627M/s items_per_second=1.70824M/s null_percent=1 size=32.768k
ArraySortIndicesStringWide/32768/10               610 us          610 us         1145 bytes_per_second=51.2671M/s items_per_second=1.86694M/s null_percent=10 size=32.768k
ArraySortIndicesStringWide/32768/2                653 us          652 us         1072 bytes_per_second=47.8979M/s items_per_second=3.13904M/s null_percent=50 size=32.768k
ArraySortIndicesStringWide/32768/1               79.4 us         79.4 us         8561 bytes_per_second=393.738M/s items_per_second=12.902M/s null_percent=100 size=32.768k
ArraySortIndicesStringWide/32768/0                580 us          579 us         1203 bytes_per_second=53.9836M/s items_per_second=1.76893M/s null_percent=0 size=32.768k
ArraySortIndicesStringWide/1048576/100          25200 us        25175 us           28 bytes_per_second=39.7218M/s items_per_second=1.31475M/s null_percent=1 size=1048.58k
ArraySortIndicesStringWide/8388608/100         239121 us       238851 us            3 bytes_per_second=33.4937M/s items_per_second=1.10861M/s null_percent=1 size=8.38861M
ArraySortIndicesStringWideDict/32768/10000        190 us          190 us         3683 bytes_per_second=164.852M/s items_per_second=5.40187M/s null_percent=0.01 size=32.768k
ArraySortIndicesStringWideDict/32768/100          195 us          195 us         3591 bytes_per_second=160.284M/s items_per_second=5.30347M/s null_percent=1 size=32.768k
ArraySortIndicesStringWideDict/32768/10           216 us          216 us         3244 bytes_per_second=144.701M/s items_per_second=5.26945M/s null_percent=10 size=32.768k
ArraySortIndicesStringWideDict/32768/2            278 us          278 us         2504 bytes_per_second=112.403M/s items_per_second=7.36645M/s null_percent=50 size=32.768k
ArraySortIndicesStringWideDict/32768/1            108 us          108 us         6456 bytes_per_second=288.614M/s items_per_second=9.45732M/s null_percent=100 size=32.768k
ArraySortIndicesStringWideDict/32768/0            190 us          190 us         3676 bytes_per_second=164.204M/s items_per_second=5.38062M/s null_percent=0 size=32.768k
ArraySortIndicesStringWideDict/1048576/100       1005 us         1005 us          695 bytes_per_second=995.211M/s items_per_second=32.9405M/s null_percent=1 size=1048.58k
ArraySortIndicesStringWideDict/8388608/100       6826 us         6823 us          102 bytes_per_second=1.14501G/s items_per_second=38.8083M/s null_percent=1 size=8.38861M
```
