### PR TITLE
GH-37021 [Java][arrow-jdbc] Pluggable getConsumer

### LINKED ISSUE #37021: [Java][JDBC] Converting TIMESTAMP_WITH_TIMEZONE
### Describe the usage question you have. Please include as many useful details as  possible.

# Error description

We have a Java FlightServer for Arrow Flight SQL that connects to various types of datawarehouses through JDBC and converts the results into arrow to send back using `sqlToArrowVectorIterator`. Everything has been working pretty well, but we just ran into some issues with `TIMESTAMP_TZ` columns on Snowflake.

We were getting the following exception (redacted):
```
java.lang.RuntimeException: Error occurred while creating iterator.
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.create(ArrowVectorIterator.java:87)
	at org.apache.arrow.adapter.jdbc.JdbcToArrow.sqlToArrowVectorIterator(JdbcToArrow.java:101)
...
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.arrow.vector.types.pojo.ArrowType.getTypeID()" because "arrowType" is null
	at org.apache.arrow.adapter.jdbc.JdbcToArrowUtils.getConsumer(JdbcToArrowUtils.java:437)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.initialize(ArrowVectorIterator.java:142)
	at org.apache.arrow.adapter.jdbc.ArrowVectorIterator.createVectorSchemaRoot(ArrowVectorIterator.java:134)
```

After digging around, I noticed we were getting back a JDBC type `TIMESTAMP_WITH_TIMEZONE` (2014) which wasn't mapped by the default converter `JdbcToArrowUtils.getArrowTypeFromJdbcType`. I created my own converter that mapped that type the same way it maps `TIMESTAMP` to get me unblocked (figured I'd deal with the TZ issue later). Now I don't get the exception, but the `TIMESTAMP_WITH_TIMEZONE` is excluded from the results. For example here's how I set up the data in Snowflake:

image

And here's what I get when I query through Dbeaver using the AFS JDBC driver through our service:

image

# Debugging attempts

My attempts at debugging this have yielded very strange results:

- When I look in the debugger on our service, the `VectorSchemaRoot` looks correct:

image

- If I try to select just the NTZ column it works fine:
image

- If I try to select just the TZ column it seems to try to make a `acceptPutPreparedStatementUpdate` call, which we haven't implemented so it fails.

My guess is that this is a bug on the JDBC driver, but as far as that's concerned the 2 vectors are of the same type, so I don't see why it would just drop one column.

Any help would be greatly appreciated!

### Component(s)

Java

### PR DESCRIPTION
**Pull request by aiguofer**
### Rationale for this change

This was discussed in [this thread](https://github.com/apache/arrow/issues/37021#issuecomment-1666169351). The `getConsumer` implementation depends on the implementation for `getArrowTypeFromJdbcType`, especially for timestamp objects. Since we can provide a different implementation for `JdbcToArrowTypeConverter` it follows we should be able to provide a different implementation for `JdbcConsumerGetter`

### What changes are included in this PR?

Adds a way to configure an alternate `JdbcToArrowUtils.getConsumer` function through `JdbcToArrowConfigBuilder.setJdbcConsumerGetter`.

It also throws a more helpful exception from the default implementations when a provided type is not mapped.

### Are these changes tested?

No, the default behavior remains unchanged.
* Related: #37021
* Closes: #37021

### CODE REVIEW

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowUtils.java [hunk 1]
```diff
@@ -489,7 +489,7 @@ static JdbcConsumer getConsumer(ArrowType arrowType, int columnIndex, boolean nu
         return new NullConsumer((NullVector) vector);
       default:
         // no-op, shouldn't get here
-        throw new UnsupportedOperationException();
+        throw new UnsupportedOperationException("No consumer for Arrow type: " + arrowType.getTypeID());
```
Comment (lidavidm) [inline java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowUtils.java:492]: nit: might prefer just arrowType so we get the full toString?

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java [hunk 2]
```diff
@@ -338,4 +356,18 @@ public Map<Integer, Map<String, String>> getColumnMetadataByColumnIndex() {
...
+   * Interface for a function with 4 parameters.
+   *
+     * @param <A> param 1 type
+     * @param <B> param 2 type
+     * @param <C> param 3 type
+     * @param <D> param 4 type
+     * @param <R> return type
+   */
+  @FunctionalInterface
+  interface Function4Arity<A, B, C, D, R> {
```
Comment (lidavidm) [inline java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java:370]: 1. public?
2. Let's make this interface specific to the getter (so JdbcConsumerFactory or similar) so it's clear what it's for? (Also then it doesn't need to be generic.)

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java [hunk 3]
```diff
@@ -102,9 +105,10 @@ public final class JdbcToArrowConfig {
           Map<Integer, JdbcFieldInfo> arraySubTypesByColumnIndex,
           Map<String, JdbcFieldInfo> arraySubTypesByColumnName,
           int targetBatchSize,
-          Function<JdbcFieldInfo, ArrowType> jdbcToArrowTypeConverter) {
+          Function<JdbcFieldInfo, ArrowType> jdbcToArrowTypeConverter,
+          Function4Arity<ArrowType, Integer, Boolean, FieldVector, JdbcConsumer> jdbcConsumerGetter) {
```
Comment (lidavidm) [inline java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java:109]: Could we add a delegate constructor to avoid breaking existing code?

**Review by lidavidm — COMMENTED** [review]
Thanks!

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java (hunk 3 above)
Comment (aiguofer) [reply java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java]: done!

File: java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java (hunk 2 above)
Comment (aiguofer) [reply java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java]: done! Though I realized that most implementations will likely also need the config itself as one of the parameters... bit of a chicken and egg problem. You don't have the config yet when building the config -.-

I'm thinking there might be some way to do this but I'm not familiar enough with java to think of a good solution. I imagine some sort of wrapper or abstract class that injects the instance of the config when `apply` is called but I'm not exactly sure what this would look like.

Comment (lidavidm) [reply java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java]: Ah, I forgot about that.

Can't you just make it one of the parameters? You're not going to invoke this while building the config, so it's fine to have it as a parameter.

Comment (aiguofer) [reply java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfig.java]: Oh right, lol not sure why I was overcomplicating it. FIxed

**Review by lidavidm — APPROVED** [review]
Thanks!

**Comment by lidavidm** [comment]
Hmm, it's not clear why, but CI is failing - does the test suite pass for you?

**Comment by aiguofer** [comment]
Hmm no... it is hanging on `TestFlightSql.testGetTablesResultFilteredWithSchema`, trying to track it down.

**Comment by aiguofer** [comment]
ahh tracked it down to an uncaught exception with unmapped JDBC types

**Review by lidavidm — APPROVED** [review]
