### PR TITLE
GH-38399: [Go][Parquet] DeltaBitPack decoder reset usedFirst after SetData

### LINKED ISSUE #38399: [Go] DeltaBitPack deltaBitWidths overflow
### Describe the bug, including details regarding any error messages, version, and platform.

I wrote some int64 using c++ ::parquet::Encoding::DELTA_BINARY_PACKED
and then tried to read this with go but got:

```
panic: runtime error: index out of range [4] with length 4

goroutine 199 [running]:
github.com/apache/arrow/go/v14/parquet/internal/encoding.(*DeltaBitPackInt64Decoder).unpackNextMini(0xc1aee302a0)
        /home/dstasenko/go/pkg/mod/github.com/apache/arrow/go/v14@v14.0.0-20231023113027-37935604bf16/parquet/internal/encoding/delta_bit_packing.go:230 +0x2da
github.com/apache/arrow/go/v14/parquet/internal/encoding.(*DeltaBitPackInt64Decoder).Decode(0xc1aee302a0, {0xc1cc73b008?, 0xa7d50d?, 0xc1adb08360?})
        /home/dstasenko/go/pkg/mod/github.com/apache/arrow/go/v14@v14.0.0-20231023113027-37935604bf16/parquet/internal/encoding/delta_bit_packing.go:267 +0x118
github.com/apache/arrow/go/v14/parquet/file.(*Int64ColumnChunkReader).ReadBatch.func1(0x15a201, 0x167d01)
        /home/dstasenko/go/pkg/mod/github.com/apache/arrow/go/v14@v14.0.0-20231023113027-37935604bf16/parquet/file/column_reader_types.gen.go:93 +0xa3
github.com/apache/arrow/go/v14/parquet/file.(*columnChunkReader).readBatch(0xc1adb08360, 0x3c9c00, {0xc1d3f26000, 0x3c9c00, 0x3c9c00}, {0x0, 0x0, 0x0}, 0xc1aeb73c80)
        /home/dstasenko/go/pkg/mod/github.com/apache/arrow/go/v14@v14.0.0-20231023113027-37935604bf16/parquet/file/column_reader.go:508 +0xc2
github.com/apache/arrow/go/v14/parquet/file.(*Int64ColumnChunkReader).ReadBatch(0xc1aee2e3d0?, 0xc1aee36960?, {0xc1cbc6a000?, 0x2b21d60?, 0xc0001a9d58?}, {0xc1d3f26000?, 0x1a49d55?, 0xa?}, {0x0, 0x0, ...})
```

I assume that this line lacks boundaries check https://github.com/apache/arrow/blob/ac581fd2a87b35c872cf334bb147851fe1287714/go/parquet/internal/encoding/delta_bit_packing.go#L228

### Component(s)

Go

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

As https://github.com/apache/arrow/issues/38399 says. DeltaBitPack will corrupt when we meet a column chunk
with more than one page. During first page decoding, it works well. But when the second page comes, the
`d.usedFirst` haven't been reset, which cause the bug.

### What changes are included in this PR?

1. Some style enhancement
2. Bug fix

### Are these changes tested?

Currently not

### Are there any user-facing changes?

bugfix

* Closes: #38399

### CODE REVIEW

**Comment by mapleFU** [comment]
@zeroshade I've investigate and submit a fixing. It's a bit late in UTC-8. I'll add tests tomorrow.

File: go/parquet/internal/encoding/delta_bit_packing.go [hunk 1]
```diff
@@ -172,6 +174,10 @@ func (d *DeltaBitPackInt32Decoder) Decode(out []int32) (int, error) {
 	for len(out) > 0 { // unpack mini blocks until we get all the values we need
 		if d.currentBlockVals == 0 {
 			err = d.initBlock()
+			if err != nil {
+				return 0, err
+			}
+			d.currentMiniBlockVals = 0
```
Comment (zeroshade) [inline go/parquet/internal/encoding/delta_bit_packing.go:180]: isn't this redundant due to the above if statement?

File: go/parquet/internal/encoding/delta_bit_packing.go [hunk 2]
```diff
@@ -260,6 +266,10 @@ func (d *DeltaBitPackInt64Decoder) Decode(out []int64) (int, error) {
 	for len(out) > 0 {
 		if d.currentBlockVals == 0 {
 			err = d.initBlock()
+			if err != nil {
+				return 0, err
+			}
+			d.currentMiniBlockVals = 0
```
Comment (zeroshade) [inline go/parquet/internal/encoding/delta_bit_packing.go:272]: same as above, isn't this redundant due to the if above?

**Comment by zeroshade** [comment]
This looks great to me @mapleFU thanks! I'll review again once you add the tests

File: go/parquet/internal/encoding/delta_bit_packing.go [hunk 3]
```diff
@@ -82,9 +82,12 @@ func (d *deltaBitPackDecoder) SetData(nvalues int, data []byte) error {
 		return xerrors.New("parquet: eof exception")
 	}
 
-	if d.miniBlocks, ok = d.bitdecoder.GetVlqInt(); !ok {
+	if d.miniBlocksPerBlock, ok = d.bitdecoder.GetVlqInt(); !ok {
 		return xerrors.New("parquet: eof exception")
 	}
+	if d.miniBlocksPerBlock == 0 {
+		return xerrors.New("parquet: cannot have zero miniblock per block")
```
[the remark this answers is not in the document]
Comment (mapleFU) [reply go/parquet/internal/encoding/delta_bit_packing.go:89]: Should I replace the `xerrors` in this file? Since mixing `xerror` and standard lib is so weird :-(

**Comment by mapleFU** [comment]
I'm not familiar with go enough, so don't know why CI failed...

**Comment by zeroshade** [comment]
@mapleFU The failing appveyor test doesn't appear related at all so you're fine there.

Are either of the tests you added able to reproduce the initial failure that was reported in the issue (without your fix)? If not, can you add a test that does reproduce the initial failure?

**Comment by mapleFU** [comment]
```go
		// Using same Decoder to decode the data.
		dec := encoding.NewDecoder(parquet.Types.Int32, parquet.Encodings.DeltaBinaryPacked, column, memory.DefaultAllocator)
		for i := 0; i < 5; i += 1 {
			dec.(encoding.Int32Decoder).SetData(len(values), buf.Bytes())

			valueBuf := make([]int32, 100)
			for i, j := 0, len(valueBuf); j <= len(values); i, j = i+len(valueBuf), j+len(valueBuf) {
				dec.(encoding.Int32Decoder).Decode(valueBuf)
				assert.Equalf(t, values[i:j], valueBuf, "indexes %d:%d", i, j)
			}
		}
```

I've add the same test for int32 and int64, please refer to "test decoding multiple pages". @zeroshade

**Review by zeroshade — APPROVED** [review]
