### PR TITLE
GH-36883: [R] Remove version number which triggers CRAN warning

### LINKED ISSUE #36883: [R] Remove version number which triggers CRAN warning
### Describe the bug, including details regarding any error messages, version, and platform.

Email from CRAN:

> the new arrow has
> 
> ** using staged installation
> Warning in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) :
>   invalid non-character version specification 'x' (type: double)
> Calls: Ops.numeric_version ... as.numeric_version -> numeric_version -> .make_numeric_version
> Calls:
>  1: Ops.numeric_version(dev_version, 100)
> 
> warning from
> 
> ./tools/nixlibs.R:dev_version <- package_version(VERSION)[1, 4]
> ./tools/nixlibs.R:if ([is.na](http://is.na/)(dev_version) || dev_version < 100) {
> 
> which should have "100" instead: can you pls fix?

### Component(s)

R

### PR DESCRIPTION
**Pull request by thisisnic**
### What changes are included in this PR?

Updates package version number to be character not numeric

### Are these changes tested?

No, is configure scripts

### Are there any user-facing changes?

No
* Closes: #36883

### CODE REVIEW

File: r/tools/winlibs.R [hunk 1]
```diff
@@ -53,7 +53,7 @@ if (!file.exists(sprintf("windows/arrow-%s/include/arrow/api.h", VERSION))) {
     dev_version <- package_version(VERSION)[1, 4]
 
     # Small dev versions are added for R-only changes during CRAN submission.
-    if (is.na(dev_version) || dev_version < 100) {
+    if (is.na(dev_version) || dev_version < "100") {
```
Comment (assignUser) [inline r/tools/winlibs.R:56]: Does the logic still work? gt/lt string comparisons can be funky iirc. Maybe we should explicitly convert it to a version object (or what ever it's called)

Comment (thisisnic) [reply r/tools/winlibs.R:56]: This is what was recommended in the email from CRAN, but you're right, i.e. `"10" > "2" == FALSE`.

Comment (thisisnic) [reply r/tools/winlibs.R:56]: Actually, nope, it doesn't matter; because `dev_version` is a `package_version` object, it's fine (i.e. in this case testing that a dev version of `10` is higher than the string "2"  returns TRUE in the above comparison when done with the right classes)

Comment (thisisnic) [reply r/tools/winlibs.R:56]:
``` r
x <- package_version("0.0.0.10")[1, 4]
x
#> [1] '10'
x > 2
#> [1] TRUE
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Comment (assignUser) [reply r/tools/winlibs.R:56]: Ah nice, yay for implicit casts :D

**Review by assignUser — APPROVED** [review]
