### PR TITLE
GH-35519: [C++][Parquet] Fixing exception handling in parquet FileSerializer

### LINKED ISSUE #35519: [C++][Parquet] Segfault when exception handling and closing RowGroupSerializer
### Describe the bug, including details regarding any error messages, version, and platform.

When closing `RowGroupSerializer` in Parquet, the program segfault on:

```
CheckRowsWritten
- RowGroupSerializer::num_rows
-- RowGroupSerializer::Close
--- FileSerializer::Close
---- ~FileSerializer
``` 

And after some analyze, I found that the bug is due to exception handling. When calling `FileSerializer::AppendRowGroup`, the `RowGroupSerializer::Close` is called. So, it goes to loop:

```c++
  void Close() override {
    if (!closed_) {
      closed_ = true;
      CheckRowsWritten();

      for (size_t i = 0; i < column_writers_.size(); i++) {
        if (column_writers_[i]) {
          total_bytes_written_ += column_writers_[i]->Close();
          total_compressed_bytes_written_ +=
              column_writers_[i]->total_compressed_bytes_written();
          column_writers_[i].reset();
        }
      }

      column_writers_.clear();

      // Ensures all columns have been written
      metadata_->set_num_rows(num_rows_);
      metadata_->Finish(total_bytes_written_, row_group_ordinal_);
    }
  }
```

When calling `column_writers_[i]->Close()` in `buffered mode`, exception is thrown. So, assume there are 3 columns, and throw exception on the second one, `column_writers_` would be:

```
nullptr
non-null
non-null
```

Thats ok, when exception propagated, it will call `FileSerializer::Close`:

```c++
  void Close() override {
    if (is_open_) {
      // If any functions here raise an exception, we set is_open_ to be false
      // so that this does not get called again (possibly causing segfault)
      is_open_ = false;
      if (row_group_writer_) {
        num_rows_ += row_group_writer_->num_rows();
        row_group_writer_->Close();
      }
      row_group_writer_.reset();

      WritePageIndex();

      // Write magic bytes and metadata
      auto file_encryption_properties = properties_->file_encryption_properties();

      if (file_encryption_properties == nullptr) {  // Non encrypted file.
        file_metadata_ = metadata_->Finish(key_value_metadata_);
        WriteFileMetaData(*file_metadata_, sink_.get());
      } else {  // Encrypted file
        CloseEncryptedFile(file_encryption_properties);
      }
    }
  }
```

The code looks good, however, this time, `row_group_writer_ != nullptr`, so `row_group_writer_->num_rows()` is called:

```c++
  int64_t num_rows() const override {
    CheckRowsWritten();
    // CheckRowsWritten ensures num_rows_ is set correctly
    return num_rows_;
  }

  void CheckRowsWritten() const {
    // verify when only one column is written at a time
    if (!buffered_row_group_ && column_writers_.size() > 0 && column_writers_[0]) {
      int64_t current_col_rows = column_writers_[0]->rows_written();
      if (num_rows_ == 0) {
        num_rows_ = current_col_rows;
      } else if (num_rows_ != current_col_rows) {
        ThrowRowsMisMatchError(next_column_index_, current_col_rows, num_rows_);
      }
    } else if (buffered_row_group_ &&
               column_writers_.size() > 0) {  // when buffered_row_group = true
      int64_t current_col_rows = column_writers_[0]->rows_written();
      for (int i = 1; i < static_cast<int>(column_writers_.size()); i++) {
        int64_t current_col_rows_i = column_writers_[i]->rows_written();
        if (current_col_rows != current_col_rows_i) {
          ThrowRowsMisMatchError(i, current_col_rows_i, current_col_rows);
        }
      }
      num_rows_ = current_col_rows;
    }
  }
```

This time, it will call `column_writers_[i]->...`, which is a nullptr call, causing segfault.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Mentioned in https://github.com/apache/arrow/issues/35519

### What changes are included in this PR?

Exception handling in `CheckRowsWritten`

### Are these changes tested?

No, I don't know how to mock it currently

### Are there any user-facing changes?

no

* Closes: #35519

### CODE REVIEW

**Comment by mapleFU** [comment]
@pitrou Would you mind take a look? Analyze is in https://github.com/apache/arrow/issues/35519#issue-1702385078

**Comment by mapleFU** [comment]
@pitrou Good Idea! Fix as your advice

File: cpp/src/parquet/file_writer.cc [hunk 1]
```diff
@@ -219,17 +219,17 @@ class RowGroupSerializer : public RowGroupWriter::Contents {
...
-        if (column_writers_[i]) {
-          total_bytes_written_ += column_writers_[i]->Close();
+      // If ColumnWriter::Close thrown an exception, avoid
+      // have bad states in column_writers_.
+      auto column_writers = std::move(column_writers_);
+      for (size_t i = 0; i < column_writers.size(); i++) {
+        if (column_writers[i]) {
+          total_bytes_written_ += column_writers[i]->Close();
           total_compressed_bytes_written_ +=
               column_writers_[i]->total_compressed_bytes_written();
```
Comment (pitrou) [inline cpp/src/parquet/file_writer.cc:229]:
```suggestion
              column_writers[i]->total_compressed_bytes_written();
```

File: cpp/src/parquet/file_writer.cc [hunk 2]
```diff
@@ -380,15 +382,15 @@ class FileSerializer : public ParquetFileWriter::Contents {
...
+      key_value_metadata_ = key_value_metadata;
     } else if (key_value_metadata != nullptr) {
       key_value_metadata_ = key_value_metadata_->Merge(*key_value_metadata);
     }
   }
 
   ~FileSerializer() override {
     try {
-      Close();
+      FileSerializer::Close();
```
Comment (pitrou) [inline cpp/src/parquet/file_writer.cc:393]: Why is this change required?

File: cpp/src/parquet/file_writer.cc [hunk 3]
```diff
@@ -219,17 +219,17 @@ class RowGroupSerializer : public RowGroupWriter::Contents {
       closed_ = true;
       CheckRowsWritten();
 
-      for (size_t i = 0; i < column_writers_.size(); i++) {
-        if (column_writers_[i]) {
-          total_bytes_written_ += column_writers_[i]->Close();
+      // If ColumnWriter::Close thrown an exception, avoid
+      // have bad states in column_writers_.
```
Comment (wgtmac) [inline cpp/src/parquet/file_writer.cc:223]:
```suggestion
      // Avoid invalid state if ColumnWriter::Close() throws internally.
```

Comment (wgtmac) [reply cpp/src/parquet/file_writer.cc:223]: If anything wrong happens here, should we let the FileSerializer know that it cannot accept any write any more?

Comment (mapleFU) [reply cpp/src/parquet/file_writer.cc:223]:
```c++
  void Close() override {
    if (!closed_) {
      closed_ = true;
      CheckRowsWritten();
 

      // ...

      // Ensures all columns have been written
      metadata_->set_num_rows(num_rows_);
      metadata_->Finish(total_bytes_written_, row_group_ordinal_);
    }
  }
```

I guess it will mark `closed_` first and throw exception. During stack unwind, the `RowGroupSerializer` will destruct. And during next time `Close` is called, it will do nothing

**Comment by pitrou** [comment]
> Seems CI failed frequently these days...

Unfortunately :-( Are there issues already open for these failures?

**Review by pitrou — APPROVED** [review]
Thanks @mapleFU . This looks ok now.

**Comment by pitrou** [comment]
Hmm, the R CI failure may be related as it seems to succeed on git main:
https://github.com/apache/arrow/actions/runs/4937417890/jobs/8826087049

**Comment by mapleFU** [comment]
Yeah, I don't want to rebase this because there are still too much failed tests :-(
Just wait others idea on this patch or merge if you think it's ok

**Comment by pitrou** [comment]
We can't merge until we make sure the R CI failure is unrelated.

**Comment by pitrou** [comment]
Hmm, actually the segfault is already known:
https://github.com/apache/arrow/issues/35391

**Comment by mapleFU** [comment]
😭Hurt by so many failed

**Comment by mapleFU** [comment]
```
[ RUN      ] TestScan/TestCsvFileFormatScan.ScanBatchSize/0Threaded16b1024r
unknown file: error: SEH exception with code 0xc00000fd thrown in the test body.
[  FAILED  ] TestScan/TestCsvFileFormatScan.ScanBatchSize/0Threaded16b1024r, where GetParam() = Threaded16b1024r (314 ms)
```

I guess this is unrelated. https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/47021836

**Comment by mapleFU** [comment]
@pitrou Seems R failed is not related. Would you mind take a look?

**Comment by pitrou** [comment]
I'm restarting CI a last time but it looks like this is ready to go.
