### PR TITLE
GH-37858: [Docs][JS] Fix check of remote URL to generate JS docs

### LINKED ISSUE #37858: [Docs][Website] JS docs are missing
### Describe the bug, including details regarding any error messages, version, and platform.

The JS docs at https://arrow.apache.org/docs/js/index.html are not accessible probably because of some reorganization of the website. 

The docs for 12 are at https://arrow.apache.org/docs/12.0/js/index.html but https://arrow.apache.org/docs/13.0/js/index.html doesn't exist either. 

### Component(s)

Documentation

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

JS Docs are currently not being generated.

### What changes are included in this PR?

Use a regex check instead of an equality to cover both remote set with `.git` and without for upstream. Added also a fix to generate docs from origin from forks if necessary.

### Are these changes tested?

Via archery

### Are there any user-facing changes?
No
* Closes: #37858

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit preview-docs

**Comment by raulcd** [comment]
It seems this never worked for PRs / preview docs, I did fix that and the fix should allow to fix the doc generation now. For the preview-docs it can be seen here: http://crossbow.voltrondata.com/pr_docs/37870/js/index.html

File: ci/scripts/js_build.sh [hunk 1]
```diff
@@ -32,12 +32,14 @@ yarn lint:ci
...
-  if [ "$(git config --get remote.origin.url)" == "https://github.com/apache/arrow.git" ]; then
-    yarn doc
-  elif [ "$(git config --get remote.upstream.url)" == "https://github.com/apache/arrow.git" ]; then
-    yarn doc --gitRemote upstream
-  elif [ "$(git config --get remote.apache.url)" == "git@github.com:apache/arrow.git" ]; then
+  # If apache or upstream are defined use those as remote.
+  # Otherwise use origin which could be a fork on PRs.
+  if [ "$(git config --get remote.apache.url)" == "git@github.com:apache/arrow.git" ]; then
     yarn doc --gitRemote apache
+  elif [[ "$(git config --get remote.upstream.url)" =~ "https://github.com/apache/arrow" ]]; then
```
Comment (raulcd) [inline ci/scripts/js_build.sh:39]: this will work with both `https://github.com/apache/arrow` and `https://github.com/apache/arrow.git`

**Comment by domoritz** [comment]
Awesome. Thanks for making the preview docs work as well!

**Review by domoritz — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1

**Comment by domoritz** [comment]
Sweet. Thanks for the quick fix @raulcd. I guess you need to push the generated docs to the docs repo to update https://arrow.apache.org/docs/js/, right?

**Comment by raulcd** [comment]
> Sweet. Thanks for the quick fix @raulcd. I guess you need to push the generated docs to the docs repo to update https://arrow.apache.org/docs/js/, right?

Yes, I have to generate the docs from the 13.0.0 branch and create a PR to the arrow-site repo. I'm currently working on that.

**Comment by raulcd** [comment]
The docs PR has been created there: https://github.com/apache/arrow-site/pull/412
