### PR TITLE
GH-34960: [C++] test util Fixing arrow Random Generator for lost nullable info

### LINKED ISSUE #34960: [C++] TestUtil: RandomArrayGenerator will lost the "nullable" info when build nested list
### Describe the bug, including details regarding any error messages, version, and platform.

```C++
  {
    auto item = std::make_shared<arrow::Field>("item", arrow::int8(), true);
    auto nestListField =
        std::make_shared<arrow::Field>("list", arrow::list(item), false);
    auto listField =
        std::make_shared<arrow::Field>("list", arrow::list(nestListField), true);
    auto array = rng.ArrayOf(*listField, 428);
    ARROW_EXPECT_OK(array->ValidateFull());

    auto batch = rng.BatchOf({listField}, 428);
    ARROW_EXPECT_OK(batch->ValidateFull());
  }
```

The code above will validate failed, because it lost the nullable info in nested list

### Component(s)

C++

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Currently, nonnull in nested schema will be losted by random generator. This patch make it not lost.

### What changes are included in this PR?

Using ctor with DataType to deduce the field type.

### Are there any user-facing changes?

* Closes: #34960

### CODE REVIEW

**Comment by mapleFU** [comment]
@wjones127 @lidavidm Mind take a look?

**Comment by lidavidm** [comment]
I'm OOO so I probably can't get to this for a while, sorry

**Comment by mapleFU** [comment]
Don't worry, you can review it any time :)

File: cpp/src/arrow/testing/random.cc [hunk 1]
```diff
@@ -793,7 +793,7 @@ std::shared_ptr<Array> RandomArrayGenerator::ArrayOf(const Field& field, int64_t
                 values_length, alignment, memory_pool);                              \
     const auto offsets = OffsetsFromLengthsArray(lengths.get(), force_empty_nulls,   \
                                                  alignment, memory_pool);            \
-    return *ARRAY_TYPE::FromArrays(*offsets, *values);                               \
+    return *ARRAY_TYPE::FromArrays(field.type(), *offsets, *values);                 \
```
Comment (wgtmac) [inline cpp/src/arrow/testing/random.cc:796]: Does map type have similar issue?

File: cpp/src/arrow/testing/random.cc [hunk 2]
```diff
@@ -916,14 +916,14 @@ std::shared_ptr<Array> RandomArrayGenerator::ArrayOf(const Field& field, int64_t
...
+      FieldVector child_fields;
       for (int i = 0; i < field.type()->num_fields(); i++) {
         const auto& child_field = field.type()->field(i);
         child_arrays[i] = ArrayOf(*child_field, length, alignment, memory_pool);
-        field_names.push_back(child_field->name());
+        child_fields.push_back(child_field);
       }
       return *StructArray::Make(
-          child_arrays, field_names,
+          child_arrays, child_fields,
```
Comment (wgtmac) [inline cpp/src/arrow/testing/random.cc:926]: Shouldn't the original overload get the data type from `child_arrays`? I saw a comment of the current overload saying `This method does not check that field types and child array types are consistent.` It seems that we need to fix the original `Make` function as well.

File: cpp/src/arrow/testing/random.cc (hunk 1 above)
Comment (mapleFU) [reply cpp/src/arrow/testing/random.cc:796]: No, the problem is a bit tricky. Let me explain it:
1. Arrow has `DataType`, `DataType` doesn't including some nullable info itself. `Field` has nullable info.
2. For `DataType` , it child would be array of `Field`, so DataType has children's nullable info

Here if doesn't pass `field.type()` in ctor, it will mark child as nullable. And Map's constructor already marks it.

File: cpp/src/arrow/testing/random.cc (hunk 2 above)
Comment (mapleFU) [reply cpp/src/arrow/testing/random.cc:926]: Yes, In fact I use `Generator` to generate testing data, but it `ValidationFull` fails, lol
Maybe @lidavidm can take a look?

**Comment by mapleFU** [comment]
@westonpace Hi, I use `BatchOf` to generate a random List/Struct, however, the generated data call `ValidateFull` failed. This patch is a fixing. Would you mind take a look?

File: cpp/src/arrow/testing/random_test.cc [hunk 3]
```diff
@@ -499,6 +499,45 @@ TEST(RandomList, Basics) {
   }
 }
 
+TEST(RandomNestedBatchOf, Basics) {
+  random::RandomArrayGenerator rng(42);
+  {
+    auto item = std::make_shared<arrow::Field>("item", arrow::int8(), true);
+    auto nestListField = std::make_shared<arrow::Field>("list", arrow::list(item), false);
```
Comment (lidavidm) [inline cpp/src/arrow/testing/random_test.cc:506]: nit: use `arrow::field` helper, remember to use `snake_case` variable names

File: cpp/src/arrow/testing/random.cc (hunk 1 above)
Comment (lidavidm) [reply cpp/src/arrow/testing/random.cc:796]: Specifically, if you look at the case for MapType, it already passes the type. So this is just bringing ListType into alignment.

File: cpp/src/arrow/testing/random.cc (hunk 2 above)
Comment (lidavidm) [reply cpp/src/arrow/testing/random.cc:926]: Sorry, what are you saying fails? I agree the proposed code is more correct.

File: cpp/src/arrow/testing/random_test.cc [hunk 4]
```diff
@@ -499,6 +499,45 @@ TEST(RandomList, Basics) {
   }
 }
 
+TEST(RandomNestedBatchOf, Basics) {
```
Comment (lidavidm) [inline cpp/src/arrow/testing/random_test.cc:502]: Can this just be part of the `RandomList` suite as a new case?

File: cpp/src/arrow/testing/random_test.cc [hunk 5]
```diff
@@ -499,6 +499,45 @@ TEST(RandomList, Basics) {
...
+    auto nestListField = std::make_shared<arrow::Field>("list", arrow::list(item), false);
+    auto listField =
+        std::make_shared<arrow::Field>("list", arrow::list(nestListField), true);
+    auto array = rng.ArrayOf(*listField, 428);
+    ARROW_EXPECT_OK(array->ValidateFull());
+
+    auto batch = rng.BatchOf({listField}, 428);
+    ARROW_EXPECT_OK(batch->ValidateFull());
+  }
+  {
```
Comment (lidavidm) [inline cpp/src/arrow/testing/random_test.cc:515]: Can this be made into a `RandomStruct` suite?

File: cpp/src/arrow/testing/random_test.cc [hunk 6]
```diff
@@ -499,6 +499,45 @@ TEST(RandomList, Basics) {
...
+        std::make_shared<arrow::Field>("struct", arrow::struct_({item}), false);
+    auto structField =
+        std::make_shared<arrow::Field>("struct", arrow::struct_({nestStructField}), true);
+    auto array = rng.ArrayOf(*structField, 428);
+    ARROW_EXPECT_OK(array->ValidateFull());
+
+    auto batch = rng.BatchOf({structField}, 428);
+    ARROW_EXPECT_OK(batch->ValidateFull());
+  }
+  {
```
Comment (lidavidm) [inline cpp/src/arrow/testing/random_test.cc:527]: And `RandomMap` here.

File: cpp/src/arrow/testing/random_test.cc (hunk 4 above)
Comment (lidavidm) [reply cpp/src/arrow/testing/random_test.cc:502]: And for all three tests, can you call out specifically that we want to test child field nullability is preserved?

File: cpp/src/arrow/testing/random.cc (hunk 1 above)
Comment (mapleFU) [reply cpp/src/arrow/testing/random.cc:796]: Yes, this patch brings `List` and `Struct` into alignment. For testing, I also tests map

File: cpp/src/arrow/testing/random.cc (hunk 2 above)
Comment (lidavidm) [reply cpp/src/arrow/testing/random.cc:926]: Ok, but I don't really get what this thread is trying to discuss.

@wgtmac note that types do not carry nullability info. So we need to use fields here, this isn't a problem with Make.

**Comment by mapleFU** [comment]
Comment resolved

**Review by lidavidm — APPROVED** [review]

File: cpp/src/arrow/testing/random.cc (hunk 2 above)
Comment (wgtmac) [reply cpp/src/arrow/testing/random.cc:926]: I just realized that `DataType` does not know the nullability but `Field` does. Thanks for reminding me! @lidavidm

**Comment by wgtmac** [comment]
@raulcd Could you please backport this patch to v12.0.0 release? Thanks!

**Comment by raulcd** [comment]
I've taken a look and as it is a minor bug fix that almost made the feature freeze I've added it to the 12.0.0. I'll try to write something to document more clearly what should be backported once the feature freeze has been done. For bug fixes we should probably include:
* Critical fixes
* Regression issues
* Incorrect data issues
