### PR TITLE
GH-34316: [Python] FixedSizeListArray.from_arrays supports mask parameter

### LINKED ISSUE #34316: [Python] Support `mask` in `FixedSizeListArray.from_arrays`
### Describe the enhancement requested

In [`ListArray.from_arrays`](https://arrow.apache.org/docs/python/generated/pyarrow.ListArray.html#pyarrow.ListArray.from_arrays) it's possible to pass in a mask array defining which list elements are null. [`FixedSizeListArray.from_arrays`](https://arrow.apache.org/docs/python/generated/pyarrow.FixedSizeListArray.html#pyarrow.FixedSizeListArray.from_arrays) does not currently have a `mask` parameter, so it appears impossible to create a fixed size list array where some elements are null?

```py
pa.array([1, 2, 3, 4], mask=[False, True, False, False])
# <pyarrow.lib.Int64Array object at 0x126eb29e0>
# [
#   1,
#   null,
#   3,
#   4
# ]
pa.FixedSizeListArray.from_arrays([1, 2, 3, 4], 2)
# <pyarrow.lib.FixedSizeListArray object at 0x127255900>
# [
#   [
#     1,
#     2
#   ],
#   [
#     3,
#     4
#   ]
# ]
pa.FixedSizeListArray.from_arrays([1, 2, 3, 4], 2, mask=[False, True])
# TypeError                                 Traceback (most recent call last)
# /Users/kyle/fused/application/job/job/raster/naip/async_zonal_stats.py in line 1
# ----> 449 pa.FixedSizeListArray.from_arrays([1, 2, 3, 4], 2, mask=[False, True])
#
# File ~/fused/application/job/.venv/lib/python3.11/site-packages/pyarrow/array.pxi:2141, in pyarrow.lib.FixedSizeListArray.from_arrays()
#
# TypeError: from_arrays() got an unexpected keyword argument 'mask'
```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by LucasG0**
### What changes are included in this PR?

Add `mask` / `null_bitmap` parameters in corresponding Cython / C++ `FixedSizeListArray` methods, and propagate this bitmap instead of using the current dummy `validity_buf`.

### Are these changes tested?

Yes

### Are there any user-facing changes?

Yes, `mask` parameter has been added to `FixedSizeListArray.from_arrays`
* Closes: #34316

### CODE REVIEW

File: cpp/src/arrow/array/array_nested.h [hunk 1]
```diff
@@ -599,17 +599,23 @@ class ARROW_EXPORT FixedSizeListArray : public Array {
...
   /// \param[in] values Array containing list values
   /// \param[in] list_size The fixed length of each list
+  /// \param[in] null_bitmap Optional validity bitmap
   /// \return Will have length equal to values.length() / list_size
-  static Result<std::shared_ptr<Array>> FromArrays(const std::shared_ptr<Array>& values,
-                                                   int32_t list_size);
+  static Result<std::shared_ptr<Array>> FromArrays(
+      const std::shared_ptr<Array>& values,
+      int32_t list_size,
+      std::shared_ptr<Buffer> null_bitmap = NULLPTR);
```
Comment (wjones127) [inline cpp/src/arrow/array/array_nested.h:607]: Other methods that allow passing a null bitmap (such as `ListArray::FromArrays()`) support another parameter `null_count` to pass the computed null count. Could we support that parameter in C++ as well? We don't need to expose it in Python.

https://github.com/apache/arrow/blob/6b11b42fcc6cd1feb7afc03badbb0deca38dfeef/cpp/src/arrow/array/array_nested.h#L174-L178

**Review by wjones127 — CHANGES_REQUESTED** [review]
Needs one small tweak to be in line with other implementations, but otherwise looks good. Thanks for working on this :)

**Review by wjones127 — APPROVED** [review]
