### PR TITLE
GH-40068:  [C++] Possible data race when reading metadata of a parquet file

### LINKED ISSUE #40068: [C++] Possible data race when reading metadata of a parquet file
### Describe the bug, including details regarding any error messages, version, and platform.

The first and the last line of this block of code access the same ```metadata``` variable but only one of them does so holding a lock.
I assume this means the other one should too.
There are some other places in this file that access metadata in tricky ways (e.g. it is not clear from a first glance at a method whether nullptr is allowed or not). They could also race.
https://github.com/apache/arrow/blob/0dbbd43ca9133912d1809394727784560cc5e797/cpp/src/arrow/dataset/file_parquet.cc#L607-L618

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by westonpace**
### Rationale for this change

The `ParquetFileFragment` will cache the parquet metadata when loading it.  The `metadata()` method accesses this metadata (a shared_ptr) but does not grab the lock used to set that shared_ptr.  It's possible then that we are reading a shared_ptr at the same time some other thread is setting the shared_ptr which is technically (I think) undefined behavior.

### What changes are included in this PR?

Guard access to the metadata by grabbing the mutex first

### Are these changes tested?

Existing tests should regress this change

### Are there any user-facing changes?

No
* Closes: #40068

### CODE REVIEW

File: cpp/src/arrow/dataset/file_parquet.cc [hunk 1]
```diff
@@ -779,6 +779,11 @@ ParquetFileFragment::ParquetFileFragment(FileSource source,
       parquet_format_(checked_cast<ParquetFileFormat&>(*format_)),
       row_groups_(std::move(row_groups)) {}
 
+const std::shared_ptr<parquet::FileMetaData>& ParquetFileFragment::metadata() {
+  auto lock = physical_schema_mutex_.Lock();
+  return metadata_;
```
Comment (pitrou) [inline cpp/src/arrow/dataset/file_parquet.cc:784]: This is returning a reference to an internal member, but the dereferencing won't be protected by the lock.
Should we switch to return a `std::shared_ptr` instead?

Comment (westonpace) [reply cpp/src/arrow/dataset/file_parquet.cc:784]: Yikes, yes, you are right.  I've updated this to return by value instead of by reference.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@raulcd This would be good for 15.0.1, if not too late.
