### PR TITLE
GH-40085: [C++][FS][Azure] Validate containers in AzureFileSystem::Impl::MovePaths()

### LINKED ISSUE #40085: [C++][FS][Azure] AzureFileSystem::Move() broken when paths are from separate containers
### Describe the bug, including details regarding any error messages, version, and platform.

The current implementation doesn't check paths are from the same filesystem before proceeding with the rename.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

Cross container moves aren't supported yet (and might never be).

### What changes are included in this PR?

 - Check that containers are the same before calling a `Rename` that assumes `src` and `dest` are on the same container

### Are these changes tested?

Yes, new tests were added.
* Closes: #40085

### CODE REVIEW

**Comment by felipecrv** [comment]
@Tom-Newton

File: cpp/src/arrow/filesystem/azurefs_test.cc [hunk 1]
```diff
@@ -1234,30 +1234,32 @@ class TestAzureFileSystem : public ::testing::Test {
...
-        IOError, HasMissingParentDirMessage("missing-container/path"),
+        NotImplemented,
+        HasCrossContainerNotImplementedMessage(data.ObjectPath(),
+                                               "missing-container/path"),
         fs()->Move(data.ObjectPath(), "missing-container/path"));
+    EXPECT_RAISES_WITH_MESSAGE_THAT(
+        NotImplemented,
+        HasCrossContainerNotImplementedMessage(data.ObjectPath(),
+                                               another_container + "/path"),
+        fs()->Move(data.ObjectPath(), another_container + "/path"));
```
Comment (kou) [inline cpp/src/arrow/filesystem/azurefs_test.cc:1256]: Could you use `ConcatAbstractPath()`?

```suggestion
                                               ConcatAbstractPath(another_container, "path")),
        fs()->Move(data.ObjectPath(), ConcatAbstractPath(another_container, "path")));
```

**Review by kou — APPROVED** [review]
+1
