### PR TITLE
GH-40089: [Go] Concurrent Recordset for receiving huge recordset

### LINKED ISSUE #40089: [Go] Can't handle huge recordset with synchronous approach
### Describe the bug, including details regarding any error messages, version, and platform.

We work with large volumes of data, and we have observed that the results of queries (db.Query()) are downloaded at once into an array in memory, which in these cases always results in containers being OOM-Killed.

We have developed a patch, where we introduced an asynchronous/concurrent approach, using goroutines, which reads only the necessary blocks, as calls to Rows.Next() are made.

All the relevant routines are in file https://github.com/apache/arrow/blob/main/go/arrow/flight/flightsql/driver/driver.go.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by miguelpragier**
### Rationale for this change

Enabling Support for Large Recordsets in Go FlightSQL Driver
Replacing **download-all-at-once->read-later** with **download-chunk-as-reading** approach.

The primary motivation for these changes is to enhance the driver's capability to handle large recordsets without the need for unnecessary memory pre-allocations. By implementing a concurrent streaming approach, the driver avoids loading the entire dataset into memory at once.

### Description:
Implementing Concurrent Record Streaming to Better Support the Handling of Large Recordsets.

For retrieving a recordset, the current implementation works as follows:
- An SQL query results in a set of [endpoints] and a query ticket.
- Each [endpoint] is requested (with the generated ticket), and its response is a [reader].
- Each reader is iterated for records. These records are, in fact, arrays of rows.
- All the retrieved rows are stored at once in an array.
- This means that data, potentially comprising billions of rows, is synchronously read into an array.
- After this array is filled, it is then returned, all at once, to the consumer.
- This can result in out-of-memory failures, or at the very least, unnecessary waiting times and huge pre-allocations.

### Proposed Changes:
Iterate over [endpoints], [readers], and [records] ad hoc, reading only the necessary data according to consumer demand.

### What changes are included in this PR?

**1. Introduction of `sync.Mutex`:**
   - The `Rows` struct has been updated to include a `currentRecordMux` mutex. This addition ensures that operations involving the release of the current record are thread-safe, thus preventing potential race conditions in a concurrent environment.

**2. Channels for Asynchronous Record Fetching:**
   - A new buffered channel, `recordChan`, has been added to the `Rows` struct. This channel permits the driver to asynchronously fetch and queue records. It provides a non-blocking mechanism to manage incoming records, which is particularly advantageous when dealing with large recordsets.

**3. Asynchronous Record Streaming via Goroutines:**
   - The `streamRecordset` function has been introduced and is designed to run concurrently using goroutines. This modification permits the driver to begin processing records as soon as they are received, without having to wait for the entire recordset to be loaded into memory.

**4. Improved Record Management:**
   - A new method, `releaseRecord`, has been created to manage the lifecycle of the current record. This method ensures that resources are released when a record is no longer needed, thus reducing the memory footprint when processing large datasets.

**5. Refactoring of the `Next` Method:**
   - The `Next` method in the `Rows` struct has been refactored to suit the new streaming model. It now efficiently waits for and retrieves the next available record from the `recordChan` channel, enabling a smooth and memory-efficient iteration over large datasets.

### Are These Changes Tested?
The proposed changes have been validated against existing tests.

### Are There Any User-Facing Changes?
No, there are no user-facing changes.

* Closes: #40089

### CODE REVIEW

File: go/arrow/flight/flightsql/driver/driver.go [hunk 1]
```diff
@@ -37,34 +38,50 @@ import (
...
 
 type Rows struct {
-	schema        *arrow.Schema
-	records       []arrow.Record
-	currentRecord int
-	currentRow    int
+	schema           *arrow.Schema
+	recordChan       chan arrow.Record
+	currentRecord    arrow.Record
+	currentRecordMux sync.Mutex
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:44]: do we actually need this mutex? I thought that the `Rows` object isn't used by multiple goroutines concurrently?

File: go/arrow/flight/flightsql/driver/driver.go [hunk 2]
```diff
@@ -37,34 +38,50 @@ import (
...
+	currentRow       uint64
+	initializedChan  chan bool
+	streamError      error
+}
+
+func newRows() *Rows {
+	return &Rows{
+		recordChan:      make(chan arrow.Record, 1),
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:52]: This buffer size should probably be configurable, depending on the server in use and how the consumer is operating, getting better performance and backpressure may require manipulating the size of the buffer.

File: go/arrow/flight/flightsql/driver/driver.go [hunk 3]
```diff
@@ -37,34 +38,50 @@ import (
...
+}
+
 // Close closes the rows iterator.
 func (r *Rows) Close() error {
-	for _, rec := range r.records {
-		rec.Release()
-	}
-	r.currentRecord = 0
-	r.currentRow = 0
+	r.releaseRecord()
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:84]: shouldn't we still need `r.currentRow = 0` ?

File: go/arrow/flight/flightsql/driver/driver.go [hunk 4]
```diff
@@ -37,34 +38,50 @@ import (
...
+	defer r.currentRecordMux.Unlock()
+
+	if r.currentRecord != nil {
+		r.currentRecord.Release()
+		r.currentRecord = nil
+	}
+}
+
 // Close closes the rows iterator.
 func (r *Rows) Close() error {
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:83]: what happens if `Close` is called before all the records have been retrieved? How do we cancel the record reader?

File: go/arrow/flight/flightsql/driver/driver.go [hunk 5]
```diff
@@ -79,28 +96,37 @@ func (r *Rows) Close() error {
...
 // a buffer held in dest.
 func (r *Rows) Next(dest []driver.Value) error {
-	if r.currentRecord >= len(r.records) {
-		return io.EOF
-	}
-	record := r.records[r.currentRecord]
+	if r.currentRecord == nil || int64(r.currentRow) >= r.currentRecord.NumRows() {
+		if r.streamError != nil {
+			return r.streamError
+		}
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:102]: if we are going to have a mutex, it needs to be locked before these usages of `r.currentRecord`. But I still don't think we need a mutex for this. We can just pull the next record from the channel as we finish the current record. There wouldn't be any concurrent accessing of `r.currentRecord`

File: go/arrow/flight/flightsql/driver/driver.go [hunk 6]
```diff
@@ -79,28 +96,37 @@ func (r *Rows) Close() error {
...
+
+		r.releaseRecord()
 
-	if int64(r.currentRow) >= record.NumRows() {
-		return ErrOutOfRange
+		// Get the next record from the channel
+		var ok bool
+		if r.currentRecord, ok = <-r.recordChan; !ok {
+			return io.EOF // Channel closed, no more records
+		}
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:110]: Same thing here, if we are going to have a mutex, it needs to be locked before this

File: go/arrow/flight/flightsql/driver/driver.go [hunk 7]
```diff
@@ -79,28 +96,37 @@ func (r *Rows) Close() error {
...
-	for i, arr := range record.Columns() {
-		v, err := fromArrowType(arr, r.currentRow)
+	for i, col := range r.currentRecord.Columns() {
+		v, err := fromArrowType(col, int(r.currentRow))
 		if err != nil {
 			return err
 		}
+
 		dest[i] = v
 	}
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:127]: again, same. either drop the mutex or it needs to be locked before this

File: go/arrow/flight/flightsql/driver/driver.go [hunk 8]
```diff
@@ -461,43 +480,63 @@ func (c *Connection) QueryContext(ctx context.Context, query string, args []driv
...
-		if err != nil {
-			return &rows, err
-		}
-		if rows.schema == nil {
-			rows.schema = schema
-		}
-		rows.records = append(rows.records, records...)
-	}
+	rows := newRows()
+	go rows.streamRecordset(ctx, c.client, info.Endpoint)
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:484]: should probably use `context.WithCancel` on this and store the cancel function so that `Rows` can call it on `Close` in and tell the streaming it can end early.

File: go/arrow/flight/flightsql/driver/driver.go [hunk 9]
```diff
@@ -461,43 +480,63 @@ func (c *Connection) QueryContext(ctx context.Context, query string, args []driv
...
+				}
 
-	return schema, records, nil
+				select {
+				case r.recordChan <- record:
+					go initializeOnceOnly.Do(func() { r.initializedChan <- true })
+
+				case <-ctx.Done():
+					r.releaseRecord()
+					r.streamError = fmt.Errorf("stream recordset context timed out")
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:529]: Should use `ctx.Err()` instead, it could be cancelled or any other situation, not necessarily timed out.

**Review by zeroshade — CHANGES_REQUESTED** [review]
So, a quick question above and beyond this review: Have you looked into using ADBC's FlightSQL driver instead of this? For reference, this asynchronous pulling of records instead of pulling them all into memory is already implemented there using the Go Arrow FlightSQL implementation and you can use https://pkg.go.dev/github.com/apache/arrow-adbc/go/adbc@v0.9.0/sqldriver if you need the `database/sql` interface rather than just working with Arrow directly.

If you haven't tried it yet, could you try it out and see if it solves your issues?

File: go/arrow/flight/flightsql/driver/driver.go (hunk 9 above)
Comment (mgross-ebner) [reply go/arrow/flight/flightsql/driver/driver.go:529]: @zeroshade 

Yes, we conducted an evaluation of the ADBC driver but ultimately chose to forgo it in favor of adapting the Arrow driver. Initially, we encountered issues integrating the driver with our Dremio deployment. We have yet to ascertain whether the problem lies with our deployment, with Dremio, or with the driver itself. A more significant consideration is our understanding that the ADBC driver utilizes Arrow data types. Our application is extensive and includes numerous structs, which would necessitate considerable refactoring.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 1 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go]: mutex removed.
wasn't really consistent.
I think the new organization is leaner & safer.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 2 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go]: thanks, @zeroshade .
I removed the magic number, but kept the buffer size=one.
Do you have suggestions for implementing a dynamic/configurable buffer size?
That could, anyway, happen on a new PR. WDYT?

File: go/arrow/flight/flightsql/driver/driver.go (hunk 3 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go:94]: Deal!

File: go/arrow/flight/flightsql/driver/driver.go (hunk 4 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go:89]: with these adjustments, Close() now properly cancel() the streaming.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 5 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go:112]: deal. mutex removed.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 6 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go:120]: deal. mutex removed.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 7 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go:137]: deal. mutex removed.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 8 above)
Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go]: this is the idea that helped me to better resolve the synchronization.
that's why I dropped the mutex, fearing no deadlocks.
thanks, it improves a lot the PR.

**Comment by miguelpragier** [comment]
thanks for reviewing, @zeroshade .
We gave it a second thought before deciding to refactor these routines, and the code edits are simple but not trivial.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 9 above)
Comment (zeroshade) [reply go/arrow/flight/flightsql/driver/driver.go]: @mgross-ebner We maintain usage of Dremio for the CI testing with the ADBC driver to ensure compatibility. So it would definitely be good for us to determine whether the issue is in the Driver or not.

>  A more significant consideration is our understanding that the ADBC driver utilizes Arrow data types. Our application is extensive and includes numerous structs, which would necessitate considerable refactoring.

There is an adapter in the arrow-adbc library that wraps the ADBC driver for the go `database/sql` interface which should allow you to drop in replace the usage without any changes. See the example here: https://pkg.go.dev/github.com/apache/arrow-adbc/go/adbc@v0.9.0/sqldriver/flightsql#example-package

That should avoid the need for refactoring, right?

File: go/arrow/flight/flightsql/driver/driver.go (hunk 2 above)
Comment (zeroshade) [reply go/arrow/flight/flightsql/driver/driver.go]: I'd be fine with making it configurable in a follow-up PR. sure. 

As for a suggestion for implementing the configuable buffer size, there are two common patterns:

* In the `Open` and `Connector` handling the uri, you can use a delimiter and allow passing various options in similar to how an ODBC DSN works. During `Open`  you can then parse out the options and store them in the driver instance, then have this function take in the buffer size as a parameter which can be passed in.
* You could provide context functions like `WithBufferSize` and then pull the value out of the context at query time when you construct the Rows object, defaulting to 1 if the user didn't stick it into the context.

File: go/arrow/flight/flightsql/driver/driver.go (hunk 9 above)
Comment (mgross-ebner) [reply go/arrow/flight/flightsql/driver/driver.go]: @zeroshade During my tests, columns of the decimal type were `arrow.Decimal` instead of a float64. I used the drop in replacement to setup the connection to flightsql Dremio via `database/sql`.

I will open an issue regarding the problems between Dremio and adbc in the adbc project. If I recall correctly, the problem was that the endpoint uri, which is used in the cache lru, was trying to fetch data from `0.0.0.0:32010` and not the url behind the ingress.

Comment (zeroshade) [reply go/arrow/flight/flightsql/driver/driver.go]: >  columns of the decimal type were arrow.Decimal instead of a float64.

On the one-hand, `decimal128.Num` does have a `ToFloat` function, but this is a good point. We should probably add a configuration to have it auto convert decimals to float64 for you.

> If I recall correctly, the problem was that the endpoint uri, which is used in the cache lru, was trying to fetch data from 0.0.0.0:32010 and not the url behind the ingress.

Interesting In theory it should be properly following the URIs provided in the endpoints or use the same connection of the client. I'll keep an eye out for the issue getting filed so I can take a look into it.

Comment (miguelpragier) [reply go/arrow/flight/flightsql/driver/driver.go]: > Should use `ctx.Err()` instead, it could be cancelled or any other situation, not necessarily timed out.

✔️  Replaced.

**Comment by zeroshade** [comment]
@miguelpragier looks like there's some sort of bad nil dereference happening in the tests that needs to be addressed before we can merge this.

**Comment by zeroshade** [comment]
@miguelpragier The only thing missing here is some tests, otherwise this looks good to me. We should make sure the cancel func is being tested

**Review by zeroshade — APPROVED** [review]
