### PR TITLE
GH-39289: [JS] Add types to exports

### LINKED ISSUE #39289: [JS] TypeScript types don't work with Node ESM
### Describe the bug, including details regarding any error messages, version, and platform.

The `apache-arrow` package has an `exports` field that points to an ESM build for Node.js imports, which works at runtime, but I get an error from TypeScript saying that it can't find the types for ESM projects:

image

https://stackblitz.com/edit/stackblitz-starters-7u3tyj?file=src%2Findex.ts

If I modify the `exports` field to this:

```
  "exports": {
    ".": {
      "node": {
        "types": "./Arrow.node.d.ts",
        "import": "./Arrow.node.mjs",
        "require": "./Arrow.node.js"
      },
      "types": "./Arrow.dom.d.ts",
      "import": "./Arrow.dom.mjs",
      "require": "./Arrow.dom.js"
    },
    "./*": {
      "import": "./*.mjs",
      "require": "./*.js"
    }
  }
```

then TypeScript is able to find the types correctly. I can also work around it by depending on `@apache-arrow/esnext-esm` directly.

### Component(s)

JavaScript

### PR DESCRIPTION
**Pull request by domoritz**
* Closes: #39289

### CODE REVIEW

**Review by trxcllnt — APPROVED** [review]

File: js/gulp/package-task.js [hunk 1]
```diff
@@ -54,18 +57,17 @@ const createMainPackageJson = (target, format) => (orig) => ({
             node: {
                 import: `./${mainExport}.node.mjs`,
                 require: `./${mainExport}.node.js`,
+                types: `./${mainExport}.node.d.ts`,
```
Comment (andrew0) [inline js/gulp/package-task.js:60]: The TypeScript docs say that the `types` property should come first: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing. Not 100% sure the reasoning since the docs don't really explain it but I think it can mess with the resolution priorities somehow.

**Comment by andrew0** [comment]
I ran `yarn build && npx @arethetypeswrong/cli --pack targets/apache-arrow`, and it gives these errors:

image

after changing the `types` to come first:

image

The [masquerading as CJS](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md) error will make it so in ESM mode, which I believe makes it so TypeScript will let you do `import arrow from 'apache-arrow'`, which would be a runtime error since there's no default export, so it really should be `import * as arrow from 'apache-arrow'`.

**Comment by andrew0** [comment]
I believe that this should fix the types for all the import scenarios: https://github.com/andrew0/arrow/commit/207881a857ada94a86c4a371da2cf89d5c6335e4

image

**Comment by domoritz** [comment]
Thanks! I made the updates.

**Review by trxcllnt — APPROVED** [review]

File: js/gulp/package-task.js (hunk 1 above)
Comment (domoritz) [reply js/gulp/package-task.js]: Weird that the order in an object matters but ok, changed.

**Comment by domoritz** [comment]
This will be in arrow 15 shortly
