### PR TITLE
GH-39525: [C++][Parquet] Pass memory pool to decoders

### LINKED ISSUE #39525: [C++][Parquet] Not all decoders are passed a memory pool from column reader
### Describe the bug, including details regarding any error messages, version, and platform.

This can prevent proper memory attribution/etc from occurring.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by emkornfield**
### Rationale for this change

Memory pools should be plumbed through where ever possible.

### What changes are included in this PR?

Pass through memory pool to decoders

### Are these changes tested?

Not directly; this was caught via some internal fuzz targets.

### Are there any user-facing changes?

No.

* Closes: #39525

### CODE REVIEW

**Review by wgtmac — APPROVED** [review]

**Review by mapleFU — APPROVED** [review]

**Comment by mapleFU** [comment]
cc @pitrou

File: cpp/src/parquet/column_reader.cc [hunk 1]
```diff
@@ -884,19 +884,20 @@ class ColumnReaderImplBase {
     } else {
       switch (encoding) {
         case Encoding::PLAIN: {
```
Comment (pitrou) [inline cpp/src/parquet/column_reader.cc:886]: Can we simplify these different `case` statements? Unless I'm missing something, they're executing the same code. So this could be:
```cpp
      switch (encoding) {
        case Encoding::PLAIN:
        case Encoding::BYTE_STREAM_SPLIT:
        case Encoding::RLE:
        case Encoding::DELTA_BINARY_PACKED: 
        case Encoding::DELTA_BYTE_ARRAY:
        case Encoding::DELTA_LENGTH_BYTE_ARRAY:
          auto decoder = MakeTypedDecoder<DType>(encoding, descr_, pool_);
          current_decoder_ = decoder.get();
          decoders_[static_cast<int>(encoding)] = std::move(decoder);
          break;

        case Encoding::RLE_DICTIONARY:
          throw ParquetException("Dictionary page must be before data page.");

        default:
          throw ParquetException("Unknown encoding type.");
      }
```

Comment (emkornfield) [reply cpp/src/parquet/column_reader.cc]: I agree changed.

**Review by pitrou — APPROVED** [review]

**Review by wgtmac — APPROVED** [review]

**Review by mapleFU — APPROVED** [review]
