### PR TITLE
GH-35942: [C++] Improve Decimal ToReal accuracy

### LINKED ISSUE #35942: [C++] Decimal-to-real accuracy loss / rounding issue
### Describe the bug, including details regarding any error messages, version, and platform.

It seems the expected result from converting a decimal to real may be off by one ULP:
```pycon
>>> a = pa.array(['999999999999999.9']).cast(pa.decimal128(17,1))
>>> a
<pyarrow.lib.Decimal128Array object at 0x7f8ec6f3f6a0>
[
  999999999999999.9
]
>>> a.cast(pa.float64())
<pyarrow.lib.DoubleArray object at 0x7f8fa4a88ee0>
[
  1e+15
]

>>> expected = 999999999999999.9
>>> actual = a.cast(pa.float64())[0].as_py()
>>> abs(expected-actual)/expected
1.25e-16
>>> abs(expected-actual) == expected - math.nextafter(expected, 0)
True  # Exactly one ULP
```

This is much less severe than #35576

### Component(s)

C++

### PR DESCRIPTION
**Pull request by js8544**
### Rationale for this change

The current implementation of `Decimal::ToReal` can be naively represented as the following pseudocode:
```
Real v = static_cast<Real>(decimal.as_int128/256())
return v * (10.0**-scale)
```
It stores the intermediate unscaled int128/256 value as a float/double. The unscaled int128/256 value can be very large when the decimal has a large scale, which causes precision issues such as in #36602.

### What changes are included in this PR?

Avoid storing the unscaled large int as float if the representation is not precise, by spliting the decimal into integral and fractional parts and dealing with them separately. This algorithm guarantees that:
1. If the decimal is an integer, the conversion is exact.
2. If the number of fractional digits is <= RealTraits<Real>::kMantissaDigits (e.g. 8 for float and 16 for double), the conversion is within 1 ULP of the exact value. For example Decimal128::ToReal<float>(9999.999) falls into this category because the integer 9999999 is precisely representable by float, whereas 9999.9999 would be in the next category.
3. Otherwise, the conversion is within 2^(-RealTraits<Real>::kMantissaDigits+1) (e.g. 2^-23 for float and 2^-52 for double) of the exact value.

Here "exact value" means the closest representable value by Real.

I believe this algorithm is good enough, because an"exact" algorithm would require iterative multiplication and subtraction of decimals to determain the binary representation of its fractional part. Yet the result would still almost always be inaccurate because float/double can only accurately represent powers of two. IMHO It's not worth it to spend that many expensive operations just to improve the result by one ULP.

### Are these changes tested?

Yes.

### Are there any user-facing changes?
 No.

* Closes: #35942

### CODE REVIEW

**Comment by js8544** [comment]
@pitrou Would you mind having a look at this PR? Thanks!

File: cpp/src/arrow/util/decimal.cc [hunk 1]
```diff
@@ -305,12 +305,39 @@ struct Decimal128RealConversion
...
-  static Real ToRealPositive(const Decimal128& decimal, int32_t scale) {
+  static Real ToRealPositiveNoSplit(const Decimal128& decimal, int32_t scale) {
     Real x = RealTraits<Real>::two_to_64(static_cast<Real>(decimal.high_bits()));
     x += static_cast<Real>(decimal.low_bits());
     x *= LargePowerOfTen<Real>(-scale);
     return x;
   }
+
+  /// An appoximate conversion from Decimal128 to Real that guarantees:
+  /// 1. If the decimal is an integer, the conversion is exact.
```
Comment (pitrou) [inline cpp/src/arrow/util/decimal.cc:316]: Even if the integer has more than 52 significant bits??

File: cpp/src/arrow/util/decimal.cc [hunk 2]
```diff
@@ -978,6 +1005,33 @@ struct Decimal256RealConversion
...
+  /// 2. If the number of fractional digits is <= RealTraits<Real>::kMantissaDigits (e.g.
+  ///    8 for float and 16 for double), the conversion is within 1 ULP of the exact
+  ///    value.
+  /// 3. Otherwise, the conversion is within 2^(-RealTraits<Real>::kMantissaDigits+1)
+  ///    (e.g. 2^-23 for float and 2^-52 for double) of the exact value.
+  /// Here "exact value" means the closest representable value by Real.
+  template <typename Real>
+  static Real ToRealPositive(const Decimal256& decimal, int32_t scale) {
+    const auto parts_le = bit_util::little_endian::Make(decimal.native_endian_array());
```
Comment (pitrou) [inline cpp/src/arrow/util/decimal.cc:1019]:
```suggestion
    const auto parts_le = decimal.little_endian_array();
```

File: cpp/src/arrow/util/decimal_internal.h [hunk 3]
```diff
@@ -451,6 +451,8 @@ struct RealTraits<float> {
   static constexpr int kMantissaBits = 24;
   // ceil(log10(2 ^ kMantissaBits))
   static constexpr int kMantissaDigits = 8;
+  // Integers between zero and kMaxPreciseInteger can be precisely represented
+  static constexpr uint64_t kMaxPreciseInteger = 1ULL << kMantissaBits;
```
Comment (pitrou) [inline cpp/src/arrow/util/decimal_internal.h:455]: Need to subtract one, no?
```suggestion
  static constexpr uint64_t kMaxPreciseInteger = (1ULL << kMantissaBits) - 1;
```

File: cpp/src/arrow/util/decimal_test.cc [hunk 4]
```diff
@@ -1119,6 +1137,35 @@ class TestDecimalToReal : public ::testing::Test {
     // 2**64 + 2**41 (exactly representable in a float)
     CheckDecimalToReal<Decimal, Real>("18446746272732807168", 0, 1.8446746e+19f);
     CheckDecimalToReal<Decimal, Real>("-18446746272732807168", 0, -1.8446746e+19f);
+
+    // Integers are always exact
+    auto scale = Decimal::kMaxScale - 1;
+    std::string seven = "7.";
+    for (int32_t i = 0; i < scale; ++i) {
+      seven += "0";
+    }
```
Comment (pitrou) [inline cpp/src/arrow/util/decimal_test.cc:1146]: Can probably write this more tersely:
```suggestion
    seven.append(scale, '0');  // pad with trailing zeros
```

File: cpp/src/arrow/util/decimal_test.cc [hunk 5]
```diff
@@ -1119,6 +1137,35 @@ class TestDecimalToReal : public ::testing::Test {
...
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("9999999.9", 1, 9999999.9f);
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("-9999999.9", 1, -9999999.9f);
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("9999999.999999", 6, 9999999.999999f);
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("-9999999.999999", 6, -9999999.999999f);
+
+    // Large fractions are within 2^-23
+    constexpr Real epsilon = 1.1920928955078125e-07f;  // 2^-23
+    CheckDecimalToRealWithinEpsilon<Decimal, Real>(
+        "112334829348925.99070703983306884765625", 23, epsilon,
+        112334829348925.99070703983306884765625f);
```
Comment (pitrou) [inline cpp/src/arrow/util/decimal_test.cc:1165]: Passing this as a `float` constant is weird. If you want to differentiate these tests between `float` and `double`, you may use `if constexpr`.

File: cpp/src/arrow/util/decimal_test.cc [hunk 6]
```diff
@@ -1119,6 +1137,35 @@ class TestDecimalToReal : public ::testing::Test {
...
+                                      -99999999999999999999.0f);
+
+    // Small fractions are within one ULP
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("9999999.9", 1, 9999999.9f);
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("-9999999.9", 1, -9999999.9f);
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("9999999.999999", 6, 9999999.999999f);
+    CheckDecimalToRealWithinOneULP<Decimal, Real>("-9999999.999999", 6, -9999999.999999f);
+
+    // Large fractions are within 2^-23
+    constexpr Real epsilon = 1.1920928955078125e-07f;  // 2^-23
```
Comment (pitrou) [inline cpp/src/arrow/util/decimal_test.cc:1162]: Shouldn't you use a better epsilon for `double`?

**Review by pitrou — CHANGES_REQUESTED** [review]
Thanks @js8544 ! This is a nice improvement.

File: cpp/src/arrow/util/decimal.cc (hunk 1 above)
Comment (js8544) [reply cpp/src/arrow/util/decimal.cc:316]: See below 
> Here "exact value" means the closest representable value by Real.

File: cpp/src/arrow/util/decimal_test.cc (hunk 5 above)
Comment (js8544) [reply cpp/src/arrow/util/decimal_test.cc:1163]: The weird thing is even though it is parametrized over `Real`, these tests were only run for `float`. I kept it this way. Perhaps it's better to remove the Real parameter and make it clear that it's only for float?

File: cpp/src/arrow/util/decimal_test.cc (hunk 6 above)
Comment (js8544) [reply cpp/src/arrow/util/decimal_test.cc:1160]: same as above

File: cpp/src/arrow/util/decimal_test.cc (hunk 5 above)
Comment (pitrou) [reply cpp/src/arrow/util/decimal_test.cc:1163]: Either that, or try to re-enable running them for `double`. Are the tests redundant with other `double` tests?

File: cpp/src/arrow/util/decimal.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/util/decimal.cc:316]: Hmm, ok :-)

File: cpp/src/arrow/util/decimal_test.cc (hunk 5 above)
Comment (js8544) [reply cpp/src/arrow/util/decimal_test.cc:1166]: Yes, `double` is tested in TestDecimalToRealDouble::Precision. I added a static_assert at the beginning to make it clearer.

Comment (pitrou) [reply cpp/src/arrow/util/decimal_test.cc:1166]: If the test parameterization is fake, then let's just remove it?

Comment (js8544) [reply cpp/src/arrow/util/decimal_test.cc]: Sure. I've refactored this test as TestDecimalToRealFloat.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
CI failures are unrelated.
