### PR TITLE
GH-37841: [Java] Dictionary decoding not using the compression factory from the ArrowReader

### LINKED ISSUE #37841: [Java] Dictionary decoding not using the compression factory from the ArrowReader
I am trying to decode  in Java records generated in Go (simple type + dictionaries) using ZSTD compression (using Arrow 13.0.0)

Although this is working fine for the simple types, I am getting this error when decoding dictionaries

```
java.lang.IllegalArgumentException: Please add arrow-compression module to use CommonsCompressionFactory for ZSTD
	at org.apache.arrow.vector.compression.NoCompressionCodec$Factory.createCodec(NoCompressionCodec.java:69)
	at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:82)
	at org.apache.arrow.vector.ipc.ArrowReader.load(ArrowReader.java:256)
	at org.apache.arrow.vector.ipc.ArrowReader.loadDictionary(ArrowReader.java:247)
	at org.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:167)
```

The Go part is essentially

```go
dtyp := &arrow.DictionaryType{
	IndexType: arrow.PrimitiveTypes.Int8,
	ValueType: arrow.BinaryTypes.LargeString,
}
bldrDictString := arrowarray.NewDictionaryBuilder(memory.DefaultAllocator, dtyp)
defer bldrDictString.Release()

bldrDictString.(*arrowarray.BinaryDictionaryBuilder).AppendString("foo")

columnTypes := make([]arrow.Field, 0, 1)
columnArrays := make([]arrow.Array, 0, 1)

columnArrays = append(columnArrays, bldrDictString.NewArray())
columnTypes = append(columnTypes, arrow.Field{Name: k.key, Type: dtyp, Nullable: nulls.Any()})

schema := arrow.NewSchema(columnTypes, nil)
rec := arrowarray.NewRecord(schema, columnArrays, int64(size))

var buf bytes.Buffer
writer := ipc.NewWriter(&buf, ipc.WithSchema(schema), ipc.WithZstd())
err := writer.Write(rec)
err = writer.Close()
```

And the Java side

```java
import org.apache.arrow.compression.CommonsCompressionFactory;


try (ArrowStreamReader reader =
         new ArrowStreamReader(
             new ByteArrayInputStream(format.getArrow().toByteArray()),
             bufferAllocator,
             CommonsCompressionFactory.INSTANCE)) {
  reader.loadNextBatch();
  ...
} catch (IOException e) {
  throw new RuntimeException(e);
}
```

I am able to get it to not throw by making the VectorLoader used when loading the dictionary use the compression factory defined in the reader (it is currently defaulting to NoCompression) 

see this [change](https://github.com/freakyzoidberg/arrow/commit/f945d2ddee9c332661d3d97084c2aedb56f7fcf5), note I was not able to make it fail using the java arrow test.

I am probably doing something wrong, and also wondering if dictionaries are compressed the same in go and java writers which could explain why the java test is not failing ?

Anyhow, unless I am doing something wrong, this looks like a bug.

Thanks !

### Component(s)

Java

### PR DESCRIPTION
**Pull request by vibhatha**
### Rationale for this change

This PR addresses https://github.com/apache/arrow/issues/37841. 

### What changes are included in this PR?

Adding compression-based write and read for Dictionary data. 

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No
* Closes: apache/arrow#37841
* GitHub Issue: #37841

### CODE REVIEW

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java [hunk 1]
```diff
@@ -79,11 +119,130 @@ public void testArrowFileZstdRoundTrip() throws Exception {
...
+    }
+  }
+
+  @Test
+  public void testArrowFileZstdRoundTripWithDictionary() throws Exception {
+    // Prepare sample data
+    DictionaryProvider.MapDictionaryProvider provider = new DictionaryProvider.MapDictionaryProvider();
+    provider.put(dictionary1);
+
+    final BufferAllocator allocator = new RootAllocator(Integer.MAX_VALUE);
```
Comment (danepitkin) [inline java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:134]: I think you can get rid of these in favor of this.allocator if you keep the `@Before/@After` functions

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java [hunk 2]
```diff
@@ -79,11 +119,130 @@ public void testArrowFileZstdRoundTrip() throws Exception {
...
              allocator, NoCompressionCodec.Factory.INSTANCE)) {
       Assert.assertEquals(1, reader.getRecordBlocks().size());
+      Exception exception = Assert.assertThrows(IllegalArgumentException.class, () -> reader.loadNextBatch());
+      String expectedMessage = "Please add arrow-compression module to use CommonsCompressionFactory for ZSTD";
+      Assert.assertEquals(expectedMessage, exception.getMessage());
+    }
+  }
+
+  @Test
+  public void testArrowFileZstdRoundTripWithDictionary() throws Exception {
```
Comment (danepitkin) [inline java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:129]: Do you think we still need the original test function `testArrowFileZstdRoundTrip`? Is this new test case possibly testing the same code path + dictionaries?

**Review by danepitkin — COMMENTED** [review]
Great work, @vibhatha !

**Comment by vibhatha** [comment]
@danepitkin Thanks a lot for the review comments, I will address them.

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java [hunk 3]
```diff
@@ -18,31 +18,71 @@
...
 import org.junit.Assert;
+import org.junit.Before;
 import org.junit.Test;
 
 public class TestArrowReaderWriterWithCompression {
+  private BufferAllocator allocator;
+  private VarCharVector dictionaryVector1;
+  private Dictionary dictionary1;
 
+  @Before
```
[the remark this answers is not in the document]
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:64]: Good point. I will update.

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 2 above)
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:129]: It is the same path + dictionaries, I refactored and reorganized the test cases, does it make sense or useful? I think my previous code had duplication.

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 1 above)
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java]: Yes, I agree. I refactored the code to use this approach.

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java [hunk 4]
```diff
@@ -66,6 +66,12 @@ public abstract class ArrowWriter implements AutoCloseable {
 
   protected IpcOption option;
 
+  private CompressionCodec.Factory compressionFactory;
+
+  private CompressionUtil.CodecType codecType;
+
+  private Optional<Integer> compressionLevel;
+
```
[the remark this answers is not in the document]
Comment (vibhatha) [reply java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java:74]: +1, way neater that way.

**Review by danepitkin — COMMENTED** [review]
Great work! The tests look very clean now. left a few small additional comments.

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:68]: Good point. I think that is better and safe.

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java [hunk 5]
```diff
@@ -18,72 +18,224 @@
...
-      Assert.assertTrue(reader.loadNextBatch());
-      Assert.assertTrue(root.equals(reader.getVectorSchemaRoot()));
-      Assert.assertFalse(reader.loadNextBatch());
+      if (expectSuccess) {
+        Assert.assertTrue(reader.loadNextBatch());
+        Assert.assertTrue(root.equals(reader.getVectorSchemaRoot()));
+        Assert.assertFalse(reader.loadNextBatch());
+      } else {
+        Exception exception = Assert.assertThrows(IllegalArgumentException.class, reader::loadNextBatch);
+        Assert.assertEquals(expectedErrorMessage, exception.getMessage());
```
[the remark this answers is not in the document]
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:114]: I had doubts after the cleanup 😄
Let me update the PR.

**Comment by vibhatha** [comment]
@danepitkin I am not sure if [this one](https://github.com/apache/arrow/pull/38371#discussion_r1401071273) is practical though :thinking:

**Comment by danepitkin** [comment]
> @danepitkin I am not sure if [this one](https://github.com/apache/arrow/pull/38371#discussion_r1401071273) is practical though 🤔

I'm okay with leaving it as-is if there are issues with using `@BeforeEach` instead of `@Before`.

Overall, LGTM! I think it's ready for final review from a committer. Excellent job.

**Comment by vibhatha** [comment]
@lidavidm appreciate your feedback.

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java [hunk 6]
```diff
@@ -18,72 +18,245 @@
...
       writer.start();
       writer.writeBatch();
       writer.end();
     }
+    return tempFile;
+  }
 
-    // Read the in-memory compressed arrow file with CommonsCompressionFactory provided
+  @Test
+  @Disabled
```
Comment (lidavidm) [inline java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:152]: Why is this disabled?

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java [hunk 7]
```diff
@@ -174,6 +178,12 @@ public long bytesWritten() {
     return out.getCurrentPosition();
   }
 
+  private CompressionCodec getCodec() {
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java:181]: It seems we should be able to initialize the codec once and reuse it in the constructor, rather than add all the new fields?

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 6 above)
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:152]: updated and tested.

**Comment by vibhatha** [comment]
@lidavidm I updated the PR. Appreciate another round of reviews.

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowFileWriter.java [hunk 8]
```diff
@@ -76,15 +74,8 @@ public ArrowFileWriter(VectorSchemaRoot root, DictionaryProvider provider, Writa
...
-                         Map<String, String> metaData, IpcOption option, CompressionCodec.Factory compressionFactory,
-                         CompressionUtil.CodecType codecType) {
-    this(root, provider, out, metaData, option, compressionFactory, codecType, Optional.empty());
-  }
-
-  public ArrowFileWriter(VectorSchemaRoot root, DictionaryProvider provider, WritableByteChannel out,
-                         Map<String, String> metaData, IpcOption option, CompressionCodec.Factory compressionFactory,
-                         CompressionUtil.CodecType codecType, Optional<Integer> compressionLevel) {
-    super(root, provider, out, option, compressionFactory, codecType, compressionLevel);
+      Map<String, String> metaData, IpcOption option, CompressionCodec codec) {
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowFileWriter.java:77]: Isn't this removing a public constructor?

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowStreamWriter.java [hunk 9]
```diff
@@ -82,33 +80,13 @@ public ArrowStreamWriter(VectorSchemaRoot root, DictionaryProvider provider, Wri
...
-   * @param option IPC write options
-   * @param compressionFactory Compression codec factory
-   * @param codecType Codec type
    * @param out WritableByteChannel for writing.
-   */
-  public ArrowStreamWriter(VectorSchemaRoot root, DictionaryProvider provider, WritableByteChannel out,
-                           IpcOption option, CompressionCodec.Factory compressionFactory,
-                           CompressionUtil.CodecType codecType) {
-    this(root, provider, out, option, compressionFactory, codecType, Optional.empty());
-  }
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowStreamWriter.java:94]: Isn't this also removing a constructor?

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java [hunk 10]
```diff
@@ -82,22 +81,16 @@ protected ArrowWriter(VectorSchemaRoot root, DictionaryProvider provider, Writab
...
    * @param out                the output where to write
    * @param option             IPC write options
-   * @param compressionFactory Compression codec factory
-   * @param codecType          Compression codec
-   * @param compressionLevel   Compression level
+   * @param codec              the compression codec
    */
-  protected ArrowWriter(VectorSchemaRoot root, DictionaryProvider provider, WritableByteChannel out, IpcOption option,
-                        CompressionCodec.Factory compressionFactory, CompressionUtil.CodecType codecType,
-                        Optional<Integer> compressionLevel) {
```
Comment (lidavidm) [inline java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java:91]: This is changing a constructor signature?

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (lidavidm) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:66]: This is unaddressed.

**Review by lidavidm — COMMENTED** [review]
@vibhatha can you file a followup to add a new integration test to cover this scenario?

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowFileWriter.java (hunk 8 above)
Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowFileWriter.java:77]: You can delegate constructors without removing public ones (which breaks API).

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java]: Btw @lidavidm 

I updated the JUnit annotations for consistency and compatibility. The @BeforeEach annotation from JUnit 5 was being used in conjunction with @Test from JUnit 4, causing the setup method not to run as expected before each test. 

Furthermore do we need to make the usage of JUnit consistent across tests?

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowFileWriter.java (hunk 8 above)
Comment (vibhatha) [reply java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowFileWriter.java]: @lidavidm does the updated change make sense?

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java]: Is this okay?

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java (hunk 7 above)
Comment (vibhatha) [reply java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java:184]: @lidavidm an issue was filed here: https://github.com/apache/arrow/issues/39222
Also, I can work on this.

**Comment by vibhatha** [comment]
@lidavidm I updated the PR, appreciate another round of reviews.

File: java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java (hunk 7 above)
Comment (lidavidm) [reply java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java:184]: Again: why did we pull this out? It's called only once. Why are we adding a bunch of new fields? We don't use them.

**Comment by vibhatha** [comment]
> @vibhatha can you file a followup to add a new integration test to cover this scenario?

Issue filed here: https://github.com/apache/arrow/issues/39222

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java [hunk 11]
```diff
@@ -18,72 +18,247 @@
...
+    List<Field> fields = new ArrayList<>();
+    fields.add(new Field("col", FieldType.notNullable(new ArrowType.Utf8()), new ArrayList<>()));
+    fields.add(encodedVector.getField());
+
+    return fields;
+  }
+
+  private File writeArrowStream(VectorSchemaRoot root, DictionaryProvider provider,
+      CompressionUtil.CodecType codecType) throws IOException {
+    File tempFile = File.createTempFile("dictionary_compression", ".arrow");
```
Comment (lidavidm) [inline java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:141]: Are we deleting the temporary files?

Can we avoid using files in the first place? Why not an in-memory buffer?

**Review by lidavidm — APPROVED** [review]

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 11 above)
Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:141]: Sure @lidavidm I will update.

Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:141]: @lidavidm I was attemping both in-memory and disk approaches that's why this function is used in the first place. 
I can delete the file after the test or, I can remove this test entirely. 

What would be the best?

Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java:141]: Sure, I will remove the redundant test.

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

File: java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java (hunk 11 above)
Comment (lidavidm) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java]: Well, is the stream reader/writer still tested, though?

Comment (vibhatha) [reply java/compression/src/test/java/org/apache/arrow/compression/TestArrowReaderWriterWithCompression.java]: Good catch, David. I added that test specifically for that and used files for some reason (I honestly cannot reason now why I did it then), but I will add it as an in-memory test. I missed it. Thanks for noting this.

**Review by lidavidm — APPROVED** [review]
