### PR TITLE
GH-36249: [MATLAB] Create a `MATLAB_ASSIGN_OR_ERROR` macro to mirror the C++ `ARROW_ASSIGN_OR_RAISE` macro

### LINKED ISSUE #36249: [MATLAB] Create a `MATLAB_ASSIGN_OR_ERROR` macro to mirror the C++ `ARROW_ASSIGN_OR_RAISE` macro
### Describe the enhancement requested

Per the discussion in https://github.com/apache/arrow/pull/36190#discussion_r1237932111, it would help with code conciseness and clarity if we created a macro like `MATLAB_ASSIGN_OR_ERROR` to mirror the design of the [`ARROW_ASSIGN_OR_RAISE`](https://github.com/apache/arrow/blob/320ecbd119f26cb2f8d604ed84aae2559dbc0e26/cpp/src/arrow/result.h#L475) macro.

The naming `MATLAB_ASSIGN_OR_ERROR` roughly matches the naming of the [`MATLAB_ERROR_IF_NOT_OK`](https://github.com/apache/arrow/blob/e3eb5898e75a0b901724f771a7e2de069993a33c/matlab/src/cpp/arrow/matlab/error/error.h#L26) macro.

This will make working with `arrow::Result` types in the MATLAB interface code much easier.

**Example**:

```cpp
MATLAB_ASSIGN_OR_ERROR(auto array, MakeArray(), error::FAILED_TO_MAKE_ARRAY);
```

### Component(s)

MATLAB

### PR DESCRIPTION
**Pull request by kevingurney**
### Rationale for this change

1. To make working with `arrow::Result<T>` values easier in the C++ code for the MATLAB interface, it would be useful to have a `MATLAB_ASSIGN_OR_ERROR` macro that mirrors the design of the [`ARROW_ASSIGN_OR_RAISE`](https://github.com/apache/arrow/blob/320ecbd119f26cb2f8d604ed84aae2559dbc0e26/cpp/src/arrow/result.h#L475) macro.
2. @kou helpfully suggested this here: https://github.com/apache/arrow/pull/36190#discussion_r1237932111.
3. There is already a [`MATLAB_ERROR_IF_NOT_OK`](https://github.com/apache/arrow/blob/e3eb5898e75a0b901724f771a7e2de069993a33c/matlab/src/cpp/arrow/matlab/error/error.h#L26) macro, so this would roughly follow the approach of that macro.

### What changes are included in this PR?

1. Added new macros `MATLAB_ASSIGN_OR_ERROR(lhs, rexpr, id)`, `MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT(lhs, rexpr, context, id)`, and `MATLAB_ERROR_IF_NOT_OK_WITH_CONTEXT(expr, context, id)`.
2. Added additional comments describing the error macros.
3. Updated call sites (i.e. `numeric_array.h`, `boolean_array.cc`, and `record_batch.cc`) where `arrow::Result<T>` is being returned to use new `MATLAB_ASSIGN_OR_ERROR` / `MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT` macros where possible.

**Example**

*`MATLAB_ASSIGN_OR_ERROR`*

```matlab
// Erroring from a static Proxy "make" member function 
libmexclass::proxy::MakeResult CustomProxy::make(const libmexclass::proxy::FunctionArguments& constructor_arguments) {
    ...
    MATLAB_ASSIGN_OR_ERROR(auto array, array_builder.Finish(), "arrow:matlab:array:builder:FailedToBuildArray");
    ...
}
``` 

*`MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT`*

```matlab
// Erroring from a non-static Proxy member function 
void CustomProxy::example(libmexclass::proxy::method::Context& context) {
    ...
    // context is passed in as an input argument to the non-static Proxy member function
    MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT(auto array, array_builder.Finish(), context, "arrow:matlab:array:builder:FailedToBuildArray");
    ...
}
``` 

### Are these changes tested?

Yes.

1. The client code that was changed to use `MATLAB_ASSIGN_OR_ERROR` / `MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT` compiles and works as expected.
2. **Note**: The `MATLAB_ERROR_IF_NOT_OK_WITH_CONTEXT` and `MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT` macros are intended to be used with *non-static* `Proxy` member functions. For reference, non-static `Proxy` member functions return an error ID to MATLAB by assigning to the `context.error` property of the input `libmexclass::proxy::method::Context` object (see [this example](https://github.com/mathworks/libmexclass/blob/77f3d72c22a9ddab7b54ba325d757c3e82e57987/example/proxy/Car.cpp#L46)). This is different than how errors are returned  to MATLAB from within a `Proxy` static `make()` method.

### Are there any user-facing changes?

Yes.

1. There are now new `MATLAB_ASSIGN_OR_ERROR` / `MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT` macros that can be used to simplify the process of extracting a value of type `T` from an expression that returns an `arrow::Result<T>` or returning an appropriate error to MATLAB if the status of the `Result` is not "OK".

### Future Directions

1. Consider modifying `mathworks/libmexclass` so that non-static `Proxy` member functions return a `Result`-like object, instead of requiring clients to assign to `context.error`. This might help avoid the need for two different "kinds" of macros - i.e. `MATLAB_ASSIGN_OR_ERROR` / `MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT` and `MATLAB_ERROR_IF_NOT_OK` / `MATLAB_ERROR_IF_NOT_OK_WITH_CONTEXT`.

### Notes

1. Thank you @sgilmore10 for your help with this pull request!
* Closes: #36249

### CODE REVIEW

File: matlab/src/cpp/arrow/matlab/error/error.h [hunk 1]
```diff
@@ -17,19 +17,154 @@
...
+//         }                                                                     \
+//     } while (0)                                                               \
+
+#define MATLAB_ASSIGN_OR_RAISE_NAME(x, y) \
+    ARROW_CONCAT(x, y)                    \
+
+#define MATLAB_ASSIGN_OR_ERROR_IMPL(result_name, lhs, rexpr, id) \
+    auto&& result_name = (rexpr);                                \
+    MATLAB_ERROR_IF_NOT_OK(result_name.status(), id);            \
+    lhs = std::move(result_name).ValueUnsafe();                  \
```
Comment (kou) [inline matlab/src/cpp/arrow/matlab/error/error.h:91]:
```suggestion
    lhs = std::move(result_name).ValueUnsafe();
```

File: matlab/src/cpp/arrow/matlab/error/error.h [hunk 2]
```diff
@@ -17,19 +17,154 @@
...
+// #define MATLAB_ERROR_IF_NOT_OK_WITH_CONTEXT(expr, context, id)                \
+//     do {                                                                      \
+//         arrow::Status _status = (expr);                                       \
+//         if (!_status.ok()) {                                                  \
+//             context.error = libmexclass::error::Error{id, _status.message()}; \
+//             return;                                                           \
+//         }                                                                     \
+//     } while (0)                                                               \
+
+#define MATLAB_ASSIGN_OR_RAISE_NAME(x, y) \
```
Comment (kou) [inline matlab/src/cpp/arrow/matlab/error/error.h:85]: How about using `ERROR` instead of `RAISE` like others?

```suggestion
#define MATLAB_ASSIGN_OR_ERROR_NAME(x, y) \
```

**Review by kou — APPROVED** [review]
+1

File: matlab/src/cpp/arrow/matlab/error/error.h (hunk 2 above)
Comment (kevingurney) [reply matlab/src/cpp/arrow/matlab/error/error.h]: Good point!

File: matlab/src/cpp/arrow/matlab/error/error.h [hunk 3]
```diff
@@ -17,19 +17,154 @@
...
+// A macro used to return an error to MATLAB if the arrow::Status returned
+// by the specified expression is not "OK" (i.e. error).
+//
+// **NOTE**: This macro should be used inside of the static make() member function for a
+//           Proxy class. Use MATLAB_ERROR_IF_NOT_OK_WITH_CONTEXT inside of a non-static
+//           Proxy member function.
+//
+// --- Arguments ---
+//
+// lhs - variable name to assign to (e.g. auto array)
```
[the remark this answers is not in the document]
Comment (kevingurney) [reply matlab/src/cpp/arrow/matlab/error/error.h]: Thanks for catching this! I think I had named the input argument `lhs` originally and then renamed it and forgot to remove this line.

File: matlab/src/cpp/arrow/matlab/error/error.h [hunk 4]
```diff
@@ -17,19 +17,154 @@
...
+// MATLAB_ERROR_IF_NOT_OK(builder.Append(...), error::BUILDER_FAILED_TO_APPEND);
+//
 #define MATLAB_ERROR_IF_NOT_OK(expr, id)                               \
     do {                                                               \
         arrow::Status _status = (expr);                                \
         if (!_status.ok()) {                                           \
             return libmexclass::error::Error{(id), _status.message()}; \
         }                                                              \
-    } while (0)
+    } while (0)                                                        \
```
[the remark this answers is not in the document]
Comment (kevingurney) [reply matlab/src/cpp/arrow/matlab/error/error.h]: Sorry about the extra line continuations! I don't have much prior experience writing macros like this, so this is really helpful.

**Comment by kou** [comment]
Could you rebase on main?

**Comment by kevingurney** [comment]
I uncommented the `MATLAB_ASSIGN_OR_ERROR_WITH_CONTEXT` and `MATLAB_ERROR_IF_NOT_OK_WITH_CONTEXT` macros since the `RecordBatch` code now uses them. I've updated the description of the PR to reflect this change.

**Review by kou — APPROVED** [review]
+1
