### PR TITLE
GH-38430: [R] Add test + fix corner cases after nixlibs.R refactor

### LINKED ISSUE #38430: [R] Add test for new nixlibs.R
### Describe the enhancement requested

#38236 and previous PRs add new functionality to nixlibs.R which are mostly not covered in `test-nixlibs.R`.

### Component(s)

R

### PR DESCRIPTION
**Pull request by paleolimbot**
### Rationale for this change

A few rough edges exist after https://github.com/apache/arrow/pull/38236 including:

- When zero or 1 nightly with the matching major version exist, detection of the latest nightly might fail
- At least one CI job is pulling nightlies instead of using the version from the current commit

### What changes are included in this PR?

- Clean up `find_latest_nightly()` + add test
- Ensure all CI jobs are not using `find_latest_nightly()`

### Are these changes tested?

Yes (test added)

### Are there any user-facing changes?

No
* Closes: #38430

### CODE REVIEW

File: r/tools/nixlibs.R [hunk 1]
```diff
@@ -35,7 +35,9 @@ exit <- function(..., .status = 1) {
 
 
 # checks the nightly repo for the latest nightly version X.Y.Z.100<dev>
-find_latest_nightly <- function(description_version) {
+find_latest_nightly <- function(description_version,
+                                list_uri = "https://nightlies.apache.org/arrow/r/src/contrib/PACKAGES",
```
Comment (assignUser) [inline r/tools/nixlibs.R:39]: oh yeah that makes more sense ^^

File: r/tools/nixlibs.R [hunk 2]
```diff
@@ -867,6 +887,8 @@ build_ok <- !env_is("LIBARROW_BUILD", "false")
 #  https://arrow.apache.org/docs/developers/cpp/building.html#offline-builds)
 download_ok <- !test_mode && !env_is("TEST_OFFLINE_BUILD", "true")
 
+download_libarrow_ok <- download_ok && !env_is("LIBARROW_DOWNLOAD", "false")
```
Comment (assignUser) [inline r/tools/nixlibs.R:890]: Why this addition? Would not `LIBARROW_BINARY=false` do the same?

**Review by assignUser — APPROVED** [review]
Some nice additions, looks good! 

I think it makes sense to not look for latest nightly when `source`ing the script. As that only happens for tests and there it makes more sense to test the function directly and not produce spurious output in the test file.

File: r/tools/nixlibs.R (hunk 2 above)
Comment (paleolimbot) [reply r/tools/nixlibs.R:890]: I forget what exactly it caused to fail, but I think the idea is that LIBARROW_BINARY controls whether or not static libs are attempted, sort of, and LIBARROW_DOWNLOAD strictly controls whether or not an http request is issued to get that binary. Mostly I just noticed that it was already set in the CI job ( https://github.com/apache/arrow/actions/runs/6801463295/job/18492381028?pr=38534#step:5:1094 ) and it was somewhat complicated to figure out how to wire up LIBARROW_BINARY because of the levels of abstraction on top of the R CI jobs.

Comment (assignUser) [reply r/tools/nixlibs.R:890]: Ah ok, fine with me.

File: r/tools/nixlibs.R [hunk 3]
```diff
@@ -44,17 +46,32 @@ find_latest_nightly <- function(description_version) {
...
-      latest <- matching_major[which.max(matching_major$X4), ]
-      package_version(paste0(latest, collapse = "."))
+      urls <- readLines(list_uri)
+      versions <- grep("Version:\\s*.*?", urls, value = TRUE)
+      versions <- sort(package_version(sub("Version:\\s*", "\\1", versions)))
+      major_versions <- vapply(
+        versions,
+        function(x) as.integer(x[[c(1, 1)]]),
+        integer(1)
+      )
```
Comment (jonkeane) [inline r/tools/nixlibs.R:56]: Any reason not to do: 

```suggestion
      major_versions <- versions$major
```

File: r/tools/nixlibs.R [hunk 4]
```diff
@@ -44,17 +46,32 @@ find_latest_nightly <- function(description_version) {
...
+        lg(
+          "No nightly binaries were found for version %s: falling back to libarrow build from source",
+          description_version
+        )
+
+        return(description_version)
+      }
+
+      versions <- versions[matching_major]
+      versions[[length(versions)]]
```
Comment (jonkeane) [inline r/tools/nixlibs.R:70]: Would this be equivalent here?

```suggestion
      max(versions)
```

If so, it might be nicer since it's clearer that you're taking the largest available version (as opposed to the last version available, which above is sorted such that it's actually the largest), no?

**Comment by jonkeane** [comment]
If the CI is good, I'm ok to merge this, though if you're looking for some other people to test this locally let me know and I'll pull it and try it (I will admit I have not yet!)

**Comment by jonkeane** [comment]
Thanks for this!
