### PR TITLE
GH-33317: [C++] Utility method to ensure an array object meetings an alignment requirement

### LINKED ISSUE #33317: [C++] Utility method to ensure an array object meetings an alignment requirement
This would look something like:

EnsureAligned(Buffer|Array|ChunkedArray|RecordBatch|Table, int minimum_alignment, MemoryPool\* memory_pool);

It would fail if MemoryPool's alignment < minimum_alignment
It would iterate through each buffer of the object, if the object is not aligned properly, it would reallocate and copy the buffer (using memory_pool)

It would return a new object where every buffer is guaranteed to meet the alignment requirements.

**Reporter**: [Weston Pace](https://issues.apache.org/jira/browse/ARROW-18119) / @westonpace
**Assignee**: [Sanjiban Sengupta](https://issues.apache.org/jira/browse/ARROW-18119) / @sanjibansg
#### PRs and other links:
- [GitHub Pull Request #14758](https://github.com/apache/arrow/pull/14758)

<sub>**Note**: *This issue was originally created as [ARROW-18119](https://issues.apache.org/jira/browse/ARROW-18119). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by sanjibansg**
This PR adds a utility function which is responsible for ensuring that all the buffers of an arrow object are properly aligned. It checks all the buffers in an arrow object for alignment, and if not aligned properly, then allocates a buffer by specifying the required alignment and copies data from the previous buffer.
* Closes: #33317

### CODE REVIEW

File: cpp/src/arrow/util/align_util.h [hunk 1]
```diff
@@ -64,5 +66,23 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
   return p;
 }
 
+template <typename T>
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:69]: Why is this templated?  Right now this relies on `T::data()` existing.  What other types of `T` do you expect to accept?

File: cpp/src/arrow/util/align_util.h [hunk 2]
```diff
@@ -64,5 +66,23 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
...
+                       MemoryPool* memory_pool) {
+  std::vector<std::shared_ptr<Buffer>> buffers_ = object->data()->buffers;
+  for (size_t i = 0; i < buffers_.size(); ++i) {
+    if (buffers_[i]) {
+      auto buffer_address = buffers_[i]->address();
+      if ((buffer_address % alignment) != 0) {
+        ARROW_ASSIGN_OR_RAISE(
+            auto new_buffer, AllocateBuffer(buffers_[i]->size(), alignment, memory_pool));
+        std::memcpy(new_buffer->mutable_data(), buffers_[i]->data(), buffers_[i]->size());
+        object->data()->buffers[i] = std::move(new_buffer);
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:80]: It'd be nice (and more consistent with the rest of the code base) if we could do this by returning a new `std::shared_ptr<Array>` instead of modifying the existing array in-place.  You should be able to create a new `ArrayData` with the new buffers and then create a new `Array` from that.

File: cpp/src/arrow/util/align_util.h [hunk 3]
```diff
@@ -64,5 +66,23 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
   return p;
 }
 
+template <typename T>
+Status EnsureAlignment(std::shared_ptr<T> object, int64_t alignment,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:70]: This method doesn't recurse into child arrays.  For example, a `StructArray` is going to have `object->children()` that will need to be visited as well.

**Review by westonpace — CHANGES_REQUESTED** [review]
This is a good start but we need to be more thorough.

File: cpp/src/arrow/util/align_util.h (hunk 2 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Made the change, thanks!

File: cpp/src/arrow/util/align_util.cc [hunk 4]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
 
 namespace util {
 
-Result<std::shared_ptr<Array>> EnsureAlignment(const Array& object, int64_t alignment,
+Result<std::shared_ptr<Buffer>> EnsureAlignment(const std::shared_ptr<Buffer>& object, int64_t alignment,
                                                MemoryPool* memory_pool) {
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:30]:
```suggestion
Result<std::shared_ptr<Buffer>> EnsureAlignment(std::shared_ptr<Buffer> object, int64_t alignment,
                                               MemoryPool* memory_pool) {
```

Also, the method should use move appropriate so I can do...

```
std::shared_ptr<Buffer> foo = ...
foo = EnsureAlignment(std::move(foo), 64, default_memory_pool())
// Should only make a copy of `foo` or the `shared_ptr` if the buffer was not aligned.
```

File: cpp/src/arrow/util/align_util.cc [hunk 5]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
...
-  std::vector<std::shared_ptr<Buffer>> buffers_ = object.data()->buffers;
+    auto buffer_address = object->address();
+    if ((buffer_address % alignment) != 0) {
+        ARROW_ASSIGN_OR_RAISE(
+                auto new_buffer, AllocateBuffer(object->size(), alignment, memory_pool));
+        std::memcpy(new_buffer->mutable_data(), object->data(), object->size());
+        return new_buffer;
+    } else {
+        return object;
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:38]:
```suggestion
        return std::move(object);
```

Needed if you follow the previous advice and change to `std::shared_ptr<Buffer> object` instead of `const std::shared_ptr<Buffer>&`

File: cpp/src/arrow/util/align_util.cc [hunk 6]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
 
 namespace util {
 
-Result<std::shared_ptr<Array>> EnsureAlignment(const Array& object, int64_t alignment,
+Result<std::shared_ptr<Buffer>> EnsureAlignment(const std::shared_ptr<Buffer>& object, int64_t alignment,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:29]:
```suggestion
Result<std::shared_ptr<Buffer>> EnsureAlignment(const std::shared_ptr<Buffer>& buffer, int64_t alignment,
```

File: cpp/src/arrow/util/align_util.cc [hunk 7]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
...
+        ARROW_ASSIGN_OR_RAISE(
+                auto new_buffer, AllocateBuffer(object->size(), alignment, memory_pool));
+        std::memcpy(new_buffer->mutable_data(), object->data(), object->size());
+        return new_buffer;
+    } else {
+        return object;
+    }
+}
+
+Result<std::shared_ptr<Array>> EnsureAlignment(const std::shared_ptr<Array>& object, int64_t alignment,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:42]:
```suggestion
Result<std::shared_ptr<Array>> EnsureAlignment(const std::shared_ptr<Array>& array, int64_t alignment,
```

File: cpp/src/arrow/util/align_util.cc [hunk 8]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
...
-        std::memcpy(new_buffer->mutable_data(), buffers_[i]->data(), buffers_[i]->size());
-        buffers_[i] = std::move(new_buffer);
+        ARROW_ASSIGN_OR_RAISE(buffers_[i], EnsureAlignment(buffers_[i], alignment, memory_pool));
       }
-    }
   }
   auto new_array_data =
-      ArrayData::Make(object.data()->type, object.data()->length, std::move(buffers_),
-                      object.data()->GetNullCount(), object.data()->offset);
+      ArrayData::Make(object->data()->type, object->data()->length, std::move(buffers_),
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:51]: You still need to handle the dictionary and the children.

File: cpp/src/arrow/util/align_util.cc [hunk 9]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
...
+                      object->data()->GetNullCount(), object->data()->offset);
   return MakeArray(new_array_data);
 }
 
-Result<std::shared_ptr<ChunkedArray>> EnsureAlignment(const ChunkedArray& object,
+Result<std::shared_ptr<ChunkedArray>> EnsureAlignment(const std::shared_ptr<ChunkedArray>& object,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:56]:
```suggestion
Result<std::shared_ptr<ChunkedArray>> EnsureAlignment(const std::shared_ptr<ChunkedArray>& array,
```

File: cpp/src/arrow/util/align_util.cc [hunk 10]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
...
     ARROW_ASSIGN_OR_RAISE(chunks_[i],
-                          EnsureAlignment(*object.chunk(i), alignment, memory_pool));
+                          EnsureAlignment(object->chunk(i), alignment, memory_pool));
   }
-  return ChunkedArray::Make(std::move(chunks_), object.type());
+  return ChunkedArray::Make(std::move(chunks_), object->type());
 }
 
-Result<std::shared_ptr<RecordBatch>> EnsureAlignment(const RecordBatch& object,
+Result<std::shared_ptr<RecordBatch>> EnsureAlignment(const std::shared_ptr<RecordBatch>& object,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:67]:
```suggestion
Result<std::shared_ptr<RecordBatch>> EnsureAlignment(const std::shared_ptr<RecordBatch>& batch,
```

File: cpp/src/arrow/util/align_util.cc [hunk 11]
```diff
@@ -26,56 +26,63 @@ namespace arrow {
...
     ARROW_ASSIGN_OR_RAISE(columns_[i],
-                          EnsureAlignment(*object.column(i), alignment, memory_pool));
+                          EnsureAlignment(object->column(i), alignment, memory_pool));
   }
-  return RecordBatch::Make(object.schema(), object.num_rows(), std::move(columns_));
+  return RecordBatch::Make(object->schema(), object->num_rows(), std::move(columns_));
 }
 
-Result<std::shared_ptr<Table>> EnsureAlignment(const Table& object, int64_t alignment,
+Result<std::shared_ptr<Table>> EnsureAlignment(const std::shared_ptr<Table>& object, int64_t alignment,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:78]:
```suggestion
Result<std::shared_ptr<Table>> EnsureAlignment(const std::shared_ptr<Table>& table, int64_t alignment,
```

File: cpp/src/arrow/util/align_util.h [hunk 12]
```diff
@@ -68,19 +68,25 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
 
 namespace util {
 
-Result<std::shared_ptr<Array>> EnsureAlignment(const Array& object, int64_t alignment,
-                                               MemoryPool* memory_pool);
+Result<std::shared_ptr<Buffer>> EnsureAlignment(const std::shared_ptr<Buffer>& object,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:71]:
```suggestion
Result<std::shared_ptr<Buffer>> EnsureAlignment(const std::shared_ptr<Buffer>& buffer,
```

File: cpp/src/arrow/util/align_util.h [hunk 13]
```diff
@@ -68,19 +68,25 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
...
+                                                int64_t alignment,
+                                                MemoryPool* memory_pool);
 
-Result<std::shared_ptr<ChunkedArray>> EnsureAlignment(const ChunkedArray& object,
-                                                      int64_t alignment,
-                                                      MemoryPool* memory_pool);
+Result<std::shared_ptr<Array>> EnsureAlignment(const std::shared_ptr<Array>& object,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:75]:
```suggestion
Result<std::shared_ptr<Array>> EnsureAlignment(const std::shared_ptr<Array>& array,
```

File: cpp/src/arrow/util/align_util.h [hunk 14]
```diff
@@ -68,19 +68,25 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
...
+                                               int64_t alignment,
+                                                MemoryPool* memory_pool);
 
-Result<std::shared_ptr<RecordBatch>> EnsureAlignment(const RecordBatch& object,
-                                                     int64_t alignment,
-                                                     MemoryPool* memory_pool);
+Result<std::shared_ptr<ChunkedArray>> EnsureAlignment(
+    const std::shared_ptr<ChunkedArray>& object, int64_t alignment,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:80]:
```suggestion
    const std::shared_ptr<ChunkedArray>& array, int64_t alignment,
```

File: cpp/src/arrow/util/align_util.h [hunk 15]
```diff
@@ -68,19 +68,25 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
...
+    MemoryPool* memory_pool);
 
-Result<std::shared_ptr<Table>> EnsureAlignment(const Table& object, int64_t alignment,
-                                               MemoryPool* memory_pool);
+Result<std::shared_ptr<RecordBatch>> EnsureAlignment(
+    const std::shared_ptr<RecordBatch>& object, int64_t alignment,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:84]:
```suggestion
    const std::shared_ptr<RecordBatch>& batch, int64_t alignment,
```

File: cpp/src/arrow/util/align_util.h [hunk 16]
```diff
@@ -68,19 +68,25 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
...
+    MemoryPool* memory_pool);
+
+Result<std::shared_ptr<Table>> EnsureAlignment(const std::shared_ptr<Table>& object,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.h:87]:
```suggestion
Result<std::shared_ptr<Table>> EnsureAlignment(const std::shared_ptr<Table>& table,
```

**Review by westonpace — CHANGES_REQUESTED** [review]
In most cases the alignment will already be correct.  We want this method to be really fast in that scenario.  So this means that methods should look like...

```
std::shared_ptr<Array> Foo(std::shared_ptr<Array> thing) {
  if (needs_alignment(...)) {
    // a copy needs to be made
  } else {
    return std::move(thing);
  }
}
```

This way we can call it like so...

```
std::shared_ptr<Array> aligned = EnsureAlignment(std::move(unaligned), ...);
```

Then, if `unaligned` is already aligned it will be a straight move into `aligned` without ever making any copies (not even copies of `shared_ptr`)

File: cpp/src/arrow/util/align_util.h (hunk 3 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Now checking the children as well

File: cpp/src/arrow/util/align_util.cc (hunk 4 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change, thanks!

File: cpp/src/arrow/util/align_util.cc (hunk 6 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change.

File: cpp/src/arrow/util/align_util.cc (hunk 8 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Handling children and dictionary.

File: cpp/src/arrow/util/align_util.cc (hunk 5 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change, thanks!

File: cpp/src/arrow/util/align_util.cc (hunk 7 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change.

File: cpp/src/arrow/util/align_util.h (hunk 12 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Made the change.

File: cpp/src/arrow/util/align_util.h (hunk 14 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Made the change.

File: cpp/src/arrow/util/align_util.h (hunk 15 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Made the change.

File: cpp/src/arrow/util/align_util.h (hunk 16 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Made the change.

File: cpp/src/arrow/util/align_util.cc (hunk 9 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change.

File: cpp/src/arrow/util/align_util.cc (hunk 10 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change.

File: cpp/src/arrow/util/align_util.cc (hunk 11 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change.

**Comment by sanjibansg** [comment]
> In most cases the alignment will already be correct. We want this method to be really fast in that scenario. So this means that methods should look like...
> 
> ```
> std::shared_ptr<Array> Foo(std::shared_ptr<Array> thing) {
>   if (needs_alignment(...)) {
>     // a copy needs to be made
>   } else {
>     return std::move(thing);
>   }
> }
> ```
> 
> This way we can call it like so...
> 
> ```
> std::shared_ptr<Array> aligned = EnsureAlignment(std::move(unaligned), ...);
> ```
> 
> Then, if `unaligned` is already aligned it will be a straight move into `aligned` without ever making any copies (not even copies of `shared_ptr`)

The current implementation might be a bit complicated, so comments and suggestions for optimized approaches will be very helpful. Thanks in advance! 

Currently, we have `Check` functions for various Arrow objects, which check their constituents for alignments. For `ChunkedArray`, `RecordBatch`, and `Table`, we use a boolean vector to track the constituents which require alignment thus avoiding unnecessary function calls.

File: cpp/src/arrow/util/align_util.cc [hunk 17]
```diff
@@ -0,0 +1,215 @@
...
+    if (child) {
+      if (!CheckAlignment(*child, alignment)) align_children = false;
+    }
+  }
+  return CheckAlignment(*array.data(), alignment) && align_dictionary && align_children;
+}
+
+bool CheckAlignment(const ChunkedArray& array, const int64_t& alignment,
+                    std::vector<bool>& needs_alignment, const int& offset) {
+  needs_alignment.resize(needs_alignment.size() + array.num_chunks(), false);
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:59]: Why `needs_alignment.size() + array.num_chunks()` and not `offset + array.num_chunks()`?

File: cpp/src/arrow/util/align_util.cc [hunk 18]
```diff
@@ -0,0 +1,215 @@
...
+  for (auto i = 0; i < array.num_chunks(); ++i) {
+    if (array.chunk(i) && !CheckAlignment(*array.chunk(i), alignment))
+      needs_alignment[i + offset] = true;
+  }
+  return std::find(needs_alignment.begin() + offset,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util.cc:64]: Instead of doing `std::find` at the end (which will loop through `needs_alignment`) could you do something like...

```
bool at_least_one_needs_alignment = false;
for (...) {
  if (...) {
    needs_alignment[i + offset] = true;
    at_least_one_needs_alignment = true;
  }
}
return at_least_one_needs_alignment;
```

File: cpp/src/arrow/util/align_util_test.cc [hunk 19]
```diff
@@ -145,6 +150,84 @@ TEST(BitmapWordAlign, UnalignedDataStart) {
...
 }
-
 }  // namespace internal
+
+TEST(EnsureAlignment, Array) {
+  MemoryPool* pool = default_memory_pool();
+  auto rand = ::arrow::random::RandomArrayGenerator(1923);
+  auto random_array = rand.UInt8(/*size*/ 50, /*min*/ 0, /*max*/ 100,
+                                 /*null_probability*/ 0, /*alignment*/ 512, pool);
+  ASSERT_OK_AND_ASSIGN(auto aligned_array,
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util_test.cc:160]: Maybe assert that `CheckAlignment(..., 1024)` returns `false` before you call `EnsureAlignment`?

**Review by westonpace — CHANGES_REQUESTED** [review]
The approach looks ok.  I have a few suggestions.

File: cpp/src/arrow/util/align_util.h [hunk 20]
```diff
@@ -63,6 +64,43 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
   p.aligned_start = data + (bit_offset + p.leading_bits) / 8;
   return p;
 }
-
 }  // namespace internal
+
+namespace util {
+
+ARROW_EXPORT bool CheckAlignment(const Buffer& buffer, const int64_t& alignment);
```
[the remark this answers is not in the document]
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Oh yes, sorry, I did that by mistake. Corrected that. Thanks for pointing it out.

File: cpp/src/arrow/util/align_util.h [hunk 21]
```diff
@@ -63,6 +64,43 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
...
+ARROW_EXPORT bool CheckAlignment(const ArrayData& array, const int64_t& alignment);
+ARROW_EXPORT bool CheckAlignment(const Array& array, const int64_t& alignment);
+ARROW_EXPORT bool CheckAlignment(const ChunkedArray& array, const int64_t& alignment,
+                                 std::vector<bool>& needs_alignment,
+                                 const int& offset = 0);
```
[the remark this answers is not in the document]
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Made the change, thanks for the suggestion.

File: cpp/src/arrow/util/align_util.cc [hunk 22]
```diff
@@ -0,0 +1,215 @@
...
+  if (array.type()->id() == Type::DICTIONARY) {
+    align_dictionary = CheckAlignment(*array.data()->dictionary, alignment);
+  }
+
+  for (const auto& child : array.data()->child_data) {
+    if (child) {
+      if (!CheckAlignment(*child, alignment)) align_children = false;
+    }
+  }
+  return CheckAlignment(*array.data(), alignment) && align_dictionary && align_children;
```
[the remark this answers is not in the document]
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Moved the checking to the `CheckAlignment` function for `ArrayData`.

File: cpp/src/arrow/util/align_util.cc [hunk 23]
```diff
@@ -0,0 +1,215 @@
...
+bool CheckAlignment(const Array& array, const int64_t& alignment) {
+  bool align_dictionary = true, align_children = true;
+
+  if (array.type()->id() == Type::DICTIONARY) {
+    align_dictionary = CheckAlignment(*array.data()->dictionary, alignment);
+  }
+
+  for (const auto& child : array.data()->child_data) {
+    if (child) {
+      if (!CheckAlignment(*child, alignment)) align_children = false;
```
[the remark this answers is not in the document]
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: Made the change, thanks.

File: cpp/src/arrow/util/align_util.cc (hunk 17 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.cc]: The resize is basically to add space for the extra elements that should be added for the check. 
For example, if we have a table made up of 2 chunked arrays, which then are made of 2 arrays each. Then, initially `needs_alignment` will be of size 2 (because of 2 chunked arrays). When the `CheckAlignment()` is called for the first chunked array, `needs_alignment` will be resized to 4 `(/*needs_alignment.size()/* 2 + /*array.num_chunks()*/ 2), thus now in needs_alignment, first two bits indicate status of the 2 arrays of the first chunk array, the third one for the ChunkArray as a whole, and the last one for the other chunk array which yet to be checked. The similar operation gets repeated for the other chunked array.

Instead if we use offset, then for the first iteration here, offset will be 0. So, the resize will enforce its size to 2, which will not be enough for storing the alignment  check bits of the first two arrays of the first chunk array, and the second chunk array.

File: cpp/src/arrow/util/align_util.h [hunk 24]
```diff
@@ -63,6 +64,43 @@ inline BitmapWordAlignParams BitmapWordAlign(const uint8_t* data, int64_t bit_of
...
+ARROW_EXPORT bool CheckAlignment(const RecordBatch& batch, const int64_t& alignment,
+                                 std::vector<bool>& needs_alignment);
+ARROW_EXPORT bool CheckAlignment(const Table& table, const int64_t& alignment,
+                                 std::vector<bool>& needs_alignment);
```
[the remark this answers is not in the document]
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util.h]: Added documentation for CheckAlignment functions. Thanks for the suggestion.

File: cpp/src/arrow/util/align_util_test.cc (hunk 19 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util_test.cc:177]: Made the change, thanks.

**Review by westonpace — CHANGES_REQUESTED** [review]
I believe the unit tests are failling because `CopySlice` is not guaranteed to give you an unaligned array.

File: cpp/src/arrow/util/align_util_test.cc [hunk 25]
```diff
@@ -59,6 +63,18 @@ void CheckBitmapWordAlign(const uint8_t* data, int64_t bit_offset, int64_t lengt
   }
 }
 
+arrow::Result<std::shared_ptr<Array>> CreateUnalignedArray(std::shared_ptr<Array> array) {
+  BufferVector sliced_buffers(array->data()->buffers.size(), nullptr);
+  for (std::size_t i = 0; i < array->data()->buffers.size(); ++i) {
+    if (array->data()->buffers[i]) {
+      sliced_buffers[i] = array->data()->buffers[i]->CopySlice(0, 2).MoveValueUnsafe();
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util_test.cc:70]: Sorry, this comment was meant to accompany the review but it seems Github swallowed it.  `CopySafe` allocates a new buffer and copies the slice into this new buffer.  The newly allocated buffer will have at least 64 byte alignment but, depending on the system allocator (or just bad luck), this alignment could be greater.

Instead you should use [`SliceBuffer`](https://github.com/apache/arrow/blob/main/cpp/src/arrow/buffer.h#L322).  However, `SliceBuffer` returns a view only (this is inevitable here) so you need to make sure to keep the original array alive.  To do that change this method to accept `const Array&` instead of `std::shared_ptr<Array>`.  Then you should be ok.

File: cpp/src/arrow/util/align_util_test.cc [hunk 26]
```diff
@@ -59,6 +63,18 @@ void CheckBitmapWordAlign(const uint8_t* data, int64_t bit_offset, int64_t lengt
...
+    }
+  }
+  auto sliced_array_data =
+      ArrayData::Make(array->type(), array->length(), std::move(sliced_buffers));
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util_test.cc:74]: The length should be smaller here correct?  Since your arrays are all `uint8` you should decrease the length to match the slice.

File: cpp/src/arrow/util/align_util_test.cc (hunk 25 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util_test.cc]: made the change, thanks for the suggestion.

File: cpp/src/arrow/util/align_util_test.cc [hunk 27]
```diff
@@ -59,6 +63,18 @@ void CheckBitmapWordAlign(const uint8_t* data, int64_t bit_offset, int64_t lengt
   }
 }
 
+arrow::Result<std::shared_ptr<Array>> CreateUnalignedArray(const Array& array) {
+  BufferVector sliced_buffers(array.data()->buffers.size(), nullptr);
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util_test.cc:67]:
```suggestion
  // Slicing by 1 would create an invalid array if the type was wider than
  // 1 byte so double-check that the array is a 1-byte type
  EXPECT_EQ(array.type_id(), Type::UINT8);
  BufferVector sliced_buffers(array.data()->buffers.size(), nullptr);
```

File: cpp/src/arrow/util/align_util_test.cc [hunk 28]
```diff
@@ -59,6 +63,18 @@ void CheckBitmapWordAlign(const uint8_t* data, int64_t bit_offset, int64_t lengt
...
+  for (std::size_t i = 0; i < array.data()->buffers.size(); ++i) {
+    if (array.data()->buffers[i]) {
+      sliced_buffers[i] = SliceBuffer(array.data()->buffers[i], 1, 2);
+    }
+  }
+  auto sliced_array_data =
+      ArrayData::Make(array.type(), array.length(), std::move(sliced_buffers));
```
Comment (westonpace) [inline cpp/src/arrow/util/align_util_test.cc:74]:
```suggestion
  auto sliced_array_data =
      ArrayData::Make(array.type(), /*length=*/2, std::move(sliced_buffers));
```

This works today, but only because you never call `Validate` or any kind of compute function on the returned array.  This could be a time bomb for a future maintainer.  Better to make sure the array is properly formed which means the length of the array must match the length of its buffers.

**Review by westonpace — CHANGES_REQUESTED** [review]
Thanks, can you make two small changes in the test?  They aren't strictly needed but they will help prevent future surprises for maintainers.

File: cpp/src/arrow/util/align_util_test.cc (hunk 27 above)
Comment (sanjibansg) [reply cpp/src/arrow/util/align_util_test.cc:70]: made the change, thanks for the suggestion.

**Review by westonpace — APPROVED** [review]
Thanks for adding this utility!

**Comment by kou** [comment]
@sanjibansg It seems that this breaks our nightly CI. Could you check this?

https://github.com/ursacomputing/crossbow/actions/runs/4518357593/jobs/7958180632#step:6:1378

```text
[ 34%] Building CXX object src/arrow/CMakeFiles/arrow_objlib.dir/util/async_util.cc.o
cd /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/src/arrow && /usr/lib64/ccache/c++  -DARROW_EXPORTING -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_HDFS -DARROW_WITH_BACKTRACE -DARROW_WITH_BROTLI -DARROW_WITH_BZ2 -DARROW_WITH_LZ4 -DARROW_WITH_RE2 -DARROW_WITH_SNAPPY -DARROW_WITH_TIMING_TESTS -DARROW_WITH_UTF8PROC -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -DURI_STATIC_BUILD -DUTF8PROC_STATIC -I/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/src -I/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src -I/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/generated -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/thirdparty/flatbuffers/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/thirdparty/hadoop/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/boost_ep-prefix/src/boost_ep -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/orc_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/zstd_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/protobuf_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/utf8proc_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/re2_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/xsimd_ep/src/xsimd_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/jemalloc_ep-prefix/src  -Wno-noexcept-type -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic -fdiagnostics-color=always  -Wall -fno-semantic-interposition -msse4.2  -DNDEBUG -ftree-vectorize -fPIC   -pthread -std=c++1z -o CMakeFiles/arrow_objlib.dir/util/async_util.cc.o -c /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/arrow/util/async_util.cc
/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/arrow/util/align_util.cc: In function 'arrow::Result<std::shared_ptr<arrow::Buffer> > arrow::util::EnsureAlignment(std::shared_ptr<arrow::Buffer>, int64_t, arrow::MemoryPool*)':
/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/arrow/util/align_util.cc:104:12: error: could not convert 'new_buffer' from 'std::unique_ptr<arrow::Buffer>' to 'arrow::Result<std::shared_ptr<arrow::Buffer> >'
     return new_buffer;
            ^~~~~~~~~~
make[2]: *** [src/arrow/CMakeFiles/arrow_objlib.dir/util/align_util.cc.o] Error 1
```

**Comment by sanjibansg** [comment]
> @sanjibansg It seems that this broke our nightly CI. Could you check this?
> 
> https://github.com/ursacomputing/crossbow/actions/runs/4518357593/jobs/7958180632#step:6:1375
> 
> ```
> [ 34%] Building CXX object src/arrow/CMakeFiles/arrow_objlib.dir/util/align_util.cc.o
> cd /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/src/arrow && /usr/lib64/ccache/c++  -DARROW_EXPORTING -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_HDFS -DARROW_WITH_BACKTRACE -DARROW_WITH_BROTLI -DARROW_WITH_BZ2 -DARROW_WITH_LZ4 -DARROW_WITH_RE2 -DARROW_WITH_SNAPPY -DARROW_WITH_TIMING_TESTS -DARROW_WITH_UTF8PROC -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -DURI_STATIC_BUILD -DUTF8PROC_STATIC -I/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/src -I/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src -I/root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/generated -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/thirdparty/flatbuffers/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/thirdparty/hadoop/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/boost_ep-prefix/src/boost_ep -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/orc_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/zstd_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/protobuf_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/utf8proc_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/re2_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/xsimd_ep/src/xsimd_ep-install/include -isystem /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/build/jemalloc_ep-prefix/src  -Wno-noexcept-type -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic -fdiagnostics-color=always  -Wall -fno-semantic-interposition -msse4.2  -DNDEBUG -ftree-vectorize -fPIC   -pthread -std=c++1z -o CMakeFiles/arrow_objlib.dir/util/align_util.cc.o -c /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/arrow/util/align_util.cc
> ...
> /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/arrow/util/align_util.cc: In function 'arrow::Result<std::shared_ptr<arrow::Buffer> > arrow::util::EnsureAlignment(std::shared_ptr<arrow::Buffer>, int64_t, arrow::MemoryPool*)':
> /root/rpmbuild/BUILD/apache-arrow-12.0.0.dev290/cpp/src/arrow/util/align_util.cc:104:12: error: could not convert 'new_buffer' from 'std::unique_ptr<arrow::Buffer>' to 'arrow::Result<std::shared_ptr<arrow::Buffer> >'
>      return new_buffer;
>             ^~~~~~~~~~
> make[2]: *** [src/arrow/CMakeFiles/arrow_objlib.dir/util/align_util.cc.o] Error 1
> ```

Thanks for letting me know. I will make a fix.

**Comment by kou** [comment]
FYI: We can test this case by commenting `@github-actions crossbow submit amazon-linux-2-amd64`.

**Comment by sanjibansg** [comment]
@kou It is passing now! https://github.com/apache/arrow/pull/34754

cc: @westonpace
