### PR TITLE
GH-39769: [C++][Device] Fix Importing nested and string types for DeviceArray

### LINKED ISSUE #39769: [C++][Device] ImportDeviceArray fails on strings and nested types
### Describe the bug, including details regarding any error messages, version, and platform.

In my testing with libcudf and other GPU data, I discovered a deficiency in `ImportDeviceArray` and thus `ImportDeviceRecordBatch` where the device type and memory manager aren't propagated to child importers and it fails to import offset-based types such as strings.

These should be addressed with some new tests added to account for them. 

### Component(s)

C++

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
In my testing with libcudf and other GPU data, I discovered a deficiency in ImportDeviceArray and thus ImportDeviceRecordBatch where the device type and memory manager aren't propagated to child importers and it fails to import offset-based types such as strings.

### What changes are included in this PR?
These are relatively easily handled by first ensuring that `ImportChild` propagates the device_type and memory manager from the parent. Then for importing offset based values we merely need to use the memory manager to copy the final offset value to the CPU to use for the buffer size computation. 

This will work for any device which has implemented CopyBufferTo/From 

### Are these changes tested?
A new test is added to test these situations.

* Closes: #39769

### CODE REVIEW

File: cpp/src/arrow/c/bridge_test.cc [hunk 1]
```diff
@@ -4302,6 +4302,16 @@ TEST_F(TestDeviceArrayRoundtrip, Primitive) {
   TestWithJSON(mm, int32(), "[4, 5, null]");
 }
 
+TEST_F(TestDeviceArrayRoundtrip, Struct) {
```
Comment (pitrou) [inline cpp/src/arrow/c/bridge_test.cc:4305]: Should there also be a roundtrip with string/binary data?

File: cpp/src/arrow/device.cc [hunk 2]
```diff
@@ -193,6 +193,9 @@ Result<std::shared_ptr<Buffer>> CPUMemoryManager::ViewBufferFrom(
   if (!from->is_cpu()) {
     return nullptr;
   }
+  if (buf->device_type() != DeviceAllocationType::kCPU) {
```
Comment (pitrou) [inline cpp/src/arrow/device.cc:196]: Perhaps add a comment motivating this piece of code?

File: cpp/src/arrow/device.cc [hunk 3]
```diff
@@ -193,6 +193,9 @@ Result<std::shared_ptr<Buffer>> CPUMemoryManager::ViewBufferFrom(
...
+    return std::make_shared<Buffer>(buf->address(), buf->size(), shared_from_this());
```
Comment (pitrou) [inline cpp/src/arrow/device.cc:197]: The problem is that the returned buffer won't keep the underlying `buf` alive. You should set `buf` as parent.

File: cpp/src/arrow/device.cc [hunk 4]
```diff
@@ -218,6 +221,9 @@ Result<std::shared_ptr<Buffer>> CPUMemoryManager::ViewBufferTo(
   if (!to->is_cpu()) {
     return nullptr;
   }
+  if (buf->device_type() != DeviceAllocationType::kCPU) {
```
Comment (pitrou) [inline cpp/src/arrow/device.cc:224]: Same comments here.

**Review by pitrou — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/c/bridge_test.cc (hunk 1 above)
Comment (zeroshade) [reply cpp/src/arrow/c/bridge_test.cc:4305]: The struct data being used in this round trip is using a string column, I confirmed that it hits the scenario for string types that i'm addressing here.

File: cpp/src/arrow/device.cc (hunk 2 above)
Comment (zeroshade) [reply cpp/src/arrow/device.cc:200]: added

File: cpp/src/arrow/device.cc (hunk 3 above)
Comment (zeroshade) [reply cpp/src/arrow/device.cc]: I meant to do that and forgot, good catch! I've updated this and the other spot accordingly

File: cpp/src/arrow/device.cc (hunk 4 above)
Comment (zeroshade) [reply cpp/src/arrow/device.cc:232]: added

File: cpp/src/arrow/c/bridge_test.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/c/bridge_test.cc:4305]: Oops, sorry for letting this slip through. Yes, this is sufficient indeed!

File: cpp/src/arrow/c/bridge.cc [hunk 5]
```diff
@@ -1851,10 +1853,25 @@ struct ArrayImporter {
...
+    }
+
+    // we only need the value of the last offset so let's just copy that
+    // one value from device to host.
+    auto single_value_buf =
+        SliceBuffer(data_->buffers[offsets_buffer_id],
+                    c_struct_->length * sizeof(OffsetType), sizeof(OffsetType));
+    ARROW_ASSIGN_OR_RAISE(
+        auto cpubuf, Buffer::ViewOrCopy(single_value_buf, default_cpu_memory_manager()));
+    auto offsets = cpubuf->data_as<OffsetType>();
```
Comment (felipecrv) [inline cpp/src/arrow/c/bridge.cc:1871]: Perhaps copying a slice of an `address()` should be a `MemoryManager` operation.

Comment (felipecrv) [reply cpp/src/arrow/c/bridge.cc:1871]: Because it seems like an overkill to do all these operations in terms of `Buffer` objects to copy 4 or 8 bytes.

**Review by felipecrv — APPROVED** [review]

File: cpp/src/arrow/c/bridge.cc (hunk 5 above)
Comment (pitrou) [reply cpp/src/arrow/c/bridge.cc:1871]: Let's open a GH issue for this, then?

**Comment by zeroshade** [comment]
@pitrou I'll add explicit CUDA based tests for the device array interface as a separate PR for https://github.com/apache/arrow/issues/39786#issuecomment-1908321452

File: cpp/src/arrow/c/bridge.cc (hunk 5 above)
Comment (zeroshade) [reply cpp/src/arrow/c/bridge.cc:1871]: Created #39858

**Review by bkietz — APPROVED** [review]

**Review by pitrou — APPROVED** [review]
