### PR TITLE
GH-32570: [C++] Fix the issue of `ExecBatchBuilder` when appending consecutive tail rows with the same id may exceed buffer boundary

### LINKED ISSUE #32570: [C++] Segmentation fault on arrow-compute-hash-join-node-test on macos nightlies
Some of our nightly builds are failing due to a segmentation fault on hash-join tests:
```java

 33/90 Test #35: arrow-compute-hash-join-node-test .........***Failed    1.21 sec
Running arrow-compute-hash-join-node-test, redirecting output into /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/arrow-HEAD.XXXXX.W72iCJcj/cpp-build/build/test-logs/arrow-compute-hash-join-node-test.txt (attempt 1/1)
/Users/runner/work/crossbow/crossbow/arrow/cpp/build-support/run-test.sh: line 88: 78018 Segmentation fault: 11  $TEST_EXECUTABLE "$@" > $LOGFILE.raw 2>&1
Running main() from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/arrow-HEAD.XXXXX.W72iCJcj/cpp-build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest_main.cc
[==========] Running 29 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 10 tests from HashJoin
[ RUN      ] HashJoin.Suffix
[       OK ] HashJoin.Suffix (4 ms)
[ RUN      ] HashJoin.Random
/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/arrow-HEAD.XXXXX.W72iCJcj/cpp-build/src/arrow/compute/exec 
```
The failures can be seen. It seems to be only related to macos from the failed jobs:
[verify-rc-source-cpp-macos-conda-amd64](https://github.com/ursacomputing/crossbow/runs/7631965199?check_suite_focus=true)
[verify-rc-source-integration-macos-conda-amd64](https://github.com/ursacomputing/crossbow/runs/7631969879?check_suite_focus=true)
[verify-rc-source-python-macos-amd64](https://github.com/ursacomputing/crossbow/runs/7631926429?check_suite_focus=true)

**Reporter**: [Raúl Cumplido](https://issues.apache.org/jira/browse/ARROW-17292) / @raulcd
**Assignee**: [Vibhatha Lakmal Abeykoon](https://issues.apache.org/jira/browse/ARROW-17292) / @vibhatha
#### PRs and other links:
- [GitHub Pull Request #14373](https://github.com/apache/arrow/pull/14373)

<sub>**Note**: *This issue was originally created as [ARROW-17292](https://issues.apache.org/jira/browse/ARROW-17292). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by zanmato1984**
### Rationale for this change

Addressed in https://github.com/apache/arrow/issues/32570#issuecomment-1856473812

### What changes are included in this PR?

1. Skip consecutive rows with the same id when calculating rows to skip when appending to `ExecBatchBuilder`.
2. Fix the bug that column offset is neglected when calculating rows to skip.

### Are these changes tested?

Yes. New UT included and the change is also protected by the existing case mentioned in the issue.

### Are there any user-facing changes?

No.

**This PR contains a "Critical Fix".**

Because #32570 is labeled critical, and causes a crash even when the API contract is upheld.

* Closes: #32570

### CODE REVIEW

**Comment by zanmato1984** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp

**Comment by zanmato1984** [comment]
@github-actions crossbow submit test-macos-12-cpp

**Comment by zanmato1984** [comment]
@github-actions crossbow submit test-macos-cpp

**Comment by zanmato1984** [comment]
@github-actions crossbow submit cpp

**Comment by zanmato1984** [comment]
@github-actions crossbow submit test

**Comment by zanmato1984** [comment]
@github-actions crossbow submit -g cpp

**Comment by zanmato1984** [comment]
I wanted to retry the CI because the failures don't seem to be related to my change. I don't know how so I tried some commands but obviously they are not what I wanted :(

**Comment by pitrou** [comment]
cc @bkietz

File: cpp/src/arrow/compute/light_array.cc [hunk 1]
```diff
@@ -395,8 +395,12 @@ int ExecBatchBuilder::NumRowsToSkip(const std::shared_ptr<ArrayData>& column,
       --num_rows_left;
       int row_id_removed = row_ids[num_rows_left];
       const uint32_t* offsets =
-          reinterpret_cast<const uint32_t*>(column->buffers[1]->data());
+          reinterpret_cast<const uint32_t*>(column->buffers[1]->data()) + column->offset;
```
Comment (pitrou) [inline cpp/src/arrow/compute/light_array.cc:398]: You should probably be able to write:
```c++
      const uint32_t* offsets = column->GetValues<uint32_t>(1);
```

Comment (pitrou) [reply cpp/src/arrow/compute/light_array.cc:398]: Also, I suppose this doesn't work on large binary arrays (where the offset type would be `int64_t`)?

File: cpp/src/arrow/compute/light_array.cc [hunk 2]
```diff
@@ -395,8 +395,12 @@ int ExecBatchBuilder::NumRowsToSkip(const std::shared_ptr<ArrayData>& column,
...
       num_bytes_skipped += offsets[row_id_removed + 1] - offsets[row_id_removed];
+      // Skip consecutive rows with the same id
```
Comment (pitrou) [inline cpp/src/arrow/compute/light_array.cc:400]: I don't understand what `row_ids` is or why this is needed.
Would you like to update the docstring for `NumRowsToSkip` to make the semantics more understandable?

Also, why is `row_ids` ignored for fixed-width columns?

File: cpp/src/arrow/compute/light_array_test.cc [hunk 3]
```diff
@@ -411,6 +411,31 @@ TEST(ExecBatchBuilder, AppendBatchesSomeRows) {
   ASSERT_EQ(0, pool->bytes_allocated());
 }
 
+TEST(ExecBatchBuilder, AppendBatchDupRows) {
+  std::unique_ptr<MemoryPool> owned_pool = MemoryPool::CreateDefault();
```
Comment (pitrou) [inline cpp/src/arrow/compute/light_array_test.cc:415]: Can you a reference to the GH issue so we understand where this comes from?

File: cpp/src/arrow/compute/light_array.cc (hunk 1 above)
Comment (zanmato1984) [reply cpp/src/arrow/compute/light_array.cc:398]: You are right, I don't think they work for large binary or large string.

Comment (zanmato1984) [reply cpp/src/arrow/compute/light_array.cc:398]: Thanks for the simplified code suggestion. That's very nice to do.

File: cpp/src/arrow/compute/light_array.cc (hunk 2 above)
Comment (zanmato1984) [reply cpp/src/arrow/compute/light_array.cc:400]: > I don't understand what `row_ids` is or why this is needed.

In `ExecBatchBuilder::AppendSelected`, `row_ids` identifies which rows in the specific `source` array need to be appended to the target batch. `row_ids` is subsequently passed into `NumRowsToSkip`, basically to calculate the number of tail rows to skip, in order to do safe (within boundary) word-to-word copy.

For more information, please see the detailed description of this bug I put in the issue link: https://github.com/apache/arrow/issues/32570#issuecomment-1856473812

> Would you like to update the docstring for `NumRowsToSkip` to make the semantics more understandable?

Of course, will do.

> Also, why is `row_ids` ignored for fixed-width columns?

I also explained this in my comment in the issue https://github.com/apache/arrow/issues/32570#issuecomment-1856473812

File: cpp/src/arrow/compute/light_array_test.cc (hunk 3 above)
Comment (zanmato1984) [reply cpp/src/arrow/compute/light_array_test.cc:415]: Of course, will do.

Comment (zanmato1984) [reply cpp/src/arrow/compute/light_array_test.cc:475]: Addressed.

File: cpp/src/arrow/compute/light_array.cc (hunk 1 above)
Comment (zanmato1984) [reply cpp/src/arrow/compute/light_array.cc]: Addressed.

File: cpp/src/arrow/compute/light_array.cc (hunk 2 above)
Comment (zanmato1984) [reply cpp/src/arrow/compute/light_array.cc:403]: > Would you like to update the docstring for `NumRowsToSkip` to make the semantics more understandable?

I updated the docstring in the header, though I don't think I've made it more understandable :-(

Please let me know if you found any specific peace of the docstring is not clear enough. I appreciate that.

**Review by pitrou — APPROVED** [review]
