### PR TITLE
GH-38074: [C++] Fix Offset Size Calculation for Slicing Large String and Binary Types in Hash Join

### LINKED ISSUE #38074: [C++] [Acero] Incorrect results in inner join
### Describe the bug, including details regarding any error messages, version, and platform.

> Before explaining, if recreating previously submitted issues like this is considered a mistake, I apologize.
>
> * #37729 

### Overview

In the previous issue, the user is discussing the occurrence of incorrect results when performing an inner join.

Although it was well-explained in the previous issue, to reiterate, the user has created this issue because they are getting incorrect results when performing an inner join between two tables, namely `table_1` and `table_2`.

Each of these tables (`table_1` and `table_2`) has columns `col_1`, `col_2`, `col_3`, and `table_2` has an additional `col_4`. Upon my investigation, it appears that `table_2.parquet` has 7 more records, but for `col_1`, `col_2`, and `col_3`, it contains the same values as `table_1`.

The number of records in each table is 6282 and 6289, respectively.

So, when performing an inner join using `col_1`, `col_2`, and `col_3` as the join keys, the result should be 6282, regardless of the order of the tables.

### Reason

To start with the cause, there is an issue with the **BloomFilter** logic.

When testing in C++, if you set the BloomFilter option (`disable_bloom_filter`) to `true`, the join operation is performed without any issues.

```cpp
// with bloom_filter (default)
HashJoinNodeOptions join_opts{
    JoinType::INNER, 
    {"col_1", "col_2", "col_3"}, 
    {"col_1", "col_2", "col_3"}, 
    literal(true), 
    "_l", 
    "_r"
};

// without bloom_filter
HashJoinNodeOptions join_opts{
    JoinType::INNER, 
    {"col_1", "col_2", "col_3"}, 
    {"col_1", "col_2", "col_3"}, 
    literal(true), 
    "_l", 
    "_r",
    true // disable_bloom_filter
};
```

Additionally, the findings from further investigation are as follows.

1. The number of matching records between the left and right tables must exceed 1024.
2. When the number of matching records is close to the number of records in the right table, errors occur.
3. The number of matching records does not appear to have any correlation with the number of records in the left table.

Up to this point, this is what I have gathered about the issue, and I am working hard to fix the bug. 

However, I am a novice about Arrow, which is causing it to take longer than expected. Nonetheless, I will continue to make efforts to resolve the bug. 

Any advice or insights from those who are more experienced would be greatly appreciated, and it would also be great if someone with expertise could tackle this issue first. So, I'm sharing this here.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by llama90**
### Rationale for this change

We found that the wrong results in inner joins during hash join operations were caused by a problem with how large strings and binary types were handled. The `Slice` function was not calculating their sizes correctly.

To fix this, I changed the `Slice` function to calculate the sizes correctly, based on the type of data for large string and binary. 

* Issue raised: #37729 

### What changes are included in this PR?

* The `Slice` function has been updated to correctly calculate the offset for Large String and Large Binary types, and assertion statements have been added to improve maintainability.
* Unit tests (`TEST(KeyColumnArray, SliceBinaryTest)`)for the Slice function have been added. 
* During random tests for Hash Join (`TEST(HashJoin, Random)`), modifications were made to allow the creation of Large String as key column values.

### Are these changes tested?

Yes

### Are there any user-facing changes?

Acero might not have a large user base as it is an experimental feature, but I deemed the issue of incorrect join results as critical and have addressed the bug.

* Closes: #38074

### CODE REVIEW

File: cpp/src/arrow/compute/light_array.cc [hunk 1]
```diff
@@ -80,26 +80,24 @@ KeyColumnArray KeyColumnArray::Slice(int64_t offset, int64_t length) const {
...
+  if (metadata_.fixed_length == 0 && !metadata_.is_null_type) {
     sliced.buffers_[1] =
         buffers_[1] ? buffers_[1] + (bit_offset_[1] + offset) / 8 : nullptr;
     sliced.mutable_buffers_[1] = mutable_buffers_[1]
                                      ? mutable_buffers_[1] + (bit_offset_[1] + offset) / 8
                                      : nullptr;
     sliced.bit_offset_[1] = (bit_offset_[1] + offset) % 8;
   } else {
-    sliced.buffers_[1] = buffers_[1] ? buffers_[1] + offset * fixed_size : nullptr;
+    sliced.buffers_[1] = buffers_[1] ? buffers_[1] + offset * metadata_.fixed_length : nullptr;
```
Comment (pitrou) [inline cpp/src/arrow/compute/light_array.cc:98]: So, IIUC, `uint32_t * int64_t` would result in a `uint32_t` result?

**Comment by pitrou** [comment]
@llama90 I don't understand why you've changed your fix, while I was asking you to explain the underlying bug.

**Comment by llama90** [comment]
@pitrou I thought you were pointing out a part in the code where a bug could occur due to implicit type conversion. 

So that's why I made the changes, and I didn't realize that there should be a discussion first when such reviews are given. I apologize for the confusion.

Is it right to fundamentally ask why the code was changed?

The initial issue raised was regarding incorrect return values of the Inner Join. Upon analyzing the code, it was found that during the execution of the `BuildBloomFilter_exec_task` function, incorrect offset calculations were made when calling the `HashBatch` function, leading to incorrect hash values being generated.

`HashBatch` is responsible for copying ColumnArrays within the Key Batch using offset and length, and it calls the `Slice` function during this process. 

In the issue, a `large_utf8` type key column was being used, and the original code was set to always calculate the offset for such binary types as `uint32_t` size, which resulted in incorrect Inner Join outcomes.

**Comment by pitrou** [comment]
> In the issue, a `large_utf8` type key column was being used, and the original code was set to always calculate the offset for such binary types as `uint32_t` size, which resulted in incorrect Inner Join outcomes.

Ahah, ok, thanks for the explanation.

**Review by pitrou — CHANGES_REQUESTED** [review]
Here are some comments.

Also, can you add join tests with large_binary or large_utf8?

**Comment by llama90** [comment]
@pitrou You are right. I will incorporate your feedback and add the Commit as soon as possible.

**Comment by llama90** [comment]
> Here are some comments.
> 
> Also, can you add join tests with large_binary or large_utf8?

I added the unit test about inner join for `large_binary` or `large_utf8`

* https://github.com/apache/arrow/pull/38147/commits/3894147f8273facf551f5070c084c2513a6d048d

File: cpp/src/arrow/compute/light_array_test.cc [hunk 2]
```diff
@@ -226,6 +226,104 @@ TEST(KeyColumnArray, SliceBool) {
   }
 }
 
+TEST(KeyColumnArray, SliceBinary) {
```
[the remark this answers is not in the document]
Comment (llama90) [reply cpp/src/arrow/compute/light_array_test.cc:229]: I enhanced the unit tests for readability

File: cpp/src/arrow/compute/light_array.cc [hunk 3]
```diff
@@ -80,16 +80,15 @@ KeyColumnArray KeyColumnArray::Slice(int64_t offset, int64_t length) const {
...
   sliced.buffers_[0] =
       buffers_[0] ? buffers_[0] + (bit_offset_[0] + offset) / 8 : nullptr;
   sliced.mutable_buffers_[0] =
       mutable_buffers_[0] ? mutable_buffers_[0] + (bit_offset_[0] + offset) / 8 : nullptr;
   sliced.bit_offset_[0] = (bit_offset_[0] + offset) % 8;
 
-  if (fixed_size == 0 && !metadata_.is_null_type) {
+  if (metadata_.fixed_length == 0 && !metadata_.is_null_type) {
     sliced.buffers_[1] =
         buffers_[1] ? buffers_[1] + (bit_offset_[1] + offset) / 8 : nullptr;
```
[the remark this answers is not in the document]
Comment (llama90) [reply cpp/src/arrow/compute/light_array.cc:93]: The code I modified is handled in the section below (`else` statement), reflecting the type size as `fixed_size`. 

Upon reviewing the implementation of the `ColumnMetadataFromDataType` function, it is understood that the type applicable to the mentioned case is `BOOL` and `is_fixed_width()`. (In the case of `DICTIONARY`, it ensures that ARROW_DCHECK(bit_width % 8 == 0) is checked to guarantee that it is a multiple of 8.)

https://github.com/apache/arrow/blob/907723663e6e20033d0c2fef4eb0f880daacdb09/cpp/src/arrow/compute/light_array.cc#L111-L145

* [Data Types](https://arrow.apache.org/docs/cpp/api/datatype.html)

**Comment by ianmcook** [comment]
@llama90 could you please run the linter? Instructions at https://arrow.apache.org/docs/developers/cpp/development.html#code-style-linting-and-ci

**Comment by llama90** [comment]
> @llama90 could you please run the linter? Instructions at https://arrow.apache.org/docs/developers/cpp/development.html#code-style-linting-and-ci

Did I apply the lint correctly as you intended?

**Comment by ianmcook** [comment]
> > @llama90 could you please run the linter? Instructions at https://arrow.apache.org/docs/developers/cpp/development.html#code-style-linting-and-ci
> 
> Did I apply the lint correctly as you intended?

Yes, the "Dev / Lint C++, Python, R, Docker, RAT" test is passing now

**Comment by ianmcook** [comment]
@llama90 could you please merge/rebase this with the latest changes on the main branch? That should fix the remaining CI failure.

**Comment by pitrou** [comment]
FTR, I still need to take a look at the fix and see if we can make things more maintainable and more understandable in the future.

**Comment by llama90** [comment]
> FTR, I still need to take a look at the fix and see if we can make things more maintainable and more understandable in the future.

If possible, could you provide specific guidelines?

**Comment by llama90** [comment]
> @llama90 could you please merge/rebase this with the latest changes on the main branch? That should fix the remaining CI failure.

I have rebased and force pushed.

File: cpp/src/arrow/acero/hash_join_node_test.cc [hunk 4]
```diff
@@ -2124,5 +2124,266 @@ TEST(HashJoin, ChainedIntegerHashJoins) {
...
 }
 
+// This test case is related to GH-38147
+// To verify that the issue with offset handling has been fixed, the number of matching
+// records needs to be larger than the mini-batch size (1024).
+constexpr uint64_t NUM_MATCH_RECORDS = 1234;
+constexpr uint64_t NUM_LEFT_RECORDS = 2000;
+constexpr uint64_t NUM_RIGHT_RECORDS = 1500;
+
+std::string GenerateTimestamp() {
```
Comment (pitrou) [inline cpp/src/arrow/acero/hash_join_node_test.cc:2134]: Are the custom generation functions required to surface the bug, or can we just build on existing generation functions? We already have random generation functions, for example.

File: cpp/src/arrow/acero/hash_join_node_test.cc [hunk 5]
```diff
@@ -2124,5 +2124,266 @@ TEST(HashJoin, ChainedIntegerHashJoins) {
...
+      GenerateLeftRecords(NUM_LEFT_RECORDS, currTS, leftExtraValues);
+  std::string rightRecords =
+      GenerateRightRecords(NUM_RIGHT_RECORDS, currTS, rightExtraValues);
+  std::string expectedRecords = GenerateExpectedRecords(
+      NUM_MATCH_RECORDS, currTS, leftExtraValues, rightExtraValues);
+
+  // Initialize left input data with the specific timestamp and large utf8 data
+  BatchesWithSchema input_left;
+  input_left.batches = {ExecBatchFromJSON(
+      {timestamp(TimeUnit::MICRO, "UTC"), large_utf8(), large_utf8()}, leftRecords)};
```
Comment (pitrou) [inline cpp/src/arrow/acero/hash_join_node_test.cc:2247]: Similar question here. Is using timestamps necessary to surface the bug or would it also be reproduced with e.g. plain integers? Trying to reduce the test case into a minimal reproducer would be useful for understanding and maintenance.

File: cpp/src/arrow/compute/light_array.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (pitrou) [reply cpp/src/arrow/compute/light_array.cc:93]: I'm not sure I understand your explanation, sorry :-) Can we add checks (or debug assertions) against the actual datatype in this function? Right now it's difficult to figure out what happens exactly, and to make sure we don't break it again.

File: cpp/src/arrow/compute/light_array_test.cc [hunk 6]
```diff
@@ -226,6 +226,120 @@ TEST(KeyColumnArray, SliceBool) {
...
+      {1, 3, {"World", "Slice", "Large"}},
+      {2, 3, {"Slice", "Large", "Binary"}},
+      {3, 3, {"Large", "Binary", "Test"}},
+      {0, 4, {"Hello", "World", "Slice", "Large"}},
+      {1, 4, {"World", "Slice", "Large", "Binary"}},
+      {2, 4, {"Slice", "Large", "Binary", "Test"}},
+      {0, 5, {"Hello", "World", "Slice", "Large", "Binary"}},
+      {1, 5, {"World", "Slice", "Large", "Binary", "Test"}},
+      {0, 6, {"Hello", "World", "Slice", "Large", "Binary", "Test"}},
+  };
```
Comment (pitrou) [inline cpp/src/arrow/compute/light_array_test.cc:320]: The two test cases (large and non-large) are almost identical except for the slight and non-useful variation in example data. I think it should be easy to refactor them into a common codebase so as to share most the code here, can you do that?

Comment (llama90) [reply cpp/src/arrow/compute/light_array_test.cc:256]: I've tried refactoring the Slice test function. Is this refactoring what you intended?

I'm also making progress on two other items, the join test and the assertion statements for the Slice function.

**Comment by llama90** [comment]
Apologies everyone, I performed a rebase on my personal repository's main branch and after rebasing the development branch, I pushed the changes. 

Unfortunately, commits that were already merged into main are now showing up in the history again. 

This was not intentional, and I'm looking for ways to correct this. If anyone has insights or suggestions on how to fix this, your assistance would be greatly appreciated.

**Comment by llama90** [comment]
I have removed the unrelated commits and forced a push. 

If this isn't the appropriate way to resolve the issue, please advise. I appreciate any guidance.

**Comment by llama90** [comment]
@pitrou I have enhanced the hash join tests as you mentioned, by modifying the existing unit test code. 

I confirmed that the random generator does not create data types corresponding to `uint64_t`, which is considered 'Large'. Accordingly, I have updated it to generate LargeString type data.

This appears to adequately generate data for offset calculations. An error occurs when testing based on the previously written `Slice` function code.

I'm still contemplating for the `Slice` function and need more time to consider the best approach.

**Comment by pitrou** [comment]
> If this isn't the appropriate way to resolve the issue, please advise. I appreciate any guidance. 😭

It seems like that did the trick :-)

File: cpp/src/arrow/compute/light_array.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (llama90) [reply cpp/src/arrow/compute/light_array.cc:95]: The `Slice` function processes the offset according to the types of `KeyColumnMetadata` it handles. With this in consideration, I've added the assertions using `ARROW_DCHECK`. Will this contribute to enhancing the understandability and maintenance of the code?

File: cpp/src/arrow/compute/light_array.cc [hunk 7]
```diff
@@ -80,27 +80,32 @@ KeyColumnArray KeyColumnArray::Slice(int64_t offset, int64_t length) const {
...
 
   sliced.buffers_[0] =
       buffers_[0] ? buffers_[0] + (bit_offset_[0] + offset) / 8 : nullptr;
   sliced.mutable_buffers_[0] =
       mutable_buffers_[0] ? mutable_buffers_[0] + (bit_offset_[0] + offset) / 8 : nullptr;
   sliced.bit_offset_[0] = (bit_offset_[0] + offset) % 8;
 
-  if (fixed_size == 0 && !metadata_.is_null_type) {
+  if (metadata_.fixed_length == 0 && !metadata_.is_null_type) {
+    ARROW_DCHECK(is_bool_type() || is_other_fixed_width_types())
```
Comment (westonpace) [inline cpp/src/arrow/compute/light_array.cc:92]: How would `is_other_fixed_width_types` be true here if `metadata_.fixed_length == 0`?  It seems we can only be here if bool.

File: cpp/src/arrow/compute/light_array.cc [hunk 8]
```diff
@@ -80,27 +80,32 @@ KeyColumnArray KeyColumnArray::Slice(int64_t offset, int64_t length) const {
...
+        << "Expected BOOL type or OTHER FIXED WIDTH type but got a different type.";
     sliced.buffers_[1] =
         buffers_[1] ? buffers_[1] + (bit_offset_[1] + offset) / 8 : nullptr;
     sliced.mutable_buffers_[1] = mutable_buffers_[1]
                                      ? mutable_buffers_[1] + (bit_offset_[1] + offset) / 8
                                      : nullptr;
     sliced.bit_offset_[1] = (bit_offset_[1] + offset) % 8;
-  } else {
+  } else if (metadata_.fixed_length > 0) {
+    ARROW_DCHECK(is_dictionary_type() || is_binary_type() || is_large_binary_type())
```
Comment (westonpace) [inline cpp/src/arrow/compute/light_array.cc:101]: I am confused.  If the type is `int32` then it seems we would reach this branch.  `metadata_.fixed_length` would be `4` and `metadata_.is_null_type` would be `false` and `metadata._is_fixed_length` would be `true`.

File: cpp/src/arrow/compute/light_array.h [hunk 9]
```diff
@@ -183,6 +183,36 @@ class ARROW_EXPORT KeyColumnArray {
   // Starting bit offset within the first byte (between 0 and 7)
   // to be used when accessing buffers that store bit vectors.
   int bit_offset_[kMaxBuffers - 1];
+
+  bool is_dictionary_type() const {
```
Comment (westonpace) [inline cpp/src/arrow/compute/light_array.h:187]: Does the `KeyColumnArray` even support storing dictionary encoded data?  I didn't think it did but I could be remembering incorrectly.

Comment (llama90) [reply cpp/src/arrow/compute/light_array.h:187]: Maybe, you are right.

My understanding is that the code is added, but probably unsupported or not being tested properly. 

So, I took a hint from what you said, I removed the code for the dictionary type within `KeyColumnArray` and ran the entire test and found that none of the tests covered that code :O 
(If that's okay, can we add a **new issue** for `KeyColumns` to have complex values like dictionary types?)

Looking at the data I was randomly generating in the `hash_join_node_test.cc` file, I was only generating data for the following types.

In the code below, I have added support for `LargeString` type.

https://github.com/apache/arrow/blob/e9aac8a4ce4b8833667efe52957fb0881a488c4b/cpp/src/arrow/acero/hash_join_node_test.cc#L284-L291

File: cpp/src/arrow/compute/light_array.h [hunk 10]
```diff
@@ -183,6 +183,36 @@ class ARROW_EXPORT KeyColumnArray {
...
+    return metadata_.is_fixed_length && metadata_.fixed_length != 0 &&
+           !metadata_.is_null_type;
```
[the remark this answers is not in the document]
Comment (llama90) [reply cpp/src/arrow/compute/light_array.h:189]: Answer excluding dictionary types. 

Unless bit types are covered by a custom type (with the exception of bool), it seems that data of type byte would be included in the condition to calculate the offset.

[the remark this answers is not in the document]
Comment (llama90) [reply cpp/src/arrow/compute/light_array.h:189]: You are correct. I overlooked that.

File: cpp/src/arrow/compute/light_array.h [hunk 11]
```diff
@@ -183,6 +183,36 @@ class ARROW_EXPORT KeyColumnArray {
...
+
+  bool is_bool_type() const {
+    return metadata_.is_fixed_length && metadata_.fixed_length == 0 &&
+           !metadata_.is_null_type;
+  }
+
+  bool is_other_fixed_width_types() const {
+    return metadata_.is_fixed_length && metadata_.fixed_length != 0 &&
+           !metadata_.is_null_type;
+  }
```
[the remark this answers is not in the document]
Comment (llama90) [reply cpp/src/arrow/compute/light_array.h:200]: You are correct. I overlooked that.

File: cpp/src/arrow/compute/light_array.cc (hunk 7 above)
Comment (llama90) [reply cpp/src/arrow/compute/light_array.cc:92]: You are right. The only thing that qualifies is the Bool type.

File: cpp/src/arrow/compute/light_array.cc (hunk 8 above)
Comment (llama90) [reply cpp/src/arrow/compute/light_array.cc:101]: That's right. 

If you're worried about why variable and fixed lengths are handled with the same logic, then the answer is as follows.

As I understand it, Arrow maintains a separate buffer for storing values for variable lengths. 

Because of this, we only need to calculate the offset well for the address pointing to the value, so I don't think fixed or variable length is an important consideration when calculating the offset. This is why I didn't think it was a problem to calculate it with the same logic.

If I'm misunderstanding, I'd be grateful to hear your concerns, I'm still a newbie to Arrow.

**Comment by llama90** [comment]
@westonpace I've refined the code, removing the dictionary type as it doesn't seem to be added in any test.

Also, I truly appreciate all the reviews.

As a beginner, I feel both overwhelmed and excited to handle an issue that requires a complex understanding. While I am aware of my limitations, I am committed to giving my best.

I humbly ask for your generous advice and guidance. Thank you.

File: cpp/src/arrow/compute/light_array.h (hunk 9 above)
Comment (westonpace) [reply cpp/src/arrow/compute/light_array.h]: >  (If that's okay, can we add a new issue for KeyColumns to have complex values like dictionary types?)

Is this request maybe covered by https://github.com/apache/arrow/issues/31622 , https://github.com/apache/arrow/issues/32494 , or https://github.com/apache/arrow/issues/32504 ?

Adding dictionary support for keys will be trickier than supporting large strings unfortunately.  I can give an overview of some of the steps but I don't know that anyone has been spending a lot of time on the hash join code lately.

File: cpp/src/arrow/compute/light_array.cc (hunk 8 above)
Comment (westonpace) [reply cpp/src/arrow/compute/light_array.cc]: > If I'm misunderstanding, I'd be grateful to hear your concerns, I'm still a newbie to Arrow.

I do not think this is a misunderstanding.  The key column array marks variable data as `!is_fixed_length` and then `fixed_length` should store the width of the offset (4 for string/binary and 8 for large_string/large_binary)

File: cpp/src/arrow/compute/light_array.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (westonpace) [reply cpp/src/arrow/compute/light_array.cc:94]: I think this is correct now.  `buffers_[0]` is the validity buffer and is handled consistently across all types.  This if/else if/else branch is handling the values (for fixed-width types) / offsets (for variable-width types) buffer.

So it's roughly...

```
if (is_bool) {
  slice by bit, update bit offset
} else if (!is_null) {
  slice by word (`fixed_size`), no bit offset needed
} else // is null {
  do nothing, there is no values buffer
}
```

**Review by westonpace — APPROVED** [review]
Thanks for your contribution!  This is an improvement over what was there before.  I think, with this PR, that slicing `KeyColumnArray` with large string works.

I'm not quite convinced yet that large strings work consistently in the hash join.  I see you did add some testing of large string / hash join in the hash_join_node_test but these don't cover values greater than 2^32 (which is hard to do in any kind of performant test sadly).  So maybe this is a sign that we support "large strings that could be stored as small strings"

If the values in `buffers_[1]` of the key column array are ever cast to `int32_t` in the hash join code (which I feel they most likely are) then this type of failure wouldn't show up until actual large strings start showing up.

However, this is an improvement, and we don't need to solve every problem all at once, so I don't see any real concern with proceeding with this PR if @pitrou is satisfied.

**Comment by westonpace** [comment]
> As a beginner, I feel both overwhelmed and excited to handle an issue that requires a complex understanding. While I am aware of my limitations, I am committed to giving my best.

The hash join code is complex and quite different from the rest of the arrow code base.  It unfortunately reinvents things that we have elsewhere.  Don't worry about feeling overwhelmed here, I think many of us are.  Do you have any long term goals for this feature?

**Comment by pitrou** [comment]
Yes, I agree the PR as is is a good improvement now.

What I would suggest is to update the PR title and description to better explain the problem. Specifically, it is about slicing large string and large binary types, with the problem being the offset size not correctly computed, IIUC.

("uint64_t Types" in the title is really confusing as this PR has nothing to do with 64-bit integer columns)

**Comment by pitrou** [comment]
Also, big +1 to what @westonpace said [above](https://github.com/apache/arrow/pull/38147#issuecomment-1763032429). You definitely didn't choose the easiest part of Arrow to contribute to :-)

**Comment by llama90** [comment]
@pitrou Hello, I have revised and updated the PR title and content.

@westonpace It seems like the issues you mentioned include the following items:

* Support for Dictionary types in key columns during Hash Join
* Handling of Dictionary types in Hash Join (Swiss)
* Join support when some columns contain lists

All are related to joins and seem to be interesting areas. I am also interested in the issues you've highlighted and would like to attempt improvements when I have some spare time.

I feel proud to have made a meaningful contribution.

@pitrou @westonpace @ianmcook Thank you again for your review, and I hope to engage with you more frequently with new contributions.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
Thanks a lot for this fix @llama90 !

@raulcd This should probably be a candidate for 14.0.0.
