### PR TITLE
GH-35326: [Go] Fix `*array.List` and `*array.LargeList` `ValueOffsets` implementation

### LINKED ISSUE #35326: [Go] Lists `ValueOffsets` implementation seems to be buggy
### Describe the bug, including details regarding any error messages, version, and platform.

Currently the `*array.List` and `*array.LargeList` use an internal function to calculate value offsets accounting for `a.array.data.offset`.
The `ValueOffsets` implementations of those don't do that.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by candiduslynx**
This fix also is connected to #35325 (as adds `*array.FixedSizeList` to the same bunch).

### Are there any user-facing changes?

* Closes: #35326
* Closes: #35325

### CODE REVIEW

File: go/arrow/cdata/cdata_exports.go [hunk 1]
```diff
@@ -416,13 +416,6 @@ func exportArray(arr arrow.Array, out *CArrowArray, outSchema *CArrowSchema) {
 		exportArray(arr.ListValues(), &children[0], nil)
 		childPtrs[0] = &children[0]
 		out.children = (**CArrowArray)(unsafe.Pointer(&childPtrs[0]))
-	case *array.FixedSizeList:
```
Comment (candiduslynx) [inline go/arrow/cdata/cdata_exports.go:419]: removed per matching `array.ListLike` above (unreachable code issue)

**Review by zeroshade — APPROVED** [review]
