### PR TITLE
GH-35760: [C++] C Data Interface helpers should also run checks in non-debug mode

### LINKED ISSUE #35760: [C++] `ArrowArrayStreamRelease` et al should clear the `ArrowArrayStream`
### Describe the bug, including details regarding any error messages, version, and platform.

This is supposed to be redundant; the `release` method is supposed to do this itself (as evidenced by the asserts), but this would guard against producers that forget to do so (like https://github.com/apache/arrow-nanoarrow/issues/203) and prevent runtime crashes.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by zeroshade**
### What changes are included in this PR?
Replaced `assert`s in the `Arrow*Release` methods with a macro which outputs to `stderr` and calls `std::abort` directly with a message. This way the check still happens in release mode. The `ARROW_CHECK*` macros require C++ and this is intended to be a C file which others can vendor.

### Are there any user-facing changes?
Instead of only failing in debug mode, now these release methods will fail if the release callback fails to set the `release` member to `null` even in release mode. Leading to potential calls to `std::abort` that weren't previously occurring.

* Closes: #35760

### CODE REVIEW

**Review by paleolimbot — APPROVED** [review]
This seems reasonable!

File: cpp/src/arrow/c/helpers.h [hunk 1]
```diff
@@ -18,10 +18,20 @@
...
+#include <stdlib.h>
 #include <string.h>
 
 #include "arrow/c/abi.h"
 
+#define CHECK_OR_DIE(condition, msg)                          \
+  do {                                                        \
+    if (!(condition)) {                                       \
+      fprintf(stderr, "%s:%d:: %s", __FILE__, __LINE__, msg); \
+      std::abort();                                           \
```
Comment (pitrou) [inline cpp/src/arrow/c/helpers.h:31]: This needs to be C code, not C++.

File: cpp/src/arrow/c/helpers.h [hunk 2]
```diff
@@ -18,10 +18,20 @@
...
+#include <stdio.h>
+#include <stdlib.h>
 #include <string.h>
 
 #include "arrow/c/abi.h"
 
+#define CHECK_OR_DIE(condition, msg)                          \
+  do {                                                        \
+    if (!(condition)) {                                       \
+      fprintf(stderr, "%s:%d:: %s", __FILE__, __LINE__, msg); \
```
Comment (pitrou) [inline cpp/src/arrow/c/helpers.h:30]: Let's allow `msg` to be complex.
```suggestion
      fprintf(stderr, "%s:%d:: %s", __FILE__, __LINE__, (msg)); \
```

File: cpp/src/arrow/c/helpers.h [hunk 3]
```diff
@@ -18,10 +18,20 @@
 #pragma once
 
 #include <assert.h>
```
Comment (pitrou) [inline cpp/src/arrow/c/helpers.h:20]: Can perhaps remove this inclusion now?

File: cpp/src/arrow/c/helpers.h (hunk 1 above)
Comment (zeroshade) [reply cpp/src/arrow/c/helpers.h]: good point, my mistake there at using `std::` it should be just `abort`.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@zeroshade `go/arrow/cdata/arrow/helpers.h` also needs to be updated but it's not a trivial copy of the C++ source anymore.

**Comment by pitrou** [comment]
@zeroshade Can you open an issue for the Go followup?
