### PR TITLE
GH-38795: [Go] Fix race GetToTimeFunc for Timestamp

### LINKED ISSUE #38795: [Go] Data race of calling `GetToTimeFunc` of fixed timestamp data type
### Describe the bug, including details regarding any error messages, version, and platform.

Hello,

I found a data race in `databricks-sql-go`. A root cause of data race is timestamp fields of `arrow.FixedWidthTypes` and the function `GetToTimeFunc()` of `arrow.TimestampType`.

A test to reproduce a data race:
```
import (
	"sync"
	"testing"

	"github.com/apache/arrow/go/v15/arrow"
)

func TestArrowDataRace(t *testing.T) {
	var (
		wg         sync.WaitGroup
		w          = make(chan bool)
		routineNum = 10
	)

	wg.Add(routineNum)
	for i := 0; i < routineNum; i++ {
		go func() {
			defer wg.Done()

			<-w

			_, _ = arrow.FixedWidthTypes.Timestamp_s.(*arrow.TimestampType).GetToTimeFunc()
		}()
	}

	close(w)

	wg.Wait()
}
```

A command to run this test with data race detector:

```
go test -race -run TestArrowDataRace .
```

A go version is 1.21.

The same issue is in Apache Arrow Go v12.

A root cause of data race is not initialised field `loc` of `arrow.TimestampType`. It initialised in the first call of function `arrow.TimestampType :: GetZone()`.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
Adding RWMutex to protect `loc` in `TimestampType` and fix the race condition.

### Are these changes tested?
Yes, a unit test is added which is covered by the CI which runs with `-race`.

### Are there any user-facing changes?
Copying `TimestampType` will now be problematic and linters will show it as an error. In theory this shouldn't be a problem as most uses of TimestampType should be utilizing pointers to it rather than the value directly.

* Closes: #38795

### CODE REVIEW

File: go/arrow/datatype_fixedwidth_test.go [hunk 1]
```diff
@@ -180,6 +181,29 @@ func TestTimestampType_GetToTimeFunc(t *testing.T) {
 	assert.Equal(t, "2345-12-29T19:00:00-05:00", toTimeNY(ts).Format(time.RFC3339))
 }
 
+func TestGetToTimeFuncRace(t *testing.T) {
```
Comment (benibus) [inline go/arrow/datatype_fixedwidth_test.go:184]:
```suggestion
// Test race condition from GH-38795
func TestGetToTimeFuncRace(t *testing.T) {
```

**Review by benibus — COMMENTED** [review]
LGTM (besides the nit)

**Review by felipecrv — APPROVED** [review]

File: go/arrow/datatype_fixedwidth.go [hunk 2]
```diff
@@ -398,10 +402,15 @@ func (t *TimestampType) ClearCachedLocation() {
...
 func (t *TimestampType) GetZone() (*time.Location, error) {
+	t.mx.RLock()
 	if t.loc != nil {
+		defer t.mx.RUnlock()
 		return t.loc, nil
 	}
 
+	t.mx.RUnlock()
+	t.mx.Lock()
+	defer t.mx.Unlock()
```
Comment (felipecrv) [inline go/arrow/datatype_fixedwidth.go:413]: Wait... :)

A full execution of `GetZone` is possible between `RUnlock()` and `Lock()`, so it's probably a good idea to check `t.loc` after the write lock is acquired.

For a lock-free way of doing this, you can combine atomic load/stores with a writers-only mutex. Porting this C++ snippet [1] to Go:

```cpp
std::atomic<Singleton*> Singleton::m_instance;
std::mutex Singleton::m_mutex;

Singleton* Singleton::getInstance() {
    Singleton* tmp = m_instance.load();
    if (tmp == nullptr) {
        std::lock_guard<std::mutex> lock(m_mutex);
        tmp = m_instance.load();
        if (tmp == nullptr) {
            tmp = new Singleton;
            m_instance.store(tmp);
        }
    }
    return tmp;
}
```

[1] https://preshing.com/20130930/double-checked-locking-is-fixed-in-cpp11/#using-c11-sequentially-consistent-atomics

Comment (zeroshade) [reply go/arrow/datatype_fixedwidth.go:413]: I'll add the check of `t.loc` after the write lock is acquired for now. My original attempt at this was to use `atomic.Pointer` for the loc but it made the test initialization for some of the tests annoying since you can't copy an `atomic.Pointer` and I didn't want to deal with refactoring the tests right now. 

For now, the `RWMutex` should be good enough with the added check to avoid the duplicate work. Nice catch!

**Review by felipecrv — APPROVED** [review]

**Review by bkietz — APPROVED** [review]

**Review by lidavidm — APPROVED** [review]

**Review by bkietz — APPROVED** [review]
