### PR TITLE
GH-35448: [C++] Fix detection of %z in strptime format

### LINKED ISSUE #35448: [C++] Detection of %z in strptime format fails in certain cases, not returning timestamp with tz=UTC
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/pull/11358 refactored the timezone offset handling in string parsing (both in read_csv, casting str->timestamp and strptime). 

The general rule was that if there is a `%z` in the format string you provide to `strptime`, we apply the offset and return a timestamp type with tz=UTC. 
But this seems to work only in certain cases:

```python
# space before %z -> works
>>> pc.strptime(["5/1/2020 +0100", None, "12/11/1900 -0130"], format="%m/%d/%Y %z", unit='us').type
TimestampType(timestamp[us, tz=UTC])
# no space before %z -> doesn't work
>>> pc.strptime(["5/1/2020+0100", None, "12/11/1900-0130"], format="%m/%d/%Y%z", unit='us').type
TimestampType(timestamp[us])
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
### Rationale for this change

See gh-35448 for the failing example. The current code in `GetZone` was assuming there was always some character between the `%z` and the preceding `%` code (like a whitespace, or `-` or `/`). That is often not the case with `%z` (in time formats like `00:00+01`, the `+` is part of `%z`, and so the format is `%H:%M%z` without character between `%M` and `%z`)
 
### Are these changes tested?

Test is added

### Are there any user-facing changes?

The result type will no now correctly have a `tz=UTC` parametrization
* Closes: #35448

### CODE REVIEW

File: cpp/src/arrow/compute/kernels/scalar_string_test.cc [hunk 1]
```diff
@@ -1900,6 +1900,12 @@ TYPED_TEST(TestStringKernels, StrptimeZoneOffset) {
   StrptimeOptions options("%m/%d/%Y %z", TimeUnit::MICRO, /*error_is_null=*/true);
   this->CheckUnary("strptime", input1, timestamp(TimeUnit::MICRO, "UTC"), output1,
                    &options);
```
Comment (kou) [inline cpp/src/arrow/compute/kernels/scalar_string_test.cc:1902]: Could you append `1` to `options` (`options1`) for consistency?

**Review by kou — APPROVED** [review]
+1

**Review by westonpace — APPROVED** [review]

**Review by pitrou — APPROVED** [review]
+1, thanks @jorisvandenbossche
