### PR TITLE
GH-41149: [C++][Acero] Fix asof join race

### LINKED ISSUE #40675: [C++][Python] Sporadic asof join test failure
### Describe the bug, including details regarding any error messages, version, and platform.

I sporadically get this failure when running the PyArrow tests locally:
```
__________________________________________________________________________ test_table_join_asof ___________________________________________________________________________
Traceback (most recent call last):
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/runner.py", line 240, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 181, in _multicall
    return outcome.get_result()
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_result.py", line 99, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 166, in _multicall
    teardown.throw(outcome._exception)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
    yield
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 166, in _multicall
    teardown.throw(outcome._exception)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
    yield
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 166, in _multicall
    teardown.throw(outcome._exception)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/logging.py", line 849, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/logging.py", line 832, in _runtest_for
    yield
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 166, in _multicall
    teardown.throw(outcome._exception)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/capture.py", line 883, in pytest_runtest_call
    return (yield)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 166, in _multicall
    teardown.throw(outcome._exception)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/skipping.py", line 256, in pytest_runtest_call
    return (yield)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/runner.py", line 182, in pytest_runtest_call
    raise e
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/runner.py", line 172, in pytest_runtest_call
    item.runtest()
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/python.py", line 1772, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/antoine/mambaforge/envs/pyarrow/lib/python3.10/site-packages/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/antoine/arrow/dev/python/pyarrow/tests/test_table.py", line 2800, in test_table_join_asof
    assert r.combine_chunks() == pa.table({
AssertionError: assert pyarrow.Table\ncolA: int64\ncol2: string\ncolC: double\n----\ncolA: [[1,1,5,6,7]]\ncol2: [["a","b","a","b","f"]]\ncolC: [[null,null,null,null,null]] == pyarrow.Table\ncolA: int64\ncol2: string\ncolC: double\n----\ncolA: [[1,1,5,6,7]]\ncol2: [["a","b","a","b","f"]]\ncolC: [[1,null,null,null,null]]
  
  Full diff:
    pyarrow.Table
    colA: int64
    col2: string
    colC: double
    ----
    colA: [[1,1,5,6,7]]
    col2: [["a","b","a","b","f"]]
  - colC: [[1,null,null,null,null]]
  ?         ^
  + colC: [[null,null,null,null,null]]
  ?         ^^^^
========================================================================= short test summary info =========================================================================
FAILED pyarrow/tests/test_table.py::test_table_join_asof - assert pyarrow.Table\ncolA: int64\ncol2: string\ncolC: double\n----\ncolA: [[1,1,5,6,7]]\ncol2: [["a","b","a","b","f"]]\ncolC: [[null,null,null,null,null]] == pyarrow...
```

### Component(s)

C++, Python

### PR DESCRIPTION
**Pull request by zanmato1984**
### Rationale for this change

Sporadic asof join test failures have been frequently and annoyingly observed in pyarrow CI, as recorded in #40675 and #41149.

Turns out the root causes are the same - a logical race (as opposed to physical race which can be detected by sanitizers). By injecting special delay in various places in asof join, as shown in https://github.com/zanmato1984/arrow/commit/ea3b24c5f7308fe42f60dad41f51dbcbc1a54929, the issue can be reproduced almost 100%. And I have put some descriptions in that commit to explain how the race happens.

### What changes are included in this PR?

Eliminate the logical race of emptiness by combining multiple call-sites of `Empty()`.

### Are these changes tested?

Include the UT to reproduce the issue.

### Are there any user-facing changes?

None.

**This PR contains a "Critical Fix".**
In #40675 and #41149 , incorrect results are produced.
* GitHub Issue: #41149 
* Also closes #40675

### CODE REVIEW

**Comment by zanmato1984** [comment]
Sorry, filed in the wrong repo.

**Comment by zanmato1984** [comment]
@ursabot please benchmark

**Comment by zanmato1984** [comment]
@ursabot please benchmark

**Comment by zanmato1984** [comment]
@ursabot please benchmark

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 1]
```diff
@@ -548,8 +548,10 @@ class InputState {
   // true when the queue is empty and, when memo may have future entries (the case of a
   // positive tolerance), when the memo is empty.
   // used when checking whether RHS is up to date with LHS.
-  bool CurrentEmpty() const {
-    return memo_.no_future_ ? Empty() : memo_.times_.empty() && Empty();
+  // NOTE: The emptiness must be decided by an atomic all to Empty() in caller, due to the
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node.cc:551]:
```suggestion
  // NOTE: The emptiness must be decided by an atomic call to Empty() in caller, due to the
```

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 2]
```diff
@@ -548,8 +548,10 @@ class InputState {
...
+  // potential race with Push(), see GH-41614.
+  bool CurrentEmpty(bool empty) const {
+    return memo_.no_future_ ? empty : memo_.times_.empty() && empty;
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node.cc:554]: Can you add parentheses to make sure operator precedence is not mistaken?

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 1 above)
Comment (pitrou) [reply cpp/src/arrow/acero/asof_join_node.cc:551]: Also, what do you call "atomic" here? I don't see any synchronization around calls to `Empty`.

File: cpp/src/arrow/acero/asof_join_node.cc [hunk 3]
```diff
@@ -918,34 +922,39 @@ class CompositeTableBuilder {
 // guaranteeing this probability is below 1 in a billion. The fix is 128-bit hashing.
 // See ARROW-17653
 class AsofJoinNode : public ExecNode {
-  // Advances the RHS as far as possible to be up to date for the current LHS timestamp
-  Result<bool> UpdateRhs() {
+  // Advances the RHS as far as possible to be up to date for the current LHS timestamp.
+  // Returns a pair of booleans. The first is if any RHS has advanced. The second is if
+  // all RHS are up to date for LHS.
+  Result<std::pair<bool, bool>> UpdateRhsAndCheckUpToDateWithLhs() {
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node.cc:928]: Can you return a struct with explanatory member names instead?

File: cpp/src/arrow/acero/asof_join_node_test.cc [hunk 4]
```diff
@@ -1678,5 +1678,55 @@ TEST(AsofJoinTest, BackpressureWithBatchesGen) {
                           /*slow_r0=*/false);
 }
 
+TEST(AsofJoinTest, GH40675) {
+  auto left_batch = ExecBatchFromJSON(
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node_test.cc:1682]: It's nice to give the GH issue reference, but it would even be a bit better with a comment explaining what specifically this test is doing (without having to decipher all the test code).

File: cpp/src/arrow/acero/asof_join_node_test.cc [hunk 5]
```diff
@@ -1678,5 +1678,55 @@ TEST(AsofJoinTest, BackpressureWithBatchesGen) {
...
+  ASSERT_OK_AND_ASSIGN(auto result, DeclarationToExecBatches(std::move(asof_join)));
+
+  auto exp_batch = ExecBatchFromJSON(
+      {int64(), utf8(), float64()},
+      R"([[1, "a", 1.0], [1, "b", null], [5, "a", null], [6, "b", null], [7, "f", null]])");
+  AssertExecBatchesEqualIgnoringOrder(result.schema, {exp_batch}, result.batches);
+}
+
+TEST(AsofJoinTest, GH41149) {
+  auto left_batch = ExecBatchFromJSON({int64()}, R"([[1], [2], [3]])");
```
Comment (pitrou) [inline cpp/src/arrow/acero/asof_join_node_test.cc:1709]: Same here.

**Review by pitrou — CHANGES_REQUESTED** [review]
It is hard to understand why this fixes the issue at all. The comments talk about an "atomic call" but I fail to see what is atomic here. This might even work by chance...

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 1 above)
Comment (westonpace) [reply cpp/src/arrow/acero/asof_join_node.cc:551]: "single call" might be a better description.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 2 above)
Comment (westonpace) [inline cpp/src/arrow/acero/asof_join_node.cc:554]: Does the `memo_.times_.empty()` value need to be obtained in a single call as well?

**Review by westonpace — COMMENTED** [review]
I think if I understand correctly you are saying that the value returned by `rhs.Empty` could change (from true to false I presume?) between the `UpdateRhs` call and the `IsUpToDateWithLhsRow` call and this becomes a logic bug?

It might be easier / simpler to wrap some part of `ProcessInner` in a mutex that is also wrapped around state modification done by the parts of the code that add data.  However, I realize that may have performance impact.

**Comment by zanmato1984** [comment]
> I think if I understand correctly you are saying that the value returned by `rhs.Empty` could change (from true to false I presume?) between the `UpdateRhs` call and the `IsUpToDateWithLhsRow` call and this becomes a logic bug?

Thank you Weston. Your presumption is correct. I've explained the issue in more detail in my previous reply to Antoine.
 
> It might be easier / simpler to wrap some part of `ProcessInner` in a mutex that is also wrapped around state modification done by the parts of the code that add data. However, I realize that may have performance impact.

Actually I was trying to fix it using mutex, here is a single-mutex version [`223951e` (#41614)](https://github.com/apache/arrow/pull/41614/commits/223951e031012e948027ce8d26f1ed3bb37cacf5) and a double-mutex version [`ade727e` (#41614)](https://github.com/apache/arrow/pull/41614/commits/ade727e68488aad1f34ea635800b1b579c5fe17a), both showing a up to 10% performance regression. This forces me to think of a lockless fix (the current one). But if the performance down is acceptable when code complexity is a consideration, I'm totally fine to go back to the mutex solution (maybe the double-mutex one is a fair tradeoff). Any recommendation?

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 2 above)
Comment (zanmato1984) [reply cpp/src/arrow/acero/asof_join_node.cc:554]: Honestly I can't tell for 100% sure. But from my understanding of the code so far, we are good. Unlike the race happening on the `queue_`, between on side being `Push` and the other being `Process`, the `memo_` seems only to be manipulated by the `Process` thread which is in good sync with itself.

File: cpp/src/arrow/acero/asof_join_node_test.cc (hunk 5 above)
Comment (zanmato1984) [reply cpp/src/arrow/acero/asof_join_node_test.cc:1713]: Addressed.

File: cpp/src/arrow/acero/asof_join_node_test.cc (hunk 4 above)
Comment (zanmato1984) [reply cpp/src/arrow/acero/asof_join_node_test.cc:1684]: Addressed.

Comment (zanmato1984) [reply cpp/src/arrow/acero/asof_join_node_test.cc:1684]: Addressed.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 3 above)
Comment (zanmato1984) [reply cpp/src/arrow/acero/asof_join_node.cc]: Addressed.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 2 above)
Comment (zanmato1984) [reply cpp/src/arrow/acero/asof_join_node.cc]: Addressed.

File: cpp/src/arrow/acero/asof_join_node.cc (hunk 1 above)
Comment (zanmato1984) [reply cpp/src/arrow/acero/asof_join_node.cc]: Changed to "single call". Thanks for suggesting the new naming.

**Review by westonpace — APPROVED** [review]
I'm happy with this fix once @pitrou is content.  Thanks for digging into these tricky issues.

File: cpp/src/arrow/acero/asof_join_node_test.cc (hunk 5 above)
Comment (pitrou) [reply cpp/src/arrow/acero/asof_join_node_test.cc:1713]: Thanks a lot!

**Review by pitrou — APPROVED** [review]
Thanks for the update @zanmato1984 !
