### PR TITLE
GH-39897: [C++][FS][S3] Ensure `AwsInstance::EnsureInitialized` to do initialization exactly once under concurrency

### LINKED ISSUE #39897: [C++] arrow::fs::FileSystemFromUri() not thread-safe with s3 URIs
### Describe the bug, including details regarding any error messages, version, and platform.

On MacOS, with Arrow version 15.0.0 and AWS SDK for C++ version 1.11.250, calling the C++ function `arrow::fs::FileSystemFromUri()` simultaneously from multiple threads results in a segmentation fault.

Here is a program that reproduces the problem on my machine:
```c++
#include <iostream>
#include <thread>
#include <arrow/api.h>
#include <arrow/filesystem/api.h>

void thread_main()
{
    // Call FileSystemFromURI() and check the returned status code.
    std::string path;
    auto result = arrow::fs::FileSystemFromUri("s3://bucket/key", &path);
    if (result.ok()){
        std::cout << std::this_thread::get_id() << ": FileSystemFromUri() succeeded." << std::endl;
    } else {
        std::cout << std::this_thread::get_id() << ": FileSystemFromUri() failed." << std::endl;
    }
}

int main()
{
    const int num_threads = 2;
    auto threads = std::vector<std::thread>();
    for (int i = 0; i < num_threads; i++)
    {
        threads.push_back(std::thread(thread_main));
    }

    for (auto &thread : threads)
    {
        thread.join();
    }

    // This line would prevent a segfault if the above code were to work.
    (void)arrow::fs::FinalizeS3();
}
```

This program should produce output like:
```
0x16eeeb000: FileSystemFromUri() succeeded.
0x16b5a7000: FileSystemFromUri() succeeded.
```

Instead, it experiences a segmentation fault before printing any output.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by Hastyshell**
### Rationale for this change

`FileSystemFromUri` could be called concurrently, and its implicit call to `AwsInstance::EnsureInitialized` will cause segment fault due to data race.

Therefore, make init stage thread-safe for `AwsInstance::EnsureInitialized`.

### What changes are included in this PR?

Serialize calls to S3 initialization to ensure initialization is done exactly once.

### Are these changes tested?

Yes, a test is added for the PyArrow bindings.

### Are there any user-facing changes?

No.

* Closes: #39897
* GitHub Issue: #39897

### CODE REVIEW

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 1]
```diff
@@ -2898,7 +2898,8 @@ struct AwsInstance {
     if (is_finalized_.load()) {
       return Status::Invalid("Attempt to initialize S3 after it has been finalized");
     }
-    if (!is_initialized_.exchange(true)) {
+    bool expected = false;
+    if (is_initialized_.compare_exchange_weak(expected, true)) {
```
Comment (kou) [inline cpp/src/arrow/filesystem/s3fs.cc:2902]: Hmm. I think that the second `EnsureS3Initialized()` call should be blocked when the first `EnsureS3Initialized()` is running. If the second `EnsureS3Initialized()` call isn't blocked, following `FileSystemFromUri()` will be failed.

Did you try a program provided in #39897?

I think that we need to do something like:

```diff
diff --git a/cpp/src/arrow/filesystem/s3fs.cc b/cpp/src/arrow/filesystem/s3fs.cc
index a987d63a6d..f89b5bdabd 100644
--- a/cpp/src/arrow/filesystem/s3fs.cc
+++ b/cpp/src/arrow/filesystem/s3fs.cc
@@ -3004,6 +3004,8 @@ Status InitializeS3(const S3GlobalOptions& options) {
 }
 
 Status EnsureS3Initialized() {
+  static std::mutex mutex;
+  std::lock_guard<std::mutex> lock(mutex);
   return EnsureAwsInstanceInitialized(S3GlobalOptions::Defaults()).status();
 }
```

Comment (TangSiyang2001) [reply cpp/src/arrow/filesystem/s3fs.cc:2902]: Thanks for your reviewing! I agree with you that I made a mistake. I'll modify it.

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 2]
```diff
@@ -3004,6 +3004,8 @@ Status InitializeS3(const S3GlobalOptions& options) {
 }
 
 Status EnsureS3Initialized() {
+  static std::mutex init_mutex;
+  std::lock_guard<std::mutex> l(init_mutex);
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs.cc:3008]: Why not put this in `AwsInstance`?

File: cpp/src/arrow/filesystem/s3fs_test.cc [hunk 3]
```diff
@@ -1272,6 +1272,30 @@ TEST_F(TestS3FS, FileSystemFromUri) {
   AssertFileInfo(fs.get(), path, FileType::File, 8);
 }
 
+TEST_F(TestS3FS, ConcurrentFSInit) {
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs_test.cc:1275]: Individual tests are not executed in separate process. The S3 subsystem is probably already initialized by the time this test is executed.

You could instead turn this into a Python test, where it's easier to spawn a subprocess.

File: cpp/src/arrow/filesystem/s3fs_test.cc [hunk 4]
```diff
@@ -1272,6 +1272,30 @@ TEST_F(TestS3FS, FileSystemFromUri) {
...
+  auto threads = std::vector<std::thread>();
+  for (int i = 0; i < num_threads; i++) {
+    threads.emplace_back(test_thread);
+  }
+
+  for (auto& thread : threads) {
+    thread.join();
+  }
+
+  static_cast<void>(FinalizeS3());
```
Comment (pitrou) [inline cpp/src/arrow/filesystem/s3fs_test.cc:1296]: This may break subsequent tests?

**Review by pitrou — CHANGES_REQUESTED** [review]

File: cpp/src/arrow/filesystem/s3fs.cc (hunk 2 above)
Comment (pitrou) [reply cpp/src/arrow/filesystem/s3fs.cc:3008]: Also, note that the idiomatic way of doing this would be https://en.cppreference.com/w/cpp/thread/call_once , but it probably does not matter much.

Comment (TangSiyang2001) [reply cpp/src/arrow/filesystem/s3fs.cc:3008]: > Why not put this in `AwsInstance`?

Thanks for your reviewing @pitrou! Cuz only `EnsureS3Initialized()` will be called implicitly by `FileSystemFromUri`, I guess it was also the reason why @kou suggested to put it here in the former comment. However, put this in `AwsInstance` does actually make it more uniformed.

> Also, note that the idiomatic way of doing this would be https://en.cppreference.com/w/cpp/thread/call_once , but it probably does not matter much.

Yes it better to use  `std::call_once` here, I'll change it to that way.

File: cpp/src/arrow/filesystem/s3fs_test.cc (hunk 3 above)
Comment (TangSiyang2001) [reply cpp/src/arrow/filesystem/s3fs_test.cc:1275]: Yes, I notice that  S3 subsystem actually is set up when S3Environment is set up. I'll make a python test case instead.

**Comment by TangSiyang2001** [comment]
@pitrou Problems have been solved, PTAL, ths.

File: cpp/src/arrow/filesystem/s3fs.cc [hunk 5]
```diff
@@ -2979,6 +2980,7 @@ struct AwsInstance {
   Aws::SDKOptions aws_options_;
   std::atomic<bool> is_initialized_;
```
Comment (kou) [inline cpp/src/arrow/filesystem/s3fs.cc:2981]: Can we remove `std::atomic<>`?

```suggestion
  bool is_initialized_;
```

Comment (TangSiyang2001) [reply cpp/src/arrow/filesystem/s3fs.cc:2981]: I think couldn't cuz is_initialized_ is exposed in AwsInstance::IsInitialized and in use.

**Review by pitrou — APPROVED** [review]
Thanks a lot @TangSiyang2001 . I've done a couple minor additions and will merge if CI is green.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel

**Comment by pitrou** [comment]
Rebased to get working PyArrow Windows builds.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel

**Comment by TangSiyang2001** [comment]
> Thanks a lot @TangSiyang2001 . I've done a couple minor additions and will merge if CI is green.

Thanks a lot for your reviews and comments @pitrou @kou , I will continue to try to familiarize myself with Arrow and enhance my skills to do more contribution with better quality.
