### PR TITLE
GH-38697: [C++][Gandiva] Use arrow io util to replace std::filesystem::path in gandiva

### LINKED ISSUE #38697: [C++][Gandiva] AlmaLinux 8 CI build failed due to `std::filesystem::path` usage
### Describe the bug, including details regarding any error messages, version, and platform.

`std::filesystem::path` has a problem on AlmaLinux 8: verify-rc-source-cpp-linux-almalinux-8-amd64

And we may have to replace the usage of `std::filesystem::path` with arrow's internal io_util.

https://lists.apache.org/thread/rbfqs9fzy66rv509wjx5j10z5ygqvvnx

https://github.com/ursacomputing/crossbow/actions/runs/6840785973/job/18600423664#step:6:8858

```
FAILED: release/gandiva-internals-test 
: && /usr/bin/c++ -Wno-noexcept-type  -fdiagnostics-color=always  -Wall -fno-semantic-interposition -msse4.2  -O3 -DNDEBUG -O2 -ftree-vectorize  src/gandiva/CMakeFiles/gandiva-internals-test.dir/bitmap_accumulator_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/engine_llvm_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/function_registry_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/function_signature_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/llvm_types_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/llvm_generator_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/annotator_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/tree_expr_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/encrypt_utils_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/expr_decomposer_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/exported_funcs_registry_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/expression_registry_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/selection_vector_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/lru_cache_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/to_date_holder_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/simple_arena_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/regex_functions_holder_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/decimal_type_util_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/random_generator_holder_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/hash_utils_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/gdv_function_stubs_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/interval_holder_test.cc.o src/gandiva/CMakeFiles/gandiva-internals-test.dir/tests/test_util.cc.o -o release/gandiva-internals-test  -Wl,-rpath,/tmp/arrow-HEAD.tNBaF/cpp-build/release  release/libgandiva.so.1500.0.0  release/libarrow_testing.so.1500.0.0  release/libarrow.so.1500.0.0  /usr/lib64/libcrypto.so  /usr/lib64/libssl.so  brotli_ep/src/brotli_ep-install/lib/libbrotlienc-static.a  brotli_ep/src/brotli_ep-install/lib/libbrotlidec-static.a  brotli_ep/src/brotli_ep-install/lib/libbrotlicommon-static.a  orc_ep-install/lib/liborc.a  protobuf_ep-install/lib/libprotobuf.a  utf8proc_ep-install/lib/libutf8proc.a  re2_ep-install/lib/libre2.a  -ldl  release/libarrow_gmock.so.1.11.0  release/libarrow_gtest_main.so.1.11.0  -ldl  utf8proc_ep-install/lib/libutf8proc.a  /usr/lib64/libcrypto.so  lz4_ep-install/lib/liblz4.a  /usr/lib64/libz.so  snappy_ep/src/snappy_ep-install/lib/libsnappy.a  jemalloc_ep-prefix/src/jemalloc_ep/dist//lib/libjemalloc_pic.a  -lrt  /usr/lib64/libzstd.so  release/libarrow_gtest.so.1.11.0  -pthread  /usr/lib64/libLLVM-15.so && :
src/gandiva/CMakeFiles/gandiva-internals-test.dir/tests/test_util.cc.o: In function `gandiva::GetTestFunctionLLVMIRPath[abi:cxx11]()':
test_util.cc:(.text+0x420): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
test_util.cc:(.text+0x46f): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
test_util.cc:(.text+0x621): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
test_util.cc:(.text+0x7d4): undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
test_util.cc:(.text+0x85a): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
```

### Notes
Some background info can be found in this PR: https://github.com/apache/arrow/pull/38677

### Component(s)

C++ - Gandiva

### PR DESCRIPTION
**Pull request by niyue**
### Rationale for this change
AlmaLinux 8 CI reported linker failure when `std::filesystem::path` is used, and This PR tries to it.

### What changes are included in this PR?
Replace `std::filesystem::path` in Gandiva with Arrow's internal io util so that AlmaLinux 8 CI build can work.

### Are these changes tested?
It should be covered by existing tests and CI.

### Are there any user-facing changes?
No
* Closes: #38697

### CODE REVIEW

File: cpp/src/gandiva/tests/test_util.cc [hunk 1]
```diff
@@ -17,22 +17,20 @@
...
 #include "gandiva/tests/test_util.h"
 
-#include <filesystem>
+#include "arrow/util/io_util.h"
 
 namespace gandiva {
 std::shared_ptr<Configuration> TestConfiguration() {
-  auto builder = ConfigurationBuilder();
-  return builder.DefaultConfiguration();
+  return ConfigurationBuilder::DefaultConfiguration();
```
Comment (niyue) [inline cpp/src/gandiva/tests/test_util.cc:24]: Previously this `DefaultConfiguration` function is called by creating a new instance of `ConfigurationBuilder`, but I think this is not necessary since it is a static function of `ConfigurationBuilder`, so I change it as well.

**Comment by pitrou** [comment]
> This PR tries to fix #38697

It would be better to make the PR description self-contained, can you update this?

**Comment by niyue** [comment]
> It would be better to make the PR description self-contained

Sure. Updated.

**Comment by js8544** [comment]
The AppVeyor check is still failing: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/48524728. `std::wstring` can't be constructed directly without encoding.
Perhaps we should use `PlatformFilename::FromString` and DCHECK the result instead?

**Comment by niyue** [comment]
> Perhaps we should use PlatformFilename::FromString and DCHECK the result instead?

Thanks for the suggestion. I took the approach and it did work. And Windows build should be okay now.

**Review by js8544 — APPROVED** [review]
+1. Thanks!

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit *almalinux*

File: cpp/src/gandiva/tests/test_util.cc [hunk 2]
```diff
@@ -17,22 +17,23 @@
...
 #define GANDIVA_EXTENSION_TEST_DIR "."
 #endif
 
 std::string GetTestFunctionLLVMIRPath() {
-  std::filesystem::path base(GANDIVA_EXTENSION_TEST_DIR);
-  std::filesystem::path ir_file = base / "multiply_by_two.bc";
-  return ir_file.string();
+  const auto base =
+      arrow::internal::PlatformFilename::FromString(GANDIVA_EXTENSION_TEST_DIR);
+  DCHECK(base.ok());
```
Comment (pitrou) [inline cpp/src/gandiva/tests/test_util.cc:35]:
```suggestion
  DCHECK_OK(base);
```

**Comment by pitrou** [comment]
Sorry for the misleading code suggestion. I've pushed a fix.

**Comment by niyue** [comment]
> Sorry for the misleading code suggestion
Sorry I should really verify this on my mac. I happened to use GitHub iOS app on the iPad yesterday night when I saw this, and I found the first time that the app provides a feature allowing me to apply the fix and resolve the conversation directly without opening any text editor so I gave it a try. Thanks for the fix.
