### PR TITLE
GH-37650: [Python] Check filter inputs in FilterMetaFunction

### LINKED ISSUE #37650: [Python] Passing table as argument to pyarrow.Table.filter causes segfault
### Describe the bug, including details regarding any error messages, version, and platform.

This is not correct code, but I did actually make this mistake and was puzzled for a while by the segfault (I thought I was passing a pyarrow.compute expression to filter)

```python
>>> import pyarrow as pa
>>> n_legs = pa.array([2, 4, 5, 100])
>>> animals = pa.array(["Flamingo", "Horse", "Brittle stars", "Centipede"])
>>> names = ["n_legs", "animals"]
>>> tbl = pa.Table.from_arrays([n_legs, animals], names=names)
>>> tbl.filter(tbl)  # meant to pass an pyarrow.compute.filter here
Segmentation fault (core dumped)
```

A gdb backtrace shows the following steps:

```sh
#0  0x00007ffff5e5cfde in arrow::compute::internal::(anonymous namespace)::FilterMetaFunction::ExecuteImpl(std::vector<arrow::Datum, std::allocator<arrow::Datum> > const&, arrow::compute::FunctionOptions const*, arrow::compute::ExecContext*) const ()
   from /home/willayd/mambaforge/envs/scratchpad/lib/python3.11/site-packages/pyarrow/../../../libarrow.so.1200
#1  0x00007ffff5d45d22 in arrow::compute::MetaFunction::Execute(std::vector<arrow::Datum, std::allocator<arrow::Datum> > const&, arrow::compute::FunctionOptions const*, arrow::compute::ExecContext*) const ()
   from /home/willayd/mambaforge/envs/scratchpad/lib/python3.11/site-packages/pyarrow/../../../libarrow.so.1200
#2  0x00007fff8c91ea26 in __pyx_pf_7pyarrow_8_compute_8Function_6call(__pyx_obj_7pyarrow_8_compute_Function*, _object*, __pyx_obj_7pyarrow_8_compute_FunctionOptions*, __pyx_obj_7pyarrow_3lib_MemoryPool*, _object*) ()
   from /home/willayd/mambaforge/envs/scratchpad/lib/python3.11/site-packages/pyarrow/_compute.cpython-311-x86_64-linux-gnu.so
#3  0x00005555557614c6 in method_vectorcall_VARARGS_KEYWORDS (func=<optimized out>, args=<optimized out>, nargsf=<optimized out>, 
    kwnames=<optimized out>) at /usr/local/src/conda/python-3.11.0/Objects/descrobject.c:364
#4  0x000055555574bec1 in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, 
    callable=0x7fff8ca66fc0, tstate=0x555555ae0d98 <_PyRuntime+166328>) at /usr/local/src/conda/python-3.11.0/Include/internal/pycore_call.h:92
#5  PyObject_Vectorcall (callable=0x7fff8ca66fc0, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.11.0/Objects/call.c:299
#6  0x000055555574169e in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>)
    at /usr/local/src/conda/python-3.11.0/Python/ceval.c:4772
#7  0x0000555555767e81 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff7fb5080, tstate=0x555555ae0d98 <_PyRuntime+166328>)
    at /usr/local/src/conda/python-3.11.0/Include/internal/pycore_ceval.h:73
#8  _PyEval_Vector (kwnames=<optimized out>, argcount=3, args=<optimized out>, locals=0x0, func=0x7fff8c824540, 
    tstate=0x555555ae0d98 <_PyRuntime+166328>) at /usr/local/src/conda/python-3.11.0/Python/ceval.c:6428
#9  _PyFunction_Vectorcall (func=0x7fff8c824540, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.11.0/Objects/call.c:393
#10 0x00007ffff6ea0411 in __Pyx_PyObject_Call(_object*, _object*, _object*) ()
   from /home/willayd/mambaforge/envs/scratchpad/lib/python3.11/site-packages/pyarrow/lib.cpython-311-x86_64-linux-gnu.so
#11 0x00007ffff6f34c0d in __pyx_pw_7pyarrow_3lib_5Table_19filter(_object*, _object*, _object*) ()
   from /home/willayd/mambaforge/envs/scratchpad/lib/python3.11/site-packages/pyarrow/lib.cpython-311-x86_64-linux-gnu.so
```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by p-a-a-a-trick**
### Rationale for this change
Prevent a segfault upon passing a non-(chunked_)array object into `Table.filter`. See #37650.

### What changes are included in this PR?
1. Check filter Datum kind to make sure that it is an array or a chunked array
2. test that attempting to filter a table with another table raises a not implemented error

### Are these changes tested?
In PyArrow, yes

### Are there any user-facing changes?
Raises an error if a non-array or non-chunked_array object is passed into `Table.filter`

* Closes: #37650

### CODE REVIEW

**Comment by p-a-a-a-trick** [comment]
@github-actions autotune

File: cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc [hunk 1]
```diff
@@ -998,6 +998,11 @@ class FilterMetaFunction : public MetaFunction {
   Result<Datum> ExecuteImpl(const std::vector<Datum>& args,
                             const FunctionOptions* options,
                             ExecContext* ctx) const override {
+    if ((args[1].kind() != Datum::ARRAY) &&
+        (args[1].kind() != Datum::CHUNKED_ARRAY)) {
+        return Status::NotImplemented("Filter should be array-like");
```
Comment (pitrou) [inline cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc:1003]: Can we make this `TypeError`?

File: python/pyarrow/tests/test_table.py [hunk 2]
```diff
@@ -2302,6 +2302,9 @@ def test_table_filter_expression():
         "colVals": ["a", "b", "f", "B", "A"]
     })
 
+    with pytest.raises(NotImplementedError):
+        result = t1.filter(t2)
```
Comment (pitrou) [inline python/pyarrow/tests/test_table.py:2306]: The tests need not depend on Acero, perhaps it should be added to `test_compute.py` instead?

**Review by pitrou — CHANGES_REQUESTED** [review]
Thanks for noticing this. The fix LGTM on the principle, just two minor suggestions.

File: cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc (hunk 1 above)
Comment (p-a-a-a-trick) [reply cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc:1003]: Sounds good to me. I got this from [L945](https://github.com/apache/arrow/blob/ae16bde4b36fe5a404c8ca22fab769db0d652543/cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc#L945). Should change that one as well?

Comment (pitrou) [reply cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc:1003]: Yes, definitely.

Comment (p-a-a-a-trick) [reply cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc:1002]: Okay, changing and updating the tests in pyarrow that need updating (I don't know if this will affect downstream tests for other subprojects)

Comment (p-a-a-a-trick) [reply cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc]: Looks like it didn't affect anything on the pyarrow/pytest side of things. Changed!

**Review by pitrou — APPROVED** [review]
+1, thank you @p-a-a-a-trick . I fixed the C++ formatting and improved the test slightly.

**Comment by pitrou** [comment]
CI failures are unrelated.
