### PR TITLE
GH-40053: [Python] Preserve dict key order when inferring struct type

### LINKED ISSUE #40053: [Python] `pa.array(<pd.Series of structs>)` changes field order to be sorted
### Describe the bug, including details regarding any error messages, version, and platform.

If I give a column of structs, then pyarrow seems to sort the fields by name. I would expect the field order to be preserved.

```python
import pandas as pd
import pyarrow as pa

print(pa.__version__)
# 15.0.0

s = pd.Series([{"b": 2, "a": 1}, {"b": 4, "a": 3}])
a = pa.array(s)
print(a.type)
# struct<a: int64, b: int64>
```

This was discovered in https://github.com/ibis-project/ibis/issues/8166

### Component(s)

Python

### PR DESCRIPTION
**Pull request by gabrielsimoes**
### Rationale for this change

Fixes https://github.com/apache/arrow/issues/40053

When converting Python dictionaries to PyArrow arrays, struct fields are sorted alphabetically instead of preserving the original dictionary key insertion order. Since Python 3.7+, dictionaries maintain insertion order, and users expect this order to be preserved.

```python
>>> import pyarrow as pa
>>> pa.array([{"b": 2, "a": 1}]).type
struct<a: int64, b: int64>
```

Expected: `struct<b: int64, a: int64>`

### What changes are included in this PR?

Replace `std::map<std::string, TypeInferrer>` with `std::vector<std::pair<std::string, TypeInferrer>>` + `std::unordered_map<std::string, size_t>` in the type inference code. This follows the same pattern used in the JSON parser (`cpp/src/arrow/json/parser.cc`) for the same problem.

### Are these changes tested?

Updated existing tests to verify field ordering.

### Are there any user-facing changes?

Struct field order now matches dictionary key insertion order instead of being sorted alphabetically. This is a behavioral change but aligns with user expectations and Python semantics.

* GitHub Issue: #40053

### CODE REVIEW

File: python/pyarrow/src/arrow/python/inference.cc [hunk 1]
```diff
@@ -704,15 +704,19 @@ class TypeInferrer {
...
-                                                      validate_interval_, make_unions_)))
-                 .first;
+      TypeInferrer* visitor;
+      auto it = struct_field_index_.find(key);
+      if (it == struct_field_index_.end()) {
+        // New field - add to vector and index
+        size_t new_index = struct_inferrers_.size();
+        struct_inferrers_.emplace_back(
+            key, TypeInferrer(pandas_null_sentinels_, validate_interval_, make_unions_));
+        struct_field_index_.emplace(key, new_index);
```
Comment (pitrou) [inline python/pyarrow/src/arrow/python/inference.cc]: We can perhaps save a copy here, though probably not very important.
```suggestion
        struct_field_index_.emplace(std::move(key), new_index);
```

File: python/pyarrow/tests/test_convert_builtin.py [hunk 2]
```diff
@@ -71,10 +71,10 @@ def __int__(self):
 
 def check_struct_type(ty, expected):
```
Comment (pitrou) [inline python/pyarrow/tests/test_convert_builtin.py]: AFAICT, this function was only necessary because we wanted to ignore field order. So now all call sites could use an equality assertion between types directly?

File: python/pyarrow/tests/test_convert_builtin.py [hunk 3]
```diff
@@ -2014,21 +2014,25 @@ def test_struct_from_dicts_inference():
...
+                {'a': None, 'c': None, 'b': None},
+                {'a': None, 'c': None, 'b': 'bar'}]
 
     arr = pa.array(data)
     data_as_ndarray = np.empty(len(data), dtype=object)
     data_as_ndarray[:] = data
     arr2 = pa.array(data)
 
-    check_struct_type(arr.type, expected_type)
+    check_struct_type(arr.type, expected_type_omitted)
```
Comment (pitrou) [inline python/pyarrow/tests/test_convert_builtin.py]: For example this could be replaced with:

```suggestion
    assert arr.type == expected_type_omitted
```

File: python/pyarrow/tests/test_convert_builtin.py
Comment (pitrou) [inline python/pyarrow/tests/test_convert_builtin.py:2042]: How about we also add a type check here too?

File: python/pyarrow/tests/test_convert_builtin.py [hunk 4]
```diff
@@ -2054,6 +2058,23 @@ def test_struct_from_dicts_inference():
         pa.array([1, {'a': 2}])
 
 
+def test_struct_from_dicts_field_order():
```
Comment (pitrou) [inline python/pyarrow/tests/test_convert_builtin.py]: Is this test doing something different from `test_struct_from_dicts_inference` above?

**Review by pitrou — COMMENTED** [review]
Thanks for the PR @gabrielsimoes ! The solution looks good in general, here are some relatively minor comments.

File: python/pyarrow/tests/test_convert_builtin.py (hunk 4 above)
Comment (gabrielsimoes) [reply python/pyarrow/tests/test_convert_builtin.py]: Nothing substantially different; I've removed it in favor of the other test.

**Comment by gabrielsimoes** [comment]
Thanks for the speedy review @pitrou; I have addressed them and the linter/doctest CI failures.

**Review by pitrou — APPROVED** [review]
This looks ok to me, thank you @gabrielsimoes . I'll wait for CI to pass and then I think we can merge.
