### PR TITLE
GH-34633: [C++][Parquet] Fix StreamReader to read decimals

### LINKED ISSUE #34633: [C++][Parquet] Can't read converted type DECIMAL in Parquet Stream Reader C++ API
### Describe the bug, including details regarding any error messages, version, and platform.

I'm trying to read the following field in a parquet file using the Stream Reader C++ API (I didn't create the parquet file):

Schema output:
```text
optional fixed_len_byte_array(16) field_id=-1 processstarted_seconds (Decimal(precision=38, scale=18));
```

```c++
// code
optional<std::array<char, 16>> processstarted_seconds;
... 
stream_reader >> columns_obj.processstarted_seconds;
// code
```

When I run the above code, I get the following runtime error message:
```text
what():  Column converted type mismatch.  Column 'processstarted_seconds' has converted type 'DECIMAL' not 'NONE'
```

The error is originating here: https://github.com/apache/arrow/blob/main/cpp/src/parquet/stream_reader.cc#L158

Note that I'm able to read the FIXED_LEN_BYTE_ARRAY type with parquet::ConvertedType::NONE. For example, the following works fine.
Schema output:
```text
optional fixed_len_byte_array(4) field_id=-1 country_char[4];
```

I'm using Arrow-Parquet C++ v9.0.0.

Thanks for your help.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

StreamReader only supports reading decimals from int32 and int64. User cannot read decimals from FIXED_LENGTH_BYTE_ARRAY or BYTE_ARRAY.

### What changes are included in this PR?

Support StreamReader to read decimals via arrow::Decimal128 type.

### Are these changes tested?

Added two test cases to read them.

### Are there any user-facing changes?

Yes, now user can directly use arrow::Decimal128 to read from parquet file.
* Closes: #34633

### CODE REVIEW

**Comment by wgtmac** [comment]
@wjones127 @westonpace Could you help review this? Thanks!

File: cpp/src/parquet/stream_reader_test.cc [hunk 1]
```diff
@@ -912,5 +913,39 @@ TEST_F(TestReadingDataFiles, Int64Decimal) {
...
 
+TEST_F(TestReadingDataFiles, FLBADecimal) {
+  PARQUET_ASSIGN_OR_THROW(auto infile, ::arrow::io::ReadableFile::Open(
+                                           GetDataFile("fixed_length_decimal.parquet")));
+
+  auto file_reader = ParquetFileReader::Open(infile);
+  auto reader = StreamReader{std::move(file_reader)};
+
+  ::arrow::Decimal128 x;
+  int i;
```
Comment (mapleFU) [inline cpp/src/parquet/stream_reader_test.cc:924]: `int i = 0;` to avoid reader already eof, and `i` is undefined?

Comment (wgtmac) [reply cpp/src/parquet/stream_reader_test.cc:924]: I just follow the same pattern of previous cases. These files are well-defined so i will always be updated.

File: cpp/src/parquet/stream_reader.cc [hunk 2]
```diff
@@ -173,6 +174,60 @@ StreamReader& StreamReader::operator>>(std::string& v) {
   return *this;
 }
 
+StreamReader& StreamReader::operator>>(::arrow::Decimal128& v) {
```
Comment (westonpace) [inline cpp/src/parquet/stream_reader.cc:177]: Is there anyway to avoid repeating the implementation here?  For example, would something like this work?

```
StreamReader& StreamReader::operator>>(::arrow::Decimal128& v) {
  std::optional<::arrow::Decimal128> maybe_v;
  this >> maybe_v;
  if (!maybe_v) {
    // I'm not sure what happens here, maybe throw an exception?
  }
  v = *maybe_v;
  return this;
}
```

File: cpp/src/parquet/stream_reader_test.cc [hunk 3]
```diff
@@ -912,5 +913,39 @@ TEST_F(TestReadingDataFiles, Int64Decimal) {
...
+
+  auto file_reader = ParquetFileReader::Open(infile);
+  auto reader = StreamReader{std::move(file_reader)};
+
+  ::arrow::Decimal128 x;
+  int i = 0;
+
+  for (i = 1; !reader.eof(); ++i) {
+    reader >> x >> EndRow;
+    EXPECT_EQ(x.ToString(2), ::arrow::Decimal128(i * 100).ToString(2));
```
Comment (westonpace) [inline cpp/src/parquet/stream_reader_test.cc:928]: Why `ToString`.  Can't we compare the decimals directly?

**Review by westonpace — COMMENTED** [review]
Nice addition.  I'm a little unfamiliar with this code so these questions may be silly.

File: cpp/src/parquet/stream_reader.cc (hunk 2 above)
Comment (wgtmac) [reply cpp/src/parquet/stream_reader.cc]: Tried to reuse code and throw if it is null.

File: cpp/src/parquet/stream_reader_test.cc (hunk 3 above)
Comment (wgtmac) [reply cpp/src/parquet/stream_reader_test.cc]: Double checked that decimal128 does not have scale. Changed it into comparing decimals directly.

**Review by westonpace — APPROVED** [review]
Thanks for this addition!
