### PR TITLE
GH-35618: [C++][Doc] Improve doc for Datum

### LINKED ISSUE #35618: [C++][Doc] arrow::compute::Datum is under-documented
### Describe the bug, including details regarding any error messages, version, and platform.

This is a pretty essential class but the documentation is extremely sparse and several key functions are missing. For an example of the confusion, see the comments on [this post](https://stackoverflow.com/questions/76246751/how-to-retrieve-an-array-instead-of-arraydata-from-a-compute-function-with-recor/76256639#76256639). 

### Component(s)

C++

### PR DESCRIPTION
**Pull request by js8544**
Improve doc for `Datum` to avoid confusion as documented in the coresponding issue.
* Closes: #35618

### CODE REVIEW

File: cpp/src/arrow/datum.h [hunk 1]
```diff
@@ -43,14 +43,18 @@ class Table;
...
   struct Empty {};
 
-  // Datums variants may have a length. This special value indicate that the
-  // current variant does not have a length.
+  /// \brief Datums variants may have a length. This special value indicate that the
+  /// current variant does not have a length.
   static constexpr int64_t kUnknownLength = -1;
 
+  /// \brief Storage of the actual datum. Note: For arrays, it stores ArrayData instead of
+  /// Array for easier data processing
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:57]: Let's keep the brief summary brief and move the rest to the longer description section?
```suggestion
  /// \brief Storage of the actual datum.
  ///
  /// Note: For arrays, ArrayData is stored instead of Array for easier processing
```

File: cpp/src/arrow/datum.h [hunk 2]
```diff
@@ -64,69 +68,102 @@ struct ARROW_EXPORT Datum {
...
-  // Explicit constructors from const-refs. Can be expensive, prefer the
-  // shared_ptr constructors
+  /// \brief Construct from a RecordBatch
+  Datum(std::shared_ptr<RecordBatch> value);  // NOLINT implicit conversion
+
+  /// \brief Construct from a Table
+  Datum(std::shared_ptr<Table> value);  // NOLINT implicit conversion
+
+  /// \brief Construct from a ChunkedArray. Can be expensive, prefer the
+  /// shared_ptr constructor
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:99]:
```suggestion
  /// \brief Construct from a ChunkedArray.
  ///
  /// This can be expensive, prefer the shared_ptr<ChunkedArray> constructor
```

File: cpp/src/arrow/datum.h [hunk 3]
```diff
@@ -64,69 +68,102 @@ struct ARROW_EXPORT Datum {
...
   explicit Datum(const ChunkedArray& value);
+
+  /// \brief Construct from a RecordBatch. Can be expensive, prefer the
+  /// shared_ptr constructor
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:103]: (same kind of suggestion here and below)

File: cpp/src/arrow/datum.h [hunk 4]
```diff
@@ -64,69 +68,102 @@ struct ARROW_EXPORT Datum {
...
   explicit Datum(const RecordBatch& value);
+
+  /// \brief Construct from a Table. Can be expensive, prefer the
+  /// shared_ptr constructor
   explicit Datum(const Table& value);
 
-  // Cast from subtypes of Array or Scalar to Datum
+  /// \brief Cast from concrete types of Array or Scalar to Datum
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:110]: "subtypes" rather than "types"?

File: cpp/src/arrow/datum.h [hunk 5]
```diff
@@ -64,69 +68,102 @@ struct ARROW_EXPORT Datum {
...
   template <typename T, typename TV = typename std::remove_reference_t<T>,
             bool IsArray = std::is_base_of_v<Array, T>,
             bool IsScalar = std::is_base_of_v<Scalar, T>,
             typename = enable_if_t<IsArray || IsScalar>>
   Datum(T&& value)  // NOLINT implicit conversion
       : Datum(std::make_shared<TV>(std::forward<T>(value))) {}
 
-  // Many Scalars are copyable, let that happen
+  /// \brief Copy from concrete types of Scalar. The scalar type must copyable.
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:126]:
```suggestion
  /// \brief Copy from concrete types of Scalar.
  /// 
  /// The concrete scalar type must be copyable (not all of them are).
```

File: cpp/src/arrow/datum.h [hunk 6]
```diff
@@ -64,69 +68,102 @@ struct ARROW_EXPORT Datum {
...
   template <typename T, typename = enable_if_t<std::is_base_of_v<Scalar, T>>>
   Datum(const T& value)  // NOLINT implicit conversion
       : Datum(std::make_shared<T>(value)) {}
 
   // Convenience constructors
+  /// \brief A convenience constructor. Stores a bool scalar.
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:132]:
```suggestion
  /// \brief Convenience constructor storing a bool scalar.
```

File: cpp/src/arrow/datum.h [hunk 7]
```diff
@@ -146,6 +183,8 @@ struct ARROW_EXPORT Datum {
     }
   }
 
+  /// \brief Retrieve the stored array as ArrayData, use make_array() if Array is desired
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:186]:
```suggestion
  /// \brief Retrieve the stored array as ArrayData
  /// 
  /// Use make_array() if an Array is desired (which is more expensive).
```

File: cpp/src/arrow/datum.h [hunk 8]
```diff
@@ -155,49 +194,74 @@ struct ARROW_EXPORT Datum {
   /// \see arrow::util::TotalBufferSize for caveats
   int64_t TotalBufferSize() const;
 
+  /// \brief Get the stored ArrayData in mutable form, primarily used in kernel
+  /// implementations
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:198]:
```suggestion
  /// \brief Get the stored ArrayData in mutable form
  /// 
  /// For internal use primarily. Keep in mind a shared_ptr<Datum> may have multiple owners.
```

File: cpp/src/arrow/datum.h [hunk 9]
```diff
@@ -155,49 +194,74 @@ struct ARROW_EXPORT Datum {
...
     return this->kind() == Datum::ARRAY || this->kind() == Datum::CHUNKED_ARRAY;
   }
 
+  /// \brief True if Datum contains a scalar
   bool is_scalar() const { return this->kind() == Datum::SCALAR; }
 
   /// \brief True if Datum contains a scalar or array-like data
   bool is_value() const { return this->is_arraylike() || this->is_scalar(); }
 
+  /// \brief Returns the null count. Only valid for scalar and array-like data
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:264]:
```suggestion
  /// \brief Return the null count.
  ///
  /// Only valid for scalar and array-like data.
```

File: cpp/src/arrow/datum.h [hunk 10]
```diff
@@ -220,11 +284,13 @@ struct ARROW_EXPORT Datum {
   /// \return empty if not arraylike
   ArrayVector chunks() const;
 
+  /// \brief True if the two data are equal
   bool Equals(const Datum& other) const;
 
   bool operator==(const Datum& other) const { return Equals(other); }
   bool operator!=(const Datum& other) const { return !Equals(other); }
 
+  /// \brief Print the kind of datum stored
```
Comment (pitrou) [inline cpp/src/arrow/datum.h:293]:
```suggestion
  /// \brief Return a string representation of the kind of datum stored.
```

**Comment by pitrou** [comment]
Thanks for doing this @js8544 ! I posted some small suggestions for style and accuracy.

File: cpp/src/arrow/datum.h (hunk 4 above)
Comment (js8544) [reply cpp/src/arrow/datum.h:114]: done

**Comment by js8544** [comment]
> Thanks for doing this @js8544 ! I posted some small suggestions for style and accuracy.

Thanks for the feedback! I've updated the doc.

**Comment by pitrou** [comment]
CI failures are unrelated, will merge.
