### PR TITLE
GH-33475: [Java] Add parameter binding for Prepared Statements in JDBC driver

### LINKED ISSUE #33475: [Java][FlightRPC] FlightSQL error: 'Parameter ordinal out of range' executing a prepared stmt with params
Hey again :) 

I'm getting a 'parameter ordinal 1 out of range' error trying to set a parameter on the returned AvaticaPreparedStatement. Repro:

- Open a FlightSQL JDBC connection
- `conn.prepareStatement` with a SQL query containing params (e.g. `INSERT INTO users (id, name) VALUES (?, ?)`)
- `ps.setString(1, "foo")` -> above error, thrown from `AvaticaPreparedStatement.getParameter(int)`
  
  I had a bit of a dig to try to identify a potential cause:
- the `Meta.Signature` passed to the `AvaticaPreparedStatement` on creation has an empty parameter list - this is what causes the out-of-bounds error.
-  in `ArrowFlightMetaImpl.prepare`, it calls `newSignature`, but this only takes the SQL query, and so `newSignature` creates the signature with the empty list. The call to `ArrowFlightSqlClientHandler.prepare` happens on the line after - could we pass the param Schema from this result to `newSignature`?
  
  Let me know if I can help narrow this down further or help with the fix :)
  
  James

**Reporter**: [James Henderson](https://issues.apache.org/jira/browse/ARROW-18300) / @jarohen
**Assignee**: [David Li](https://issues.apache.org/jira/browse/ARROW-18300) / @lidavidm
#### PRs and other links:
- [GitHub Pull Request #14627](https://github.com/apache/arrow/pull/14627)

<sub>**Note**: *This issue was originally created as [ARROW-18300](https://issues.apache.org/jira/browse/ARROW-18300). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #35536: [Java] ArrowFlightPreparedStatement is missing dynamic parameters
### Describe the bug, including details regarding any error messages, version, and platform.

Hi Sir/Madam,

I noticed that ArrowFlightPreparedStatement doesn't have the dynamic parameters from flight server. (for example, `SELECT * FROM where f1 = ? or f2 = ?`)
[ArrowFlightPreparedStatement#createNewPreparedStatement](https://github.com/apache/arrow/blob/eaa1a1ea74e2b37020e0133f1460cb251e5f4974/java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatement.java#L76)

This method only populates `signature.columns`  and doesn't populate `signature.parameters`, the client side couldn't do `preparedStmt.setByte(1, 0)`

Could you verify if it's a bug? 

### Component(s)

Java

### PR DESCRIPTION
**Pull request by aiguofer**
This PR is a combination of apache/arrow#33961 and apache/arrow#14627. The goal is to support parametrized queries through the Arrow Flight SQL JDBC driver.

An Arrow Flight SQL server returns a Schema for the `PreparedStatement` parameters. The driver then converts the `Field` list associated with the Schema into a list of `AvaticaParameter`. When the user sets values for the parameters, Avatica generates a list of `TypedValue`, which we then bind to each parameter vector. This conversion between Arrow and Avatica is handled by implementations of a `AvaticaParameterConverter` interface for each Arrow type. This interface which provides 2 methods:
- createParameter: Create an `AvaticaParameter` from the given Arrow `Field`.
- bindParameter: Cast the given `TypedValue` and bind it to the `FieldVector` at the specified index.

This PR purposely leaves out a few features:
- We currently naively cast the `TypedValue` values assuming users set the type correctly. If this cast fails, we raise an exception letting the user know that the cast is not supported. This could be improved in subsequent PRs to do smarter conversions from other types.
- We currently don't provide conversions for complex types such as List, Map, Struct, Union, Interval, and Duration. The stubs are there so they can be implemented as needed.
- Tests for specific types have not been implemented. I'm not very familiar with a lot of these JDBC types so it's hard to implement rigorous tets.

* Closes: apache/arrow#33475
* Closes: apache/arrow#35536
* GitHub Issue: #33475

### CODE REVIEW

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcFactory.java [hunk 1]
```diff
@@ -89,12 +86,6 @@ public ArrowFlightPreparedStatement newPreparedStatement(
     ArrowFlightSqlClientHandler.PreparedStatement preparedStatement =
         flightConnection.getMeta().getPreparedStatement(statementHandle);
 
-    if (preparedStatement == null) {
-      preparedStatement = flightConnection.getClientHandler().prepare(signature.sql);
-    }
-    final Schema resultSetSchema = preparedStatement.getDataSetSchema();
-    signature.columns.addAll(convertArrowFieldsToColumnMetaDataList(resultSetSchema.getFields()));
-
```
Comment (aiguofer) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcFactory.java:97]: `newPreparedStatement` only gets called by `AvaticaConnection.newPreparedStatement`:

```
  public PreparedStatement prepareStatement(
      String sql,
      int resultSetType,
      int resultSetConcurrency,
      int resultSetHoldability) throws SQLException {
    checkOpen();
    try {
      final Meta.StatementHandle h = meta.prepare(handle, sql, -1);
      return factory.newPreparedStatement(this, h, h.signature, resultSetType,
          resultSetConcurrency, resultSetHoldability);
    } catch (RuntimeException e) {
      throw HELPER.createException("while preparing SQL: " + sql, e);
    }
  }
```

The `columnMetaData` and `parameters` are already set up in `ArrowFlightMetaImpl.prepare` so there doesn't seem to be a reason to do this check again here.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatement.java [hunk 2]
```diff
@@ -50,36 +47,6 @@ private ArrowFlightPreparedStatement(final ArrowFlightConnection connection,
...
-    final ArrowFlightSqlClientHandler.PreparedStatement prepare = connection.getClientHandler().prepare(signature.sql);
-    final Schema resultSetSchema = prepare.getDataSetSchema();
-
-    signature.columns.addAll(ConvertUtils.convertArrowFieldsToColumnMetaDataList(resultSetSchema.getFields()));
-
-    return new ArrowFlightPreparedStatement(
-        connection, prepare, statementHandle,
-        signature, resultSetType, resultSetConcurrency, resultSetHoldability);
-  }
-
```
Comment (aiguofer) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatement.java:82]: Unused method.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+      case Date:
+        return Date.class.getCanonicalName();
+      case Time:
+        return Time.class.getCanonicalName();
+      case Timestamp:
+      case Interval:
+      case Duration:
+        return Timestamp.class.getCanonicalName();
+      default:
+        return null;
```
Comment (aiguofer) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:120]: Should I error instead?

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java [hunk 4]
```diff
@@ -349,8 +416,16 @@ public Runnable acceptPutPreparedStatementQuery(
...
+    final ByteString handle = commandPreparedStatementQuery.getPreparedStatementHandle();
+    final String query = Preconditions.checkNotNull(
+        preparedStatements.get(handle),
+        format("No query registered under handle: <%s>.", handle));
+
+    if (validateParameters(query, flightStream, streamListener)) {
+      return () -> { };
+    }
+
+    return streamListener::onCompleted;
```
Comment (aiguofer) [inline java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java:428]: Do we need to do anything else here? What exactly is the `streamListener` used for in `acceptPutPreparedStatementQuery`?

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java (hunk 3 above)
Comment (vibhatha) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:120]: Seems like it could be better. I looked into other scenarios where switch cases have been used with types and it seems that throwing an exception in the default have been done.

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:120]: I wonder if it would make sense to return `Object.class.getCanonicalName()`? I don't fully understand how this  gets used. From what I've been reading, this value would be used to determine the class of the object you'd like to set if you call `PreparedStatement.setObject` without specifying a type. However, you can also specify the type when you make the call.

I've never used `getObject` or `setObject` in JDBC so I'm not entirely sure how to best handle this scenario.

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:120]: Additionally, FWIW, these are the only types not covered:

```
    Null(Type.Null),
    Struct(Type.Struct_),
    Union(Type.Union),
    NONE(Type.NONE);
```

Comment (vibhatha) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:120]: Good point. I am not entirely sure about that bit too. 

@lidavidm appreciate your thoughts.

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:120]: hmm a thought for `Struct` is that the server could send along a class name as part of the Field metadata and default to `Object.class.getCanonicalName` if not given.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+      case Null:
+        return Types.NULL;
+      case Struct:
+        return Types.STRUCT;
+      case List:
+      case LargeList:
+      case FixedSizeList:
+        return Types.ARRAY;
+      case Int:
+        return ((ArrowType.Int) type).getBitWidth() == 64 ? Types.BIGINT : Types.INTEGER;
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:58]: Should this switch on getBitWidth() as well to return SmallInt and Tinyint?

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+
+import org.apache.arrow.vector.types.pojo.ArrowType;
+
+/**
+ * Helper class to convert Arrow types to JDBC required values.
+ */
+class ArrowToJdbcUtils {
+  static boolean isSigned(ArrowType type) {
+    switch (type.getTypeID()) {
+      case Int:
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:36]: This should depend on the integer subtype.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+      case Struct:
+        return Types.STRUCT;
+      case List:
+      case LargeList:
+      case FixedSizeList:
+        return Types.ARRAY;
+      case Int:
+        return ((ArrowType.Int) type).getBitWidth() == 64 ? Types.BIGINT : Types.INTEGER;
+      case FloatingPoint:
+        return Types.FLOAT;
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:60]: 32-bit floats are usually exposed as Types.REAL

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+      case LargeList:
+      case FixedSizeList:
+        return ArrayList.class.getCanonicalName();
+      case Map:
+        return HashMap.class.getCanonicalName();
+      case Int:
+        return ((ArrowType.Int) type).getBitWidth() == 64 ?
+                long.class.getCanonicalName() : int.class.getCanonicalName();
+      case FloatingPoint:
+        return float.class.getCanonicalName();
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:99]: This should depend on the float subtype (float vs double).

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java (hunk 3 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:120]: Yeah I think we should make this a property exposed by the TypeInfo catalog.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+      } else if (vector instanceof LargeVarBinaryVector) {
+        ((LargeVarBinaryVector) vector).setSafe(0, (byte[]) value);
+      } else if (vector instanceof NullVector) {
+        assert true;
+      } else {
+        throw new UnsupportedOperationException(
+                String.format("Binding to parameter of Arrow type %s", vector.getField().getType()));
+      }
+    } catch (ClassCastException e) {
+      throw new RuntimeException(String.format("Value of type %s is not compatible with Arrow type %s",
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:122]: This isn't truly an error. In JDBC, a user is allowed to bind to a different type that the server expects and the driver is supposed to do the conversion behind-the-scenes. This doesn't happen that often. Applications sometimes do this with integers where they use a 32-bit integer regardless of what type the server is expecting.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+        String pattern = "yyyy-MM-dd HH:mm:ss.SSS";
+        DateTime dateTime = DateTime.parse((String) value, DateTimeFormat.forPattern(pattern));
+
+        ((DateMilliVector) vector).setSafe(0, dateTime.getMillis());
+      } else if (vector instanceof VarBinaryVector) {
+        ((VarBinaryVector) vector).setSafe(0, (byte[]) value);
+      } else if (vector instanceof LargeVarBinaryVector) {
+        ((LargeVarBinaryVector) vector).setSafe(0, (byte[]) value);
+      } else if (vector instanceof NullVector) {
+        assert true;
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:116]: This doesn't seem right...

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+      } else {
+        throw new UnsupportedOperationException(
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:118]: Complex types such as Map, list, and struct aren't being covered here. We should report a different error for types that aren't yet implemented vs. types that are plain unrecognized.

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java (hunk 4 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java:428]: This is all for this MockFlightSqlProducer.
In a real server, this should bind parameters on multiple queries on the backend.
Se FlightSqlExample for how it'd work in practice.

File: java/flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java [hunk 12]
```diff
@@ -951,12 +951,11 @@ public static class PreparedStatement implements AutoCloseable {
      *                             {@code PreparedStatement} setters.
      */
     public void setParameters(final VectorSchemaRoot parameterBindingRoot) {
-      if (this.parameterBindingRoot != null) {
-        if (this.parameterBindingRoot.equals(parameterBindingRoot)) {
-          return;
-        }
-        this.parameterBindingRoot.close();
+      if (parameterBindingRoot.equals(this.parameterBindingRoot)) {
```
Comment (jduo) [inline java/flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java:954]: Is this right? Doesn't this do a deep vector comparison when you need a reference comparison here?

**Comment by jduo** [comment]
This is really great @aiguofer . I've added some inline code comments.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java [hunk 13]
```diff
@@ -0,0 +1,123 @@
...
+        return Types.BOOLEAN;
+      case Decimal:
+        return Types.DECIMAL;
+      case Date:
+        return Types.DATE;
+      case Time:
+        return Types.TIME;
+      case Timestamp:
+      case Interval:
+      case Duration:
```
[the remark this answers is not in the document]
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:79]: Yeah makes sense! I just copy pasted this bit, will adjust!

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java (hunk 7 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:60]: so something like `((ArrowType.FloatingPoint) type).getBitWidth() == 32 ? Types.REAL : Types.FLOAT;`?

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 9 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:122]: ahhh interesting.. that makes sense. Should we somehow keep track of the `Fields` list that the server returns then to make sure we're casting to the expected type?

We have this strange dance here: of Server

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 10 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:116]: Yeah I wasn't too sure about how to deal with `NullVector`... I honestly don't even really understand what the purpose of such a vector is.

In regular vectors, we set nulls by simply not setting anything on an index, so I just did a `assert true` as a sort of `NoOp`. Would welcome any feedback about this!

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 11 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:118]: Fair point!

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatementTest.java [hunk 14]
```diff
@@ -107,4 +151,19 @@ public void testUpdateQuery() throws SQLException {
       assertEquals(42, updated);
     }
   }
+
+  @Test
```
[the remark this answers is not in the document]
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatementTest.java:155]: I'm not very familiar with batched parameter updates but will look into it.

File: java/flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java (hunk 12 above)
Comment (aiguofer) [reply java/flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java:954]: I was just reorganizing this logic a bit but used the same comparison that was there. It does look like a VSR `equals` method does a deep comparison, and from my understanding of the purpose of this method what we want is a reference check. Happy to make the change!

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java (hunk 6 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:36]: Looks like you can just straight call https://arrow.apache.org/docs/java/reference/org/apache/arrow/vector/types/pojo/ArrowType.Int.html#getIsSigned--

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java (hunk 7 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:60]: Yes (or alternatively ((ArrowType.FloatingPoint) type).getBitWidth() == 32 ? Types.REAL : Types.DOUBLE;

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 9 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:122]: Yes, it'd be good to keep track of the expected arrow type.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 10 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:116]: I guess we should evaluate if the incoming value is a null and throw an error if not since it'd be an invalid conversion.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java (hunk 5 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java:58]: I think it makes sense!

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java (hunk 4 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java:428]: ahhh interesting, I see in the Example that everything happens in the callback instead. This is a bit of an unrelated discussion but why does this happen in a callback? Is it just due to the nature of bidirectional streams?

Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java:428]: Yes, that's correct. When this RPC is received the server won't have all the parameter sets and shouldn't block the RPC handler thread waiting for and consuming them. It instead lets the implementer provide a callback that describes how to process each parameter set and does that work asynchronously.

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/MockFlightSqlProducer.java:428]: Awesome thanks! that makes sense. Learning more and more about gRPC :)

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 9 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:122]: Hmm lol ok nvm, the `Field` list we have here already IS the one returned from the server.

> a user is allowed to bind to a different type that the server expects and the driver is supposed to do the conversion behind-the-scenes

Interesting... so does that mean we need to be a whole lot smarter about casting the `TypedValue` to a Java type? Doesn't Avatica already take care of this for us?

I added that exception handler in case the casting when setting the value failed at least there would be a useful error, but I wouldn't expect to hit that case since the AvaticaParameter should already specify and handle the expected type.

Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java:122]: Avatica might handle this -- haven't tried it.

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java]: After digging a bit, it looks like Avatica does not really do any verification that the obect that is set by the user is compatible with type defined for the `AvaticaParameter`. This likely means we'll need more complex type conversion/validation so I refactored to use a `ArrowType.ArrowTypeVisitor` pattern for both generating the `AvaticaParameter` and for binding the parameter value to a Vector.

This helps us accomplish a couple of things:
- Ensure all Arrow types are covered
- Keep all conversion logic between AvaticaParameters/TypedValues and Arrow in the same class (one class per ArrowType)

For the purpose of this PR, I think we should just assume the user is setting the correct type and simply throw an error if we can't cast correctly. This conversion logic can easily be improved over time as needed.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 10 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java]: This is now handled in the `NullAvaticaParameterConverter`

File: java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatementTest.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatementTest.java:155]: Dug into it a bit. I had to implement `executeBatch`. Will add test in a follow up.

File: java/flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java (hunk 12 above)
Comment (aiguofer) [reply java/flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java]: Changed to ref equality.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 9 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java]: This is fine for me. I'd suggest we raise an issue to add mismatched user parameter -> Flight server type conversion

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java (hunk 3 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowToJdbcUtils.java]: I found that we already provide `SqlTypes.getSqlTypeIdFromArrowType` to convert an Arrow type to a JDBC type. Avatica also provides a mapping of JDBC types to Java classes. I removed the new custom logic and replaced it with:

```
    final int jdbcType = SqlTypes.getSqlTypeIdFromArrowType(arrowType);
    final String className = SqlType.valueOf(jdbcType).clazz.getCanonicalName();
```

See `BaseAvaticaParameterConverter`.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java (hunk 9 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java]: Yeah right now I have this:

```
    } catch (ClassCastException e) {
      throw new RuntimeException(String.format("Value of type %s is not compatible with Arrow type %s",
              typedValue.type, vector.getField().getType()));
    }
```

Happy to change the exception type or message.

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/TypedValueBinder.java]: I reworded this a little. See `AvaticaParameterBinder.bind(vector, typedVale, index)`

**Comment by aiguofer** [comment]
I refactored this quite a bit to put Arrow <-> Avatica conversions in the same class for each Arrow type. This should help ensure we do this correctly for all Arrow types.

Currently, testing is pretty basic and we're missing conversions for complex types, but I think it's a pretty good starting point to implement the rest.

I'm not sure why the one test failed and can't figure out how to re-run it.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/DateAvaticaParameterConverter.java [hunk 15]
```diff
@@ -35,12 +35,12 @@ public DateAvaticaParameterConverter(ArrowType.Date type) {
 
   @Override
   public boolean bindParameter(FieldVector vector, TypedValue typedValue, int index) {
-    Object value = typedValue.toLocal();
+    int value = (int) typedValue.toLocal();
```
Comment (jduo) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/DateAvaticaParameterConverter.java:38]: This doesn't seem right? Wouldn't we expect these types to be submitted as Date objects from the user?

Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/DateAvaticaParameterConverter.java:38]: Avatica converts all values internally to a more efficient type. They provide a conversion matrix: https://calcite.apache.org/avatica/javadocAggregate/org/apache/calcite/avatica/remote/TypedValue.html

From digging into the code, the matrix doesn't always seem correct, but looking at the `toLocal` code provides a pretty good representation of how different objects are handled. There's also a `jdbc` representation, but that converts objects back to specific types, which seemed redundant since we're converting to Arrow types. 

In some cases (mainly numeric types) I chose to ignore the `toLocal` method and do the conversion myself.

**Comment by aiguofer** [comment]
@lidavidm @jduo Hey all, I've spent a lot of time on this PR. It's a little frustrating that a PR that started well after mine has merged and now I have to deal with merge conflicts while mine still hasn't been thoroughly reviewed. We need this for one of our partner integrations and there's still been no movement on this. Could I at least get some eyes on this?

**Comment by lidavidm** [comment]
@aiguofer sorry about that - I'll give this a review over the weekend once Github is working again.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/AvaticaParameterConverter.java [hunk 16]
```diff
@@ -0,0 +1,42 @@
...
+ * Arrow.
+ */
+public interface AvaticaParameterConverter {
+
+  /**
+   * Bind a TypedValue to a FieldVector at the given index.
+   *
+   * @param vector FieldVector that the parameter should be bound to.
+   * @param typedValue TypedValue to bind as a parameter.
+   * @param index Vector index that the TypedValue should be bound to.
```
Comment (lidavidm) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/AvaticaParameterConverter.java:36]: 0-index, right? (I ask because JDBC is often 1-indexed)

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/DateAvaticaParameterConverter.java (hunk 15 above)
Comment (jduo) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/DateAvaticaParameterConverter.java:38]: Sounds good to me.

**Comment by jduo** [comment]
> @lidavidm @jduo Hey all, I've spent a lot of time on this PR. It's a little frustrating that a PR that started well after mine has merged and now I have to deal with merge conflicts while mine still hasn't been thoroughly reviewed. We need this for one of our partner integrations and there's still been no movement on this. Could I at least get some eyes on this?

Hi @aiguofer . It looks good. I didn't have additional comments.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/BinaryAvaticaParameterConverter.java [hunk 17]
```diff
@@ -0,0 +1,49 @@
...
+ * AvaticaParameterConverter for Binary Arrow types.
+ */
+public class BinaryAvaticaParameterConverter extends BaseAvaticaParameterConverter {
+
+  public BinaryAvaticaParameterConverter(ArrowType.Binary type) {
+  }
+
+  @Override
+  public boolean bindParameter(FieldVector vector, TypedValue typedValue, int index) {
+    byte[] value = (byte[]) typedValue.toJdbc(null);
```
Comment (lidavidm) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/BinaryAvaticaParameterConverter.java:37]: Do we need to handle `value == null`? Or in general how does Avatica handle null bind parameters?

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/TimestampAvaticaParameterConverter.java [hunk 18]
```diff
@@ -0,0 +1,78 @@
...
+ * AvaticaParameterConverter for Timestamp Arrow types.
+ */
+public class TimestampAvaticaParameterConverter extends BaseAvaticaParameterConverter {
+
+  public TimestampAvaticaParameterConverter(ArrowType.Timestamp type) {
+  }
+
+  @Override
+  public boolean bindParameter(FieldVector vector, TypedValue typedValue, int index) {
+    // FIXME: how should we handle TZ? Do we need to convert the value to the TZ on the vector?
```
Comment (lidavidm) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/TimestampAvaticaParameterConverter.java:44]: The timezone on the vector is purely for display; the underlying value is always UTC in Arrow.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/AvaticaParameterBinder.java [hunk 19]
```diff
@@ -0,0 +1,233 @@
...
+   * Bind a TypedValue to the given index on the FieldVctor.
+   *
+   * @param vector     FieldVector to bind to.
+   * @param typedValue TypedValue to bind to the vector.
+   * @param index      Vector index to bind the value at.
+   */
+  private void bind(FieldVector vector, TypedValue typedValue, int index) {
+    try {
+      if (!vector.getField().getType().accept(new BinderVisitor(vector, typedValue, index))) {
+        throw new RuntimeException(
```
Comment (lidavidm) [inline java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/AvaticaParameterBinder.java:106]: nit: is there a more appropriate exception than RuntimeException?

**Review by lidavidm — APPROVED** [review]
None of my comments are critical - if you want to just file an issue to track them that would be fine

> We currently naively cast the TypedValue values assuming users set the type correctly. If this cast fails, we raise an exception letting the user know that the cast is not supported. This could be improved in subsequent PRs to do smarter conversions from other types.

We can file a followup for this too.

> We currently don't provide conversions for complex types such as List, Map, Struct, Union, Interval, and Duration. The stubs are there so they can be implemented as needed.

Ditto.

> Tests for specific types have not been implemented. I'm not very familiar with a lot of these JDBC types so it's hard to implement rigorous tets.

I would be in favor of trying to set up integration suites with systems that depend on the driver, in the same way we have integration tests with Spark and Pandas (two other projects that heavily depend on Arrow). But this is also something we can defer.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/AvaticaParameterConverter.java (hunk 16 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/AvaticaParameterConverter.java:36]: Correct! that would be the index on the Arrow vector. I'll add to the docstring just to be more clear

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/BinaryAvaticaParameterConverter.java (hunk 17 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/BinaryAvaticaParameterConverter.java:37]: Ohhh good catch. `Avatica` doesn't really do anything special for `null` values so it just returns `null`.

For example:

```
  public Object toJdbc(Calendar calendar) {
    return this.value == null ? null : serialToJdbc(this.type, this.componentType, this.value, calendar);
  }
```

I guess we need to call `setNull` if the value is null?

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/TimestampAvaticaParameterConverter.java (hunk 18 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/TimestampAvaticaParameterConverter.java:44]: cool that's what I was thinking. At this point Avatica has already converted to UTC so that's perfect.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/AvaticaParameterBinder.java (hunk 19 above)
Comment (aiguofer) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/AvaticaParameterBinder.java:106]: I was thinking some type of `NotImplementedException` would be ideal but I couldn't find an exception like that. Any thoughts on an alternative? `UnsupportedOperationException` seem to imply that it will not be supported, which might not be what we want.

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/BinaryAvaticaParameterConverter.java (hunk 17 above)
Comment (lidavidm) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/BinaryAvaticaParameterConverter.java:37]: Yeah - do you want to handle that here, or do you want to file a follow-up for now?

Comment (lidavidm) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/converter/impl/BinaryAvaticaParameterConverter.java:37]: Actually, let's just get this in before something else conflicts with it

File: java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/AvaticaParameterBinder.java (hunk 19 above)
Comment (lidavidm) [reply java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/AvaticaParameterBinder.java:106]: IMO `UnsupportedOperationException` is fine for this sort of thing

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
I filed a general followups issue at #38585 

Thanks again @aiguofer!

**Comment by aiguofer** [comment]
> I filed a general followups issue at #38585 
> 
> Thanks again @aiguofer!

Perfect sounds good! I can work on a few of those soon after this!
