### PR TITLE
GH-35190: [Go] Correctly handle null values in CSV reader

### LINKED ISSUE #35190: [Go] CSV Reader fails to read empty values as null
### Describe the bug, including details regarding any error messages, version, and platform.

When the CSV reader is passed empty string as one of the possible null values, it still returns this as an empty string rather than null, even when used with the `WithNullReader(stringsCanBeNull=true)` option. 

### Component(s)

Go

### PR DESCRIPTION
**Pull request by hermanschaaf**
The way the CSV reader handles null values currently makes it impossible for empty strings to be interpreted as null, even when this is explicitly enabled through the `csv.WithNullReader(stringsCanBeNull: true, "", "NULL", "null")` option. This change fixes this.
* Closes: #35190

### CODE REVIEW

File: go/arrow/csv/reader.go [hunk 1]
```diff
@@ -767,7 +767,7 @@ func (r *Reader) parseList(field array.Builder, str string) {
 
 func (r *Reader) parseBinaryType(field array.Builder, str string) {
 	// specialize the implementation when we know we cannot have nulls
-	if str != "" && r.isNull(str) {
+	if r.isNull(str) {
 		field.AppendNull()
 		return
 	}
```
Comment (zeroshade) [inline go/arrow/csv/reader.go:773]: Do we currently have a test that verifies you can still get an empty string if it is not in the list of Null values? / `stringsCanBeNull` == `false` ?

Comment (hermanschaaf) [reply go/arrow/csv/reader.go:773]: I think not, but happy to add one here

Comment (hermanschaaf) [reply go/arrow/csv/reader.go:773]: Added two new test cases for this

**Review by zeroshade — APPROVED** [review]
