### PR TITLE
GH-38049: [R] Prevent `on_rosetta()` from warning

### LINKED ISSUE #38049: [R] Rosetta detector has output when running on x86
### Describe the bug, including details regarding any error messages, version, and platform.

In #37777 we added a detector that checks if Rosetta translation is being used. It turns out this will produce warnings on x86 systems. We should fix that.

```
sysctl: unknown oid 'sysctl.proc_translated'
...
Warning message:
In system("sysctl -n sysctl.proc_translated", intern = TRUE) :
  running command 'sysctl -n sysctl.proc_translated' had status 1
```

### Component(s)

R

### PR DESCRIPTION
**Pull request by jonkeane**
### Rationale for this change

Stop extraneous warnings.

### What changes are included in this PR?

Prevent warning when detecting translation, but on x86

### Are these changes tested?

Yes

### Are there any user-facing changes?

Yes, there will be fewer extraneous warnings.
* Closes: #38049

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-install-local

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-install-local

File: r/tests/testthat/test-arrow-pacakge.R [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+
+test_that("on_rosetta() does not warn", {
+  # There is no warning
+  expect_warning(on_rosetta(), NA)
```
Comment (jonkeane) [inline r/tests/testthat/test-arrow-pacakge.R:20]: I wasn't actually able to find a way to test that the console output from stderr doesn't show here. I tried both `expect_output(..., NA)` and `expect_silent(...)` as well as capturing the output with `capture_output(...)` and `capture.output(...)` but none of those seemed to actually capture the console warning I'm seeing. This is _probably_ fine. I've tested locally and the output is supressed on my system.

**Review by paleolimbot — APPROVED** [review]
Thank you!

**Comment by jonkeane** [comment]
Thanks for merging.

For posterity only:

> (It floated in last night that the `system("...", ignore.stdout = TRUE) == 1` might be sufficient if the return code is what's causing the warning. Either way!)

We actually do need to inter to get the output. `system("...", ignore.stdout = TRUE) == 1 ` will be 1 if you're on x86 (because the command failed to find `sysctl.proc_translated`), but 0 on an M* processor _regardless if you're under emulation or not_ since the command succeeded at finding the property and printing 0 or 1 to the console depending on if you're in emulation or not. There might be a cleaner `system2` incantation, but I didn't want to drift too far from what was there.

**Comment by jonkeane** [comment]
And, actually writting that out now made me realize I had introduced a bug resolved in #38083 I tested this code on x86 but not M*
