### PR TITLE
GH-37884: [Swift] Allow reading of unaligned FlatBuffers buffers

### LINKED ISSUE #37884: [Swift][FlightRPC] Processing valid utf-8 lead to misaligned error
### Describe the bug, including details regarding any error messages, version, and platform.

**Bug**

During FlightClient.doGet call, processing utf-8 generated from the flight server using [arrow-rs](https://github.com/apache/arrow-rs) leads to misaligned error.

**Details**

It's a simple `testString` in a single `TEST` column.
The same test was made on the python flight server, and no errors were raised. 

**Error Messages**

```sh
Swift/UnsafeRawPointer.swift:1203: Fatal error: load from misaligned raw pointer
```

**System details**
- Using Xcode Version 15.0 beta 8 (15A5229m)
- Building for Apple Vision Pro Simulator
- Swift-Driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1)

### Component(s)

Swift

### PR DESCRIPTION
**Pull request by abandy**
The PR enables the swift readers to read from unaligned buffers (fix for issue: 37884)

Enabling unaligned buffers incurs a performance penalty so the developer will need to consider this when enabling this feature.  

It is not currently possible to recover from a buffer unaligned error as this error is a fatalError so trying aligned and then falling back to unaligned is not an option.  Also, FlatBuffers has a verifier that should be able to catch this error but currently it seems to fail on both aligned and unaligned buffers (I tried verifying the example python server get return value but verification fails even though the buffers are able to be read successfully)
* Closes: #37884

### CODE REVIEW

**Comment by abandy** [comment]
@kou Please review when you get a chance.

File: swift/Arrow/Package.swift [hunk 1]
```diff
@@ -32,7 +32,7 @@ let package = Package(
             targets: ["Arrow"]),
     ],
     dependencies: [
-        .package(url: "https://github.com/google/flatbuffers.git", from: "23.3.3")
+        .package(url: "https://github.com/google/flatbuffers.git", branch: "master")
```
Comment (kou) [inline swift/Arrow/Package.swift:35]: Could you add a comment why we need to use `master` for now and when we can specify a tag again?

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
Done!

**Comment by mgrazianoc** [comment]
Nice to hear about that!!!
