### PR TITLE
GH-14909: [Java]  Prevent potential memory leak of ListSubfieldEncoder and StructSubfieldEncoder

### LINKED ISSUE #14909: [Java] ListSubfieldEncoder and StructSubfieldEncoder may leak memory when exception thrown
### Describe the bug, including details regarding any error messages, version, and platform.

This is a follow up of https://github.com/apache/arrow/issues/14890. `ListSubfieldEncoder` and `StructSubfieldEncoder` may leak memory as well.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by gf2121**
* Closes: #14909

### CODE REVIEW

File: java/vector/src/test/java/org/apache/arrow/vector/TestDictionaryVector.java [hunk 1]
```diff
@@ -916,6 +916,132 @@ public void testNoMemoryLeak() {
...
+      writeListVector(dictWriter, new int[]{10});
+      dictionaryVector.setValueCount(1);
+
+      Dictionary dictionary = new Dictionary(dictionaryVector, new DictionaryEncoding(1L, false, null));
+      ListSubfieldEncoder encoder = new ListSubfieldEncoder(dictionary, allocator);
+
+      try (final ListVector encoded = (ListVector) encoder.encodeListSubField(vector)) {
+        fail("There should be an exception when encoding");
+      } catch (Exception e) {
+        assertEquals("Dictionary encoding not defined for value:" + 20, e.getMessage());
```
Comment (lidavidm) [inline java/vector/src/test/java/org/apache/arrow/vector/TestDictionaryVector.java:941]: nit: why concat here, when the string is fully hardcoded below?

**Review by lidavidm — APPROVED** [review]
