### PR TITLE
GH-35450: [C++] Return error when `RecordBatch::ToStructArray` called with mismatched column lengths

### LINKED ISSUE #35450: [C++] RecordBatch::ToStructArray does not respect the length of the record batch if it differs from the length of the child arrays
### Describe the bug, including details regarding any error messages, version, and platform.

I'm not entirely certain if it's legal for a record batch to be shorter than its child arrays.  However, if it is, then ToStructArray is not working properly.

```
TEST_F(TestRecordBatch, SlicedToStructArray) {
  std::shared_ptr<Array> x_arr = ArrayFromJSON(int64(), "[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]");
  auto batch = RecordBatch::Make(::arrow::schema({field("x", int64())}), 5, {x_arr});
  ASSERT_EQ(batch->num_rows(), 5); // This works
  ASSERT_OK_AND_ASSIGN(auto struct_array, batch->ToStructArray());
  ASSERT_EQ(struct_array->length(), 5); // This fails
}
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by benibus**
### Rationale for this change

If a `RecordBatch` is created with column lengths that don't match the provided `num_rows` (technically invalid), then there are some circumstances where `ToStructArray` will successfully return an array whose length doesn't match `num_rows`. Instead, we should return an error.

### What changes are included in this PR?

* Add a small validation check to `ToStructArray` before constructing the output array
* Add a test

### Are these changes tested?

Yes (tests are included)

### Are there any user-facing changes?

No

* Closes: #35450

### CODE REVIEW

File: cpp/src/arrow/record_batch.cc [hunk 1]
```diff
@@ -301,12 +318,8 @@ namespace {
 
 Status ValidateBatch(const RecordBatch& batch, bool full_validation) {
   for (int i = 0; i < batch.num_columns(); ++i) {
+    RETURN_NOT_OK(ValidateColumnLength(batch, i));
```
Comment (wgtmac) [inline cpp/src/arrow/record_batch.cc:321]: nit: passing `array` created in line 304 to `ValidateColumnLength` to avoid creating shared_ptr twice.

**Review by pitrou — APPROVED** [review]
